const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 3: Enterprise Network Design";

const questions = [
    // --- Data Center Advanced & Virtualization (20 Qns) ---
    { q: "Which Data Center cooling technique involves raising the entire floor to pump cold air upwards through perforated tiles into the server racks?", o: ["Liquid Cooling", "Hot Aisle Containment", "Raised Floor Cooling", "Evaporative Cooling"], a: "Raised Floor Cooling", e: "Raised floors are a traditional data center design allowing massive cold air distribution from below." },
    { q: "In a heavily virtualized Data Center, what is a 'Hypervisor'?", o: ["A high-speed router.", "A software layer that sits between the physical hardware and the Virtual Machines, allocating CPU and RAM to each VM.", "A physical security guard.", "A type of firewall."], a: "A software layer that sits between the physical hardware and the Virtual Machines, allocating CPU and RAM to each VM.", e: "The hypervisor (like ESXi or Hyper-V) is the engine that makes virtualization possible." },
    { q: "What is the difference between a Type 1 and Type 2 Hypervisor?", o: ["Type 1 runs on Windows; Type 2 runs on Linux.", "Type 1 runs directly on the bare-metal hardware; Type 2 runs as an application inside an existing Host OS.", "Type 1 is slower than Type 2.", "Type 1 is only for cloud environments."], a: "Type 1 runs directly on the bare-metal hardware; Type 2 runs as an application inside an existing Host OS.", e: "Type 1 (Bare-Metal) is heavily used in enterprise Data Centers for maximum performance." },
    { q: "Why is 'VM Sprawl' a significant management problem in Data Centers?", o: ["VMs take up too much physical space in the racks.", "Because creating a VM is so easy, administrators create thousands of them, eventually losing track of what they do, consuming all resources.", "VMs constantly delete their own data.", "VMs automatically change their IP addresses."], a: "Because creating a VM is so easy, administrators create thousands of them, eventually losing track of what they do, consuming all resources.", e: "Unmanaged virtual growth leads to wasted RAM, CPU, and storage." },
    { q: "Which of the following describes 'vMotion' or 'Live Migration' in a Data Center?", o: ["Moving physical servers with a forklift.", "Moving a running Virtual Machine from one physical server to another without any downtime or dropping user connections.", "Deleting old Virtual Machines.", "Restarting the hypervisor."], a: "Moving a running Virtual Machine from one physical server to another without any downtime or dropping user connections.", e: "Live migration is a core feature for Tier 3 concurrent maintainability." },
    { q: "What is 'Overprovisioning' in a virtualized Data Center?", o: ["Buying too many physical servers.", "Assigning more total virtual CPUs to the VMs than actually physically exist on the host, assuming they won't all hit 100% usage at once.", "Using too much electricity.", "Assigning duplicate IP addresses."], a: "Assigning more total virtual CPUs to the VMs than actually physically exist on the host, assuming they won't all hit 100% usage at once.", e: "Overprovisioning maximizes hardware efficiency but risks crippling slow-downs if all VMs spike simultaneously." },
    { q: "Which Storage Area Network (SAN) protocol uses standard Ethernet cables rather than expensive dedicated fiber optics?", o: ["Fibre Channel (FC)", "iSCSI (Internet Small Computer Systems Interface)", "SATA", "PCIe"], a: "iSCSI (Internet Small Computer Systems Interface)", e: "iSCSI encapsulates SCSI storage commands inside standard IP/Ethernet packets." },
    { q: "What does 'Fibre Channel over Ethernet (FCoE)' attempt to solve?", o: ["The need for routers.", "The need for two separate networks (one for LAN data, one for SAN storage) by combining them onto a single Ethernet infrastructure.", "The high cost of wireless networks.", "The limitations of IPv4."], a: "The need for two separate networks (one for LAN data, one for SAN storage) by combining them onto a single Ethernet infrastructure.", e: "FCoE converges storage and data networks to save massive amounts of cabling." },
    { q: "In a Tier 4 Data Center, 'Fault Tolerance' means:", o: ["The system warns you before it crashes.", "The infrastructure has active-active redundant components, so a failure goes completely unnoticed by the servers.", "The data center has no physical doors.", "The data center only uses solar power."], a: "The infrastructure has active-active redundant components, so a failure goes completely unnoticed by the servers.", e: "Fault tolerance implies seamless, instant takeover by backup components." },
    { q: "What is a 'CRAC' unit in a Data Center?", o: ["Computer Room Air Conditioning unit, responsible for maintaining precise temperature and humidity.", "A device that routes BGP traffic.", "A backup generator.", "A physical security biometric scanner."], a: "Computer Room Air Conditioning unit, responsible for maintaining precise temperature and humidity.", e: "CRACs are specialized, industrial-grade cooling systems." },
    { q: "Why is 'Humidity Control' just as important as temperature in a Data Center?", o: ["High humidity prevents hackers.", "Low humidity causes static electricity (ESD) which can fry motherboards; high humidity causes condensation and short circuits.", "Humidity makes the servers run faster.", "Servers need water to operate."], a: "Low humidity causes static electricity (ESD) which can fry motherboards; high humidity causes condensation and short circuits.", e: "Precise humidity (usually 40-60%) prevents both static sparks and water damage." },
    { q: "A company decides to lease rack space in a massive facility shared by 50 other companies. What is this facility called?", o: ["Enterprise Data Center", "Colocation (Colo) Facility", "Hybrid Cloud", "Personal LAN"], a: "Colocation (Colo) Facility", e: "Colo allows sharing the extreme overhead costs of the building, security, and power." },
    { q: "What does an 'Automatic Transfer Switch' (ATS) do?", o: ["It moves data between VLANs.", "It instantly shifts the server's power source from the dead city grid to the spinning backup generator.", "It changes the IP address.", "It blocks unauthorized access."], a: "It instantly shifts the server's power source from the dead city grid to the spinning backup generator.", e: "The ATS is the critical electrical component that senses power loss and throws the switch to backup power." },
    { q: "Which Data Center topology connects every Top-of-Rack (Leaf) switch directly to every Core (Spine) switch, ensuring exactly one hop between any two racks?", o: ["Hub and Spoke", "Ring Topology", "Spine-and-Leaf", "Bus Topology"], a: "Spine-and-Leaf", e: "Spine-Leaf is the modern standard for fast, predictable Data Center traffic." },
    { q: "Why do modern Data Centers heavily prioritize 'East-West' traffic over 'North-South' traffic?", o: ["Because internet traffic is decreasing.", "Because modern microservices, database lookups, and VM migrations generate massive amounts of server-to-server traffic internally.", "Because servers only face the East.", "Because routers are too slow."], a: "Because modern microservices, database lookups, and VM migrations generate massive amounts of server-to-server traffic internally.", e: "Traditional networks were built for users hitting the internet (North-South). Modern apps talk to each other constantly (East-West)." },
    { q: "Which component prevents 'Tailgating' in a secure Data Center?", o: ["Firewall", "Man-Trap (Access Control Vestibule)", "IPS (Intrusion Prevention System)", "CCTV Camera"], a: "Man-Trap (Access Control Vestibule)", e: "A Man-Trap ensures only one person can pass through a set of doors at a time." },
    { q: "What is 'Micro-Segmentation' in a Data Center?", o: ["Cutting cables into small pieces.", "Using software (like VMware NSX) to place a firewall around every single Virtual Machine, isolating them even if they are on the same VLAN.", "Shrinking the size of the hard drives.", "Dividing the room into smaller cubes."], a: "Using software (like VMware NSX) to place a firewall around every single Virtual Machine, isolating them even if they are on the same VLAN.", e: "Micro-segmentation provides Zero Trust security deep inside the data center." },
    { q: "Which protocol is heavily used to manage and monitor the hardware health (fan speeds, temperatures) of Data Center servers remotely?", o: ["BGP", "IPMI (Intelligent Platform Management Interface)", "RIP", "STP"], a: "IPMI (Intelligent Platform Management Interface)", e: "IPMI allows out-of-band management, letting admins reboot a server even if the OS has crashed." },
    { q: "What is the primary risk of relying on a single 'Tier 1' Data Center?", o: ["It uses too much electricity.", "Any maintenance or power failure guarantees a complete shutdown of operations.", "It forces you to use IPv6.", "It has too many generators."], a: "Any maintenance or power failure guarantees a complete shutdown of operations.", e: "Tier 1 has zero redundancy, making downtime inevitable." },
    { q: "Which Data Center metric defines 'Power Usage Effectiveness' (PUE)?", o: ["The ratio of total facility energy used compared to the energy strictly used by the IT equipment.", "The speed of the routers.", "The number of hours the generator can run.", "The amount of water used for cooling."], a: "The ratio of total facility energy used compared to the energy strictly used by the IT equipment.", e: "A PUE near 1.0 means almost all power is going directly to the servers, not wasted on cooling." },

    // --- Complex Scenarios: Campus vs WAN vs DC (20 Qns) ---
    { q: "Scenario: A hospital campus uses a flat Layer 2 network. IP Phones frequently drop calls. What is the most likely architectural cause?", o: ["The WAN connection is too slow.", "Massive broadcast storms are overwhelming the switch CPUs, causing real-time VoIP packets to drop.", "They are using fiber optics instead of copper.", "The data center is too cold."], a: "Massive broadcast storms are overwhelming the switch CPUs, causing real-time VoIP packets to drop.", e: "Without a Distribution layer to block broadcasts, flat networks ruin real-time traffic." },
    { q: "Scenario: A bank's ATM in a rural town loses its primary MPLS connection. It instantly switches to a 4G LTE cellular connection. This is an example of:", o: ["A Hub-and-Spoke failure.", "WAN Redundancy and Failover.", "Campus Network routing.", "Data Center virtualization."], a: "WAN Redundancy and Failover.", e: "Using diverse physical mediums (fiber and cellular) is the ultimate WAN backup strategy." },
    { q: "Scenario: An engineer notices that traffic between two VMs on the same physical server is traveling all the way up to the Core switch and back down. What should be configured?", o: ["A new WAN link.", "A Virtual Switch (vSwitch) inside the hypervisor to route the traffic internally.", "A BGP peering session.", "A biometric lock."], a: "A Virtual Switch (vSwitch) inside the hypervisor to route the traffic internally.", e: "A vSwitch keeps local VM traffic entirely within the physical server, saving network bandwidth." },
    { q: "Scenario: A university wants to add a new Chemistry building. With a proper Hierarchical Campus Design, what is the process?", o: ["Tear down the Core routers and buy new ones.", "Simply add a new Access and Distribution block for the building and uplink it to the existing Core.", "Convert the entire campus to a WAN.", "Delete the guest VLAN."], a: "Simply add a new Access and Distribution block for the building and uplink it to the existing Core.", e: "This is the essence of 'Scalability' provided by the hierarchical model." },
    { q: "Which technology would a company use to securely route internal OSPF traffic across a public Internet WAN link?", o: ["A physical leased line.", "A GRE (Generic Routing Encapsulation) Tunnel protected by IPsec.", "A VLAN tag.", "A switch stack."], a: "A GRE (Generic Routing Encapsulation) Tunnel protected by IPsec.", e: "GRE can encapsulate routing protocols (which normal IPsec cannot), making the internet look like a private link." },
    { q: "In a 'Hub-and-Spoke' WAN, how does the Hub site represent a 'Single Point of Failure'?", o: ["If a spoke goes down, the hub goes down.", "If the Hub router fails, none of the branch offices can communicate with each other or the internet.", "The Hub cannot use wireless.", "The Hub uses too much electricity."], a: "If the Hub router fails, none of the branch offices can communicate with each other or the internet.", e: "Because all traffic routes through the hub, its death paralyzes the entire company." },
    { q: "Why might an organization prefer a 'Partial Mesh' WAN over a 'Hub-and-Spoke'?", o: ["It is cheaper.", "It provides direct, redundant links between the most critical branch offices without the extreme cost of a Full Mesh.", "It requires fewer IP addresses.", "It uses less power."], a: "It provides direct, redundant links between the most critical branch offices without the extreme cost of a Full Mesh.", e: "Partial mesh is the perfect middle-ground between extreme cost and extreme vulnerability." },
    { q: "Which Data Center approach eliminates the massive cost of building a physical facility entirely?", o: ["Building a Tier 4 facility.", "Migrating all infrastructure to a Public Cloud (like AWS or Azure) using an IaaS model.", "Using Colocation.", "Using a Collapsed Core."], a: "Migrating all infrastructure to a Public Cloud (like AWS or Azure) using an IaaS model.", e: "Cloud allows companies to rent computing power on-demand, shifting CapEx to OpEx." },
    { q: "Scenario: An administrator accidentally unplugs the power cord from a critical Database server in a Tier 3 Data Center. What happens?", o: ["The server crashes.", "The server stays online because it has dual power supplies connected to two independent electrical paths.", "The UPS catches fire.", "The generator shuts down."], a: "The server stays online because it has dual power supplies connected to two independent electrical paths.", e: "Tier 3 provides concurrent maintainability via redundant paths directly into the server hardware." },
    { q: "What is 'VLAN Trunking'?", o: ["Connecting a router to the internet.", "Using a single physical cable (like an 802.1q trunk) to carry traffic for multiple different VLANs between switches.", "Storing servers in a physical trunk.", "Deleting old VLANs."], a: "Using a single physical cable (like an 802.1q trunk) to carry traffic for multiple different VLANs between switches.", e: "Trunks prevent you from needing a separate physical cable for every single VLAN." },
    { q: "Which Campus layer is most heavily impacted if a massive 'Broadcast Storm' occurs?", o: ["The WAN Edge.", "The Access and Distribution layers, as their CPU gets overwhelmed processing the broadcasts.", "The Data Center cooling.", "The UPS systems."], a: "The Access and Distribution layers, as their CPU gets overwhelmed processing the broadcasts.", e: "Switches must process broadcasts in software, rapidly hitting 100% CPU and dropping legitimate traffic." },
    { q: "What does 'SD-WAN' provide that traditional 'MPLS' does not?", o: ["Guaranteed QoS for voice.", "Centralized, software-defined control that dynamically routes traffic over the best available link (Internet or MPLS) in real-time.", "A physical fiber optic cable.", "Higher costs."], a: "Centralized, software-defined control that dynamically routes traffic over the best available link (Internet or MPLS) in real-time.", e: "SD-WAN is agile and application-aware, whereas MPLS is a static, rigid pipe." },
    { q: "In a Campus network, why is 'PoE' (Power over Ethernet) a critical requirement at the Access Layer?", o: ["It powers the Core routers.", "It eliminates the need to run separate electrical wall outlets for thousands of IP Phones and Wi-Fi Access Points.", "It increases internet speed.", "It encrypts the data."], a: "It eliminates the need to run separate electrical wall outlets for thousands of IP Phones and Wi-Fi Access Points.", e: "PoE saves millions in electrical contracting by delivering DC power over the network cable." },
    { q: "Which physical medium is required for WAN links that cross oceans?", o: ["CAT6 Copper.", "Submarine Fiber Optic cables.", "Microwave links.", "Wi-Fi 6."], a: "Submarine Fiber Optic cables.", e: "Only fiber optics have the range and bandwidth necessary for intercontinental traffic." },
    { q: "What is the primary advantage of a 'Storage Area Network' (SAN) over 'Direct Attached Storage' (DAS)?", o: ["DAS is faster.", "A SAN allows multiple servers to share a massive pool of highly redundant storage, rather than storage being trapped inside one specific server.", "SAN uses USB cables.", "SAN is free."], a: "A SAN allows multiple servers to share a massive pool of highly redundant storage, rather than storage being trapped inside one specific server.", e: "SAN centralizes storage for the entire data center, enabling features like vMotion." },
    { q: "Scenario: A company requires 99.999% uptime. They deploy a Full Mesh WAN, a Tier 4 Data Center, and dual Core routers. What design objective are they prioritizing?", o: ["Cost Efficiency", "Flexibility", "Extreme Reliability and Availability", "Physical Security"], a: "Extreme Reliability and Availability", e: "This level of redundancy sacrifices all cost efficiency to ensure the network never dies." },
    { q: "What happens to network traffic when a 'Router on a Stick' design hits its maximum physical interface bandwidth limit?", o: ["The router encrypts the data.", "Traffic is severely delayed or dropped, causing massive latency across all VLANs.", "The switch takes over routing.", "The internet becomes faster."], a: "Traffic is severely delayed or dropped, causing massive latency across all VLANs.", e: "A single bottleneck chokes the entire network." },
    { q: "Why is 'Cable Management' strictly enforced in Data Centers?", o: ["To make it look pretty for visitors.", "To prevent thick 'spaghetti' cabling from blocking the cold air intake, which would cause servers to overheat and fail.", "To prevent hackers from seeing the cables.", "To reduce the cost of the cables."], a: "To prevent thick 'spaghetti' cabling from blocking the cold air intake, which would cause servers to overheat and fail.", e: "Blocked airflow is a massive hazard in high-density server racks." },
    { q: "Which Data Center technology allows a physical server to 'pretend' to be 5 different servers?", o: ["Containerization", "VLANs", "Virtualization (Hypervisor)", "RAID"], a: "Virtualization (Hypervisor)", e: "Hypervisors abstract the physical hardware." },
    { q: "In WAN design, what is a 'CPE' (Customer Premises Equipment)?", o: ["The ISP's core router in their building.", "The router, modem, or CSU/DSU located physically inside the customer's building.", "A satellite in space.", "A physical security camera."], a: "The router, modem, or CSU/DSU located physically inside the customer's building.", e: "CPE is the equipment the company actually touches and houses on-site." },

    // --- Enterprise Integration (20 Qns) ---
    { q: "When integrating a Campus Network with a Data Center, which connection requires the highest bandwidth?", o: ["Access to Distribution", "Distribution to Access", "Campus Core to Data Center Core", "WAN Edge to Internet"], a: "Campus Core to Data Center Core", e: "All internal traffic eventually flows to the Data Center for application access." },
    { q: "Why are 'Firewalls' placed between the Campus Core and the Data Center Core?", o: ["To speed up the traffic.", "To ensure that if a user's PC is infected with ransomware, the infection cannot easily spread into the critical servers.", "To stop internet traffic.", "To provide electrical power."], a: "To ensure that if a user's PC is infected with ransomware, the infection cannot easily spread into the critical servers.", e: "Internal firewalls prevent lateral movement of threats." },
    { q: "What is 'Dark Fiber' primarily used for?", o: ["Connecting a mouse to a PC.", "Creating private, ultra-high-speed point-to-point WAN links that the enterprise completely controls.", "Hiding data from the government.", "Providing Wi-Fi."], a: "Creating private, ultra-high-speed point-to-point WAN links that the enterprise completely controls.", e: "Dark fiber gives the enterprise raw, unmetered bandwidth." },
    { q: "Which WAN link type is considered the most 'Predictable' for real-time voice and video?", o: ["Internet VPN", "MPLS (Multiprotocol Label Switching)", "Cellular 4G", "Public Wi-Fi"], a: "MPLS (Multiprotocol Label Switching)", e: "MPLS offers strict Quality of Service (QoS) SLAs from the telecom provider." },
    { q: "What is a 'Metro Area Network' (MAN)?", o: ["A network that covers the entire globe.", "A network spanning a single city or metropolitan area, usually connecting multiple campuses.", "A network inside a single room.", "A network on a train."], a: "A network spanning a single city or metropolitan area, usually connecting multiple campuses.", e: "MANs are larger than a Campus but smaller than a global WAN." },
    { q: "Why do enterprise networks use 'Out-of-Band' (OOB) Management networks?", o: ["To listen to music.", "To provide a completely separate, dedicated physical network to manage routers and switches, so admins can reach them even if the main data network crashes.", "To increase the internet speed.", "To route guest traffic."], a: "To provide a completely separate, dedicated physical network to manage routers and switches, so admins can reach them even if the main data network crashes.", e: "OOB ensures you never lose control of the network during a catastrophic outage." },
    { q: "What is the primary role of an 'Edge Router'?", o: ["To connect servers together.", "To act as the absolute boundary between the trusted internal enterprise and the untrusted external internet/WAN.", "To provide PoE to phones.", "To run the hypervisor."], a: "To act as the absolute boundary between the trusted internal enterprise and the untrusted external internet/WAN.", e: "The Edge router handles BGP, NAT, and perimeter security." },
    { q: "If an enterprise migrates to 'Office 365', which WAN characteristic becomes the most critical?", o: ["Local SAN storage.", "Reliable, high-speed Internet connectivity, because the application is now entirely hosted in a Public Cloud.", "Adding more core switches.", "Building a new data center."], a: "Reliable, high-speed Internet connectivity, because the application is now entirely hosted in a Public Cloud.", e: "SaaS migration heavily shifts traffic from internal data centers to the public internet." },
    { q: "What does 'Active-Active' redundancy mean?", o: ["One router is off, waiting for the other to break.", "Both routers actively forward traffic simultaneously, providing both redundancy and doubled bandwidth (load balancing).", "The routers physically move around.", "Only one router has power."], a: "Both routers actively forward traffic simultaneously, providing both redundancy and doubled bandwidth (load balancing).", e: "Active-Active maximizes ROI by using all hardware at once." },
    { q: "What does 'Active-Passive' redundancy mean?", o: ["Both routers route traffic.", "One router handles all traffic while the other sits idle, wasting its potential bandwidth but ensuring an identical backup is ready.", "The network has no redundancy.", "The routers are unplugged."], a: "One router handles all traffic while the other sits idle, wasting its potential bandwidth but ensuring an identical backup is ready.", e: "Active-Passive is simpler to configure but wastes the standby hardware." },
    { q: "Why is 'Physical Redundancy' useless if you have 'Logical Spanning Tree Loops'?", o: ["Because spanning tree increases bandwidth.", "Because a logical loop will crash the network software (broadcast storm) regardless of how many physical cables you have.", "Because spanning tree physically cuts the cables.", "It is not useless."], a: "Because a logical loop will crash the network software (broadcast storm) regardless of how many physical cables you have.", e: "Logical software failures bypass physical hardware redundancy." },
    { q: "Which Data Center technology utilizes massive 'Arrays of Independent Disks' (RAID)?", o: ["Routers", "Storage Systems (SAN/NAS) to provide data redundancy and speed.", "Firewalls", "Access Points"], a: "Storage Systems (SAN/NAS) to provide data redundancy and speed.", e: "RAID ensures that if a hard drive dies, the data survives." },
    { q: "What is a 'Top-Level Domain' (TLD)?", o: ["The highest physical floor in a data center.", "The .com, .org, or .net part of a web address.", "The core switch in a campus.", "A WAN routing protocol."], a: "The .com, .org, or .net part of a web address.", e: "TLDs are managed by global DNS authorities." },
    { q: "Scenario: A company wants to merge Voice (Telephone) and Data onto the same Campus Network. What must be deployed?", o: ["Two separate physical cables.", "Voice VLANs and strict Quality of Service (QoS) to prioritize the voice packets.", "A new data center.", "Only fiber optic cables."], a: "Voice VLANs and strict Quality of Service (QoS) to prioritize the voice packets.", e: "Voice traffic is highly sensitive to delay; QoS ensures it gets priority over regular data." },
    { q: "What is the primary function of a 'Load Balancer' in an Enterprise Data Center?", o: ["To physically weigh the servers.", "To sit in front of the web servers and distribute incoming user requests evenly, preventing any single server from crashing under heavy traffic.", "To block hackers.", "To encrypt all traffic."], a: "To sit in front of the web servers and distribute incoming user requests evenly, preventing any single server from crashing under heavy traffic.", e: "Load balancers provide scale-out horizontal scalability." },
    { q: "Why is 'IPSec' heavily used in WAN topologies?", o: ["To speed up the internet.", "To encrypt data as it travels across untrusted networks like the public internet, ensuring Confidentiality and Integrity.", "To assign IP addresses.", "To route BGP packets."], a: "To encrypt data as it travels across untrusted networks like the public internet, ensuring Confidentiality and Integrity.", e: "IPSec provides the cryptographic foundation for VPNs." },
    { q: "Which topology connects every single Data Center rack directly to a massive central core, completely avoiding the Distribution layer?", o: ["Collapsed Core", "Spine-and-Leaf", "Ring Topology", "Hub-and-Spoke"], a: "Spine-and-Leaf", e: "Spine-Leaf flattens the network for massive East-West scalability." },
    { q: "If a business requires a WAN connection that physically never shares a wire with any other company's data, they must buy:", o: ["A VPN.", "A Dedicated Leased Line or Dark Fiber.", "A broadband cable connection.", "A public Wi-Fi link."], a: "A Dedicated Leased Line or Dark Fiber.", e: "Dedicated lines provide absolute physical separation." },
    { q: "What is a 'VLAN Tag' (802.1q)?", o: ["A physical sticker on a cable.", "A small header inserted into an Ethernet frame so the receiving switch knows exactly which VLAN the packet belongs to.", "A routing protocol metric.", "An IP address."], a: "A small header inserted into an Ethernet frame so the receiving switch knows exactly which VLAN the packet belongs to.", e: "Tags are strictly required on Trunk links to differentiate traffic." },
    { q: "Which Data Center cooling method involves submerging the entire server hardware in a non-conductive fluid?", o: ["Hot Aisle Containment", "Liquid Immersion Cooling", "Raised Floors", "CRAC Units"], a: "Liquid Immersion Cooling", e: "Immersion cooling is an extreme but highly efficient method for incredibly dense server racks." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            const doc = {
                subjectId, moduleName, type: "MULTIPLE_CHOICE",
                category: categories[Math.floor(Math.random() * categories.length)],
                difficultyLevel: ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)],
                createdAt: new Date(),
                questionText: q.q,
                options: q.o.sort(() => Math.random() - 0.5),
                correctAnswer: q.a,
                explanation: q.e
            };
            const exists = await collection.findOne({ subjectId: doc.subjectId, questionText: doc.questionText });
            if (!exists) {
                await collection.insertOne(doc);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 3 (Batch 2 of Phase 3)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
