const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 3: Enterprise Network Design";

const questions = [
    // --- Campus Network Advanced Scenarios (20 Qns) ---
    { q: "Which characteristic makes a 'Campus Network' fundamentally different from a WAN?", o: ["It only uses wireless routers.", "It spans a limited, contiguous geographical area (like a single university grounds) usually owned by the organization.", "It is entirely managed by the ISP.", "It requires satellites."], a: "It spans a limited, contiguous geographical area (like a single university grounds) usually owned by the organization.", e: "Ownership and geographic proximity (like a university or business park) define a campus." },
    { q: "In a Campus Network, why are 'Hostels' and 'Admin Offices' physically separated but logically connected?", o: ["Because they use different electrical voltages.", "To logically isolate traffic using VLANs, preventing students from accessing sensitive administrative servers.", "Because Hostels do not need the internet.", "To increase the cost of cabling."], a: "To logically isolate traffic using VLANs, preventing students from accessing sensitive administrative servers.", e: "VLANs provide security boundaries across the same physical campus infrastructure." },
    { q: "What is the specific risk if an 'Access Layer' switch is placed in a public hallway without a locked cabinet?", o: ["The switch will overheat.", "Physical Security compromise: anyone can plug a laptop directly into the corporate network.", "The MAC addresses will be erased.", "The core router will reboot."], a: "Physical Security compromise: anyone can plug a laptop directly into the corporate network.", e: "Physical security is the first line of defense; accessible ports are massive security risks." },
    { q: "If an engineer wants to enforce 'Inter-VLAN routing' between the Library and the Labs, which device must they deploy?", o: ["A Layer 2 unmanaged switch.", "A Layer 3 Switch or a Router.", "A wireless access point.", "A repeater."], a: "A Layer 3 Switch or a Router.", e: "Traffic cannot cross from one VLAN to another without Layer 3 routing logic." },
    { q: "Why is 'High Performance' specifically listed as a Design Objective for Campus Networks?", o: ["Because users share massive files locally (like videos or medical images) requiring enormous LAN bandwidth.", "Because internet speeds are slow.", "Because IP addresses run out.", "To slow down hackers."], a: "Because users share massive files locally (like videos or medical images) requiring enormous LAN bandwidth.", e: "Internal LAN traffic is often vastly heavier than internet traffic, demanding high-speed campus backbones." },
    { q: "A company with 10,000 devices connects them all to a single massive VLAN. What is the immediate consequence?", o: ["Incredible speeds.", "Crippling broadcast traffic storms that consume all switch CPU and bandwidth.", "Perfect security.", "The network becomes a WAN."], a: "Crippling broadcast traffic storms that consume all switch CPU and bandwidth.", e: "Large flat networks suffer from broadcast radiation, slowing everything down." },
    { q: "How does the 'Distribution Layer' solve the broadcast storm problem mentioned above?", o: ["By turning off the network at night.", "By acting as a Layer 3 boundary, breaking the massive network into smaller, routed VLANs.", "By encrypting broadcasts.", "By sending broadcasts to the internet."], a: "By acting as a Layer 3 boundary, breaking the massive network into smaller, routed VLANs.", e: "Routers (and Layer 3 switches) do not forward Layer 2 broadcasts, effectively killing storms." },
    { q: "What is 'Load Balancing' in the context of the Campus Distribution Layer?", o: ["Balancing the physical weight of switches in a rack.", "Splitting network traffic evenly across two or more redundant uplinks to the Core.", "Deleting old files to save disk space.", "Balancing electrical power."], a: "Splitting network traffic evenly across two or more redundant uplinks to the Core.", e: "Load balancing maximizes bandwidth utilization by using all available paths simultaneously." },
    { q: "If the Core Layer must perform 'Minimal processing for speed', what feature should NEVER be configured there?", o: ["High-speed fiber optics.", "VLAN Access Control Lists (VACLs) requiring deep packet inspection.", "BGP routing.", "Redundant power supplies."], a: "VLAN Access Control Lists (VACLs) requiring deep packet inspection.", e: "Filtering slows down traffic. The core's only job is ultra-fast packet switching." },
    { q: "Which component of the campus network directly interfaces with end-user IP Phones and Printers?", o: ["Core Switches", "Firewalls", "Access Switches", "BGP Edge Routers"], a: "Access Switches", e: "The Access layer is the physical connection point for all endpoints." },
    { q: "What is the primary DISADVANTAGE of Inter-VLAN routing using a 'Router on a Stick' design?", o: ["It is too fast.", "The single physical link between the switch and router becomes a massive bottleneck and single point of failure.", "It requires BGP.", "It cannot route IPv4."], a: "The single physical link between the switch and router becomes a massive bottleneck and single point of failure.", e: "Router-on-a-stick pushes all inter-VLAN traffic through one cable, choking large networks." },
    { q: "To solve the 'Router on a Stick' bottleneck, modern campuses use:", o: ["Hubs", "Layer 3 Switches at the Distribution Layer", "More cables", "Wireless routers"], a: "Layer 3 Switches at the Distribution Layer", e: "Layer 3 switches route packets natively in hardware (ASICs), infinitely faster than external routers." },
    { q: "Which aspect of a Campus Network is most heavily reliant on 'Reliability'?", o: ["The color of the cables.", "The Core Backbone, which must never go down.", "The guest Wi-Fi password.", "The desktop wallpaper."], a: "The Core Backbone, which must never go down.", e: "A core failure paralyzes the entire campus." },
    { q: "A 'Scalable' campus design ensures that:", o: ["You never have to buy new hardware.", "Adding a new building simply requires attaching a new Distribution block to the Core without redesigning the whole network.", "The network gets smaller over time.", "Security is disabled."], a: "Adding a new building simply requires attaching a new Distribution block to the Core without redesigning the whole network.", e: "Scalability means growth is planned for and easy to execute." },
    { q: "What is the main 'Manageability' advantage of using centralized Network Management Software (NMS) on a campus?", o: ["It generates IP addresses.", "It allows admins to monitor and push configurations to hundreds of switches from a single dashboard.", "It encrypts the internet.", "It physically mounts the switches."], a: "It allows admins to monitor and push configurations to hundreds of switches from a single dashboard.", e: "Centralized NMS turns a nightmare of CLI management into a streamlined process." },
    { q: "Which campus layer is most responsible for 'Policy Enforcement' (e.g., blocking Student VLAN from Admin VLAN)?", o: ["Access Layer", "Distribution Layer", "Core Layer", "Physical Layer"], a: "Distribution Layer", e: "The Distribution Layer acts as the security boundary between different campus modules." },
    { q: "If an access switch loses power, why does the entire campus NOT crash?", o: ["Because of the hierarchical, modular design which isolates failures to the lowest level.", "Because Wi-Fi takes over automatically.", "Because the Core provides power.", "Because of OSPF routing."], a: "Because of the hierarchical, modular design which isolates failures to the lowest level.", e: "Modularity limits the 'blast radius' of any hardware failure." },
    { q: "Which technology allows multiple physical switches in the Access Layer to act logically as one single switch?", o: ["VLANs", "BGP", "Switch Stacking (e.g., Cisco StackWise)", "OSPF"], a: "Switch Stacking (e.g., Cisco StackWise)", e: "Stacking simplifies management and spanning tree by turning multiple physical switches into one logical unit." },
    { q: "Why is 'Port Security' strictly an Access Layer function?", o: ["Because the Core layer doesn't have ports.", "Because the Access layer is where untrusted physical devices actually plug into the network.", "Because it increases internet speed.", "Because it is required by BGP."], a: "Because the Access layer is where untrusted physical devices actually plug into the network.", e: "You must secure the edge where users actually connect." },
    { q: "What happens if the 'Core Layer' is omitted in a large campus with 20 buildings?", o: ["Nothing.", "The Distribution switches must all connect directly to each other, creating a massive, unmanageable, expensive full-mesh.", "The network runs faster.", "VLANs stop working."], a: "The Distribution switches must all connect directly to each other, creating a massive, unmanageable, expensive full-mesh.", e: "The Core prevents the need for a full-mesh of distribution switches." },

    // --- WAN Technologies and Topologies (20 Qns) ---
    { q: "A multinational bank connects its London, New York, and Tokyo offices. What kind of network is this?", o: ["LAN", "Campus Network", "WAN (Wide Area Network)", "PAN"], a: "WAN (Wide Area Network)", e: "WANs span vast geographical distances, connecting disparate LANs." },
    { q: "What is the primary reason WANs have 'Higher Latency' than LANs?", o: ["Because WAN routers are old.", "Because the physical speed of light across thousands of miles of fiber optics inherently takes longer.", "Because ISPs intentionally slow them down.", "Because LANs use wireless."], a: "Because the physical speed of light across thousands of miles of fiber optics inherently takes longer.", e: "Physics dictates that bouncing a signal under an ocean takes milliseconds, whereas crossing a room takes microseconds." },
    { q: "Why are WAN links typically 'Lower Speed' (e.g., 100Mbps) compared to LAN links (e.g., 10Gbps)?", o: ["Because routers cannot handle 10Gbps.", "Because leasing long-distance, dedicated high-speed fiber from Telecoms is incredibly expensive.", "Because long cables cannot hold data.", "Because the internet is too small."], a: "Because leasing long-distance, dedicated high-speed fiber from Telecoms is incredibly expensive.", e: "WAN bandwidth is a recurring monthly cost (OpEx), forcing companies to buy only what they strictly need." },
    { q: "Which WAN topology offers the absolute highest reliability but the most extreme cost?", o: ["Hub-and-Spoke", "Point-to-Point", "Full Mesh", "Ring"], a: "Full Mesh", e: "Connecting every site to every other site guarantees uptime but costs a fortune in leased lines." },
    { q: "In a 'Hub-and-Spoke' WAN, if Branch A wants to send a file to Branch B, how does the data flow?", o: ["Directly from Branch A to Branch B.", "From Branch A, to the central HQ (Hub), and then down to Branch B.", "Through the public internet unencrypted.", "It is blocked."], a: "From Branch A, to the central HQ (Hub), and then down to Branch B.", e: "Spokes cannot talk directly to other spokes; everything routes through the Hub." },
    { q: "What is a 'Partial Mesh' WAN?", o: ["A network with no routers.", "A compromise where only the most critical, high-traffic sites are fully interconnected, while smaller sites act as spokes.", "A network that only works part of the day.", "A network using only dial-up modems."], a: "A compromise where only the most critical, high-traffic sites are fully interconnected, while smaller sites act as spokes.", e: "Partial mesh balances the extreme cost of full mesh with the high reliability needed at key sites." },
    { q: "Which WAN technology revolutionized corporate networking by using software to intelligently route traffic over cheaper internet connections instead of expensive MPLS?", o: ["Frame Relay", "SD-WAN (Software-Defined WAN)", "ATM", "Dial-up"], a: "SD-WAN (Software-Defined WAN)", e: "SD-WAN dynamically chooses the best path (Internet vs MPLS) based on current application performance." },
    { q: "What does 'MPLS' stand for?", o: ["Multi-Path Logical System", "Multiprotocol Label Switching", "Main Protocol Line Service", "Multiple Port LAN Switch"], a: "Multiprotocol Label Switching", e: "MPLS is a highly reliable, private WAN technology provided by Telecoms." },
    { q: "How does MPLS speed up packet forwarding compared to traditional IP routing?", o: ["It ignores IP addresses entirely.", "It assigns short 'Labels' to packets and switches them based on the label, avoiding deep IP table lookups at every hop.", "It encrypts the packet.", "It uses wireless signals."], a: "It assigns short 'Labels' to packets and switches them based on the label, avoiding deep IP table lookups at every hop.", e: "Label switching is vastly faster than routing table lookups." },
    { q: "Which legacy WAN technology, popular in the 90s, used fixed 53-byte cells to transport data, voice, and video?", o: ["Frame Relay", "SD-WAN", "ATM (Asynchronous Transfer Mode)", "MPLS"], a: "ATM (Asynchronous Transfer Mode)", e: "ATM used tiny, predictable 53-byte cells to guarantee voice quality before modern QoS existed." },
    { q: "What is the biggest advantage of using an 'Internet VPN' for WAN connectivity?", o: ["It provides the fastest possible physical speed.", "It is incredibly cheap compared to private MPLS lines, leveraging the existing public internet securely.", "It requires no routers.", "It eliminates network latency."], a: "It is incredibly cheap compared to private MPLS lines, leveraging the existing public internet securely.", e: "Internet VPNs are nearly free once the internet connection is paid for." },
    { q: "What is the major DISADVANTAGE of using an 'Internet VPN' for WAN connectivity?", o: ["It is too expensive.", "Performance and latency are unpredictable because the traffic relies on the public internet.", "It cannot be encrypted.", "It only supports IPv6."], a: "Performance and latency are unpredictable because the traffic relies on the public internet.", e: "The internet has no QoS guarantees. Traffic might be fast today and crippled by congestion tomorrow." },
    { q: "Which WAN component sits at the edge of the customer network and physically connects to the ISP's line?", o: ["Core Switch", "Modem / CSU/DSU", "Access Point", "Load Balancer"], a: "Modem / CSU/DSU", e: "The Modem or CSU/DSU translates the digital router signals into the analog or digital format required by the Telecom line." },
    { q: "A 'Leased Line' (like a T1 or T3) provides:", o: ["Shared bandwidth with other companies.", "Dedicated, guaranteed bandwidth strictly for your company.", "Wireless connectivity.", "Free internet access."], a: "Dedicated, guaranteed bandwidth strictly for your company.", e: "Leased lines are expensive because the bandwidth is reserved 100% for you, never shared." },
    { q: "Which WAN objective focuses on keeping corporate data safe while it traverses thousands of miles of ISP cables?", o: ["Scalability", "Reliability", "Security (via VPNs and Encryption)", "Cost Efficiency"], a: "Security (via VPNs and Encryption)", e: "Data leaving the building must be encrypted to prevent wiretapping by third parties." },
    { q: "What is 'Dark Fiber'?", o: ["Fiber optic cables painted black.", "Unused, unlit optical fiber infrastructure that a company can lease and light up with their own equipment.", "Fiber cables that carry malware.", "Fiber cables installed underground."], a: "Unused, unlit optical fiber infrastructure that a company can lease and light up with their own equipment.", e: "Telecoms lay massive amounts of extra fiber and lease the 'dark' strands to companies who want ultimate control." },
    { q: "Which WAN topology is typically used to connect a company's Headquarters directly to a single Disaster Recovery site?", o: ["Hub-and-Spoke", "Point-to-Point", "Full Mesh", "Partial Mesh"], a: "Point-to-Point", e: "A dedicated point-to-point link is perfect for high-speed replication between exactly two locations." },
    { q: "Why is 'Dependence on Service Providers' listed as a WAN disadvantage?", o: ["Because ISPs charge no money.", "Because if the ISP's core network goes down, your WAN goes down, and you have zero control to fix it.", "Because ISPs force you to use Windows.", "Because ISPs delete your data."], a: "Because if the ISP's core network goes down, your WAN goes down, and you have zero control to fix it.", e: "You are at the mercy of the Telecom's SLA (Service Level Agreement)." },
    { q: "What is 'Frame Relay'?", o: ["A modern fiber optic technology.", "A legacy, packet-switching WAN technology that used virtual circuits to share bandwidth among customers.", "A type of VPN.", "A wireless protocol."], a: "A legacy, packet-switching WAN technology that used virtual circuits to share bandwidth among customers.", e: "Frame relay was the predecessor to MPLS, offering cost-effective shared WAN links." },
    { q: "If an organization wants to dynamically route VoIP traffic over an MPLS link and general web browsing over a cheap Internet link, they must use:", o: ["SD-WAN", "A Hub", "A Layer 2 Switch", "A repeater"], a: "SD-WAN", e: "SD-WAN is specifically designed for intelligent, application-aware routing across multiple WAN links." },

    // --- Data Center Basics and Tiers (20 Qns) ---
    { q: "What is the primary definition of a 'Data Center'?", o: ["A small room with one router.", "A dedicated facility that stores, processes, and manages massive amounts of data and applications.", "A cloud software app.", "A type of hard drive."], a: "A dedicated facility that stores, processes, and manages massive amounts of data and applications.", e: "Data centers are specialized buildings designed specifically to keep servers running 24/7." },
    { q: "Which component of a Data Center consumes the most electricity aside from the servers themselves?", o: ["The lighting.", "The Cooling Systems (Air Conditioning).", "The firewalls.", "The biometric scanners."], a: "The Cooling Systems (Air Conditioning).", e: "Thousands of servers generate massive heat. Cooling them requires immense amounts of electricity." },
    { q: "A 'Colocation' (Colo) Data Center is best defined as:", o: ["A facility owned entirely by one bank.", "A shared facility where multiple companies rent rack space, power, and cooling, but provide their own servers.", "A public cloud like AWS.", "A data center built underground."], a: "A shared facility where multiple companies rent rack space, power, and cooling, but provide their own servers.", e: "Colo allows companies to share the massive building costs while keeping control of their own server hardware." },
    { q: "What is the key difference between an 'Enterprise Data Center' and a 'Cloud Data Center'?", o: ["There is no difference.", "Enterprise is owned and used internally by one company; Cloud is owned by a provider (like AWS) who rents virtual resources to the public.", "Enterprise data centers do not use electricity.", "Cloud data centers have no physical servers."], a: "Enterprise is owned and used internally by one company; Cloud is owned by a provider (like AWS) who rents virtual resources to the public.", e: "Ownership and customer base define the type." },
    { q: "Which technology allows one massive physical server to be sliced into 20 smaller, independent 'Virtual Machines'?", o: ["Containerization", "Virtualization (Hypervisors like VMware/Hyper-V)", "SDN", "Load Balancing"], a: "Virtualization (Hypervisors like VMware/Hyper-V)", e: "Virtualization revolutionizes data centers by maximizing physical hardware utilization." },
    { q: "How do 'Containers' (like Docker) differ from Virtual Machines?", o: ["Containers are heavier and slower.", "Containers share the host's operating system kernel, making them incredibly lightweight and fast to start compared to VMs.", "Containers require a dedicated physical server.", "Containers cannot connect to a network."], a: "Containers share the host's operating system kernel, making them incredibly lightweight and fast to start compared to VMs.", e: "Containers do not need a full Guest OS, making them extremely efficient for modern microservices." },
    { q: "According to the Uptime Institute, what defines a 'Tier 1' Data Center?", o: ["It has fully redundant power and cooling.", "It is fully fault-tolerant.", "It has basic infrastructure with ZERO redundancy (a single path for power and cooling).", "It has 99.999% uptime."], a: "It has basic infrastructure with ZERO redundancy (a single path for power and cooling).", e: "Tier 1 has no backups. If the power line fails, the data center goes offline." },
    { q: "Which Data Center tier introduces 'Partial Redundancy' (N+1), meaning they have one extra generator or AC unit just in case?", o: ["Tier 1", "Tier 2", "Tier 3", "Tier 4"], a: "Tier 2", e: "Tier 2 provides slightly better reliability but still has single points of failure in the distribution paths." },
    { q: "What is the hallmark capability of a 'Tier 3' Data Center?", o: ["Zero redundancy.", "Concurrent Maintainability: equipment can be repaired or replaced without shutting down the servers.", "It can survive a nuclear blast.", "It uses no electricity."], a: "Concurrent Maintainability: equipment can be repaired or replaced without shutting down the servers.", e: "Tier 3 uses redundant paths (active and passive) so maintenance never causes downtime." },
    { q: "A 'Tier 4' Data Center is the pinnacle of reliability. What makes it unique?", o: ["It is only used by schools.", "It is Fully Fault-Tolerant (2N+1), meaning ANY single catastrophic failure (fire, power loss) will NOT affect operations.", "It requires no cooling.", "It is entirely wireless."], a: "It is Fully Fault-Tolerant (2N+1), meaning ANY single catastrophic failure (fire, power loss) will NOT affect operations.", e: "Tier 4 has duplicate, physically isolated, active power and cooling systems." },
    { q: "What does 'SAN' stand for in Data Center storage?", o: ["Storage Area Network", "System Access Node", "Secure Area Network", "Server Allocation Number"], a: "Storage Area Network", e: "A SAN is a dedicated, high-speed network purely for block-level storage." },
    { q: "How does a SAN differ from a NAS (Network Attached Storage)?", o: ["NAS is faster.", "SAN provides raw, block-level storage to servers via Fiber Channel; NAS provides file-level access over standard Ethernet.", "SAN only works on Windows.", "NAS uses satellites."], a: "SAN provides raw, block-level storage to servers via Fiber Channel; NAS provides file-level access over standard Ethernet.", e: "SAN looks like a local hard drive to a server; NAS looks like a shared network folder." },
    { q: "Which security measure is an example of 'Physical Security' in a Data Center?", o: ["An IPSec VPN.", "A Cisco ASA Firewall.", "A Biometrically Controlled Man-Trap (double doors).", "A complex password."], a: "A Biometrically Controlled Man-Trap (double doors).", e: "Man-traps prevent 'tailgating' where an unauthorized person follows an admin through a secure door." },
    { q: "What is the purpose of a 'UPS' (Uninterruptible Power Supply)?", o: ["To deliver packages.", "To provide instant battery backup power the exact millisecond the city power grid fails, keeping servers alive until the generators spin up.", "To cool the servers.", "To route internet traffic."], a: "To provide instant battery backup power the exact millisecond the city power grid fails, keeping servers alive until the generators spin up.", e: "Generators take 10-30 seconds to start. The UPS bridge that gap using massive batteries." },
    { q: "Why are Data Centers considered to have a 'High installation and operational cost'?", o: ["Because they require thousands of servers, massive power grids, industrial cooling, and 24/7 staffing.", "Because they must pay the government.", "Because the building must be made of gold.", "Because software is expensive."], a: "Because they require thousands of servers, massive power grids, industrial cooling, and 24/7 staffing.", e: "Building and running a facility that uses as much power as a small town is incredibly expensive." },
    { q: "In a Banking Data Center, why are 'Redundant Links' absolutely critical?", o: ["To download movies faster.", "If the primary fiber optic cable is cut by construction, the backup link instantly routes ATM and transaction traffic to prevent massive financial loss.", "To save electricity.", "To make the routers look cool."], a: "If the primary fiber optic cable is cut by construction, the backup link instantly routes ATM and transaction traffic to prevent massive financial loss.", e: "Banks lose millions per minute of downtime; redundancy is non-negotiable." },
    { q: "What does 'SDN' (Software Defined Networking) do in a modern data center?", o: ["It replaces all cables with Wi-Fi.", "It separates the Control Plane from the Data Plane, allowing a central controller to program all switches instantly.", "It installs Windows on routers.", "It encrypts hard drives."], a: "It separates the Control Plane from the Data Plane, allowing a central controller to program all switches instantly.", e: "SDN brings automation and agility to massive networks." },
    { q: "Which Data Center topology specifically eliminates the Spanning Tree Protocol (STP) to utilize all available links simultaneously?", o: ["Hub and Spoke", "Spine-and-Leaf", "Ring Topology", "Bus Topology"], a: "Spine-and-Leaf", e: "Spine-Leaf uses advanced Layer 3 routing down to the rack to avoid STP's blocked ports." },
    { q: "In Data Center cooling, what is the 'Hot Aisle / Cold Aisle' containment strategy?", o: ["Mixing hot and cold air randomly.", "Arranging server racks so cold air is pumped into the front, and the hot exhaust is captured in the back and exhausted out, maximizing cooling efficiency.", "Putting ice on the servers.", "Turning off half the servers."], a: "Arranging server racks so cold air is pumped into the front, and the hot exhaust is captured in the back and exhausted out, maximizing cooling efficiency.", e: "Containment prevents hot exhaust from mixing with cold intake, saving massive amounts of AC power." },
    { q: "What is a 'Disaster Recovery' (DR) Data Center?", o: ["A place to store old furniture.", "A secondary data center located in a different geographical region that takes over if the primary data center is destroyed by a flood or earthquake.", "A virtual reality simulation.", "A data center that runs with no electricity."], a: "A secondary data center located in a different geographical region that takes over if the primary data center is destroyed by a flood or earthquake.", e: "DR sites ensure business continuity during catastrophic, region-wide events." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            const doc = {
                subjectId, moduleName, type: "MULTIPLE_CHOICE",
                category: categories[Math.floor(Math.random() * categories.length)],
                difficultyLevel: ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)],
                createdAt: new Date(),
                questionText: q.q,
                options: q.o.sort(() => Math.random() - 0.5),
                correctAnswer: q.a,
                explanation: q.e
            };
            const exists = await collection.findOne({ subjectId: doc.subjectId, questionText: doc.questionText });
            if (!exists) {
                await collection.insertOne(doc);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 3 (Batch 1 of Phase 3)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
