const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 5: Implementation & Troubleshooting";

const questions = [
    // --- Troubleshooting Methods Deep Dive (25 questions) ---
    { questionText: "What is the primary goal of Troubleshooting Methods in a network environment?", options: ["To randomly restart servers until they work.", "To systematically identify, analyze, and resolve problems to restore normal system operation efficiently.", "To upgrade all hardware to the latest versions.", "To write new software applications."], correctAnswer: "To systematically identify, analyze, and resolve problems to restore normal system operation efficiently.", explanation: "Troubleshooting is a structured approach to fixing issues and minimizing downtime." },
    { questionText: "Which troubleshooting method is considered the simplest, involving testing different possible solutions one by one until the problem is resolved?", options: ["Top-Down Method", "Divide-and-Conquer Method", "Trial-and-Error Method", "Root Cause Analysis"], correctAnswer: "Trial-and-Error Method", explanation: "Trial-and-error is simple but often inefficient for complex systems." },
    { questionText: "Why is the Trial-and-Error method generally inefficient for complex network issues?", options: ["Because it requires expensive software.", "Because it does not follow a structured diagnostic process, wasting time.", "Because it deletes all user data automatically.", "Because it requires shutting down the entire network."], correctAnswer: "Because it does not follow a structured diagnostic process, wasting time.", explanation: "Without a structured process, you may test irrelevant solutions, wasting time on complex issues." },
    { questionText: "If a technician starts diagnosing an issue by checking the web application's user configuration and then moves down to check network protocols, which method are they using?", options: ["Bottom-Up Method", "Top-Down Method", "Substitution Method", "Comparison Method"], correctAnswer: "Top-Down Method", explanation: "Top-Down starts at the Application layer (Layer 7) and moves down towards the Physical layer." },
    { questionText: "The 'Top-Down' method is most useful in which scenario?", options: ["When the physical cables are clearly broken.", "When applications are functioning incorrectly despite apparently healthy hardware and network infrastructure.", "When the server has completely lost power.", "When a new switch needs to be installed."], correctAnswer: "When applications are functioning incorrectly despite apparently healthy hardware and network infrastructure.", explanation: "If the lower layers seem fine, starting at the top (application) is the fastest way to find the software issue." },
    { questionText: "Which troubleshooting method starts by inspecting physical cables, connectors, and switch interfaces before moving to software settings?", options: ["Divide-and-Conquer", "Top-Down Method", "Bottom-Up Method", "Root Cause Analysis"], correctAnswer: "Bottom-Up Method", explanation: "Bottom-Up starts at the Physical layer (Layer 1) and moves upward." },
    { questionText: "Why is the 'Bottom-Up' method widely used in network troubleshooting?", options: ["Because applications break more often than hardware.", "Because many network issues originate from simple physical faults, like unplugged cables.", "Because it requires no technical knowledge.", "Because it skips the OSI model completely."], correctAnswer: "Because many network issues originate from simple physical faults, like unplugged cables.", explanation: "Starting at the physical layer quickly rules out the most common causes of outages (bad cables, power issues)." },
    { questionText: "Which troubleshooting approach begins testing at a middle point (like pinging a gateway router) to determine whether the problem exists above or below that point?", options: ["Bottom-Up Method", "Divide-and-Conquer Method", "Trial-and-Error Method", "Substitution Method"], correctAnswer: "Divide-and-Conquer Method", explanation: "Divide-and-Conquer splits the system in half (e.g., pinging halfway across the network) to quickly narrow down the fault area." },
    { questionText: "If a technician believes a network cable is faulty and decides to swap it with a brand new cable to see if the problem disappears, which method is being used?", options: ["Substitution Method", "Comparison Method", "Top-Down Method", "Root Cause Analysis"], correctAnswer: "Substitution Method", explanation: "The Substitution Method involves replacing a suspected faulty component with a known working one." },
    { questionText: "The 'Comparison Method' involves:", options: ["Comparing the cost of two different routers.", "Comparing a malfunctioning system with a similar system that is functioning correctly to identify differences.", "Substituting a broken switch with a new one.", "Starting troubleshooting from the application layer."], correctAnswer: "Comparing a malfunctioning system with a similar system that is functioning correctly to identify differences.", explanation: "If two systems should be identical but one is broken, comparing their configs reveals the error." },
    { questionText: "Which troubleshooting method goes beyond fixing symptoms to identify the fundamental, underlying reason a problem occurred?", options: ["Root Cause Analysis (RCA)", "Trial-and-Error", "Divide-and-Conquer", "Substitution Method"], correctAnswer: "Root Cause Analysis (RCA)", explanation: "RCA aims to find the true origin of a problem to prevent it from ever recurring." },
    { questionText: "What is a common technique used during Root Cause Analysis (RCA)?", options: ["Just buying a new server.", "The '5 Whys' and cause-and-effect analysis.", "Ping sweeps.", "Guessing randomly."], correctAnswer: "The '5 Whys' and cause-and-effect analysis.", explanation: "The '5 Whys' technique drills down through symptoms to find the core issue." },
    { questionText: "If a technician traces the exact flow of data through routers and firewalls to find where communication drops, they are using:", options: ["Follow-the-Path Method", "Substitution Method", "Comparison Method", "Bottom-Up Method"], correctAnswer: "Follow-the-Path Method", explanation: "Follow-the-Path involves tracing the exact data route to see where it gets blocked." },
    { questionText: "According to the standard troubleshooting process, what is the very FIRST step?", options: ["Test and verify suspected causes.", "Implement the appropriate solution.", "Identify and define the problem.", "Establish possible causes."], correctAnswer: "Identify and define the problem.", explanation: "You cannot fix a problem until you clearly understand and define what the problem actually is." },
    { questionText: "What should a technician do immediately after 'Identifying and defining the problem'?", options: ["Buy new hardware.", "Gather relevant information and symptoms from users and systems.", "Format the server.", "Document the final solution."], correctAnswer: "Gather relevant information and symptoms from users and systems.", explanation: "Before guessing causes, you must gather all the facts and symptoms." },
    { questionText: "Why is 'Documenting the problem and corrective actions taken' the crucial final step of troubleshooting?", options: ["It provides a record that can help resolve similar issues much faster in the future.", "It automatically refunds the company for downtime.", "It deletes the server logs to save space.", "It changes the network topology."], correctAnswer: "It provides a record that can help resolve similar issues much faster in the future.", explanation: "Documentation ensures knowledge is retained and future troubleshooting is highly efficient." },
    { questionText: "Which of the following is a classic 'Diagnostic Utility' used during network troubleshooting?", options: ["Microsoft Word", "Ping and Traceroute", "Adobe Photoshop", "AutoCAD"], correctAnswer: "Ping and Traceroute", explanation: "Ping and Traceroute are fundamental tools for checking connectivity and routing paths." },
    { questionText: "Which best practice prevents a technician from making a bad situation worse during troubleshooting?", options: ["Always use Trial-and-Error first.", "Gather complete information BEFORE making any changes to the system.", "Delete old configurations immediately.", "Reboot the core router before asking questions."], correctAnswer: "Gather complete information BEFORE making any changes to the system.", explanation: "Making blind changes without information can cause cascading network failures." },
    { questionText: "Why should you 'Check simple causes before investigating complex issues'?", options: ["Because complex issues are impossible to fix.", "Because checking if a cable is unplugged takes seconds, whereas analyzing routing protocols takes hours.", "Because you shouldn't touch software.", "Because routers don't have complex issues."], correctAnswer: "Because checking if a cable is unplugged takes seconds, whereas analyzing routing protocols takes hours.", explanation: "Always rule out the simplest (and most common) faults first to save massive amounts of time." },
    { questionText: "Which diagnostic tool is specifically designed to analyze 'Event Viewer' records and 'System Logs'?", options: ["Cable tester", "Ping", "Monitoring Software / Log Analyzers", "Traceroute"], correctAnswer: "Monitoring Software / Log Analyzers", explanation: "Log analyzers scan deep into the operating system's internal event records." },
    { questionText: "The 'Substitution Method' is most frequently used to diagnose:", options: ["Software bugs in a custom app.", "Hardware issues such as faulty cables or bad RAM modules.", "Routing protocol misconfigurations.", "Database SQL errors."], correctAnswer: "Hardware issues such as faulty cables or bad RAM modules.", explanation: "Swapping out a physical part is the definitive way to prove a hardware fault." },
    { questionText: "If a technician is trying to figure out why an email didn't reach its destination by checking the local switch, then the firewall, then the ISP router, they are using:", options: ["Follow-the-Path Method", "Comparison Method", "Top-Down Method", "Trial-and-Error"], correctAnswer: "Follow-the-Path Method", explanation: "They are tracking the exact physical and logical path the email takes." },
    { questionText: "What does 'Verify the solution after implementation' mean in the troubleshooting process?", options: ["Asking the boss for a raise.", "Confirming that the fix actually solved the problem and didn't break anything else.", "Writing a new network policy.", "Re-installing the operating system."], correctAnswer: "Confirming that the fix actually solved the problem and didn't break anything else.", explanation: "You must test the system to ensure the problem is fully resolved." },
    { questionText: "When comparing Top-Down and Bottom-Up, which method relies heavily on understanding the OSI model?", options: ["Only Top-Down", "Only Bottom-Up", "Both Top-Down and Bottom-Up", "Neither"], correctAnswer: "Both Top-Down and Bottom-Up", explanation: "Both methods use the layers of the OSI model as their roadmap for troubleshooting." },
    { questionText: "In a massive enterprise network, which troubleshooting method is typically the fastest way to isolate a fault?", options: ["Divide-and-Conquer Method", "Trial-and-Error", "Bottom-Up (checking every single cable first)", "Comparison Method"], correctAnswer: "Divide-and-Conquer Method", explanation: "By splitting the network in half repeatedly, you rapidly eliminate huge sections of the network from suspicion." },

    // --- Performance Optimization Deep Dive (25 questions) ---
    { questionText: "How is 'Performance Optimization' defined?", options: ["The process of slowing down the network to save electricity.", "The process of improving the efficiency, speed, reliability, and overall performance of systems.", "The process of deleting old user accounts.", "The process of bypassing security firewalls."], correctAnswer: "The process of improving the efficiency, speed, reliability, and overall performance of systems.", explanation: "Optimization squeezes the maximum possible performance out of existing hardware and software." },
    { questionText: "What is a primary consequence of 'Poor system performance'?", options: ["Increased employee morale.", "Slow response times, reduced productivity, and user dissatisfaction.", "Lower electricity bills.", "Higher security against hackers."], correctAnswer: "Slow response times, reduced productivity, and user dissatisfaction.", explanation: "Slow systems frustrate users and cost the business time and money." },
    { questionText: "How does regular optimization affect hardware lifespan?", options: ["It breaks hardware faster.", "It extends the lifespan of resources by ensuring they operate efficiently without unnecessary strain.", "It has no effect on hardware.", "It causes servers to overheat."], correctAnswer: "It extends the lifespan of resources by ensuring they operate efficiently without unnecessary strain.", explanation: "Optimized systems do less 'wasted' work, generating less heat and reducing hardware wear." },
    { questionText: "Which of the following is a 'Hardware limitation' that affects performance?", options: ["Inefficient software code.", "Fragmented hard drive storage.", "Insufficient memory (RAM) and slow processors.", "Too many background apps running."], correctAnswer: "Insufficient memory (RAM) and slow processors.", explanation: "Physical lack of RAM or CPU power is a hard physical limit on performance." },
    { questionText: "Which of the following is a 'Software-related issue' that degrades performance?", options: ["A broken network cable.", "A slow 10Mbps switch.", "Unnecessary background processes and fragmented storage.", "A dead server power supply."], correctAnswer: "Unnecessary background processes and fragmented storage.", explanation: "Software bloat and disk fragmentation slow down the operating system's ability to process data." },
    { questionText: "Replacing traditional Hard Disk Drives (HDDs) with Solid-State Drives (SSDs) is an example of:", options: ["Network Performance Optimization", "System Performance Optimization", "Database Optimization", "Application Optimization"], correctAnswer: "System Performance Optimization", explanation: "Upgrading local server hardware (like SSDs) directly boosts system-level performance." },
    { questionText: "Disabling unused services and removing unnecessary software helps to:", options: ["Reduce system load and improve processing speed.", "Increase the network bandwidth.", "Create new VLANs.", "Encrypt the hard drive."], correctAnswer: "Reduce system load and improve processing speed.", explanation: "Fewer running background tasks frees up CPU and RAM for critical applications." },
    { questionText: "What is the primary goal of 'Network Performance Optimization'?", options: ["To upgrade server RAM.", "To improve communication speed, reliability, and bandwidth utilization across the network.", "To write better SQL queries.", "To install new antivirus software."], correctAnswer: "To improve communication speed, reliability, and bandwidth utilization across the network.", explanation: "Network optimization focuses purely on the flow of data through switches and routers." },
    { questionText: "Implementing Quality of Service (QoS) and load balancing are techniques primarily used for:", options: ["System Optimization", "Database Optimization", "Network Performance Optimization", "Application Optimization"], correctAnswer: "Network Performance Optimization", explanation: "QoS and load balancing directly manage and optimize network traffic flow." },
    { questionText: "Which optimization category focuses on 'improving database queries' and 'minimizing application startup times'?", options: ["System Performance Optimization", "Network Performance Optimization", "Application Performance Optimization", "Capacity Planning"], correctAnswer: "Application Performance Optimization", explanation: "Application optimization requires developers to write cleaner, more efficient software code." },
    { questionText: "Why is 'Database Performance Optimization' so critical?", options: ["Because databases control the network switches.", "Because poor database performance can significantly affect overall application performance (creating a massive bottleneck).", "Because databases store all the passwords.", "Because it cools down the server room."], correctAnswer: "Because poor database performance can significantly affect overall application performance (creating a massive bottleneck).", explanation: "If the database is slow, every application that relies on it will also be slow, regardless of network speed." },
    { questionText: "Creating 'Indexes' in a database is a technique used to:", options: ["Encrypt the database.", "Delete old database records.", "Optimize queries and speed up data retrieval.", "Back up the database to the cloud."], correctAnswer: "Optimize queries and speed up data retrieval.", explanation: "Database indexes work like a book's index, allowing the system to find data instantly rather than scanning every row." },
    { questionText: "Allocating CPU, memory, and network bandwidth appropriately based on workload requirements is known as:", options: ["Database Indexing", "Resource Management", "Security Auditing", "Trial-and-Error"], correctAnswer: "Resource Management", explanation: "Resource management ensures that critical apps get the hardware resources they need to function." },
    { questionText: "Why is 'Performance Monitoring' a prerequisite for Optimization?", options: ["Because you must monitor the system to identify trends, detect abnormalities, and find the bottlenecks you need to optimize.", "Because monitoring tools automatically write new software code.", "Because monitoring tools increase the physical RAM.", "It is not a prerequisite."], correctAnswer: "Because you must monitor the system to identify trends, detect abnormalities, and find the bottlenecks you need to optimize.", explanation: "You cannot optimize a system if you don't know where the performance bottlenecks are." },
    { questionText: "What does 'Capacity Planning' involve?", options: ["Deleting old user accounts.", "Forecasting future resource requirements based on current usage patterns and expected growth.", "Configuring the firewall to block all traffic.", "Switching from a Top-Down to a Bottom-Up troubleshooting method."], correctAnswer: "Forecasting future resource requirements based on current usage patterns and expected growth.", explanation: "Capacity planning uses historical monitoring data to predict when you will run out of space or bandwidth." },
    { questionText: "Effective capacity planning prevents performance degradation caused by:", options: ["Hackers.", "Resource shortages (running out of RAM, Disk Space, or Bandwidth).", "Poorly written software.", "Unplugged cables."], correctAnswer: "Resource shortages (running out of RAM, Disk Space, or Bandwidth).", explanation: "By predicting growth, you can buy new servers BEFORE the old ones run out of capacity and crash." },
    { questionText: "How do Security measures (like Firewalls and Encryption) typically affect System Performance?", options: ["They drastically increase system speed.", "They have absolutely zero effect on performance.", "They consume computing resources (CPU/RAM) and can reduce operational efficiency if not balanced.", "They replace the need for physical memory."], correctAnswer: "They consume computing resources (CPU/RAM) and can reduce operational efficiency if not balanced.", explanation: "Deep packet inspection and complex encryption algorithms require significant CPU processing power." },
    { questionText: "What is the key challenge in 'Security and Performance'?", options: ["Security is always free.", "Finding the right balance between maximum system protection and acceptable operational performance levels.", "Turning off all security to make the network fast.", "Using only legacy encryption methods."], correctAnswer: "Finding the right balance between maximum system protection and acceptable operational performance levels.", explanation: "Too much security can grind a network to a halt; too little exposes it to hackers. Balance is key." },
    { questionText: "If an application is slow because it is recalculating the same complex data repeatedly, which optimization technique should be applied?", options: ["Increasing network bandwidth.", "Implementing caching mechanisms.", "Replacing the firewall.", "Using the Divide-and-Conquer method."], correctAnswer: "Implementing caching mechanisms.", explanation: "Caching stores the result of complex calculations so the application doesn't have to compute it again." },
    { questionText: "Fragmented storage specifically impacts which type of performance?", options: ["Network latency", "System Performance (Disk read/write speeds)", "Database indexing", "Cloud security"], correctAnswer: "System Performance (Disk read/write speeds)", explanation: "Fragmentation scatters data across a physical hard drive, making the read heads work harder and slower." },
    { questionText: "Which action would best optimize 'Network Performance' for a company experiencing massive broadcast storms?", options: ["Installing an SSD in a local PC.", "Implementing Network Segmentation (VLANs).", "Changing default server passwords.", "Optimizing a SQL database query."], correctAnswer: "Implementing Network Segmentation (VLANs).", explanation: "VLAN segmentation breaks up large broadcast domains, drastically improving network efficiency." },
    { questionText: "Why is 'Analyzing resource usage' critical during optimization?", options: ["To find out which users are playing games.", "To ensure that you don't upgrade the CPU when the actual bottleneck is the hard drive.", "To print out logs for HR.", "To format the router."], correctAnswer: "To ensure that you don't upgrade the CPU when the actual bottleneck is the hard drive.", explanation: "Blind upgrades are a waste of money. Analysis shows exactly which component (CPU, RAM, Disk) needs replacing." },
    { questionText: "A database administrator 'removes redundant data' to speed up processing. This is a form of:", options: ["Network Optimization", "Database Performance Optimization", "System OS Optimization", "Security Optimization"], correctAnswer: "Database Performance Optimization", explanation: "Cleaning up a database (normalization) reduces the amount of data the engine has to sift through." },
    { questionText: "Which statement best summarizes the continuous nature of Performance Optimization?", options: ["It is only done once when the server is bought.", "It requires continuous monitoring and proactive improvements as workloads and traffic patterns change.", "It ends as soon as the network is deployed.", "It is only done after a catastrophic failure."], correctAnswer: "It requires continuous monitoring and proactive improvements as workloads and traffic patterns change.", explanation: "Networks are dynamic; optimization must be an ongoing, continuous process." },
    { questionText: "Which troubleshooting step directly relies on the data collected by Monitoring Tools?", options: ["Document the solution.", "Gather relevant information and symptoms.", "Test suspected causes.", "Format the hard drive."], correctAnswer: "Gather relevant information and symptoms.", explanation: "Monitoring tool dashboards and alerts provide the exact symptoms and logs needed to start troubleshooting." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            q.category = categories[Math.floor(Math.random() * categories.length)];
            q.type = "MULTIPLE_CHOICE";
            q.difficultyLevel = ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)];
            q.createdAt = new Date();
            
            const exists = await collection.findOne({ 
                subjectId: q.subjectId, 
                questionText: q.questionText 
            });
            if (!exists) {
                await collection.insertOne(q);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 5 (Batch 2)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
