const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 1: Network Design Fundamentals";

const questions = [
    // --- Network Design Methodology (15 Qns) ---
    { q: "During which phase of the Network Design Methodology do engineers define the IP addressing scheme and routing protocols?", o: ["Requirements Analysis", "Logical Network Design", "Physical Network Design", "Testing and Validation"], a: "Logical Network Design", e: "The logical design phase establishes the topology, IP addressing, and routing without picking the physical hardware yet." },
    { q: "If a business goal is to 'support a 50% increase in remote workers over the next two years', which phase documents this?", o: ["Physical Network Design", "Testing and Validation", "Requirements Analysis", "Maintenance"], a: "Requirements Analysis", e: "Business goals and future growth requirements are gathered during the Requirements Analysis phase." },
    { q: "Which of the following occurs during the 'Physical Network Design' phase?", o: ["Selecting specific brands of routers and switches.", "Creating the IP subnet table.", "Running Ping and Traceroute.", "Defining the business budget."], a: "Selecting specific brands of routers and switches.", e: "Physical design takes the logical blueprint and assigns real hardware, like specific Cisco routers or CAT6 cables." },
    { q: "The 'Testing and Validation' phase is crucial because it:", o: ["Reduces the cost of the hardware.", "Ensures the deployed network actually meets the business and technical requirements gathered earlier.", "Installs the physical racks in the server room.", "Draws the logical network topology."], a: "Ensures the deployed network actually meets the business and technical requirements gathered earlier.", e: "Validation ensures the network performs as expected before it is officially handed over for daily use." },
    { q: "What is the primary activity during the 'Implementation' phase?", o: ["Drawing Visio diagrams.", "Defining the budget.", "Physically installing and configuring the networking devices.", "Monitoring network bottlenecks over a year."], a: "Physically installing and configuring the networking devices.", e: "Implementation is the active deployment phase where configurations are applied to physical devices." },
    { q: "Which tool is most likely to be heavily utilized during the 'Monitoring and Optimization' phase?", o: ["A screwdriver", "NetFlow or SNMP", "A subnet calculator", "A physical cable tester"], a: "NetFlow or SNMP", e: "SNMP and NetFlow are software protocols used to monitor traffic and device health continuously." },
    { q: "If a company replaces an old Core Switch with a newer, faster model after five years of operation, this falls under which phase?", o: ["Requirements Analysis", "Implementation", "Maintenance and Scaling", "Testing and Validation"], a: "Maintenance and Scaling", e: "Hardware upgrades after the initial deployment are part of the ongoing Maintenance and Scaling phase." },
    { q: "Why is a structured methodology preferred over 'ad-hoc' (unplanned) network building?", o: ["It completely eliminates the need for IT staff.", "It is always cheaper to buy hardware this way.", "It ensures scalability, reduces long-term costs, and aligns technical solutions with business goals.", "It guarantees that the network will never experience a hardware failure."], a: "It ensures scalability, reduces long-term costs, and aligns technical solutions with business goals.", e: "A structured methodology prevents costly redesigns and ensures the network meets organizational needs." },
    { q: "During Requirements Analysis, a hospital states that 'patient data must never cross the public internet unencrypted'. This is classified as a:", o: ["Business Goal", "Technical Constraint", "Security Requirement", "Physical Design"], a: "Security Requirement", e: "Data protection mandates form the core of the Security Requirements gathered early in the project." },
    { q: "Which documentation is typically finalized as the main output of the Logical Design phase?", o: ["A list of MAC addresses.", "The purchase order for Cisco switches.", "The logical topology diagram and IP addressing plan.", "The disaster recovery backups."], a: "The logical topology diagram and IP addressing plan.", e: "Logical design outputs blueprints of how the network operates conceptually." },
    { q: "A 'Pilot Network' or 'Proof of Concept' is often built during which phase?", o: ["Testing and Validation", "Requirements Analysis", "Maintenance", "Monitoring"], a: "Testing and Validation", e: "A pilot network tests the design in a safe, controlled environment before full rollout." },
    { q: "If an engineer is deciding whether to use CAT6 copper or Multimode Fiber for a specific building link, they are actively engaged in:", o: ["Logical Design", "Physical Design", "Implementation", "Monitoring"], a: "Physical Design", e: "Choosing the exact physical transmission medium is a Physical Design decision." },
    { q: "What is the significance of the 'Sign-off' at the end of the Testing and Validation phase?", o: ["It legally forces the ISP to provide faster internet.", "It serves as formal agreement from stakeholders that the network meets all requirements and is ready for production.", "It automatically configures all remaining routers.", "It signals the start of the Requirements Analysis phase."], a: "It serves as formal agreement from stakeholders that the network meets all requirements and is ready for production.", e: "Sign-off is the formal acceptance of the deployed network by the business owners." },
    { q: "A company realizes their new network cannot support VoIP traffic because no QoS was planned. Which phase failed?", o: ["Implementation", "Physical Design", "Requirements Analysis", "Maintenance"], a: "Requirements Analysis", e: "Failing to capture the need for VoIP (and its QoS requirements) is a failure of the initial analysis phase." },
    { q: "Applying software patches and firmware upgrades to routers is a standard task in the ________ phase.", o: ["Logical Design", "Maintenance and Scaling", "Requirements Analysis", "Physical Design"], a: "Maintenance and Scaling", e: "Routine patching is part of the ongoing operational maintenance." },

    // --- Hierarchical Network Model (15 Qns) ---
    { q: "In the Hierarchical Model, which layer is responsible for defining broadcast domains and implementing routing policies?", o: ["Core Layer", "Distribution Layer", "Access Layer", "Application Layer"], a: "Distribution Layer", e: "The Distribution Layer acts as a boundary for broadcast domains (VLAN routing) and enforces security policies." },
    { q: "What happens if a network designer implements complex Access Control Lists (ACLs) directly on the Core Layer?", o: ["The network becomes much faster.", "The Core Layer's primary job of high-speed switching is compromised, leading to significant latency.", "The Access Layer will shut down automatically.", "The routers will convert to switches."], a: "The Core Layer's primary job of high-speed switching is compromised, leading to significant latency.", e: "The Core must remain fast; complex filtering like ACLs slows down packet forwarding." },
    { q: "A 'Collapsed Core' architecture combines which two layers into a single device?", o: ["Access and Distribution", "Core and Distribution", "Core and Access", "Physical and Logical"], a: "Core and Distribution", e: "In smaller networks to save costs, the Core and Distribution layers are merged into a single set of switches." },
    { q: "Which feature is most commonly deployed exclusively at the Access Layer?", o: ["BGP Internet Routing", "Power over Ethernet (PoE) for IP cameras", "High-speed optical backbone links", "Inter-VLAN routing tables"], a: "Power over Ethernet (PoE) for IP cameras", e: "Access switches power end devices like phones and cameras using PoE." },
    { q: "How does the Hierarchical Model aid in 'Fault Isolation'?", o: ["By putting all devices in one broadcast domain.", "By organizing the network into distinct, independent blocks, making it easy to identify which layer or module failed.", "By eliminating the need for firewalls.", "By making the network wireless."], a: "By organizing the network into distinct, independent blocks, making it easy to identify which layer or module failed.", e: "Modular design means a failure in one access block doesn't take down the entire network, and is easy to locate." },
    { q: "Which layer requires the absolute highest level of physical and logical redundancy?", o: ["Access Layer", "Distribution Layer", "Core Layer", "Edge Layer"], a: "Core Layer", e: "The Core handles all traffic crossing the network; a failure here is catastrophic, demanding extreme redundancy." },
    { q: "A university has 5 buildings. Each building has its own routers that connect to a massive central router. This central router represents the:", o: ["Access Layer", "Core Layer", "Distribution Layer", "Server Layer"], a: "Core Layer", e: "The central hub connecting different major modules or buildings acts as the Core." },
    { q: "Where does 'Summarization of routes' typically occur to keep routing tables small?", o: ["Access Layer towards Distribution", "Distribution Layer towards the Core", "Core Layer towards the Access", "Access Layer towards End Devices"], a: "Distribution Layer towards the Core", e: "The Distribution layer summarizes subnets before advertising them to the Core, keeping the Core routing table fast and lean." },
    { q: "If a student attempts to plug a rogue DHCP server into a wall jack, which layer should block this action?", o: ["Core Layer", "Distribution Layer", "Access Layer", "Network Layer"], a: "Access Layer", e: "The Access Layer implements edge security like DHCP Snooping and Port Security." },
    { q: "Why is 'Scalability' a major benefit of the 3-tier Hierarchical Model?", o: ["Because you never need to buy new hardware.", "Because adding a new building only requires adding a new Access/Distribution module without redesigning the Core.", "Because it uses IPv6.", "Because it removes the need for IP addressing."], a: "Because adding a new building only requires adding a new Access/Distribution module without redesigning the Core.", e: "Modular growth allows the network to scale horizontally effortlessly." },
    { q: "Which layer acts as an aggregation point for multiple Access Layer switches?", o: ["Core Layer", "Distribution Layer", "Physical Layer", "Perimeter Layer"], a: "Distribution Layer", e: "The Distribution Layer aggregates uplinks from numerous access switches." },
    { q: "In a massive enterprise network, what is the primary metric for selecting a Core Switch?", o: ["Number of PoE ports", "Packet forwarding rate (Switching capacity)", "Ability to run antivirus software", "Size of the physical case"], a: "Packet forwarding rate (Switching capacity)", e: "Core switches are chosen based on sheer throughput and speed." },
    { q: "If a company has a tight budget and only 50 users, which hierarchical model modification is most appropriate?", o: ["Using a 4-tier model.", "Implementing a Collapsed Core design.", "Removing the Access Layer.", "Connecting all PCs directly to the Core router."], a: "Implementing a Collapsed Core design.", e: "Collapsed Core saves money for small networks by combining Core and Distribution." },
    { q: "What is the primary role of the Distribution Layer in regards to traffic from the Access Layer?", o: ["To convert it to analog signals.", "To aggregate it and apply organizational policies before forwarding it to the Core.", "To drop all traffic.", "To encrypt all traffic automatically."], a: "To aggregate it and apply organizational policies before forwarding it to the Core.", e: "The Distribution layer aggregates and filters traffic." },
    { q: "Which layer is most closely associated with the phrase 'High-speed switching without deep packet inspection'?", o: ["Access Layer", "Distribution Layer", "Core Layer", "Security Layer"], a: "Core Layer", e: "Deep packet inspection slows down traffic, so it is avoided at the high-speed Core." },

    // --- Design Objectives (15 Qns) ---
    { q: "A network design heavily emphasizes using dual-power supplies and HSRP (Hot Standby Router Protocol). Which objective is being prioritized?", o: ["Security", "Reliability", "Manageability", "Cost Efficiency"], a: "Reliability", e: "Redundant power and routing protocols ensure the network remains reliable during component failures." },
    { q: "Which design objective focuses on ensuring the network operates efficiently with minimal 'Latency' and 'Jitter'?", o: ["Flexibility", "Performance", "Security", "Scalability"], a: "Performance", e: "Latency and jitter are direct metrics of network Performance." },
    { q: "If a network is described as 'Highly Manageable', what feature does it likely possess?", o: ["It has no passwords.", "It is completely wireless.", "It utilizes centralized monitoring tools like SNMP and standardized configurations.", "It only uses one switch."], a: "It utilizes centralized monitoring tools like SNMP and standardized configurations.", e: "Manageability means administrators can easily oversee and configure the network." },
    { q: "Balancing the need for a 10Gbps backbone against a limited corporate budget represents a focus on:", o: ["Cost Efficiency", "Scalability", "Security", "Availability"], a: "Cost Efficiency", e: "Cost Efficiency requires finding the optimal balance between performance needs and financial limits." },
    { q: "Which objective is met when a network can easily integrate a new VoIP phone system without replacing existing data switches?", o: ["Flexibility", "Security", "Availability", "Reliability"], a: "Flexibility", e: "Flexibility refers to the network's ability to adapt to new technologies and services." },
    { q: "A hospital's network must be active 24/7/365, as any downtime could risk lives. This emphasizes extreme:", o: ["Manageability", "Availability", "Cost Efficiency", "Flexibility"], a: "Availability", e: "Availability is the measure of a network's uptime and readiness to serve users." },
    { q: "Deploying 802.1x Authentication on all Access Switches directly supports which design objective?", o: ["Security", "Performance", "Scalability", "Manageability"], a: "Security", e: "802.1x prevents unauthorized devices from joining the network, a core security function." },
    { q: "What is the primary difference between 'Reliability' and 'Availability'?", o: ["There is no difference.", "Availability focuses on uptime; Reliability focuses on operating without errors or failing gracefully.", "Availability only applies to hardware; Reliability only applies to software.", "Reliability is cheaper than Availability."], a: "Availability focuses on uptime; Reliability focuses on operating without errors or failing gracefully.", e: "A system can be highly available but unreliable if it constantly throws errors while remaining online." },
    { q: "Which two design objectives often conflict with 'Cost Efficiency'?", o: ["Manageability and Flexibility", "High Performance and Extreme Availability", "Documentation and Training", "VLANs and Subnets"], a: "High Performance and Extreme Availability", e: "Achieving 99.999% uptime and 10Gbps speeds requires massive financial investment." },
    { q: "If a network architecture allows adding a new 500-user branch office by simply plugging in a new module, it demonstrates excellent:", o: ["Scalability", "Security", "Performance", "Cost Efficiency"], a: "Scalability", e: "Scalability allows massive growth without structural redesigns." },
    { q: "Implementing Network Address Translation (NAT) to hide internal IP addresses supports which objective?", o: ["Performance", "Security", "Flexibility", "Manageability"], a: "Security", e: "Hiding internal infrastructure details from the public internet is a security measure." },
    { q: "Which objective is severely compromised if administrators must manually configure each of the 500 switches in a company one by one?", o: ["Manageability", "Performance", "Availability", "Reliability"], a: "Manageability", e: "Manual configuration of large networks destroys manageability; automation is required." },
    { q: "Using Quality of Service (QoS) to prioritize voice over email traffic ensures the network meets its _________ objectives.", o: ["Security", "Performance", "Cost Efficiency", "Scalability"], a: "Performance", e: "QoS directly impacts the performance of real-time applications." },
    { q: "A 'Single Point of Failure' (SPOF) is the absolute enemy of which design objective?", o: ["Flexibility", "Reliability", "Manageability", "Cost Efficiency"], a: "Reliability", e: "A SPOF means if one device fails, the network fails, destroying reliability." },
    { q: "Purchasing 'Energy-efficient' switches with lower cooling requirements primarily targets which objective?", o: ["Security", "Cost Efficiency", "Performance", "Scalability"], a: "Cost Efficiency", e: "Lowering power and cooling bills directly improves long-term cost efficiency (OpEx)." },

    // --- Scalability & Documentation (15 Qns) ---
    { q: "What is 'Scale-Out' also known as?", o: ["Vertical Scalability", "Horizontal Scalability", "Downward Scalability", "Static Scalability"], a: "Horizontal Scalability", e: "Scale-Out refers to adding more physical or virtual nodes (Horizontal)." },
    { q: "Upgrading a server's RAM from 16GB to 64GB is an example of:", o: ["Scale-Out", "Horizontal Scalability", "Vertical Scalability", "Network Redundancy"], a: "Vertical Scalability", e: "Scale-Up (Vertical) means increasing the resources of an existing single machine." },
    { q: "Which type of scalability generally provides better 'Fault Tolerance'?", o: ["Vertical Scalability", "Horizontal Scalability", "Neither", "Both equally"], a: "Horizontal Scalability", e: "Horizontal scalability adds more machines, meaning if one dies, the others take over." },
    { q: "What is a major limitation of Vertical Scalability?", o: ["It requires buying 100 servers at once.", "Every machine has a physical maximum limit on how much RAM/CPU can be installed.", "It cannot be done on a Sunday.", "It makes the network wireless."], a: "Every machine has a physical maximum limit on how much RAM/CPU can be installed.", e: "Vertical scaling eventually hits a hardware ceiling." },
    { q: "Adding three new web servers behind a Load Balancer to handle holiday traffic is:", o: ["Vertical Scalability", "Horizontal Scalability", "Physical Redesign", "VLAN Trimming"], a: "Horizontal Scalability", e: "Adding more identical nodes to share the load is horizontal scaling." },
    { q: "Which document specifically maps out the exact port connections, such as 'Switch 1 Port 24 connects to Server B'?", o: ["Logical Network Diagram", "Physical Network Diagram", "Security Policy", "Operational Guide"], a: "Physical Network Diagram", e: "Physical diagrams map exact physical cables and port connections." },
    { q: "An 'IP Addressing Scheme' and 'VLAN assignments' are components of:", o: ["Physical Network Documentation", "Logical Network Documentation", "Operational Documentation", "Security Documentation"], a: "Logical Network Documentation", e: "Logical documentation focuses on how data flows logically via IP and subnets." },
    { q: "Why is 'Operational Documentation' critical for an IT department?", o: ["It shows where cables are physically buried.", "It outlines daily procedures, backup schedules, and standard maintenance tasks.", "It lists the MAC addresses of all devices.", "It generates encryption keys."], a: "It outlines daily procedures, backup schedules, and standard maintenance tasks.", e: "Operational docs guide the day-to-day running of the network." },
    { q: "If an administrator needs to restore a router that crashed, which specific documentation holds the commands needed?", o: ["Security Documentation", "Configuration Documentation", "Physical Documentation", "Logical Documentation"], a: "Configuration Documentation", e: "Configuration docs contain the exact CLI commands or backup files for device settings." },
    { q: "What is the primary danger of having 'Outdated' Network Documentation?", o: ["It takes up too much hard drive space.", "It can mislead administrators during an emergency, causing them to make fatal errors based on old topologies.", "It automatically unplugs cables.", "It causes the servers to run faster."], a: "It can mislead administrators during an emergency, causing them to make fatal errors based on old topologies.", e: "Wrong documentation is often worse than no documentation, leading to catastrophic mistakes." },
    { q: "A 'Rack Elevation Diagram' belongs to which category of documentation?", o: ["Physical Network Documentation", "Logical Network Documentation", "Configuration Documentation", "Operational Documentation"], a: "Physical Network Documentation", e: "Rack elevations show exactly where physical servers are mounted in the data center racks." },
    { q: "Which document would contain a list of 'Allowed IP addresses through the main firewall'?", o: ["Logical Documentation", "Security Documentation", "Physical Documentation", "Operational Documentation"], a: "Security Documentation", e: "Firewall rules and ACLs are central to Security Documentation." },
    { q: "In the context of scalability, why do companies prefer Cloud Computing?", o: ["Because cloud servers don't use electricity.", "Cloud computing offers virtually infinite and instant Horizontal Scalability.", "Because cloud networks don't need documentation.", "Because the cloud only uses Vertical Scalability."], a: "Cloud computing offers virtually infinite and instant Horizontal Scalability.", e: "The cloud allows spinning up hundreds of new servers (horizontal scaling) in seconds." },
    { q: "Which scalability method increases the complexity of management because there are more devices to monitor?", o: ["Vertical Scalability", "Horizontal Scalability", "Scale-Up", "CPU Upgrades"], a: "Horizontal Scalability", e: "More devices mean more endpoints to patch, monitor, and configure." },
    { q: "A network map showing OSPF areas and BGP autonomous systems is a type of:", o: ["Physical Diagram", "Logical Diagram", "Security Diagram", "Rack Diagram"], a: "Logical Diagram", e: "Routing protocols operate logically across the network, regardless of physical cable paths." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            const doc = {
                subjectId, moduleName, type: "MULTIPLE_CHOICE",
                category: categories[Math.floor(Math.random() * categories.length)],
                difficultyLevel: ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)],
                createdAt: new Date(),
                questionText: q.q,
                options: q.o.sort(() => Math.random() - 0.5),
                correctAnswer: q.a,
                explanation: q.e
            };
            const exists = await collection.findOne({ subjectId: doc.subjectId, questionText: doc.questionText });
            if (!exists) {
                await collection.insertOne(doc);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 1 (Batch 1 of Phase 1)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
