const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 5: Implementation & Troubleshooting";

const questions = [
    // --- Network Implementation Plan (15 questions) ---
    { questionText: "What is the primary purpose of a Network Implementation Plan?", options: ["To completely eliminate the need for future troubleshooting.", "To outline the steps, resources, and schedule required to deploy a network efficiently and systematically.", "To automatically configure all routers.", "To increase the implementation risks."], correctAnswer: "To outline the steps, resources, and schedule required to deploy a network efficiently and systematically.", explanation: "The plan serves as a roadmap to reduce risks, minimize downtime, and ensure proper coordination." },
    { questionText: "Which stage of the Network Implementation Plan involves 'identifying the number of users, applications, and expected network performance'?", options: ["Requirement Analysis", "Hardware Selection", "Procurement", "Testing and Verification"], correctAnswer: "Requirement Analysis", explanation: "Requirement analysis gathers all necessary technical and business constraints before any design begins." },
    { questionText: "At which stage of the Implementation Plan are network diagrams and IP addressing schemes created?", options: ["Network Design", "Deployment and Monitoring", "Procurement and Installation", "User Training"], correctAnswer: "Network Design", explanation: "The Network Design phase translates requirements into a detailed technical architecture and topology." },
    { questionText: "Selecting compatible routers, switches, and operating systems falls under which implementation step?", options: ["Requirement Analysis", "Hardware and Software Selection", "Testing and Verification", "Change Management"], correctAnswer: "Hardware and Software Selection", explanation: "This step ensures that the purchased equipment meets the design and capability requirements." },
    { questionText: "Physical installation, mounting devices in racks, and proper cable management occur during:", options: ["Security Implementation", "Network Configuration", "Procurement and Installation", "Testing and Verification"], correctAnswer: "Procurement and Installation", explanation: "Once hardware is selected and procured, it must be physically installed and cabled properly." },
    { questionText: "Assigning IP addresses, setting up VLANs, and implementing routing protocols happens in which phase?", options: ["Network Configuration", "Physical Installation", "Requirement Analysis", "Change Management"], correctAnswer: "Network Configuration", explanation: "Network configuration takes the physically installed devices and makes them logically communicative." },
    { questionText: "When should 'Security Implementation' (like firewalls and encryption) occur during the network deployment process?", options: ["Only after the network has been hacked once.", "It should be integrated into every stage of the implementation process, rather than added later.", "During the User Training phase exclusively.", "Only when purchasing the cables."], correctAnswer: "It should be integrated into every stage of the implementation process, rather than added later.", explanation: "Security must be a foundational component built into every step, not an afterthought." },
    { questionText: "Why is 'Testing and Verification' critical before making the network available to users?", options: ["It ensures that any identified issues are resolved, reducing the likelihood of operational problems after deployment.", "It automatically increases the bandwidth of the ISP.", "It eliminates the need for user passwords.", "It physically cools down the server room."], correctAnswer: "It ensures that any identified issues are resolved, reducing the likelihood of operational problems after deployment.", explanation: "Testing confirms that the configuration works as designed under load and securely." },
    { questionText: "Which phase simplifies future upgrades and helps new administrators understand the system?", options: ["Hardware Selection", "User Training and Documentation", "Monitoring", "Procurement"], correctAnswer: "User Training and Documentation", explanation: "Documentation provides a permanent record of network diagrams, IP schemas, and configurations." },
    { questionText: "Once testing is successfully completed, the network enters which final phase for operational use?", options: ["Deployment and Monitoring", "Requirement Analysis", "Network Design", "Hardware Selection"], correctAnswer: "Deployment and Monitoring", explanation: "The network goes live (Deployment) and must be continuously watched for faults (Monitoring)." },
    { questionText: "Which of the following is a Best Practice for Network Implementation?", options: ["Test network components only after deployment.", "Use scalable and reliable network designs.", "Avoid documentation to save time.", "Implement security controls only if there is a budget left over."], correctAnswer: "Use scalable and reliable network designs.", explanation: "Scalability and reliability are core best practices for a sustainable network deployment." },
    { questionText: "Why is 'Cable Management' and 'Equipment Labeling' emphasized during Procurement and Installation?", options: ["Because it makes the cables run faster.", "It helps simplify future maintenance and troubleshooting.", "It automatically configures the IP addresses.", "It encrypts the physical data."], correctAnswer: "It helps simplify future maintenance and troubleshooting.", explanation: "Messy cables make finding physical faults incredibly difficult. Labeling saves massive amounts of time." },
    { questionText: "Which implementation phase specifically addresses 'budget constraints' and 'future expansion needs'?", options: ["Testing", "Requirement Analysis", "User Training", "Monitoring"], correctAnswer: "Requirement Analysis", explanation: "The earliest phase must capture all limitations, including financial budgets." },
    { questionText: "Configuring wireless settings and establishing security policies is a core activity of:", options: ["Network Configuration", "Procurement", "Hardware Selection", "Documentation"], correctAnswer: "Network Configuration", explanation: "Configuration turns raw hardware into a functional, secure network." },
    { questionText: "What is the primary benefit of maintaining 'detailed documentation of configurations and procedures'?", options: ["It guarantees 100% uptime.", "It allows administrators to quickly track changes and restore systems during disaster recovery.", "It automatically updates router software.", "It reduces the cost of electricity."], correctAnswer: "It allows administrators to quickly track changes and restore systems during disaster recovery.", explanation: "Documentation is the blueprint for fixing catastrophic failures." },

    // --- Configuration Strategies (15 questions) ---
    { questionText: "What do 'Configuration Strategies' refer to in IT environments?", options: ["Methods used solely to buy new routers.", "Systematic methods and practices used to set up, manage, and maintain hardware and software settings.", "The physical layout of cables in a server room.", "The process of troubleshooting a broken PC."], correctAnswer: "Systematic methods and practices used to set up, manage, and maintain hardware and software settings.", explanation: "Configuration management ensures systems are consistently and securely set up." },
    { questionText: "Which type of configuration involves using a common set of settings (like naming conventions) across similar devices?", options: ["Automated Configuration", "Standardized Configuration", "Baseline Configuration", "Security-Focused Configuration"], correctAnswer: "Standardized Configuration", explanation: "Standardization reduces effort by making all similar devices follow the exact same rules." },
    { questionText: "A 'Baseline Configuration' is best described as:", options: ["A configuration that applies only to physical cables.", "A predefined set of approved settings that serves as a reference point for deployment and maintenance.", "A script that automatically writes code.", "A configuration that completely blocks internet access."], correctAnswer: "A predefined set of approved settings that serves as a reference point for deployment and maintenance.", explanation: "Baselines are the 'known good' standard that administrators compare current settings against." },
    { questionText: "In a large organization, what is the main advantage of 'Centralized Configuration Management'?", options: ["Administrators must physically visit each switch.", "It distributes configurations and applies updates to multiple devices from one central location, improving efficiency.", "It isolates every device completely from the network.", "It prevents any changes from ever being made."], correctAnswer: "It distributes configurations and applies updates to multiple devices from one central location, improving efficiency.", explanation: "Centralized management saves massive amounts of time and prevents human error." },
    { questionText: "Which configuration strategy relies heavily on scripts and templates to speed up deployment and reduce human errors?", options: ["Manual Configuration", "Automated Configuration", "Trial-and-Error Configuration", "Baseline Configuration"], correctAnswer: "Automated Configuration", explanation: "Automation uses tools (like Ansible or Chef) to apply settings without manual typing." },
    { questionText: "Disabling unnecessary services and changing default passwords are key elements of which strategy?", options: ["Performance Optimization", "Security-Focused Configuration", "Capacity Planning", "Divide-and-Conquer"], correctAnswer: "Security-Focused Configuration", explanation: "Security configurations lock down the device to minimize the attack surface." },
    { questionText: "Why is 'Change Management' critical before implementing configuration changes?", options: ["Because it automatically updates all passwords.", "It ensures that modifications are planned, documented, and approved, preventing negative impacts on system performance.", "It skips the testing phase to save time.", "It forces the network to restart every day."], correctAnswer: "It ensures that modifications are planned, documented, and approved, preventing negative impacts on system performance.", explanation: "Unplanned changes cause the majority of network outages; change management controls this risk." },
    { questionText: "What is the purpose of 'Backup and Recovery Configuration'?", options: ["To physically replace old routers.", "To regularly save device settings so systems can be restored quickly after a failure.", "To monitor CPU temperatures.", "To delete old log files."], correctAnswer: "To regularly save device settings so systems can be restored quickly after a failure.", explanation: "If a router dies, having its configuration backed up allows instant restoration on a new router." },
    { questionText: "What role does 'Monitoring and Auditing' play in configuration management?", options: ["It provides physical security guards for the server room.", "It compares current settings against approved baselines to detect unauthorized changes.", "It generates electricity for the switches.", "It automatically creates new VLANs."], correctAnswer: "It compares current settings against approved baselines to detect unauthorized changes.", explanation: "Auditing ensures that devices haven't drifted from their secure, approved baseline configurations." },
    { questionText: "Which of the following is considered a 'Best Practice' for configuration strategies?", options: ["Implement strong security settings by default.", "Always use manual configuration for large networks.", "Make changes directly without documentation.", "Never back up configurations until a device fails."], correctAnswer: "Implement strong security settings by default.", explanation: "Default strong security (Fail-Safe Defaults) prevents immediate compromise upon deployment." },
    { questionText: "Why should configuration changes be tested in a 'controlled environment' before live deployment?", options: ["To increase the cost of deployment.", "To ensure the change doesn't accidentally cause a network outage in the live production environment.", "To permanently delete old backups.", "Because live deployment is illegal."], correctAnswer: "To ensure the change doesn't accidentally cause a network outage in the live production environment.", explanation: "Testing in a lab (sandbox) catches fatal errors before they affect real users." },
    { questionText: "What is an immediate benefit of 'Automated Configuration' in large-scale data centers?", options: ["It physically mounts the servers into racks.", "It ensures consistency across thousands of systems and deploys them rapidly.", "It cools down the servers faster.", "It replaces the need for an internet connection."], correctAnswer: "It ensures consistency across thousands of systems and deploys them rapidly.", explanation: "Automation removes the slow, error-prone human element when configuring massive numbers of devices." },
    { questionText: "If an administrator identifies a rogue admin changing firewall rules, which strategy failed or caught the issue?", options: ["Monitoring and Auditing", "Hardware Selection", "Cable Management", "Performance Optimization"], correctAnswer: "Monitoring and Auditing", explanation: "Auditing tracks who changed what, identifying unauthorized configuration drift." },
    { questionText: "Which element must be maintained to ensure continuity when personnel changes occur within the IT organization?", options: ["Accurate Documentation Strategy", "Automated Scripts only", "Physical keys to the server room", "Default passwords"], correctAnswer: "Accurate Documentation Strategy", explanation: "When admins leave, documentation is the only way new staff can understand the existing configurations." },
    { questionText: "Scheduling a 'maintenance window' is a crucial step in which configuration strategy?", options: ["Change Management Strategy", "Automated Configuration", "Baseline Strategy", "Standardization Strategy"], correctAnswer: "Change Management Strategy", explanation: "Maintenance windows ensure that changes are applied when they will cause the least disruption to users." },

    // --- Monitoring Tools Deep Dive (20 questions) ---
    { questionText: "What is the primary function of Monitoring Tools in an IT environment?", options: ["To compile software code.", "To observe, analyze, and manage the performance, availability, and security of systems in real-time.", "To physically clean the inside of servers.", "To generate IP addresses."], correctAnswer: "To observe, analyze, and manage the performance, availability, and security of systems in real-time.", explanation: "Monitoring tools act as the 'eyes and ears' of the administrator, tracking system health constantly." },
    { questionText: "Why is continuous monitoring critical in modern IT environments?", options: ["Because without it, detecting performance issues, hardware failures, or security threats before they affect users is very difficult.", "Because it stops users from accessing the internet.", "Because it physically repairs broken cables.", "Because it reduces the cost of internet bandwidth."], correctAnswer: "Because without it, detecting performance issues, hardware failures, or security threats before they affect users is very difficult.", explanation: "Proactive monitoring allows admins to fix problems before users even notice them." },
    { questionText: "Which type of tool observes bandwidth usage, packet loss, and latency on routers and switches?", options: ["System Monitoring Tools", "Application Monitoring Tools", "Network Monitoring Tools", "Security Monitoring Tools"], correctAnswer: "Network Monitoring Tools", explanation: "Network monitoring specifically tracks traffic flow and hardware connectivity." },
    { questionText: "SolarWinds, PRTG, and Nagios are prominent examples of which type of monitoring tool?", options: ["Database Optimization Tools", "Network Monitoring Tools", "Physical Security Tools", "Web Browsers"], correctAnswer: "Network Monitoring Tools", explanation: "These are industry-standard platforms for monitoring network infrastructure." },
    { questionText: "Which type of monitoring tool tracks CPU usage, memory utilization, and disk activity on a specific server?", options: ["Application Monitoring Tools", "Network Monitoring Tools", "System Monitoring Tools", "Security Monitoring Tools"], correctAnswer: "System Monitoring Tools", explanation: "System monitoring looks inward at the server's local hardware resources." },
    { questionText: "Windows Performance Monitor and Linux System Monitor are examples of:", options: ["System Monitoring Tools", "Network Monitoring Tools", "Application Monitoring Tools", "Capacity Planning Tools"], correctAnswer: "System Monitoring Tools", explanation: "These built-in OS tools track local system health (CPU, RAM, Disk)." },
    { questionText: "If a developer wants to monitor software response times, transaction processing, and user activity errors, which tool should they use?", options: ["Network Monitoring Tools", "Application Monitoring Tools", "System Monitoring Tools", "Cable Testers"], correctAnswer: "Application Monitoring Tools", explanation: "Application Performance Monitoring (APM) tools focus specifically on how the software code is performing." },
    { questionText: "AppDynamics, Dynatrace, and New Relic are examples of:", options: ["Network Routers", "Application Monitoring Tools", "System Operating Systems", "Hardware Load Balancers"], correctAnswer: "Application Monitoring Tools", explanation: "These are leading APM platforms used to trace software transaction bottlenecks." },
    { questionText: "Which type of monitoring tool analyzes logs and network traffic specifically to detect malware infections and unauthorized access?", options: ["Security Monitoring Tools", "System Monitoring Tools", "Performance Monitoring Tools", "Capacity Planning Tools"], correctAnswer: "Security Monitoring Tools", explanation: "Security monitoring (like SIEMs) hunt for anomalies indicating a cyber attack." },
    { questionText: "Splunk, Snort, OSSEC, and IBM QRadar are examples of:", options: ["Application Monitoring Tools", "Security Monitoring Tools", "Hardware Switches", "Network Cables"], correctAnswer: "Security Monitoring Tools", explanation: "These are powerful security tools (SIEMs and IDSs) used to detect threats." },
    { questionText: "What is the primary benefit of 'Real-Time Monitoring'?", options: ["It provides historical data from last year.", "It gives immediate visibility into current system conditions, allowing quick responses to failures.", "It completely replaces the need for a firewall.", "It automatically purchases new servers."], correctAnswer: "It gives immediate visibility into current system conditions, allowing quick responses to failures.", explanation: "Real-time visibility means instant awareness of outages or spikes." },
    { questionText: "When predefined thresholds (like CPU reaching 95%) are exceeded, what crucial feature of monitoring tools is triggered?", options: ["Automated configuration", "Alerting and Notification", "Hardware shutdown", "Capacity planning"], correctAnswer: "Alerting and Notification", explanation: "Alerts (via SMS, email) wake up administrators so they can address critical thresholds." },
    { questionText: "Why is 'Logging and Reporting' an essential feature of monitoring tools?", options: ["It provides valuable historical information for troubleshooting, auditing, and compliance.", "It automatically deletes old databases.", "It blocks unauthorized IP addresses.", "It writes new software applications."], correctAnswer: "It provides valuable historical information for troubleshooting, auditing, and compliance.", explanation: "Logs are the permanent record used to investigate past incidents or prove regulatory compliance." },
    { questionText: "Which monitoring feature helps organizations forecast future resource requirements based on expected growth?", options: ["Real-time alerts", "Capacity Planning support", "Application code tracing", "Intrusion detection"], correctAnswer: "Capacity Planning support", explanation: "By analyzing historical trends, admins can plan when to buy more storage or bandwidth (Capacity Planning)." },
    { questionText: "A best practice for using monitoring tools is to configure 'meaningful alert thresholds'. Why is this important?", options: ["To ensure the administrator receives thousands of emails an hour.", "To prevent 'alert fatigue' by only notifying staff when a genuinely critical issue occurs.", "To disable the monitoring tool entirely.", "To ensure the server shuts down on its own."], correctAnswer: "To prevent 'alert fatigue' by only notifying staff when a genuinely critical issue occurs.", explanation: "If thresholds are too low, admins get spammed with useless alerts and start ignoring them (alert fatigue)." },
    { questionText: "Which monitoring tool would immediately notify you if an interface on your main Core Router goes down?", options: ["AppDynamics", "Nagios / PRTG", "Windows Performance Monitor", "Snort"], correctAnswer: "Nagios / PRTG", explanation: "Network monitoring tools (Nagios, PRTG, SolarWinds) specifically monitor router interface statuses." },
    { questionText: "If you want to track whether your web server's SQL database queries are taking too long to execute, you need:", options: ["Network Monitoring", "Application Monitoring", "Physical Security Monitoring", "Bandwidth Monitoring"], correctAnswer: "Application Monitoring", explanation: "APM tools trace transactions down to the exact SQL query slowing down the app." },
    { questionText: "SIEM (Security Information and Event Management) systems primarily fall under which category?", options: ["Performance Monitoring", "Security Monitoring", "Application Monitoring", "Capacity Planning"], correctAnswer: "Security Monitoring", explanation: "SIEMs aggregate and analyze security logs from across the entire network." },
    { questionText: "Dashboards and visual graphs are key features of monitoring tools because:", options: ["They allow administrators to quickly visualize complex data and spot anomalies at a glance.", "They replace the need for an operating system.", "They increase the CPU speed of the server.", "They physically map the server room layout."], correctAnswer: "They allow administrators to quickly visualize complex data and spot anomalies at a glance.", explanation: "Visualizations turn millions of log entries into easily digestible trends." },
    { questionText: "Which of the following is NOT a best practice for monitoring tools?", options: ["Monitor critical devices continuously.", "Integrate monitoring with incident response procedures.", "Review logs and reports regularly.", "Ignore alerts that happen outside of business hours."], correctAnswer: "Ignore alerts that happen outside of business hours.", explanation: "Ignoring alerts defeats the purpose of monitoring. Critical alerts must be addressed 24/7." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            q.category = categories[Math.floor(Math.random() * categories.length)];
            q.type = "MULTIPLE_CHOICE";
            q.difficultyLevel = ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)];
            q.createdAt = new Date();
            
            const exists = await collection.findOne({ 
                subjectId: q.subjectId, 
                questionText: q.questionText 
            });
            if (!exists) {
                await collection.insertOne(q);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 5 (Batch 1)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
