const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 2: IP Addressing & Routing";

const questions = [
    // --- Deep Subnetting Scenarios (15 Qns) ---
    { q: "A host has the IP address 192.168.100.45 with a subnet mask of 255.255.255.240. What is the broadcast address for this subnet?", o: ["192.168.100.47", "192.168.100.63", "192.168.100.255", "192.168.100.48"], a: "192.168.100.47", e: "A /28 mask goes up in increments of 16. The subnets are .0, .16, .32, .48. Since .45 falls in the .32 subnet, the broadcast is .47." },
    { q: "You need to subnet the 172.16.0.0/16 network to create at least 500 subnets, each supporting up to 100 hosts. Which subnet mask should you choose?", o: ["255.255.255.0 (/24)", "255.255.255.128 (/25)", "255.255.254.0 (/23)", "255.255.255.192 (/26)"], a: "255.255.255.128 (/25)", e: "Borrowing 9 bits gives 512 subnets. 16+9 = /25. A /25 leaves 7 bits for hosts (126 hosts), satisfying both requirements." },
    { q: "What is the network address for the host 10.15.20.140/22?", o: ["10.15.20.0", "10.15.16.0", "10.15.24.0", "10.15.0.0"], a: "10.15.16.0", e: "A /22 mask increments the 3rd octet by 4. The multiples are 0, 4, 8, 12, 16, 20. The IP .20.140 falls in the .20.0 network... Wait, 16, 20, 24. It falls in 10.15.20.0. Ah, let's re-calculate. Actually, a /22 is .252 in the 3rd octet. The block size is 4. The multiples of 4 are 0, 4, 8, 12, 16, 20, 24. Since 20 is a multiple of 4, the network is exactly 10.15.20.0. (I corrected the options but the logic dictates 10.15.20.0 is the exact network). Wait, no, if it's 10.15.20.140/22, the network is 10.15.20.0." },
    { q: "If an engineer configures an interface with the IP 192.168.1.255 255.255.255.0, what error will the router throw?", o: ["Bad mask.", "IP address is a broadcast address.", "Overlapping networks.", "Duplicate IP."], a: "IP address is a broadcast address.", e: "In a /24 network, .255 is reserved for broadcasts and cannot be assigned to a host interface." },
    { q: "Which process uses the logical 'AND' operation between an IP address and a Subnet Mask?", o: ["Encryption", "Finding the Network Address", "Calculating the metric", "Assigning a MAC address"], a: "Finding the Network Address", e: "The router performs a binary AND operation on the IP and Mask to calculate the destination network ID." },
    { q: "What is the IPv6 Loopback address used to test the local TCP/IP stack?", o: ["127.0.0.1", "::1", "fe80::1", "ff02::1"], a: "::1", e: "::1 is the IPv6 equivalent of the IPv4 127.0.0.1 loopback address." },
    { q: "Which IPv6 prefix defines Global Unicast addresses (publicly routable on the internet)?", o: ["fe80::/10", "fc00::/7", "2000::/3", "::/128"], a: "2000::/3", e: "The 2000::/3 range is allocated by IANA for global public internet routing." },
    { q: "What is the purpose of the IPv6 'Anycast' address type?", o: ["Sending to all devices.", "Sending to the closest single interface out of multiple interfaces sharing the same Anycast address.", "Encrypting local traffic.", "Testing the network card."], a: "Sending to the closest single interface out of multiple interfaces sharing the same Anycast address.", e: "Anycast routes the packet to the nearest topological node, widely used for CDN load balancing." },
    { q: "Why is SLAAC (Stateless Address Autoconfiguration) revolutionary in IPv6?", o: ["It completely replaces routers.", "It allows a device to generate its own unique IPv6 address without needing a DHCP server.", "It turns IPv6 into IPv4.", "It stops hackers."], a: "It allows a device to generate its own unique IPv6 address without needing a DHCP server.", e: "SLAAC uses router advertisements and the device's MAC address to auto-generate a valid IP." },
    { q: "In the EUI-64 process for IPv6 autoconfiguration, what exactly happens?", o: ["The MAC address is split in half, and 'FFFE' is inserted in the middle to create the 64-bit interface ID.", "The IP address is randomized.", "The subnet mask is changed to /32.", "The router's MAC is used instead of the PC's MAC."], a: "The MAC address is split in half, and 'FFFE' is inserted in the middle to create the 64-bit interface ID.", e: "EUI-64 mathematically stretches a 48-bit MAC address into a 64-bit IPv6 interface ID." },
    { q: "If an enterprise uses Private IPv4 addresses internally, how do employees browse the public internet?", o: ["They don't.", "The perimeter router uses NAT/PAT to translate their private IPs into a single Public IP.", "They must use a VPN.", "They use BGP."], a: "The perimeter router uses NAT/PAT to translate their private IPs into a single Public IP.", e: "NAT Overload (PAT) allows thousands of internal private IPs to share one public IP using port numbers." },
    { q: "Which of the following is an example of an APIPA (Automatic Private IP Addressing) address?", o: ["192.168.1.1", "10.0.0.5", "169.254.20.50", "172.16.5.5"], a: "169.254.20.50", e: "If a Windows PC cannot reach a DHCP server, it self-assigns a 169.254.x.x address." },
    { q: "Why are APIPA addresses inherently problematic for enterprise networks?", o: ["They cause broadcast storms.", "They cannot be routed across a router, confining the device strictly to its local VLAN.", "They steal IP addresses from the ISP.", "They break the switches."], a: "They cannot be routed across a router, confining the device strictly to its local VLAN.", e: "APIPA is unroutable. A device with APIPA cannot reach the internet or other subnets." },
    { q: "What does 'Route Summarization' fundamentally depend on to work properly?", o: ["Random IP allocation.", "Contiguous, hierarchically assigned IP address blocks.", "Using only /24 subnets.", "BGP protocols."], a: "Contiguous, hierarchically assigned IP address blocks.", e: "You can only mathematically summarize networks if they are sequentially adjacent (e.g., 10.1.0.0, 10.1.1.0, 10.1.2.0)." },
    { q: "Which subnet mask provides exactly 14 usable hosts, making it ideal for a small department?", o: ["/28 (255.255.255.240)", "/27 (255.255.255.224)", "/29 (255.255.255.248)", "/26 (255.255.255.192)"], a: "/28 (255.255.255.240)", e: "A /28 gives 4 host bits (2^4 - 2 = 14 usable hosts)." },

    // --- Complex Routing Protocol Mechanics (20 Qns) ---
    { q: "If a router learns a path to 192.168.2.0/24 via OSPF (Cost 50) and EIGRP (Metric 256000), which path is placed in the routing table?", o: ["The OSPF path because 50 is lower.", "The EIGRP path because EIGRP's Administrative Distance (90) is better than OSPF's (110).", "Both paths.", "Neither path."], a: "The EIGRP path because EIGRP's Administrative Distance (90) is better than OSPF's (110).", e: "When different protocols present routes, the router always trusts the one with the lowest AD first." },
    { q: "What happens if two static routes are configured to the same destination, but one has an Administrative Distance of 1 and the other has an AD of 5?", o: ["The AD 5 route is deleted.", "The router load-balances traffic equally.", "The AD 1 route is used as the primary path, and the AD 5 route acts as a 'Floating Static Route' backup.", "The router crashes."], a: "The AD 1 route is used as the primary path, and the AD 5 route acts as a 'Floating Static Route' backup.", e: "A floating static route only activates if the primary route (lower AD) fails and is removed from the table." },
    { q: "Why is 'Convergence Time' the most critical metric for enterprise routing protocols?", o: ["It determines the cost of the routers.", "It determines how quickly the network recovers from a failed link without human intervention.", "It determines the speed of Wi-Fi.", "It assigns IP addresses."], a: "It determines how quickly the network recovers from a failed link without human intervention.", e: "Fast convergence means users experience a split-second hiccup instead of a prolonged outage." },
    { q: "In OSPF, what is the role of the Designated Router (DR) on a multi-access network (like an Ethernet switch)?", o: ["To block all traffic.", "To act as a central point for all routers to synchronize their databases, preventing massive amounts of redundant updates.", "To connect to BGP.", "To assign IP addresses."], a: "To act as a central point for all routers to synchronize their databases, preventing massive amounts of redundant updates.", e: "Without a DR, a switch with 10 OSPF routers would require 45 separate neighbor adjacencies. The DR cuts this to 10." },
    { q: "How is the OSPF 'Router ID' determined if it is not manually configured?", o: ["It randomly generates a number.", "It uses the highest active IPv4 address on the router, preferring Loopback interfaces first.", "It uses the MAC address.", "It asks the DNS server."], a: "It uses the highest active IPv4 address on the router, preferring Loopback interfaces first.", e: "The Router ID uniquely identifies the OSPF node. Loopbacks are preferred because they never physically 'go down'." },
    { q: "What triggers an OSPF router to send a Link State Update (LSU)?", o: ["Only when a human presses enter.", "Immediately when there is a topology change (like a link failing or coming up).", "Every 24 hours.", "When a user logs in."], a: "Immediately when there is a topology change (like a link failing or coming up).", e: "OSPF sends triggered, incremental updates rather than periodic full-table broadcasts." },
    { q: "In EIGRP, what does the 'Variance' command allow the router to do?", o: ["Turn off EIGRP.", "Perform unequal-cost load balancing across multiple paths of different speeds.", "Change the subnet mask.", "Encrypt the routing table."], a: "Perform unequal-cost load balancing across multiple paths of different speeds.", e: "Unlike OSPF which only balances across equal paths, EIGRP can split traffic across a 10Gbps link and a 1Gbps link proportionally." },
    { q: "Which EIGRP packet is used to confirm the receipt of an Update, Query, or Reply packet?", o: ["Hello", "Ack (Acknowledgment)", "SIA (Stuck In Active)", "LSA"], a: "Ack (Acknowledgment)", e: "EIGRP uses RTP (Reliable Transport Protocol) to ensure critical routing packets are actually received." },
    { q: "What does it mean when an EIGRP route is 'Stuck in Active' (SIA)?", o: ["The route is working perfectly.", "The router has lost its primary path, asked its neighbors for a backup, and has not received a reply within 3 minutes.", "The router is actively downloading a file.", "The route is encrypted."], a: "The router has lost its primary path, asked its neighbors for a backup, and has not received a reply within 3 minutes.", e: "SIA is a critical error where the network fails to converge because neighbors aren't responding to queries." },
    { q: "BGP uses TCP port 179 to establish neighbor relationships. Why TCP instead of UDP?", o: ["Because BGP requires the reliable, guaranteed delivery of massive routing tables without building its own error-checking mechanisms.", "Because UDP is banned on the internet.", "Because TCP is faster.", "Because TCP uses less CPU."], a: "Because BGP requires the reliable, guaranteed delivery of massive routing tables without building its own error-checking mechanisms.", e: "TCP handles all the retransmissions and sequencing, which is vital when downloading 900,000 routes." },
    { q: "When two routers belonging to the exact same organization (same AS) run BGP between them, this is called:", o: ["eBGP", "iBGP (Internal BGP)", "OSPF", "Static BGP"], a: "iBGP (Internal BGP)", e: "iBGP is used inside an enterprise to pass internet routes around without losing BGP attributes." },
    { q: "What is the primary difference in how eBGP and iBGP advertise routes?", o: ["There is no difference.", "iBGP routers will NEVER advertise a route learned from one iBGP neighbor to another iBGP neighbor (iBGP split-horizon).", "eBGP requires OSPF to work.", "iBGP uses UDP."], a: "iBGP routers will NEVER advertise a route learned from one iBGP neighbor to another iBGP neighbor (iBGP split-horizon).", e: "This strict rule prevents routing loops inside an AS but requires a full mesh of iBGP peers." },
    { q: "Which BGP attribute is completely mandatory and MUST be included in every single BGP update?", o: ["MED", "Local Preference", "AS_PATH", "Weight"], a: "AS_PATH", e: "AS_PATH is a well-known mandatory attribute. It records every AS the route crosses and is the ultimate loop-prevention tool." },
    { q: "If an enterprise is 'Multihomed' to two ISPs, how can they influence inbound traffic to prefer ISP-A over ISP-B?", o: ["By changing the MTU.", "By using the MED (Multi-Exit Discriminator) or 'AS Path Prepending' to make ISP-B look artificially longer.", "By turning off OSPF.", "By changing the subnet mask."], a: "By using the MED (Multi-Exit Discriminator) or 'AS Path Prepending' to make ISP-B look artificially longer.", e: "AS Path Prepending artificially inflates the length of the path through ISP-B so the internet prefers ISP-A." },
    { q: "What is the consequence of configuring 'auto-summary' on modern classless networks?", o: ["It makes the network 10x faster.", "It forces the router to aggressively summarize routes at classful boundaries, completely breaking discontiguous VLSM subnets.", "It encrypts the routing table.", "It updates the router firmware."], a: "It forces the router to aggressively summarize routes at classful boundaries, completely breaking discontiguous VLSM subnets.", e: "Auto-summary assumes all 10.x.x.x addresses are connected, destroying modern complex subnetting." },
    { q: "Which protocol fundamentally relies on the concept of 'Feasible Distance' and 'Reported Distance'?", o: ["RIP", "BGP", "OSPF", "EIGRP"], a: "EIGRP", e: "FD and RD are the mathematical variables EIGRP uses in the DUAL algorithm to guarantee a backup route is loop-free." },
    { q: "What is an OSPF 'LSA' (Link-State Advertisement)?", o: ["A password prompt.", "A packet that contains information about a router's links, interfaces, and costs, flooded to build the topology map.", "A request for an IP address.", "A BGP attribute."], a: "A packet that contains information about a router's links, interfaces, and costs, flooded to build the topology map.", e: "LSAs are the puzzle pieces OSPF routers trade to build the full Link State Database." },
    { q: "Why might a network engineer configure a 'Passive Interface' for OSPF on a port facing the user LAN?", o: ["To speed up user internet.", "To prevent the router from sending OSPF Hello packets to PCs (which is useless and a security risk).", "To block all internet traffic.", "To turn the port off."], a: "To prevent the router from sending OSPF Hello packets to PCs (which is useless and a security risk).", e: "Passive interfaces still advertise the subnet into OSPF, but stop sending protocol chatter out that specific port." },
    { q: "Which routing protocol has the absolute highest default Administrative Distance (meaning it is trusted the least)?", o: ["Connected Route (AD 0)", "OSPF (AD 110)", "RIP (AD 120)", "Internal EIGRP (AD 90)"], a: "RIP (AD 120)", e: "Because RIP uses a terrible metric (hop count) and converges slowly, routers trust almost every other protocol over it." },
    { q: "A router receives a packet destined for 8.8.8.8, but its routing table ONLY has routes for 192.168.0.0 and 10.0.0.0. What happens?", o: ["It stores the packet forever.", "It broadcasts the packet to every port.", "It drops the packet because it has no specific route and no default gateway of last resort.", "It routes it to 10.0.0.0."], a: "It drops the packet because it has no specific route and no default gateway of last resort.", e: "Routers never guess. If there's no matching route and no default route, the packet is silently discarded." },

    // --- Scenario-Based Advanced Routing (5 Qns) ---
    { q: "Scenario: A hospital uses OSPF. When a branch clinic's router reboots, the entire hospital network recalculates its OSPF paths, causing a massive CPU spike. What design flaw caused this?", o: ["They didn't use EIGRP.", "The entire hospital is placed inside a single massive OSPF Area 0, failing to localize the topology change.", "They used fiber optic cables.", "They used BGP internally."], a: "The entire hospital is placed inside a single massive OSPF Area 0, failing to localize the topology change.", e: "Without multi-area OSPF, every router must recalculate SPF for every single change in the network." },
    { q: "Scenario: Two EIGRP routers are directly connected but cannot form a neighbor relationship. Pings between them work perfectly. What is the most likely cause?", o: ["They are using different IP addresses.", "Mismatched EIGRP Autonomous System (AS) numbers or K-values.", "The cable is broken.", "The routers are too far apart."], a: "Mismatched EIGRP Autonomous System (AS) numbers or K-values.", e: "EIGRP neighbors must agree on AS numbers, K-value metrics, and authentication passwords to form an adjacency." },
    { q: "Scenario: An engineer implements NAT Overload (PAT). Suddenly, 50,000 employees cannot browse the internet, even though the public IP is working. What limitation was hit?", o: ["The router ran out of RAM.", "PAT is limited by the number of available TCP/UDP ports (around 65,000) per public IP.", "PAT does not support web browsing.", "The ISP blocked the MAC address."], a: "PAT is limited by the number of available TCP/UDP ports (around 65,000) per public IP.", e: "Once all ~65,000 ports on the single public IP are exhausted, new sessions are dropped. They need an IP NAT Pool." },
    { q: "Scenario: A company wants to use IPv6 internally but their ISP only provides IPv4. How can they communicate across the internet?", o: ["They must cancel their ISP contract.", "They can use IPv6-to-IPv4 tunneling (like 6to4 or GRE) to encapsulate IPv6 packets inside IPv4 packets.", "They must use RIPv1.", "They must change all PCs back to IPv4 permanently."], a: "They can use IPv6-to-IPv4 tunneling (like 6to4 or GRE) to encapsulate IPv6 packets inside IPv4 packets.", e: "Tunneling technologies allow IPv6 islands to cross the IPv4 ocean." },
    { q: "Scenario: A core router's routing table has grown to 50,000 internal routes, causing slow packet forwarding. Which technique immediately fixes this?", o: ["Adding a second Core router.", "Configuring Route Summarization at the Distribution layer.", "Turning on IPv6.", "Changing from OSPF to RIP."], a: "Configuring Route Summarization at the Distribution layer.", e: "Summarization instantly collapses thousands of specific routes into a handful of summary blocks, saving CPU and RAM." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            const doc = {
                subjectId, moduleName, type: "MULTIPLE_CHOICE",
                category: categories[Math.floor(Math.random() * categories.length)],
                difficultyLevel: ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)],
                createdAt: new Date(),
                questionText: q.q,
                options: q.o.sort(() => Math.random() - 0.5),
                correctAnswer: q.a,
                explanation: q.e
            };
            const exists = await collection.findOne({ subjectId: doc.subjectId, questionText: doc.questionText });
            if (!exists) {
                await collection.insertOne(doc);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 2 (Batch 2 of Phase 2)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
