const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 4: Advanced Network Design";

const questions = [
    // --- Advanced Network Security (20 Qns) ---
    { q: "What is the core principle of the 'CIA Triad' in network security?", o: ["Cost, Integration, Automation", "Confidentiality, Integrity, Availability", "Cisco, Intel, Apple", "Control, Intelligence, Analytics"], a: "Confidentiality, Integrity, Availability", e: "The CIA Triad forms the foundational baseline of all security policies and designs." },
    { q: "Which security mechanism strictly ensures 'Confidentiality'?", o: ["Redundant power supplies.", "Encryption (like AES-256) of data in transit.", "Hashing (like SHA-256).", "Load balancing."], a: "Encryption (like AES-256) of data in transit.", e: "Encryption ensures that even if data is intercepted, it cannot be read without the key." },
    { q: "Which security mechanism strictly ensures 'Integrity'?", o: ["Cryptographic Hashing (like SHA-256).", "Uninterruptible Power Supplies (UPS).", "Data encryption.", "Subnetting."], a: "Cryptographic Hashing (like SHA-256).", e: "Hashing proves that the data was not altered or corrupted while in transit." },
    { q: "What is the security principle of 'Least Privilege'?", o: ["Giving everyone Administrator access to save time.", "Granting users and systems only the absolute bare minimum access permissions necessary to perform their specific job functions.", "Using the cheapest possible firewall.", "Blocking all internet access."], a: "Granting users and systems only the absolute bare minimum access permissions necessary to perform their specific job functions.", e: "Least privilege minimizes the damage a compromised account or malware can inflict." },
    { q: "Which of the following is a physical implementation of 'Defense in Depth'?", o: ["A single strong password.", "Using a locked fence, a biometric door scanner, a mantrap, and a locked server cabinet.", "Using only Wi-Fi.", "Disabling all firewalls."], a: "Using a locked fence, a biometric door scanner, a mantrap, and a locked server cabinet.", e: "Defense in Depth layers multiple independent security controls so if one fails, others remain." },
    { q: "In a network context, what does a 'Next-Generation Firewall (NGFW)' do that a traditional port-based firewall cannot?", o: ["It blocks IP addresses.", "It performs Deep Packet Inspection (DPI) to identify and block specific applications (like BitTorrent or Facebook) regardless of the port they use.", "It provides PoE power.", "It calculates OSPF routes."], a: "It performs Deep Packet Inspection (DPI) to identify and block specific applications (like BitTorrent or Facebook) regardless of the port they use.", e: "Traditional firewalls only look at Ports (e.g., Block 80). NGFWs look inside the packet to see the actual application." },
    { q: "What is the primary difference between an IDS (Intrusion Detection System) and an IPS (Intrusion Prevention System)?", o: ["IDS only detects and alerts about malicious traffic; IPS actively drops and blocks the malicious traffic.", "IDS is for hardware; IPS is for software.", "IDS is faster than IPS.", "There is no difference."], a: "IDS only detects and alerts about malicious traffic; IPS actively drops and blocks the malicious traffic.", e: "Prevention (IPS) sits inline with the traffic and stops attacks in real-time." },
    { q: "Where is the most strategic place to deploy an IPS (Intrusion Prevention System)?", o: ["On a user's laptop.", "At the Enterprise Edge (Perimeter) or the Data Center Core, where all traffic chokepoints exist.", "Inside a physical safe.", "On a guest Wi-Fi network."], a: "At the Enterprise Edge (Perimeter) or the Data Center Core, where all traffic chokepoints exist.", e: "Placing IPS at chokepoints ensures all entering or leaving traffic is inspected." },
    { q: "What does 'Network Access Control' (NAC) like Cisco ISE do?", o: ["It encrypts the internet.", "It authenticates devices BEFORE they are allowed to join the network, checking their antivirus status and assigning them to the correct VLAN.", "It prevents physical access to the building.", "It acts as a load balancer."], a: "It authenticates devices BEFORE they are allowed to join the network, checking their antivirus status and assigning them to the correct VLAN.", e: "NAC ensures only healthy, authorized devices can connect to the switch ports or Wi-Fi." },
    { q: "Which protocol is heavily used by NAC systems to authenticate users at the switch port level?", o: ["BGP", "802.1X", "OSPF", "Spanning Tree"], a: "802.1X", e: "802.1X is the IEEE standard for port-based Network Access Control." },
    { q: "What is a 'DMZ' (Demilitarized Zone) in network security?", o: ["A secure room for the CEO.", "An isolated network segment that hosts public-facing servers (like Web and Email) separate from the highly secure internal network.", "A wireless network.", "A type of encryption."], a: "An isolated network segment that hosts public-facing servers (like Web and Email) separate from the highly secure internal network.", e: "The DMZ acts as a buffer. If a web server is hacked, the hacker still cannot easily reach the internal databases." },
    { q: "Why is 'Micro-Segmentation' considered a massive leap forward in Data Center security?", o: ["Because it shrinks the physical servers.", "Because it places a firewall boundary around every single Virtual Machine, stopping threats from moving laterally inside the data center.", "Because it uses IPv6.", "Because it blocks all internet traffic."], a: "Because it places a firewall boundary around every single Virtual Machine, stopping threats from moving laterally inside the data center.", e: "Traditional security only protected the perimeter. Micro-segmentation protects everything internally." },
    { q: "What is a 'DDoS' (Distributed Denial of Service) attack?", o: ["A hacker guessing a password.", "A coordinated attack using thousands of compromised computers (a botnet) to flood a target with traffic, overwhelming its bandwidth or CPU.", "A virus that deletes files.", "A physical cut of a fiber cable."], a: "A coordinated attack using thousands of compromised computers (a botnet) to flood a target with traffic, overwhelming its bandwidth or CPU.", e: "DDoS attacks aim to destroy Availability (the 'A' in the CIA triad)." },
    { q: "How do modern networks mitigate massive volumetric DDoS attacks?", o: ["By turning off the routers.", "By using Cloud-based 'Scrubbing Centers' that absorb the massive traffic, filter out the bad packets, and forward only the clean traffic to the enterprise.", "By changing IP addresses daily.", "By using smaller cables."], a: "By using Cloud-based 'Scrubbing Centers' that absorb the massive traffic, filter out the bad packets, and forward only the clean traffic to the enterprise.", e: "On-premises firewalls are useless against DDoS because the ISP link itself gets overwhelmed first." },
    { q: "What is 'IPsec' primarily used for?", o: ["Speeding up video games.", "Creating highly secure, encrypted Virtual Private Network (VPN) tunnels across untrusted public networks like the internet.", "Assigning IP addresses.", "Calculating OSPF metrics."], a: "Creating highly secure, encrypted Virtual Private Network (VPN) tunnels across untrusted public networks like the internet.", e: "IPsec operates at Layer 3 to provide encryption and authentication for IP packets." },
    { q: "What does an 'Endpoint Detection and Response' (EDR) agent do?", o: ["It blocks spam emails.", "It runs on the user's laptop/PC, continuously monitoring for advanced malware and malicious behaviors that bypassed the network firewalls.", "It configures the switch.", "It provides Wi-Fi."], a: "It runs on the user's laptop/PC, continuously monitoring for advanced malware and malicious behaviors that bypassed the network firewalls.", e: "EDR is the last line of defense when the network perimeter fails." },
    { q: "Why is 'Two-Factor Authentication' (2FA) or MFA critical for VPN access?", o: ["It makes logging in faster.", "Because passwords can be easily stolen; MFA requires a second, physical proof of identity (like a phone app code) to grant access.", "Because it encrypts the password.", "Because it uses less bandwidth."], a: "Because passwords can be easily stolen; MFA requires a second, physical proof of identity (like a phone app code) to grant access.", e: "Compromised credentials are the #1 cause of breaches. MFA stops them." },
    { q: "What is a 'Honeypot' in network security?", o: ["A server full of actual sensitive data.", "A decoy system intentionally designed to look vulnerable, used to attract hackers and study their attack methods.", "A type of firewall.", "A fast router."], a: "A decoy system intentionally designed to look vulnerable, used to attract hackers and study their attack methods.", e: "Honeypots act as early warning systems." },
    { q: "Which of the following is a 'Social Engineering' attack?", o: ["A DDoS attack.", "A hacker calling the IT helpdesk pretending to be the CEO who forgot their password to trick the technician into resetting it.", "A virus destroying a hard drive.", "A physical cable cut."], a: "A hacker calling the IT helpdesk pretending to be the CEO who forgot their password to trick the technician into resetting it.", e: "Social engineering attacks humans, not technology, because humans are the weakest link." },
    { q: "What is 'Ransomware'?", o: ["A free antivirus software.", "Malware that encrypts all the data on a company's network and demands a financial payment to provide the decryption key.", "A routing protocol.", "A type of VPN."], a: "Malware that encrypts all the data on a company's network and demands a financial payment to provide the decryption key.", e: "Ransomware destroys Data Availability and can bankrupt a business." },

    // --- Quality of Service (QoS) & Performance Optimization (20 Qns) ---
    { q: "What is the fundamental purpose of 'Quality of Service' (QoS)?", o: ["To make all traffic equally fast.", "To classify, mark, and prioritize critical network traffic (like Voice) over less important traffic (like Web Browsing) during times of congestion.", "To encrypt data.", "To delete old files."], a: "To classify, mark, and prioritize critical network traffic (like Voice) over less important traffic (like Web Browsing) during times of congestion.", e: "QoS doesn't create more bandwidth; it simply decides who gets to use the existing bandwidth first." },
    { q: "Why does Voice over IP (VoIP) absolutely require QoS?", o: ["Because VoIP uses too much bandwidth.", "Because Voice traffic is incredibly sensitive to Delay (Latency) and Jitter; if packets arrive late or out of order, the conversation becomes unintelligible.", "Because Voice cannot be encrypted.", "Because VoIP uses IPv6."], a: "Because Voice traffic is incredibly sensitive to Delay (Latency) and Jitter; if packets arrive late or out of order, the conversation becomes unintelligible.", e: "Real-time traffic cannot be buffered or retransmitted like an email." },
    { q: "In QoS, what is 'Latency'?", o: ["The amount of data transferred.", "The absolute time it takes for a packet to travel from the source to the destination.", "The variation in delay.", "The speed of the router CPU."], a: "The absolute time it takes for a packet to travel from the source to the destination.", e: "High latency causes frustrating delays in conversation (e.g., over satellite links)." },
    { q: "What is 'Jitter' in a network?", o: ["The physical shaking of the router.", "The variation in latency (delay) between consecutive packets arriving at the destination.", "The total bandwidth available.", "The time it takes to boot up."], a: "The variation in latency (delay) between consecutive packets arriving at the destination.", e: "Jitter causes choppy, robotic-sounding voice calls because the audio frames do not arrive smoothly." },
    { q: "How do VoIP phones compensate for minor Jitter?", o: ["They drop the call immediately.", "They use a 'Jitter Buffer' to temporarily store packets and play them out at a smooth, constant rate.", "They increase the internet speed.", "They change their IP address."], a: "They use a 'Jitter Buffer' to temporarily store packets and play them out at a smooth, constant rate.", e: "The buffer smooths out the bumps, but if the jitter is too large, the buffer overflows and audio drops." },
    { q: "Which QoS mechanism identifies traffic (e.g., recognizing that a packet is a VoIP packet)?", o: ["Marking", "Classification", "Queuing", "Shaping"], a: "Classification", e: "Classification is the first step. You must identify what the traffic is before you can treat it." },
    { q: "After traffic is Classified, what does 'Marking' do?", o: ["It deletes the packet.", "It alters the IP header (e.g., using DSCP fields) to 'color' or 'tag' the packet, so downstream routers instantly know its priority level.", "It encrypts the packet.", "It changes the destination IP."], a: "It alters the IP header (e.g., using DSCP fields) to 'color' or 'tag' the packet, so downstream routers instantly know its priority level.", e: "Marking saves downstream routers from having to perform deep packet inspection again." },
    { q: "What is the standard DSCP (Differentiated Services Code Point) marking value used specifically for critical Voice (VoIP) traffic?", o: ["Default (0)", "AF31", "EF (Expedited Forwarding - 46)", "CS6"], a: "EF (Expedited Forwarding - 46)", e: "EF (DSCP 46) is the industry standard for telling routers 'Drop everything else and forward this Voice packet NOW'." },
    { q: "What does 'Queuing' (or Scheduling) do during periods of network congestion?", o: ["It randomly drops all packets.", "It places packets in different memory buffers (lines) based on their priority marking, and services the high-priority queues first.", "It increases the physical bandwidth.", "It restarts the router."], a: "It places packets in different memory buffers (lines) based on their priority marking, and services the high-priority queues first.", e: "Queuing ensures Voice packets skip the line and are sent out the interface before large file downloads." },
    { q: "Which queuing algorithm provides a strict, guaranteed bandwidth queue for Voice traffic, but can starve other traffic if not configured properly?", o: ["FIFO (First In First Out)", "Weighted Fair Queuing (WFQ)", "Strict Priority Queuing (PQ) or LLQ (Low Latency Queuing)", "Round Robin"], a: "Strict Priority Queuing (PQ) or LLQ (Low Latency Queuing)", e: "LLQ puts voice in a strict priority line that always goes first." },
    { q: "What is the primary difference between 'Traffic Shaping' and 'Traffic Policing'?", o: ["There is no difference.", "Shaping buffers (delays) excess traffic to smooth out the flow; Policing aggressively drops or remarks excess traffic immediately.", "Shaping drops traffic; Policing buffers it.", "Shaping is for WANs; Policing is for LANs."], a: "Shaping buffers (delays) excess traffic to smooth out the flow; Policing aggressively drops or remarks excess traffic immediately.", e: "Shaping prevents packet loss by holding data in RAM. Policing acts like a harsh speed limit." },
    { q: "When is 'Traffic Shaping' most commonly used?", o: ["On local LAN switches.", "On a router's WAN interface to prevent sending traffic faster than the ISP's contracted speed limit, avoiding ISP packet drops.", "To speed up video games.", "To block hackers."], a: "On a router's WAN interface to prevent sending traffic faster than the ISP's contracted speed limit, avoiding ISP packet drops.", e: "If your router's port is 1Gbps but you only pay the ISP for 100Mbps, you must Shape the traffic to 100Mbps." },
    { q: "What does 'WRED' (Weighted Random Early Detection) do in QoS?", o: ["It guarantees voice quality.", "It proactively drops low-priority TCP packets before the queue becomes 100% full, preventing 'Tail Drop' and global TCP synchronization.", "It increases bandwidth.", "It encrypts data."], a: "It proactively drops low-priority TCP packets before the queue becomes 100% full, preventing 'Tail Drop' and global TCP synchronization.", e: "WRED acts as a pressure relief valve, signaling TCP senders to slow down gracefully." },
    { q: "Why is UDP traffic (like Voice/Video) NOT affected by WRED packet drops?", o: ["Because UDP is encrypted.", "Because UDP has no retransmission or windowing mechanism; dropping UDP does not tell the sender to slow down.", "Because UDP is faster than TCP.", "Because UDP is immune to network congestion."], a: "Because UDP has no retransmission or windowing mechanism; dropping UDP does not tell the sender to slow down.", e: "WRED targets TCP because TCP inherently slows down when it detects a dropped packet." },
    { q: "What is a 'Trust Boundary' in a QoS design?", o: ["A firewall.", "The specific point in the network (usually the Access Switch) where the network stops trusting endpoint markings and begins classifying/marking traffic itself.", "A VPN tunnel.", "A BGP peer."], a: "The specific point in the network (usually the Access Switch) where the network stops trusting endpoint markings and begins classifying/marking traffic itself.", e: "You cannot trust a user's PC because they could mark their torrent downloads as 'Voice' to get faster speeds." },
    { q: "Which layer of the OSI model does QoS primarily operate in when reading DSCP values?", o: ["Layer 1 (Physical)", "Layer 2 (Data Link)", "Layer 3 (Network - IP Header)", "Layer 7 (Application)"], a: "Layer 3 (Network - IP Header)", e: "DSCP is a 6-bit field located inside the Layer 3 IPv4 or IPv6 header." },
    { q: "What is the Layer 2 (VLAN tag) equivalent of Layer 3 DSCP markings?", o: ["MAC Address", "Class of Service (CoS) / 802.1p", "EtherType", "FCS Checksum"], a: "Class of Service (CoS) / 802.1p", e: "CoS provides 3 bits of QoS priority inside the 802.1q VLAN tag on switches." },
    { q: "If a company uses SD-WAN, how does it inherently improve QoS without traditional queuing?", o: ["By turning off the internet.", "By continuously measuring latency/jitter on all WAN links and dynamically shifting Voice traffic to the cleanest link in real-time.", "By converting Voice to text.", "By dropping all data traffic."], a: "By continuously measuring latency/jitter on all WAN links and dynamically shifting Voice traffic to the cleanest link in real-time.", e: "SD-WAN provides 'Application-Aware' routing, solving QoS problems via path selection." },
    { q: "Which metric represents the percentage of packets that fail to reach their destination?", o: ["Latency", "Jitter", "Bandwidth", "Packet Loss"], a: "Packet Loss", e: "Even 1% packet loss can severely degrade real-time video calls." },
    { q: "Why is 'Best Effort' the default QoS behavior for the internet?", o: ["Because it is the most expensive.", "Because the internet has no central authority to enforce priority queues across thousands of different ISPs.", "Because it guarantees zero packet loss.", "Because it is required by law."], a: "Because the internet has no central authority to enforce priority queues across thousands of different ISPs.", e: "Once a packet leaves your enterprise and hits the public internet, all QoS markings are ignored." },

    // --- Enterprise Design Case Studies & Integration (20 Qns) ---
    { q: "Scenario: A multinational corporation merges with another company. Both companies use the internal IP subnet 10.1.1.0/24. How do you allow them to communicate?", o: ["You can't.", "Use NAT (Network Address Translation) at the WAN boundary to translate the overlapping IPs into unique subnets before they cross.", "Turn off one company's network.", "Change the MAC addresses."], a: "Use NAT (Network Address Translation) at the WAN boundary to translate the overlapping IPs into unique subnets before they cross.", e: "NAT is the standard solution for resolving overlapping private IP address spaces during M&A (Mergers & Acquisitions)." },
    { q: "Scenario: A hospital requires that patient monitoring devices (like heart monitors) are absolutely never compromised by malware. What is the best design?", o: ["Install antivirus on the heart monitors.", "Place all medical devices on a heavily restricted, isolated VLAN with no internet access (Micro-segmentation).", "Use a public Wi-Fi network.", "Connect them directly to the core router."], a: "Place all medical devices on a heavily restricted, isolated VLAN with no internet access (Micro-segmentation).", e: "Network isolation is the most bulletproof way to protect insecure IoT/Medical devices." },
    { q: "In a University Campus design, why is 'Guest Wi-Fi' traffic usually tunneled directly to the DMZ/Firewall?", o: ["To make it faster.", "To prevent guest devices from ever touching or scanning the internal student/admin VLANs.", "To encrypt it.", "To save IP addresses."], a: "To prevent guest devices from ever touching or scanning the internal student/admin VLANs.", e: "Tunneling (like CAPWAP) keeps dirty guest traffic completely encapsulated until it reaches the exit." },
    { q: "Scenario: A retail chain with 5,000 small stores needs WAN connectivity. They have no IT staff at the stores. What technology allows central IT to ship a blank router to a store, have a cashier plug it in, and automatically configure it?", o: ["BGP", "Zero Touch Provisioning (ZTP) / SD-WAN", "Static Routing", "Spanning Tree"], a: "Zero Touch Provisioning (ZTP) / SD-WAN", e: "ZTP allows a router to securely phone home to the controller and download its full configuration instantly." },
    { q: "Why do modern Enterprise Designs push 'Security to the Edge' (like SASE - Secure Access Service Edge)?", o: ["Because routers are too heavy.", "Because users are now working from home (remote) and apps are in the Cloud, bypassing traditional central Data Center firewalls.", "Because firewalls are obsolete.", "To save electricity."], a: "Because users are now working from home (remote) and apps are in the Cloud, bypassing traditional central Data Center firewalls.", e: "If a user is at home accessing Salesforce, routing them back through the corporate HQ firewall is incredibly slow and inefficient." },
    { q: "What does a 'VPN Concentrator' do in an enterprise network?", o: ["It cleans the cables.", "It is a dedicated hardware appliance designed specifically to handle the massive CPU encryption load of thousands of remote workers logging in via VPN.", "It provides wireless access.", "It routes BGP."], a: "It is a dedicated hardware appliance designed specifically to handle the massive CPU encryption load of thousands of remote workers logging in via VPN.", e: "Offloading encryption to a dedicated concentrator prevents the main firewall from crashing under load." },
    { q: "Scenario: A financial trading firm needs absolute minimum latency (microseconds) between their servers and the Stock Exchange. What design choice must they make?", o: ["Use a satellite link.", "Use Colocation (Colo) to physically place their servers in the exact same Data Center building as the Stock Exchange's servers.", "Use an internet VPN.", "Use Wi-Fi 6."], a: "Use Colocation (Colo) to physically place their servers in the exact same Data Center building as the Stock Exchange's servers.", e: "In High-Frequency Trading, physical distance equals latency. They pay millions to be geographically feet away from the exchange." },
    { q: "When designing a Data Center, what is the 'Top-of-Rack' (ToR) switch design advantage?", o: ["It uses more cables.", "It drastically reduces the amount of physical cabling required, because all servers in a rack plug into a single switch at the top of that specific rack.", "It increases latency.", "It removes the need for power."], a: "It drastically reduces the amount of physical cabling required, because all servers in a rack plug into a single switch at the top of that specific rack.", e: "ToR replaces 40 long cables running across the room with 1 high-speed fiber uplink per rack." },
    { q: "What is an 'End-of-Row' (EoR) Data Center design?", o: ["Servers have no switches.", "All servers in an entire row of racks run long copper cables to one massive, chassis-based switch at the end of the row.", "Switches are placed on the ceiling.", "Servers use Wi-Fi."], a: "All servers in an entire row of racks run long copper cables to one massive, chassis-based switch at the end of the row.", e: "EoR centralizes switching but requires massive, heavy bundles of cables." },
    { q: "Scenario: A company uses a single ISP. A backhoe cuts the fiber line outside the building. The network goes down. This is a failure in:", o: ["Configuration", "Physical Diversity (Redundancy)", "Logical Routing", "Security"], a: "Physical Diversity (Redundancy)", e: "True redundancy requires two different ISPs whose cables physically enter the building from two different sides." },
    { q: "What is the primary benefit of 'Infrastructure as Code' (IaC) during a Disaster Recovery scenario?", o: ["It buys new hardware.", "If the primary Data Center burns down, IaC scripts can automatically spin up an exact, 100% identical replica of the entire network in the Cloud in minutes.", "It puts out the fire.", "It calls the police."], a: "If the primary Data Center burns down, IaC scripts can automatically spin up an exact, 100% identical replica of the entire network in the Cloud in minutes.", e: "Automated provisioning turns Disaster Recovery from a multi-week nightmare into a coffee-break task." },
    { q: "In a hybrid cloud environment, why must the 'IP Addressing Scheme' be meticulously planned?", o: ["To save money.", "To ensure the on-premises subnets NEVER overlap with the Cloud VPC subnets, which would destroy routing between them.", "Because the cloud uses only IPv6.", "Because IP addresses are random."], a: "To ensure the on-premises subnets NEVER overlap with the Cloud VPC subnets, which would destroy routing between them.", e: "Overlapping IPs break VPNs and routing. The cloud must be treated as an extension of the corporate IP space." },
    { q: "Which Data Center architecture allows for massive horizontal scaling of Web Servers?", o: ["A single huge mainframe.", "Dozens of small, cheap servers sitting behind a Hardware Load Balancer.", "A router on a stick.", "A collapsed core."], a: "Dozens of small, cheap servers sitting behind a Hardware Load Balancer.", e: "Scale-out (horizontal) is cheaper and far more reliable than Scale-up (vertical)." },
    { q: "Scenario: An enterprise wants to adopt IPv6 but has legacy software that only supports IPv4. What is the most common transition mechanism?", o: ["Delete the legacy software.", "Dual-Stack: Running both IPv4 and IPv6 simultaneously on every router and PC until the legacy software is retired.", "NAT64", "IPsec"], a: "Dual-Stack: Running both IPv4 and IPv6 simultaneously on every router and PC until the legacy software is retired.", e: "Dual-Stack allows seamless coexistence without complicated translation mechanisms." },
    { q: "What is the primary function of a 'Web Application Firewall' (WAF)?", o: ["To block ICMP pings.", "To inspect HTTP/HTTPS traffic at Layer 7 and block specific web attacks like SQL Injection and Cross-Site Scripting (XSS).", "To route BGP.", "To provide Wi-Fi."], a: "To inspect HTTP/HTTPS traffic at Layer 7 and block specific web attacks like SQL Injection and Cross-Site Scripting (XSS).", e: "Normal firewalls don't understand web code. A WAF specifically protects web servers from code-based attacks." },
    { q: "Why is 'Spanning Tree Protocol' (STP) universally hated in modern Data Center designs?", o: ["It is too fast.", "It intentionally blocks redundant links to prevent loops, meaning 50% of your highly expensive 40Gbps cables are sitting idle and unused.", "It deletes data.", "It uses IPv4."], a: "It intentionally blocks redundant links to prevent loops, meaning 50% of your highly expensive 40Gbps cables are sitting idle and unused.", e: "Modern designs like Spine-Leaf use Layer 3 routing to utilize all links simultaneously, abandoning STP." },
    { q: "What does a 'First Hop Redundancy Protocol' (FHRP) like HSRP or VRRP do?", o: ["It provides a backup internet connection.", "It allows two physical routers to share a single 'Virtual IP Address' to act as a highly available Default Gateway for PCs.", "It assigns IP addresses.", "It encrypts traffic."], a: "It allows two physical routers to share a single 'Virtual IP Address' to act as a highly available Default Gateway for PCs.", e: "If Router A dies, Router B instantly takes over the Virtual IP, and the PCs never lose their gateway." },
    { q: "Scenario: A company's internal DNS server goes down. What is the immediate effect on the users?", o: ["Nothing.", "Users cannot access the internet or internal servers by name (e.g., www.google.com), making the network appear 'down' even though routing is fine.", "The routers explode.", "Bandwidth increases."], a: "Users cannot access the internet or internal servers by name (e.g., www.google.com), making the network appear 'down' even though routing is fine.", e: "DNS failure is the #1 cause of perceived network outages." },
    { q: "Which design concept ensures that an attacker who breaches the Guest Wi-Fi cannot pivot and attack the internal Domain Controller?", o: ["Network Segmentation (VLANs, VRFs, Firewalls).", "Changing the password.", "Increasing bandwidth.", "Using BGP."], a: "Network Segmentation (VLANs, VRFs, Firewalls).", e: "Segmentation provides rigid walls between different security zones." },
    { q: "In advanced network design, what is 'CAPEX' vs 'OPEX'?", o: ["Routing protocols.", "CAPEX is huge upfront hardware costs (buying servers); OPEX is ongoing monthly costs (leasing cloud/WAN links).", "Types of fiber optic cables.", "Security encryption standards."], a: "CAPEX is huge upfront hardware costs (buying servers); OPEX is ongoing monthly costs (leasing cloud/WAN links).", e: "Modern networking (Cloud/SD-WAN) heavily shifts IT budgets from CapEx to OpEx." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            const doc = {
                subjectId, moduleName, type: "MULTIPLE_CHOICE",
                category: categories[Math.floor(Math.random() * categories.length)],
                difficultyLevel: ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)],
                createdAt: new Date(),
                questionText: q.q,
                options: q.o.sort(() => Math.random() - 0.5),
                correctAnswer: q.a,
                explanation: q.e
            };
            const exists = await collection.findOne({ subjectId: doc.subjectId, questionText: doc.questionText });
            if (!exists) {
                await collection.insertOne(doc);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 4 (Batch 2 of Phase 4)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
