const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 5: Implementation and Operations";

const questions = [
    // --- Advanced Operations & Maintenance (20 Qns) ---
    { q: "What is the primary goal of a 'Change Management' process in network operations?", o: ["To physically change the cables.", "To ensure all proposed network changes are reviewed, tested, and approved before implementation, minimizing the risk of causing accidental outages.", "To change user passwords.", "To change the IP addresses randomly."], a: "To ensure all proposed network changes are reviewed, tested, and approved before implementation, minimizing the risk of causing accidental outages.", e: "Uncontrolled 'cowboy' changes are the #1 cause of network downtime." },
    { q: "What must a network engineer submit to the Change Advisory Board (CAB) before making a major routing change?", o: ["A request for a new laptop.", "A detailed Change Request (CR) including the exact commands to be typed, the expected impact, and a tested Rollback plan.", "A new IP address.", "A ping request."], a: "A detailed Change Request (CR) including the exact commands to be typed, the expected impact, and a tested Rollback plan.", e: "The CAB reviews the CR to ensure the change won't negatively impact other business units." },
    { q: "What is an 'RCA' (Root Cause Analysis)?", o: ["A virus scanner.", "A formal, deep-dive investigation conducted after a major network outage to find the exact underlying flaw so it never happens again.", "A tool to install software.", "A routing protocol."], a: "A formal, deep-dive investigation conducted after a major network outage to find the exact underlying flaw so it never happens again.", e: "RCA moves beyond 'fixing the symptom' to 'curing the disease'." },
    { q: "Why is 'Baselining' a critical practice in network monitoring?", o: ["To make the network louder.", "To record what 'normal' network traffic and CPU usage looks like during a regular week, so anomalies (like a sudden spike) are immediately obvious.", "To paint the server racks.", "To set the clock."], a: "To record what 'normal' network traffic and CPU usage looks like during a regular week, so anomalies (like a sudden spike) are immediately obvious.", e: "You cannot identify 'abnormal' if you don't know what 'normal' looks like." },
    { q: "Which IT framework provides globally recognized best practices for IT Service Management, including Incident and Change Management?", o: ["OSPF", "ITIL (Information Technology Infrastructure Library)", "IEEE 802.11", "BGP"], a: "ITIL (Information Technology Infrastructure Library)", e: "ITIL is the industry standard for running an IT department efficiently." },
    { q: "In ITIL terminology, what is the difference between an 'Incident' and a 'Problem'?", o: ["There is no difference.", "An Incident is a single unplanned interruption to a service; a Problem is the unknown underlying root cause of one or more Incidents.", "An incident is hardware; a problem is software.", "An incident is cheap; a problem is expensive."], a: "An Incident is a single unplanned interruption to a service; a Problem is the unknown underlying root cause of one or more Incidents.", e: "Fixing an incident restores service (e.g., rebooting). Fixing a problem stops the incident from returning." },
    { q: "What does a 'Help Desk' or 'Service Desk' ticketing system do?", o: ["It sells airplane tickets.", "It acts as a central database to track all user issues, assign technicians, and measure how fast problems are resolved (SLAs).", "It encrypts user data.", "It automatically reboots routers."], a: "It acts as a central database to track all user issues, assign technicians, and measure how fast problems are resolved (SLAs).", e: "Ticketing systems organize the chaos of IT support." },
    { q: "What is 'Capacity Planning' in network operations?", o: ["Guessing how many cables to buy.", "Analyzing historical bandwidth growth trends to accurately predict exactly when the company will need to buy larger WAN links or bigger switches.", "Planning the office layout.", "Planning user passwords."], a: "Analyzing historical bandwidth growth trends to accurately predict exactly when the company will need to buy larger WAN links or bigger switches.", e: "Capacity planning prevents the network from suddenly hitting 100% utilization and crashing." },
    { q: "Why do administrators schedule 'Maintenance Windows' for 2:00 AM on a Sunday?", o: ["Because they don't want to sleep.", "To perform disruptive tasks (like router firmware upgrades) when user traffic and business impact are at the absolute minimum.", "To save electricity.", "Because the internet is faster at night."], a: "To perform disruptive tasks (like router firmware upgrades) when user traffic and business impact are at the absolute minimum.", e: "Maintenance windows protect the business's revenue-generating hours." },
    { q: "What is a 'Patch Management' policy?", o: ["A policy for sewing clothes.", "A strict schedule and procedure for testing and deploying security updates to router firmware and server operating systems.", "A policy for changing IP addresses.", "A policy for physical security."], a: "A strict schedule and procedure for testing and deploying security updates to router firmware and server operating systems.", e: "Unpatched routers are sitting ducks for hackers. Patch management ensures updates are applied safely." },
    { q: "What does the 'MTBF' (Mean Time Between Failures) metric indicate about a network switch?", o: ["How fast it routes packets.", "The statistical average time the manufacturer expects the switch to operate perfectly before it suffers a hardware failure.", "How much it costs.", "How heavy it is."], a: "The statistical average time the manufacturer expects the switch to operate perfectly before it suffers a hardware failure.", e: "MTBF helps engineers plan when they should proactively replace aging hardware." },
    { q: "What does 'MTTR' (Mean Time to Repair) measure?", o: ["The speed of the internet.", "The average time it takes the IT department to detect an outage, diagnose it, and completely restore the service.", "The time it takes to boot a PC.", "The time it takes to buy a router."], a: "The average time it takes the IT department to detect an outage, diagnose it, and completely restore the service.", e: "A low MTTR indicates a highly skilled IT team with good documentation." },
    { q: "Why is 'Asset Management' critical for network operations?", o: ["To count the chairs in the office.", "You cannot secure, patch, or upgrade devices if you don't have an accurate database of exactly what hardware you own and where it is physically located.", "To sell old routers on eBay.", "To increase bandwidth."], a: "You cannot secure, patch, or upgrade devices if you don't have an accurate database of exactly what hardware you own and where it is physically located.", e: "Unknown 'shadow IT' devices are massive security vulnerabilities." },
    { q: "What is 'End of Life' (EoL) for a Cisco router?", o: ["The router instantly explodes.", "The manufacturer officially stops selling the router, stops providing software updates, and stops offering technical support for it.", "The router's warranty doubles.", "The router becomes wireless."], a: "The manufacturer officially stops selling the router, stops providing software updates, and stops offering technical support for it.", e: "Running EoL hardware is extremely risky because security flaws will never be patched." },
    { q: "Which disaster recovery strategy involves a 'Warm Site'?", o: ["A data center that is currently on fire.", "A backup facility with hardware installed, but the data must be restored from backups before it can operate, taking hours or days.", "A fully operational, instantly ready data center.", "An empty building with no hardware."], a: "A backup facility with hardware installed, but the data must be restored from backups before it can operate, taking hours or days.", e: "A Warm site is cheaper than a Hot site (instant), but faster than a Cold site (empty room)." },
    { q: "What is 'RTO' (Recovery Time Objective)?", o: ["The time it takes to read a book.", "The maximum acceptable amount of time the business can survive the network being down before catastrophic damage occurs.", "The speed of the router.", "The time it takes to boot up."], a: "The maximum acceptable amount of time the business can survive the network being down before catastrophic damage occurs.", e: "If the RTO is 1 hour, IT must design a network that can be fixed or failed-over in under 60 minutes." },
    { q: "What is 'RPO' (Recovery Point Objective)?", o: ["The physical location of the data center.", "The maximum acceptable amount of data loss (measured in time) a business can tolerate (e.g., losing the last 15 minutes of transactions).", "The number of routers.", "The IP address of the backup server."], a: "The maximum acceptable amount of data loss (measured in time) a business can tolerate (e.g., losing the last 15 minutes of transactions).", e: "If the RPO is zero, you must use synchronous real-time mirroring. If it's 24 hours, daily tape backups are fine." },
    { q: "Why do administrators 'Archive' Syslog data for 1 to 7 years?", o: ["Because they like reading logs.", "To comply with strict legal regulations (like HIPAA or PCI-DSS) that require historical proof of security auditing and access controls.", "To slow down the hard drives.", "To prevent viruses."], a: "To comply with strict legal regulations (like HIPAA or PCI-DSS) that require historical proof of security auditing and access controls.", e: "Compliance laws dictate how long audit data must be retained." },
    { q: "What is 'Configuration Drift'?", o: ["When a router physically moves across the desk.", "When the actual running configuration of a router slowly changes over time due to quick undocumented 'hot-fixes', making it different from the official baseline document.", "When the internet gets faster.", "When IP addresses change automatically."], a: "When the actual running configuration of a router slowly changes over time due to quick undocumented 'hot-fixes', making it different from the official baseline document.", e: "Configuration drift causes bizarre troubleshooting issues because the map no longer matches the territory." },
    { q: "Which tool physically destroys old hard drives to ensure data cannot be recovered before the server is thrown away?", o: ["A software formatting tool.", "A Degausser or a physical shredder.", "A microwave.", "A magnet."], a: "A Degausser or a physical shredder.", e: "Physical destruction is the only 100% guaranteed way to prevent data recovery." },

    // --- Complex Multi-Technology Operations (20 Qns) ---
    { q: "Scenario: A user cannot access a specific internal web server via its name, but CAN access it via its IP address. What is the next logical troubleshooting step?", o: ["Replace the switch.", "Check the user's DNS settings and verify the DNS server has the correct 'A Record' for that web server.", "Reboot the router.", "Turn off the firewall."], a: "Check the user's DNS settings and verify the DNS server has the correct 'A Record' for that web server.", e: "Name resolution failure while IP connectivity works is a textbook DNS issue." },
    { q: "Scenario: You implement a new ACL on the WAN router to block Telnet (Port 23), but suddenly users complain they cannot browse the internet (HTTP Port 80). What happened?", o: ["Telnet and HTTP are the same.", "You forgot to add 'permit ip any any' at the end of the ACL, so the 'Implicit Deny' blocked all other traffic.", "The internet is down.", "The router crashed."], a: "You forgot to add 'permit ip any any' at the end of the ACL, so the 'Implicit Deny' blocked all other traffic.", e: "Always remember the invisible deny statement at the bottom of every ACL." },
    { q: "Scenario: A fiber optic link between two buildings keeps 'flapping' (going up and down rapidly). What is the most likely Layer 1 cause?", o: ["A bad IP address.", "A dirty optical connector, a failing SFP transceiver, or the fiber cable is bent too sharply (micro-bending).", "A routing loop.", "BGP misconfiguration."], a: "A dirty optical connector, a failing SFP transceiver, or the fiber cable is bent too sharply (micro-bending).", e: "Intermittent Layer 1 issues are almost always physical damage or dirt on the laser." },
    { q: "When troubleshooting an OSPF routing issue, why would you check the 'Subnet Mask' on both routers?", o: ["Because OSPF uses MAC addresses.", "If the subnet masks don't match, the routers consider themselves on different networks and will NEVER form an OSPF neighbor relationship.", "Because OSPF requires IPv6.", "To speed up the internet."], a: "If the subnet masks don't match, the routers consider themselves on different networks and will NEVER form an OSPF neighbor relationship.", e: "OSPF is incredibly strict about subnet mask matching on broadcast segments." },
    { q: "Scenario: An engineer types 'write erase' and reboots the core router. What is the result?", o: ["The router runs faster.", "The NVRAM is completely wiped. The router will boot up with a totally blank factory default configuration, bringing down the network.", "The router updates its firmware.", "The router encrypts the data."], a: "The NVRAM is completely wiped. The router will boot up with a totally blank factory default configuration, bringing down the network.", e: "Write erase destroys the startup-config." },
    { q: "What does the 'ip helper-address' command do on a Cisco router?", o: ["It blocks hackers.", "It allows a router to take local DHCP broadcast requests and forward them as unicast packets to a centralized DHCP server on a different subnet.", "It provides technical support.", "It assigns an IP address to the router."], a: "It allows a router to take local DHCP broadcast requests and forward them as unicast packets to a centralized DHCP server on a different subnet.", e: "Routers block broadcasts. The helper-address tells the router exactly where to forward DHCP requests." },
    { q: "Scenario: PCs on VLAN 10 cannot talk to PCs on VLAN 20. They are connected to the same Layer 2 switch. The switch is connected to a router. What is likely missing?", o: ["A wireless access point.", "The link between the switch and the router is not configured as an 802.1q Trunk, so VLAN tags are being stripped or ignored.", "A firewall.", "A BGP route."], a: "The link between the switch and the router is not configured as an 802.1q Trunk, so VLAN tags are being stripped or ignored.", e: "Router-on-a-stick requires the switchport to be a Trunk to pass multiple VLANs." },
    { q: "Why is 'PortFast' configured on access switch ports connected to PCs?", o: ["To make the PC run faster.", "To bypass the 30-second Spanning Tree listening/learning delay, bringing the port up instantly because a PC cannot cause a routing loop.", "To block all traffic.", "To assign IP addresses."], a: "To bypass the 30-second Spanning Tree listening/learning delay, bringing the port up instantly because a PC cannot cause a routing loop.", e: "Waiting 30 seconds for a port to turn on causes DHCP timeouts on modern PCs." },
    { q: "What does 'BPDU Guard' do if enabled on a PortFast interface?", o: ["It encrypts the BPDU.", "If a user illegally plugs a switch into the wall jack, the port instantly shuts down to prevent a spanning-tree loop.", "It blocks viruses.", "It increases bandwidth."], a: "If a user illegally plugs a switch into the wall jack, the port instantly shuts down to prevent a spanning-tree loop.", e: "BPDU Guard protects the edge of the network from rogue switches." },
    { q: "Scenario: You are monitoring NetFlow and notice a massive, sustained spike in traffic originating from a single internal PC to an unknown IP address in Russia at 3:00 AM. What is this?", o: ["A Windows update.", "A massive security breach; the PC is likely compromised and exfiltrating corporate data to a hacker.", "A routing loop.", "A broadcast storm."], a: "A massive security breach; the PC is likely compromised and exfiltrating corporate data to a hacker.", e: "Anomalous high-volume outbound traffic is the classic signature of data exfiltration." },
    { q: "In operations, what is a 'Runbook'?", o: ["A book about jogging.", "A highly detailed, step-by-step manual that tells junior technicians exactly what commands to type to fix common, known network problems without needing to call senior engineers.", "A novel.", "A type of firewall."], a: "A highly detailed, step-by-step manual that tells junior technicians exactly what commands to type to fix common, known network problems without needing to call senior engineers.", e: "Runbooks standardize and accelerate incident response." },
    { q: "What does a 'Tap' (Test Access Point) do that is superior to SPAN (Port Mirroring)?", o: ["It turns on the water.", "A physical Tap splits the light in a fiber cable, providing a 100% exact copy of the traffic to an analyzer without putting any CPU load on the router.", "It speeds up the internet.", "It encrypts the data."], a: "A physical Tap splits the light in a fiber cable, providing a 100% exact copy of the traffic to an analyzer without putting any CPU load on the router.", e: "SPAN can drop packets if the switch CPU is busy. A physical tap never drops packets." },
    { q: "Scenario: A user complains the network is slow. You ping the server and get 0% packet loss but a latency of 400ms. What is the issue?", o: ["The cable is unplugged.", "The network is heavily congested, causing packets to sit in router queues for a long time before being forwarded.", "The server is turned off.", "DNS is broken."], a: "The network is heavily congested, causing packets to sit in router queues for a long time before being forwarded.", e: "High latency with no packet loss means the pipes are full, but QoS or TCP windowing is keeping packets alive." },
    { q: "Which command shows exactly how much memory (RAM) and CPU a Cisco router is currently using?", o: ["show interfaces", "show processes cpu / show memory", "show ip route", "ping"], a: "show processes cpu / show memory", e: "This command is critical when diagnosing a router that is sluggish or dropping packets." },
    { q: "If an interface shows 'up, line protocol is down', what does this indicate?", o: ["The router is turned off.", "The physical cable is plugged in (Layer 1 is UP), but there is a severe Layer 2 mismatch (like wrong encapsulation or clock rate).", "The internet is fast.", "The IP address is correct."], a: "The physical cable is plugged in (Layer 1 is UP), but there is a severe Layer 2 mismatch (like wrong encapsulation or clock rate).", e: "This specific status output narrows the problem exactly to Layer 2 data-link framing." },
    { q: "What is 'VTY' (Virtual Teletype) on a router?", o: ["A physical port.", "The logical interfaces used strictly for remote management connections like SSH or Telnet.", "A routing protocol.", "A type of memory."], a: "The logical interfaces used strictly for remote management connections like SSH or Telnet.", e: "Securing the VTY lines with strong passwords and ACLs is the foundation of device hardening." },
    { q: "Scenario: You want to block all PCs in VLAN 10 from talking to VLAN 20. Should you place the Standard ACL close to the Source (VLAN 10) or the Destination (VLAN 20)?", o: ["Close to the Source.", "Close to the Destination.", "It doesn't matter.", "On the internet router."], a: "Close to the Destination.", e: "Standard ACLs (which only check Source IP) MUST be placed near the destination, otherwise they block the source from reaching EVERYTHING." },
    { q: "Where should an 'Extended ACL' (which checks both Source and Destination IPs) be placed?", o: ["Close to the Destination.", "As close to the Source as possible.", "On the user's PC.", "In the cloud."], a: "As close to the Source as possible.", e: "Extended ACLs should block unwanted traffic immediately before it wastes bandwidth traversing the whole network." },
    { q: "What does the Cisco command 'copy tftp running-config' do?", o: ["It formats the router.", "It downloads a configuration file from a remote TFTP server and instantly applies it to the active memory of the router.", "It uploads the config to the server.", "It turns on the firewall."], a: "It downloads a configuration file from a remote TFTP server and instantly applies it to the active memory of the router.", e: "This is a fast way to restore a router from a backup." },
    { q: "Why is 'Continuous Learning' essential for Network Operations professionals?", o: ["To get free food.", "Because network technology evolves insanely fast (SDN, Cloud, AI); skills that were elite 5 years ago are obsolete today.", "To play video games.", "To learn how to type faster."], a: "Because network technology evolves insanely fast (SDN, Cloud, AI); skills that were elite 5 years ago are obsolete today.", e: "The transition from CLI typing to Python coding has forced the entire industry to adapt." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            const doc = {
                subjectId, moduleName, type: "MULTIPLE_CHOICE",
                category: categories[Math.floor(Math.random() * categories.length)],
                difficultyLevel: ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)],
                createdAt: new Date(),
                questionText: q.q,
                options: q.o.sort(() => Math.random() - 0.5),
                correctAnswer: q.a,
                explanation: q.e
            };
            const exists = await collection.findOne({ subjectId: doc.subjectId, questionText: doc.questionText });
            if (!exists) {
                await collection.insertOne(doc);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 5 (Batch 2 of Phase 5)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
