const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 1: Network Design Fundamentals";

const questions = [
    // --- Detailed Topology and Hierarchy Scenarios (20 Qns) ---
    { q: "A company decides to connect every single router to every other router physically. This is an example of:", o: ["A Hub-and-Spoke topology", "A Full Mesh topology", "A Hierarchical topology", "A Ring topology"], a: "A Full Mesh topology", e: "Full Mesh means every node is directly connected to every other node, providing maximum redundancy but highest cost." },
    { q: "What is the formula to calculate the number of physical links required for a Full Mesh network with 'n' nodes?", o: ["n * (n - 1)", "n * (n - 1) / 2", "n^2", "2n"], a: "n * (n - 1) / 2", e: "The formula n*(n-1)/2 calculates the exact number of cables needed, showing how unscalable Full Mesh is." },
    { q: "Why is a Hub-and-Spoke topology highly vulnerable to outages?", o: ["Because it has no core router.", "Because if the central 'Hub' fails, all communication between the 'Spokes' stops immediately.", "Because the spokes are directly connected to each other.", "Because it only uses wireless connections."], a: "Because if the central 'Hub' fails, all communication between the 'Spokes' stops immediately.", e: "Hub-and-spoke relies entirely on the central node. It is a massive Single Point of Failure (SPOF)." },
    { q: "In a 3-tier hierarchy, what happens if an Access switch fails?", o: ["The entire network goes down.", "Only the users directly connected to that specific switch lose connectivity.", "The Core switches reboot.", "The Distribution switches block all traffic."], a: "Only the users directly connected to that specific switch lose connectivity.", e: "Hierarchical design isolates faults to the lowest possible level." },
    { q: "Which protocol is absolutely critical to configure at the Access Layer to prevent bridging loops?", o: ["BGP", "Spanning Tree Protocol (STP)", "OSPF", "EIGRP"], a: "Spanning Tree Protocol (STP)", e: "STP prevents loops at the Layer 2 Access switches." },
    { q: "If a company has 10,000 employees in one skyscraper, the network designer should definitely use:", o: ["A Collapsed Core design", "A flat Layer 2 network", "A full 3-tier Hierarchical design (Core, Distribution, Access)", "A Hub-and-Spoke design"], a: "A full 3-tier Hierarchical design (Core, Distribution, Access)", e: "Massive scale demands the full 3-tier model to maintain speed and manageability." },
    { q: "A 'Flat Network' (Layer 2 only) is terrible for large organizations because:", o: ["It creates massive, uncontrollable broadcast domains that degrade performance.", "It is too expensive to build.", "It forces you to use IPv6.", "It requires hundreds of routers."], a: "It creates massive, uncontrollable broadcast domains that degrade performance.", e: "Without Layer 3 routers (Distribution layer) to break up broadcasts, the network gets overwhelmed with noise." },
    { q: "Which term describes 'combining multiple physical links into one logical link to increase bandwidth and redundancy'?", o: ["Subnetting", "EtherChannel (Link Aggregation)", "VLAN Tagging", "Route Summarization"], a: "EtherChannel (Link Aggregation)", e: "EtherChannel binds multiple cables together, heavily used between Access and Distribution layers." },
    { q: "What is a 'Top-of-Rack' (ToR) switch design commonly associated with?", o: ["Campus networks", "Data Center Access layer", "WAN Core layer", "Home networks"], a: "Data Center Access layer", e: "In Data Centers, the Access layer is often placed at the top of the server rack (ToR)." },
    { q: "Which tier in the hierarchical model is sometimes called the 'Aggregation Layer'?", o: ["Access Layer", "Core Layer", "Distribution Layer", "Server Layer"], a: "Distribution Layer", e: "The Distribution layer aggregates all the access switches." },
    { q: "If the business requirement is to strictly prevent the Finance Department from talking to the Guest Wi-Fi, where is this policy enforced?", o: ["Access Layer (Port Security)", "Distribution Layer (ACLs)", "Core Layer", "Physical Layer"], a: "Distribution Layer (ACLs)", e: "Policy enforcement and inter-VLAN routing restrictions happen at the Distribution layer." },
    { q: "A network architect places two identical Core switches side by side, connected via a 40Gbps link. This is an implementation of:", o: ["Scalability", "Hardware Redundancy", "Software Redundancy", "Cost Efficiency"], a: "Hardware Redundancy", e: "Placing duplicate physical hardware ensures if one dies, the other takes over immediately." },
    { q: "Which design methodology phase involves 'simulating traffic loads' to see if the proposed design will crash?", o: ["Requirements Analysis", "Physical Design", "Testing and Validation", "Maintenance"], a: "Testing and Validation", e: "Stress testing happens before the network goes live." },
    { q: "Why might a designer choose a 'Collapsed Core' over a 'Full 3-Tier' model?", o: ["Because they have unlimited budget.", "Because the organization is small enough that a dedicated Core layer is a waste of money.", "Because they want maximum latency.", "Because they don't want to use switches."], a: "Because the organization is small enough that a dedicated Core layer is a waste of money.", e: "Collapsed Core saves money for small-to-medium businesses by merging Core and Distribution." },
    { q: "In a modular design, what is an 'Enterprise Edge' module?", o: ["The module where users plug in their laptops.", "The module connecting the internal network to the Internet, WAN, and Remote workers.", "The module hosting internal databases.", "The module powering the air conditioning."], a: "The module connecting the internal network to the Internet, WAN, and Remote workers.", e: "The Edge is the boundary between the internal enterprise and the outside world." },

    // --- Technical Constraints & Trade-offs (20 Qns) ---
    { q: "If a company has a massive budget but requires absolutely zero downtime, which design objective takes precedence over Cost Efficiency?", o: ["Manageability", "Extreme Availability", "Simplicity", "Documentation"], a: "Extreme Availability", e: "Extreme Availability requires duplicating everything, which ruins cost efficiency." },
    { q: "Which of the following is considered a 'Technical Constraint' during Requirements Analysis?", o: ["The company only has $5,000 to spend.", "The existing wiring in the building is old CAT3 cable which cannot support Gigabit speeds.", "The CEO wants the network done by Friday.", "The IT staff needs training."], a: "The existing wiring in the building is old CAT3 cable which cannot support Gigabit speeds.", e: "Physical/hardware limits like old cabling are technical constraints." },
    { q: "A business requirement states 'Employees must be able to work from coffee shops.' What technical solution must be designed?", o: ["A new Access layer switch.", "A secure VPN solution in the Enterprise Edge.", "A Collapsed Core.", "Thicker ethernet cables."], a: "A secure VPN solution in the Enterprise Edge.", e: "Remote access dictates the need for VPNs and strong perimeter security." },
    { q: "When designing for 'Scalability', what is a major consideration for the IP Addressing scheme?", o: ["Using the smallest possible subnet to save IP addresses.", "Using hierarchical, contiguous IP blocks that can be easily summarized and expanded.", "Using public IP addresses for every computer.", "Randomly assigning IP addresses manually."], a: "Using hierarchical, contiguous IP blocks that can be easily summarized and expanded.", e: "Proper IP planning allows route summarization and future growth." },
    { q: "Which objective is met by standardizing all switches to be the exact same Cisco Catalyst model?", o: ["Availability", "Manageability and Maintainability", "Security", "Flexibility"], a: "Manageability and Maintainability", e: "Having uniform hardware means admins only need to learn one OS, making management and spare-part swapping vastly easier." },
    { q: "A network designer uses OSPF instead of static routing for a 500-router network. This primarily improves:", o: ["Scalability and Manageability", "Cost Efficiency", "Physical Security", "Latency"], a: "Scalability and Manageability", e: "Dynamic routing protocols (OSPF) automatically adjust to changes, making huge networks manageable." },
    { q: "What trade-off is typically made when deploying Deep Packet Inspection (DPI) on a firewall?", o: ["Security increases, but Performance (throughput) decreases.", "Cost decreases, but Security decreases.", "Manageability increases, but Availability decreases.", "Latency decreases, but Jitter increases."], a: "Security increases, but Performance (throughput) decreases.", e: "DPI takes massive CPU power, inherently slowing down the flow of traffic." },
    { q: "In the PPDIOO lifecycle methodology (Prepare, Plan, Design, Implement, Operate, Optimize), where does 'Requirements Analysis' fit?", o: ["Implement", "Operate", "Prepare and Plan", "Optimize"], a: "Prepare and Plan", e: "Gathering requirements happens at the very beginning of the lifecycle." },
    { q: "Which document specifically outlines the step-by-step procedures to revert to the old network if the new network deployment fails?", o: ["IP Addressing Scheme", "Rollback Plan", "Logical Diagram", "Security Policy"], a: "Rollback Plan", e: "A Rollback Plan is critical during Implementation in case things go wrong." },
    { q: "If the Core layer goes down, what happens to traffic trying to travel between two different Distribution blocks?", o: ["It is automatically routed through the Access layer.", "It fails entirely because the Core is the only path between Distribution blocks.", "It is stored in memory until the Core comes back.", "It travels over the internet."], a: "It fails entirely because the Core is the only path between Distribution blocks.", e: "The Core is the central transit; without it, major modules are isolated." },
    { q: "Which feature allows a network to survive a power outage in a specific building?", o: ["Uninterruptible Power Supplies (UPS) and backup generators.", "OSPF routing.", "VLAN segmentation.", "Spanning Tree Protocol."], a: "Uninterruptible Power Supplies (UPS) and backup generators.", e: "Physical power requires physical backup solutions." },
    { q: "What is 'Overbooking' or 'Oversubscription' in network design?", o: ["Buying too many routers.", "Designing a network where the total bandwidth of access ports exceeds the uplink bandwidth to the core.", "Putting too many IP addresses in a subnet.", "Paying the ISP too much money."], a: "Designing a network where the total bandwidth of access ports exceeds the uplink bandwidth to the core.", e: "It assumes not all users will download at maximum speed at the exact same time." },
    { q: "If an access switch has 24 ports of 1Gbps each, but its uplink to the Distribution layer is only 10Gbps, what is the oversubscription ratio?", o: ["2.4:1", "1:1", "24:1", "10:1"], a: "2.4:1", e: "24Gbps potential demand vs 10Gbps actual supply gives a 2.4 to 1 ratio." },
    { q: "Why is a 1:1 oversubscription ratio usually avoided at the Access Layer?", o: ["Because it makes the network too slow.", "Because it is completely impossible to achieve.", "Because it is extremely expensive and largely unnecessary since users rarely use 100% of their bandwidth simultaneously.", "Because it causes broadcast storms."], a: "Because it is extremely expensive and largely unnecessary since users rarely use 100% of their bandwidth simultaneously.", e: "Providing 1:1 bandwidth to end-users wastes massive amounts of money." },
    { q: "What is the primary purpose of a 'Demilitarized Zone' (DMZ) in network design?", o: ["To place internal databases where anyone can access them.", "To securely host public-facing servers (like Web or Email) away from the highly secure internal network.", "To route traffic faster.", "To store backup generators."], a: "To securely host public-facing servers (like Web or Email) away from the highly secure internal network.", e: "A DMZ acts as a buffer zone for servers that must touch the internet." },

    // --- Final Advanced Mix (25 Qns) ---
    { q: "When upgrading an enterprise network, what is a 'Brownfield' deployment?", o: ["Building a brand new network from scratch in an empty building.", "Integrating new equipment into a currently operating, legacy network.", "Painting the server racks brown.", "Deploying a network in a rural area."], a: "Integrating new equipment into a currently operating, legacy network.", e: "Brownfield means working around existing infrastructure, which is much harder than Greenfield (scratch)." },
    { q: "What is a 'Greenfield' deployment?", o: ["Working with legacy IBM mainframes.", "Designing and building a completely new network from the ground up without legacy constraints.", "Using environmentally friendly solar panels for routers.", "Upgrading old CAT5 cables to CAT6."], a: "Designing and building a completely new network from the ground up without legacy constraints.", e: "Greenfield provides a clean slate for the network designer." },
    { q: "Which design document is updated during the 'Optimize' phase of the network lifecycle?", o: ["Physical Diagram only.", "All documentation (Logical, Physical, Operational) to reflect performance tweaks.", "Only the purchase orders.", "None, documentation is never updated."], a: "All documentation (Logical, Physical, Operational) to reflect performance tweaks.", e: "Documentation must always reflect the live, running network." },
    { q: "In a massive Data Center, a 'Spine-and-Leaf' architecture is replacing the traditional 3-tier model. Why?", o: ["It is cheaper.", "It provides highly predictable, low-latency 'East-West' traffic flow between servers.", "It uses less electricity.", "It doesn't require routers."], a: "It provides highly predictable, low-latency 'East-West' traffic flow between servers.", e: "Spine-Leaf ensures every server is exactly the same number of hops away from any other server." },
    { q: "What does 'East-West traffic' refer to in network design?", o: ["Traffic leaving the network to the internet.", "Traffic flowing directly between servers within the data center.", "Traffic coming from mobile phones.", "Traffic moving from the Access layer to the Core layer."], a: "Traffic flowing directly between servers within the data center.", e: "East-West is internal server-to-server traffic, which dominates modern data centers." },
    { q: "What does 'North-South traffic' refer to?", o: ["Internal server backups.", "Traffic moving horizontally between switches.", "Traffic flowing into and out of the data center from the external internet.", "Traffic on a local VLAN."], a: "Traffic flowing into and out of the data center from the external internet.", e: "North-South implies traffic crossing the perimeter firewall." },
    { q: "Which objective is achieved by strictly using open-standard protocols (like OSPF) instead of proprietary ones (like EIGRP)?", o: ["Security", "Flexibility and Vendor Interoperability", "Performance", "Cost Efficiency"], a: "Flexibility and Vendor Interoperability", e: "Open standards allow you to mix Cisco, Juniper, and HP equipment freely." },
    { q: "What is the primary risk of building a network entirely on proprietary protocols (Vendor Lock-in)?", o: ["The network becomes unhackable.", "You are forced to buy expensive upgrades from that specific vendor forever.", "The network runs too fast.", "Routing tables become empty."], a: "You are forced to buy expensive upgrades from that specific vendor forever.", e: "Vendor lock-in destroys Flexibility and Cost Efficiency." },
    { q: "A designer places critical servers in a secure room that requires biometric scanning to enter. This satisfies:", o: ["Logical Security", "Physical Security", "Performance", "Manageability"], a: "Physical Security", e: "Biometrics and locked doors are physical security measures." },
    { q: "Which of the following is a key deliverable of the 'Design' phase?", o: ["Installed physical switches", "A comprehensive Bill of Materials (BoM)", "Live NetFlow data", "User passwords"], a: "A comprehensive Bill of Materials (BoM)", e: "The BoM is the exact list of every piece of hardware and software that must be purchased." },
    { q: "Why is 'QoS (Quality of Service)' considered during the Logical Design phase rather than waiting until the network is built?", o: ["Because QoS requires physical cables to be cut.", "Because QoS policies dictate how subnets and routing must prioritize traffic, which affects the core logical architecture.", "Because QoS is a hardware device.", "Because QoS only works on Mondays."], a: "Because QoS policies dictate how subnets and routing must prioritize traffic, which affects the core logical architecture.", e: "QoS must be baked into the design, not slapped on as an afterthought." },
    { q: "If a company mandates 'Five Nines' (99.999%) availability, how much downtime is acceptable per year?", o: ["About 5 minutes.", "About 5 hours.", "About 5 days.", "Zero."], a: "About 5 minutes.", e: "99.999% allows exactly 5.26 minutes of downtime per entire year." },
    { q: "Which technique is strictly used to achieve 'Five Nines' availability?", o: ["Removing the Core layer.", "Extensive redundancy, failover clustering, and HA (High Availability) protocols.", "Using Trial-and-Error troubleshooting.", "Manually restarting routers daily."], a: "Extensive redundancy, failover clustering, and HA (High Availability) protocols.", e: "Only extreme redundancy can guarantee near-zero downtime." },
    { q: "What happens during a 'Maintenance Window'?", o: ["The network is completely destroyed.", "Scheduled upgrades or disruptive changes are applied during off-peak hours to minimize impact on the business.", "Users are forced to change their passwords.", "The ISP increases bandwidth."], a: "Scheduled upgrades or disruptive changes are applied during off-peak hours to minimize impact on the business.", e: "Maintenance windows protect the business from unexpected midday outages." },
    { q: "Which metric defines 'the time it takes for a packet to travel from source to destination and back'?", o: ["Bandwidth", "Round Trip Time (RTT) Latency", "Jitter", "Throughput"], a: "Round Trip Time (RTT) Latency", e: "RTT is a critical performance metric, especially for real-time apps." },
    { q: "What is 'Throughput' in network design?", o: ["The physical capacity of the cable (e.g., 1Gbps).", "The actual amount of successful data transferred over a specific period of time.", "The time it takes to ping a server.", "The cost of the router."], a: "The actual amount of successful data transferred over a specific period of time.", e: "Throughput is always lower than Bandwidth due to overhead and congestion." },
    { q: "A 'Modular Network Design' makes it extremely easy to:", o: ["Cause a broadcast storm.", "Identify faults and scale the network by adding self-contained blocks.", "Bypass firewalls.", "Eliminate IP addressing."], a: "Identify faults and scale the network by adding self-contained blocks.", e: "Modularity provides clean boundaries for troubleshooting and scaling." },
    { q: "Which module connects the internal campus to a remote Data Center across the country?", o: ["Internet Edge", "WAN Edge", "Campus Core", "Access Module"], a: "WAN Edge", e: "The WAN Edge specifically handles long-distance private links to other company sites." },
    { q: "In network design, what does 'Convergence' mean?", o: ["The physical melting of cables.", "The speed at which all routers in the network agree on the current topology after a change or failure.", "The process of installing software.", "The combining of passwords."], a: "The speed at which all routers in the network agree on the current topology after a change or failure.", e: "Fast convergence is critical for High Availability." },
    { q: "Which routing protocol is specifically chosen for massive enterprise networks because of its extremely fast convergence time?", o: ["RIPv1", "EIGRP or OSPF", "BGP", "Static Routing"], a: "EIGRP or OSPF", e: "Interior Gateway Protocols like EIGRP and OSPF react to link failures in milliseconds." },
    { q: "Why is RIPv1 almost never used in modern Enterprise Network Designs?", o: ["It is too fast.", "It cannot handle networks larger than 15 hops and converges incredibly slowly.", "It requires expensive licenses.", "It only works on wireless devices."], a: "It cannot handle networks larger than 15 hops and converges incredibly slowly.", e: "RIP is a legacy protocol that cannot scale." },
    { q: "If an enterprise demands that internet traffic load-balances across two different ISPs, they are implementing:", o: ["Dual-homed internet connectivity", "A Hub-and-Spoke topology", "A collapsed core", "A single point of failure"], a: "Dual-homed internet connectivity", e: "Dual-homed means connecting to multiple ISPs for redundancy and load balancing." },
    { q: "Which protocol dominates the Internet Edge for routing traffic between an Enterprise and multiple ISPs?", o: ["OSPF", "EIGRP", "BGP (Border Gateway Protocol)", "RIP"], a: "BGP (Border Gateway Protocol)", e: "BGP is the only protocol capable of handling the massive routing tables of the global internet." },
    { q: "A 'VLAN' is technically a:", o: ["Physical broadcast domain.", "Logical broadcast domain.", "Routing protocol.", "Security firewall."], a: "Logical broadcast domain.", e: "VLANs divide a single physical switch into multiple logical broadcast domains." },
    { q: "Which design objective is the primary focus of 'Network Documentation'?", o: ["Performance", "Cost Efficiency", "Manageability and Maintainability", "Physical Security"], a: "Manageability and Maintainability", e: "Without documentation, managing the network relies entirely on memory, which is impossible at scale." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            const doc = {
                subjectId, moduleName, type: "MULTIPLE_CHOICE",
                category: categories[Math.floor(Math.random() * categories.length)],
                difficultyLevel: ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)],
                createdAt: new Date(),
                questionText: q.q,
                options: q.o.sort(() => Math.random() - 0.5),
                correctAnswer: q.a,
                explanation: q.e
            };
            const exists = await collection.findOne({ subjectId: doc.subjectId, questionText: doc.questionText });
            if (!exists) {
                await collection.insertOne(doc);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 1 (Batch 2 of Phase 1)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
