const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 4: Advanced Network Design";

const questions = [
    // --- Security Design Principles (15 questions) ---
    { questionText: "The 'CIA Triad' forms the foundation of secure system design. What does the 'C' stand for?", options: ["Compliance", "Control", "Confidentiality", "Cryptography"], correctAnswer: "Confidentiality", explanation: "Confidentiality ensures that information is accessible only to authorized users." },
    { questionText: "Which mechanism is primarily used to enforce Confidentiality in the CIA Triad?", options: ["Hashing", "Redundant servers", "Encryption", "Checksums"], correctAnswer: "Encryption", explanation: "Encryption hides data from unauthorized users, enforcing confidentiality." },
    { questionText: "Ensuring that systems and data are accessible when needed is the definition of which CIA Triad objective?", options: ["Confidentiality", "Integrity", "Availability", "Accountability"], correctAnswer: "Availability", explanation: "Availability focuses on keeping systems online using backups, redundancy, and High Availability (HA)." },
    { questionText: "Which tool is commonly used to verify the 'Integrity' of a downloaded file?", options: ["Firewall", "Digital signatures", "VPN", "RBAC"], correctAnswer: "Digital signatures", explanation: "Digital signatures, hashing, and checksums verify that data has not been modified (Integrity)." },
    { questionText: "Which security principle dictates that users should be given only the minimum permissions necessary to perform their tasks?", options: ["Separation of Privilege", "Principle of Least Privilege", "Defense in Depth", "Fail-Safe Defaults"], correctAnswer: "Principle of Least Privilege", explanation: "The Principle of Least Privilege limits user permissions to minimize accidental or malicious misuse." },
    { questionText: "Role-Based Access Control (RBAC) is the primary method for implementing which security principle?", options: ["Psychological Acceptability", "Principle of Least Privilege", "Economy of Mechanism", "Open Design"], correctAnswer: "Principle of Least Privilege", explanation: "RBAC ensures users only get access to what their specific job role requires." },
    { questionText: "What is the core concept behind 'Defense in Depth'?", options: ["Using a single, unbreakable firewall.", "Implementing security in multiple independent layers so if one fails, others protect the system.", "Using the most expensive security software available.", "Denying access by default to all users."], correctAnswer: "Implementing security in multiple independent layers so if one fails, others protect the system.", explanation: "Defense in depth uses layered security (e.g., Firewall -> Authentication -> Encryption -> IDS)." },
    { questionText: "If a security mechanism is 'simple, small, and easy to understand', it follows which design principle?", options: ["Economy of Mechanism", "Complete Mediation", "Open Design", "Fail-Safe Defaults"], correctAnswer: "Economy of Mechanism", explanation: "Economy of Mechanism (Simplicity) reduces the chance of security flaws by keeping systems simple." },
    { questionText: "Which principle states that 'Every access request to a resource must be checked for authorization' rather than assuming a previously authenticated user is still authorized?", options: ["Open Design", "Complete Mediation", "Separation of Privilege", "Least Common Mechanism"], correctAnswer: "Complete Mediation", explanation: "Complete Mediation ensures every single request is verified against security policies." },
    { questionText: "Which security principle is violated if different departments are forced to share the exact same file servers and user accounts, leading to potential information leakage?", options: ["Least Common Mechanism", "Psychological Acceptability", "Complete Mediation", "Fail-Safe Defaults"], correctAnswer: "Least Common Mechanism", explanation: "Least Common Mechanism advises minimizing the sharing of resources among users and processes." },
    { questionText: "If a security system is too complicated and users end up bypassing it, which design principle failed?", options: ["Psychological Acceptability", "Defense in Depth", "Accountability", "Open Design"], correctAnswer: "Psychological Acceptability", explanation: "Psychological Acceptability means security controls should be user-friendly so users actually adopt them." },
    { questionText: "Recording login attempts, file access, and administrative actions in system logs is an example of:", options: ["Separation of Privilege", "Accountability and Auditing", "Fail-Safe Defaults", "Economy of Mechanism"], correctAnswer: "Accountability and Auditing", explanation: "Accountability and Auditing ensures all significant system activities are monitored and recorded." },
    { questionText: "What is the first step in the professional Security Design Process?", options: ["Implementation", "Risk Assessment", "Requirement Analysis", "Testing and Validation"], correctAnswer: "Requirement Analysis", explanation: "Before designing security, one must first analyze the requirements of the organization." },
    { questionText: "In Healthcare Systems, what is the primary reason for strictly implementing 'Audit logs'?", options: ["To speed up network traffic.", "To track who accesses sensitive patient medical records.", "To prevent servers from overheating.", "To provide High Availability."], correctAnswer: "To track who accesses sensitive patient medical records.", explanation: "Audit logs ensure accountability and regulatory compliance regarding patient privacy." },
    { questionText: "In Banking Systems, which practice prevents a single employee from completing a massive fraudulent transaction alone?", options: ["Network segmentation", "Separation of duties for approvals", "Encryption of data at rest", "Identity and Access Management (IAM)"], correctAnswer: "Separation of duties for approvals", explanation: "Separation of duties ensures that critical operations require multiple conditions or approvals." },

    // --- Multicast Concepts (15 questions) ---
    { questionText: "What defines 'Multicasting' in computer networks?", options: ["Sending separate copies of data to each receiver one by one.", "Sending data to all devices on the entire network.", "Transmitting data to a specific group of interested receivers simultaneously.", "Sending data to the nearest router only."], correctAnswer: "Transmitting data to a specific group of interested receivers simultaneously.", explanation: "Multicast sends one stream of data that is received only by devices in the multicast group." },
    { questionText: "Which data transmission type is characterized as 'One sender → One receiver'?", options: ["Broadcast", "Multicast", "Unicast", "Anycast"], correctAnswer: "Unicast", explanation: "Unicast is a one-to-one communication, like accessing a specific website." },
    { questionText: "An ARP request is an example of which type of data transmission?", options: ["Unicast", "Multicast", "Broadcast", "Telecast"], correctAnswer: "Broadcast", explanation: "Broadcast sends a message to every device on the local network ('One sender → All devices')." },
    { questionText: "Which transmission method is most commonly used for 'Live video streaming' to multiple users?", options: ["Unicast", "Broadcast", "Multicast", "Anycast"], correctAnswer: "Multicast", explanation: "Multicast efficiently streams video to a selected group of receivers without overwhelming the network." },
    { questionText: "How are devices identified as part of a specific Multicast Group?", options: ["By sharing the same MAC address.", "By sharing a specific Multicast IP address.", "By connecting to the same physical switch.", "By using the same subnet mask."], correctAnswer: "By sharing a specific Multicast IP address.", explanation: "Each multicast group is identified by a unique multicast IP address (Class D)." },
    { questionText: "Which class of IPv4 addresses is strictly reserved for Multicast?", options: ["Class A", "Class B", "Class C", "Class D"], correctAnswer: "Class D", explanation: "Class D addresses (224.0.0.0 to 239.255.255.255) are used for multicasting." },
    { questionText: "The multicast IP address 224.0.0.1 is specifically designated to address:", options: ["All routers", "All hosts on the subnet", "Only OSPF routers", "Only web servers"], correctAnswer: "All hosts on the subnet", explanation: "224.0.0.1 is a well-known multicast address used to reach all hosts on the local network segment." },
    { questionText: "The multicast IP address 224.0.0.2 is specifically designated to address:", options: ["All hosts", "All routers on the subnet", "Only NTP servers", "Only wireless access points"], correctAnswer: "All routers on the subnet", explanation: "224.0.0.2 is used to reach all multicast-capable routers on the local segment." },
    { questionText: "In a multicast architecture, what is the role of a 'Multicast Router'?", options: ["It generates the multicast traffic.", "It joins groups to receive data.", "It forwards multicast packets only to networks with interested receivers.", "It blocks all broadcast traffic."], correctAnswer: "It forwards multicast packets only to networks with interested receivers.", explanation: "Multicast routers ensure traffic only flows to segments where receivers have requested it." },
    { questionText: "What does IGMP stand for in Multicast networking?", options: ["Internet Gateway Management Protocol", "Internet Group Management Protocol", "Internal Group Message Protocol", "Intranet Gateway Multicast Protocol"], correctAnswer: "Internet Group Management Protocol", explanation: "IGMP is used by hosts and routers to manage multicast group membership." },
    { questionText: "Which IGMP version is currently the most advanced and supports Source-Specific Multicast (SSM)?", options: ["IGMPv1", "IGMPv2", "IGMPv3", "IGMPv4"], correctAnswer: "IGMPv3", explanation: "IGMPv3 allows receivers to specify which specific source they want to receive traffic from." },
    { questionText: "Which of the following is the most commonly used Multicast Routing Protocol?", options: ["DVMRP", "MOSPF", "PIM (Protocol Independent Multicast)", "RIP"], correctAnswer: "PIM (Protocol Independent Multicast)", explanation: "PIM is widely used because it can leverage any existing unicast routing protocol to build multicast trees." },
    { questionText: "What does DVMRP stand for?", options: ["Dynamic Virtual Multicast Routing Protocol", "Distance Vector Multicast Routing Protocol", "Direct Video Multicast Routing Protocol", "Data Vector Multicast Routing Protocol"], correctAnswer: "Distance Vector Multicast Routing Protocol", explanation: "DVMRP is an early multicast routing protocol based on the Distance Vector algorithm." },
    { questionText: "Which of the following is a major DISADVANTAGE of Multicasting?", options: ["Reduces network congestion.", "Efficient bandwidth utilization.", "Complex network configuration.", "Ideal for real-time applications."], correctAnswer: "Complex network configuration.", explanation: "Multicast requires specialized configuration, IGMP, and multicast-enabled routers, making it complex." },
    { questionText: "Which application scenario benefits the most from Multicast?", options: ["Sending an email.", "Browsing a web page.", "Downloading a private PDF file.", "IPTV services and Stock market updates."], correctAnswer: "IPTV services and Stock market updates.", explanation: "IPTV and financial tickers send identical data streams to thousands of users simultaneously, making multicast ideal." },

    // --- QoS (Quality of Service) Design (15 questions) ---
    { questionText: "What is the primary goal of Quality of Service (QoS) in network design?", options: ["To encrypt all network traffic.", "To manage and prioritize network traffic so important applications perform efficiently.", "To physically increase the length of Ethernet cables.", "To automatically assign IP addresses to new devices."], correctAnswer: "To manage and prioritize network traffic so important applications perform efficiently.", explanation: "QoS ensures critical traffic (like VoIP) gets the bandwidth and low latency it needs during congestion." },
    { questionText: "Without QoS enabled on a congested network, what happens to voice and video traffic?", options: ["It is automatically prioritized.", "It is dropped entirely by the switch.", "All packets are treated equally, causing voice and video to suffer delays.", "It is converted into text data."], correctAnswer: "All packets are treated equally, causing voice and video to suffer delays.", explanation: "Without QoS, it's 'best-effort', meaning delay-sensitive traffic fights with file downloads equally." },
    { questionText: "Which QoS parameter measures the 'Amount of data transmitted per second'?", options: ["Delay", "Jitter", "Bandwidth", "Packet Loss"], correctAnswer: "Bandwidth", explanation: "Bandwidth is the capacity of the link, measured in bps, Kbps, Mbps, or Gbps." },
    { questionText: "In QoS, the formula 'Processing + Queuing + Transmission + Propagation' is used to calculate what?", options: ["Bandwidth", "Total Delay (Latency)", "Jitter", "Packet Loss"], correctAnswer: "Total Delay (Latency)", explanation: "Delay is the total time taken for a packet to travel from source to destination, accumulating across these four factors." },
    { questionText: "What is the primary negative effect of 'High Jitter' on a network?", options: ["Web pages take longer to load.", "Files fail to download completely.", "Voice and video quality degrade significantly (choppy audio/video).", "The network switch overheats."], correctAnswer: "Voice and video quality degrade significantly (choppy audio/video).", explanation: "Because real-time apps depend on a steady stream of packets, variation in arrival times (jitter) destroys playback quality." },
    { questionText: "Which QoS component is responsible for 'identifying different types of traffic' (e.g., separating Voice from Email)?", options: ["Traffic Marking", "Traffic Classification", "Traffic Policing", "Traffic Shaping"], correctAnswer: "Traffic Classification", explanation: "Classification examines packets to determine what category of traffic they belong to." },
    { questionText: "What is the function of 'Traffic Marking' in QoS?", options: ["It drops packets that exceed bandwidth.", "It delays excess packets.", "It alters the packet header to indicate its priority level.", "It stores packets in memory."], correctAnswer: "It alters the packet header to indicate its priority level.", explanation: "Marking writes a value (like DSCP or IP Precedence) into the packet header so downstream routers know its priority." },
    { questionText: "Which marking method is most commonly used in modern QoS deployments?", options: ["VLAN ID", "DSCP (Differentiated Services Code Point)", "MAC Address", "Port Number"], correctAnswer: "DSCP (Differentiated Services Code Point)", explanation: "DSCP provides 64 different priority levels and is the standard for modern QoS marking in IP headers." },
    { questionText: "If a router 'drops packets that exceed the configured bandwidth limit' immediately, which QoS mechanism is acting?", options: ["Traffic Shaping", "Priority Queuing", "Traffic Policing", "Classification"], correctAnswer: "Traffic Policing", explanation: "Policing acts as a strict limit, dropping any traffic that exceeds the allowed rate to prevent bandwidth abuse." },
    { questionText: "Unlike Policing, how does 'Traffic Shaping' handle excess packets?", options: ["It encrypts them.", "It sends them back to the source.", "It delays them in a buffer to smooth out the traffic flow.", "It drops them immediately."], correctAnswer: "It delays them in a buffer to smooth out the traffic flow.", explanation: "Shaping smooths traffic by buffering excess packets and sending them out gradually." },
    { questionText: "Which QoS mechanism 'stores packets before transmission' during periods of congestion?", options: ["Classification", "Marking", "Queuing", "Policing"], correctAnswer: "Queuing", explanation: "Queuing places packets in memory buffers (queues) while waiting for the outbound link to become available." },
    { questionText: "In Priority Queuing (PQ), what happens to low-priority traffic if the high-priority queue is always full?", options: ["It is transmitted faster.", "It shares bandwidth equally with high-priority traffic.", "It suffers from resource starvation and may never be transmitted.", "It is automatically converted to high-priority."], correctAnswer: "It suffers from resource starvation and may never be transmitted.", explanation: "PQ strictly serves the high queue first. If it's always full, lower queues are starved." },
    { questionText: "Which Queuing method attempts to 'allocate bandwidth fairly among all applications' rather than prioritizing one strictly?", options: ["FIFO", "Priority Queuing (PQ)", "Weighted Fair Queuing (WFQ)", "Strict Queuing"], correctAnswer: "Weighted Fair Queuing (WFQ)", explanation: "WFQ dynamically creates queues for different flows and schedules them fairly based on weight." },
    { questionText: "What is the first step in the QoS Design Process?", options: ["Apply QoS Policies", "Monitor Performance", "Identify Applications", "Classify Traffic"], correctAnswer: "Identify Applications", explanation: "Before you can prioritize traffic, you must identify which applications (e.g., VoIP, Web) are running on the network." },
    { questionText: "Which of the following is considered a Disadvantage of QoS Design?", options: ["Better voice quality", "Efficient bandwidth utilization", "Increased configuration complexity", "Reduced packet loss"], correctAnswer: "Increased configuration complexity", explanation: "Implementing QoS requires intricate knowledge, careful planning, and complex configurations on all routers." },

    // --- Fillers for 50 total ---
    { questionText: "Which CIA Triad component prevents unauthorized modifications to a database?", options: ["Confidentiality", "Integrity", "Availability", "Authentication"], correctAnswer: "Integrity", explanation: "Integrity ensures data remains accurate, consistent, and unmodified by unauthorized entities." },
    { questionText: "If a web server remains online even if one of its hard drives fails, it demonstrates:", options: ["Integrity", "Availability", "Confidentiality", "Least Privilege"], correctAnswer: "Availability", explanation: "Redundancy (like RAID for hard drives) ensures continuous Availability." },
    { questionText: "The 'Open Design' principle specifically encourages:", options: ["Hiding the system architecture from everyone.", "Using public review and testing to build trust in security mechanisms.", "Removing all passwords from the network.", "Sharing encryption keys publicly."], correctAnswer: "Using public review and testing to build trust in security mechanisms.", explanation: "Open Design believes public scrutiny (like open-source cryptography) makes algorithms stronger." },
    { questionText: "Which QoS parameter is most negatively impacted by taking a route that passes through a satellite link?", options: ["Bandwidth", "Delay (Latency)", "Jitter", "Marking"], correctAnswer: "Delay (Latency)", explanation: "Satellite links introduce massive propagation delay due to the physical distance to space and back." },
    { questionText: "What does 'IP Precedence' refer to in QoS?", options: ["An older method of Traffic Marking using 3 bits.", "A method to compress IP addresses.", "A routing protocol.", "A physical queuing mechanism."], correctAnswer: "An older method of Traffic Marking using 3 bits.", explanation: "IP Precedence is the legacy predecessor to DSCP, offering only 8 priority levels." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            q.category = categories[Math.floor(Math.random() * categories.length)];
            q.type = "MULTIPLE_CHOICE";
            q.difficultyLevel = ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)];
            q.createdAt = new Date();
            
            const exists = await collection.findOne({ 
                subjectId: q.subjectId, 
                questionText: q.questionText 
            });
            if (!exists) {
                await collection.insertOne(q);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 4 (Batch 2)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
