const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 2: IP Addressing & Routing";

const questions = [
    // --- IPv4, IPv6, and Subnetting (20 Qns) ---
    { q: "An organization is assigned the network 192.168.10.0/24. They need to divide it into 4 equal subnets. What subnet mask must they use?", o: ["255.255.255.128 (/25)", "255.255.255.192 (/26)", "255.255.255.224 (/27)", "255.255.255.240 (/28)"], a: "255.255.255.192 (/26)", e: "Borrowing 2 bits (2^2 = 4 subnets) changes /24 to /26, which is .192 in the last octet." },
    { q: "What is the primary motivation behind replacing IPv4 with IPv6?", o: ["IPv4 is too fast for modern routers.", "IPv4 addresses have been completely exhausted globally due to its 32-bit limitation.", "IPv6 eliminates the need for physical cables.", "IPv4 cannot be used for wireless devices."], a: "IPv4 addresses have been completely exhausted globally due to its 32-bit limitation.", e: "IPv4's 4.3 billion addresses ran out. IPv6 uses 128-bit addressing, providing virtually infinite addresses." },
    { q: "Which of the following is a valid, fully compressed IPv6 address?", o: ["2001:0db8:0000:0000:0000:ff00:0042:8329", "2001:db8::ff00:42:8329", "2001::db8::ff00:42", "2001:db8:0:0:0:ff00:42:8329"], a: "2001:db8::ff00:42:8329", e: "The '::' replaces the longest string of consecutive zeros, and leading zeros are dropped." },
    { q: "Why can the '::' (double colon) compression be used only once in an IPv6 address?", o: ["Because routers can only process one symbol.", "Because using it twice makes it impossible for the router to know exactly how many zeros were compressed in each spot.", "Because it is illegal by IEEE standards.", "Because it increases network latency."], a: "Because using it twice makes it impossible for the router to know exactly how many zeros were compressed in each spot.", e: "If '::' was used twice, the device couldn't determine the exact original 128-bit structure." },
    { q: "What does VLSM (Variable Length Subnet Masking) allow a network engineer to do?", o: ["Use the exact same subnet mask for all departments, regardless of size.", "Assign different subnet masks to different networks based on exact host requirements, minimizing wasted IP addresses.", "Convert IPv4 addresses into MAC addresses.", "Physically shrink the size of routers."], a: "Assign different subnet masks to different networks based on exact host requirements, minimizing wasted IP addresses.", e: "VLSM allows you to use a /30 for a router link and a /24 for a LAN, perfectly fitting the needs." },
    { q: "If a Point-to-Point WAN link only requires 2 IP addresses, what is the most efficient IPv4 subnet mask to use?", o: ["/24 (255.255.255.0)", "/28 (255.255.255.240)", "/30 (255.255.255.252)", "/32 (255.255.255.255)"], a: "/30 (255.255.255.252)", e: "A /30 provides exactly 4 IPs: 1 Network, 2 Usable (for the two routers), and 1 Broadcast." },
    { q: "Which protocol is natively built into IPv6 to provide end-to-end encryption and authentication without requiring third-party software?", o: ["NAT", "IPsec", "SSL", "TLS"], a: "IPsec", e: "IPsec is a mandatory, deeply integrated component of the IPv6 protocol suite." },
    { q: "Which feature of IPv4 was completely removed in IPv6 to speed up packet processing by routers?", o: ["Source IP Addresses", "Destination IP Addresses", "Header Checksum", "TTL (Time to Live)"], a: "Header Checksum", e: "IPv6 relies on upper layers (like TCP) for error checking, removing the checksum from the IP header to save router CPU." },
    { q: "In IPv6, what replaces the IPv4 'Broadcast' method?", o: ["Anycast", "Unicast", "Multicast", "There is no replacement; broadcasts are still used."], a: "Multicast", e: "IPv6 heavily utilizes Multicast (specifically all-nodes multicast) instead of overwhelming the network with Broadcasts." },
    { q: "What does CIDR (Classless Inter-Domain Routing) achieve in global internet routing?", o: ["It forces all IPs to be Class A, B, or C.", "It allows multiple smaller networks to be summarized into a single routing table entry (Supernetting).", "It blocks all traffic from unknown domains.", "It translates private IPs to public IPs."], a: "It allows multiple smaller networks to be summarized into a single routing table entry (Supernetting).", e: "CIDR ignores classes and uses prefix lengths (/), allowing massive route summarization." },
    { q: "If an IP address is 172.16.5.10 with a mask of 255.255.248.0 (/21), what is the Network Address?", o: ["172.16.5.0", "172.16.0.0", "172.16.8.0", "172.16.4.0"], a: "172.16.4.0", e: "A /21 mask means the interesting octet goes by multiples of 8. The network falls in the 172.16.4.0 block." },
    { q: "Which of the following IPv4 address blocks is designated strictly for 'Private' internal network use (RFC 1918)?", o: ["8.8.8.8 to 8.8.4.4", "10.0.0.0 to 10.255.255.255", "192.0.2.0 to 192.0.2.255", "224.0.0.0 to 239.255.255.255"], a: "10.0.0.0 to 10.255.255.255", e: "The 10.x.x.x range is the largest private address block available for internal enterprise networks." },
    { q: "Why is NAT (Network Address Translation) heavily used in IPv4 but essentially unnecessary in IPv6?", o: ["Because IPv6 doesn't support the internet.", "Because IPv4 lacks enough public IPs so internal PCs share one public IP via NAT, whereas IPv6 has enough IPs for every device globally.", "Because NAT increases network speed.", "Because IPv6 has built-in NAT automatically."], a: "Because IPv4 lacks enough public IPs so internal PCs share one public IP via NAT, whereas IPv6 has enough IPs for every device globally.", e: "IPv6's massive address space eliminates the need to hide behind a single public IP address." },
    { q: "What is an IPv6 'Link-Local' address primarily used for?", o: ["Browsing public websites.", "Communication strictly between devices on the same physical link or subnet, and cannot be routed.", "Connecting to satellite networks.", "Encrypting data."], a: "Communication strictly between devices on the same physical link or subnet, and cannot be routed.", e: "Link-Local addresses (starting with fe80::) are automatically generated and never leave the local LAN segment." },
    { q: "Which protocol automatically assigns an IPv4 address, subnet mask, and default gateway to a PC?", o: ["DNS", "DHCP", "ARP", "ICMP"], a: "DHCP", e: "Dynamic Host Configuration Protocol handles automatic IP distribution." },
    { q: "What is the IPv6 equivalent of ARP (Address Resolution Protocol)?", o: ["DHCPv6", "ICMPv6 (Neighbor Discovery Protocol)", "BGP", "OSPFv3"], a: "ICMPv6 (Neighbor Discovery Protocol)", e: "IPv6 uses NDP (which runs over ICMPv6) to map IP addresses to MAC addresses instead of broadcasting ARP." },
    { q: "An organization needs 500 hosts per subnet. Which IPv4 mask is the most efficient choice?", o: ["/24 (254 hosts)", "/23 (510 hosts)", "/22 (1022 hosts)", "/16 (65534 hosts)"], a: "/23 (510 hosts)", e: "A /23 borrows 9 bits for hosts (2^9 - 2 = 510), perfectly fitting the 500 host requirement." },
    { q: "What does the IPv4 'Time to Live' (TTL) field prevent?", o: ["Hackers stealing data.", "Packets looping endlessly in the network if there is a routing error.", "The router from overheating.", "Broadcast storms on Layer 2."], a: "Packets looping endlessly in the network if there is a routing error.", e: "Each router decrements the TTL by 1. If it hits 0, the packet is discarded." },
    { q: "Which command would you use to verify the exact path an IP packet takes to reach its destination?", o: ["ping", "ipconfig", "traceroute (or tracert)", "netstat"], a: "traceroute (or tracert)", e: "Traceroute lists every router hop along the path using ICMP TTL expiration." },
    { q: "In the IPv6 address 2001:db8:acad:1::10/64, what does the '/64' represent?", o: ["The total number of hosts allowed.", "The prefix length indicating that the first 64 bits represent the Network portion.", "The physical speed of the link.", "The security encryption level."], a: "The prefix length indicating that the first 64 bits represent the Network portion.", e: "Similar to CIDR in IPv4, /64 defines the boundary between the network prefix and the interface ID." },

    // --- Routing Basics (Static vs Dynamic) (20 Qns) ---
    { q: "What is the core function of a 'Router' in a network?", o: ["To power PoE cameras.", "To connect devices on the exact same VLAN.", "To determine the best path to forward packets between entirely different networks.", "To filter spam emails."], a: "To determine the best path to forward packets between entirely different networks.", e: "Routers look at destination IP addresses and make path decisions to move packets across network boundaries." },
    { q: "Which statement best describes 'Static Routing'?", o: ["The router learns paths automatically from other routers.", "The network administrator manually types the exact path to a specific destination into the router.", "It uses massive amounts of CPU and bandwidth.", "It is highly recommended for networks with 500+ routers."], a: "The network administrator manually types the exact path to a specific destination into the router.", e: "Static routes are hard-coded by humans." },
    { q: "What is a major DISADVANTAGE of Static Routing?", o: ["It is incredibly slow.", "If a cable breaks, the router cannot automatically adapt and traffic is dropped until an administrator manually changes the route.", "It uses too much memory.", "It is easily hacked."], a: "If a cable breaks, the router cannot automatically adapt and traffic is dropped until an administrator manually changes the route.", e: "Static routes have zero fault tolerance or adaptability." },
    { q: "When is Static Routing actually the BEST choice?", o: ["In massive enterprise networks.", "For a 'Stub Network' that only has one single exit path to the ISP.", "When connecting thousands of BGP peers.", "When the network constantly changes daily."], a: "For a 'Stub Network' that only has one single exit path to the ISP.", e: "If there's only one way out, dynamic routing is overkill; a simple static default route is perfect." },
    { q: "Which concept explains how Dynamic Routing protocols function?", o: ["Administrators write every route by hand.", "Routers automatically exchange topology information with neighbors, calculate the best paths, and adapt to failures instantly.", "Routers broadcast all data to all PCs.", "Routers ignore the routing table."], a: "Routers automatically exchange topology information with neighbors, calculate the best paths, and adapt to failures instantly.", e: "Dynamic protocols build and maintain their own routing tables autonomously." },
    { q: "What does a router use to choose between two different routing protocols (e.g., OSPF vs EIGRP) that have a path to the exact same destination?", o: ["The metric.", "Administrative Distance (AD).", "The bandwidth of the cable.", "The MAC address."], a: "Administrative Distance (AD).", e: "AD defines the 'trustworthiness' of a protocol. The router picks the protocol with the lowest AD." },
    { q: "Which route will a Cisco router prefer to reach 10.1.1.0/24: A Static Route (AD 1) or an OSPF Route (AD 110)?", o: ["The OSPF Route", "The Static Route", "It will load balance between them.", "It will drop the traffic."], a: "The Static Route", e: "Lower Administrative Distance always wins. Static (1) is trusted over OSPF (110)." },
    { q: "What does the 'Metric' represent in routing?", o: ["The cost or distance of a specific path calculated by a routing protocol to determine the 'best' route.", "The physical length of the cable in meters.", "The number of users on the network.", "The router's password."], a: "The cost or distance of a specific path calculated by a routing protocol to determine the 'best' route.", e: "Metrics differ by protocol (e.g., Hop count for RIP, Bandwidth/Delay for EIGRP) to find the fastest path." },
    { q: "Which of the following is a Distance Vector routing protocol?", o: ["OSPF", "IS-IS", "BGP", "RIP (Routing Information Protocol)"], a: "RIP (Routing Information Protocol)", e: "RIP is a classic distance vector protocol that uses hop count as its metric." },
    { q: "How do 'Link-State' routing protocols (like OSPF) differ from Distance Vector protocols?", o: ["Link-State protocols only know about their direct neighbors.", "Link-State protocols build a complete, detailed map of the entire network topology before calculating paths.", "Link-State protocols use hop count.", "Link-State protocols are much slower."], a: "Link-State protocols build a complete, detailed map of the entire network topology before calculating paths.", e: "Link-state routers have a God's-eye view of the network via the LSDB (Link State Database)." },
    { q: "What algorithm do Link-State routing protocols (OSPF, IS-IS) use to calculate the shortest path?", o: ["Bellman-Ford", "Dijkstra's Shortest Path First (SPF)", "DUAL (Diffusing Update Algorithm)", "Spanning Tree"], a: "Dijkstra's Shortest Path First (SPF)", e: "Dijkstra's algorithm is the mathematical foundation for OSPF and IS-IS." },
    { q: "Which protocol is known as an 'Advanced Distance Vector' or 'Hybrid' protocol created by Cisco?", o: ["RIP", "BGP", "EIGRP", "OSPF"], a: "EIGRP", e: "EIGRP combines the fast convergence of link-state with the simplicity of distance vector." },
    { q: "What does a 'Default Route' (0.0.0.0/0) do?", o: ["It drops all unknown traffic.", "It tells the router: 'If you don't know where to send a packet, send it this way' (usually towards the internet).", "It reboots the router.", "It formats the routing table."], a: "It tells the router: 'If you don't know where to send a packet, send it this way' (usually towards the internet).", e: "The Gateway of Last Resort ensures packets heading to the internet aren't dropped." },
    { q: "Why are 'Routing Loops' a massive threat to Distance Vector protocols?", o: ["Because they increase bandwidth.", "Because incorrect routing updates can cause packets to bounce endlessly between two routers until their TTL expires.", "Because they encrypt the data.", "Because they turn off the routers."], a: "Because incorrect routing updates can cause packets to bounce endlessly between two routers until their TTL expires.", e: "Loops cause massive congestion and CPU spikes." },
    { q: "What is 'Split Horizon'?", o: ["A physical router interface.", "A loop prevention mechanism that stops a router from advertising a route back out the same interface it learned it from.", "A satellite internet connection.", "A BGP attribute."], a: "A loop prevention mechanism that stops a router from advertising a route back out the same interface it learned it from.", e: "Split horizon prevents a router from feeding bad routing info back to its source." },
    { q: "If a router's routing table has a path to 192.168.1.0/24 and 192.168.1.0/26, and a packet arrives for 192.168.1.10, which route is chosen?", o: ["192.168.1.0/24", "192.168.1.0/26", "It load balances.", "It drops the packet."], a: "192.168.1.0/26", e: "Routers always use the 'Longest Prefix Match' rule. /26 is a more specific, exact match than /24." },
    { q: "Which of the following is considered an Exterior Gateway Protocol (EGP)?", o: ["OSPF", "EIGRP", "RIP", "BGP"], a: "BGP", e: "BGP routes between entirely different organizations (Autonomous Systems)." },
    { q: "Interior Gateway Protocols (IGPs) like OSPF and EIGRP are designed to operate:", o: ["Between different ISPs.", "Across the entire global internet.", "Strictly within a single organization's internal network (a single Autonomous System).", "Only on home Wi-Fi routers."], a: "Strictly within a single organization's internal network (a single Autonomous System).", e: "IGPs handle fast, internal routing." },
    { q: "What is an 'Autonomous System (AS)'?", o: ["A self-driving car network.", "A collection of networks under a single administrative control (like a university or ISP).", "A router that requires no configuration.", "A physical server rack."], a: "A collection of networks under a single administrative control (like a university or ISP).", e: "An AS is a unified administrative domain, critical for BGP routing." },
    { q: "What does 'Route Convergence' mean?", o: ["The physical breaking of cables.", "The state when all routers have identical, updated knowledge of the network topology after a change.", "The process of logging into a router.", "The speed of the CPU."], a: "The state when all routers have identical, updated knowledge of the network topology after a change.", e: "A converged network is stable and ready to route traffic." },

    // --- OSPF, EIGRP, and BGP Deep Dive (20 Qns) ---
    { q: "What metric does OSPF primarily use to determine the best path?", o: ["Hop count", "Cost (based on interface Bandwidth)", "Delay and Load", "AS Path length"], a: "Cost (based on interface Bandwidth)", e: "OSPF calculates 'Cost' by dividing a reference bandwidth (usually 100Mbps) by the interface's actual bandwidth." },
    { q: "Why does OSPF use 'Areas' (like Area 0, Area 1)?", o: ["To charge customers more money.", "To break massive networks into smaller domains, reducing the size of the Link-State Database and saving router CPU/Memory.", "To increase the physical length of cables.", "To prevent wireless interference."], a: "To break massive networks into smaller domains, reducing the size of the Link-State Database and saving router CPU/Memory.", e: "Areas localize routing updates so a flapping link in Area 1 doesn't force Area 2 routers to recalculate paths." },
    { q: "What is special about OSPF 'Area 0'?", o: ["It is only for wireless devices.", "It is the 'Backbone Area', and all other areas MUST connect directly to it.", "It is disabled by default.", "It uses RIP routing."], a: "It is the 'Backbone Area', and all other areas MUST connect directly to it.", e: "Area 0 is the transit core of any multi-area OSPF design." },
    { q: "What is the role of an ABR (Area Border Router) in OSPF?", o: ["It blocks all traffic.", "It sits between Area 0 and another Area, translating and summarizing routes between them.", "It connects the network to the ISP.", "It acts as a firewall."], a: "It sits between Area 0 and another Area, translating and summarizing routes between them.", e: "ABRs hold databases for both areas they connect." },
    { q: "What algorithm does EIGRP use to guarantee loop-free routing?", o: ["Dijkstra SPF", "DUAL (Diffusing Update Algorithm)", "Bellman-Ford", "Spanning Tree"], a: "DUAL (Diffusing Update Algorithm)", e: "DUAL calculates primary paths and backup paths instantly to avoid loops." },
    { q: "Which metrics does EIGRP use by default to calculate its composite metric?", o: ["Hop count and MTU", "Cost and Reliability", "Bandwidth and Delay", "AS Path and Local Preference"], a: "Bandwidth and Delay", e: "EIGRP looks at the slowest bandwidth link in the path and adds up all the delays." },
    { q: "What makes EIGRP's 'Feasible Successor' feature so powerful?", o: ["It encrypts data.", "It acts as a pre-calculated, loop-free backup route that can be used instantly (sub-second) if the primary route fails.", "It increases internet speed.", "It bypasses firewalls."], a: "It acts as a pre-calculated, loop-free backup route that can be used instantly (sub-second) if the primary route fails.", e: "Because the backup route is already in the topology table, EIGRP doesn't have to waste time recalculating if a link drops." },
    { q: "BGP (Border Gateway Protocol) is known as a 'Path Vector' protocol. What is its primary metric for choosing a route across the internet?", o: ["Bandwidth", "Hop count", "AS_PATH (The number of Autonomous Systems it must cross)", "Delay"], a: "AS_PATH (The number of Autonomous Systems it must cross)", e: "BGP prefers the route that traverses the fewest number of ISP networks (AS hops)." },
    { q: "Why is BGP used to run the Global Internet instead of OSPF?", o: ["OSPF is too expensive.", "BGP can handle routing tables with millions of routes and apply extreme policy-based filtering, which would crash OSPF.", "BGP is much faster than OSPF.", "OSPF cannot use IP addresses."], a: "BGP can handle routing tables with millions of routes and apply extreme policy-based filtering, which would crash OSPF.", e: "BGP is built for immense scale and strict policy control, not raw speed." },
    { q: "If an enterprise wants to connect to two different ISPs (e.g., AT&T and Verizon) and control exactly which traffic uses which ISP, they MUST run:", o: ["RIP", "BGP", "Static Routes only", "EIGRP"], a: "BGP", e: "BGP is required when multihoming to multiple ISPs to advertise public IP blocks and manipulate inbound/outbound paths." },
    { q: "What does an OSPF 'Hello' packet do?", o: ["It transfers large files.", "It discovers neighboring routers and ensures they are still alive.", "It deletes routing tables.", "It configures IP addresses."], a: "It discovers neighboring routers and ensures they are still alive.", e: "Hello packets are tiny keep-alives sent every few seconds." },
    { q: "What is an ASBR (Autonomous System Boundary Router) in OSPF?", o: ["A router that has no OSPF configured.", "A router that connects the OSPF network to a completely different routing domain (like EIGRP or the Internet).", "A router only in Area 0.", "A switch."], a: "A router that connects the OSPF network to a completely different routing domain (like EIGRP or the Internet).", e: "ASBRs 'redistribute' outside routes into the internal OSPF network." },
    { q: "What happens during 'Route Redistribution'?", o: ["A router takes routes learned from one protocol (like OSPF) and injects them into another protocol (like BGP).", "A router drops all packets.", "A router encrypts the routing table.", "A router reboots."], a: "A router takes routes learned from one protocol (like OSPF) and injects them into another protocol (like BGP).", e: "Redistribution translates routes so two different protocol domains can talk." },
    { q: "Why is OSPF strictly a hierarchical design?", o: ["Because it forces you to buy expensive cables.", "Because all areas must logically connect through the central backbone (Area 0) to prevent routing loops.", "Because it uses IPv6 only.", "Because it only supports 10 routers."], a: "Because all areas must logically connect through the central backbone (Area 0) to prevent routing loops.", e: "A strict Hub-and-Spoke logical layout (Area 0 is the Hub) guarantees loop-free area communication." },
    { q: "Which EIGRP table holds all possible routes to a destination (both primary and backup)?", o: ["The Routing Table", "The Neighbor Table", "The Topology Table", "The MAC Address Table"], a: "The Topology Table", e: "The Topology Table holds every learned path. The best path is then copied to the Routing Table." },
    { q: "What is a 'Stub Router' in EIGRP?", o: ["A router that only uses BGP.", "An edge router that tells neighbors not to query it for backup routes, saving massive amounts of network bandwidth and CPU.", "A router with no cables attached.", "A broken router."], a: "An edge router that tells neighbors not to query it for backup routes, saving massive amounts of network bandwidth and CPU.", e: "Stub routers prevent EIGRP from wasting time asking branch offices for routes to the core." },
    { q: "In BGP, what does the 'Local Preference' attribute do?", o: ["It determines how traffic LEAVES an Autonomous System (higher is better).", "It determines how traffic ENTERS an Autonomous System.", "It calculates bandwidth.", "It assigns IP addresses."], a: "It determines how traffic LEAVES an Autonomous System (higher is better).", e: "Local Pref is used by admins to force outbound traffic to use ISP A instead of ISP B." },
    { q: "What does 'eBGP' stand for?", o: ["Encrypted BGP", "External BGP (routing between two completely different Autonomous Systems)", "Enhanced BGP", "Enterprise BGP"], a: "External BGP (routing between two completely different Autonomous Systems)", e: "eBGP is the protocol speaking between your company's edge router and the ISP's router." },
    { q: "Which protocol is renowned for its extremely complex path selection process (weight, local pref, AS path, origin code, MED)?", o: ["RIP", "EIGRP", "OSPF", "BGP"], a: "BGP", e: "BGP has a very long, complex list of attributes it checks to decide the best path." },
    { q: "Why would a network engineer 'Summarize' routes (e.g., combining four /24 networks into one /22)?", o: ["To increase latency.", "To drastically reduce the size of routing tables, saving router memory and CPU.", "To prevent ping requests.", "To physically cut cables."], a: "To drastically reduce the size of routing tables, saving router memory and CPU.", e: "Summarization hides complexity. Instead of knowing 100 distinct routes, a core router only needs to know 1 summary route." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            const doc = {
                subjectId, moduleName, type: "MULTIPLE_CHOICE",
                category: categories[Math.floor(Math.random() * categories.length)],
                difficultyLevel: ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)],
                createdAt: new Date(),
                questionText: q.q,
                options: q.o.sort(() => Math.random() - 0.5),
                correctAnswer: q.a,
                explanation: q.e
            };
            const exists = await collection.findOne({ subjectId: doc.subjectId, questionText: doc.questionText });
            if (!exists) {
                await collection.insertOne(doc);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 2 (Batch 1 of Phase 2)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
