const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 4: Advanced Network Design";

const questions = [
    // --- Cloud Computing Models (20 Qns) ---
    { q: "Which cloud service model provides the highest level of control to the customer, granting direct access to raw virtual machines, storage, and networking?", o: ["SaaS", "PaaS", "IaaS (Infrastructure as a Service)", "FaaS"], a: "IaaS (Infrastructure as a Service)", e: "IaaS gives you the bare virtual hardware (like AWS EC2), so you must install and manage the Operating System yourself." },
    { q: "A software developer wants to write code and instantly deploy it without worrying about managing the underlying Linux servers or scaling them. Which model is best?", o: ["IaaS", "PaaS (Platform as a Service)", "SaaS", "DaaS"], a: "PaaS (Platform as a Service)", e: "PaaS (like Heroku or AWS Elastic Beanstalk) hides the OS and infrastructure, providing a ready-made runtime environment for developers." },
    { q: "If a company replaces its internally hosted Microsoft Exchange email server with Office 365, they have migrated to which cloud model?", o: ["IaaS", "PaaS", "SaaS (Software as a Service)", "On-Premises"], a: "SaaS (Software as a Service)", e: "SaaS delivers a fully functioning, finished application directly to the end-user over the internet." },
    { q: "What is the defining characteristic of a 'Public Cloud' (like AWS, Azure, GCP)?", o: ["It is free.", "Resources are owned, operated, and shared by a third-party provider and delivered over the public internet.", "It can only be accessed by the government.", "It requires a physical key."], a: "Resources are owned, operated, and shared by a third-party provider and delivered over the public internet.", e: "Public clouds use a multi-tenant model where hardware is shared among millions of different customers." },
    { q: "Why would a highly secure intelligence agency choose to build a 'Private Cloud' instead of using AWS?", o: ["Because AWS is too slow.", "To guarantee absolute data isolation and physical control, ensuring their hardware is never shared with another organization.", "Because they want to use IPv4.", "To reduce their electricity bill."], a: "To guarantee absolute data isolation and physical control, ensuring their hardware is never shared with another organization.", e: "Private clouds are single-tenant, offering maximum security and compliance at the cost of extremely high CapEx." },
    { q: "What defines a 'Hybrid Cloud' architecture?", o: ["Using both Windows and Linux.", "Combining an on-premises Private Cloud with a Public Cloud, allowing data and applications to seamlessly move between them.", "Using two different web browsers.", "Using Wi-Fi and Ethernet simultaneously."], a: "Combining an on-premises Private Cloud with a Public Cloud, allowing data and applications to seamlessly move between them.", e: "Hybrid clouds offer the security of private infrastructure with the massive scalability (cloud bursting) of public infrastructure." },
    { q: "In the context of Cloud Computing, what does 'Elasticity' mean?", o: ["The ability to bounce packets back.", "The ability of the cloud to automatically scale computing resources up or down in real-time based strictly on current demand.", "The physical stretch of the cables.", "The ability to run macOS on Windows."], a: "The ability of the cloud to automatically scale computing resources up or down in real-time based strictly on current demand.", e: "Elasticity prevents overpaying for idle servers during the night and prevents crashing during peak daytime traffic." },
    { q: "What is the primary financial advantage of migrating from an On-Premises Data Center to an IaaS Public Cloud?", o: ["It eliminates the need for passwords.", "Shifting massive upfront Capital Expenditure (CapEx) to a pay-as-you-go Operational Expenditure (OpEx).", "It stops you from paying taxes.", "It makes software free."], a: "Shifting massive upfront Capital Expenditure (CapEx) to a pay-as-you-go Operational Expenditure (OpEx).", e: "Instead of buying $1M in servers today, you rent them for $1,000 a month." },
    { q: "Which cloud concept refers to taking a single physical server and dividing its resources among multiple different cloud customers?", o: ["Monopoly", "Multi-Tenancy", "Single-Tenancy", "Encapsulation"], a: "Multi-Tenancy", e: "Multi-tenancy is the core economic engine of the public cloud, though it requires strict hypervisor security to prevent data leakage." },
    { q: "What is a 'VPC' (Virtual Private Cloud)?", o: ["A physical router.", "A logically isolated, private section of a Public Cloud where you can define your own IP addresses, subnets, and firewalls.", "A public chat room.", "A VPN client."], a: "A logically isolated, private section of a Public Cloud where you can define your own IP addresses, subnets, and firewalls.", e: "A VPC lets you build a virtual data center topology inside AWS or Azure." },
    { q: "If you rent an IaaS Virtual Machine (like an EC2 instance), who is responsible for patching the Operating System (e.g., updating Windows)?", o: ["The Cloud Provider (e.g., Amazon/Microsoft)", "The Customer (You)", "No one", "The ISP"], a: "The Customer (You)", e: "Under the Shared Responsibility Model, IaaS leaves OS-level management entirely to the customer." },
    { q: "In a SaaS model (like Google Workspace), who is responsible for patching the underlying server Operating System?", o: ["The Customer (You)", "The Cloud Provider (Google)", "The ISP", "The end user"], a: "The Cloud Provider (Google)", e: "With SaaS, the provider manages everything from the hardware up to the application software." },
    { q: "Which technology is considered a more lightweight, faster-starting alternative to traditional Virtual Machines in cloud environments?", o: ["Mainframes", "Containers (e.g., Docker)", "Bare-metal servers", "Tape drives"], a: "Containers (e.g., Docker)", e: "Containers do not require booting a full OS, making them start in milliseconds." },
    { q: "What is the purpose of 'Cloud Bursting' in a Hybrid Cloud setup?", o: ["To delete old data.", "When the private cloud reaches 100% capacity during a traffic spike, overflow traffic is automatically routed to the public cloud.", "To cool down the servers.", "To stop hackers from entering."], a: "When the private cloud reaches 100% capacity during a traffic spike, overflow traffic is automatically routed to the public cloud.", e: "Cloud bursting uses the public cloud as a massive, on-demand safety valve." },
    { q: "Which term describes a cloud service that executes code strictly in response to an event trigger, without the developer ever provisioning a server (Serverless)?", o: ["IaaS", "SaaS", "FaaS (Function as a Service)", "DaaS"], a: "FaaS (Function as a Service)", e: "FaaS (like AWS Lambda) runs a tiny piece of code instantly when triggered, and you only pay for the exact milliseconds it runs." },
    { q: "What is the greatest security concern specifically associated with 'Multi-Tenancy' in the Public Cloud?", o: ["The servers are too heavy.", "A vulnerability in the hypervisor could allow one customer (tenant) to access the memory or data of another customer on the same physical machine.", "It uses too much electricity.", "It blocks Wi-Fi signals."], a: "A vulnerability in the hypervisor could allow one customer (tenant) to access the memory or data of another customer on the same physical machine.", e: "Hypervisor escape is the ultimate nightmare scenario in public clouds." },
    { q: "Why do large enterprises often use a 'Multi-Cloud' strategy (e.g., using both AWS and Azure)?", o: ["Because they don't know which one works.", "To avoid Vendor Lock-in and ensure that if one entire cloud provider suffers a global outage, the business survives.", "Because it is cheaper.", "Because they only have one router."], a: "To avoid Vendor Lock-in and ensure that if one entire cloud provider suffers a global outage, the business survives.", e: "Multi-cloud spreads the massive risk of relying on a single tech giant." },
    { q: "Which component is strictly necessary for a remote employee to securely connect to a corporate VPC in the cloud?", o: ["A physical cable.", "A VPN (Virtual Private Network) gateway or IPsec tunnel.", "A BGP router.", "A new monitor."], a: "A VPN (Virtual Private Network) gateway or IPsec tunnel.", e: "VPCs are private; the only secure way in from the public internet is via VPN." },
    { q: "What is an 'Internet Gateway' (IGW) in cloud networking?", o: ["A firewall that blocks everything.", "A logical component attached to a VPC that provides a target in the routing table for internet-bound traffic, allowing VMs to talk to the public.", "A physical switch.", "A database."], a: "A logical component attached to a VPC that provides a target in the routing table for internet-bound traffic, allowing VMs to talk to the public.", e: "Without an IGW, your cloud VMs are trapped in a purely internal network." },
    { q: "In a cloud VPC, what is the difference between a Public Subnet and a Private Subnet?", o: ["Public subnets have a route to the Internet Gateway; Private subnets do not.", "Public subnets are free; Private subnets cost money.", "Public subnets use IPv6; Private subnets use IPv4.", "There is no difference."], a: "Public subnets have a route to the Internet Gateway; Private subnets do not.", e: "Routing dictates public vs private in the cloud. Private subnets require a NAT Gateway to reach out." },

    // --- SDN (Software Defined Networking) (20 Qns) ---
    { q: "Historically, traditional network devices (like physical routers) contained both the ________ and the ________ in the same box.", o: ["Power supply and Keyboard", "Control Plane and Data Plane", "Internet and Wi-Fi", "Firewall and Antivirus"], a: "Control Plane and Data Plane", e: "Traditional routers had to both calculate the routes (Control) and physically move the packets (Data) autonomously." },
    { q: "What is the fundamental architectural change introduced by Software Defined Networking (SDN)?", o: ["It makes cables wireless.", "It physically separates the Control Plane from the Data Plane, centralizing the intelligence into a software Controller.", "It deletes IP addresses.", "It encrypts all traffic by default."], a: "It physically separates the Control Plane from the Data Plane, centralizing the intelligence into a software Controller.", e: "SDN turns physical switches into 'dumb' forwarders that simply obey the central 'smart' Controller." },
    { q: "In an SDN architecture, what is the primary function of the 'Data Plane' (or Forwarding Plane)?", o: ["Calculating BGP routes.", "Physically switching and moving packets from an input port to an output port as fast as possible.", "Authenticating users.", "Running the network management GUI."], a: "Physically switching and moving packets from an input port to an output port as fast as possible.", e: "The data plane is the muscle of the network, doing exactly what it's told at hardware speed." },
    { q: "Which SDN plane is responsible for building routing tables, learning MAC addresses, and making the actual decisions about where traffic should go?", o: ["Data Plane", "Physical Plane", "Control Plane", "Application Plane"], a: "Control Plane", e: "The Control plane is the brain. In SDN, this brain is removed from the router and centralized." },
    { q: "What is an 'SDN Controller'?", o: ["A physical router.", "The centralized software 'brain' (Control Plane) that oversees the entire network and pushes rules down to the switches.", "A user's laptop.", "A firewall."], a: "The centralized software 'brain' (Control Plane) that oversees the entire network and pushes rules down to the switches.", e: "The controller (like Cisco DNA Center) has a global, god's-eye view of the entire topology." },
    { q: "In SDN, what is a 'Southbound API' used for?", o: ["For the Controller to communicate DOWN to the physical network hardware (switches/routers).", "For the user to browse the internet.", "For the Controller to talk UP to business applications.", "For encrypting passwords."], a: "For the Controller to communicate DOWN to the physical network hardware (switches/routers).", e: "Southbound APIs (like OpenFlow) push the forwarding rules into the hardware ASICs." },
    { q: "Which protocol is the most famous, open-standard 'Southbound API' used in SDN?", o: ["BGP", "OpenFlow", "OSPF", "HTTP"], a: "OpenFlow", e: "OpenFlow was the original protocol that allowed the controller to program the flow tables of switches." },
    { q: "In SDN, what is a 'Northbound API' used for?", o: ["Connecting to the physical switches.", "Allowing the centralized Controller to communicate UP to high-level network applications and orchestration software.", "Turning off the power.", "Running BGP."], a: "Allowing the centralized Controller to communicate UP to high-level network applications and orchestration software.", e: "Northbound APIs allow a Python script or firewall app to tell the Controller what policy to implement." },
    { q: "What is 'Network Programmability'?", o: ["Typing commands slowly into a CLI.", "The ability to use software code (like Python) and APIs to automatically configure, manage, and scale the network.", "Changing the physical wires.", "Using a mouse to click a router."], a: "The ability to use software code (like Python) and APIs to automatically configure, manage, and scale the network.", e: "Programmability replaces manual CLI typing with fast, error-free automation." },
    { q: "Why do traditional networks struggle to support modern Cloud Computing data centers?", o: ["They are too secure.", "Traditional networks are manual, static, and cannot adapt instantly when thousands of VMs are spun up or destroyed.", "They use IPv4.", "They don't use electricity."], a: "Traditional networks are manual, static, and cannot adapt instantly when thousands of VMs are spun up or destroyed.", e: "Cloud computing is dynamic; traditional CLI networking is painfully slow." },
    { q: "What does 'NFV' (Network Functions Virtualization) aim to achieve?", o: ["Buying more Cisco routers.", "Replacing expensive, proprietary hardware appliances (like physical Firewalls or Load Balancers) with software running on standard, cheap servers.", "Turning off the network.", "Encrypting the hard drives."], a: "Replacing expensive, proprietary hardware appliances (like physical Firewalls or Load Balancers) with software running on standard, cheap servers.", e: "NFV virtualizes the network appliances themselves, just like hypervisors virtualized servers." },
    { q: "How do SDN and NFV relate to each other?", o: ["They are enemies.", "They are the exact same thing.", "SDN centralizes the control of the network; NFV virtualizes the physical network devices. They are highly complementary.", "NFV only works on Wi-Fi."], a: "SDN centralizes the control of the network; NFV virtualizes the physical network devices. They are highly complementary.", e: "SDN routes the traffic; NFV provides the virtual firewalls/routers that the traffic flows through." },
    { q: "Which data format is most commonly used by modern REST APIs (Northbound) to exchange network configurations?", o: ["Binary code", "JSON (JavaScript Object Notation)", "HTML", "Morse code"], a: "JSON (JavaScript Object Notation)", e: "JSON is human-readable and easily parsed by Python scripts." },
    { q: "What does a 'REST API' rely on to function?", o: ["Standard HTTP methods like GET, POST, PUT, and DELETE.", "Physical cables.", "BGP routing tables.", "OpenFlow protocols."], a: "Standard HTTP methods like GET, POST, PUT, and DELETE.", e: "REST uses the same underlying technology as web browsers to send instructions." },
    { q: "In an automated network, what is 'Infrastructure as Code' (IaC)?", o: ["Writing malware.", "Managing and provisioning data centers through machine-readable definition files (code) rather than physical hardware configuration.", "Encrypting the server.", "Building routers from scratch."], a: "Managing and provisioning data centers through machine-readable definition files (code) rather than physical hardware configuration.", e: "Tools like Terraform or Ansible allow you to deploy a whole network using a script." },
    { q: "What is the major security advantage of having a centralized SDN Controller?", o: ["It blocks all traffic.", "It allows administrators to instantly enforce a single, unified security policy across thousands of switches at the push of a button.", "It prevents people from entering the building.", "It hides IP addresses."], a: "It allows administrators to instantly enforce a single, unified security policy across thousands of switches at the push of a button.", e: "Centralized control eliminates the risk of human error when configuring 500 individual firewalls." },
    { q: "What is the major security vulnerability introduced by an SDN Controller?", o: ["It is too heavy.", "It acts as a massive Single Point of Failure (SPOF) and an ultimate target for hackers; if the controller is compromised, the whole network falls.", "It deletes passwords.", "It slows down the internet."], a: "It acts as a massive Single Point of Failure (SPOF) and an ultimate target for hackers; if the controller is compromised, the whole network falls.", e: "Because the controller has God-mode access, protecting it is paramount." },
    { q: "Which SDN concept allows multiple tenants (companies) to share the same physical network hardware while keeping their traffic completely isolated?", o: ["Routing", "Network Slicing / Virtualization", "Subnetting", "Physical separation"], a: "Network Slicing / Virtualization", e: "SDN allows the creation of isolated 'slices' of the network, heavily used in 5G and cloud." },
    { q: "When using Python to automate a network, what does the 'Requests' library do?", o: ["It formats the hard drive.", "It makes HTTP calls (GET, POST) to the SDN Controller's REST API.", "It calculates OSPF metrics.", "It installs Windows."], a: "It makes HTTP calls (GET, POST) to the SDN Controller's REST API.", e: "The requests library is the standard way Python talks to web-based APIs." },
    { q: "What is the purpose of 'NETCONF' and 'YANG' in modern networking?", o: ["They are video games.", "YANG models the data strictly, and NETCONF is the protocol used to push those configurations to routers securely via SSH.", "They are used to encrypt web traffic.", "They calculate BGP routes."], a: "YANG models the data strictly, and NETCONF is the protocol used to push those configurations to routers securely via SSH.", e: "NETCONF/YANG is the modern, structured replacement for typing CLI commands." },

    // --- High-Level Advanced Design Mixed Scenarios (20 Qns) ---
    { q: "Scenario: A global streaming company needs their videos to load instantly anywhere in the world. What network design must they use?", o: ["A single Tier 1 Data Center.", "A Content Delivery Network (CDN) utilizing Anycast addressing to route users to the geographically closest server.", "A Hub-and-Spoke WAN.", "A collapsed core campus."], a: "A Content Delivery Network (CDN) utilizing Anycast addressing to route users to the geographically closest server.", e: "CDNs push the data to the edge of the internet, right next to the user." },
    { q: "In a Hybrid Cloud, what is the best way to securely connect the On-Premises Data Center to the AWS VPC?", o: ["A public Wi-Fi link.", "A dedicated private cloud connection (like AWS Direct Connect or Azure ExpressRoute).", "A standard internet connection.", "A satellite link."], a: "A dedicated private cloud connection (like AWS Direct Connect or Azure ExpressRoute).", e: "Direct Connect bypasses the public internet entirely, providing high-speed, private, predictable latency." },
    { q: "What is a 'Zero Trust Network Architecture' (ZTNA)?", o: ["Trusting everyone on the inside.", "A security model that assumes threats exist both outside and INSIDE the network, requiring strict authentication for every single packet and session.", "A network with zero firewalls.", "A network with no routers."], a: "A security model that assumes threats exist both outside and INSIDE the network, requiring strict authentication for every single packet and session.", e: "Zero trust destroys the old 'castle-and-moat' idea that internal users are safe." },
    { q: "Scenario: An engineer deploys 500 new branch routers. Instead of manually configuring them via CLI, the engineer writes a script that automatically configures them in 10 minutes. This is an example of:", o: ["Network Automation and Programmability", "Physical Layer Design", "Static Routing", "Troubleshooting"], a: "Network Automation and Programmability", e: "Automation removes human error and drastically reduces deployment time." },
    { q: "Which tool is considered an 'Infrastructure as Code' (IaC) configuration management tool?", o: ["Microsoft Word", "Ansible", "Ping", "Wireshark"], a: "Ansible", e: "Ansible uses YAML playbooks to automate the configuration of thousands of devices simultaneously." },
    { q: "In SDN, if a switch receives a packet with a destination it does not recognize in its flow table, what does it do?", o: ["It drops the packet immediately.", "It forwards the packet to the SDN Controller and asks 'What should I do with this?'", "It broadcasts it to all ports.", "It sends it to the internet."], a: "It forwards the packet to the SDN Controller and asks 'What should I do with this?'", e: "The 'dumb' switch relies entirely on the 'smart' controller to make unknown routing decisions." },
    { q: "What does 'White-box Switching' mean in the SDN era?", o: ["Painting Cisco switches white.", "Buying cheap, generic, unbranded hardware switches and installing a custom SDN-compatible operating system on them.", "Using switches that have no security.", "Using switches made of plastic."], a: "Buying cheap, generic, unbranded hardware switches and installing a custom SDN-compatible operating system on them.", e: "White-boxing breaks vendor lock-in, separating the hardware from the software." },
    { q: "How does SD-WAN save massive amounts of money for enterprises?", o: ["By stealing internet.", "By dynamically routing non-critical traffic over cheap broadband internet while reserving expensive MPLS lines ONLY for critical voice/video.", "By turning off the routers at night.", "By using smaller cables."], a: "By dynamically routing non-critical traffic over cheap broadband internet while reserving expensive MPLS lines ONLY for critical voice/video.", e: "SD-WAN optimizes link usage, drastically reducing the need for massive MPLS pipes." },
    { q: "What is a 'Microservice Architecture'?", o: ["A tiny physical server.", "Breaking a massive monolithic application into dozens of small, independent services (like billing, login, search) that communicate via APIs.", "A network for small businesses.", "A type of firewall."], a: "Breaking a massive monolithic application into dozens of small, independent services (like billing, login, search) that communicate via APIs.", e: "Microservices require heavy East-West Data Center networking." },
    { q: "Which protocol allows a Virtual Machine to retain its exact IP address even if it is live-migrated (vMotion) to a completely different physical subnet in a modern Data Center?", o: ["RIPv1", "VXLAN (Virtual Extensible LAN)", "OSPF", "BGP"], a: "VXLAN (Virtual Extensible LAN)", e: "VXLAN encapsulates Layer 2 traffic over a Layer 3 network, stretching a VLAN across the entire data center." },
    { q: "What problem does VXLAN solve that traditional VLANs could not?", o: ["VLANs use too much power.", "Traditional VLANs are limited to 4,096 IDs, which is too small for massive cloud data centers. VXLAN supports 16 million IDs.", "VLANs cannot use IPv4.", "VLANs are easily hacked."], a: "Traditional VLANs are limited to 4,096 IDs, which is too small for massive cloud data centers. VXLAN supports 16 million IDs.", e: "VXLAN provides massive multi-tenancy scale for the cloud." },
    { q: "Scenario: You query an SDN Controller via API to get a list of all down interfaces. The controller replies with a massive block of text formatted with curly braces `{}` and key-value pairs. What format is this?", o: ["XML", "JSON", "HTML", "YAML"], a: "JSON", e: "JSON (JavaScript Object Notation) uses `{}` and `\"key\": \"value\"` syntax." },
    { q: "What does a '200 OK' HTTP status code mean when a Python script sends a REST API request to a router?", o: ["The router crashed.", "The request was successful and the data was retrieved or the configuration was applied.", "The router needs a password.", "The IP address is wrong."], a: "The request was successful and the data was retrieved or the configuration was applied.", e: "200-level codes indicate success in REST APIs." },
    { q: "What does a '401 Unauthorized' HTTP status code mean in an API call?", o: ["The network is too slow.", "The Python script failed to provide the correct API token or username/password.", "The router is on fire.", "The cable is unplugged."], a: "The Python script failed to provide the correct API token or username/password.", e: "401 means authentication failed." },
    { q: "Which tool is commonly used to manually test REST APIs before writing Python scripts?", o: ["Wireshark", "Postman", "Ping", "Traceroute"], a: "Postman", e: "Postman is an industry-standard GUI for testing API endpoints." },
    { q: "What is 'Telemetry' in modern advanced networks?", o: ["Watching television.", "Instead of polling the router every 5 minutes (SNMP), the router continuously 'pushes' real-time performance data to an analytics engine.", "Configuring the router.", "Encrypting data."], a: "Instead of polling the router every 5 minutes (SNMP), the router continuously 'pushes' real-time performance data to an analytics engine.", e: "Streaming telemetry provides sub-second visibility into network health." },
    { q: "How does AI (Artificial Intelligence) integrate with SDN Controllers?", o: ["It plays games.", "It analyzes streaming telemetry to predict failures before they happen and automatically reroutes traffic without human intervention.", "It installs Windows.", "It blocks all users."], a: "It analyzes streaming telemetry to predict failures before they happen and automatically reroutes traffic without human intervention.", e: "AI-driven Intent-Based Networking (IBN) is the future of autonomous networks." },
    { q: "What is 'Intent-Based Networking' (IBN)?", o: ["Typing commands randomly.", "The administrator tells the controller the *intent* (e.g., 'Make sure Voice is fast'), and the controller automatically writes all the complex code to make it happen.", "A physical hardware switch.", "A type of cable."], a: "The administrator tells the controller the *intent* (e.g., 'Make sure Voice is fast'), and the controller automatically writes all the complex code to make it happen.", e: "IBN bridges the gap between business goals and technical CLI commands." },
    { q: "Which technology would allow a developer to spin up a complete virtual network, 5 web servers, and a database using a single text file?", o: ["BGP", "Terraform (Infrastructure as Code)", "Spanning Tree", "OSPF"], a: "Terraform (Infrastructure as Code)", e: "Terraform provisions complex cloud infrastructures via declarative code." },
    { q: "Why is 'Version Control' (like Git) critical when using Infrastructure as Code?", o: ["To play music.", "Because the network is now just a text file (code). Git tracks every change, who made it, and allows instant rollback if the network crashes.", "To increase bandwidth.", "To block viruses."], a: "Because the network is now just a text file (code). Git tracks every change, who made it, and allows instant rollback if the network crashes.", e: "Treating infrastructure as code means using software developer tools (Git) to manage the network safely." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            const doc = {
                subjectId, moduleName, type: "MULTIPLE_CHOICE",
                category: categories[Math.floor(Math.random() * categories.length)],
                difficultyLevel: ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)],
                createdAt: new Date(),
                questionText: q.q,
                options: q.o.sort(() => Math.random() - 0.5),
                correctAnswer: q.a,
                explanation: q.e
            };
            const exists = await collection.findOne({ subjectId: doc.subjectId, questionText: doc.questionText });
            if (!exists) {
                await collection.insertOne(doc);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 4 (Batch 1 of Phase 4)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
