const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; 
const moduleName = "Unit 5: Implementation and Operations";

const questions = [
    // --- Network Management & Monitoring (20 Qns) ---
    { q: "What is the primary function of SNMP (Simple Network Management Protocol)?", o: ["To send emails.", "To allow administrators to remotely monitor the health (CPU, RAM, bandwidth) of network devices and modify their configurations.", "To encrypt hard drives.", "To assign IP addresses."], a: "To allow administrators to remotely monitor the health (CPU, RAM, bandwidth) of network devices and modify their configurations.", e: "SNMP is the universal language for network monitoring and management." },
    { q: "Which component of SNMP resides on the actual router or switch being monitored?", o: ["The SNMP Manager (NMS)", "The SNMP Agent", "The MIB (Management Information Base)", "The Trap"], a: "The SNMP Agent", e: "The Agent is the software running on the device that collects local data and answers questions from the Manager." },
    { q: "In SNMP, what is a 'MIB' (Management Information Base)?", o: ["A physical hard drive.", "A hierarchical, tree-structured database that defines all the specific variables (OIDs) that can be monitored on a device.", "A firewall rule.", "A routing protocol metric."], a: "A hierarchical, tree-structured database that defines all the specific variables (OIDs) that can be monitored on a device.", e: "The MIB acts as a dictionary so the Manager knows exactly what data it can ask the Agent for." },
    { q: "What is the primary difference between an SNMP 'Poll' and an SNMP 'Trap'?", o: ["There is no difference.", "A Poll is when the Manager asks the Agent for data; a Trap is an unsolicited alert sent by the Agent to the Manager when something breaks.", "A Poll is for Windows; a Trap is for Linux.", "A Poll uses IPv4; a Trap uses IPv6."], a: "A Poll is when the Manager asks the Agent for data; a Trap is an unsolicited alert sent by the Agent to the Manager when something breaks.", e: "Traps are critical for instant alerting (like a fan failing), rather than waiting 5 minutes for the next Poll." },
    { q: "Why is SNMP version 1 and version 2c highly discouraged in modern enterprise networks?", o: ["They are too slow.", "They send all management data and authentication strings (community strings) in clear-text, making them incredibly easy to hack.", "They require fiber optic cables.", "They cost too much money."], a: "They send all management data and authentication strings (community strings) in clear-text, making them incredibly easy to hack.", e: "Clear-text management protocols are massive security vulnerabilities." },
    { q: "What critical feature does SNMPv3 introduce?", o: ["Faster routing.", "Strong cryptographic authentication and encryption (Confidentiality and Integrity) for all management traffic.", "The ability to assign IPv6 addresses.", "Wireless support."], a: "Strong cryptographic authentication and encryption (Confidentiality and Integrity) for all management traffic.", e: "SNMPv3 secures the management plane, ensuring hackers cannot read or alter device configs." },
    { q: "While SNMP monitors 'Hardware Health' (like CPU %), which protocol is specifically designed to analyze 'Traffic Flow' (who is talking to whom, and how much data)?", o: ["OSPF", "NetFlow (or IPFIX)", "BGP", "Spanning Tree"], a: "NetFlow (or IPFIX)", e: "NetFlow acts like a phone bill, recording the source, destination, protocol, and volume of every conversation." },
    { q: "Why is NetFlow critical for Cyber Security and Forensics?", o: ["It blocks all hackers.", "It provides a historical record of all traffic, allowing security teams to see exactly what data was exfiltrated during a breach even months later.", "It encrypts all internet traffic.", "It deletes viruses."], a: "It provides a historical record of all traffic, allowing security teams to see exactly what data was exfiltrated during a breach even months later.", e: "Without NetFlow, you have no visibility into past network anomalies." },
    { q: "What does the 'Syslog' protocol do?", o: ["It installs software updates.", "It centralizes system logs and error messages from hundreds of routers into a single, searchable server.", "It assigns IP addresses.", "It routes internet traffic."], a: "It centralizes system logs and error messages from hundreds of routers into a single, searchable server.", e: "Without a centralized Syslog server, admins would have to manually log into 500 routers to check their individual logs." },
    { q: "In Syslog, severity level 0 is 'Emergency'. What is severity level 7?", o: ["Critical", "Warning", "Informational", "Debugging"], a: "Debugging", e: "Level 7 (Debugging) produces massive amounts of highly detailed output, usually only turned on briefly to fix a specific problem." },
    { q: "What is an 'NTP' (Network Time Protocol) server used for?", o: ["To speed up the network.", "To ensure every router, switch, and server has the exact same synchronized clock time down to the millisecond.", "To schedule router reboots.", "To measure bandwidth."], a: "To ensure every router, switch, and server has the exact same synchronized clock time down to the millisecond.", e: "If clocks are out of sync, Syslog timestamps are useless, and cryptographic certificates will fail to validate." },
    { q: "Which tool takes Syslog, NetFlow, and SNMP data, correlates it all together using AI, and alerts the security team of an ongoing attack?", o: ["A basic Firewall.", "A SIEM (Security Information and Event Management) system.", "A VPN.", "A Load Balancer."], a: "A SIEM (Security Information and Event Management) system.", e: "SIEMs (like Splunk or QRadar) are the brain of the Security Operations Center (SOC)." },
    { q: "What is the function of 'Port Mirroring' (SPAN) on a network switch?", o: ["To reflect physical light in fiber cables.", "To copy all traffic passing through a specific switch port and send it to an IDS or packet sniffer (like Wireshark) for deep analysis.", "To block all traffic.", "To increase the port speed."], a: "To copy all traffic passing through a specific switch port and send it to an IDS or packet sniffer (like Wireshark) for deep analysis.", e: "SPAN allows an analyzer to inspect traffic silently without interrupting the actual flow." },
    { q: "Why might a network administrator prefer using an 'Out-of-Band' (OOB) management connection instead of SSH over the production network?", o: ["Because OOB is cheaper.", "Because if the production network crashes or is severely congested, OOB provides a dedicated backdoor to fix the routers.", "Because SSH is illegal.", "Because OOB uses Wi-Fi."], a: "Because if the production network crashes or is severely congested, OOB provides a dedicated backdoor to fix the routers.", e: "In-Band management fails when the network fails. OOB ensures you always have control." },
    { q: "What does 'Configuration Management' software (like SolarWinds NCM) do?", o: ["It builds the physical servers.", "It automatically backs up router configurations nightly and alerts admins if someone makes an unauthorized CLI change.", "It encrypts the hard drives.", "It writes the company security policy."], a: "It automatically backs up router configurations nightly and alerts admins if someone makes an unauthorized CLI change.", e: "Tracking configuration drift is critical for stability and security." },
    { q: "Which layer of the OSI model does SNMP operate at?", o: ["Layer 1 (Physical)", "Layer 3 (Network)", "Layer 4 (Transport)", "Layer 7 (Application)"], a: "Layer 7 (Application)", e: "SNMP is an application-level protocol that uses UDP port 161/162 for transport." },
    { q: "What is the purpose of an 'SLA' (Service Level Agreement) with an ISP?", o: ["A contract defining the speed of the computers.", "A legally binding contract that guarantees specific network performance metrics (like 99.9% uptime, maximum latency) and outlines financial penalties if the ISP fails.", "A contract to buy new routers.", "A software license."], a: "A legally binding contract that guarantees specific network performance metrics (like 99.9% uptime, maximum latency) and outlines financial penalties if the ISP fails.", e: "SLAs hold the telecom providers accountable for the expensive leased lines." },
    { q: "How does a network monitoring system test 'Availability'?", o: ["By downloading a massive file.", "By sending constant ICMP Echo Requests (Pings) to a device and waiting for a reply.", "By checking the router's temperature.", "By turning the router off and on."], a: "By sending constant ICMP Echo Requests (Pings) to a device and waiting for a reply.", e: "Ping is the universal heartbeat monitor for UP/DOWN status." },
    { q: "In NetFlow, what defines a 'Flow'?", o: ["The physical cable type.", "A unidirectional sequence of packets sharing the same Source/Destination IP, Ports, and Protocol.", "The speed of the router.", "The cost of the bandwidth."], a: "A unidirectional sequence of packets sharing the same Source/Destination IP, Ports, and Protocol.", e: "A flow represents a single specific conversation between two applications." },
    { q: "What is 'SNMP Polling Interval'?", o: ["The distance between routers.", "How frequently the Manager asks the Agent for updates (e.g., every 5 minutes).", "The time it takes to boot the router.", "The password for SNMP."], a: "How frequently the Manager asks the Agent for updates (e.g., every 5 minutes).", e: "Polling too fast crashes the router CPU; polling too slow misses critical events." },

    // --- CLI Configuration & Implementation Basics (20 Qns) ---
    { q: "When you first unpack a brand new enterprise router, how do you initially connect to it to configure it?", o: ["Via Wi-Fi.", "Using a 'Console Cable' connected physically from your laptop's serial/USB port to the router's Console port.", "By pinging its IP address.", "By opening a web browser."], a: "Using a 'Console Cable' connected physically from your laptop's serial/USB port to the router's Console port.", e: "A new router has no IP address or SSH configured, so you must use a direct, out-of-band serial connection." },
    { q: "In Cisco IOS, what is the difference between 'User EXEC Mode' (Router>) and 'Privileged EXEC Mode' (Router#)?", o: ["There is no difference.", "User mode is only for basic viewing (like ping); Privileged mode allows viewing all configs, rebooting the device, and entering configuration mode.", "User mode allows deleting the OS.", "Privileged mode is only for wireless users."], a: "User mode is only for basic viewing (like ping); Privileged mode allows viewing all configs, rebooting the device, and entering configuration mode.", e: "Privileged EXEC (enabled by the 'enable' command) is the equivalent of 'root' or 'Administrator'." },
    { q: "Which command moves you into the mode where you can actually change the router's settings (Global Configuration Mode)?", o: ["show running-config", "configure terminal", "ping", "exit"], a: "configure terminal", e: "The 'conf t' command changes the prompt to Router(config)#, unlocking all configuration commands." },
    { q: "What does the command 'show running-config' display?", o: ["The configurations that will load the next time the router reboots.", "The current, active configuration stored in the router's volatile RAM.", "The list of users online.", "The routing table."], a: "The current, active configuration stored in the router's volatile RAM.", e: "The running-config is live. If you lose power without saving, all changes here are lost." },
    { q: "How do you permanently save the active configuration so it survives a power outage?", o: ["copy running-config startup-config", "save now", "store memory", "exit"], a: "copy running-config startup-config", e: "This copies the RAM config to NVRAM (Non-Volatile RAM) which survives reboots." },
    { q: "What is the purpose of the 'shutdown' command on a router interface?", o: ["It restarts the whole router.", "It administratively disables (turns off) the specific physical port.", "It deletes the routing table.", "It uninstalls the OS."], a: "It administratively disables (turns off) the specific physical port.", e: "Interfaces are often 'shutdown' by default for security until an admin explicitly types 'no shutdown'." },
    { q: "Which configuration step is absolutely essential before a router interface will forward IP packets?", o: ["Installing an antivirus.", "Assigning a valid IP address and Subnet Mask to the interface, and ensuring it is 'no shutdown'.", "Configuring BGP.", "Changing the hostname."], a: "Assigning a valid IP address and Subnet Mask to the interface, and ensuring it is 'no shutdown'.", e: "Without an IP address, the port is dead to Layer 3 traffic." },
    { q: "Why should a network administrator configure SSH (Secure Shell) instead of Telnet for remote CLI access?", o: ["SSH is faster.", "Telnet sends all passwords and data in clear-text; SSH encrypts the entire session, preventing eavesdropping.", "Telnet cannot use IPv4.", "SSH is free."], a: "Telnet sends all passwords and data in clear-text; SSH encrypts the entire session, preventing eavesdropping.", e: "Telnet is universally banned in modern enterprise networks due to the extreme security risk." },
    { q: "What does the 'hostname' command do?", o: ["It creates a website.", "It changes the name of the router in the CLI prompt, which is critical for identifying the device in Syslog and SNMP.", "It changes the IP address.", "It assigns a MAC address."], a: "It changes the name of the router in the CLI prompt, which is critical for identifying the device in Syslog and SNMP.", e: "Leaving all 500 routers named 'Router' makes troubleshooting impossible." },
    { q: "When implementing a new network, what is a 'Pilot' or 'Phased' deployment?", o: ["Replacing all routers in one night.", "Rolling out the new network to a small, non-critical department first to find bugs before upgrading the entire company.", "Testing the network in a virtual simulator only.", "Not upgrading at all."], a: "Rolling out the new network to a small, non-critical department first to find bugs before upgrading the entire company.", e: "A Phased approach limits the 'blast radius' if the new design has unforeseen flaws." },
    { q: "What is a 'Cut-over' or 'Flash Cut' deployment?", o: ["A slow migration over 6 months.", "A high-risk strategy where the old network is shut down and the entire new network is turned on simultaneously, usually over a weekend.", "A deployment using optical fiber.", "A deployment with no downtime."], a: "A high-risk strategy where the old network is shut down and the entire new network is turned on simultaneously, usually over a weekend.", e: "A Flash Cut is risky but sometimes necessary when old and new systems cannot coexist." },
    { q: "What must be heavily utilized during a 'Cut-over' to ensure success?", o: ["A detailed Implementation Plan and a tested Rollback Plan.", "A large hammer.", "Static Routing.", "Telnet."], a: "A detailed Implementation Plan and a tested Rollback Plan.", e: "If the cut-over fails at 3 AM Sunday, the Rollback plan ensures the business opens safely on Monday." },
    { q: "Why is 'Device Hardening' a critical implementation step before placing a router into production?", o: ["To make the physical casing stronger.", "To disable unused ports, set strong encrypted passwords, disable clear-text protocols (like HTTP/Telnet), and restrict management IPs.", "To speed up routing.", "To increase the power supply limit."], a: "To disable unused ports, set strong encrypted passwords, disable clear-text protocols (like HTTP/Telnet), and restrict management IPs.", e: "Hardening reduces the attack surface of the infrastructure." },
    { q: "Which command would you use to view the OSPF neighbor relationships on a Cisco router?", o: ["show ip interface brief", "show ip ospf neighbor", "show running-config", "ping"], a: "show ip ospf neighbor", e: "This command immediately verifies if the router has successfully formed adjacencies with its peers." },
    { q: "What does the command 'show ip route' output?", o: ["The physical MAC addresses.", "The router's entire routing table, showing every known network and how to reach it.", "The firewall rules.", "The current time."], a: "The router's entire routing table, showing every known network and how to reach it.", e: "The routing table is the absolute source of truth for where a router will send a packet." },
    { q: "If you configure an Access Control List (ACL) but forget to apply it to an interface, what happens?", o: ["The router drops all traffic.", "Nothing happens. The ACL is just a useless list until it is explicitly applied inbound or outbound on a specific port.", "The router crashes.", "The ACL automatically applies to all ports."], a: "Nothing happens. The ACL is just a useless list until it is explicitly applied inbound or outbound on a specific port.", e: "Creating a rule does nothing; you must enforce it." },
    { q: "What is the 'Implicit Deny' at the end of every ACL?", o: ["A rule that drops all traffic specifically permitted.", "An invisible rule at the very bottom that says 'If the packet didn't match any of the lines above, drop it'.", "A rule that allows all traffic.", "A logging mechanism."], a: "An invisible rule at the very bottom that says 'If the packet didn't match any of the lines above, drop it'.", e: "Because of the implicit deny, if you create an ACL with only 'deny' statements, it will block 100% of all traffic." },
    { q: "In standard ACLs, what does the rule 'permit any' do?", o: ["It blocks all traffic.", "It allows all IP traffic that hasn't been explicitly denied by previous lines to pass.", "It allows physical access to the server room.", "It gives the user administrator rights."], a: "It allows all IP traffic that hasn't been explicitly denied by previous lines to pass.", e: "You must put 'permit any' at the bottom of an ACL if you don't want the implicit deny to block the rest of the legitimate traffic." },
    { q: "When implementing VLANs, which command turns a switch port into a trunk link to carry multiple VLANs?", o: ["switchport mode access", "switchport mode trunk", "ip address", "shutdown"], a: "switchport mode trunk", e: "Trunk mode enables 802.1q tagging so the port can carry traffic for VLAN 10, 20, 30, etc." },
    { q: "What is the purpose of the 'description' command on an interface?", o: ["It encrypts the interface.", "It allows the admin to write a human-readable note (e.g., 'Link to Core Switch 1') to make future troubleshooting vastly easier.", "It changes the IP address.", "It increases bandwidth."], a: "It allows the admin to write a human-readable note (e.g., 'Link to Core Switch 1') to make future troubleshooting vastly easier.", e: "Documentation inside the CLI is just as important as Visio diagrams." },

    // --- Troubleshooting Methodology & Tools (20 Qns) ---
    { q: "What is the first step in any structured Troubleshooting Methodology?", o: ["Reboot the server.", "Define the specific problem by gathering information and asking the user clear questions.", "Replace the router.", "Format the hard drive."], a: "Define the specific problem by gathering information and asking the user clear questions.", e: "You cannot fix a problem if you don't fully understand what is broken." },
    { q: "Which troubleshooting approach starts at the Application Layer (Layer 7) and works its way down to the Physical Layer (Layer 1)?", o: ["Bottom-Up", "Divide-and-Conquer", "Top-Down", "Random Guessing"], a: "Top-Down", e: "Top-Down starts by asking 'Does the web browser work?' and works down to 'Is the cable plugged in?'." },
    { q: "Why is the 'Bottom-Up' troubleshooting approach so common?", o: ["Because software never breaks.", "Because the vast majority of network problems (like unplugged cables or dead ports) occur at Layer 1 or Layer 2.", "Because it takes the longest.", "Because it requires no knowledge."], a: "Because the vast majority of network problems (like unplugged cables or dead ports) occur at Layer 1 or Layer 2.", e: "Checking the physical link light is always the fastest first step." },
    { q: "If you can ping 8.8.8.8 but you CANNOT ping www.google.com, which layer is broken?", o: ["Layer 1 (Physical Cable)", "Layer 3 (IP Routing)", "Layer 7 (Application - DNS)", "Layer 2 (VLANs)"], a: "Layer 7 (Application - DNS)", e: "Since you can reach an external IP, your routing is perfect. The failure is strictly DNS name resolution." },
    { q: "What does the 'ping' command actually do?", o: ["It encrypts data.", "It sends an ICMP Echo Request to a target IP and waits for an ICMP Echo Reply, measuring the time it took.", "It shows the MAC address.", "It reboots the target computer."], a: "It sends an ICMP Echo Request to a target IP and waits for an ICMP Echo Reply, measuring the time it took.", e: "Ping verifies basic end-to-end Layer 3 IP connectivity." },
    { q: "A user reports 'The internet is down'. You ping their Default Gateway and it succeeds. What does this prove?", o: ["The ISP is definitely down.", "The user's physical cable, switch port, VLAN, and Layer 3 connection to the local router are all functioning perfectly.", "The user has a virus.", "The router is broken."], a: "The user's physical cable, switch port, VLAN, and Layer 3 connection to the local router are all functioning perfectly.", e: "A successful local ping instantly eliminates all Layer 1 and 2 issues on the local LAN." },
    { q: "What is the primary function of the 'traceroute' (or tracert) command?", o: ["To delete files.", "To map out the exact sequence of routers (hops) a packet takes to reach a destination, showing exactly where a connection drops.", "To assign an IP address.", "To test DNS."], a: "To map out the exact sequence of routers (hops) a packet takes to reach a destination, showing exactly where a connection drops.", e: "Traceroute is invaluable for proving that a packet left your network but died at the ISP." },
    { q: "How does 'traceroute' mathematically force routers to reply?", o: ["By sending money.", "By sending packets with an intentionally low TTL (Time to Live) starting at 1, forcing each router in the path to drop the packet and send back an ICMP 'Time Exceeded' error.", "By using BGP.", "By encrypting the ping."], a: "By sending packets with an intentionally low TTL (Time to Live) starting at 1, forcing each router in the path to drop the packet and send back an ICMP 'Time Exceeded' error.", e: "Traceroute manipulates the TTL mechanism to map the topology." },
    { q: "Which command shows the Layer 2 to Layer 3 mapping (MAC address to IP address) on a Windows PC?", o: ["ipconfig", "netstat", "arp -a", "tracert"], a: "arp -a", e: "The ARP cache holds the critical mapping between local IP addresses and their physical MAC addresses." },
    { q: "What does 'ipconfig /all' (or ifconfig) display?", o: ["Only the IP address.", "The full IP address, Subnet Mask, Default Gateway, DNS Servers, and the physical MAC address of the device.", "The routing table.", "The internet speed."], a: "The full IP address, Subnet Mask, Default Gateway, DNS Servers, and the physical MAC address of the device.", e: "It is the foundational command for verifying a PC's local network configuration." },
    { q: "Scenario: Two PCs are plugged into the exact same switch. PC-A is 192.168.1.10/24. PC-B is 192.168.2.10/24. They cannot ping each other. Why?", o: ["The switch is broken.", "They are in different logical subnets (/24), meaning they require a Layer 3 Router to communicate, even if they are on the same physical switch.", "The cables are bad.", "Ping is disabled."], a: "They are in different logical subnets (/24), meaning they require a Layer 3 Router to communicate, even if they are on the same physical switch.", e: "Layer 2 switches cannot move packets between different IP subnets without a router." },
    { q: "In troubleshooting, what does 'Duplex Mismatch' cause?", o: ["A power failure.", "Massive packet collisions and painfully slow speeds because one side is talking Full-Duplex (simultaneous) while the other expects Half-Duplex (one at a time).", "IP address conflicts.", "A broadcast storm."], a: "Massive packet collisions and painfully slow speeds because one side is talking Full-Duplex (simultaneous) while the other expects Half-Duplex (one at a time).", e: "Duplex mismatches are a classic Layer 1/2 performance killer." },
    { q: "What is an 'IP Address Conflict'?", o: ["When two routers argue about routes.", "When two different physical devices on the exact same network are accidentally assigned the exact same IP address, causing intermittent connectivity drops for both.", "When an IP address is too long.", "When IPv4 talks to IPv6."], a: "When two different physical devices on the exact same network are accidentally assigned the exact same IP address, causing intermittent connectivity drops for both.", e: "IP conflicts destroy the ARP tables, making switches hopelessly confused about where to send traffic." },
    { q: "How do you permanently prevent 'IP Address Conflicts' in a large enterprise?", o: ["Assign them all manually.", "Use a properly configured, centralized DHCP Server with a strict scope, and never manually assign IPs to end-user PCs.", "Turn off the network.", "Use IPv4 only."], a: "Use a properly configured, centralized DHCP Server with a strict scope, and never manually assign IPs to end-user PCs.", e: "DHCP ensures flawless, conflict-free IP distribution." },
    { q: "What does a 'Cable Tester' physically verify?", o: ["BGP routes.", "Continuity, ensuring that all 8 copper wires inside the CAT6 cable are unbroken and properly pinned.", "The IP address.", "The speed of light."], a: "Continuity, ensuring that all 8 copper wires inside the CAT6 cable are unbroken and properly pinned.", e: "A cable tester is the ultimate Layer 1 diagnostic tool." },
    { q: "What is the function of a 'TDR' (Time Domain Reflectometer)?", o: ["It creates routing loops.", "It shoots an electrical pulse down a cable and measures the reflection to tell you exactly how many meters down the cable the physical break is.", "It changes the time zone.", "It encrypts the cable."], a: "It shoots an electrical pulse down a cable and measures the reflection to tell you exactly how many meters down the cable the physical break is.", e: "TDRs are incredibly expensive, magical tools for finding cut cables inside walls." },
    { q: "If an OSPF router is stuck in the 'INIT' or '2-WAY' state and won't form a full adjacency, what is a very common cause?", o: ["The power is out.", "Mismatched MTU (Maximum Transmission Unit) sizes or mismatched OSPF Hello Timers between the two routers.", "They are using IPv6.", "The cables are too long."], a: "Mismatched MTU (Maximum Transmission Unit) sizes or mismatched OSPF Hello Timers between the two routers.", e: "OSPF requires extremely strict agreement on timers and packet sizes before it trusts a neighbor." },
    { q: "What is the purpose of 'Wireshark' (Packet Sniffer)?", o: ["To speed up downloads.", "To capture raw packets flying across the network wire and decode them into human-readable text for extreme deep-dive Layer 2-7 troubleshooting.", "To assign IP addresses.", "To format hard drives."], a: "To capture raw packets flying across the network wire and decode them into human-readable text for extreme deep-dive Layer 2-7 troubleshooting.", e: "Wireshark allows you to see the exact binary conversations, proving exactly which device is failing." },
    { q: "During troubleshooting, why is it critical to 'Document the Solution'?", o: ["To waste time.", "So that if the exact same bizarre problem happens 6 months later to a different engineer, they don't have to spend 5 hours reinventing the wheel to fix it.", "To make the router faster.", "To encrypt the logs."], a: "So that if the exact same bizarre problem happens 6 months later to a different engineer, they don't have to spend 5 hours reinventing the wheel to fix it.", e: "A knowledge base is the most valuable asset an IT department has." },
    { q: "Scenario: A server can ping 10.1.1.1 but not 10.1.1.2. Another server on the same switch can ping both. What is likely wrong with the first server?", o: ["The switch is dead.", "The first server has an incorrect Subnet Mask configured, causing it to miscalculate which IPs are local.", "The router is on fire.", "The internet is down."], a: "The first server has an incorrect Subnet Mask configured, causing it to miscalculate which IPs are local.", e: "A bad subnet mask will cause a host to send local traffic to the gateway, or gateway traffic nowhere." }
];

async function run() {
    const categories = ["QUIZ", "EXERCISE", "CAT 1", "CAT 2", "POSSIBLE QNS", "UE"];
    const client = new MongoClient(uri);
    try {
        await client.connect();
        const db = client.db('school_db');
        const collection = db.collection('questions');
        
        let inserted = 0;
        let duplicates = 0;
        for (const q of questions) {
            const doc = {
                subjectId, moduleName, type: "MULTIPLE_CHOICE",
                category: categories[Math.floor(Math.random() * categories.length)],
                difficultyLevel: ["EASY", "MEDIUM", "HARD"][Math.floor(Math.random() * 3)],
                createdAt: new Date(),
                questionText: q.q,
                options: q.o.sort(() => Math.random() - 0.5),
                correctAnswer: q.a,
                explanation: q.e
            };
            const exists = await collection.findOne({ subjectId: doc.subjectId, questionText: doc.questionText });
            if (!exists) {
                await collection.insertOne(doc);
                inserted++;
            } else {
                duplicates++;
            }
        }
        console.log(`Successfully inserted ${inserted} highly distinct handcrafted questions for Unit 5 (Batch 1 of Phase 5)!`);
    } catch (e) {
        console.error("Error inserting questions:", e);
    } finally {
        await client.close();
    }
}
run();
