const { MongoClient } = require('mongodb');
const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de'; // COURSE FOR DESIGN PROFESSIONAL

const questions = [];
const moduleName = "Unit 1: Network Design Fundamentals";

// Helper to add question
function addQ(qText, options, correct, explanation, diff = "MEDIUM", cat = "QUIZ") {
    questions.push({
        subjectId, moduleName, category: cat, type: "MULTIPLE_CHOICE",
        questionText: qText, options, correctAnswer: correct, explanation, difficultyLevel: diff
    });
}

// 1. Network Design Methodology (20 questions)
addQ("What is the primary purpose of a Network Design Methodology?", ["To build networks ad hoc", "To ensure scalability, reliability, security, and cost-effectiveness", "To focus solely on purchasing hardware", "To bypass technical requirements"], "To ensure scalability, reliability, security, and cost-effectiveness", "Network Design Methodology is a structured approach that ensures scalability, reliability, security, and cost-effectiveness.", "EASY", "EXERCISE");
addQ("Which phase of network design methodology involves identifying business goals and technical needs?", ["Logical Network Design", "Requirements Analysis", "Physical Network Design", "Implementation"], "Requirements Analysis", "Requirements Analysis is the foundation where business goals and technical needs are identified.", "EASY", "QUIZ");
addQ("What is considered a business goal during the Requirements Analysis phase?", ["Routing protocols", "Budget and growth", "IP addressing scheme", "Hardware selection"], "Budget and growth", "Business goals include factors like growth, services, and budget constraints.", "MEDIUM", "POSSIBLE");
addQ("Which of the following belongs to the Logical Network Design phase?", ["Selecting physical cables", "Rack layout", "IP addressing scheme", "Installing devices"], "IP addressing scheme", "Logical design focuses on topology, IP addressing, routing protocols, and segmentation.", "MEDIUM", "CAT 1");
addQ("Designing the network topology (star, mesh, hybrid) is part of which methodology step?", ["Physical Network Design", "Requirements Analysis", "Logical Network Design", "Testing and Validation"], "Logical Network Design", "Topology selection (what the network should do conceptually) is part of the Logical Network Design.", "EASY", "EXERCISE");
addQ("Which phase involves hardware selection such as routers, switches, and cables?", ["Requirements Analysis", "Logical Network Design", "Physical Network Design", "Monitoring and Optimization"], "Physical Network Design", "Physical Network Design defines how to implement the logical design, including hardware selection.", "EASY", "QUIZ");
addQ("Defining the data center or site layout falls under which network design phase?", ["Logical Network Design", "Physical Network Design", "Implementation", "Documentation"], "Physical Network Design", "Data center or site layout is a key part of the Physical Network Design.", "MEDIUM", "CAT 2");
addQ("What is a primary task during the Implementation (Deployment) phase?", ["Identifying user constraints", "Selecting routing protocols", "Installing and configuring devices", "Upgrading hardware"], "Installing and configuring devices", "Implementation involves installing devices, configuring them, and applying IP addressing.", "EASY", "EXERCISE");
addQ("Which step in the design methodology includes setting up security policies?", ["Testing and Validation", "Implementation (Deployment)", "Requirements Analysis", "Monitoring"], "Implementation (Deployment)", "Applying IP addressing, routing, and setting up security policies happens during deployment.", "MEDIUM", "POSSIBLE");
addQ("What type of testing checks the throughput and latency of the deployed network?", ["Security testing", "Connectivity testing", "Performance testing", "Failover testing"], "Performance testing", "Performance testing specifically tracks throughput and latency metrics.", "EASY", "QUIZ");
addQ("Using Ping and Traceroute is part of which type of testing?", ["Performance testing", "Security testing", "Failover testing", "Connectivity testing"], "Connectivity testing", "Connectivity testing uses tools like ping and traceroute to ensure nodes can communicate.", "EASY", "CAT 1");
addQ("Penetration testing is typically conducted during which design methodology step?", ["Testing and Validation", "Monitoring and Optimization", "Documentation", "Maintenance"], "Testing and Validation", "Security testing, such as penetration testing, is part of Testing and Validation.", "MEDIUM", "EXERCISE");
addQ("Which tools are typically used during the Monitoring and Optimization phase?", ["Ping and Traceroute", "SNMP and NetFlow", "CAD and Visio", "Screwdrivers and crimpers"], "SNMP and NetFlow", "Monitoring and Optimization utilize tools like SNMP and NetFlow to track performance.", "HARD", "QUIZ");
addQ("Identifying network bottlenecks is a primary activity of which phase?", ["Requirements Analysis", "Implementation", "Monitoring and Optimization", "Documentation"], "Monitoring and Optimization", "Monitoring tools track performance and usage to identify and optimize bottlenecks.", "MEDIUM", "POSSIBLE");
addQ("IP addressing tables and device configurations are outputs of which phase?", ["Maintenance", "Documentation", "Physical Design", "Testing"], "Documentation", "Documentation includes diagrams, configurations, IP tables, and policies.", "EASY", "CAT 2");
addQ("What is a key activity in the Maintenance and Scaling phase?", ["Applying patches and security updates", "Designing the initial logical topology", "Defining initial business goals", "Selecting the first core router"], "Applying patches and security updates", "Maintenance involves upgrading hardware, expanding capacity, and applying security updates.", "MEDIUM", "EXERCISE");
addQ("Which step ensures the network adapts to an organization's growth over time?", ["Requirements Analysis", "Maintenance and Scaling", "Logical Network Design", "Connectivity Testing"], "Maintenance and Scaling", "Maintenance and Scaling handles capacity expansion and upgrades as the network grows.", "MEDIUM", "QUIZ");
addQ("Why is a structured Network Design Methodology preferred over building networks ad hoc?", ["It is faster to deploy", "It completely eliminates the need for routers", "It ensures scalability, reliability, and security", "It avoids documentation completely"], "It ensures scalability, reliability, and security", "A structured approach ensures that the resulting network meets business and technical needs effectively.", "EASY", "POSSIBLE");
addQ("Which of the following is considered a 'constraint' during Requirements Analysis?", ["Routing protocol choice", "Time and existing infrastructure", "Ping latency", "Rack layout"], "Time and existing infrastructure", "Constraints include cost, time, and the limitations of existing infrastructure.", "HARD", "CAT 1");
addQ("Network segmentation using VLANs is decided during which phase?", ["Physical Network Design", "Logical Network Design", "Testing and Validation", "Monitoring"], "Logical Network Design", "VLANs and subnets are logical segmentations planned during the Logical Network Design phase.", "MEDIUM", "EXERCISE");

// 2. Hierarchical Network Model (30 questions)
addQ("The Hierarchical Network Model divides the network into layers to achieve what primary goal?", ["To increase physical cable length", "To improve performance and simplify management", "To eliminate the need for switches", "To bypass security policies"], "To improve performance and simplify management", "The layered approach improves performance, simplifies management, and increases scalability.", "EASY", "QUIZ");
addQ("How many primary layers does the standard Hierarchical Network Model have?", ["Two", "Three", "Four", "Five"], "Three", "The most common hierarchical model has three layers: Core, Distribution, and Access.", "EASY", "POSSIBLE");
addQ("Which layer is the lowest layer of the Hierarchical Network Model?", ["Core Layer", "Distribution Layer", "Access Layer", "Transport Layer"], "Access Layer", "The Access Layer is the lowest layer where end devices connect.", "EASY", "CAT 2");
addQ("At which layer do PCs, printers, and IP phones directly connect to the network?", ["Core Layer", "Distribution Layer", "Access Layer", "Internet Layer"], "Access Layer", "The Access Layer provides network access directly to end users and their devices.", "EASY", "EXERCISE");
addQ("Which of the following is a primary function of the Access Layer?", ["High-speed data transport", "Routing between VLANs", "Controls user access and supports port security", "Server load balancing"], "Controls user access and supports port security", "The Access layer connects end devices and implements initial port security and VLAN assignment.", "MEDIUM", "QUIZ");
addQ("What devices are primarily used at the Access Layer?", ["High-performance routers", "Access switches and Wireless Access Points", "Core switches", "Firewalls"], "Access switches and Wireless Access Points", "Access switches and WAPs are used to connect end devices at the Access Layer.", "EASY", "POSSIBLE");
addQ("Which layer acts as the middle layer, connecting the access layer to the core layer?", ["Data Link Layer", "Access Layer", "Distribution Layer", "Core Layer"], "Distribution Layer", "The Distribution Layer sits between the Access and Core layers.", "EASY", "CAT 1");
addQ("Which hierarchical layer is responsible for routing between VLANs?", ["Access Layer", "Distribution Layer", "Core Layer", "Physical Layer"], "Distribution Layer", "The Distribution Layer handles inter-VLAN routing, traffic filtering, and policy enforcement.", "MEDIUM", "EXERCISE");
addQ("Where is policy enforcement and traffic filtering typically implemented in the hierarchical model?", ["Core Layer", "Distribution Layer", "Access Layer", "Perimeter Layer"], "Distribution Layer", "Policy enforcement and traffic filtering are key functions of the Distribution Layer.", "HARD", "QUIZ");
addQ("Layer 3 switches and routers are most prominently featured in which intermediate layer?", ["Access Layer", "Distribution Layer", "Core Layer", "Application Layer"], "Distribution Layer", "The Distribution Layer heavily utilizes Layer 3 switches and routers for policy and routing.", "MEDIUM", "POSSIBLE");
addQ("Which layer is considered the 'backbone' of the network?", ["Access Layer", "Distribution Layer", "Core Layer", "Network Layer"], "Core Layer", "The Core Layer is the backbone, providing high-speed transport between distribution layers.", "EASY", "CAT 2");
addQ("What is the primary function of the Core Layer?", ["Port security for end devices", "High-speed data transfer and fast routing", "Connecting printers and IP phones", "Applying complex Access Control Lists (ACLs)"], "High-speed data transfer and fast routing", "The Core Layer focuses on fast, reliable, high-speed switching and routing.", "MEDIUM", "EXERCISE");
addQ("Which layer demands the highest redundancy and fault tolerance in the network?", ["Access Layer", "Distribution Layer", "Core Layer", "User Layer"], "Core Layer", "Because the Core Layer is the backbone, it requires maximum redundancy and fault tolerance.", "MEDIUM", "QUIZ");
addQ("In a university network, what role does the main data center network connecting all buildings play?", ["Access Layer", "Distribution Layer", "Core Layer", "Wireless Layer"], "Core Layer", "The central network connecting multiple buildings or departments acts as the Core Layer.", "MEDIUM", "POSSIBLE");
addQ("Which of the following is NOT an advantage of the Hierarchical Network Model?", ["Scalability", "Fault Isolation", "Complex Design", "Better Performance"], "Complex Design", "Complex Design is a disadvantage, whereas scalability, fault isolation, and performance are advantages.", "EASY", "CAT 1");
addQ("How does the hierarchical model aid in 'Fault Isolation'?", ["By combining all devices into one flat network", "By allowing problems to be identified quickly within specific layers", "By eliminating the need for routers", "By removing security protocols"], "By allowing problems to be identified quickly within specific layers", "The layered structure makes it easier to isolate and troubleshoot problems.", "MEDIUM", "EXERCISE");
addQ("Which layer is primarily responsible for keeping broadcast traffic from crossing over into other departments?", ["Access Layer", "Distribution Layer", "Core Layer", "Internet Layer"], "Distribution Layer", "The Distribution Layer routes between VLANs and stops broadcast domains from expanding to the core.", "HARD", "QUIZ");
addQ("What is a known disadvantage of implementing the Hierarchical Network Model?", ["It decreases network performance", "It has a high initial cost due to multiple networking devices", "It makes adding new users impossible", "It eliminates redundancy"], "It has a high initial cost due to multiple networking devices", "Proper hierarchical design requires specialized hardware for each layer, increasing initial costs.", "MEDIUM", "POSSIBLE");
addQ("Why is a failure in the Core Layer considered highly critical?", ["Because it only affects one PC", "Because it may affect the entire network's communication", "Because it controls the wireless access points", "Because it manages port security"], "Because it may affect the entire network's communication", "The core connects all distribution layers; its failure can bring down the entire network.", "EASY", "CAT 2");
addQ("What does 'Scalability' mean in the context of the hierarchical model?", ["The network cannot grow", "New devices and departments can be added easily without redesigning the whole network", "Security policies are harder to implement", "The core layer is removed"], "New devices and departments can be added easily without redesigning the whole network", "Scalability allows seamless expansion by just adding access/distribution modules.", "EASY", "EXERCISE");
// Expanding Hierarchical model to reach 30
addQ("If you need to implement Load Balancing between different building networks, which layer manages this?", ["Access Layer", "Distribution Layer", "Core Layer", "End-user Layer"], "Distribution Layer", "Load balancing between access switches and the core is handled by the distribution layer.", "HARD", "QUIZ");
addQ("Which layer would typically connect a staff room's desktop computers?", ["Core Layer", "Distribution Layer", "Access Layer", "Backbone Layer"], "Access Layer", "End-user devices connect at the Access Layer.", "EASY", "POSSIBLE");
addQ("High-performance routers that do minimal filtering to ensure maximum speed are placed in the:", ["Access Layer", "Distribution Layer", "Core Layer", "Security Layer"], "Core Layer", "Core devices avoid complex filtering to maximize switching speed.", "MEDIUM", "CAT 1");
addQ("A switch that provides Power over Ethernet (PoE) to IP cameras is most likely located in the:", ["Core Layer", "Distribution Layer", "Access Layer", "Cloud Layer"], "Access Layer", "Access switches connect and often power end devices like IP cameras.", "MEDIUM", "EXERCISE");
addQ("Which characteristic best describes the Core layer?", ["High policy enforcement", "End-user connectivity", "High-speed switching without deep packet inspection", "Inter-VLAN routing for local departments"], "High-speed switching without deep packet inspection", "The core is optimized for speed, leaving policy enforcement to the distribution layer.", "HARD", "QUIZ");
addQ("Which layer acts as an aggregation point for multiple access switches?", ["Access Layer", "Distribution Layer", "Core Layer", "Data Link Layer"], "Distribution Layer", "The Distribution Layer aggregates uplinks from multiple Access Layer switches.", "MEDIUM", "POSSIBLE");
addQ("Implementing the hierarchical model simplifies management because:", ["There is only one router to manage", "Each layer has separate, clearly defined responsibilities", "It uses only one type of cable", "It does not require IP addresses"], "Each layer has separate, clearly defined responsibilities", "Layered responsibilities make configuring and managing devices predictable and straightforward.", "EASY", "CAT 2");
addQ("The hierarchical model improves security primarily because:", ["Security policies can be applied effectively at the distribution layer", "The core layer encrypts all traffic", "Access layer switches don't use electricity", "Hackers do not understand the model"], "Security policies can be applied effectively at the distribution layer", "Centralized policy enforcement at the distribution layer enhances overall security.", "MEDIUM", "EXERCISE");
addQ("What must be carefully planned to avoid the disadvantage of 'Dependency on Core Layer'?", ["Removing the access layer", "Core layer redundancy and fault tolerance", "Using cheaper core switches", "Connecting PCs directly to the core"], "Core layer redundancy and fault tolerance", "Because a core failure is catastrophic, redundancy is strictly required.", "HARD", "QUIZ");
addQ("In a small campus, the core and distribution layers are sometimes combined. This is known as a:", ["Collapsed Core architecture", "Flat network", "Single-layer model", "Expanded Access model"], "Collapsed Core architecture", "When core and distribution are combined into one layer, it's called a collapsed core.", "HARD", "POSSIBLE");

// 3. Design Objectives (30 questions)
addQ("What are Design Objectives in network design?", ["Software programs used to draw topologies", "Goals and requirements that guide the planning and implementation of a network", "The physical cables connecting devices", "The IP addresses assigned to routers"], "Goals and requirements that guide the planning and implementation of a network", "Design objectives ensure the network operates efficiently according to organizational needs.", "EASY", "CAT 1");
addQ("Which design objective ensures the network can support future growth without a major redesign?", ["Security", "Reliability", "Scalability", "Manageability"], "Scalability", "Scalability means the network easily supports new users, devices, and traffic.", "EASY", "EXERCISE");
addQ("A college network designed for 500 users later supporting 2000 users seamlessly is an example of:", ["Security", "Scalability", "Cost Efficiency", "Manageability"], "Scalability", "Expanding capacity without replacing infrastructure is the definition of scalability.", "MEDIUM", "QUIZ");
addQ("Which objective ensures the network works continuously with minimum downtime?", ["Performance", "Flexibility", "Reliability", "Scalability"], "Reliability", "Reliability implies minimal downtime and continuous operation.", "EASY", "POSSIBLE");
addQ("Features like backup links, redundant devices, and fault tolerance contribute to which design objective?", ["Reliability", "Cost Efficiency", "Flexibility", "Security"], "Reliability", "Redundancy and fault tolerance are key features of network reliability.", "MEDIUM", "CAT 2");
addQ("Which design objective refers to the speed, efficiency, and low latency of data transfer?", ["Manageability", "Availability", "Performance", "Security"], "Performance", "Performance is measured by latency, bandwidth, and fast data transfer.", "EASY", "EXERCISE");
addQ("Ensuring that video conferencing runs smoothly without delay is an example of meeting which objective?", ["Security", "Performance", "Availability", "Flexibility"], "Performance", "Smooth, delay-free video conferencing requires high performance (low latency/high bandwidth).", "MEDIUM", "QUIZ");
addQ("Protecting the network from unauthorized access and cyber threats is the definition of:", ["Security", "Reliability", "Scalability", "Manageability"], "Security", "Security utilizes firewalls, encryption, and ACLs to protect the network.", "EASY", "POSSIBLE");
addQ("Firewalls, Encryption, and Access Control Lists (ACLs) are features of which design objective?", ["Performance", "Security", "Flexibility", "Availability"], "Security", "These are standard tools used to implement network security.", "EASY", "CAT 1");
addQ("Which objective ensures the network is accessible whenever users need it, often demanding 24/7 connectivity?", ["Flexibility", "Manageability", "Availability", "Cost Efficiency"], "Availability", "Availability guarantees that the network is up and running when needed.", "EASY", "EXERCISE");
addQ("Banking networks requiring uninterrupted uptime for transactions emphasize which objective?", ["Availability", "Flexibility", "Manageability", "Scalability"], "Availability", "Critical transaction systems require extremely high availability (often 99.999% uptime).", "MEDIUM", "QUIZ");
addQ("Which objective means the network should be easy to monitor, maintain, and troubleshoot?", ["Manageability", "Performance", "Security", "Reliability"], "Manageability", "Manageability is achieved through centralized management and monitoring tools.", "EASY", "POSSIBLE");
addQ("Using centralized monitoring tools to track all switches and routers fulfills which objective?", ["Manageability", "Flexibility", "Security", "Scalability"], "Manageability", "Centralized tools make the network easier for administrators to manage.", "MEDIUM", "CAT 2");
addQ("Which objective describes a network's ability to adapt to new technologies, such as integrating wireless networking into a wired system?", ["Reliability", "Flexibility", "Cost Efficiency", "Performance"], "Flexibility", "Flexibility means the network can easily adopt new technologies and changes.", "MEDIUM", "EXERCISE");
addQ("Ensuring maximum network performance within the available budget is known as:", ["Cost Efficiency", "Scalability", "Manageability", "Reliability"], "Cost Efficiency", "Cost Efficiency balances high performance with budget constraints and low maintenance costs.", "EASY", "QUIZ");
addQ("Using VLANs to separate departments instead of purchasing separate physical switches is an example of:", ["Cost Efficiency", "Performance", "Availability", "Redundancy"], "Cost Efficiency", "VLANs maximize the utility of existing hardware, reducing capital expenditure.", "MEDIUM", "POSSIBLE");
addQ("If a network administrator installs redundant backup power systems (UPS), they are primarily enhancing:", ["Availability", "Cost Efficiency", "Scalability", "Manageability"], "Availability", "Backup power ensures the network remains available during a power outage.", "HARD", "CAT 1");
addQ("Low maintenance cost and energy-efficient devices contribute most directly to:", ["Cost Efficiency", "Security", "Performance", "Flexibility"], "Cost Efficiency", "Energy efficiency and low maintenance save money, improving cost efficiency.", "MEDIUM", "EXERCISE");
addQ("Which objective is most critical to prevent unauthorized staff from accessing the server room network?", ["Security", "Scalability", "Availability", "Performance"], "Security", "Access control is a fundamental aspect of network security.", "EASY", "QUIZ");
addQ("If a primary link fails and a backup link automatically takes over traffic, the network is demonstrating:", ["Reliability", "Flexibility", "Cost Efficiency", "Manageability"], "Reliability", "Automatic failover is a textbook example of network reliability and fault tolerance.", "MEDIUM", "POSSIBLE");
// Additional to hit 30
addQ("Which two objectives are often in direct conflict, requiring a careful balance?", ["Security and Cost Efficiency", "Scalability and Flexibility", "Availability and Reliability", "Manageability and Documentation"], "Security and Cost Efficiency", "Implementing high security often requires expensive equipment, challenging cost efficiency.", "HARD", "CAT 2");
addQ("Which feature is NOT typically associated with Performance?", ["Low latency", "High bandwidth", "Efficient traffic management", "24/7 backup power"], "24/7 backup power", "Backup power is a feature of Availability, not Performance.", "MEDIUM", "EXERCISE");
addQ("A network that easily integrates new IPv6 devices into an older IPv4 infrastructure demonstrates:", ["Flexibility", "Security", "Cost Efficiency", "Reliability"], "Flexibility", "Adapting to new protocol technologies showcases flexibility.", "HARD", "QUIZ");
addQ("What distinguishes Availability from Reliability?", ["Availability is about uptime when needed; Reliability is about continuous fault-tolerant operation", "They are exactly the same thing", "Reliability is only for hardware; Availability is for software", "Availability reduces costs; Reliability increases them"], "Availability is about uptime when needed; Reliability is about continuous fault-tolerant operation", "While related, availability focuses on access time, whereas reliability focuses on failing gracefully.", "HARD", "POSSIBLE");
addQ("Which design objective relies heavily on tools like SNMP (Simple Network Management Protocol)?", ["Manageability", "Security", "Flexibility", "Cost Efficiency"], "Manageability", "SNMP is a core protocol used for monitoring and manageability.", "MEDIUM", "CAT 1");
addQ("Implementing AES encryption for all wireless traffic primarily addresses:", ["Security", "Scalability", "Performance", "Availability"], "Security", "Encryption protects data confidentiality and integrity, which is a security function.", "EASY", "EXERCISE");
addQ("Designing a network so that adding a new branch office requires zero changes to the core routing topology is an example of:", ["Scalability", "Cost Efficiency", "Performance", "Security"], "Scalability", "Seamless expansion without core redesign is the hallmark of scalability.", "HARD", "QUIZ");
addQ("Which of the following is a symptom of poor network Performance?", ["High latency and slow file transfers", "Frequent unauthorized access", "Inability to add new users", "High power consumption"], "High latency and slow file transfers", "Latency directly degrades the user's perception of network performance.", "EASY", "POSSIBLE");
addQ("If an administrator struggles to locate the source of a network outage, the network suffers from poor:", ["Manageability", "Scalability", "Performance", "Cost Efficiency"], "Manageability", "Poor manageability means troubleshooting is difficult and time-consuming.", "MEDIUM", "CAT 2");
addQ("The requirement that 'all departments must share the same physical switches but remain logically isolated' is satisfied by VLANs to meet which two objectives?", ["Security and Cost Efficiency", "Performance and Availability", "Scalability and Reliability", "Flexibility and Manageability"], "Security and Cost Efficiency", "VLANs isolate traffic (Security) without buying new switches (Cost Efficiency).", "HARD", "EXERCISE");

// 4. Scalability Concepts (20 questions)
addQ("How is network Scalability defined?", ["The capability of a network system to support future growth efficiently", "The ability to run without any electricity", "The process of replacing all switches every year", "The restriction of the network to a fixed number of users"], "The capability of a network system to support future growth efficiently", "Scalability handles growth without reducing performance or requiring complete redesign.", "EASY", "QUIZ");
addQ("What happens to a network that lacks scalability as the organization grows?", ["Network congestion increases and performance decreases", "It automatically upgrades its hardware", "Cost efficiency improves", "Security policies become stronger"], "Network congestion increases and performance decreases", "Without scalability, added load causes congestion, poor performance, and difficult maintenance.", "MEDIUM", "POSSIBLE");
addQ("Which of the following is NOT typically a result of a growing network?", ["Decreased bandwidth demands", "More users", "More devices", "New services and applications"], "Decreased bandwidth demands", "Growing networks demand MORE bandwidth, not less.", "EASY", "CAT 1");
addQ("What are the two primary types of scalability?", ["Vertical and Horizontal", "Internal and External", "Physical and Logical", "Active and Passive"], "Vertical and Horizontal", "Scalability is generally divided into Vertical (Scale-Up) and Horizontal (Scale-Out).", "EASY", "EXERCISE");
addQ("Vertical Scalability is also known as:", ["Scale-Up", "Scale-Out", "Scale-In", "Scale-Down"], "Scale-Up", "Vertical scalability involves scaling up the capacity of existing devices.", "EASY", "QUIZ");
addQ("Which action is an example of Vertical Scalability?", ["Upgrading the CPU or RAM of an existing server", "Adding five new switches to the network", "Connecting a new branch office", "Implementing a new routing protocol"], "Upgrading the CPU or RAM of an existing server", "Vertical scalability means increasing the power/capacity of an existing single device.", "MEDIUM", "POSSIBLE");
addQ("Replacing a 24-port switch with a 48-port switch to accommodate more users is an example of:", ["Vertical Scalability", "Horizontal Scalability", "Network Redundancy", "Fault Tolerance"], "Vertical Scalability", "Replacing a device with a higher-capacity version of the same device is vertical scaling.", "MEDIUM", "CAT 2");
addQ("What is a major advantage of Vertical Scalability?", ["Simple implementation with fewer configuration changes", "It provides unlimited expansion capability", "Hardware upgrade costs are very low", "It adds more devices to the network"], "Simple implementation with fewer configuration changes", "Since you are just upgrading one device, the network topology and configuration changes are minimal.", "HARD", "EXERCISE");
addQ("What is a notable disadvantage of Vertical Scalability?", ["Hardware upgrade cost is high and expansion is limited", "It requires adding hundreds of new cables", "It makes the network horizontally flat", "It reduces security"], "Hardware upgrade cost is high and expansion is limited", "Eventually, a device cannot be upgraded further, and high-end hardware is expensive.", "MEDIUM", "QUIZ");
addQ("Horizontal Scalability is also known as:", ["Scale-Out", "Scale-Up", "Scale-In", "Scale-Down"], "Scale-Out", "Horizontal scalability involves scaling out by adding more devices.", "EASY", "POSSIBLE");
addQ("Which action is an example of Horizontal Scalability?", ["Adding another switch to support a new computer lab", "Increasing the RAM in the core router", "Replacing a 1Gbps link with a 10Gbps link", "Upgrading the firewall's CPU"], "Adding another switch to support a new computer lab", "Adding new nodes/devices to the network is horizontal scaling.", "MEDIUM", "CAT 1");
addQ("Adding more servers to distribute a web application's load represents which type of scalability?", ["Horizontal Scalability", "Vertical Scalability", "Physical Scalability", "Downward Scalability"], "Horizontal Scalability", "Adding more servers (scaling out) handles load horizontally.", "MEDIUM", "EXERCISE");
addQ("What is a key advantage of Horizontal Scalability?", ["Better fault tolerance and easy expansion", "No configuration changes required", "It uses only one central device", "It decreases the number of cables needed"], "Better fault tolerance and easy expansion", "Adding more devices improves fault tolerance because there is no single point of failure.", "HARD", "QUIZ");
addQ("What is a common disadvantage of Horizontal Scalability?", ["More complex management and requires proper planning", "Hardware is impossible to find", "It limits the network to 50 users", "It prevents the use of VLANs"], "More complex management and requires proper planning", "More devices mean more points of management, increasing network complexity.", "MEDIUM", "POSSIBLE");
addQ("If an organization anticipates explosive, unlimited growth, which scalability approach is generally more sustainable long-term?", ["Horizontal Scalability", "Vertical Scalability", "Cost Scalability", "Static Scalability"], "Horizontal Scalability", "Horizontal scaling is theoretically limitless (just add more nodes), whereas vertical scaling hits hardware limits.", "HARD", "CAT 2");
addQ("Which scalability approach often results in a 'single point of failure' if not paired with redundancy?", ["Vertical Scalability", "Horizontal Scalability", "Mesh Scalability", "Distributed Scalability"], "Vertical Scalability", "Relying on one massive, scaled-up device creates a single point of failure.", "HARD", "EXERCISE");
addQ("True or False: Expanding network segments by adding new routers is an example of Scale-Out.", ["True, it is Horizontal Scalability", "False, it is Vertical Scalability", "True, it is Vertical Scalability", "False, it is not a form of scalability"], "True, it is Horizontal Scalability", "Adding new routers is scaling out.", "MEDIUM", "QUIZ");
addQ("Why do organizations often use a mix of both vertical and horizontal scalability?", ["To balance cost, complexity, and performance limits", "Because routers only support vertical and switches only support horizontal", "Because horizontal scalability is illegal in some countries", "To intentionally confuse network attackers"], "To balance cost, complexity, and performance limits", "A hybrid approach provides the best balance of easy upgrades and long-term expansion.", "HARD", "POSSIBLE");
addQ("When a network administrator adds additional storage arrays to an existing SAN rather than buying a new SAN, they are utilizing:", ["Vertical Scalability", "Horizontal Scalability", "Network Segmentation", "Load Balancing"], "Vertical Scalability", "Expanding the capacity of an existing system is vertical scaling.", "MEDIUM", "CAT 1");
addQ("Which scalability method inherently improves network redundancy?", ["Horizontal Scalability", "Vertical Scalability", "Scale-Up", "CPU Upgrades"], "Horizontal Scalability", "Adding more devices means traffic can be rerouted if one device fails.", "EASY", "EXERCISE");

// 5. Network Documentation (20 questions)
addQ("What is the primary purpose of Network Documentation?", ["To record all important information about a computer network", "To automatically configure switches", "To block unauthorized access", "To replace network administrators"], "To record all important information about a computer network", "Documentation includes diagrams, configs, and IP addresses to help manage the network.", "EASY", "QUIZ");
addQ("Which of the following is NOT typically included in Network Documentation?", ["Employee salaries", "IP addresses", "Topology diagrams", "Security settings"], "Employee salaries", "Documentation focuses on technical network details, not HR information.", "EASY", "POSSIBLE");
addQ("How does proper network documentation assist administrators?", ["It simplifies troubleshooting and helps in maintenance", "It increases network latency", "It prevents the need for hardware upgrades", "It automatically generates IP addresses"], "It simplifies troubleshooting and helps in maintenance", "Clear records allow admins to quickly find and fix issues or plan expansions.", "MEDIUM", "CAT 2");
addQ("Which type of documentation shows the physical arrangement of devices and cables?", ["Physical Network Documentation", "Logical Network Documentation", "Security Documentation", "Operational Documentation"], "Physical Network Documentation", "Physical documentation shows where devices are placed and how cables run.", "EASY", "EXERCISE");
addQ("Device locations, rack layouts, and patch panel details are found in which documentation type?", ["Physical Network Documentation", "Logical Network Documentation", "Configuration Documentation", "Security Documentation"], "Physical Network Documentation", "These are physical attributes of the network infrastructure.", "MEDIUM", "QUIZ");
addQ("Which type of documentation shows how data flows through the network conceptually?", ["Logical Network Documentation", "Physical Network Documentation", "Operational Documentation", "Maintenance Documentation"], "Logical Network Documentation", "Logical documentation focuses on data flow, IP addressing, and routing.", "EASY", "POSSIBLE");
addQ("IP addressing schemes, VLAN structures, and routing protocols are detailed in the:", ["Logical Network Documentation", "Physical Network Documentation", "Security Documentation", "Rack Layout Documentation"], "Logical Network Documentation", "These represent the logical organization of the network.", "MEDIUM", "CAT 1");
addQ("If an administrator needs to check the exact commands used to set up a Cisco router, which documentation should they consult?", ["Configuration Documentation", "Physical Documentation", "Logical Documentation", "Operational Documentation"], "Configuration Documentation", "Configuration documentation contains the specific device settings and commands.", "MEDIUM", "EXERCISE");
addQ("Firewall policies, Access Control Lists (ACLs), and VPN settings are part of which documentation?", ["Security Documentation", "Physical Documentation", "Operational Documentation", "Configuration Documentation"], "Security Documentation", "Security documentation outlines all rules and permissions protecting the network.", "EASY", "QUIZ");
addQ("Which documentation type is used for daily network operations and maintenance schedules?", ["Operational Documentation", "Logical Documentation", "Security Documentation", "Physical Documentation"], "Operational Documentation", "Operational documentation guides daily tasks, backups, and maintenance.", "EASY", "POSSIBLE");
addQ("Backup procedures and troubleshooting guides are classified under:", ["Operational Documentation", "Physical Documentation", "Configuration Documentation", "Logical Documentation"], "Operational Documentation", "These are procedures used for operating and recovering the network.", "MEDIUM", "CAT 2");
addQ("Why is network documentation particularly crucial when a new administrator joins the team?", ["It drastically reduces the time needed for them to understand the network structure", "It hides the network's flaws", "It allows them to change passwords instantly", "It proves the previous administrator did a good job"], "It drastically reduces the time needed for them to understand the network structure", "Documentation is the primary learning tool for new IT staff.", "MEDIUM", "EXERCISE");
addQ("What can happen if a network is NOT properly documented?", ["Troubleshooting becomes difficult and downtime increases", "The network will automatically shut down", "Hackers will easily bypass firewalls", "Routers will lose their configurations"], "Troubleshooting becomes difficult and downtime increases", "Without a map of the network, finding the source of a problem takes much longer.", "EASY", "QUIZ");
addQ("A diagram showing communication between departments using VLANs is an example of a:", ["Logical Network Diagram", "Physical Network Diagram", "Rack Layout Diagram", "Operational Flowchart"], "Logical Network Diagram", "VLANs represent logical pathways, not physical cables.", "MEDIUM", "POSSIBLE");
addQ("A document listing 'Rules allowing only authorized users to access servers' belongs to:", ["Security Documentation", "Physical Documentation", "Logical Documentation", "Configuration Documentation"], "Security Documentation", "Access rules are a core component of security documentation.", "EASY", "CAT 1");
addQ("Which documentation type would typically contain 'Monitoring reports'?", ["Operational Documentation", "Security Documentation", "Physical Documentation", "Configuration Documentation"], "Operational Documentation", "Monitoring reports are part of the day-to-day operational tracking.", "MEDIUM", "EXERCISE");
addQ("Keeping track of which switch port connects to which wall jack in an office building is part of:", ["Physical Network Documentation", "Logical Network Documentation", "Security Documentation", "Operational Documentation"], "Physical Network Documentation", "Cable mapping is a physical documentation task.", "MEDIUM", "QUIZ");
addQ("In the context of documentation, what does 'reducing downtime' mean?", ["Fixing problems faster because the network layout is known", "Turning off servers during the night", "Making the network physically smaller", "Ignoring minor errors"], "Fixing problems faster because the network layout is known", "Quick troubleshooting directly leads to reduced downtime.", "MEDIUM", "POSSIBLE");
addQ("Is it considered good practice to update network documentation only once when the network is first built?", ["No, documentation must be updated continuously as the network changes", "Yes, the initial design never changes", "Yes, to save time for administrators", "No, it should only be updated when a device breaks"], "No, documentation must be updated continuously as the network changes", "Outdated documentation is often worse than no documentation.", "EASY", "CAT 2");
addQ("Which document would best help you recreate a switch's exact setup if it were destroyed by a power surge?", ["Configuration Documentation", "Physical Documentation", "Logical Documentation", "Operational Documentation"], "Configuration Documentation", "This contains the exact text or file needed to restore the device's settings.", "MEDIUM", "EXERCISE");

async function run() {
  const client = new MongoClient(uri);
  try {
    await client.connect();
    const db = client.db('school_db');
    let inserted = 0, skipped = 0;
    for (let q of questions) {
        q.createdAt = new Date();
        const exists = await db.collection('questions').findOne({ subjectId: q.subjectId, questionText: q.questionText });
        if (!exists) { await db.collection('questions').insertOne(q); inserted++; }
        else skipped++;
    }
    const total = await db.collection('questions').countDocuments({ subjectId });
    console.log(`\n✅ UNIT 1 (DESIGN PROFESSIONAL) IMEKAMILIKA!`);
    console.log(`   Maswali mapya: ${inserted} | Yaliyorukwa: ${skipped} | Maswali ya hili somo mpaka sasa: ${total}`);
  } finally { await client.close(); }
}
run().catch(console.dir);
