const { MongoClient } = require('mongodb');
const uri = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const subjectId = '6a49ecd238bb37720e3e91de';

const questions = [];
const moduleName = "Unit 2: Addressing & Routing Design";

function addQ(qText, options, correct, explanation, diff = "MEDIUM", cat = "QUIZ") {
    questions.push({
        subjectId, moduleName, category: cat, type: "MULTIPLE_CHOICE",
        questionText: qText, options, correctAnswer: correct, explanation, difficultyLevel: diff
    });
}

// 1. IPv4 & IPv6 Design (30 Questions)
addQ("What is the primary function of an IP Address?", ["To encrypt network traffic", "To uniquely identify devices in a network", "To act as a physical MAC address", "To define the routing protocol"], "To uniquely identify devices in a network", "An IP Address is a unique logical address used to identify devices.", "EASY", "QUIZ");
addQ("How many bits does an IPv4 address contain?", ["16-bit", "32-bit", "64-bit", "128-bit"], "32-bit", "IPv4 addresses are 32 bits long.", "EASY", "POSSIBLE");
addQ("Which format is typically used to write an IPv4 address?", ["Hexadecimal format", "Binary notation only", "Dotted decimal format", "Alphanumeric string"], "Dotted decimal format", "IPv4 is written in dotted decimal format (e.g., 192.168.1.1).", "EASY", "EXERCISE");
addQ("Approximately how many unique addresses does IPv4 support?", ["4.3 million", "4.3 billion", "340 undecillion", "Unlimited"], "4.3 billion", "32 bits allow for approximately 4.3 billion unique IP addresses.", "MEDIUM", "CAT 1");
addQ("Which of the following represents an IPv4 address divided correctly?", ["Divided into 3 octets", "Divided into 4 octets", "Divided into 6 octets", "Divided into 8 groups"], "Divided into 4 octets", "A 32-bit IPv4 address is divided into four 8-bit octets.", "EASY", "QUIZ");
addQ("Which IPv4 class is designated by the range 128 to 191 in the first octet?", ["Class A", "Class B", "Class C", "Class D"], "Class B", "Class B networks span from 128 to 191.", "EASY", "EXERCISE");
addQ("What is the default subnet mask for a Class A network?", ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"], "255.0.0.0", "Class A uses a default mask of /8 or 255.0.0.0.", "EASY", "POSSIBLE");
addQ("Which IPv4 class is reserved specifically for Multicast (Group communication)?", ["Class B", "Class C", "Class D", "Class E"], "Class D", "Class D (224-239) is reserved for multicast traffic.", "MEDIUM", "CAT 2");
addQ("Which class is used for experimental and research purposes?", ["Class A", "Class C", "Class D", "Class E"], "Class E", "Class E (240-255) is experimental.", "EASY", "QUIZ");
addQ("What is a major disadvantage of IPv4?", ["It does not support routing", "It requires Network Address Translation (NAT) due to limited addresses", "It cannot be used on local networks", "It operates at the physical layer"], "It requires Network Address Translation (NAT) due to limited addresses", "Because IPv4 addresses are exhausted, NAT is heavily relied upon.", "MEDIUM", "EXERCISE");
addQ("Why was IPv6 developed?", ["To replace routing protocols", "To solve the IPv4 address shortage", "To switch from binary to decimal", "To slow down internet speeds"], "To solve the IPv4 address shortage", "IPv6 provides a massive 128-bit address space to replace IPv4.", "EASY", "POSSIBLE");
addQ("How many bits does an IPv6 address use?", ["32-bit", "64-bit", "128-bit", "256-bit"], "128-bit", "IPv6 uses a 128-bit address space.", "EASY", "CAT 1");
addQ("In what format is an IPv6 address written?", ["Dotted decimal", "Binary only", "Hexadecimal", "Octal"], "Hexadecimal", "IPv6 is written using hexadecimal characters separated by colons.", "EASY", "QUIZ");
addQ("Which feature is built directly into IPv6 but is only optional in IPv4?", ["NAT (Network Address Translation)", "IPSec (Security)", "Subnetting", "DHCP"], "IPSec (Security)", "IPSec is built-in and mandatory for IPv6, providing native security.", "HARD", "EXERCISE");
addQ("Why is NAT not required in an IPv6 network?", ["Because IPv6 has a nearly unlimited number of public addresses", "Because IPv6 cannot communicate with the internet", "Because IPv6 uses only private addresses", "Because IPv6 is only used for local LANs"], "Because IPv6 has a nearly unlimited number of public addresses", "The vast address space makes NAT unnecessary; every device can have a public IP.", "MEDIUM", "POSSIBLE");
addQ("How is an IPv6 address structured?", ["Divided into 4 groups of 8 bits", "Divided into 8 groups of 16 bits", "Divided into 6 groups of 8 bits", "Divided into 2 groups of 64 bits"], "Divided into 8 groups of 16 bits", "128 bits are divided into 8 groups, each containing 4 hex digits (16 bits).", "HARD", "CAT 2");
addQ("Which of the following is an advantage of IPv6?", ["It uses NAT heavily", "It relies entirely on manual configuration", "Auto-configuration support", "It has a variable length header"], "Auto-configuration support", "IPv6 supports stateless address auto-configuration (SLAAC).", "MEDIUM", "QUIZ");
addQ("What is a disadvantage of adopting IPv6?", ["It limits the number of devices on the network", "It is complex to implement and requires expensive upgrades", "It forces networks to use Class A addresses", "It uses more bandwidth for payload data"], "It is complex to implement and requires expensive upgrades", "Transitioning to IPv6 can be complex and costly due to legacy equipment.", "MEDIUM", "EXERCISE");
addQ("Which version has a fixed header size to improve routing performance?", ["IPv4", "IPv6", "Both", "Neither"], "IPv6", "IPv6 has a fixed 40-byte header to speed up processing at routers.", "HARD", "POSSIBLE");
addQ("What mechanism in IPv4 causes congestion but is handled differently in IPv6?", ["Unicast traffic", "Broadcast traffic", "Multicast traffic", "Anycast traffic"], "Broadcast traffic", "IPv4 broadcasts cause congestion; IPv6 eliminates broadcasts, using multicast instead.", "HARD", "CAT 1");
addQ("Which network prefix length indicates a standard IPv6 subnet size?", ["/24", "/32", "/64", "/128"], "/64", "The standard IPv6 subnet size is /64.", "MEDIUM", "QUIZ");
addQ("How does IPv6 simplify router processing compared to IPv4?", ["By making the header variable length", "By fixing the header size and removing the header checksum", "By requiring NAT on all routers", "By routing based on MAC addresses"], "By fixing the header size and removing the header checksum", "Removing the checksum and fixing the size speeds up hardware processing.", "HARD", "EXERCISE");
addQ("Which of the following accurately describes the number of addresses supported by IPv6?", ["4.3 billion", "Almost unlimited (340 undecillion)", "256 million", "16 million"], "Almost unlimited (340 undecillion)", "IPv6 provides an astronomically large number of addresses.", "EASY", "POSSIBLE");
addQ("If an IPv4 address is 192.168.1.1, what is it represented as in binary?", ["11000000.10101000.00000001.00000001", "10101010.11001100.00000000.00000000", "11111111.11111111.11111111.00000000", "01010101.10101010.11110000.00001111"], "11000000.10101000.00000001.00000001", "192 = 11000000, 168 = 10101000, 1 = 00000001.", "HARD", "CAT 2");
addQ("What feature allows IPv6 to compress its address representation?", ["Removing all numbers", "Omitting leading zeros and using double colons (::) for consecutive zeros", "Converting to decimal", "Using letters instead of numbers"], "Omitting leading zeros and using double colons (::) for consecutive zeros", "Zero compression allows shortening IPv6 addresses significantly.", "MEDIUM", "QUIZ");
addQ("Which protocol version forces the use of DHCP for automatic configuration in most enterprise environments?", ["IPv6", "IPv4", "Both equally", "Neither"], "IPv4", "IPv4 relies heavily on DHCP, while IPv6 has native Auto-Configuration (SLAAC).", "MEDIUM", "EXERCISE");
addQ("Which IP version uses a decimal format?", ["IPv4", "IPv6", "Both", "Neither"], "IPv4", "IPv4 is decimal; IPv6 is hexadecimal.", "EASY", "POSSIBLE");
addQ("Class C networks are typically used for:", ["Very large global networks", "Multicast groups", "Small networks", "Experimental research"], "Small networks", "Class C provides 254 hosts per network, ideal for small networks.", "EASY", "CAT 1");
addQ("In an IPv6 short form address like 2001:db8::1, what does the '::' represent?", ["A wildcard for any IP", "One or more groups of all zeros", "The subnet mask delimiter", "The port number separator"], "One or more groups of all zeros", "The double colon represents consecutive groups of zeros.", "MEDIUM", "QUIZ");
addQ("Which protocol was designed to provide native, end-to-end security?", ["IPv4", "IPv6", "RIP", "ARP"], "IPv6", "IPv6 has built-in IPSec support.", "MEDIUM", "EXERCISE");

// 2. Subnetting Techniques (30 Questions)
addQ("What is the primary purpose of subnetting?", ["To combine multiple small networks into one", "To divide one large network into smaller networks", "To encrypt IP traffic", "To translate IP addresses to MAC addresses"], "To divide one large network into smaller networks", "Subnetting splits a large network into smaller, manageable subnets.", "EASY", "POSSIBLE");
addQ("Which of the following is a benefit of subnetting?", ["It increases broadcast traffic", "It wastes IP addresses", "It improves network performance and security", "It eliminates the need for routers"], "It improves network performance and security", "By reducing broadcast domains, it improves performance and allows tight security.", "MEDIUM", "CAT 2");
addQ("Without subnetting, a large network would suffer from:", ["Too much security", "Large broadcast traffic and network congestion", "Lack of IP addresses", "Faster routing speeds"], "Large broadcast traffic and network congestion", "A single large broadcast domain causes severe congestion.", "EASY", "QUIZ");
addQ("What does a Subnet Mask do?", ["It hides the IP address from hackers", "It separates the network portion from the host portion of an IP address", "It provides the MAC address of the gateway", "It routes packets to the Internet"], "It separates the network portion from the host portion of an IP address", "The mask tells the device which bits are network and which are host.", "MEDIUM", "EXERCISE");
addQ("What does CIDR stand for?", ["Classless Inter-Domain Routing", "Classful Internet Domain Routing", "Computer Internal Data Routing", "Centralized IP Distribution Resource"], "Classless Inter-Domain Routing", "CIDR is Classless Inter-Domain Routing.", "EASY", "POSSIBLE");
addQ("In Fixed Length Subnet Mask (FLSM), all subnets have:", ["Different subnet masks", "The same subnet mask and same number of hosts", "Variable number of hosts", "No subnet masks"], "The same subnet mask and same number of hosts", "FLSM divides the network into equally sized subnets.", "MEDIUM", "CAT 1");
addQ("If a network has a /24 mask and you borrow 2 bits for subnetting, what is the new mask?", ["/26", "/25", "/28", "/22"], "/26", "24 + 2 = 26. The new subnet mask is /26.", "HARD", "QUIZ");
addQ("Borrowing 2 bits for subnetting creates how many subnets?", ["2", "4", "6", "8"], "4", "2^2 = 4 subnets.", "MEDIUM", "EXERCISE");
addQ("What is the decimal equivalent of a /26 subnet mask?", ["255.255.255.128", "255.255.255.192", "255.255.255.224", "255.255.255.240"], "255.255.255.192", "/26 uses 2 bits in the 4th octet (128 + 64 = 192).", "HARD", "POSSIBLE");
addQ("In the subnet 192.168.1.0/26, what is the broadcast address for the first subnet?", ["192.168.1.62", "192.168.1.63", "192.168.1.64", "192.168.1.255"], "192.168.1.63", "The range is 0-63, making 63 the broadcast address.", "HARD", "CAT 2");
addQ("What technique uses different subnet masks for different subnets to save IP addresses?", ["FLSM", "VLSM", "CIDR", "NAT"], "VLSM", "Variable Length Subnet Mask (VLSM) creates subnets of varying sizes based on need.", "MEDIUM", "QUIZ");
addQ("When designing a VLSM network, which department should you allocate addresses to first?", ["The one with the smallest requirement", "The one with the largest network requirement first", "The router interfaces", "The servers"], "The one with the largest network requirement first", "You always start allocating the largest blocks first in VLSM.", "HARD", "EXERCISE");
addQ("If a department needs 100 hosts, which subnet mask should be used in VLSM?", ["/26", "/25", "/24", "/27"], "/25", "/25 provides 126 usable hosts (2^7 - 2 = 126), which fits 100 perfectly.", "HARD", "POSSIBLE");
addQ("Why is the formula (2^n - 2) used to calculate usable hosts?", ["Because the first address is the Network ID and the last is the Broadcast ID", "Because the router always takes 2 addresses", "Because IPv4 reserves 2 addresses for IPv6 compatibility", "Because of NAT translation overhead"], "Because the first address is the Network ID and the last is the Broadcast ID", "You cannot assign the Network ID or Broadcast ID to a device.", "MEDIUM", "CAT 1");
addQ("If a department needs 25 hosts, which subnet mask is most efficient?", ["/25", "/26", "/27", "/28"], "/27", "/27 provides 2^5 - 2 = 30 usable hosts, fitting 25 efficiently.", "HARD", "QUIZ");
addQ("Which of the following is a direct benefit of subnetting?", ["It makes all computers run faster", "It efficiently utilizes IP bandwidth by containing broadcasts", "It removes the need for physical cables", "It replaces the core router"], "It efficiently utilizes IP bandwidth by containing broadcasts", "Containing broadcasts to a smaller subnet saves bandwidth.", "MEDIUM", "EXERCISE");
addQ("How does IPv6 approach subnetting compared to IPv4?", ["It uses VLSM extensively because IPs are scarce", "It uses prefixes (like /64) instead of traditional decimal subnet masks", "It relies entirely on FLSM", "It does not support subnetting at all"], "It uses prefixes (like /64) instead of traditional decimal subnet masks", "IPv6 uses prefix lengths and has so many addresses that complex VLSM is rarely needed.", "MEDIUM", "POSSIBLE");
addQ("A common subnet size assigned to a standard local network in IPv6 is:", ["/32", "/48", "/64", "/128"], "/64", "/64 is the standard subnet size for a single LAN in IPv6.", "EASY", "CAT 2");
addQ("Which feature distinguishes FLSM from VLSM?", ["FLSM has high flexibility; VLSM has low flexibility", "FLSM subnet sizes are all the same; VLSM subnet sizes differ", "FLSM is complex; VLSM is simple", "FLSM saves IPs; VLSM wastes IPs"], "FLSM subnet sizes are all the same; VLSM subnet sizes differ", "FLSM = Fixed Length, VLSM = Variable Length.", "EASY", "QUIZ");
addQ("In a VLSM design, if the HR department takes 192.168.10.0/25, what is the starting network address for the next department?", ["192.168.10.64", "192.168.10.127", "192.168.10.128", "192.168.10.255"], "192.168.10.128", "/25 covers 0-127. The next subnet starts at 128.", "HARD", "EXERCISE");
addQ("Why do we subtract 2 when calculating hosts, but not when calculating subnets (in modern networking)?", ["Because subnets don't have broadcast addresses", "Modern routing protocols like OSPF and EIGRP support subnet zero", "Because binary math requires it", "Because IPv6 changed the rules"], "Modern routing protocols like OSPF and EIGRP support subnet zero", "With classless routing, the first and last subnets (subnet zero and all-ones) are usable.", "HARD", "POSSIBLE");
addQ("What term identifies the specific device within a subnet?", ["Network ID", "Subnet Mask", "Host ID", "MAC Prefix"], "Host ID", "The Host ID uniquely identifies a node on that specific subnet.", "EASY", "CAT 1");
addQ("Which classless notation represents a subnet mask of 255.255.0.0?", ["/8", "/16", "/24", "/32"], "/16", "255.255.0.0 represents 16 contiguous network bits.", "EASY", "QUIZ");
addQ("If you have a /30 subnet, how many usable hosts are available?", ["2", "4", "6", "14"], "2", "/30 leaves 2 host bits. 2^2 - 2 = 2 usable hosts. Perfect for point-to-point router links.", "MEDIUM", "EXERCISE");
addQ("A network administrator wants to separate the Sales and Admin networks to prevent Sales from accessing Admin servers. What is the best technique?", ["Implement VLSM/Subnetting and place them in different subnets", "Change their MAC addresses", "Give them the exact same IP address", "Use IPv6 instead of IPv4"], "Implement VLSM/Subnetting and place them in different subnets", "Subnetting logically isolates traffic, improving security and control.", "MEDIUM", "POSSIBLE");
addQ("In the binary mask 11111111.11111111.11111111.00000000, what does the 0 represent?", ["Network bits", "Host bits", "Broadcast bits", "Multicast bits"], "Host bits", "0s in a subnet mask indicate the host portion of the address.", "EASY", "CAT 2");
addQ("What dictates how many bits you must 'borrow' for subnetting?", ["The number of routers in the building", "The required number of subnets or the maximum hosts per subnet", "The speed of the network switch", "The version of the operating system"], "The required number of subnets or the maximum hosts per subnet", "You borrow bits based on how many subnets you need (2^n) or how many hosts you need.", "MEDIUM", "QUIZ");
addQ("If an IP address is 10.1.1.50/24, what is the network address?", ["10.0.0.0", "10.1.0.0", "10.1.1.0", "10.1.1.255"], "10.1.1.0", "With a /24 mask, the first three octets are the network ID.", "MEDIUM", "EXERCISE");
addQ("Which subnetting technique causes the most IP wastage if departments have vastly different sizes?", ["CIDR", "VLSM", "FLSM", "IPv6 Prefixing"], "FLSM", "FLSM forces all subnets to be the size of the largest requirement, wasting IPs on smaller ones.", "EASY", "POSSIBLE");
addQ("Which routing capability is required to support VLSM?", ["Classful Routing", "Classless Routing", "Static Routing", "Source Routing"], "Classless Routing", "Classless routing protocols (like OSPF, EIGRP, RIPv2) carry subnet mask info, allowing VLSM.", "HARD", "CAT 1");

// 3. Routing Protocols & OSPF/EIGRP (50 Questions)
addQ("What is the primary function of a routing protocol?", ["To encrypt user data", "To dynamically discover routes and update routing tables", "To act as a firewall", "To resolve domain names to IP addresses"], "To dynamically discover routes and update routing tables", "Routing protocols share info to discover and maintain the best paths.", "EASY", "QUIZ");
addQ("Which type of routing relies entirely on manual configuration by an administrator?", ["Dynamic Routing", "Static Routing", "Adaptive Routing", "Hybrid Routing"], "Static Routing", "Static routes are manually entered and do not adapt to topology changes automatically.", "EASY", "EXERCISE");
addQ("What is a major advantage of Static Routing?", ["Automatic updates when links fail", "Extremely scalable for large networks", "Secure with no routing protocol overhead", "It uses Dijkstra's algorithm"], "Secure with no routing protocol overhead", "Static routing consumes no bandwidth for updates and is secure because it doesn't advertise routes.", "MEDIUM", "POSSIBLE");
addQ("What is the primary disadvantage of Dynamic Routing?", ["It cannot find the shortest path", "It is complex and consumes CPU/bandwidth for updates", "It requires manual reconfiguration when a link drops", "It only works on small networks"], "It is complex and consumes CPU/bandwidth for updates", "Dynamic protocols constantly compute routes and exchange messages, utilizing resources.", "MEDIUM", "CAT 2");
addQ("Protocols used inside a single organization or network are known as:", ["Exterior Gateway Protocols (EGP)", "Interior Gateway Protocols (IGP)", "Path Vector Protocols", "Static Protocols"], "Interior Gateway Protocols (IGP)", "IGPs (like OSPF, EIGRP, RIP) operate within a single Autonomous System.", "EASY", "QUIZ");
addQ("Which protocol is an example of an Exterior Gateway Protocol (EGP)?", ["OSPF", "EIGRP", "RIP", "BGP"], "BGP", "BGP connects different organizations and ISPs across the internet.", "EASY", "EXERCISE");
addQ("Which of the following is a Distance Vector protocol?", ["OSPF", "RIP", "BGP", "IS-IS"], "RIP", "RIP is a classic distance vector protocol.", "EASY", "POSSIBLE");
addQ("What metric does RIP use to determine the best path?", ["Bandwidth", "Delay", "Hop Count", "Cost"], "Hop Count", "RIP uses hop count, with a maximum of 15 hops.", "EASY", "CAT 1");
addQ("Why is RIP considered slow?", ["It has a slow convergence time when the network changes", "It uses heavy encryption", "It calculates complex link states", "It uses high CPU power"], "It has a slow convergence time when the network changes", "RIP relies on periodic updates, making its reaction to changes (convergence) slow.", "MEDIUM", "QUIZ");
addQ("OSPF stands for:", ["Open Source Path Finder", "Open Shortest Path First", "Optical Switching Protocol Format", "Optimal Secure Path Forwarding"], "Open Shortest Path First", "OSPF stands for Open Shortest Path First.", "EASY", "EXERCISE");
addQ("What type of routing protocol is OSPF?", ["Distance Vector", "Link-State", "Path Vector", "Hybrid"], "Link-State", "OSPF is a link-state routing protocol.", "EASY", "POSSIBLE");
addQ("Which algorithm does OSPF use to calculate the best path?", ["Bellman-Ford", "DUAL", "Dijkstra (SPF)", "Diffusing Update Algorithm"], "Dijkstra (SPF)", "OSPF uses Dijkstra's Shortest Path First algorithm.", "MEDIUM", "CAT 2");
addQ("What is the metric used by OSPF?", ["Hop count", "Cost (based on bandwidth)", "Bandwidth and Delay", "Reliability"], "Cost (based on bandwidth)", "OSPF calculates 'Cost' by dividing a reference bandwidth by the interface bandwidth.", "MEDIUM", "QUIZ");
addQ("What is the central, backbone area in an OSPF hierarchical design?", ["Area 1", "Area 51", "Area 0", "Area 255"], "Area 0", "Area 0 is the backbone, and all other areas must connect to it.", "EASY", "EXERCISE");
addQ("Which OSPF packet type is used to discover and maintain neighbor relationships?", ["DBD", "LSR", "LSU", "Hello"], "Hello", "Hello packets are sent periodically to establish and verify neighbor adjacency.", "MEDIUM", "POSSIBLE");
addQ("What state indicates that OSPF routers have fully established adjacency and synchronized databases?", ["Init", "2-Way", "ExStart", "Full"], "Full", "The 'Full' state means routers have successfully exchanged all link-state information.", "HARD", "CAT 1");
addQ("What is a known disadvantage of OSPF?", ["It only supports up to 15 routers", "It has very slow convergence", "It requires complex configuration and higher CPU/memory usage", "It is a proprietary protocol owned by Cisco"], "It requires complex configuration and higher CPU/memory usage", "Maintaining link-state databases for large networks is resource-intensive.", "MEDIUM", "QUIZ");
addQ("EIGRP stands for:", ["Enhanced Interior Gateway Routing Protocol", "Exterior Internet Gateway Routing Protocol", "Encrypted Internal Gigabit Routing Protocol", "Extended Inter-Area Gateway Routing Protocol"], "Enhanced Interior Gateway Routing Protocol", "EIGRP stands for Enhanced Interior Gateway Routing Protocol.", "EASY", "EXERCISE");
addQ("What type of protocol is EIGRP considered to be?", ["Pure Distance Vector", "Pure Link-State", "Hybrid Routing Protocol", "Path Vector Protocol"], "Hybrid Routing Protocol", "EIGRP combines the best features of both Distance Vector and Link-State protocols.", "MEDIUM", "POSSIBLE");
addQ("Which metrics does EIGRP primarily use by default to calculate the best route?", ["Hop count only", "Bandwidth and Delay", "Reliability and Load", "Cost and Hop count"], "Bandwidth and Delay", "EIGRP uses a composite metric heavily weighted on Bandwidth and Delay.", "HARD", "CAT 2");
addQ("Which algorithm powers EIGRP's fast convergence?", ["Dijkstra SPF", "Bellman-Ford", "DUAL (Diffusing Update Algorithm)", "Spanning Tree"], "DUAL (Diffusing Update Algorithm)", "EIGRP uses DUAL to instantly calculate backup routes, providing lightning-fast convergence.", "HARD", "QUIZ");
addQ("Which EIGRP table stores all possible routes learned from neighbors, including backup routes?", ["Routing Table", "Neighbor Table", "Topology Table", "Adjacency Table"], "Topology Table", "The Topology Table holds all routes; the best ones are promoted to the Routing Table.", "HARD", "EXERCISE");
addQ("What is a primary advantage of EIGRP over OSPF?", ["It is open-source and supported by all vendors equally", "It uses lower bandwidth for updates (partial updates) and has faster convergence", "It requires no configuration", "It uses hop count for simplicity"], "It uses lower bandwidth for updates (partial updates) and has faster convergence", "EIGRP only sends updates when there is a change, unlike OSPF which refloods periodically.", "MEDIUM", "POSSIBLE");
addQ("What is the primary disadvantage of EIGRP?", ["It is slow", "It doesn't support VLSM", "It is mostly used in Cisco-based networks, limiting multi-vendor interoperability", "It cannot route across wide area networks"], "It is mostly used in Cisco-based networks, limiting multi-vendor interoperability", "While technically open now, EIGRP remains heavily tied to Cisco hardware.", "MEDIUM", "CAT 1");
addQ("BGP (Border Gateway Protocol) is known as a:", ["Link-State Protocol", "Distance Vector Protocol", "Path Vector Protocol", "Hybrid Protocol"], "Path Vector Protocol", "BGP is a Path Vector protocol used to exchange routing info between Autonomous Systems.", "MEDIUM", "QUIZ");
addQ("What is the primary use case for BGP?", ["Routing within a small office LAN", "Internet-scale routing between different organizations and ISPs", "Connecting printers in a department", "Replacing STP in a switched network"], "Internet-scale routing between different organizations and ISPs", "BGP is the protocol that runs the global Internet.", "EASY", "EXERCISE");
addQ("Which OSPF packet contains the actual routing information being updated?", ["LSU (Link-State Update)", "Hello", "LSR (Link-State Request)", "LSAck"], "LSU (Link-State Update)", "The LSU packet carries the Link-State Advertisements (LSAs) with routing updates.", "HARD", "POSSIBLE");
addQ("In OSPF, the state where bi-directional communication is established but databases are not yet exchanged is:", ["Init", "2-Way", "ExStart", "Exchange"], "2-Way", "2-Way indicates they see each other's Hellos, but haven't synced routing data.", "HARD", "CAT 2");
addQ("Which routing protocol prevents routing loops by maintaining a complete, detailed map of the entire network topology?", ["RIP", "EIGRP", "OSPF", "Static Routing"], "OSPF", "Link-state protocols (OSPF) build a complete topology map (database) of the network.", "MEDIUM", "QUIZ");
addQ("Which feature allows OSPF and EIGRP to support Subnetting and VLSM effectively?", ["They are Classful protocols", "They are Classless protocols", "They only use /24 masks", "They don't use IP addresses"], "They are Classless protocols", "Classless protocols send the subnet mask along with the route update.", "MEDIUM", "EXERCISE");
addQ("In EIGRP, what does the Neighbor Table store?", ["The best paths to all destinations", "All backup routes", "Directly connected EIGRP routers", "The entire internet routing table"], "Directly connected EIGRP routers", "The neighbor table tracks adjacent routers running EIGRP.", "MEDIUM", "POSSIBLE");
addQ("What does 'Convergence' mean in the context of routing?", ["The speed at which data travels", "The time it takes for all routers to agree on the network topology after a change", "The process of subnetting a network", "The encryption of routing updates"], "The time it takes for all routers to agree on the network topology after a change", "Fast convergence means the network quickly recovers from a link failure.", "EASY", "CAT 1");
addQ("If a routing protocol is described as 'vendor independent' or an 'open standard', which protocol is it most likely referring to?", ["EIGRP", "OSPF", "AppleTalk", "Novell IPX"], "OSPF", "OSPF is the industry standard link-state protocol supported by all vendors.", "EASY", "QUIZ");
addQ("What is the primary role of an ABR (Area Border Router) in OSPF?", ["To connect OSPF to the Internet via BGP", "To connect an OSPF area to the Backbone Area 0", "To provide firewall services", "To assign IP addresses dynamically"], "To connect an OSPF area to the Backbone Area 0", "ABRs sit on the border of Area 0 and another area, passing routing information between them.", "HARD", "EXERCISE");
addQ("Which protocol is best suited for Policy-Based Routing, where an administrator wants to control traffic based on business rules rather than just speed?", ["RIP", "OSPF", "BGP", "Static Routing"], "BGP", "BGP relies heavily on attributes and policies to select paths between autonomous systems.", "HARD", "POSSIBLE");
addQ("Which of the following routing protocols is considered the most scalable for massive, global networks?", ["RIPv1", "EIGRP", "OSPF", "BGP"], "BGP", "BGP handles hundreds of thousands of routes, making it the most scalable protocol globally.", "MEDIUM", "CAT 2");
addQ("If Router A has a static route to a destination and an OSPF route to the same destination, which route is typically placed in the routing table?", ["The OSPF route", "The static route", "Both routes", "Neither"], "The static route", "Static routes have a lower Administrative Distance (AD), meaning they are trusted more than dynamic protocols.", "HARD", "QUIZ");
addQ("Why do dynamic routing protocols use CPU and bandwidth?", ["They mine cryptocurrency", "They constantly send and process messages to discover and maintain routes", "They encrypt all payload data", "They scan for viruses"], "They constantly send and process messages to discover and maintain routes", "Dynamic routing requires processing hello packets, updates, and calculating algorithms.", "EASY", "EXERCISE");
addQ("What is the maximum hop count in RIP before a network is considered unreachable?", ["10", "15", "16", "255"], "16", "15 is the maximum valid distance; 16 signifies 'infinity' or unreachable.", "MEDIUM", "POSSIBLE");
addQ("If a router wants to find a route to a destination it does not know, where does it send the packet?", ["To the broadcast address", "To the default route (gateway of last resort)", "It drops it immediately without checking", "Back to the sender"], "To the default route (gateway of last resort)", "A default route acts as a catch-all for unknown destinations.", "EASY", "CAT 1");
addQ("Which formula correctly represents the OSPF Cost metric calculation?", ["Cost = Delay + Bandwidth", "Cost = Interface Bandwidth / Reference Bandwidth", "Cost = Reference Bandwidth / Interface Bandwidth", "Cost = Hop Count * 10"], "Cost = Reference Bandwidth / Interface Bandwidth", "OSPF cost is inversely proportional to interface bandwidth.", "HARD", "QUIZ");
addQ("Which OSPF packet type requests specific, missing Link-State information from a neighbor?", ["Hello", "LSR (Link-State Request)", "LSU", "LSAck"], "LSR (Link-State Request)", "LSRs are used to request pieces of the database that the router is missing.", "MEDIUM", "EXERCISE");
addQ("What happens during the 'Init' state of OSPF?", ["A Hello packet is received from a neighbor", "Databases are completely exchanged", "The router goes offline", "Bi-directional communication is verified"], "A Hello packet is received from a neighbor", "The Init state means a Hello was heard, but bi-directional visibility isn't established yet.", "HARD", "POSSIBLE");
addQ("What makes EIGRP 'Hybrid'?", ["It runs on both Windows and Linux", "It uses both IPv4 and IPv6", "It has the fast convergence of link-state but the simple configuration of distance-vector", "It mixes wireless and wired routing"], "It has the fast convergence of link-state but the simple configuration of distance-vector", "EIGRP combines characteristics from both major routing types.", "MEDIUM", "CAT 2");
addQ("If an OSPF router loses connection to a link, what does it do?", ["Waits 30 seconds and does nothing", "Sends a Link-State Update (LSU) to notify all other routers to rerun the SPF algorithm", "Changes its IP address", "Deletes its entire routing table"], "Sends a Link-State Update (LSU) to notify all other routers to rerun the SPF algorithm", "OSPF is event-driven; it floods changes immediately so the network converges.", "HARD", "QUIZ");
addQ("What metric does EIGRP multiply by 256 to calculate its final metric?", ["Hop count", "Cost", "(Bandwidth + Delay)", "Load"], "(Bandwidth + Delay)", "The core EIGRP formula uses Bandwidth and Delay scaled by 256.", "HARD", "EXERCISE");
addQ("In OSPF, what is the role of an LSAck packet?", ["To request routing info", "To acknowledge the receipt of an LSU", "To discover neighbors", "To describe the database"], "To acknowledge the receipt of an LSU", "LSAck ensures reliable delivery of link-state updates.", "MEDIUM", "POSSIBLE");
addQ("Which routing method is best for a very small, simple network with only one exit point?", ["OSPF", "BGP", "Static Routing", "EIGRP"], "Static Routing", "Static routing is simplest and perfectly suited for small networks with no redundant paths (stub networks).", "EASY", "CAT 1");
addQ("What is the primary function of the Dijkstra algorithm in OSPF?", ["To encrypt passwords", "To calculate the shortest, loop-free path to every known destination", "To assign IP addresses", "To filter malicious traffic"], "To calculate the shortest, loop-free path to every known destination", "Dijkstra builds a shortest-path tree from the topology database.", "MEDIUM", "QUIZ");
addQ("Which feature of OSPF allows it to limit the size of the topology database and reduce routing overhead?", ["Hierarchical design using Areas", "Metric scaling", "Path Vectors", "Hop count limits"], "Hierarchical design using Areas", "Dividing the network into areas contains link-state updates within the area.", "MEDIUM", "EXERCISE");


// 4. Route Summarization (30 Questions)
addQ("What is Route Summarization?", ["The process of combining multiple network routes into a single summarized route", "The process of splitting a single route into many subnets", "A method to encrypt routing tables", "A technique to increase the size of a routing table"], "The process of combining multiple network routes into a single summarized route", "Summarization aggregates multiple specific routes into one general route.", "EASY", "QUIZ");
addQ("Which of the following is another name for Route Summarization?", ["Subnetting", "Supernetting", "Fragmentation", "Multiplexing"], "Supernetting", "Route summarization is often called Supernetting or Route Aggregation.", "EASY", "POSSIBLE");
addQ("What is a primary benefit of Route Summarization?", ["It increases CPU usage", "It reduces routing table size, saving memory and CPU", "It makes routing tables extremely large and detailed", "It stops routers from communicating"], "It reduces routing table size, saving memory and CPU", "Smaller routing tables mean faster lookups and less memory usage.", "MEDIUM", "CAT 2");
addQ("Without route summarization, what issue might a large network face?", ["Faster routing", "Large routing tables leading to high bandwidth consumption during updates", "Better performance", "Fewer routing updates"], "Large routing tables leading to high bandwidth consumption during updates", "Huge routing tables slow down the router and consume bandwidth when exchanged.", "EASY", "QUIZ");
addQ("If you summarize 192.168.0.0/24, 1.0/24, 2.0/24, and 3.0/24, what is the resulting summarized route?", ["192.168.0.0/22", "192.168.0.0/23", "192.168.0.0/24", "192.168.0.0/16"], "192.168.0.0/22", "These 4 networks share the first 22 bits. Thus, the summary is /22.", "HARD", "EXERCISE");
addQ("How is the summary prefix length determined?", ["By adding all IP addresses together", "By finding the number of common binary bits shared by all the network addresses", "By selecting the smallest subnet mask", "By guessing"], "By finding the number of common binary bits shared by all the network addresses", "The common leading bits define the new, shorter subnet mask.", "MEDIUM", "POSSIBLE");
addQ("In the formula 2^n for summarization, what does 'n' represent?", ["The number of routers", "The number of bits borrowed (or reduced) from the network portion", "The number of hosts per subnet", "The speed of the link"], "The number of bits borrowed (or reduced) from the network portion", "n is the number of bit positions that differ among the summarized networks.", "HARD", "CAT 1");
addQ("If the CIDR notation is 10.0.0.0/8, what does the /8 signify?", ["8 hosts are allowed", "The network prefix length is 8 bits", "There are 8 subnets", "It is an IPv6 address"], "The network prefix length is 8 bits", "The /8 indicates that the first 8 bits define the network.", "EASY", "QUIZ");
addQ("Which step is crucial when manually calculating a summarized route?", ["Convert the network addresses to binary", "Convert the MAC address to hexadecimal", "Multiply the IP by the subnet mask", "Ping the default gateway"], "Convert the network addresses to binary", "Converting to binary allows you to see where the bit patterns diverge.", "MEDIUM", "EXERCISE");
addQ("What is the summarized route for 172.16.0.0/24 through 172.16.3.0/24?", ["172.16.0.0/21", "172.16.0.0/22", "172.16.0.0/16", "172.16.0.0/24"], "172.16.0.0/22", "4 networks require 2 bits. 24 - 2 = 22. Thus, /22.", "HARD", "POSSIBLE");
addQ("Does the RIP protocol support manual route summarization?", ["Yes, fully", "No, it only supports auto-summarization at classful boundaries", "Yes, but only for IPv6", "No, RIP does not support any summarization"], "No, it only supports auto-summarization at classful boundaries", "Traditional RIP (v1) only supports classful boundaries; it lacks manual classless summarization.", "HARD", "CAT 2");
addQ("Where does OSPF typically perform route summarization?", ["At every single router", "At the Access layer switches", "At the ABR (Area Border Router) between areas", "OSPF does not support summarization"], "At the ABR (Area Border Router) between areas", "OSPF summarizes routes at the boundaries of areas (ABR or ASBR) to keep area databases small.", "MEDIUM", "QUIZ");
addQ("Which protocol developed by Cisco supports both automatic and manual summarization at any router?", ["OSPF", "BGP", "EIGRP", "RIP"], "EIGRP", "EIGRP allows an administrator to configure manual summarization on any router interface.", "MEDIUM", "EXERCISE");
addQ("How does BGP utilize summarization?", ["It doesn't", "It uses 'aggregation' to significantly reduce the size of the global Internet routing table", "It only summarizes private IP addresses", "It uses it to speed up local LAN switching"], "It uses 'aggregation' to significantly reduce the size of the global Internet routing table", "BGP calls it route aggregation, which is critical for internet scalability.", "EASY", "POSSIBLE");
addQ("Does IPv6 support route summarization?", ["No, IPv6 has too many addresses", "Yes, IPv6 also supports summarization to keep routing tables manageable", "Only on Cisco devices", "Only when converted to IPv4"], "Yes, IPv6 also supports summarization to keep routing tables manageable", "Despite large addresses, aggregating prefixes (e.g., /48) is standard in IPv6.", "EASY", "CAT 1");
addQ("Why do large companies summarize routes towards their WAN links?", ["To reduce router workload and improve WAN performance", "To increase the number of IP addresses", "To encrypt the traffic", "To allow hackers access"], "To reduce router workload and improve WAN performance", "Fewer routes mean less processing and less bandwidth consumed by routing updates.", "MEDIUM", "QUIZ");
addQ("Why do ISPs rely heavily on route summarization?", ["Because they don't have enough routers", "For Internet scalability; without it, core internet routers would crash from massive routing tables", "To slow down customer internet speeds", "To prevent the use of IPv6"], "For Internet scalability; without it, core internet routers would crash from massive routing tables", "The global routing table would be unmanageable without aggressive summarization by ISPs.", "MEDIUM", "EXERCISE");
addQ("Which action directly opposes route summarization?", ["Supernetting", "Route Aggregation", "Subnetting", "CIDR block allocation"], "Subnetting", "Subnetting divides a block into smaller pieces; Summarization merges pieces into a larger block.", "EASY", "POSSIBLE");
addQ("When summarizing, the new subnet mask will always be:", ["Larger (longer) than the original masks", "Exactly the same as the original masks", "Smaller (shorter) than the original masks", "Always /8"], "Smaller (shorter) than the original masks", "Merging networks means the network prefix becomes shorter (e.g., /24 becomes /22).", "MEDIUM", "CAT 2");
addQ("If you have 8 contiguous /24 networks to summarize, what will the summarized prefix length be?", ["/24", "/23", "/21", "/16"], "/21", "8 networks = 2^3. Subtract 3 from 24 to get /21.", "HARD", "QUIZ");
addQ("Summarization hides network instability. If a specific /24 link goes up and down rapidly (flapping), what happens to the summarized /16 route advertised to the core?", ["The /16 route flaps as well", "The core router crashes", "The summarized /16 route remains stable as long as at least one subnet is active", "The /16 route is deleted"], "The summarized /16 route remains stable as long as at least one subnet is active", "Summarization isolates topology changes, preventing flaps from affecting the wider network.", "HARD", "EXERCISE");
addQ("Which of the following describes Auto-Summarization?", ["The administrator manually calculates the bits", "The router automatically summarizes routes to their default classful boundaries (A, B, C)", "The router turns off all routing protocols", "The router encrypts the routing table"], "The router automatically summarizes routes to their default classful boundaries (A, B, C)", "Auto-summarization happens at classful boundaries automatically in older protocols.", "MEDIUM", "POSSIBLE");
addQ("Why is Auto-Summarization often turned off in modern networks?", ["It causes routers to overheat", "Because modern networks are classless and disjointed; auto-summarizing can cause routing black holes", "Because it uses too much electricity", "It is actually never turned off"], "Because modern networks are classless and disjointed; auto-summarizing can cause routing black holes", "In a discontiguous network, auto-summarization causes incorrect routing decisions.", "HARD", "CAT 1");
addQ("What happens if an IP packet matches a summarized route (e.g., /16) AND a more specific route (e.g., /24) in the routing table?", ["The router drops the packet", "The router chooses the more specific route (Longest Prefix Match)", "The router chooses the summarized route", "The router sends the packet to both"], "The router chooses the more specific route (Longest Prefix Match)", "Routers always forward based on the most specific match (longest prefix).", "HARD", "QUIZ");
addQ("To summarize 10.1.0.0/16 and 10.2.0.0/16, what must be true?", ["They cannot be summarized because they are not contiguous binary boundaries", "They can be summarized to 10.0.0.0/8 immediately", "They must use IPv6", "They must use RIP"], "They cannot be summarized because they are not contiguous binary boundaries", "10.1 (00000001) and 10.2 (00000010) cannot be perfectly summarized into one block without including 10.3 and 10.0.", "HARD", "EXERCISE");
addQ("What is an 'Aggregate Route'?", ["A route that has been broken down into smaller pieces", "Another term for a summarized route representing multiple subnets", "A route that fails constantly", "A route configured for Voice over IP"], "Another term for a summarized route representing multiple subnets", "Aggregation and Summarization are synonymous in routing.", "EASY", "POSSIBLE");
addQ("Which of the following is NOT a benefit of Supernetting/Summarization?", ["Reduces routing update traffic", "Saves memory in routers", "Increases the number of IP addresses available to hosts", "Speeds up route table lookups"], "Increases the number of IP addresses available to hosts", "Summarization does not create new IP addresses; it just changes how routers advertise them.", "MEDIUM", "CAT 2");
addQ("In binary, if two addresses share the first 20 bits identically, the summary mask will be:", ["/24", "/20", "/16", "/22"], "/20", "The shared bits determine the length of the summarized mask.", "EASY", "QUIZ");
addQ("Route summarization is essentially the opposite of:", ["Routing", "Switching", "Subnetting", "VLAN Tagging"], "Subnetting", "Subnetting divides; Summarization merges.", "EASY", "EXERCISE");
addQ("When configuring summarization on an OSPF ABR, which command concept is used?", ["ip route", "area range", "summary-address", "auto-summary"], "area range", "In OSPF, the 'area range' command is used on the ABR to summarize routes into the backbone.", "HARD", "POSSIBLE");

async function run() {
  const client = new MongoClient(uri);
  try {
    await client.connect();
    const db = client.db('school_db');
    let inserted = 0, skipped = 0;
    for (let q of questions) {
        q.createdAt = new Date();
        const exists = await db.collection('questions').findOne({ subjectId: q.subjectId, questionText: q.questionText });
        if (!exists) { await db.collection('questions').insertOne(q); inserted++; }
        else skipped++;
    }
    const total = await db.collection('questions').countDocuments({ subjectId });
    console.log(`\n✅ UNIT 2 (DESIGN PROFESSIONAL) IMEKAMILIKA!`);
    console.log(`   Maswali mapya: ${inserted} | Yaliyorukwa: ${skipped} | Maswali ya hili somo mpaka sasa: ${total}`);
  } finally { await client.close(); }
}
run().catch(console.dir);
