const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a49ecb638bb37720e3e9194"; // COMPUTER ARCHITECTURE AND ASSEMBLY PROGRAMMING LANGUAGE

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const ca_unit4_part2 = [
// ╔══════════════════════════════════╗
// ║           QUIZ (8 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "What is an array processor?", ["A processor that only handles text", "A specialized hardware unit designed specifically for performing operations on arrays efficiently, often using SIMD", "A processor for hard drives", "A software algorithm"], "A specialized hardware unit designed specifically for performing operations on arrays efficiently, often using SIMD", "Array processors have dedicated memory banks optimized to fetch long lines of data (arrays) quickly for parallel processing."),
Q("QUIZ", "MEDIUM", "What is the primary function of the 'Instruction Queue' in a microprocessor?", ["To store the results of operations", "To pre-fetch and temporarily hold upcoming instructions from memory so the execution unit doesn't have to wait", "To connect to the monitor", "To cool the CPU down"], "To pre-fetch and temporarily hold upcoming instructions from memory so the execution unit doesn't have to wait", "This is a basic form of pipelining. The Bus Interface Unit fetches code into the queue while the Execution Unit is busy doing math."),
Q("QUIZ", "HARD", "How does 'CISC' differ from 'RISC' in terms of hardware design?", ["CISC has no registers", "CISC microprocessors have highly complex control units (often microprogrammed) to handle variable-length, multi-cycle instructions", "CISC only uses one instruction", "CISC cannot use RAM"], "CISC microprocessors have highly complex control units (often microprogrammed) to handle variable-length, multi-cycle instructions", "Because CISC instructions can do complex things (like 'multiply a memory address by a register and store it back'), the hardware required to decode them is massive compared to RISC."),
Q("QUIZ", "MEDIUM", "What is a 'Digital Signal Processor' (DSP) used for?", ["Word processing", "Specialized, real-time math operations like audio encoding, video decoding, and telecommunications signal filtering", "Writing databases", "Cooling the computer"], "Specialized, real-time math operations like audio encoding, video decoding, and telecommunications signal filtering", "DSPs are highly optimized for Multiply-Accumulate (MAC) operations, which are the foundation of digital filtering and Fourier transforms."),
Q("QUIZ", "EASY", "In an 8086 microprocessor, what does 'ALU' stand for?", ["Arithmetic Logic Unit", "Array Line Utility", "Advanced Local Unit", "Asynchronous Link User"], "Arithmetic Logic Unit", "The ALU is the calculator inside the microprocessor that performs all the addition, subtraction, AND, OR, and XOR operations."),
Q("QUIZ", "HARD", "What is 'Out-of-Order Execution' in modern superscalar processors?", ["Executing programs randomly", "The CPU dynamically reordering instructions to execute them as soon as their required data is available, rather than strictly following the program's original order", "Executing code backwards", "Failing to execute instructions"], "The CPU dynamically reordering instructions to execute them as soon as their required data is available, rather than strictly following the program's original order", "If Instruction 2 is stalled waiting for RAM, but Instruction 3 is ready and independent, the CPU will execute Instruction 3 first to save time, and reorder the final results later."),
Q("QUIZ", "MEDIUM", "What is the purpose of 'Instruction-Level Parallelism' (ILP)?", ["To run two programs at once", "To execute multiple independent instructions from a single program simultaneously within the CPU pipeline to increase throughput", "To copy data faster", "To save hard drive space"], "To execute multiple independent instructions from a single program simultaneously within the CPU pipeline to increase throughput", "This is done entirely in hardware. The programmer writes normal sequential code, and the CPU finds the parallelism automatically."),
Q("QUIZ", "HARD", "What is 'Data Dependency' in the context of pipelining?", ["When a hard drive fails", "When an instruction requires the result of a previous instruction that hasn't finished executing yet, causing a pipeline stall", "When the CPU is connected to Wi-Fi", "When data is corrupted"], "When an instruction requires the result of a previous instruction that hasn't finished executing yet, causing a pipeline stall", "Data dependency is the biggest enemy of pipeline efficiency. Techniques like 'Operand Forwarding' are used to mitigate it."),

// ╔══════════════════════════════════╗
// ║         EXERCISE (8 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "What is the main benefit of a 64-bit processor over a 32-bit processor?", ["It has 64 screens", "It can process larger chunks of data at once and address vastly more physical memory (RAM)", "It uses 64 times less power", "It is 64 years old"], "It can process larger chunks of data at once and address vastly more physical memory (RAM)", "A 32-bit processor can only address about 4GB of RAM. A 64-bit processor can theoretically address 16 Exabytes."),
Q("EXERCISE", "MEDIUM", "What is a 'Multicore' processor?", ["A processor with multiple power supplies", "A single physical microprocessor chip that contains two or more independent processing units (cores) that can execute different tasks simultaneously", "A processor that only does math", "A processor with multiple motherboards"], "A single physical microprocessor chip that contains two or more independent processing units (cores) that can execute different tasks simultaneously", "This is the most common form of MIMD parallel processing for consumers today. Your OS can run a game on Core 1 and a virus scan on Core 2."),
Q("EXERCISE", "HARD", "How does a 'Branch Instruction' negatively affect pipelining?", ["It deletes data", "It changes the program counter based on a condition; if the CPU pre-fetched the wrong path, it must flush the entire pipeline, wasting many clock cycles", "It overheats the CPU", "It stops the clock"], "It changes the program counter based on a condition; if the CPU pre-fetched the wrong path, it must flush the entire pipeline, wasting many clock cycles", "This is called a Control Hazard. CPUs use complex 'Branch Prediction' hardware to guess which way the IF statement will go to avoid flushing the pipeline."),
Q("EXERCISE", "MEDIUM", "What is the 'Execution Unit' (EU) in the 8086 architecture responsible for?", ["Fetching data from memory", "Decoding and executing the instructions using the ALU and registers", "Connecting to the monitor", "Managing the power supply"], "Decoding and executing the instructions using the ALU and registers", "In the 8086, the Bus Interface Unit handles getting the data from the outside world, while the Execution Unit does the actual thinking inside."),
Q("EXERCISE", "EASY", "What is a 'Clock Cycle'?", ["The time on a wall clock", "One pulse of the system's electronic oscillator, acting as the fundamental heartbeat that synchronizes all processor operations", "The time it takes to boot up", "The speed of the hard drive"], "One pulse of the system's electronic oscillator, acting as the fundamental heartbeat that synchronizes all processor operations", "If a CPU is 3 GHz, its 'heart' beats 3 billion times per second. Every pipeline stage usually takes exactly one clock cycle."),
Q("EXERCISE", "HARD", "What does 'Hardware Multithreading' (like Intel Hyper-Threading) achieve?", ["It physically splits the CPU in half", "It allows a single physical core to present itself as multiple logical cores to the OS, interleaving instructions from two threads to fill pipeline bubbles", "It increases the clock speed infinitely", "It connects to multiple internet networks"], "It allows a single physical core to present itself as multiple logical cores to the OS, interleaving instructions from two threads to fill pipeline bubbles", "If Thread 1 stalls waiting for RAM, the core instantly switches to executing Thread 2, maximizing the utilization of the superscalar execution units."),
Q("EXERCISE", "MEDIUM", "What is the role of a 'System Bus'?", ["To transport people", "To act as the main communication pathway connecting the microprocessor to memory and other peripheral devices", "To cool the motherboard", "To provide electricity"], "To act as the main communication pathway connecting the microprocessor to memory and other peripheral devices", "It consists of the address bus, data bus, and control bus."),
Q("EXERCISE", "HARD", "In array processing, what is 'Data Locality'?", ["Storing data in a local folder", "The concept that keeping data elements physically close together in memory (like an array) allows for vastly more efficient cache and vector processing", "Storing data randomly", "Encrypting local files"], "The concept that keeping data elements physically close together in memory (like an array) allows for vastly more efficient cache and vector processing", "If data is scattered randomly across RAM, a vector processor will waste all its time waiting for the bus. If it's contiguous, it can burst-read it all at once."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "Which company is known for creating the x86 microprocessor architecture?", ["Apple", "Intel", "Microsoft", "Google"], "Intel", "Intel introduced the 8086 in 1978, and its underlying instruction set architecture (x86) is still the standard for almost all desktop PCs today."),
Q("CAT 1", "MEDIUM", "What is 'Distributed Memory' in SPMD systems?", ["Memory that is deleted", "An architecture where each parallel node has its own private, local RAM, and processors must explicitly send messages to each other to share data", "Memory that is shared on one chip", "Memory stored on USBs"], "An architecture where each parallel node has its own private, local RAM, and processors must explicitly send messages to each other to share data", "Unlike a multi-core desktop where all cores share the same RAM, a supercomputer has thousands of separate PCs linked by high-speed cables."),
Q("CAT 1", "HARD", "What is 'Speculative Execution'?", ["Executing code without power", "The CPU executing instructions past an unresolved branch (like an IF statement) based on a prediction, before knowing if those instructions actually should be executed", "Executing code very slowly", "Executing code with errors"], "The CPU executing instructions past an unresolved branch (like an IF statement) based on a prediction, before knowing if those instructions actually should be executed", "If the prediction is right, the CPU saves a lot of time. If wrong, it throws away the speculative work. This technique led to the famous Spectre security vulnerability."),
Q("CAT 1", "EASY", "What is the basic component of a microprocessor that acts as a tiny electronic switch?", ["The Transistor", "The Hard Drive", "The Monitor", "The Keyboard"], "The Transistor", "Modern microprocessors contain billions of microscopic transistors that turn on and off to represent binary 1s and 0s."),
Q("CAT 1", "MEDIUM", "What is a 'System on a Chip' (SoC)?", ["A chip used only for sound", "An integrated circuit that incorporates a microprocessor along with memory, GPU, and I/O controllers all onto a single piece of silicon", "A massive supercomputer", "A type of network cable"], "An integrated circuit that incorporates a microprocessor along with memory, GPU, and I/O controllers all onto a single piece of silicon", "Most smartphone processors (like the Apple A-series or Qualcomm Snapdragon) are SoCs. They are highly power-efficient and space-saving."),
Q("CAT 1", "HARD", "How does a 'Data Hazard' differ from a 'Structural Hazard' in pipelining?", ["They are the same", "A data hazard is waiting for a previous result; a structural hazard is two different pipeline stages trying to use the same hardware resource (like the memory bus) at the exact same time", "A structural hazard is a physical break in the CPU", "A data hazard only happens on hard drives"], "A data hazard is waiting for a previous result; a structural hazard is two different pipeline stages trying to use the same hardware resource (like the memory bus) at the exact same time", "If the Instruction Fetch stage is trying to read code from RAM, and the Memory Access stage is trying to save a variable to RAM, the bus cannot do both at once. One stage must stall."),
Q("CAT 1", "MEDIUM", "What does 'Throughput' mean in the context of CPU performance?", ["The size of the CPU", "The number of instructions completed per unit of time", "The temperature of the CPU", "The amount of electricity used"], "The number of instructions completed per unit of time", "Pipelining doesn't make a single instruction execute faster (latency); it increases the total number of instructions finishing per second (throughput)."),
Q("CAT 1", "HARD", "What is the 'Operand Fetch' stage in an arithmetic pipeline?", ["Buying a calculator", "The stage where the specific data values (operands) needed for a complex math operation are retrieved from registers before entering the multiplication/addition hardware", "Fetching instructions", "Deleting data"], "The stage where the specific data values (operands) needed for a complex math operation are retrieved from registers before entering the multiplication/addition hardware", "Before you can multiply two floating-point numbers, the pipeline must align their exponents and fetch their mantissas."),
Q("CAT 1", "EASY", "What is the main function of 'Cache' inside a microprocessor?", ["To store the operating system permanently", "To hold frequently used data and instructions extremely close to the execution units for instant access, bypassing slow RAM", "To cool the CPU", "To connect to Wi-Fi"], "To hold frequently used data and instructions extremely close to the execution units for instant access, bypassing slow RAM", "Cache is the bridge between the ultra-fast CPU core and the relatively slow system memory."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "What is an 'Opcode'?", ["A secret password", "The portion of a machine language instruction that specifies the exact operation to be performed (like ADD or JMP)", "A type of memory", "A web address"], "The portion of a machine language instruction that specifies the exact operation to be performed (like ADD or JMP)", "The CPU's decode stage reads the opcode to know which hardware circuits to turn on."),
Q("CAT 2", "MEDIUM", "What is 'Shared Memory' in parallel architecture?", ["Memory that is copied to a USB", "An architecture where multiple processors have access to the same global physical memory space, making data sharing easy but requiring synchronization", "Memory that is given away for free", "A single small cache"], "An architecture where multiple processors have access to the same global physical memory space, making data sharing easy but requiring synchronization", "This is how your desktop PC works. All cores can see the same 16GB of RAM. If they aren't synchronized properly, they will corrupt each other's data."),
Q("CAT 2", "HARD", "What is the purpose of 'Operand Forwarding' (or Bypassing) in a pipeline?", ["To skip the execution stage", "A hardware technique that routes the result of an ALU operation directly back to the input of the ALU for the next instruction, avoiding a stall while waiting for the Write Back stage", "To forward emails", "To send data to the printer"], "A hardware technique that routes the result of an ALU operation directly back to the input of the ALU for the next instruction, avoiding a stall while waiting for the Write Back stage", "If Instruction 2 needs the result of Instruction 1, forwarding allows Instruction 2 to grab the answer the exact millisecond Instruction 1 finishes calculating it, eliminating the data hazard stall."),
Q("CAT 2", "EASY", "Which architecture focuses on a small, highly optimized set of instructions?", ["CISC", "RISC (Reduced Instruction Set Computing)", "GPU", "DSP"], "RISC (Reduced Instruction Set Computing)", "RISC processors (like ARM) focus on doing simple things incredibly fast, relying on the compiler to string them together to do complex tasks."),
Q("CAT 2", "MEDIUM", "What is a 'Coprocessor'?", ["A processor that copies data", "A specialized secondary processor (like an old Math Coprocessor or a modern GPU) designed to assist the main CPU with specific, intensive tasks", "A backup power supply", "A type of RAM"], "A specialized secondary processor (like an old Math Coprocessor or a modern GPU) designed to assist the main CPU with specific, intensive tasks", "Before CPUs had built-in floating-point units, you had to buy a separate 'math coprocessor' chip just to do decimal calculations efficiently."),
Q("CAT 2", "HARD", "What is 'Amdahl's Law' in parallel computing?", ["A law that states computers double in speed every year", "A formula that calculates the maximum theoretical speedup of a parallel system, proving that the speedup is strictly limited by the sequential (non-parallelizable) portion of the code", "A law about hard drive capacity", "A law about network speed"], "A formula that calculates the maximum theoretical speedup of a parallel system, proving that the speedup is strictly limited by the sequential (non-parallelizable) portion of the code", "Even if you have a million processors, if 10% of your code MUST be run sequentially, your program can never run more than 10 times faster overall."),
Q("CAT 2", "MEDIUM", "What is the 'Instruction Queue' in pipelining?", ["A line of people waiting to use the computer", "A small buffer that pre-fetches and holds sequential instructions from memory so the pipeline doesn't have to wait for RAM during the Fetch stage", "A type of hard drive", "A virus"], "A small buffer that pre-fetches and holds sequential instructions from memory so the pipeline doesn't have to wait for RAM during the Fetch stage", "By fetching chunks of code at a time, the CPU ensures it always has work ready to do."),
Q("CAT 2", "HARD", "In superscalar architecture, what is 'Instruction Issue'?", ["Publishing a manual", "The process of the CPU's decode/dispatch unit analyzing multiple instructions simultaneously and sending them to available, independent execution units in the same clock cycle", "A hardware error", "Deleting old code"], "The process of the CPU's decode/dispatch unit analyzing multiple instructions simultaneously and sending them to available, independent execution units in the same clock cycle", "This requires complex dependency-checking hardware. The CPU must guarantee that the two instructions being issued together don't interfere with each other."),
Q("CAT 2", "EASY", "What does 'GPU' stand for?", ["General Processing Unit", "Graphics Processing Unit", "Global Power Unit", "Gigabyte Processor Unit"], "Graphics Processing Unit", "While initially just for rendering video game graphics, GPUs are now the driving force behind modern Artificial Intelligence training."),

// ╔══════════════════════════════════╗
// ║            UE (8 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "What is a 'Bus Interface Unit' (BIU)?", ["A public transportation schedule", "The part of the microprocessor responsible for all communication with external memory and I/O devices over the system buses", "A type of monitor", "A cooling fan"], "The part of the microprocessor responsible for all communication with external memory and I/O devices over the system buses", "In the 8086, the BIU fetches data and instructions, passing them to the Execution Unit (EU)."),
Q("UE", "MEDIUM", "What makes 'Vector Processing' highly efficient for scientific simulations?", ["It uses less electricity", "It exploits 'Data-Level Parallelism' by applying a single mathematical operation to massive arrays of data simultaneously, avoiding scalar loop overhead", "It guesses the answers", "It only uses integers"], "It exploits 'Data-Level Parallelism' by applying a single mathematical operation to massive arrays of data simultaneously, avoiding scalar loop overhead", "Simulating fluid dynamics requires applying the same physics equation to millions of water particles. Vector processing does this instantly."),
Q("UE", "HARD", "What is 'VLIW' (Very Long Instruction Word) architecture?", ["A processor with a very long physical size", "An architecture where the compiler, rather than the CPU hardware, groups independent instructions together into one long 'word' to be executed in parallel, reducing CPU hardware complexity", "A software program that writes long essays", "A type of slow memory"], "An architecture where the compiler, rather than the CPU hardware, groups independent instructions together into one long 'word' to be executed in parallel, reducing CPU hardware complexity", "Unlike Superscalar (where the CPU finds the parallelism at runtime), VLIW forces the software compiler to find the parallelism beforehand, simplifying the silicon chip."),
Q("UE", "MEDIUM", "What is 'Branch Prediction'?", ["Predicting tree growth", "A hardware technique where the CPU guesses the outcome of an IF statement and starts executing that path speculatively to keep the pipeline full", "A weather forecasting tool", "Predicting hard drive failure"], "A hardware technique where the CPU guesses the outcome of an IF statement and starts executing that path speculatively to keep the pipeline full", "Modern CPUs are right about 95% of the time, saving massive amounts of time that would otherwise be wasted waiting for the condition to be calculated."),
Q("UE", "HARD", "How does a 'Write-After-Write' (WAW) data dependency occur?", ["When writing a letter twice", "When two instructions attempt to write a result to the same specific register, and due to out-of-order execution, the older instruction accidentally overwrites the newer instruction's result", "When writing to a full hard drive", "When copying a file"], "When two instructions attempt to write a result to the same specific register, and due to out-of-order execution, the older instruction accidentally overwrites the newer instruction's result", "This is an 'Output Dependency'. The CPU solves this using 'Register Renaming' hardware to give them separate hidden physical registers."),
Q("UE", "EASY", "What is the 'Accumulator'?", ["A battery charger", "A special, primary register in the CPU used heavily for arithmetic and logical operations and storing their immediate results", "A type of RAM", "A cooling system"], "A special, primary register in the CPU used heavily for arithmetic and logical operations and storing their immediate results", "In the 8086, this is the AX register. Many instructions are hardwired to use the accumulator automatically to save code space."),
Q("UE", "MEDIUM", "What does 'Instruction Decoding' (ID) achieve?", ["Translating English to Spanish", "It translates the binary opcode fetched from memory into specific control signals that activate the correct hardware pathways in the execution unit", "It decrypts passwords", "It changes binary to text"], "It translates the binary opcode fetched from memory into specific control signals that activate the correct hardware pathways in the execution unit", "The ID stage is the 'brain' figuring out what the 'eyes' (IF stage) just read."),
Q("UE", "HARD", "What is the defining characteristic of an 'Array Processor'?", ["It processes arrays of hard drives", "It consists of a large grid of identical processing elements acting synchronously under the control of a single master unit (SIMD) to process massive datasets", "It processes audio only", "It has no memory"], "It consists of a large grid of identical processing elements acting synchronously under the control of a single master unit (SIMD) to process massive datasets", "They are highly specialized. If you want to brighten an image, the master unit says 'ADD 10', and 1000 processing elements instantly add 10 to 1000 different pixels simultaneously."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (8 Qns)       ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "What does 'DSP' stand for?", ["Digital Signal Processor", "Data Storage Protocol", "Dynamic System Power", "Direct Screen Print"], "Digital Signal Processor", "These specialized chips are what make your noise-canceling headphones and high-speed modems work."),
Q("POSSIBLE QNS", "MEDIUM", "What is 'Pipeline Processing'?", ["Processing oil and gas", "An implementation technique where multiple instructions are overlapped in execution, acting like an assembly line for the CPU", "Processing data on a hard drive", "Processing network packets"], "An implementation technique where multiple instructions are overlapped in execution, acting like an assembly line for the CPU", "It doesn't change how fast one instruction runs; it drastically increases how many instructions finish per second."),
Q("POSSIBLE QNS", "HARD", "What is 'Register Renaming'?", ["Giving a register a new name in software", "A hardware technique used in out-of-order execution where logical registers are dynamically mapped to a larger pool of physical registers to eliminate false data dependencies (like WAW or WAR)", "A software bug", "Deleting a register"], "A hardware technique used in out-of-order execution where logical registers are dynamically mapped to a larger pool of physical registers to eliminate false data dependencies (like WAW or WAR)", "This allows the CPU to pretend it has hundreds of registers, preventing instructions from stalling just because they happen to use the same variable name."),
Q("POSSIBLE QNS", "MEDIUM", "What is a 'Structural Hazard' in a pipeline?", ["A broken motherboard", "A conflict that occurs when two different pipeline stages attempt to use the exact same hardware resource (like the ALU or memory bus) at the exact same time", "A software crash", "A power failure"], "A conflict that occurs when two different pipeline stages attempt to use the exact same hardware resource (like the ALU or memory bus) at the exact same time", "CPUs solve this by duplicating hardware, such as having a separate L1 Cache for Instructions and a separate L1 Cache for Data."),
Q("POSSIBLE QNS", "HARD", "What is the difference between 'Scalar' and 'Superscalar'?", ["There is no difference", "A scalar processor executes one instruction per clock cycle; a superscalar processor has multiple execution units and can issue and execute multiple independent instructions per clock cycle", "Scalar is for text, superscalar for video", "Superscalar is slower"], "A scalar processor executes one instruction per clock cycle; a superscalar processor has multiple execution units and can issue and execute multiple independent instructions per clock cycle", "Superscalar is how modern CPUs achieve incredibly high performance, acting like a multi-lane highway instead of a single-lane road."),
Q("POSSIBLE QNS", "EASY", "What is a 'Clock Driven' device?", ["A physical clock", "A device, like a microprocessor, whose operations are entirely synchronized and stepped forward by an electronic oscillator pulse", "A device that tells time", "A stop watch"], "A device, like a microprocessor, whose operations are entirely synchronized and stepped forward by an electronic oscillator pulse", "Nothing in a CPU happens without a clock pulse pushing it forward."),
Q("POSSIBLE QNS", "MEDIUM", "What are the stages of a classic 5-stage pipeline?", ["Start, Run, Stop, Save, Exit", "Instruction Fetch (IF), Instruction Decode (ID), Execution (EX), Memory Access (MEM), Write Back (WB)", "Read, Write, Execute, Delete, Copy", "Load, Process, Output, Print, Save"], "Instruction Fetch (IF), Instruction Decode (ID), Execution (EX), Memory Access (MEM), Write Back (WB)", "This RISC-based 5-stage pipeline is the foundational concept taught in all computer architecture courses."),
Q("POSSIBLE QNS", "HARD", "What is the impact of a 'Control Hazard'?", ["It destroys the control unit", "Also known as a branch hazard, it occurs when the pipeline fetches instructions based on a sequence, but an IF statement or JUMP changes the sequence, rendering the fetched instructions useless", "It stops the power supply", "It formats the disk"], "Also known as a branch hazard, it occurs when the pipeline fetches instructions based on a sequence, but an IF statement or JUMP changes the sequence, rendering the fetched instructions useless", "This results in a 'pipeline flush', wiping out the assembly line and starting over from the new address, wasting significant time.")
];

async function insertUnit4Part2() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = ca_unit4_part2.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} questions for CA Unit 4 Part 2.`);
        } else {
            console.log("No new questions for CA Unit 4 Part 2 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit4Part2();
