const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a49ecb638bb37720e3e9194"; // COMPUTER ARCHITECTURE AND ASSEMBLY PROGRAMMING LANGUAGE

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const ca_unit1_part3 = [
// ╔══════════════════════════════════╗
// ║           QUIZ (8 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "Which CPU register always holds the address of the next instruction to be fetched?", ["Accumulator (AC)", "Program Counter (PC)", "Instruction Register (IR)", "Stack Pointer (SP)"], "Program Counter (PC)", "The Program Counter (PC) acts as a bookmark, keeping track of exactly where the CPU is in the execution of a program."),
Q("QUIZ", "MEDIUM", "What is meant by a 'Memory Transfer'?", ["Moving data via a USB cable", "The movement of data between CPU registers and main memory (RAM)", "Transferring data over the internet", "Burning data to a CD"], "The movement of data between CPU registers and main memory (RAM)", "Memory transfers are required whenever the CPU needs to read from or write back to the system's main RAM."),
Q("QUIZ", "HARD", "In digital logic, what does an 'XOR' micro operation typically do when applied to a register against itself?", ["It doubles the value", "It clears the register to all zeros", "It sets the register to all ones", "It leaves the register unchanged"], "It clears the register to all zeros", "In binary logic, XORing any value with itself results in 0 (e.g., 1 XOR 1 = 0, 0 XOR 0 = 0). It is a fast way to clear a register."),
Q("QUIZ", "MEDIUM", "What is the function of 'Control Bits' in an instruction format?", ["To set the length of the cable", "To specify other control signals, such as whether an instruction should be executed conditionally based on condition codes", "To adjust the monitor brightness", "To allocate IP addresses"], "To specify other control signals, such as whether an instruction should be executed conditionally based on condition codes", "Control bits add extra modifiers to an instruction, telling the CPU to only execute it if a certain flag (like the Zero flag) is set."),
Q("QUIZ", "EASY", "Which component performs mathematical operations like addition and subtraction?", ["Control Unit", "Arithmetic Logic Unit (ALU)", "Memory Management Unit", "Register File"], "Arithmetic Logic Unit (ALU)", "The ALU contains the digital circuits (like adders and subtractors) required for math."),
Q("QUIZ", "HARD", "What does 'Instruction Decoding' entail?", ["Displaying text on the screen", "Translating the binary opcode into the specific sequence of internal control signals needed to execute the operation", "Translating Python to C++", "Decompressing a ZIP file"], "Translating the binary opcode into the specific sequence of internal control signals needed to execute the operation", "Decoding is the critical step where the Control Unit figures out what the machine code actually means in terms of hardware action."),
Q("QUIZ", "MEDIUM", "Why is 'Cache Memory' important for processor organization?", ["It stores the operating system", "It provides faster access to frequently used data than fetching it directly from slower main memory (RAM)", "It connects to the internet", "It cools down the CPU"], "It provides faster access to frequently used data than fetching it directly from slower main memory (RAM)", "The CPU is much faster than RAM. Cache acts as a high-speed middleman so the CPU doesn't have to wait."),
Q("QUIZ", "HARD", "Which addressing mode uses the value in the Program Counter (PC) plus an offset to find the operand?", ["Base-Register Mode", "Relative Mode", "Direct Mode", "Immediate Mode"], "Relative Mode", "Relative addressing calculates the target address relative to the current instruction pointer, which is essential for position-independent code."),

// ╔══════════════════════════════════╗
// ║         EXERCISE (8 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "What does LIFO stand for in relation to a memory stack?", ["Last In, First Out", "Long Integer, Fast Output", "Logical Input, Functional Output", "Lost In Formatting Options"], "Last In, First Out", "LIFO means that the last piece of data pushed onto the stack is the first piece to be popped off."),
Q("EXERCISE", "MEDIUM", "Which architecture is 'Compiler-Friendly' due to its simple instruction set?", ["CISC", "Von Neumann", "RISC", "Harvard"], "RISC", "RISC architectures provide simple, uniform instructions that allow compilers to optimize code schedules very efficiently."),
Q("EXERCISE", "HARD", "In a 'Register Set with a Common ALU', what is a potential drawback?", ["It takes up too much physical space", "Potential for contention, as multiple instructions may require the single ALU simultaneously, leading to delays", "It cannot perform arithmetic", "It requires too much power"], "Potential for contention, as multiple instructions may require the single ALU simultaneously, leading to delays", "A single shared ALU acts as a bottleneck if the CPU attempts superscalar execution (doing multiple math operations at once)."),
Q("EXERCISE", "MEDIUM", "What is an 'Operand'?", ["The mathematical operation to perform", "The data or memory address on which the operation specified by the opcode is performed", "The length of the instruction", "The clock speed of the CPU"], "The data or memory address on which the operation specified by the opcode is performed", "Operands are the targets of the instruction. For example, in 'ADD A, B', A and B are the operands."),
Q("EXERCISE", "HARD", "What does 'Hardware Limitations' refer to regarding the stack limit?", ["The physical weight of the CPU", "Constraints imposed by the architecture, such as the maximum size of the stack pointer register or memory addressing limits", "The number of USB ports", "The speed of the fans"], "Constraints imposed by the architecture, such as the maximum size of the stack pointer register or memory addressing limits", "If the stack pointer is a 16-bit register, the stack cannot physically exceed 64KB, regardless of how much RAM is installed."),
Q("EXERCISE", "EASY", "Which register holds the results of arithmetic operations?", ["Program Counter (PC)", "Accumulator (AC)", "Instruction Register (IR)", "Stack Pointer (SP)"], "Accumulator (AC)", "The Accumulator accumulates the results of sequential math operations in the ALU."),
Q("EXERCISE", "MEDIUM", "What does the 'Instruction Set Architecture (ISA)' define?", ["The shape of the computer case", "The opcodes, addressing modes, and registers supported by the CPU that programmers use to write machine code", "The color of the motherboard", "The cooling system"], "The opcodes, addressing modes, and registers supported by the CPU that programmers use to write machine code", "The ISA is the fundamental software-hardware interface. It dictates what binary commands the CPU understands."),
Q("EXERCISE", "HARD", "How does a 'Micro-programmed Control Unit' operate?", ["By using physical wiring for every instruction", "The opcode is used as an index into a control memory (ROM) to fetch a specific microinstruction sequence that controls the hardware", "By connecting to a cloud server", "By using a mechanical switch"], "The opcode is used as an index into a control memory (ROM) to fetch a specific microinstruction sequence that controls the hardware", "It works like a small program inside the CPU. The opcode triggers a mini-routine of microcode that executes the instruction step-by-step."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "What is the purpose of the 'Control Bus'?", ["To carry memory addresses", "To carry data between RAM and CPU", "To carry control signals that coordinate operations, like read/write commands and interrupt requests", "To provide power"], "To carry control signals that coordinate operations, like read/write commands and interrupt requests", "The Control Bus is how the Control Unit tells the rest of the computer what to do and when to do it."),
Q("CAT 1", "MEDIUM", "What happens during a 'Shift Micro Operation'?", ["Data is moved to the hard drive", "Bits of a binary number are shifted left or right, often used for multiplication or division by powers of two", "Data is erased", "The CPU enters sleep mode"], "Bits of a binary number are shifted left or right, often used for multiplication or division by powers of two", "Shifting left by one bit multiplies the number by 2; shifting right divides it by 2. This is much faster than full ALU multiplication."),
Q("CAT 1", "HARD", "Which addressing mode requires the CPU to first fetch an address from a register, and then go to memory to find the actual operand?", ["Immediate Mode", "Direct Mode", "Indirect Mode", "Relative Mode"], "Indirect Mode", "Indirect mode is like a treasure hunt. The register gives you a clue (an address), and you have to go to that address to find the real data."),
Q("CAT 1", "EASY", "What component fetches instructions from memory and decodes them?", ["Arithmetic Logic Unit (ALU)", "Control Unit (CU)", "Memory Stack", "Cache Memory"], "Control Unit (CU)", "The Control Unit is the manager of the CPU, handling the fetch-decode-execute cycle."),
Q("CAT 1", "MEDIUM", "In a CPU, what is 'Pipelining'?", ["Using water to cool the processor", "Breaking down instruction execution into multiple overlapping stages to improve throughput", "Storing data permanently on a disk", "Encrypting memory"], "Breaking down instruction execution into multiple overlapping stages to improve throughput", "Pipelining allows the CPU to fetch instruction 3, while decoding instruction 2, and executing instruction 1, all at the same time."),
Q("CAT 1", "HARD", "What is the main advantage of a 'Hardwired Control Unit'?", ["It is easy to modify later", "It executes instructions faster because control signals are generated directly by physical logic gates without fetching microcode", "It supports very complex instruction sets easily", "It uses less power than a lightbulb"], "It executes instructions faster because control signals are generated directly by physical logic gates without fetching microcode", "Hardwired units sacrifice flexibility for raw speed, as electrical signals travel through physical gates almost instantly."),
Q("CAT 1", "MEDIUM", "What is the function of 'Status Flags' (Condition Codes)?", ["To store passwords", "To hold individual bits (like zero, carry, overflow) that represent the outcome of the last ALU operation for decision making", "To show the CPU load", "To change the monitor resolution"], "To hold individual bits (like zero, carry, overflow) that represent the outcome of the last ALU operation for decision making", "Flags are essential for conditional logic. When you write 'if (x == y)', the CPU subtracts y from x and checks the Zero flag."),
Q("CAT 1", "HARD", "How does a 'Binary Adder' differ from a 'Binary Subtractor'?", ["A binary adder is larger", "A binary adder computes the sum of two numbers, while a subtractor typically uses borrow logic or two's complement to find the difference", "A binary adder is used for text", "A subtractor is only for floating point"], "A binary adder computes the sum of two numbers, while a subtractor typically uses borrow logic or two's complement to find the difference", "While physically similar, subtractors have to handle the concept of borrowing from the next significant bit, similar to manual decimal subtraction."),
Q("CAT 1", "MEDIUM", "What does 'Direct Addressing Mode' mean?", ["The operand is a register", "The instruction provides the exact memory address where the operand is located", "The operand is hidden", "The operand is the next instruction"], "The instruction provides the exact memory address where the operand is located", "In direct mode, the address is explicitly written in the instruction, e.g., 'Load data from address 1000'."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "What does 'CISC' stand for?", ["Computer Instruction Standard Code", "Complex Instruction Set Computing", "Central Internal System Cache", "Control Instruction Signal Circuit"], "Complex Instruction Set Computing", "CISC architectures are designed to have rich, complex instructions that do a lot of work in a single command."),
Q("CAT 2", "MEDIUM", "What is the role of the 'Instruction Register' (IR)?", ["To point to the next instruction", "To hold the currently executing instruction that was just fetched from memory so it can be decoded", "To perform arithmetic", "To manage the stack"], "To hold the currently executing instruction that was just fetched from memory so it can be decoded", "The IR acts as a holding pen for the instruction while the Control Unit figures out what to do with it."),
Q("CAT 2", "HARD", "What does 'Vector Processing' or 'SIMD' involve?", ["Executing one instruction on one piece of data", "A single instruction operating on multiple data elements simultaneously, useful for graphics and array math", "Storing data on magnetic tape", "Using multiple CPUs for one math problem"], "A single instruction operating on multiple data elements simultaneously, useful for graphics and array math", "SIMD (Single Instruction, Multiple Data) is crucial for modern applications like video rendering, where the exact same math is applied to thousands of pixels at once."),
Q("CAT 2", "EASY", "Which bus is used to transfer actual binary data between components?", ["Address Bus", "Control Bus", "Data Bus", "Universal Serial Bus"], "Data Bus", "The data bus carries the actual payloads of information between the CPU, RAM, and peripherals."),
Q("CAT 2", "MEDIUM", "What is a 'Stack Overflow'?", ["When the CPU overheats", "When a program exceeds the stack size limit, often due to deep recursive function calls, causing a crash", "When the hard drive is full", "When a network connection is lost"], "When a program exceeds the stack size limit, often due to deep recursive function calls, causing a crash", "Because the stack has a fixed size in memory, pushing too many items (like infinite recursion) causes it to overflow into memory it shouldn't touch."),
Q("CAT 2", "HARD", "What happens during an 'Interrupt Cycle'?", ["The CPU stops working permanently", "The CPU saves its current state, services a high-priority request from an external device or internal source, and then restores its state", "The program is deleted", "The RAM is cleared"], "The CPU saves its current state, services a high-priority request from an external device or internal source, and then restores its state", "Interrupts are essential for multitasking and hardware interaction. The CPU must save the PC and registers before jumping to the interrupt handler."),
Q("CAT 2", "MEDIUM", "What is the function of the 'Stack Pointer' (SP)?", ["To measure CPU speed", "To keep track of the top of the stack in memory, updating automatically during push and pop operations", "To point to the hard drive", "To store graphics data"], "To keep track of the top of the stack in memory, updating automatically during push and pop operations", "The SP tells the CPU exactly where in memory the current top of the LIFO stack is located."),
Q("CAT 2", "HARD", "Which architecture typically uses a 'Load/Store' model where operations only happen on registers?", ["Von Neumann", "CISC", "RISC", "Harvard"], "RISC", "In RISC, if you want to add two numbers in RAM, you must LOAD them to registers, ADD them in the CPU, and STORE the result back to RAM. You cannot add them directly in RAM."),
Q("CAT 2", "EASY", "What is 'Cache Memory' used for?", ["Permanent file storage", "Storing frequently accessed data close to the CPU to reduce average memory access time", "Cooling the processor", "Connecting to the internet"], "Storing frequently accessed data close to the CPU to reduce average memory access time", "Cache acts as a high-speed buffer between the ultra-fast CPU and the relatively slow main RAM."),

// ╔══════════════════════════════════╗
// ║            UE (8 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "What is the 'Central Processing Unit' (CPU) often referred to as?", ["The hard drive of the computer", "The brain of the computer", "The power supply", "The motherboard"], "The brain of the computer", "The CPU is the primary component that executes instructions and coordinates all other hardware."),
Q("UE", "MEDIUM", "In 'Immediate Addressing Mode', where is the operand found?", ["In a CPU register", "Directly within the instruction itself", "In main memory", "On the hard drive"], "Directly within the instruction itself", "Immediate mode means the data value (like the number 5) is hardcoded directly into the machine code instruction, requiring no extra memory lookups."),
Q("UE", "HARD", "What is 'Branch Prediction' in modern processor organization?", ["A technique to predict hardware failure", "Speculative execution of conditional branches to prevent the execution pipeline from stalling", "A method for encrypting data", "A way to increase hard drive capacity"], "Speculative execution of conditional branches to prevent the execution pipeline from stalling", "If a CPU encounters an 'if' statement, it tries to guess the outcome and execute the code early. If wrong, it flushes the pipeline and starts over."),
Q("UE", "MEDIUM", "What is the purpose of 'Base-Register Addressing Mode'?", ["To store data permanently", "To store a base address in a register and add an offset to it, commonly used for addressing data structures like arrays", "To bypass the CPU", "To change the clock speed"], "To store a base address in a register and add an offset to it, commonly used for addressing data structures like arrays", "This mode is perfect for arrays; the base register holds the start of the array, and the offset acts as the array index."),
Q("UE", "HARD", "What is a '4-bit Arithmetic Circuit'?", ["A circuit that only does multiplication", "A combinational logic circuit implemented using gates that can perform addition, subtraction, and incrementation on 4-bit binary numbers", "A small battery", "A type of network cable"], "A combinational logic circuit implemented using gates that can perform addition, subtraction, and incrementation on 4-bit binary numbers", "This circuit forms the core of an ALU, using full adders and multiplexers to select which math operation to perform on a 4-bit word."),
Q("UE", "EASY", "What principle does the stack use to manage local variables and function calls?", ["FIFO", "LIFO (Last In, First Out)", "Random Access", "Sequential Access"], "LIFO (Last In, First Out)", "Because of LIFO, when a function calls another function, the newest function's variables are on top and will be removed first when it returns."),
Q("UE", "MEDIUM", "Why do CISC architectures often require 'Multi-Cycle Execution'?", ["Because they are broken", "Because their instructions can perform complex operations or directly access memory, which takes several clock ticks to complete", "Because they use old wires", "Because the clock is too fast"], "Because their instructions can perform complex operations or directly access memory, which takes several clock ticks to complete", "A single CISC instruction might involve fetching an address, doing math on it, and saving it back—which physically requires multiple clock cycles to step through."),
Q("UE", "HARD", "What is the role of the 'Memory Management Unit' (MMU)?", ["To format hard drives", "To translate virtual addresses generated by the CPU into physical addresses in main memory and handle memory protection", "To delete old files", "To upgrade RAM size"], "To translate virtual addresses generated by the CPU into physical addresses in main memory and handle memory protection", "The MMU ensures that program A cannot accidentally read or write to the memory space belonging to program B, providing system stability."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (8 Qns)       ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "What does 'RTL' stand for?", ["Register Transfer Language", "Real Time Loader", "Random Transfer Logic", "Right To Left"], "Register Transfer Language", "RTL is used to describe the exact micro-operations and data flow between registers in a digital system."),
Q("POSSIBLE QNS", "MEDIUM", "What is the main function of 'Index Registers' (IX, IY)?", ["To hold the program counter", "To hold memory addresses, often used as offsets in indexed addressing modes for arrays and loops", "To store passwords", "To measure CPU temperature"], "To hold memory addresses, often used as offsets in indexed addressing modes for arrays and loops", "Index registers are specialized general-purpose registers that are incredibly useful for iterating through blocks of memory."),
Q("POSSIBLE QNS", "HARD", "How does a 'Micro-programmed Control Unit' differ from a 'Hardwired' one in terms of modification?", ["It cannot be modified", "It is easier to modify because you only need to update the micro-program stored in ROM, rather than redesigning physical hardware circuits", "It requires a soldering iron to change", "It changes itself randomly"], "It is easier to modify because you only need to update the micro-program stored in ROM, rather than redesigning physical hardware circuits", "This flexibility allows chip makers to fix logic bugs in CPUs by releasing microcode updates via BIOS patches."),
Q("POSSIBLE QNS", "MEDIUM", "In processor organization, what does the 'Opcode' field of an instruction do?", ["It holds the actual data", "It specifies the operation to be performed, such as addition or load", "It determines the color of the output", "It connects to the internet"], "It specifies the operation to be performed, such as addition or load", "The Opcode (Operation Code) is the verb of the instruction, telling the CPU what action to take on the operands."),
Q("POSSIBLE QNS", "HARD", "What is the significance of the 'Indirect Cycle' during instruction execution?", ["It speeds up the CPU", "It is an extra cycle needed to fetch an effective address from memory when an instruction uses indirect addressing", "It shuts down the computer", "It empties the cache"], "It is an extra cycle needed to fetch an effective address from memory when an instruction uses indirect addressing", "When using indirect addressing, the CPU must read memory twice: once to get the pointer, and again to get the actual data."),
Q("POSSIBLE QNS", "EASY", "Which bus dictates how much total memory a CPU can address?", ["Data Bus", "Control Bus", "Address Bus", "USB"], "Address Bus", "The number of lines on the Address Bus determines the maximum physical memory space. 32 lines = 4GB, 64 lines = Exabytes."),
Q("POSSIBLE QNS", "MEDIUM", "What is the role of 'Temporary Registers'?", ["To permanently store the OS", "To hold intermediate results during complex arithmetic and logical operations before the final answer is calculated", "To store the user's files", "To connect to Bluetooth"], "To hold intermediate results during complex arithmetic and logical operations before the final answer is calculated", "When executing a complex instruction, the CPU uses temp registers (invisible to the programmer) to hold halfway answers."),
Q("POSSIBLE QNS", "HARD", "What is a major advantage of 'RISC' architecture regarding pipelining?", ["It cannot use pipelining", "Because instructions are simple and execute in a single cycle, the architecture is inherently suited for highly efficient pipelining", "It requires huge amounts of RAM", "It uses complicated microcode"], "Because instructions are simple and execute in a single cycle, the architecture is inherently suited for highly efficient pipelining", "Since every RISC instruction takes roughly the same amount of time to execute, they flow through the pipeline stages perfectly without stalling.")
];

async function insertUnit1Part3() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = ca_unit1_part3.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} part 3 questions for CA Unit 1.`);
        } else {
            console.log("No new part 3 questions for CA Unit 1 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit1Part3();
