const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a49ecb638bb37720e3e9194"; // COMPUTER ARCHITECTURE AND ASSEMBLY PROGRAMMING LANGUAGE

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const ca_unit3_part2 = [
// ╔══════════════════════════════════╗
// ║           QUIZ (8 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "Which type of memory is specifically designed to be portable and is commonly used in smartphones and digital cameras?", ["Magnetic Tape", "SD Cards (Secure Digital Cards)", "DDR4 RAM", "L1 Cache"], "SD Cards (Secure Digital Cards)", "SD cards use compact flash memory to provide durable, portable storage for mobile devices."),
Q("QUIZ", "MEDIUM", "What does 'EPROM' allow that standard PROM does not?", ["It allows the chip to run faster", "It allows users to erase and reprogram the memory multiple times using ultraviolet (UV) light", "It allows continuous power without overheating", "It allows the memory to become volatile"], "It allows users to erase and reprogram the memory multiple times using ultraviolet (UV) light", "EPROM was a major breakthrough because developers didn't have to throw away the chip every time they wanted to update the firmware."),
Q("QUIZ", "HARD", "In cache mapping, what is 'Direct Mapping'?", ["Connecting the cache directly to the hard drive", "A technique where each block of main memory is rigidly mapped to one specific cache line based on the least significant bits of the address", "Mapping the cache over a network", "Mapping cache to the GPU"], "A technique where each block of main memory is rigidly mapped to one specific cache line based on the least significant bits of the address", "While simple and fast to check, direct mapping suffers heavily from cache conflicts if a program alternates between two memory addresses that map to the exact same cache line."),
Q("QUIZ", "MEDIUM", "What is the role of the 'Data Bus' in memory architecture?", ["To control the power supply", "To carry the actual binary data being read from or written to the memory", "To carry the memory addresses", "To check for errors"], "To carry the actual binary data being read from or written to the memory", "The width of the data bus determines how many bits (e.g., 64 bits) can be transferred between RAM and the CPU in a single operation."),
Q("QUIZ", "EASY", "What does 'Volatile Memory' mean?", ["Memory that explodes", "Memory that loses its contents when the power is turned off", "Memory that cannot be erased", "Memory that is extremely slow"], "Memory that loses its contents when the power is turned off", "RAM is volatile, which is why you must save your documents to a non-volatile hard drive before shutting down the computer."),
Q("QUIZ", "HARD", "How does a 'Solid State Drive' (SSD) store data?", ["Using rotating magnetic platters", "Using NAND flash memory chips with no moving parts, providing fast read/write speeds and high durability", "Using optical lasers to burn pits in plastic", "Using long ribbons of magnetic tape"], "Using NAND flash memory chips with no moving parts, providing fast read/write speeds and high durability", "Because there is no mechanical read/write head to move, SSDs have near-zero seek time, making them vastly faster than HDDs."),
Q("QUIZ", "MEDIUM", "What is the primary function of the 'Instruction Pointer' (or Program Counter) register?", ["To perform addition", "To store the address of the next instruction to be executed by the CPU", "To store the result of the ALU", "To point to the top of the stack"], "To store the address of the next instruction to be executed by the CPU", "This register ensures the CPU executes the program in the correct sequence."),
Q("QUIZ", "HARD", "What is 'Memory-Mapped I/O'?", ["Storing memory on a disk map", "An architecture where I/O devices are treated exactly like memory locations, using the same address space and memory instructions", "A visual map of the RAM", "A type of cache mapping"], "An architecture where I/O devices are treated exactly like memory locations, using the same address space and memory instructions", "Instead of needing special IN/OUT commands, the CPU just writes to a specific memory address, and the hardware intercepts that signal and sends it to the printer or screen."),

// ╔══════════════════════════════════╗
// ║         EXERCISE (8 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "Which storage medium provides the largest capacity at the absolute lowest cost per gigabyte, but is extremely slow?", ["Solid State Drives (SSDs)", "Magnetic Tapes (Tertiary Storage)", "DDR5 RAM", "USB Flash Drives"], "Magnetic Tapes (Tertiary Storage)", "Magnetic tapes are still heavily used by enterprise servers and cloud providers for deep archival backups due to their incredible cost-efficiency."),
Q("EXERCISE", "MEDIUM", "What is the main advantage of 'Virtual Memory'?", ["It makes the hard drive spin faster", "It provides the illusion of having a much larger main memory (RAM) than physically exists, allowing larger or multiple programs to run concurrently", "It prevents all computer viruses", "It turns ROM into RAM"], "It provides the illusion of having a much larger main memory (RAM) than physically exists, allowing larger or multiple programs to run concurrently", "Without virtual memory, if you had 4GB of RAM, you could only run exactly 4GB of programs. Virtual memory swaps inactive parts to the disk."),
Q("EXERCISE", "HARD", "What does a 'Page Replacement Algorithm' like LFU do?", ["It deletes the operating system", "It decides which page to evict from RAM to disk when physical memory is full, specifically choosing the 'Least Frequently Used' page", "It copies the RAM to a USB", "It formats the hard drive"], "It decides which page to evict from RAM to disk when physical memory is full, specifically choosing the 'Least Frequently Used' page", "LFU keeps track of how many times a page is accessed. A page accessed only once is evicted before a page accessed 100 times."),
Q("EXERCISE", "MEDIUM", "What is 'Dynamic RAM' (DRAM) and why must it be 'refreshed'?", ["It is a hard drive that needs spinning", "It is volatile memory that stores bits in tiny capacitors that slowly leak charge, requiring periodic electrical refreshing to maintain data integrity", "It is a cache memory that runs too fast", "It is a read-only memory"], "It is volatile memory that stores bits in tiny capacitors that slowly leak charge, requiring periodic electrical refreshing to maintain data integrity", "DRAM is cheap and dense, but the constant need to refresh the capacitors thousands of times a second is why it's called 'Dynamic'."),
Q("EXERCISE", "EASY", "What type of data access does a 'Hard Disk Drive' (HDD) primarily offer?", ["Sequential Access only", "Random Access (though slower than RAM due to physical seek times)", "Read-Only Access", "Write-Once Access"], "Random Access (though slower than RAM due to physical seek times)", "While not as instant as solid-state RAM, the read head of an HDD can move to any sector on the platter directly, making it random access."),
Q("EXERCISE", "HARD", "How does 'Write-Through' cache policy impact performance?", ["It is the fastest method possible", "It ensures high data consistency by writing to both cache and RAM simultaneously, but it incurs a performance penalty due to high memory bus traffic", "It prevents data from being written", "It only writes to the hard drive"], "It ensures high data consistency by writing to both cache and RAM simultaneously, but it incurs a performance penalty due to high memory bus traffic", "Because every write must wait for the slow RAM, Write-Through is safer against power failure but much slower than Write-Back."),
Q("EXERCISE", "MEDIUM", "What is the role of 'Status Flags' in CPU registers?", ["To store the user's password", "To indicate the outcome of arithmetic or logical operations, such as whether a result was zero, negative, or overflowed", "To control the cooling fan", "To assign IP addresses"], "To indicate the outcome of arithmetic or logical operations, such as whether a result was zero, negative, or overflowed", "These flags are crucial for 'IF' statements. The CPU checks the Zero flag to decide if it should jump to a different part of the code."),
Q("EXERCISE", "HARD", "What is the function of the 'Memory Management Unit' (MMU)?", ["To format disk drives", "To translate logical (virtual) addresses generated by the CPU into physical addresses in RAM, and to enforce memory protection rules", "To clean the cache", "To upgrade the RAM capacity"], "To translate logical (virtual) addresses generated by the CPU into physical addresses in RAM, and to enforce memory protection rules", "The MMU is the hardware gatekeeper. It performs the complex math to look up the Page Table instantly on every memory access."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "Which of the following is considered 'Primary Memory'?", ["Hard Disk Drive", "Main Memory (RAM)", "USB Flash Drive", "Magnetic Tape"], "Main Memory (RAM)", "RAM is the primary workspace for the CPU. Secondary memory (like HDDs) is for long-term storage."),
Q("CAT 1", "MEDIUM", "What is a 'Cache Miss'?", ["When the CPU crashes", "When the CPU looks for data in the cache but it is not there, forcing the CPU to fetch it from the much slower main memory", "When the cache deletes data", "When the cache is too small"], "When the CPU looks for data in the cache but it is not there, forcing the CPU to fetch it from the much slower main memory", "A high cache miss rate severely degrades computer performance. Good software algorithms are written to maximize cache hits."),
Q("CAT 1", "HARD", "In Virtual Memory, what happens during a 'Page Fault'?", ["The computer reboots", "The MMU realizes the requested virtual page is not in physical RAM, triggers an interrupt, and the OS fetches the required page from the hard drive (swap space)", "The RAM physically breaks", "The page is deleted permanently"], "The MMU realizes the requested virtual page is not in physical RAM, triggers an interrupt, and the OS fetches the required page from the hard drive (swap space)", "A page fault is an expensive operation time-wise, as reading from a hard drive is thousands of times slower than reading from RAM."),
Q("CAT 1", "EASY", "What does 'ROM' stand for?", ["Read-Only Memory", "Random Operator Mode", "Running Object Memory", "Rapid Online Memory"], "Read-Only Memory", "ROM contains firmware (like the BIOS) that the computer needs to boot up, which shouldn't be casually erased or modified."),
Q("CAT 1", "MEDIUM", "What characterizes 'Optical Discs' like CDs, DVDs, and Blu-rays?", ["They use magnetic tape", "They use laser technology to read and write data encoded as microscopic pits on a reflective plastic layer", "They use volatile flash memory", "They are built into the CPU"], "They use laser technology to read and write data encoded as microscopic pits on a reflective plastic layer", "The laser reads the transition between pits and lands as binary data. A Blu-ray uses a finer blue laser to pack pits closer together, offering more capacity."),
Q("CAT 1", "HARD", "How does 'Segmented-Page Mapping' work?", ["It divides memory randomly", "It divides memory logically into segments (code, data, stack), and then divides each segment physically into fixed-size pages to combine the benefits of both approaches", "It uses only magnetic tapes", "It maps memory to the cloud"], "It divides memory logically into segments (code, data, stack), and then divides each segment physically into fixed-size pages to combine the benefits of both approaches", "Segmentation provides logical protection (you can't execute the data segment), while paging prevents physical memory fragmentation."),
Q("CAT 1", "MEDIUM", "What is 'EEPROM' commonly known as in modern portable devices?", ["Magnetic Disk", "Flash Memory (like in USB drives and SSDs)", "SRAM", "DDR RAM"], "Flash Memory (like in USB drives and SSDs)", "Modern Flash memory is just a dense, highly optimized form of EEPROM that allows data to be erased and written in large blocks electrically."),
Q("CAT 1", "HARD", "What is the primary difference between 'L1 Cache' and 'L3 Cache'?", ["L1 is for audio, L3 is for video", "L1 is the smallest and fastest cache located directly on the CPU core, while L3 is larger, slightly slower, and often shared among multiple cores", "L1 is on the hard drive", "L3 is volatile, L1 is non-volatile"], "L1 is the smallest and fastest cache located directly on the CPU core, while L3 is larger, slightly slower, and often shared among multiple cores", "The memory hierarchy dictates that as you move further from the CPU execution unit, memory gets larger but slower."),
Q("CAT 1", "EASY", "Which bus specifies the exact location in RAM that the CPU wants to access?", ["Data Bus", "Address Bus", "Control Bus", "USB"], "Address Bus", "If the CPU wants to read byte number 500, it puts the binary number 500 onto the Address Bus wires."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "What is the function of a 'USB Flash Drive'?", ["To cool the computer", "To act as a small, portable secondary storage device using flash memory for transferring files", "To upgrade RAM", "To act as the CPU"], "To act as a small, portable secondary storage device using flash memory for transferring files", "USB drives replaced floppy disks because they are faster, hold vastly more data, and have no moving parts."),
Q("CAT 2", "MEDIUM", "What does 'SRAM' use to store data bits, making it faster than DRAM?", ["Capacitors", "Bistable latching circuitry (flip-flops) that do not require periodic refreshing", "Magnetic platters", "Lasers"], "Bistable latching circuitry (flip-flops) that do not require periodic refreshing", "Because it doesn't leak charge like a capacitor, SRAM is incredibly fast and stable, perfect for CPU caches."),
Q("CAT 2", "HARD", "In Cache memory, what is 'Set-Associative Mapping'?", ["A method that maps everything to one spot", "A compromise between direct and fully associative mapping, dividing the cache into sets where a memory block can occupy any line within its specific set", "Mapping cache to the hard drive", "Mapping cache over Wi-Fi"], "A compromise between direct and fully associative mapping, dividing the cache into sets where a memory block can occupy any line within its specific set", "For example, in a 4-way set associative cache, a block of RAM maps to a specific set, but has 4 different 'slots' it can take within that set, reducing conflicts."),
Q("CAT 2", "EASY", "What does 'HDD' stand for?", ["High Density Disk", "Hard Disk Drive", "Hardware Data Device", "Hyper Drive Disk"], "Hard Disk Drive", "HDDs use spinning magnetic platters and mechanical actuator arms to read and write data."),
Q("CAT 2", "MEDIUM", "What is the purpose of 'Memory Protection' hardware?", ["To physically lock the RAM", "To ensure that processes cannot access memory regions they are not authorized to access (like the OS kernel), preventing crashes and malicious attacks", "To encrypt passwords", "To prevent overheating"], "To ensure that processes cannot access memory regions they are not authorized to access (like the OS kernel), preventing crashes and enhancing security", "Without memory protection, any buggy program could accidentally overwrite the operating system's memory, bringing down the whole computer."),
Q("CAT 2", "HARD", "What is the 'TLB' (Translation Lookaside Buffer)?", ["A buffer for video playback", "A specialized hardware cache inside the MMU that stores recently used virtual-to-physical address translations, skipping the need to search the Page Table in RAM", "A type of USB drive", "A hard drive cache"], "A specialized hardware cache inside the MMU that stores recently used virtual-to-physical address translations, skipping the need to search the Page Table in RAM", "Since reading the Page Table from RAM takes time, the TLB caches the answers. A TLB hit allows instant address translation."),
Q("CAT 2", "MEDIUM", "What is 'Cache Initialization'?", ["Formatting the hard drive", "The process of clearing the cache memory and loading it with data from main memory, usually during system boot-up", "Deleting the OS", "Connecting to a network"], "The process of clearing the cache memory and loading it with data from main memory, usually during system boot-up", "Initialization ensures the cache doesn't contain garbage data left over from a previous power state."),
Q("CAT 2", "HARD", "How does 'Write-Back' cache differ from 'Write-Through'?", ["Write-back writes to the hard drive", "Write-back writes data only to the fast cache initially, updating the slow main memory only when that specific cache line is evicted, improving performance", "Write-back cannot save data", "Write-back writes data backwards"], "Write-back writes data only to the fast cache initially, updating the slow main memory only when that specific cache line is evicted, improving performance", "This drastically reduces traffic on the memory bus, but requires a 'dirty bit' to track which cache lines have modified data that hasn't been saved to RAM yet."),
Q("CAT 2", "EASY", "Which principle dictates that memory hierarchy places faster, smaller memory closer to the CPU?", ["The Principle of Gravity", "The Principle of Locality", "The Principle of Least Privilege", "The Principle of Relativity"], "The Principle of Locality", "Programs spend 90% of their time executing 10% of their code. The hierarchy puts that 10% in the ultra-fast cache."),

// ╔══════════════════════════════════╗
// ║            UE (8 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "Which register temporarily holds data being actively processed by the ALU?", ["Program Counter (PC)", "General-Purpose Data Register / Accumulator", "Instruction Register (IR)", "Base Pointer (BP)"], "General-Purpose Data Register / Accumulator", "When you add 5 + 3, those numbers are loaded from RAM into data registers first, then fed into the ALU."),
Q("UE", "MEDIUM", "What does 'DDR' mean in modern RAM (DDR SDRAM)?", ["Direct Data Read", "Double Data Rate, meaning data is transferred on both the rising and falling edges of the clock cycle", "Dynamic Disk RAM", "Dual Drive Random"], "Double Data Rate, meaning data is transferred on both the rising and falling edges of the clock cycle", "Older SDRAM only transferred data on the rising edge. DDR effectively doubles the speed without increasing the clock frequency."),
Q("UE", "HARD", "What is the main drawback of 'Fully Associative Mapping' in Cache?", ["It causes too many cache misses", "While it offers maximum flexibility by letting a block go anywhere, the hardware required to search every cache line simultaneously for a hit is highly complex, slow, and expensive", "It cannot store binary data", "It only works with magnetic tape"], "While it offers maximum flexibility by letting a block go anywhere, the hardware required to search every cache line simultaneously for a hit is highly complex, slow, and expensive", "To achieve a cache hit in 1 nanosecond, a fully associative cache must compare the requested address against *every single tag* in the cache at the exact same time using massive comparator circuits."),
Q("UE", "MEDIUM", "What is 'PROM'?", ["A school dance", "Programmable Read-Only Memory; chips that can be programmed (written to) exactly once by the user using a special device", "A type of fast RAM", "A temporary cache file"], "Programmable Read-Only Memory; chips that can be programmed (written to) exactly once by the user using a special device", "PROMs use tiny fuses. The programmer burns (blows) the fuses to write the data permanently. It cannot be undone."),
Q("UE", "HARD", "What is 'Access Permissions' in the context of memory protection?", ["A password to turn on the PC", "Rules defined in the page table (like Read, Write, Execute) that the MMU enforces to prevent unauthorized operations on specific memory pages", "A firewall for the internet", "A way to encrypt files"], "Rules defined in the page table (like Read, Write, Execute) that the MMU enforces to prevent unauthorized operations on specific memory pages", "If a hacker uses a buffer overflow to inject malware into a data variable, the MMU will prevent the CPU from running it because that page is marked 'No-Execute'."),
Q("UE", "EASY", "Which secondary storage device uses lasers to read microscopic pits on a reflective surface?", ["Solid State Drive (SSD)", "Optical Discs (CD/DVD/Blu-ray)", "Magnetic Tape", "Hard Disk Drive (HDD)"], "Optical Discs (CD/DVD/Blu-ray)", "The laser reads the reflections off the 'pits' and 'lands' to decipher the binary data."),
Q("UE", "MEDIUM", "What does the 'Control Bus' transmit?", ["User passwords", "Various control signals like read/write commands, memory enable signals, and bus arbitration signals between the CPU and memory", "Audio and video data", "Power to the motherboard"], "Various control signals like read/write commands, memory enable signals, and bus arbitration signals between the CPU and memory", "It's the command channel. Even if the address and data are set, nothing happens until the Control Bus pulses the 'WRITE' signal."),
Q("UE", "HARD", "What happens when 'Cache Memory' experiences a 'Hit'?", ["The computer crashes", "The CPU finds the requested data immediately in the high-speed cache, avoiding the severe latency penalty of fetching it from main RAM", "The hard drive formats itself", "The data is deleted"], "The CPU finds the requested data immediately in the high-speed cache, avoiding the severe latency penalty of fetching it from main RAM", "A high cache hit ratio (e.g., 95%) is the primary reason modern computers feel fast despite having relatively slow RAM."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (8 Qns)       ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "What does 'Sequential Access' mean?", ["Accessing data instantly from anywhere", "Reading or writing data in a linear, ordered sequence, meaning you must pass through preceding data to reach your target", "Accessing data randomly", "Accessing data over Wi-Fi"], "Reading or writing data in a linear, ordered sequence, meaning you must pass through preceding data to reach your target", "Think of a VHS tape or cassette tape; you have to fast-forward to get to the middle."),
Q("POSSIBLE QNS", "MEDIUM", "What is the difference between 'Physical Address' and 'Logical Address'?", ["There is no difference", "A Physical Address is the actual hardware location in RAM, while a Logical (Virtual) Address is an illusion generated by the CPU and translated by the MMU", "Physical is for hard drives, Logical is for monitors", "Logical is faster"], "A Physical Address is the actual hardware location in RAM, while a Logical (Virtual) Address is an illusion generated by the CPU and translated by the MMU", "This abstraction allows the OS to move a program's RAM around physically without the program ever noticing."),
Q("POSSIBLE QNS", "HARD", "In page replacement algorithms, what is the 'FIFO' technique?", ["A networking protocol", "First-In-First-Out; the OS evicts the page that has been in physical memory the longest when it needs space for a new page from the disk", "A method for printing", "A graphics rendering technique"], "First-In-First-Out; the OS evicts the page that has been in physical memory the longest when it needs space for a new page from the disk", "While simple, FIFO can be inefficient because the 'oldest' page might be an important system library that is still being heavily used."),
Q("POSSIBLE QNS", "MEDIUM", "What is a 'Solid State Drive' (SSD)?", ["A drive made of liquid", "A secondary storage device that uses non-volatile NAND flash memory chips instead of spinning magnetic platters, offering vastly superior speed and durability", "A type of RAM that forgets data", "An optical disc format"], "A secondary storage device that uses non-volatile NAND flash memory chips instead of spinning magnetic platters, offering vastly superior speed and durability", "SSDs have revolutionized computing by eliminating the mechanical seek-time bottleneck of traditional hard drives."),
Q("POSSIBLE QNS", "HARD", "What is the primary flaw of 'Direct Mapping' in cache memory?", ["It is too expensive", "It suffers from 'Conflict Misses'; if two actively used memory blocks map to the exact same cache line, they will constantly evict each other (thrashing)", "It uses too much electricity", "It cannot store integers"], "It suffers from 'Conflict Misses'; if two actively used memory blocks map to the exact same cache line, they will constantly evict each other (thrashing)", "Because each block of RAM has exactly one rigid spot it can occupy in the cache, conflicts are highly likely."),
Q("POSSIBLE QNS", "EASY", "Which memory component is the largest in capacity but the slowest in speed in the memory hierarchy?", ["L1 Cache", "Tertiary Storage (Magnetic Tapes)", "RAM", "CPU Registers"], "Tertiary Storage (Magnetic Tapes)", "Tapes hold massive amounts of data (Terabytes per cartridge) very cheaply, but take minutes to seek to a specific file."),
Q("POSSIBLE QNS", "MEDIUM", "What does 'EPROM' stand for?", ["Erasable Programmable Read-Only Memory", "Electronic Power RAM", "External Processing ROM", "Encrypted Private ROM"], "Erasable Programmable Read-Only Memory", "It is identifiable by the small quartz window on the chip, which allows UV light in to erase the memory cells."),
Q("POSSIBLE QNS", "HARD", "What does 'Mask ROM' imply?", ["It is used for Halloween", "The data is permanently and physically etched into the silicon during the photolithographic manufacturing process using custom metal masks", "It is erasable", "It is used for encryption"], "The data is permanently and physically etched into the silicon during the photolithographic manufacturing process using custom metal masks", "This is the most secure and cheapest ROM for massive scale production, but completely inflexible once manufactured.")
];

async function insertUnit3Part2() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = ca_unit3_part2.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} questions for CA Unit 3 Part 2.`);
        } else {
            console.log("No new questions for CA Unit 3 Part 2 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit3Part2();
