const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a49ecb638bb37720e3e9194"; // COMPUTER ARCHITECTURE AND ASSEMBLY PROGRAMMING LANGUAGE

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const ca_unit2_part1 = [
// ╔══════════════════════════════════╗
// ║           QUIZ (8 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "What is the primary function of an I/O Interface?", ["To increase the clock speed of the CPU", "To provide a method for transferring information between internal storage and external I/O devices", "To cool down the hard drive", "To generate electric power"], "To provide a method for transferring information between internal storage and external I/O devices", "The I/O interface acts as a translator and buffer between the fast CPU/Memory and the slower external peripheral devices."),
Q("QUIZ", "MEDIUM", "What distinguishes 'Isolated I/O' from 'Memory-mapped I/O'?", ["Isolated I/O uses a completely different physical motherboard", "Isolated I/O has separate address spaces for memory and I/O devices, using special instructions like IN and OUT", "Memory-mapped I/O only works with RAM, not ROM", "Isolated I/O is slower and outdated"], "Isolated I/O has separate address spaces for memory and I/O devices, using special instructions like IN and OUT", "In Isolated I/O, memory addresses and I/O addresses are separate. In Memory-mapped I/O, they share the same address space and the same instructions (like LOAD/STORE)."),
Q("QUIZ", "HARD", "In asynchronous data transfer, what is the main disadvantage of 'Strobe Control'?", ["It requires too much power", "The source unit has no way of knowing if the destination unit actually received the data", "It is only compatible with USB 2.0", "It is too slow for modern CPUs"], "The source unit has no way of knowing if the destination unit actually received the data", "Strobe control uses a single control line to indicate data is ready, but it lacks an acknowledgment signal from the receiver, unlike handshaking."),
Q("QUIZ", "MEDIUM", "What is 'Handshaking' in data transfer?", ["A physical connection between two computers", "A two-way communication method where a 'Ready' signal is followed by an 'Acknowledge' signal", "A security protocol to encrypt data", "A type of memory allocation"], "A two-way communication method where a 'Ready' signal is followed by an 'Acknowledge' signal", "Handshaking ensures reliable data transfer by having the receiver confirm that it has successfully read the data before the sender sends the next byte."),
Q("QUIZ", "EASY", "Which mode of transfer requires the CPU to constantly check the status of a peripheral to see if it is ready?", ["Direct Memory Access (DMA)", "Programmed I/O", "Interrupt-initiated I/O", "Asynchronous serial transfer"], "Programmed I/O", "In Programmed I/O, the CPU executes a loop (polling) to continually check the I/O device's status flag, wasting significant CPU time."),
Q("QUIZ", "HARD", "What does a 'Vectored Interrupt' provide that a non-vectored interrupt does not?", ["More electrical power to the device", "The device supplies a specific branch address (vector) to the CPU, pointing directly to the specific Interrupt Service Routine", "A graphical vector image of the error", "Automatic error correction"], "The device supplies a specific branch address (vector) to the CPU, pointing directly to the specific Interrupt Service Routine", "In a vectored interrupt, the hardware tells the CPU exactly where the handler code is located, saving time. In non-vectored, the CPU must poll to find out which device interrupted."),
Q("QUIZ", "MEDIUM", "What is the primary role of a DMA (Direct Memory Access) controller?", ["To manage the display graphics", "To manage the transfer of blocks of data directly between an I/O device and memory without CPU intervention", "To calculate complex math equations", "To act as the system clock"], "To manage the transfer of blocks of data directly between an I/O device and memory without CPU intervention", "DMA frees up the CPU by taking control of the buses temporarily to transfer large amounts of data (like a file from a disk) straight to RAM."),
Q("QUIZ", "HARD", "What happens during a 'Cycle Stealing' DMA transfer?", ["The DMA steals power from the CPU", "The DMA controller transfers one data word at a time, momentarily pausing the CPU's access to the bus", "The CPU steals data from the hard drive", "The system clock skips a cycle"], "The DMA controller transfers one data word at a time, momentarily pausing the CPU's access to the bus", "In cycle stealing, the DMA takes control of the system bus for just a single clock cycle to transfer a byte, then gives it back to the CPU."),

// ╔══════════════════════════════════╗
// ║         EXERCISE (8 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "Which I/O command is used by the CPU to check if a peripheral device is ready, busy, or has an error?", ["Control command", "Status command", "Data Output command", "Data Input command"], "Status command", "A status command reads the status register of the I/O interface to determine the condition of the peripheral."),
Q("EXERCISE", "MEDIUM", "Why is an I/O Interface necessary between the CPU and peripherals?", ["Because peripherals are too small to plug in", "Because peripherals have different data formats, slower operating speeds, and different voltage levels compared to the CPU", "Because the CPU doesn't know how to read binary", "Because it is required by law"], "Because peripherals have different data formats, slower operating speeds, and different voltage levels compared to the CPU", "The interface acts as a crucial buffer and translator. The CPU is electronic and fast; peripherals are often electromechanical and slow."),
Q("EXERCISE", "HARD", "In 'Memory-mapped I/O', how does the CPU differentiate between accessing RAM and accessing an I/O device?", ["It uses special IN and OUT instructions", "It doesn't; it treats the I/O device register exactly like a memory address, relying on the address decoding logic to route the request", "It asks the user to confirm", "It uses the control bus exclusively"], "It doesn't; it treats the I/O device register exactly like a memory address, relying on the address decoding logic to route the request", "Memory-mapped I/O sacrifices some memory address space to map device registers, allowing any memory manipulation instruction to be used on I/O."),
Q("EXERCISE", "MEDIUM", "What does 'Asynchronous' mean in the context of data transfer?", ["The transfer happens instantly", "The timing of the data transfer is not governed by a common master clock; instead, control signals coordinate the transfer", "Data is sent backwards", "The CPU is turned off"], "The timing of the data transfer is not governed by a common master clock; instead, control signals coordinate the transfer", "Because the CPU and the peripheral have different clock speeds, asynchronous transfer uses strobes or handshaking rather than a shared clock pulse."),
Q("EXERCISE", "HARD", "What is the purpose of an 'Interrupt Controller' (like the 8259A)?", ["To stop the computer from overheating", "To manage multiple interrupt requests, prioritize them, and send a single interrupt signal to the CPU with the appropriate vector", "To convert AC power to DC", "To act as a firewall"], "To manage multiple interrupt requests, prioritize them, and send a single interrupt signal to the CPU with the appropriate vector", "The CPU only has one or two interrupt pins. The interrupt controller acts as a receptionist, prioritizing multiple devices that want the CPU's attention."),
Q("EXERCISE", "EASY", "Which transfer mode is best for transferring a massive 1GB video file from a hard drive to RAM?", ["Programmed I/O", "Interrupt-initiated I/O", "Direct Memory Access (DMA)", "Strobe Control"], "Direct Memory Access (DMA)", "DMA is specifically designed for high-speed, large-volume data transfers without wasting the CPU's time."),
Q("EXERCISE", "MEDIUM", "What is an 'I/O Processor' (IOP)?", ["A small chip inside the keyboard", "A dedicated processor with its own memory access that can execute I/O programs independently of the main CPU", "A cooling unit for the CPU", "A software driver"], "A dedicated processor with its own memory access that can execute I/O programs independently of the main CPU", "An IOP (sometimes called a channel) is a highly advanced I/O interface that acts almost like a mini-CPU exclusively for managing peripherals."),
Q("EXERCISE", "HARD", "In serial communication, what is the role of a UART (Universal Asynchronous Receiver-Transmitter)?", ["To generate graphics", "To convert parallel data from the CPU into a serial bit stream for transmission, and vice versa", "To amplify audio signals", "To connect to Wi-Fi"], "To convert parallel data from the CPU into a serial bit stream for transmission, and vice versa", "The CPU processes data in parallel (e.g., 8 bits at once), but serial cables send 1 bit at a time. The UART handles this conversion."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "Which I/O command actually sends data from the CPU to the peripheral?", ["Status command", "Control command", "Data Output command", "Data Input command"], "Data Output command", "This command takes data from the CPU (or memory) and writes it into the buffer register of the I/O interface."),
Q("CAT 1", "MEDIUM", "What is a 'Control Command' used for in an I/O Interface?", ["To move data", "To activate the peripheral and inform it what action to take (e.g., instructing a tape drive to rewind)", "To check for errors", "To format the hard drive"], "To activate the peripheral and inform it what action to take (e.g., instructing a tape drive to rewind)", "It is essentially an instruction meant specifically for the mechanical/electronic control logic of the peripheral device."),
Q("CAT 1", "HARD", "How does a 'Priority Interrupt' system handle simultaneous requests?", ["It crashes the system", "It uses hardware (like daisy-chaining) or software (polling order) to establish a hierarchy, ensuring the highest priority device is serviced first", "It services them in random order", "It ignores all requests until the CPU is idle"], "It uses hardware (like daisy-chaining) or software (polling order) to establish a hierarchy, ensuring the highest priority device is serviced first", "Devices like the system clock or hard drive usually have higher priority than a keyboard, so their interrupts are processed first if a conflict occurs."),
Q("CAT 1", "EASY", "What is 'Programmed I/O' heavily criticized for?", ["Being too complicated to program", "Wasting CPU time through continuous polling while waiting for a slow peripheral to be ready", "Using too much electricity", "Being too fast for the device"], "Wasting CPU time through continuous polling while waiting for a slow peripheral to be ready", "The CPU gets stuck in a 'while (!ready)' loop, unable to do any other useful work until the device responds."),
Q("CAT 1", "MEDIUM", "What must the CPU do before granting the bus to the DMA controller?", ["Turn off the power", "Complete its current instruction and place its address, data, and read/write lines into a high-impedance state (tri-state)", "Delete the cache", "Reboot the operating system"], "Complete its current instruction and place its address, data, and read/write lines into a high-impedance state (tri-state)", "The CPU must electronically disconnect from the system buses so the DMA controller can take over without causing an electrical short circuit."),
Q("CAT 1", "HARD", "What is 'Burst Mode' in DMA transfer?", ["Transferring one byte every hour", "The DMA controller takes over the bus and transfers an entire block of data continuously until the transfer is complete", "The CPU taking back control instantly", "Transferring data over the internet"], "The DMA controller takes over the bus and transfers an entire block of data continuously until the transfer is complete", "Burst mode is the fastest way to move data, but it locks the CPU out of the memory bus for the duration of the entire block transfer."),
Q("CAT 1", "MEDIUM", "What is 'Serial Communication'?", ["Sending data over a radio wave", "Transmitting data one bit at a time over a single wire or channel", "Sending multiple bits simultaneously over multiple wires", "Printing a document"], "Transmitting data one bit at a time over a single wire or channel", "Serial is slower per clock tick but is much more reliable over long distances than parallel communication, which is why USB (Universal Serial Bus) is so popular."),
Q("CAT 1", "HARD", "What does the 'Baud Rate' measure in asynchronous serial transfer?", ["The size of the hard drive", "The rate of signal changes per second, which often corresponds to the bits per second (bps) transmitted", "The temperature of the wire", "The voltage of the power supply"], "The rate of signal changes per second, which often corresponds to the bits per second (bps) transmitted", "Baud rate determines how fast data is pushed across the serial line. Both the sender and receiver must agree on this rate to communicate asynchronously."),
Q("CAT 1", "EASY", "What is the role of an 'I/O Bus'?", ["To transport people", "To carry data, address, and control signals specifically between the CPU/Memory and the various I/O interfaces", "To connect to Wi-Fi", "To power the monitor"], "To carry data, address, and control signals specifically between the CPU/Memory and the various I/O interfaces", "The I/O bus is an extension of the system bus dedicated to peripheral communication."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "In an I/O Interface, what does the 'Data Register' do?", ["Stores the operating system", "Acts as a buffer to temporarily hold data being transferred between the CPU and the peripheral", "Counts the time", "Generates electricity"], "Acts as a buffer to temporarily hold data being transferred between the CPU and the peripheral", "Because the CPU is much faster than the peripheral, the data register holds the data until the slower device is ready to accept it."),
Q("CAT 2", "MEDIUM", "What is the main advantage of 'Interrupt-Initiated I/O' over 'Programmed I/O'?", ["It requires less hardware", "The CPU does not waste time polling; it can execute other programs until the peripheral explicitly signals it is ready", "It is easier to program", "It uses a serial cable"], "The CPU does not waste time polling; it can execute other programs until the peripheral explicitly signals it is ready", "Interrupts allow the system to be 'event-driven'. The CPU only stops what it's doing when an event actually occurs."),
Q("CAT 2", "HARD", "How does a 'Daisy-Chaining' priority interrupt system work?", ["By asking the user which device is more important", "By connecting all device interrupt request lines in a hardware serial chain; the device closest to the CPU has the highest priority", "By randomly selecting a device", "By using a software array to sort priorities"], "By connecting all device interrupt request lines in a hardware serial chain; the device closest to the CPU has the highest priority", "When the CPU acknowledges an interrupt, the signal travels down the chain. The first device in the chain that requested the interrupt intercepts the signal and replies."),
Q("CAT 2", "EASY", "What does DMA stand for?", ["Direct Memory Access", "Dynamic Media Audio", "Digital Monitor Array", "Data Movement Application"], "Direct Memory Access", "DMA is a hardware feature allowing peripherals to access main memory independently of the CPU."),
Q("CAT 2", "MEDIUM", "What are the two main control signals used by the CPU to grant the bus to a DMA controller?", ["READ and WRITE", "BUS REQUEST (BR) and BUS GRANT (BG)", "START and STOP", "ON and OFF"], "BUS REQUEST (BR) and BUS GRANT (BG)", "The DMA controller asserts Bus Request. When the CPU is ready to yield the bus, it replies with Bus Grant."),
Q("CAT 2", "HARD", "In an I/O Processor (IOP), what is the difference between a 'Selector Channel' and a 'Multiplexer Channel'?", ["Selector is for input, Multiplexer is for output", "A selector channel handles one high-speed device at a time, while a multiplexer channel handles multiple low-speed devices concurrently", "Selector is software, Multiplexer is hardware", "They are exactly the same"], "A selector channel handles one high-speed device at a time, while a multiplexer channel handles multiple low-speed devices concurrently", "Multiplexers interleave data from multiple slow devices (like keyboards), whereas selectors lock onto a fast device (like a disk drive) until the transfer is done."),
Q("CAT 2", "MEDIUM", "What is 'Parallel Communication'?", ["Sending data over a radio wave", "Transmitting multiple bits of data simultaneously over multiple parallel wires", "Sending data backwards", "Encrypting data heavily"], "Transmitting multiple bits of data simultaneously over multiple parallel wires", "Inside the computer (like the data bus), communication is parallel. It is very fast but prone to interference over long distances."),
Q("CAT 2", "HARD", "What is the purpose of 'Start and Stop bits' in asynchronous serial transfer?", ["To turn the computer on and off", "To frame each character of data, allowing the receiver to synchronize its clock with the incoming data stream for just that character", "To indicate the file size", "To encrypt the data"], "To frame each character of data, allowing the receiver to synchronize its clock with the incoming data stream for just that character", "Because there is no shared clock, the Start bit wakes up the receiver, and the Stop bit gives it a moment to process before the next character arrives."),
Q("CAT 2", "EASY", "Which type of I/O command asks the peripheral to send data to the CPU?", ["Data Output command", "Data Input command", "Control command", "Status command"], "Data Input command", "This command triggers the peripheral to read data (e.g., from a sensor or disk) and place it on the data bus for the CPU."),

// ╔══════════════════════════════════╗
// ║            UE (8 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "What is the biggest limitation of Isolated I/O?", ["It is too fast", "It requires separate, dedicated instructions (IN/OUT) and control lines just for I/O operations", "It doesn't work with keyboards", "It uses too much RAM"], "It requires separate, dedicated instructions (IN/OUT) and control lines just for I/O operations", "Because it uses a separate address space, programmers must use specific, limited assembly instructions to talk to devices, rather than the rich set of memory instructions."),
Q("UE", "MEDIUM", "What does a 'Three-State (Tri-State) Buffer' allow the CPU to do?", ["Print in 3D", "Disconnect its pins from the system bus electrically (high impedance state), allowing another controller like DMA to use the wires", "Store three times as much data", "Run three programs at once"], "Disconnect its pins from the system bus electrically (high impedance state), allowing another controller like DMA to use the wires", "A tri-state buffer has three outputs: Logic 0, Logic 1, and High Impedance (effectively disconnected). This is crucial for bus sharing."),
Q("UE", "HARD", "In the CPU-IOP communication process, where does the CPU put the 'I/O program' for the IOP to execute?", ["On a floppy disk", "The CPU writes a sequence of I/O instructions into main memory, and then tells the IOP where to find them", "Inside the ALU", "On the monitor"], "The CPU writes a sequence of I/O instructions into main memory, and then tells the IOP where to find them", "The IOP acts like a co-processor. The main CPU leaves a 'to-do list' (I/O program) in RAM, kicks the IOP, and goes back to its own work."),
Q("UE", "MEDIUM", "Why is 'Handshaking' preferred over 'Strobe Control' for communication between devices of unknown speeds?", ["It uses fewer wires", "Because it uses a two-way acknowledgment system, ensuring data is not lost even if the receiver is extremely slow", "Because it is an older technology", "Because it encrypts the data"], "Because it uses a two-way acknowledgment system, ensuring data is not lost even if the receiver is extremely slow", "With a strobe, the sender just blasts data. With handshaking, the sender waits patiently for the receiver to say 'Got it! Send the next.'"),
Q("UE", "HARD", "What is 'Software Polling' in priority interrupt determination?", ["Voting for a new operating system", "An interrupt handler routine that interrogates each device's status register in a specific sequence to find out which one interrupted", "A virus scan", "Connecting to the internet"], "An interrupt handler routine that interrogates each device's status register in a specific sequence to find out which one interrupted", "This is the software way to establish priority. The device checked first in the code has the highest priority. However, it is slower than hardware daisy-chaining."),
Q("UE", "EASY", "Which component acts as an intermediary between the CPU and an external Hard Drive?", ["The I/O Interface / Controller", "The ALU", "The Power Supply", "The Monitor"], "The I/O Interface / Controller", "The hard drive controller translates the CPU's binary requests into the magnetic/mechanical actions needed by the disk."),
Q("UE", "MEDIUM", "In DMA operations, what happens after the DMA controller finishes transferring the entire block of data?", ["It turns off the computer", "It sends an interrupt signal to the CPU to inform it that the transfer is complete", "It deletes the data", "It starts formatting the drive"], "It sends an interrupt signal to the CPU to inform it that the transfer is complete", "Since the CPU was ignoring the transfer to do other work, the DMA must 'tap the CPU on the shoulder' (interrupt) to say the job is done."),
Q("UE", "HARD", "What is the difference between a 'Synchronous' and 'Asynchronous' communication interface?", ["Synchronous uses Wi-Fi, asynchronous uses cables", "Synchronous relies on a shared clock signal to time data bits, while asynchronous uses start/stop bits and agreed-upon baud rates without a shared clock", "Synchronous is slower", "Asynchronous cannot send text"], "Synchronous relies on a shared clock signal to time data bits, while asynchronous uses start/stop bits and agreed-upon baud rates without a shared clock", "Synchronous is faster and more efficient because it lacks the overhead of start/stop bits, but it requires an extra wire for the clock signal."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (8 Qns)       ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "What is the main function of an 'Interrupt'?", ["To break the computer", "To temporarily halt the CPU's current task so it can attend to a more urgent event", "To display an error message on the screen", "To increase internet speed"], "To temporarily halt the CPU's current task so it can attend to a more urgent event", "Interrupts are the foundation of modern multitasking and responsive hardware."),
Q("POSSIBLE QNS", "MEDIUM", "What is a 'Non-Vectored Interrupt'?", ["An interrupt that uses a physical vector", "An interrupt where the CPU must execute a polling routine to determine the source of the interrupt", "An interrupt from a mouse", "An interrupt that cannot be stopped"], "An interrupt where the CPU must execute a polling routine to determine the source of the interrupt", "Because the interrupting device doesn't provide its own address (vector), the CPU has to waste time asking every device, 'Was it you?'"),
Q("POSSIBLE QNS", "HARD", "How does a 'Data Communication Processor' differ from a standard IOP?", ["It is only used for audio", "It is specifically designed to manage complex network communication protocols, handling data formatting, error checking, and routing over long distances", "It is completely mechanical", "It has no memory"], "It is specifically designed to manage complex network communication protocols, handling data formatting, error checking, and routing over long distances", "While an IOP might just read a hard drive, a Data Communication Processor (like a NIC processor) handles the heavy lifting of TCP/IP or serial network protocols."),
Q("POSSIBLE QNS", "MEDIUM", "What is the advantage of 'Memory-Mapped I/O'?", ["It isolates the I/O completely", "It allows the CPU to use its entire rich set of memory-manipulation instructions (like ADD, CMP) directly on I/O device registers", "It saves hard drive space", "It uses a separate bus"], "It allows the CPU to use its entire rich set of memory-manipulation instructions (like ADD, CMP) directly on I/O device registers", "Because device registers look exactly like RAM to the CPU, programming them is highly flexible and doesn't require special IN/OUT commands."),
Q("POSSIBLE QNS", "HARD", "In 'Handshaking', what is the function of the 'Data Valid' and 'Data Accepted' signals?", ["They are used for encryption", "The sender asserts 'Data Valid' when data is on the bus; the receiver asserts 'Data Accepted' when it has successfully read it", "They turn the power on and off", "They calculate the baud rate"], "The sender asserts 'Data Valid' when data is on the bus; the receiver asserts 'Data Accepted' when it has successfully read it", "This interlocking logic ensures neither device outpaces the other, guaranteeing zero data loss due to speed mismatches."),
Q("POSSIBLE QNS", "EASY", "Which type of data transfer requires the least CPU involvement?", ["Programmed I/O", "Interrupt-Initiated I/O", "Direct Memory Access (DMA)", "Software Polling"], "Direct Memory Access (DMA)", "With DMA, the CPU just sets up the transfer (starting address and word count) and then does completely unrelated work while the DMA hardware handles the data movement."),
Q("POSSIBLE QNS", "MEDIUM", "Why do computers use 'Serial' communication for external devices (like USB) instead of 'Parallel'?", ["Parallel is too slow", "Parallel cables suffer from crosstalk and timing skew over long distances, making serial communication cheaper and more reliable externally", "Serial uses more wires", "Serial is an older technology"], "Parallel cables suffer from crosstalk and timing skew over long distances, making serial communication cheaper and more reliable externally", "Inside a tight motherboard, 64 parallel wires are fine. Over a 3-meter cable, keeping 64 signals perfectly synchronized is nearly impossible."),
Q("POSSIBLE QNS", "HARD", "What is the 'Address Decoder' used for in an I/O interface?", ["To decode secret messages", "To monitor the address bus and activate the specific I/O interface only when its unique address is output by the CPU", "To change IP addresses", "To compress files"], "To monitor the address bus and activate the specific I/O interface only when its unique address is output by the CPU", "Every device on the bus sees every address. The decoder is the 'bouncer' that only lets data through if the address matches the device's assigned port number.")
];

async function insertUnit2Part1() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = ca_unit2_part1.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} questions for CA Unit 2 Part 1.`);
        } else {
            console.log("No new questions for CA Unit 2 Part 1 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit2Part1();
