const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a5d16dbf29e866583f45d27";

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const exp_part4 = [
Q("CAT 1", "HARD", "In the OSI model, what does the Application Layer handle?", ["Error control across a single link", "Network transparency, resource allocation, and providing a window for user processes", "Synchronizing checkpoints", "Translating MAC to IP"], "Network transparency, resource allocation, and providing a window for user processes", "Layer 7 (Application) interfaces with the user's software, managing tasks like file transfers (FTAM) and mail services."),
Q("CAT 2", "EASY", "What is an advantage of the OSI Model?", ["It is cheap to buy", "It supports connectionless and connection-oriented services, and its layered approach makes it adaptable and secure", "It eliminates the need for routers", "It has only one layer to learn"], "It supports connectionless and connection-oriented services, and its layered approach makes it adaptable and secure", "The OSI model's modular architecture means changes in one layer don't necessarily require changes in others, providing flexibility and security."),
Q("UE", "MEDIUM", "Which IP version is represented by 8 groups of hexadecimal numbers separated by colons?", ["IPv4", "IPv5", "IPv6", "MAC"], "IPv6", "IPv6 uses 128 bits represented in colon-hexadecimal notation to provide a massively larger address space."),
Q("POSSIBLE QNS", "HARD", "Why is the Subnet Mask 255.255.0.0 considered the default for Class B networks?", ["Because Class B networks have 8 network bits and 24 host bits", "Because Class B networks have 16 network bits and 16 host bits", "Because it is the only mask that works with IPv6", "Because it represents a private network"], "Because Class B networks have 16 network bits and 16 host bits", "A Class B address naturally splits its 32 bits into 16 for the network (255.255) and 16 for the hosts (0.0)."),
Q("QUIZ", "EASY", "What is the primary function of a network switch?", ["To broadcast all traffic", "To segment networks into different subnets and filter/forward packets based on MAC address", "To assign IP addresses", "To convert domain names"], "To segment networks into different subnets and filter/forward packets based on MAC address", "Switches improve network performance by dividing collision domains and using MAC addresses to forward frames intelligently."),
Q("EXERCISE", "MEDIUM", "What is the difference between an Unmanaged Switch and a Managed Switch?", ["Unmanaged switches are only for Wi-Fi", "Unmanaged switches are plug-and-play with no configuration; Managed switches offer complex protocols like SNMP for better security and control", "Managed switches are cheaper", "There is no difference"], "Unmanaged switches are plug-and-play with no configuration; Managed switches offer complex protocols like SNMP for better security and control", "Managed switches are enterprise-grade devices allowing granular control over VLANs and traffic."),
Q("CAT 1", "HARD", "What defines 'Full Duplex' mode on a switch?", ["Data flows in one direction only", "Data can be transmitted and received simultaneously on the same port, effectively eliminating collisions", "The switch sends data twice", "The switch divides the bandwidth in half"], "Data can be transmitted and received simultaneously on the same port, effectively eliminating collisions", "Full-duplex allows the transmit (TX) and receive (RX) wires to be used simultaneously, doubling potential throughput."),
Q("CAT 2", "EASY", "Which layer of the OSI model does a Network Switch primarily operate in?", ["Layer 1 (Physical)", "Layer 2 (Data Link)", "Layer 3 (Network)", "Layer 4 (Transport)"], "Layer 2 (Data Link)", "Switches operate primarily at the Data Link Layer, processing Ethernet frames using MAC addresses."),
Q("UE", "MEDIUM", "What happens when a switch encounters a broadcast MAC address (FF-FF-FF-FF-FF-FF)?", ["It deletes the frame", "It routes it to the internet", "It floods the frame out of all ports (except the receiving port)", "It sends it back to the sender"], "It floods the frame out of all ports (except the receiving port)", "A switch cannot stop a broadcast frame; it must send it to every connected device on that LAN segment."),
Q("POSSIBLE QNS", "HARD", "What is a 'PoE Switch'?", ["A switch that uses optical fiber only", "A switch that combines data and power transmission over the same Ethernet cable, removing the need for separate power supplies for devices", "A switch that acts as a router", "A switch that is strictly unmanaged"], "A switch that combines data and power transmission over the same Ethernet cable, removing the need for separate power supplies for devices", "Power over Ethernet (PoE) switches supply electricity along with data, ideal for powering IP cameras and phones."),
Q("QUIZ", "EASY", "Which type of switch is implemented entirely in software within a virtual machine environment?", ["Modular Switch", "Virtual Switch", "Stackable Switch", "Smart Switch"], "Virtual Switch", "Virtual switches connect virtual machines together within a host server, functioning exactly like physical switches."),
Q("EXERCISE", "MEDIUM", "What does a 'Smart Switch' provide?", ["Full SNMP management", "A partially managed experience with extra controls but with limitations compared to fully managed switches", "Wireless routing only", "Automatic MAC cloning"], "A partially managed experience with extra controls but with limitations compared to fully managed switches", "Smart switches offer an affordable middle ground between unmanaged and fully managed enterprise switches."),
Q("CAT 1", "HARD", "What is the primary characteristic of a 'Stackable Switch'?", ["It connects to the cloud", "It uses a backplane to combine two or more logical switches into a single manageable logical switch", "It only handles Wi-Fi", "It requires no power"], "It uses a backplane to combine two or more logical switches into a single manageable logical switch", "Stacking allows administrators to manage multiple physical switches as if they were one single switch, increasing port density."),
Q("CAT 2", "EASY", "How does a switch reduce data collisions compared to a hub?", ["By using IP addresses", "By establishing a temporary connection between source and destination and offering dedicated bandwidth", "By dropping every other packet", "By increasing the electrical voltage"], "By establishing a temporary connection between source and destination and offering dedicated bandwidth", "Unlike a hub that broadcasts everything, a switch creates an isolated collision domain for each port."),
Q("UE", "MEDIUM", "Which feature is listed as a DISADVANTAGE of a Network Switch?", ["It prevents traffic overloading", "It increases bandwidth", "It cannot stop traffic destined for a different LAN segment from traveling to all other LAN segments (in the context of broadcasts)", "It uses MAC addresses"], "It cannot stop traffic destined for a different LAN segment from traveling to all other LAN segments (in the context of broadcasts)", "While a switch breaks up collision domains, it does NOT break up broadcast domains. A broadcast frame will still be sent to all ports."),
Q("POSSIBLE QNS", "HARD", "What makes a 'Modular Switch' flexible?", ["It fits in a pocket", "It helps accommodate two or more expansion cards (blades), allowing the network to scale dynamically", "It acts as a wireless router", "It is completely unmanaged"], "It helps accommodate two or more expansion cards (blades), allowing the network to scale dynamically", "Modular switches allow administrators to add specific line cards (like fiber optic ports) as the network grows."),
Q("QUIZ", "EASY", "In the Network Lab, what is meant by 'Topology'?", ["The operating system of the router", "The physical or logical layout of the network", "The password for the Wi-Fi", "The type of ethernet cable used"], "The physical or logical layout of the network", "Topology describes the map (Star, Ring, Mesh) of how devices are interconnected."),
Q("EXERCISE", "MEDIUM", "What does a switch do BEFORE forwarding data to ensure its integrity?", ["It compresses it", "It performs error checking (like reading the CRC)", "It encrypts it", "It converts it to a packet"], "It performs error checking (like reading the CRC)", "A switch performs error checking before forwarding the frame to ensure corrupted data isn't propagated."),
Q("CAT 1", "HARD", "Which device transfers data together by connecting devices, operates at Layer 2, and uses Ethernet frames to prevent collisions?", ["Hub", "Network Switch", "Router", "Modem"], "Network Switch", "Switches actively manage the flow of Ethernet frames based on MAC addresses, effectively preventing collisions."),
Q("CAT 2", "EASY", "What is one major difference between a Switch and a Router?", ["Switches are software, Routers are hardware", "Switches operate at Layer 2 using MAC addresses, Routers operate at Layer 3 using IP addresses", "Switches route globally, Routers switch locally", "There is no difference"], "Switches operate at Layer 2 using MAC addresses, Routers operate at Layer 3 using IP addresses", "Switches build the local network, Routers connect local networks to other networks (like the internet)."),
Q("UE", "MEDIUM", "Why do communication collisions usually happen in a Hub?", ["Because hubs are too fast", "Because a hub is a Layer 1 device that blindly broadcasts every received signal to all other ports simultaneously", "Because hubs use IP addresses", "Because hubs are expensive"], "Because a hub is a Layer 1 device that blindly broadcasts every received signal to all other ports simultaneously", "A hub creates one massive collision domain. If two devices talk at the exact same time, the signals collide and corrupt."),
Q("POSSIBLE QNS", "HARD", "In the context of the Network Lab, what does a 'RIP' routing protocol configuration achieve?", ["It physically connects cables", "It allows routers to dynamically learn and share network paths using distance-vector algorithms", "It tests the RAM of a server", "It encrypts Wi-Fi passwords"], "It allows routers to dynamically learn and share network paths using distance-vector algorithms", "Routing Information Protocol (RIP) is configured in labs to teach how routers automatically discover routes to distant subnets."),
Q("QUIZ", "EASY", "What does 'LAN' stand for in the context of LAN Switches?", ["Large Area Network", "Local Area Network", "Logical Access Node", "Lightwave Area Network"], "Local Area Network", "LAN switches connect devices within a single local area, like an office building."),
Q("EXERCISE", "MEDIUM", "Which device helps prevent traffic overloading by segmenting the network into smaller subnets?", ["Hub", "Modem", "Repeater", "Network Switch"], "Network Switch", "Switches divide a large network into smaller collision domains, vastly improving overall performance."),
Q("CAT 1", "HARD", "What does a 'Routing Switch' do?", ["It only acts as a hub", "It is a Layer 3 switch that connects LANs and performs routing functions normally done by a router", "It routes analog telephone calls", "It operates at Layer 1"], "It is a Layer 3 switch that connects LANs and performs routing functions normally done by a router", "A routing switch has the hardware of a switch but includes software to handle IP routing between subnets internally."),
Q("CAT 2", "EASY", "What is the primary identifier a switch looks for to deliver a message?", ["Email Address", "IP Address", "MAC Address", "Computer Name"], "MAC Address", "Switches operate at the Data Link layer and rely exclusively on hardware MAC addresses for forwarding frames."),
Q("UE", "MEDIUM", "What protocol is commonly used to configure Managed Switches?", ["HTTP", "SNMP (Simple Network Management Protocol)", "FTP", "POP3"], "SNMP (Simple Network Management Protocol)", "Administrators use SNMP to monitor, configure, and manage high-end network switches."),
Q("POSSIBLE QNS", "HARD", "How does a switch handle a frame destined for a MAC address it has not yet learned?", ["It deletes the frame", "It routes it to the internet", "It floods the frame out of all ports (except the receiving port) like a hub", "It sends an error message"], "It floods the frame out of all ports (except the receiving port) like a hub", "If the destination MAC is unknown, the switch broadcasts it. When the target replies, the switch records the MAC to its table for future use."),
Q("QUIZ", "EASY", "Which network device operates at Layer 3 of the OSI Model?", ["Hub", "Unmanaged Switch", "Router", "PoE Switch"], "Router", "Routers operate at the Network Layer (Layer 3) and use IP addresses to move data between different networks."),
Q("EXERCISE", "MEDIUM", "What feature allows network switches to automatically remove time-consuming manual settings?", ["Auto-negotiation and automatic link connections", "AI encryption", "Manual port forwarding", "MAC cloning"], "Auto-negotiation and automatic link connections", "Switches automatically negotiate speed and duplex settings with connected devices, providing easy and instant network access."),
Q("CAT 1", "HARD", "What does it mean that a switch 'cannot stop traffic destined for a different LAN segment from traveling to all other LAN segments'?", ["It means switches route IPs", "It means that Broadcast frames (like ARP requests) cannot be stopped by a switch and will flood all ports in the broadcast domain", "It means switches are useless", "It means switches drop all packets"], "It means that Broadcast frames (like ARP requests) cannot be stopped by a switch and will flood all ports in the broadcast domain", "While switches stop collisions, they do not stop broadcasts. A router is required to divide a broadcast domain."),
Q("CAT 2", "EASY", "Which transmission mode sends data from one source to ALL devices on the network?", ["Unicast", "Multicast", "Broadcast", "Anycast"], "Broadcast", "Broadcast transmission sends a frame to the MAC address FF-FF-FF-FF-FF-FF, reaching every node."),
Q("UE", "MEDIUM", "Is a Network Switch generally used for WAN or LAN?", ["WAN", "LAN", "PAN", "MAN"], "LAN", "Switches are primarily designed to segment and manage traffic within a Local Area Network (LAN)."),
Q("POSSIBLE QNS", "HARD", "What type of switch provides better security levels, precision control, and is mostly used in large networks?", ["Unmanaged Switch", "Managed Switch", "Hub", "PoE Switch"], "Managed Switch", "Managed switches allow granular configuration of ports, VLANs, and security policies, essential for large enterprise environments."),
Q("QUIZ", "EASY", "Which device primarily shares resources among multiple devices with the help of a single LAN?", ["Router", "Network Switch", "Modem", "Gateway"], "Network Switch", "A switch connects local devices (like PCs and printers) together so they can share resources on the same LAN segment."),
Q("EXERCISE", "MEDIUM", "What is one distinct advantage of switches over hubs regarding bandwidth?", ["Switches decrease total bandwidth", "Switches allocate a limited but dedicated bandwidth to each LAN segment, increasing overall network bandwidth", "Switches use bandwidth only for Wi-Fi", "Hubs have infinite bandwidth"], "Switches allocate a limited but dedicated bandwidth to each LAN segment, increasing overall network bandwidth", "Because a switch doesn't force all devices to share a single collision domain, the aggregate bandwidth of the network increases significantly."),
Q("CAT 1", "HARD", "How does a 'Routing Switch' differ from a standard 'Network Switch'?", ["It operates at Layer 1", "It is completely unmanaged", "It combines Layer 2 switching with Layer 3 Network routing functions", "It only handles analog signals"], "It combines Layer 2 switching with Layer 3 Network routing functions", "A routing switch (or Layer 3 switch) can route IP packets between different subnets as well as switch MAC frames."),
Q("CAT 2", "EASY", "Which device acts simply to connect all nodes of a network physically, without managing data in and out?", ["Router", "Managed Switch", "Hub", "Firewall"], "Hub", "A hub merely connects physical wires together. When an electrical signal enters one port, it is blindly repeated out of all other ports."),
Q("UE", "MEDIUM", "What is a 'Collision Domain'?", ["A virtual reality game", "A network segment where data packets can collide with one another when being sent on a shared medium", "A routing protocol", "A type of fiber optic cable"], "A network segment where data packets can collide with one another when being sent on a shared medium", "In a hub network, all devices share one collision domain. A switch breaks this up, providing each port with its own collision domain."),
Q("POSSIBLE QNS", "HARD", "Which switch type is used when you need to power an IP camera directly through the network cable?", ["Virtual Switch", "PoE Switch", "Unmanaged Switch", "Routing Switch"], "PoE Switch", "Power over Ethernet (PoE) switches eliminate the need for separate electrical power supplies for networked devices."),
Q("QUIZ", "EASY", "What is one reason why network switches are considered essential for home or local networks?", ["They host web pages", "They provide automatic link connections, remove time-consuming settings, and allow fast streaming and easy device access", "They generate MAC addresses", "They encrypt passwords"], "They provide automatic link connections, remove time-consuming settings, and allow fast streaming and easy device access", "Switches make local networking seamless. Devices plug in and instantly communicate without manual IP routing configuration."),
Q("EXERCISE", "MEDIUM", "What does a switch examine first when data arrives at any of its ports?", ["The IP Address", "The destination MAC address in the frame header", "The size of the file", "The HTTP request"], "The destination MAC address in the frame header", "The switch reads the destination MAC address to decide which specific port the frame should be forwarded to."),
Q("CAT 1", "HARD", "What is a 'Stackable Switch' used for?", ["Connecting to wireless devices", "Combining two or more logical switches into a single logical switch via a backplane connection", "Acting as a router", "Powering down inactive ports"], "Combining two or more logical switches into a single logical switch via a backplane connection", "Stacking provides the capacity of multiple switches while allowing the network administrator to manage them as a single entity."),
Q("CAT 2", "EASY", "How does a switch handle 'Unicast' transmission?", ["It sends the data to all connected devices", "It establishes a one-to-one connection and transfers the data only to the device that has been specifically addressed", "It sends data to a specific group", "It drops the packet"], "It establishes a one-to-one connection and transfers the data only to the device that has been specifically addressed", "Unicast is direct communication. The switch uses its MAC table to forward the frame exclusively to the intended recipient's port."),
Q("UE", "MEDIUM", "What technique is used by switches to transfer data packets from source to destination?", ["Circuit Switching", "Packet Switching techniques (specifically frame switching)", "Message Switching", "Analog Switching"], "Packet Switching techniques (specifically frame switching)", "Modern switches use packet switching techniques (specifically frame switching) to receive, store, and forward digital data blocks."),
Q("POSSIBLE QNS", "HARD", "Which device works exclusively in a wired network connection according to standard definitions?", ["Router", "Network Switch", "Smartphone", "Tablet"], "Network Switch", "While routers often include Wi-Fi access points, pure network switches deal entirely with wired Ethernet connections."),
Q("QUIZ", "EASY", "What is a known disadvantage of using switches instead of hubs?", ["They cause more collisions", "They cannot perform full-duplex communication", "They are generally more expensive than simple hubs", "They cannot read MAC addresses"], "They are generally more expensive than simple hubs", "Because switches require complex ASICs, processors, and memory to manage MAC tables and forward frames, they cost more than simple hubs."),
Q("EXERCISE", "MEDIUM", "What does 'LAN' segment mean?", ["A piece of a cable", "A subdivided portion of a network created by a switch to reduce congestion", "A type of router", "A wireless protocol"], "A subdivided portion of a network created by a switch to reduce congestion", "Switches break large networks into smaller, more efficient LAN segments."),
Q("CAT 1", "HARD", "If you need a switch for a small home business and do not want to configure anything, what should you buy?", ["Managed Switch", "Core Router", "Unmanaged Switch", "Modular Switch"], "Unmanaged Switch", "Unmanaged switches are purely plug-and-play, perfect for small setups requiring no management."),
Q("CAT 2", "EASY", "Which transmission mode means 'one-to-many'?", ["Unicast", "Multicast", "Broadcast", "Simplex"], "Multicast", "Multicast allows a source to send data to a specific group of interested devices, rather than just one or all of them.")
];

async function run() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = exp_part4.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} EXPANSION Part 4 questions.`);
        } else {
            console.log("No new EXPANSION Part 4 questions to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
run();
