const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a5d16dbf29e866583f45d27";

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const exp_part1 = [
Q("POSSIBLE QNS", "HARD", "In a Star Topology, what happens if the central hub or switch fails?", ["Only the closest computers disconnect", "The entire network goes down", "The network slows down but remains functional", "It switches to a ring topology automatically"], "The entire network goes down", "A Star topology relies entirely on the central node. If it fails, all connected devices lose network access."),
Q("POSSIBLE QNS", "MEDIUM", "What is the main function of 'Cladding' in a Fiber Optic cable?", ["To conduct electricity", "To reflect light back into the core, keeping the signal contained", "To protect the cable from physical crushing", "To translate analog signals to digital"], "To reflect light back into the core, keeping the signal contained", "Cladding has a lower refractive index than the core, causing total internal reflection and keeping the light signal inside the cable."),
Q("EXERCISE", "HARD", "Which diagnostic command specifically shows the path and measures transit delays of packets across an IP network?", ["ping", "ipconfig", "traceroute", "netstat"], "traceroute", "Traceroute maps the exact router-by-router path a packet takes, showing the IP addresses and delays of each hop."),
Q("QUIZ", "MEDIUM", "What is a prominent characteristic of 'Microwave' transmission?", ["It penetrates thick concrete walls easily", "It is omnidirectional", "It requires strict line-of-sight between antennas", "It operates at 3 KHz"], "It requires strict line-of-sight between antennas", "Microwaves are highly directional and cannot penetrate solid obstacles, requiring clear line-of-sight communication."),
Q("CAT 1", "MEDIUM", "If you need a network that spans across a large city, which type of network is most appropriate?", ["LAN", "PAN", "MAN", "SAN"], "MAN", "A Metropolitan Area Network (MAN) is designed to span a city or a large campus."),
Q("CAT 2", "EASY", "Which transmission mode allows data to flow in both directions, but only one direction at a time?", ["Simplex", "Half-Duplex", "Full-Duplex", "Multiplex"], "Half-Duplex", "Half-duplex communication allows two-way data transfer, but not simultaneously (e.g., walkie-talkies)."),
Q("UE", "HARD", "How does a 'Tone Generator' assist a network technician?", ["It generates IP addresses", "It sends an audio tone down a cable to help locate the specific wire in a messy wiring closet", "It measures voltage spikes", "It tests the fiber optic core"], "It sends an audio tone down a cable to help locate the specific wire in a messy wiring closet", "A tone generator and probe kit is a physical diagnostic tool used to trace and identify specific unlabelled cables."),
Q("POSSIBLE QNS", "HARD", "What does 'Attenuation' mean regarding transmission media?", ["The increase in signal speed", "The gradual loss of signal strength as it travels over a distance", "The encryption of the signal", "The reflection of light in fiber optics"], "The gradual loss of signal strength as it travels over a distance", "As electrical or light signals travel, they naturally lose energy. Repeaters are used to combat attenuation."),
Q("EXERCISE", "MEDIUM", "Which device acts as a 'multi-port repeater'?", ["Router", "Bridge", "Hub", "Switch"], "Hub", "A hub regenerates an incoming signal and repeats it out to all other ports, functioning as a multi-port repeater at Layer 1."),
Q("QUIZ", "HARD", "What is the primary difference between a Peer-to-Peer (P2P) network and a Client/Server network?", ["P2P uses fiber optics", "In P2P, all computers have equal status and share resources; in Client/Server, a central machine manages everything", "Client/Server is only used in homes", "P2P networks do not use IP addresses"], "In P2P, all computers have equal status and share resources; in Client/Server, a central machine manages everything", "P2P lacks central administration, making it cheaper but less secure and harder to scale than a Client/Server model."),
Q("CAT 1", "EASY", "Which type of copper cable offers the best protection against Electromagnetic Interference (EMI)?", ["Unshielded Twisted Pair (UTP)", "Shielded Twisted Pair (STP)", "Flat phone cable", "Fiber Optic"], "Shielded Twisted Pair (STP)", "STP has metallic shielding around the twisted pairs, which blocks external electrical noise and EMI."),
Q("CAT 2", "HARD", "Why is a 'Mesh Topology' considered highly fault-tolerant?", ["It uses the fastest cables", "Every node is connected to every other node; if one link fails, data can be rerouted through many other paths", "It requires no routers", "It uses wireless signals exclusively"], "Every node is connected to every other node; if one link fails, data can be rerouted through many other paths", "A full mesh topology offers maximum redundancy because of the multiple direct connections between all devices."),
Q("UE", "MEDIUM", "What is a Loopback Plug used for?", ["To connect two computers directly", "To test the physical transmitting and receiving capabilities of a single network port or NIC", "To encrypt data packets", "To block unauthorized access"], "To test the physical transmitting and receiving capabilities of a single network port or NIC", "A loopback plug connects the transmit pins directly to the receive pins on the same port to ensure the hardware is functioning."),
Q("POSSIBLE QNS", "MEDIUM", "What does the command 'ipconfig /all' do in Windows?", ["It deletes all IP addresses", "It displays detailed network configuration including MAC addresses, DHCP status, and DNS servers", "It pings all computers on the LAN", "It restarts the router"], "It displays detailed network configuration including MAC addresses, DHCP status, and DNS servers", "The '/all' switch provides comprehensive details about all network adapters on the Windows machine."),
Q("EXERCISE", "HARD", "Which type of network spans a very small physical area, typically around a single person (e.g., Bluetooth headphones)?", ["LAN", "PAN", "WAN", "MAN"], "PAN", "A Personal Area Network (PAN) covers a range of roughly 10 meters, primarily used for connecting personal devices."),
Q("QUIZ", "MEDIUM", "What is 'Baseband' transmission?", ["Transmitting multiple signals simultaneously using different frequencies", "Transmitting a single digital signal over the entire bandwidth of the wire", "Transmitting via radio waves", "Transmitting via satellites"], "Transmitting a single digital signal over the entire bandwidth of the wire", "Baseband uses the entire capacity of the cable to transmit one signal at a time, common in standard Ethernet."),
Q("CAT 1", "HARD", "If you ping 127.0.0.1 and receive successful replies, what does this confirm?", ["The internet is working perfectly", "The router is functioning", "The local machine's TCP/IP stack and network interface are functioning properly", "The DNS server is reachable"], "The local machine's TCP/IP stack and network interface are functioning properly", "127.0.0.1 is the local loopback address. A successful ping means your own computer's networking software is healthy."),
Q("CAT 2", "EASY", "Which unguided media type is heavily used by TV remote controls?", ["Bluetooth", "Infrared", "Microwaves", "Radio Waves"], "Infrared", "Infrared is a short-range, line-of-sight wireless technology that cannot penetrate walls, perfect for remotes."),
Q("UE", "MEDIUM", "Which device physically connects different topologies together but does not route packets logically?", ["Bridge", "Router", "Gateway", "Firewall"], "Bridge", "A bridge connects two LAN segments (even of different topologies) and filters traffic using MAC addresses, not IP addresses."),
Q("POSSIBLE QNS", "HARD", "What happens in a Bus Topology if the main backbone cable breaks?", ["Only the computers near the break go offline", "The entire network fails", "The network uses a backup cable automatically", "Data gets routed wirelessly"], "The entire network fails", "In a bus topology, all devices share a single backbone cable. A break in this cable severs the entire communication line."),
Q("EXERCISE", "EASY", "What does 'NIC' stand for?", ["Network Internet Connection", "Network Interface Card", "National Internet Company", "Node Interface Controller"], "Network Interface Card", "A NIC is the hardware component (adapter) that allows a computer to connect to a network."),
Q("QUIZ", "MEDIUM", "Which network software tool is considered a 'Packet Sniffer'?", ["Ping", "Nslookup", "Wireshark", "Ipconfig"], "Wireshark", "Wireshark captures and deeply analyzes individual data packets as they travel across the network."),
Q("CAT 1", "MEDIUM", "What does 'Nslookup' help an administrator do?", ["Test cable continuity", "Find the IP address associated with a specific domain name (or vice versa)", "Measure voltage", "Reboot a switch"], "Find the IP address associated with a specific domain name (or vice versa)", "Nslookup queries the DNS server to resolve domain names to IP addresses for troubleshooting."),
Q("CAT 2", "HARD", "How does 'CSMA/CD' help in network transmission?", ["It encrypts the data", "It listens to the wire to ensure it is clear before transmitting, and detects collisions to retransmit later", "It routes packets to the internet", "It acts as a firewall"], "It listens to the wire to ensure it is clear before transmitting, and detects collisions to retransmit later", "Carrier Sense Multiple Access with Collision Detection is the protocol used in early Ethernet to manage shared media and prevent data corruption."),
Q("UE", "EASY", "What is the primary characteristic of an 'Extranet'?", ["It is open to everyone on the planet", "It is an intranet that can be partially accessed by authorized outside users (like vendors or partners)", "It is a network without any routers", "It uses only Bluetooth"], "It is an intranet that can be partially accessed by authorized outside users (like vendors or partners)", "An extranet securely extends a company's internal network to trusted external stakeholders over the internet."),
Q("POSSIBLE QNS", "MEDIUM", "Why is Fiber Optic cable immune to EMI (Electromagnetic Interference)?", ["It is wrapped in lead", "It uses light pulses instead of electrical signals to transmit data", "It uses wireless frequencies", "It is buried underground"], "It uses light pulses instead of electrical signals to transmit data", "Since fiber optics transmit photons (light) rather than electrons, nearby magnetic fields or electrical noise cannot distort the signal."),
Q("EXERCISE", "HARD", "What is the purpose of the twisting in Twisted Pair cables?", ["To make the cable stronger", "To cancel out electromagnetic interference (EMI) and crosstalk from adjacent wires", "To fit more wires in the jacket", "To speed up the electrons"], "To cancel out electromagnetic interference (EMI) and crosstalk from adjacent wires", "The twists create opposing magnetic fields that cancel out external noise and crosstalk, preserving signal integrity."),
Q("QUIZ", "EASY", "Which transmission mode is represented by a traditional television broadcast?", ["Simplex", "Half-Duplex", "Full-Duplex", "Multiplex"], "Simplex", "In Simplex mode, data flows in only one direction (from the TV station to your television)."),
Q("CAT 1", "HARD", "In a Ring Topology using Token Passing, what happens if a node has no data to send when it receives the token?", ["It holds the token indefinitely", "It destroys the token", "It immediately passes the token to the next node in the ring", "It shuts down"], "It immediately passes the token to the next node in the ring", "The token continuously circulates. If a node doesn't need to transmit, it simply forwards the token to its neighbor."),
Q("CAT 2", "MEDIUM", "Which layer of the OSI model deals with the physical voltage levels and pin layouts?", ["Physical Layer", "Data Link Layer", "Network Layer", "Transport Layer"], "Physical Layer", "Layer 1 defines all electrical, mechanical, and procedural specifications for the physical hardware connections."),
Q("UE", "HARD", "What does a 'Gateway' do that a standard Router might not?", ["It routes packets faster", "It converts data between completely different network architectures and protocol models", "It only uses MAC addresses", "It acts as a simple hub"], "It converts data between completely different network architectures and protocol models", "While routers connect networks of similar architecture, gateways act as complex protocol converters (e.g., connecting a TCP/IP network to an IBM SNA network)."),
Q("POSSIBLE QNS", "EASY", "What is the 'Internet'?", ["A private corporate network", "A global, interconnected network of public and private networks using the TCP/IP protocol suite", "A single massive server in the US", "A type of fiber optic cable"], "A global, interconnected network of public and private networks using the TCP/IP protocol suite", "The Internet is the ultimate 'Network of Networks', connecting billions of devices globally using standard protocols."),
Q("EXERCISE", "MEDIUM", "What is the main function of the 'Core' in a fiber optic cable?", ["It protects against physical damage", "It is the central glass or plastic tube through which the light actually travels", "It absorbs the light", "It conducts electricity for PoE"], "It is the central glass or plastic tube through which the light actually travels", "The core is the microscopic pathway where the actual data-carrying light pulses traverse."),
Q("QUIZ", "HARD", "Which diagnostic command shows all active network connections and listening ports on a machine?", ["ping", "netstat", "ipconfig", "traceroute"], "netstat", "Network Statistics (netstat) displays incoming and outgoing network connections, routing tables, and a number of network interface statistics."),
Q("CAT 1", "EASY", "Which cable type is most commonly used in modern LAN installations (e.g., Cat5e, Cat6)?", ["Coaxial", "Unshielded Twisted Pair (UTP)", "Fiber Optic", "Token Ring cable"], "Unshielded Twisted Pair (UTP)", "UTP cables with RJ-45 connectors are the standard, affordable choice for almost all modern Ethernet LANs."),
Q("CAT 2", "MEDIUM", "What is a defining trait of a 'Server' in a Client/Server architecture?", ["It primarily requests files from other computers", "It provides centralized resources, data storage, and management for client workstations", "It never connects to the internet", "It only uses a GUI interface"], "It provides centralized resources, data storage, and management for client workstations", "Servers are powerful, dedicated machines running a Network Operating System (NOS) designed specifically to serve clients."),
Q("UE", "HARD", "Why are 'Radio Waves' considered omnidirectional?", ["They travel exclusively in a straight line", "They propagate in all directions from the source antenna, allowing them to penetrate walls and reach multiple receivers easily", "They only travel up to the sky", "They bounce off the moon"], "They propagate in all directions from the source antenna, allowing them to penetrate walls and reach multiple receivers easily", "Because radio waves spread outwards in all directions, antennas do not need to be perfectly aligned, making them ideal for FM radio and Wi-Fi."),
Q("POSSIBLE QNS", "MEDIUM", "Which device uses a 'Crossover Cable'?", ["Connecting a PC to a switch", "Connecting a router to a switch", "Connecting two similar devices directly together, like PC to PC or Switch to Switch", "Connecting a TV to the wall"], "Connecting two similar devices directly together, like PC to PC or Switch to Switch", "Historically, crossover cables rewired the transmit/receive pins to allow two identical devices to communicate without an intermediary hub or switch."),
Q("EXERCISE", "HARD", "What is the function of the 'Jacket' on network cables?", ["To reflect light", "To provide the actual data transmission", "To provide an outer protective layer against physical damage, moisture, and shock", "To encrypt the signal"], "To provide an outer protective layer against physical damage, moisture, and shock", "The outer plastic jacket protects the delicate internal wires or glass fibers from environmental hazards."),
Q("QUIZ", "EASY", "What does 'WAN' stand for?", ["Wide Access Node", "Wide Area Network", "Wireless Area Network", "Web Application Network"], "Wide Area Network", "A Wide Area Network spans large geographical distances, connecting multiple smaller LANs together, often using internet leased lines."),
Q("CAT 1", "MEDIUM", "Which topology uses a central device that connects to all other nodes, resembling a bicycle wheel?", ["Bus Topology", "Ring Topology", "Star Topology", "Mesh Topology"], "Star Topology", "In a Star topology, all endpoints are connected individually to a central switch or hub."),
Q("CAT 2", "HARD", "How does a 'Multimeter' differ from a 'Cable Tester'?", ["A multimeter tests IP addresses", "A multimeter tests raw electrical voltage and continuity, while a cable tester specifically verifies the correct pinout wiring of network cables", "A multimeter only works on fiber optics", "They are exactly the same tool"], "A multimeter tests raw electrical voltage and continuity, while a cable tester specifically verifies the correct pinout wiring of network cables", "A multimeter is a general electronics tool for voltage/resistance, while a network cable tester specifically checks if the RJ-45 pins are crimped in the right order."),
Q("UE", "MEDIUM", "What does it mean when a network is described as 'Scalable'?", ["It is resistant to viruses", "It can easily be expanded by adding more nodes without causing major disruptions or requiring total reconfiguration", "It uses only static IPs", "It is very cheap"], "It can easily be expanded by adding more nodes without causing major disruptions or requiring total reconfiguration", "Scalability is a critical network design factor, ensuring that the network can grow alongside a business seamlessly."),
Q("POSSIBLE QNS", "HARD", "In older coax-based bus networks, what is the purpose of a 'Terminator'?", ["To assign IP addresses", "To absorb the electrical signal at the ends of the cable so it doesn't bounce back and cause data collisions", "To physically mount the cable to the wall", "To encrypt the analog signal"], "To absorb the electrical signal at the ends of the cable so it doesn't bounce back and cause data collisions", "Without terminators at both physical ends of a bus cable, signals would reflect back along the wire, causing continuous collisions."),
Q("EXERCISE", "EASY", "Which type of computer network is typically established in a small office or a single home?", ["WAN", "MAN", "LAN", "SAN"], "LAN", "A Local Area Network (LAN) covers a small, confined area like a house, office, or building."),
Q("QUIZ", "HARD", "Why is 'Broadband' transmission used in coaxial cables for cable TV?", ["It is highly secure", "It divides the bandwidth into different frequency channels, allowing multiple signals (TV, Internet, Phone) to be transmitted simultaneously", "It uses light pulses", "It only allows one-way communication"], "It divides the bandwidth into different frequency channels, allowing multiple signals (TV, Internet, Phone) to be transmitted simultaneously", "Broadband allows frequency-division multiplexing, which is why your single coax cable can deliver hundreds of TV channels and fast internet all at once."),
Q("CAT 1", "MEDIUM", "What does 'Network Operating System' (NOS) provide?", ["Word processing capabilities", "Advanced file sharing, user management, security policies, and resource allocation across a network", "Hardware cooling", "Virus creation"], "Advanced file sharing, user management, security policies, and resource allocation across a network", "A NOS (like Windows Server or Linux) is specifically designed to manage robust network services, distinct from standard desktop OSs."),
Q("CAT 2", "EASY", "Which tool captures and analyzes network traffic packet-by-packet?", ["Wireshark", "Ping", "Notepad", "Multimeter"], "Wireshark", "Wireshark is the industry-standard software packet sniffer and network protocol analyzer."),
Q("UE", "HARD", "What defines 'Line-of-Sight' communication?", ["Data transmitted over underground fiber", "Wireless signals (like microwaves or infrared) that require a clear, unobstructed path between the transmitter and receiver", "Using cables that can be seen", "Routing packets through firewalls"], "Wireless signals (like microwaves or infrared) that require a clear, unobstructed path between the transmitter and receiver", "Line-of-sight means any physical obstacle (buildings, hills, heavy rain) blocking the direct path will disrupt the signal."),
Q("POSSIBLE QNS", "MEDIUM", "What is the defining characteristic of a 'Full Mesh' topology?", ["It uses one central switch", "Every single device is connected directly to every other device on the network", "It uses a single circular cable", "It relies entirely on Wi-Fi"], "Every single device is connected directly to every other device on the network", "Full mesh provides the highest redundancy and reliability, but it is extremely expensive and complex to wire.")
];

async function run() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = exp_part1.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} EXPANSION Part 1 questions.`);
        } else {
            console.log("No new EXPANSION Part 1 questions to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
run();
