const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a5d16dbf29e866583f45d27";

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const questions_unit2_part2 = [
// ╔══════════════════════════════════╗
// ║         CAT 1 (20 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "Which transmission medium is best suited for transmitting data over oceans?", ["Twisted Pair", "Coaxial Cable", "Microwaves", "Infrared"], "Microwaves", "Microwave transmission can be achieved over large obstacles and even oceans, often utilizing satellites or high towers."),
Q("CAT 1", "EASY", "What is the primary function of a Network Operating System (NOS)?", ["To browse the internet", "To facilitate communication and resource sharing among multiple devices", "To edit images", "To compile programming code"], "To facilitate communication and resource sharing among multiple devices", "A NOS is specialized software installed on servers to manage network traffic, security, and resource sharing."),
Q("CAT 1", "EASY", "Which of the following is an example of a Network Operating System?", ["Windows 10 Home", "Ubuntu Server", "Microsoft Word", "Google Chrome"], "Ubuntu Server", "Ubuntu Server, Windows Server, and Red Hat are examples of Network Operating Systems."),
Q("CAT 1", "EASY", "What does 'Resource Sharing' mean in a LAN?", ["Distributing money equally among employees", "Allowing workstations to use a single printer, scanner, or file server", "Deleting old files to save space", "Connecting to a satellite"], "Allowing workstations to use a single printer, scanner, or file server", "Resource sharing reduces costs by allowing multiple computers to use the same hardware or software on the network."),
Q("CAT 1", "EASY", "When testing a new LAN, which basic step should you perform first?", ["Check physical connections like Ethernet cables and LED indicators", "Format the hard drive", "Install an antivirus", "Change the MAC address"], "Check physical connections like Ethernet cables and LED indicators", "Start with the basics; many network issues stem from disconnected cables or powered-off switches."),
Q("CAT 1", "EASY", "Which software tool checks the active connections and listening ports on a computer?", ["ping", "netstat", "ipconfig", "nslookup"], "netstat", "Netstat shows active network connections, routing tables, and listening ports, helping detect unauthorized access."),
Q("CAT 1", "EASY", "Which mode of transmission allows data to be sent in one direction only?", ["Simplex", "Half-Duplex", "Full-Duplex", "Complex"], "Simplex", "Simplex mode is unidirectional. Devices like keyboards and traditional radio stations use this mode."),
Q("CAT 1", "EASY", "Which tool is considered a 'Hardware Diagnostic Tool'?", ["Wireshark", "Ping", "Cable Tester", "Traceroute"], "Cable Tester", "A cable tester is a physical device used to check if network cables are properly wired and functioning."),
Q("CAT 1", "EASY", "What is the primary characteristic of 'Twisted Pair' cables?", ["They are made of solid glass", "They contain a pair of copper wires twisted together to reduce noise interference", "They are wireless", "They transmit microwaves"], "They contain a pair of copper wires twisted together to reduce noise interference", "Twisting the wires cancels out electromagnetic interference. The more twists per foot, the better the noise reduction."),
Q("CAT 1", "EASY", "Which is a major disadvantage of a Client/Server Network Operating System?", ["It is highly secure", "It is centralized", "It is very expensive to implement and maintain", "It cannot share printers"], "It is very expensive to implement and maintain", "Client/Server networks require expensive dedicated servers and skilled administrators, raising the cost."),
Q("CAT 1", "MEDIUM", "What does the 'nslookup' command do during network diagnostics?", ["It traces the physical cable route", "It queries DNS to resolve domain names into IP addresses", "It restarts the DHCP server", "It tests the voltage of the network card"], "It queries DNS to resolve domain names into IP addresses", "Nslookup is used to troubleshoot DNS problems by fetching the IP address corresponding to a hostname."),
Q("CAT 1", "MEDIUM", "Why is a fiber optic cable considered better than a copper cable?", ["It is much cheaper", "It is easier to install", "It offers greater bandwidth and is immune to electromagnetic interference", "It uses electricity more efficiently"], "It offers greater bandwidth and is immune to electromagnetic interference", "Fiber optics use light instead of electricity, making them immune to EMI, and they support vastly higher data speeds over longer distances."),
Q("CAT 1", "MEDIUM", "What does the 'Kernel' do in relation to a NIC driver?", ["It deletes malicious packets", "It provides power to the NIC", "It is the core of the OS that controls access to the driver and the NIC hardware", "It encrypts all data"], "It is the core of the OS that controls access to the driver and the NIC hardware", "The operating system's kernel manages system resources and controls software access to hardware devices like the NIC."),
Q("CAT 1", "MEDIUM", "In a Coaxial cable, what is the role of the non-conductive cover (insulator)?", ["To separate the inner conductor from the outer copper mesh", "To transmit light pulses", "To increase the speed of the data", "To block radio waves"], "To separate the inner conductor from the outer copper mesh", "The insulator separates the central copper core (which carries data) from the outer shielding mesh (which prevents EMI)."),
Q("CAT 1", "MEDIUM", "What is an advantage of Half-Duplex over Simplex?", ["It allows communication in both directions, utilizing the entire bandwidth when transmitting", "It is faster than Full-Duplex", "It doesn't require cables", "It encrypts the data automatically"], "It allows communication in both directions, utilizing the entire bandwidth when transmitting", "Half-Duplex allows two-way communication (though not simultaneously), meaning devices can both send and receive."),
Q("CAT 1", "HARD", "What is the primary cause of 'Distortion' in a transmission medium?", ["A loss of signal strength due to distance", "Unwanted signals adding to the original signal", "Different frequency components of a signal traveling at different propagation speeds", "A cut in the physical cable"], "Different frequency components of a signal traveling at different propagation speeds", "Delay distortion occurs because different frequencies travel at different speeds, altering the shape of the signal upon arrival."),
Q("CAT 1", "HARD", "How does a 'Loopback Plug' diagnose network issues?", ["It traces wires behind walls", "It tests network ports by connecting the transmit pins directly to the receive pins", "It captures packets on the network", "It measures voltage drops"], "It tests network ports by connecting the transmit pins directly to the receive pins", "A loopback plug tricks the NIC or switch port into communicating with itself to verify that the port hardware is fully functional."),
Q("CAT 1", "HARD", "Which transmission mode requires no dedicated path and can suffer from eavesdropping due to broadcasting in free space?", ["Fiber Optics", "Coaxial Broadband", "Unguided Transmission (Radio/Microwaves)", "Twisted Pair Baseband"], "Unguided Transmission (Radio/Microwaves)", "Unguided transmission sends waves through the air. Because it is not confined to a cable, anyone with a suitable antenna can potentially eavesdrop."),
Q("CAT 1", "HARD", "In the context of LAN configuration, what is 'DHCP' responsible for?", ["Providing Power over Ethernet", "Resolving website names", "Automatically assigning dynamic IP addresses to workstations", "Testing physical cables"], "Automatically assigning dynamic IP addresses to workstations", "Dynamic Host Configuration Protocol (DHCP) automatically provides IP addresses and subnet masks to devices joining the network."),
Q("CAT 1", "HARD", "What happens to the transmission if the sending and receiving antennas for Microwaves are NOT perfectly aligned?", ["The transmission becomes faster", "The transmission converts to Radio waves", "The signal is lost because Microwaves are highly directional (unidirectional)", "The signal bounces off the ionosphere"], "The signal is lost because Microwaves are highly directional (unidirectional)", "Microwaves are strictly line-of-sight. If the narrowly focused antennas are not aligned, the connection will fail."),

// ╔══════════════════════════════════╗
// ║         CAT 2 (20 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "Which transmission medium transmits data via electromagnetic signals through copper wires?", ["Fiber Optic", "Coaxial and Twisted Pair", "Radio Waves", "Infrared"], "Coaxial and Twisted Pair", "Both coaxial and twisted pair cables use copper wires to transmit data in the form of electrical signals."),
Q("CAT 2", "EASY", "What is the function of the 'Jacket' on a fiber optic cable?", ["To transmit light", "To reflect light back into the core", "To protect the fiber from physical damage and absorb shock", "To provide a ground connection"], "To protect the fiber from physical damage and absorb shock", "The outer plastic jacket protects the delicate glass core and cladding from external physical damage."),
Q("CAT 2", "EASY", "What is 'Wireshark' used for?", ["To edit text documents", "To sniff and analyze network packets in detail", "To physically test cables", "To assign IP addresses"], "To sniff and analyze network packets in detail", "Wireshark is a popular software diagnostic tool used to capture and inspect network traffic packet by packet."),
Q("CAT 2", "EASY", "A walkie-talkie operates using which transmission mode?", ["Simplex", "Half-Duplex", "Full-Duplex", "Multiplex"], "Half-Duplex", "A walkie-talkie allows two-way communication, but only one person can speak at a time, making it Half-Duplex."),
Q("CAT 2", "EASY", "Which of the following is a disadvantage of a LAN?", ["High data transmission rates", "Resource sharing", "Initial setup cost can be high", "Small geographical location"], "Initial setup cost can be high", "While cheap in the long run due to resource sharing, purchasing servers, switches, and cabling makes the initial setup expensive."),
Q("CAT 2", "EASY", "What is a 'Client' in a Client/Server network?", ["The central computer managing everything", "A device that requests services from the server", "The physical network cable", "The router connecting to the internet"], "A device that requests services from the server", "In a Client/Server network, client workstations send requests (like opening a file or printing) to the central server."),
Q("CAT 2", "EASY", "Which type of unguided media cannot penetrate solid walls?", ["Radio Waves", "Microwaves", "Infrared", "Wi-Fi"], "Infrared", "Infrared waves are blocked by solid objects like walls, which is why your TV remote doesn't work from another room."),
Q("CAT 2", "EASY", "Which networking device is known as an 'Adapter'?", ["Switch", "NIC (Network Interface Card)", "Hub", "Router"], "NIC (Network Interface Card)", "A NIC is often referred to as a network adapter or LAN adapter, providing the physical connection to the network."),
Q("CAT 2", "EASY", "What does 'Broadband transmission' in coaxial cables mean?", ["Transmitting a single signal at high speed", "Transmitting multiple signals simultaneously over different frequencies", "Transmitting data via light", "Transmitting wireless signals"], "Transmitting multiple signals simultaneously over different frequencies", "Broadband allows a single cable to carry multiple signals (like TV, internet, phone) at the same time by dividing the frequency."),
Q("CAT 2", "EASY", "When designing a LAN, what is the first step you should take?", ["Buy the cables", "Assess requirements and goals (users, devices, applications)", "Configure IP addresses", "Test the ping"], "Assess requirements and goals (users, devices, applications)", "Before buying anything, you must understand the client's needs, such as the number of users, speed required, and layout."),
Q("CAT 2", "MEDIUM", "Why is a Network Operating System (NOS) said to improve 'Stability'?", ["It doesn't use electricity", "Centralized servers managed by a NOS are designed to handle heavy loads without crashing", "It uses peer-to-peer connections only", "It physically bolsters the hardware"], "Centralized servers managed by a NOS are designed to handle heavy loads without crashing", "A dedicated NOS running on robust server hardware ensures the network remains stable and available to all clients."),
Q("CAT 2", "MEDIUM", "What is the main advantage of using Shielded Twisted Pair (STP) over Unshielded Twisted Pair (UTP)?", ["It is much cheaper", "It has a higher capacity and better protection against noise interference", "It does not require a router", "It uses light instead of electricity"], "It has a higher capacity and better protection against noise interference", "The metallic shield inside an STP cable blocks external electromagnetic interference, allowing for faster and more reliable data transmission."),
Q("CAT 2", "MEDIUM", "What does a 'Multimeter' measure during network diagnostics?", ["Packet loss", "IP addresses", "Electrical signals, voltage, and continuity in cables", "DNS resolution time"], "Electrical signals, voltage, and continuity in cables", "A multimeter is a hardware tool used to ensure electrical circuits within the cables are intact and providing the correct voltage."),
Q("CAT 2", "MEDIUM", "Which unguided transmission media is most affected by environmental conditions like rain and wind?", ["Infrared", "Radio Waves", "Microwaves", "Bluetooth"], "Microwaves", "Because microwaves operate at high frequencies and require line-of-sight, heavy rain or wind moving the antennas can severely distort the signal."),
Q("CAT 2", "MEDIUM", "In a Full-Duplex communication system, what makes it faster than Half-Duplex?", ["It uses light", "It has two separate simplex channels, allowing simultaneous transmission and reception", "It removes the need for error checking", "It compresses data locally"], "It has two separate simplex channels, allowing simultaneous transmission and reception", "Full-Duplex effectively uses two channels (one for sending, one for receiving), eliminating the need to wait turns."),
Q("CAT 2", "HARD", "How does 'Attenuation' affect a copper cable compared to a fiber optic cable?", ["Copper suffers more from attenuation over short distances compared to fiber optics", "Fiber optics suffer from more attenuation", "They suffer equally", "Attenuation does not affect copper"], "Copper suffers more from attenuation over short distances compared to fiber optics", "Electrical signals in copper degrade much faster over distance than light pulses in a fiber optic cable, which is why fiber can run for kilometers without repeaters."),
Q("CAT 2", "HARD", "In LAN setup, what is the role of a 'Crossover Cable'?", ["To connect a PC to a hub", "To connect a router's LAN port to a switch's standard port (in older equipment lacking Auto-MDIX)", "To connect to Wi-Fi", "To provide electrical grounding"], "To connect a router's LAN port to a switch's standard port (in older equipment lacking Auto-MDIX)", "Crossover cables were specifically wired to connect similar devices directly, such as switch-to-switch or PC-to-PC."),
Q("CAT 2", "HARD", "If you are receiving a 'Request timed out' message when pinging a server, what does this indicate?", ["The connection is perfect", "The DNS successfully resolved the name", "A problem exists; the server is unreachable or a firewall is blocking ICMP requests", "The network is too fast"], "A problem exists; the server is unreachable or a firewall is blocking ICMP requests", "A timeout means the echo request was sent, but no reply was received within the expected timeframe."),
Q("CAT 2", "HARD", "What is the primary purpose of 'SolarWinds Network Performance Monitor'?", ["To edit video files", "To monitor network traffic, bandwidth usage, and unauthorized access continuously", "To replace a router", "To assign static IP addresses"], "To monitor network traffic, bandwidth usage, and unauthorized access continuously", "SolarWinds is an advanced network management tool used by administrators to ensure the LAN stays healthy after setup."),
Q("CAT 2", "HARD", "Why is 'Documentation' considered a crucial final step in setting up a LAN?", ["To make the network run faster", "It is legally required by the government", "It provides a blueprint of IP assignments and configurations for future troubleshooting and expansion", "It stops viruses"], "It provides a blueprint of IP assignments and configurations for future troubleshooting and expansion", "Properly documented network diagrams and IP tables save immense amounts of time when resolving future issues or adding new devices."),

// ╔══════════════════════════════════╗
// ║           UE (20 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "Which transmission media is also known as 'Bounded media'?", ["Wireless Transmission", "Unguided Media", "Guided Media", "Microwaves"], "Guided Media", "Guided media uses physical wires (like copper or fiber) to bind and guide the signal from source to destination."),
Q("UE", "EASY", "Which of the following is an unguided transmission medium?", ["Twisted Pair", "Coaxial Cable", "Radio Waves", "Fiber Optic"], "Radio Waves", "Radio waves transmit data through the air without physical cables, making them an unguided medium."),
Q("UE", "EASY", "Which software tool is used to trace the path a packet takes from source to destination?", ["Ping", "Tracert (Traceroute)", "Ipconfig", "Netstat"], "Tracert (Traceroute)", "Traceroute lists all the intermediate hops (routers) a packet travels through to reach its target."),
Q("UE", "EASY", "What is the main advantage of a Radio Wave transmission?", ["It requires perfect line-of-sight", "It is omnidirectional and can easily penetrate walls", "It cannot be intercepted", "It uses light pulses"], "It is omnidirectional and can easily penetrate walls", "Radio waves spread out in all directions and easily pass through buildings, making them ideal for mobile and wide-area networks."),
Q("UE", "EASY", "Which of the following represents a Full-Duplex communication device?", ["Keyboard", "Radio Broadcast", "Walkie-Talkie", "Telephone"], "Telephone", "A telephone allows both callers to speak and listen simultaneously, operating in full-duplex mode."),
Q("UE", "EASY", "What is the primary component of a fiber optic cable that transmits the light?", ["Cladding", "Jacket", "Core", "Copper Mesh"], "Core", "The core is the very thin glass or plastic strand in the center of the cable where the light actually travels."),
Q("UE", "EASY", "If your computer cannot access a website by its name (e.g., google.com) but can access it via its IP address, which service is likely failing?", ["DHCP", "DNS", "FTP", "ARP"], "DNS", "The Domain Name System (DNS) is responsible for resolving names to IP addresses. If it fails, you can only browse using raw IP addresses."),
Q("UE", "EASY", "Which of the following operates at the TCP/IP Network layer?", ["Switch", "Hub", "Router", "Repeater"], "Router", "A router is a Layer 3 (Network layer) device responsible for delivering data packets across different networks."),
Q("UE", "EASY", "What does 'Baseband' refer to in transmission?", ["Transmitting a single digital signal over a channel", "Transmitting multiple analog signals", "Using wireless antennas", "Encrypting passwords"], "Transmitting a single digital signal over a channel", "Baseband transmission dedicates the entire capacity of the cable to transmitting a single data signal at high speed."),
Q("UE", "EASY", "Which hardware tool is used to verify if an Ethernet cable is broken inside?", ["Loopback plug", "Wireshark", "Cable Tester", "Nslookup"], "Cable Tester", "A cable tester is a physical device plugged into both ends of a cable to ensure all internal wires are unbroken and properly mapped."),
Q("UE", "MEDIUM", "What is 'Noise' in data transmission?", ["The sound of the cooling fans in a server", "The loss of signal energy", "Unwanted electrical or electromagnetic signals that mix with the data signal", "A type of routing protocol"], "Unwanted electrical or electromagnetic signals that mix with the data signal", "Noise is any external interference (like EMI from power lines) that corrupts the original data signal during transmission."),
Q("UE", "MEDIUM", "Why might a network administrator choose Peer-to-Peer NOS over a Client/Server NOS?", ["To handle 1,000+ users securely", "To save costs on a very small network with limited resources", "To host a major website", "To prevent physical cable damage"], "To save costs on a very small network with limited resources", "Peer-to-peer networks are cheap and easy to set up for a small number of computers since they don't require an expensive dedicated server."),
Q("UE", "MEDIUM", "In diagnosing a network, what is a 'Loopback Plug' specifically used for?", ["To connect two computers directly", "To test the functionality of a specific network port on a NIC or switch", "To trace a wire in a wall", "To monitor bandwidth usage"], "To test the functionality of a specific network port on a NIC or switch", "A loopback plug takes the transmit signal and routes it directly back to the receive pin on the same port to ensure the hardware works."),
Q("UE", "MEDIUM", "Which feature of a Network Operating System (NOS) allows an administrator in New York to fix a server in London?", ["Resource Sharing", "Data Backup", "Remote Access", "User Authentication"], "Remote Access", "Remote Access capabilities allow administrators to securely log into and manage servers from geographically distant locations."),
Q("UE", "MEDIUM", "Why is Infrared communication considered highly secure compared to Radio Waves?", ["It is fully encrypted by default", "It cannot penetrate walls, keeping the signal contained within a single room", "It uses military satellites", "It operates at a lower frequency"], "It cannot penetrate walls, keeping the signal contained within a single room", "Because infrared requires line-of-sight and cannot pass through solid walls, it is impossible for someone outside the room to intercept the signal."),
Q("UE", "HARD", "How does a 'Tone Generator and Probe' assist a network technician?", ["By calculating IP subnet masks automatically", "By injecting an audio signal onto a specific wire, allowing the probe to find the other end in a messy wiring closet", "By generating network traffic to test bandwidth", "By measuring the resistance in ohms"], "By injecting an audio signal onto a specific wire, allowing the probe to find the other end in a messy wiring closet", "The tone generator sends an analog signal down the wire. The technician uses the probe wand to scan cables until they hear the matching tone, identifying the correct wire."),
Q("UE", "HARD", "During initial testing of a LAN, you ping a workstation and receive the message 'Request timed out'. What is the LEAST likely cause?", ["The target computer is powered off", "The target computer's firewall is blocking ICMP packets", "The switch port is broken", "The target computer is using a web browser"], "The target computer is using a web browser", "Using a web browser has no effect on responding to pings. Timeouts are usually caused by physical disconnection, routing issues, or firewalls."),
Q("UE", "HARD", "What is the primary difference between a 'Hub' and a 'Switch' regarding collision domains?", ["A switch creates one large collision domain; a hub creates multiple", "A hub sends data everywhere causing collisions; a switch isolates collision domains per port", "There is no difference", "A hub uses IP addresses; a switch uses MAC addresses"], "A hub sends data everywhere causing collisions; a switch isolates collision domains per port", "Because a hub broadcasts to all ports, all devices share one collision domain. A switch forwards intelligently, making each port its own collision domain."),
Q("UE", "HARD", "If an administrator needs to provide power to a ceiling-mounted Wireless Access Point without installing a new electrical outlet, what technology should they use?", ["DHCP", "Power over Ethernet (PoE)", "Fiber Optics", "Coaxial Broadband"], "Power over Ethernet (PoE)", "PoE (Power over Ethernet) allows electrical power to be transmitted alongside data over standard twisted-pair Ethernet cables."),
Q("UE", "HARD", "Why are Microwaves typically used for long-distance telecommunications despite their line-of-sight restriction?", ["They can bend around mountains", "They support very high bandwidth (1 to 10 Mbps) and don't require laying physical cables across difficult terrain", "They are immune to rain and weather", "They automatically encrypt data"], "They support very high bandwidth (1 to 10 Mbps) and don't require laying physical cables across difficult terrain", "For rough terrain where laying cables is impossible, point-to-point microwave towers offer high bandwidth and are cheaper than physical land acquisition.")
];

async function insertUnit2() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        // Part 1
        const toInsert1 = require('./cn_unit2_part1.js').filter(q => !existingTexts.has(`${q.category}|${q.questionText.substring(0, 50)}`));
        if (toInsert1.length > 0) {
            const res1 = await db.collection('questions').insertMany(toInsert1);
            console.log(`Inserted ${res1.insertedCount} questions from unit 2 part 1.`);
        }
        
        // Part 2
        const toInsert2 = questions_unit2_part2.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert2.length > 0) {
            const res2 = await db.collection('questions').insertMany(toInsert2);
            console.log(`Inserted ${res2.insertedCount} questions from unit 2 part 2.`);
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit2();
