const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a5d16dbf29e866583f45d27";

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const questions_unit3 = [
// ╔══════════════════════════════════╗
// ║          QUIZ (20 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "What is an IP address primarily used for?", ["To encrypt passwords", "To uniquely identify a device on a network", "To boost the internet speed", "To filter spam emails"], "To uniquely identify a device on a network", "An IP Address is a unique logical number used to identify a device on a network to allow communication."),
Q("QUIZ", "EASY", "How many bits are in an IPv4 address?", ["16-bit", "32-bit", "64-bit", "128-bit"], "32-bit", "An IPv4 address is a 32-bit logical address typically represented in 4 octets."),
Q("QUIZ", "EASY", "Which component of the IP address is common to all hosts within a given network?", ["Host ID", "Network ID", "MAC Address", "Subnet Mask"], "Network ID", "The Network ID (or network address) is the prefix common to all hosts within the same local network."),
Q("QUIZ", "EASY", "What type of IP address can be accessed globally over the internet?", ["Private IP Address", "Loopback Address", "Public IP Address", "APIPA Address"], "Public IP Address", "Public IP addresses are unique across the entire Internet and can be accessed globally."),
Q("QUIZ", "EASY", "What does a Dynamic IP address mean?", ["It is tied to a single user permanently", "It never changes", "It can change from time-to-time", "It is only used for printers"], "It can change from time-to-time", "Dynamic IP addresses are assigned temporarily (leased) by a DHCP server and can change periodically."),
Q("QUIZ", "EASY", "What does 'APIPA' stand for?", ["Automatic Private IP Addressing", "Automated Public Internet Protocol Address", "Active Protocol Internet Provider Access", "Application Programming Interface Provider Address"], "Automatic Private IP Addressing", "APIPA is a mechanism where a system automatically assigns itself an IP address when the DHCP server fails."),
Q("QUIZ", "EASY", "Which block of IP addresses is reserved for testing internal devices (loopback)?", ["10.0.0.0", "192.168.0.0", "127.x.x.x", "172.16.0.0"], "127.x.x.x", "The 127 network block (specifically 127.0.0.1) is known as the loopback address used for testing the local machine."),
Q("QUIZ", "EASY", "How many layers are in the OSI model?", ["4", "5", "6", "7"], "7", "The OSI (Open System Interconnection) reference model consists of 7 layers."),
Q("QUIZ", "EASY", "Which is the lowest layer of the OSI model?", ["Data Link Layer", "Physical Layer", "Network Layer", "Transport Layer"], "Physical Layer", "The Physical Layer is Layer 1, the lowest layer, responsible for transmitting raw bits."),
Q("QUIZ", "EASY", "What does 'NAT' stand for?", ["Network Address Translation", "National Access Terminal", "Network Allocation Table", "Node Application Transfer"], "Network Address Translation", "NAT translates private local addresses to globally routable public addresses."),
Q("QUIZ", "MEDIUM", "What happens when an IP address has its host octet set to all 1's (or 255)?", ["It becomes a private IP", "It becomes a loopback address", "It is interpreted as a broadcast address", "It causes a network collision"], "It is interpreted as a broadcast address", "By replacing the host bits of a network address with 1s (255 in decimal), it becomes the broadcast address for that network."),
Q("QUIZ", "MEDIUM", "Which version of IP uses 128 binary bits expressed in 8 groups of hexadecimal numbers?", ["IPv4", "IPv5", "IPv6", "IPv8"], "IPv6", "IPv6 was created to solve the IP shortage. It uses 128-bit addresses written in hexadecimal separated by colons."),
Q("QUIZ", "MEDIUM", "What is the primary function of a DHCP Reservation?", ["To limit the network speed", "To assign an IP address permanently to a specific device like a printer", "To block unauthorized users", "To encrypt IP addresses"], "To assign an IP address permanently to a specific device like a printer", "DHCP reservation ensures that a specific device always receives the same IP address from the DHCP server."),
Q("QUIZ", "MEDIUM", "Which layer of the OSI model handles 'Framing' and 'Physical Addressing' (MAC)?", ["Network Layer", "Physical Layer", "Transport Layer", "Data Link Layer"], "Data Link Layer", "The Data Link Layer (Layer 2) translates the raw bit stream into frames and adds the hardware (MAC) destination and source addresses."),
Q("QUIZ", "MEDIUM", "In the OSI model, which layer is responsible for routing and logical addressing (IP)?", ["Data Link Layer", "Network Layer", "Transport Layer", "Session Layer"], "Network Layer", "The Network Layer (Layer 3) handles device IP addressing and tracks the best path to route packets from source to destination."),
Q("QUIZ", "HARD", "Which two protocols operate at the Transport Layer of the OSI model?", ["HTTP and FTP", "IPv4 and IPv6", "TCP and UDP", "SMTP and POP3"], "TCP and UDP", "Transmission Control Protocol (TCP) and User Datagram Protocol (UDP) are the primary Layer 4 (Transport) protocols."),
Q("QUIZ", "HARD", "What is the difference between TCP and UDP?", ["UDP is reliable and requires acknowledgment, TCP does not", "TCP is a connection-oriented, reliable protocol, while UDP is connectionless and unreliable", "TCP operates at Layer 3, UDP at Layer 4", "TCP is only for wireless networks"], "TCP is a connection-oriented, reliable protocol, while UDP is connectionless and unreliable", "TCP ensures complete data transfer with acknowledgments and reordering, whereas UDP sends packets without waiting for acknowledgments."),
Q("QUIZ", "HARD", "Which OSI layer uses 'checkpoints' to allow data synchronization and avoid massive data loss if a connection breaks?", ["Session Layer", "Presentation Layer", "Transport Layer", "Application Layer"], "Session Layer", "The Session Layer (Layer 5) adds synchronization points (checkpoints) so that if an error occurs, data can be re-synchronized properly from the last checkpoint."),
Q("QUIZ", "HARD", "Data compression and encryption are primary functions of which OSI layer?", ["Application Layer", "Presentation Layer", "Session Layer", "Data Link Layer"], "Presentation Layer", "The Presentation Layer (Layer 6) acts as the data translator, handling syntax, semantics, compression, and encryption."),
Q("QUIZ", "HARD", "Which statement accurately describes a disadvantage of the OSI model?", ["It is highly insecure", "Some services are duplicated at various layers (e.g., error/flow control in Data Link and Transport layers)", "It only supports IPv6", "It only has 4 layers"], "Some services are duplicated at various layers (e.g., error/flow control in Data Link and Transport layers)", "A known disadvantage of the OSI model is that features like flow control and error control appear redundantly in both the Data Link and Transport layers."),

// ╔══════════════════════════════════╗
// ║        EXERCISE (20 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "Which class of IP address ranges from 128 to 191?", ["Class A", "Class B", "Class C", "Class D"], "Class B", "Class B IP addresses range from 128 to 191 in their first octet."),
Q("EXERCISE", "EASY", "Which IP address range is reserved for Class A private networks?", ["192.168.0.0 - 192.168.255.255", "172.16.0.0 - 172.31.255.255", "10.0.0.0 - 10.255.255.255", "127.0.0.0 - 127.255.255.255"], "10.0.0.0 - 10.255.255.255", "The 10.x.x.x block is strictly reserved for Class A private networks."),
Q("EXERCISE", "EASY", "Can devices with private IP addresses connect directly to the public Internet?", ["Yes, always", "No, they need a router utilizing NAT", "Yes, but only if they use IPv6", "No, they can only connect to printers"], "No, they need a router utilizing NAT", "Private IP addresses are internal and non-routable on the public internet. Network Address Translation (NAT) maps them to a public IP."),
Q("EXERCISE", "EASY", "What does a DHCP 'Lease' mean?", ["The cost of the DHCP software", "The amount of time an IP address is assigned to a computer", "The password required to join the network", "The physical cable connection"], "The amount of time an IP address is assigned to a computer", "A DHCP lease determines how long a device can use the assigned IP address before it must renew it. This ensures IP addresses don't run out."),
Q("EXERCISE", "EASY", "If you see a double colon '::' in an IP address, what version of IP is it?", ["IPv4", "IPv5", "IPv6", "MAC Address"], "IPv6", "IPv6 uses a double colon to replace consecutive sections of zeroes to shorten the address notation (e.g., 2001:0db7::54)."),
Q("EXERCISE", "EASY", "In the OSI model, what are the 'Lower Layers' primarily concerned with?", ["User interaction", "Data transport activities (implemented in both software and hardware)", "Software application issues", "Data encryption"], "Data transport activities (implemented in both software and hardware)", "The Lower Layers (Physical, Data Link, Network, Transport) handle data transport and are implemented in hardware and software."),
Q("EXERCISE", "EASY", "What is the primary function of the Physical Layer?", ["Routing packets", "Transmitting individual raw bits from one node to another", "Encrypting passwords", "Checking for MAC addresses"], "Transmitting individual raw bits from one node to another", "The Physical Layer (Layer 1) establishes the physical connection and transmits the raw bit stream."),
Q("EXERCISE", "EASY", "What do we call the data units at the Data Link Layer?", ["Segments", "Packets", "Frames", "Bits"], "Frames", "The Data Link Layer takes raw bits from the Physical Layer and translates them into packets known as Frames."),
Q("EXERCISE", "EASY", "What do we call the data units at the Network Layer?", ["Frames", "Segments", "Packets", "Datagrams"], "Packets", "The Network Layer receives data from the Transport Layer and converts them into Packets (a process known as Packetizing)."),
Q("EXERCISE", "EASY", "What is 'Flow Control' at the Data Link Layer?", ["A method to encrypt data", "A technique ensuring the transmitting station does not exceed the receiving station's processing speed", "A way to assign IP addresses", "A process of compressing video"], "A technique ensuring the transmitting station does not exceed the receiving station's processing speed", "Flow control prevents a fast sender from overwhelming a slow receiver, avoiding data corruption."),
Q("EXERCISE", "MEDIUM", "What is CRC (Cyclic Redundancy Check) used for?", ["Error control at the Data Link Layer", "Assigning IP addresses at the Network Layer", "Encrypting data at the Presentation Layer", "Compressing files at the Application Layer"], "Error control at the Data Link Layer", "CRC is a calculated value placed in the frame's trailer by the Data Link Layer to detect errors during transmission."),
Q("EXERCISE", "MEDIUM", "Which sub-layer of the Data Link Layer provides flow control and identifies network layer protocols?", ["Media Access Control (MAC) Layer", "Logical Link Control (LLC) Layer", "Session Layer", "Physical Layer"], "Logical Link Control (LLC) Layer", "The Data Link Layer is divided into the LLC (which handles flow/error control and protocol identification) and the MAC sub-layers."),
Q("EXERCISE", "MEDIUM", "What is 'Service-point addressing' (Port Addressing)?", ["Assigning IP addresses to routers", "Assigning MAC addresses to NICs", "Using port numbers at the Transport layer to deliver messages to the correct software process", "Creating subnets"], "Using port numbers at the Transport layer to deliver messages to the correct software process", "Because computers run multiple programs, the Transport layer uses port addresses to deliver data to the correct specific application process."),
Q("EXERCISE", "MEDIUM", "Which OSI layer acts as a 'Dialog Controller'?", ["Physical Layer", "Session Layer", "Network Layer", "Presentation Layer"], "Session Layer", "The Session Layer establishes the session and acts as a dialog controller, managing half-duplex or full-duplex communication start."),
Q("EXERCISE", "MEDIUM", "FTAM (File transfer, access, and management) is a function of which layer?", ["Presentation Layer", "Transport Layer", "Data Link Layer", "Application Layer"], "Application Layer", "The Application Layer provides services like FTAM, Mail services, and Directory services directly to the user's software."),
Q("EXERCISE", "HARD", "Why does NAT (Network Address Translation) improve network security?", ["It encrypts all data with AES-256", "It hides the internal private IP addresses of devices from external hackers", "It physically disconnects unauthorized cables", "It blocks all UDP traffic"], "It hides the internal private IP addresses of devices from external hackers", "Because NAT maps internal private IPs to a single public IP at the router, external entities cannot directly see or address the internal devices."),
Q("EXERCISE", "HARD", "How does Error Control at the Transport Layer differ from Error Control at the Data Link Layer?", ["Transport Layer does not perform error control", "Transport layer error control is performed end-to-end, while Data Link is across a single link (hop-to-hop)", "Data link layer uses TCP, Transport uses MAC", "There is no difference"], "Transport layer error control is performed end-to-end, while Data Link is across a single link (hop-to-hop)", "Data Link checks for errors on a single physical cable hop, whereas the Transport layer ensures the message reached the final destination without error across the entire path."),
Q("EXERCISE", "HARD", "Which protocols are matched correctly to Layer 7 (Application Layer)?", ["TCP, UDP", "IPV4, IPV6, ICMP", "MPEG, SSL, TLS", "SMTP, HTTP, FTP, POP3, SNMP"], "SMTP, HTTP, FTP, POP3, SNMP", "These protocols define high-level application interactions, making them Layer 7 protocols."),
Q("EXERCISE", "HARD", "Which OSI layer provides 'Hop-to-Hop' delivery?", ["Network Layer", "Data Link Layer", "Transport Layer", "Application Layer"], "Data Link Layer", "The Data Link layer is responsible for delivering frames securely across a single physical link (hop-to-hop)."),
Q("EXERCISE", "HARD", "What does 'Segmentation and Reassembly' refer to at the Transport Layer?", ["Breaking a cable into segments", "Dividing a message into smaller units (segments) with sequence numbers to reassemble them correctly at the destination", "Translating IPv4 to IPv6", "Compressing multimedia files"], "Dividing a message into smaller units (segments) with sequence numbers to reassemble them correctly at the destination", "The Transport layer takes large messages from upper layers, segments them, numbers them, and reassembles them upon arrival.")
];

const cat1 = [
Q("CAT 1", "EASY", "Which layer of the OSI model translates syntax and semantics?", ["Session Layer", "Presentation Layer", "Application Layer", "Network Layer"], "Presentation Layer", "The Presentation layer acts as the data translator, handling syntax, encryption, and compression."),
Q("CAT 1", "EASY", "What is an IP address?", ["A physical MAC address", "A 32-bit logical address used to uniquely identify a device on a network", "A protocol for sending files", "A type of network cable"], "A 32-bit logical address used to uniquely identify a device on a network", "An IP address (IPv4) is a 32-bit logical identifier."),
Q("CAT 1", "EASY", "If the DHCP server fails, what mechanism assigns an IP address automatically?", ["NAT", "DNS", "APIPA", "TCP"], "APIPA", "APIPA (Automatic Private IP Addressing) kicks in when a device cannot reach a DHCP server, assigning an IP in the 169.254.x.x range."),
Q("CAT 1", "EASY", "The IP address 192.168.1.1 belongs to which IP Class?", ["Class A", "Class B", "Class C", "Class D"], "Class C", "Class C networks range from 192 to 223 in their first octet."),
Q("CAT 1", "MEDIUM", "What is the primary difference between Static and Dynamic IP addresses?", ["Static IPs are for MACs, Dynamic for Windows", "Static IPs change frequently, Dynamic never change", "Static IPs (Dedicated) never change, Dynamic IPs are leased and change from time-to-time", "There is no difference"], "Static IPs (Dedicated) never change, Dynamic IPs are leased and change from time-to-time", "Static IPs are manually assigned and permanent. Dynamic IPs are assigned by DHCP and can change."),
Q("CAT 1", "MEDIUM", "Which device uses NAT to translate local addresses to routable internet addresses?", ["A basic Hub", "A Layer 2 Switch", "A Gateway or Router", "A Cable Tester"], "A Gateway or Router", "Routers and Gateways perform Network Address Translation (NAT) to bridge private networks to the public internet."),
Q("CAT 1", "MEDIUM", "At which OSI layer does an IP address operate?", ["Physical Layer (Layer 1)", "Data Link Layer (Layer 2)", "Network Layer (Layer 3)", "Transport Layer (Layer 4)"], "Network Layer (Layer 3)", "Logical addressing (IP) and routing occur at Layer 3, the Network Layer."),
Q("CAT 1", "HARD", "How is a broadcast address calculated for a Class C network (e.g., 192.168.1.0)?", ["Change the first octet to 255", "Change the network bits to 0s", "Replace the host octet bits with all 1s (resulting in 192.168.1.255)", "Add 1 to the network address"], "Replace the host octet bits with all 1s (resulting in 192.168.1.255)", "By setting the host bits (the last 8 bits in Class C) to all 1s, the address becomes the broadcast address."),
Q("CAT 1", "HARD", "In the OSI model, what does the phrase 'Layers cannot work in parallel' mean?", ["Layers can process data simultaneously", "Each layer must wait to receive data from the previous layer", "The OSI model is broken", "Multiple protocols cannot be used"], "Each layer must wait to receive data from the previous layer", "A disadvantage of the OSI model is its strict sequential nature; a layer cannot begin processing until the adjacent layer passes the data to it.")
];

const cat2 = [
Q("CAT 2", "EASY", "What is the default subnet mask for a Class B network?", ["255.0.0.0", "255.255.0.0", "255.255.255.0", "0.0.0.0"], "255.255.0.0", "Class B uses 16 bits for the network and 16 bits for the host, making the default mask 255.255.0.0."),
Q("CAT 2", "EASY", "What does 'TCP' stand for?", ["Transfer Control Protocol", "Transmission Control Protocol", "Terminal Connection Protocol", "Total Command Protocol"], "Transmission Control Protocol", "TCP is a core protocol of the Transport Layer that provides reliable, ordered, and error-checked delivery."),
Q("CAT 2", "EASY", "Which layer is known as Layer 5 in the OSI model?", ["Session Layer", "Presentation Layer", "Transport Layer", "Application Layer"], "Session Layer", "Layer 5 is the Session Layer, responsible for establishing, maintaining, and synchronizing interactions."),
Q("CAT 2", "EASY", "What is the function of the Application Layer?", ["To compress files", "To serve as a window for users and application processes to access network services", "To route packets over the internet", "To transmit raw bits"], "To serve as a window for users and application processes to access network services", "The Application layer (Layer 7) provides direct services like Email, File Transfer, and Web browsing to the user's software."),
Q("CAT 2", "MEDIUM", "What defines an Ethernet network as a 'Broadcast Network'?", ["It uses satellites", "Any system can send information and all systems receive the message, but they discard messages not addressed to them", "It only allows one computer to send data", "It uses token passing"], "Any system can send information and all systems receive the message, but they discard messages not addressed to them", "In an Ethernet broadcast network, frames are flooded. Only the NIC with the matching MAC address processes the frame; others discard it."),
Q("CAT 2", "MEDIUM", "Which protocol is matched to the Session Layer?", ["TCP", "NetBIOS", "IPv4", "HTTP"], "NetBIOS", "NetBIOS and SAP are examples of protocols operating at the Session Layer."),
Q("CAT 2", "MEDIUM", "Which IP block is considered a Class B Private Network?", ["10.0.0.0 to 10.255.255.255", "192.168.0.0 to 192.168.255.255", "172.16.0.0 to 172.31.255.255", "127.0.0.0 to 127.255.255.255"], "172.16.0.0 to 172.31.255.255", "The 172.16 to 172.31 block is reserved by IANA for Class B private networks."),
Q("CAT 2", "HARD", "How does a 'Connectionless Service' at the Transport layer operate?", ["It establishes a firm connection before sending data", "It treats each segment as an individual packet that can travel different routes to the destination", "It requires a physical cable", "It guarantees delivery"], "It treats each segment as an individual packet that can travel different routes to the destination", "Connectionless services (like UDP) send packets independently without setting up a path first. Packets may arrive out of order."),
Q("CAT 2", "HARD", "What is 'Bit rate control' and which layer handles it?", ["Determining the sequence of packets; Network layer", "Encrypting bits; Presentation layer", "Defining the transmission rate (bits per second); Physical layer", "Controlling application access; Application layer"], "Defining the transmission rate (bits per second); Physical layer", "The Physical Layer defines how many bits are sent per second, ensuring synchronization between sender and receiver.")
];

const ue = [
Q("UE", "EASY", "What does OSI stand for?", ["Open Source Internet", "Open System Interconnection", "Operating System Interface", "Optical Signal Interconnect"], "Open System Interconnection", "OSI is a standard reference model created by ISO to describe network communication."),
Q("UE", "EASY", "Which type of IP address is required for a web server accessible to everyone on the internet?", ["Private IP", "APIPA IP", "Loopback IP", "Public IP"], "Public IP", "A Public IP is globally routable and unique, which is required for publicly accessible entities like web servers."),
Q("UE", "EASY", "Which layer is responsible for defining physical topologies (like Star, Bus, Ring)?", ["Data Link Layer", "Physical Layer", "Network Layer", "Application Layer"], "Physical Layer", "The Physical Layer specifies how nodes are physically arranged in a network topology."),
Q("UE", "EASY", "What happens to data at the Presentation layer?", ["It gets an IP address", "It is routed to another country", "It is translated, compressed, or encrypted", "It is broken into raw bits"], "It is translated, compressed, or encrypted", "The Presentation Layer (Layer 6) prepares the data structure (syntax), compresses it, and encrypts it for security."),
Q("UE", "MEDIUM", "What is the primary role of the MAC sub-layer in the Data Link Layer?", ["It handles IP routing", "It is a link between the Logical Link Control (LLC) layer and the physical layer for transferring packets", "It establishes the session", "It provides user interface"], "It is a link between the Logical Link Control (LLC) layer and the physical layer for transferring packets", "The Media Access Control (MAC) layer physically addresses frames and interfaces directly with the hardware media."),
Q("UE", "MEDIUM", "Why is the Transport layer considered 'End-to-End'?", ["It connects physical cables together", "It ensures the complete message reaches the final destination without error, crossing multiple links", "It translates IP addresses", "It runs in the application"], "It ensures the complete message reaches the final destination without error, crossing multiple links", "Unlike Data Link which is hop-to-hop, Transport ensures the entire conversation between the source and destination is reliable."),
Q("UE", "MEDIUM", "Which of these protocols works at the Data Link Layer?", ["IP", "TCP", "PPP (Point-to-Point Protocol)", "HTTP"], "PPP (Point-to-Point Protocol)", "PPP, Frame Relay, and ATM are protocols that operate at the Data Link layer."),
Q("UE", "HARD", "How does IPv6 solve the problem of address exhaustion experienced by IPv4?", ["By using a 64-bit address", "By reusing private IP addresses on the internet", "By using a 128-bit hexadecimal address, offering vastly more unique addresses", "By switching to MAC addresses"], "By using a 128-bit hexadecimal address, offering vastly more unique addresses", "IPv6 expands the address space from 32 bits (IPv4) to 128 bits, providing virtually unlimited IP addresses."),
Q("UE", "HARD", "Why is UDP described as an 'unreliable' protocol?", ["Because it frequently crashes computers", "Because it is slow", "Because the receiver does not send acknowledgments and the sender does not wait for them", "Because it cannot send video files"], "Because the receiver does not send acknowledgments and the sender does not wait for them", "UDP is connectionless. It simply sends data without verifying if it was received, making it 'unreliable' but very fast (good for streaming).")
];

const poss = [
Q("POSSIBLE QNS", "EASY", "Which layer is Layer 3 in the OSI model?", ["Physical", "Data Link", "Network", "Transport"], "Network", "The Network Layer is Layer 3, handling IP addresses and routing."),
Q("POSSIBLE QNS", "EASY", "Which IP version uses numbers separated by dots (e.g., 192.168.1.1)?", ["IPv6", "IPv4", "IPv5", "MAC v4"], "IPv4", "IPv4 uses the dotted-decimal notation consisting of four octets."),
Q("POSSIBLE QNS", "EASY", "A DHCP server can automatically assign which of the following?", ["A new graphics card", "An IP Address, Subnet Mask, Default Gateway, and DNS Server", "A physical MAC address", "An antivirus license"], "An IP Address, Subnet Mask, Default Gateway, and DNS Server", "DHCP automates network configuration by providing all necessary logical addressing details."),
Q("POSSIBLE QNS", "MEDIUM", "What is 'Packetizing'?", ["Compressing a file into a ZIP folder", "The process at the Network Layer where data from the upper layer is converted into packets", "Encrypting an email", "Transmitting a broadcast"], "The process at the Network Layer where data from the upper layer is converted into packets", "Packetizing is the process of encapsulating upper-layer segments into Network layer IP packets."),
Q("POSSIBLE QNS", "MEDIUM", "If an IP address is 10.5.5.5, what Class does it belong to?", ["Class A", "Class B", "Class C", "Class D"], "Class A", "The first octet '10' falls within the 0 to 126 range, which denotes a Class A address."),
Q("POSSIBLE QNS", "HARD", "In the OSI model, what does the Application Layer handle?", ["Error control across a single link", "Network transparency, resource allocation, and providing a window for user processes", "Synchronizing checkpoints", "Translating MAC to IP"], "Network transparency, resource allocation, and providing a window for user processes", "Layer 7 (Application) interfaces with the user's software, managing tasks like file transfers (FTAM) and mail services."),
Q("POSSIBLE QNS", "HARD", "What is an advantage of the OSI Model?", ["It is cheap to buy", "It supports connectionless and connection-oriented services, and its layered approach makes it adaptable and secure", "It eliminates the need for routers", "It has only one layer to learn"], "It supports connectionless and connection-oriented services, and its layered approach makes it adaptable and secure", "The OSI model's modular architecture means changes in one layer don't necessarily require changes in others, providing flexibility and security.")
];

const all_questions = [...questions_unit3, ...cat1, ...cat2, ...ue, ...poss];

async function insertUnit3() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = all_questions.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} questions for Unit 3.`);
        } else {
            console.log("No new questions for Unit 3 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit3();
