const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a5d16dbf29e866583f45d27";

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const questions_unit3_extra = [
// ╔══════════════════════════════════╗
// ║          QUIZ (15 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "Which block of IP addresses is reserved for Class B private networks?", ["10.0.0.0 - 10.255.255.255", "172.16.0.0 - 172.31.255.255", "192.168.0.0 - 192.168.255.255", "127.0.0.0 - 127.255.255.255"], "172.16.0.0 - 172.31.255.255", "The 172.16.0.0 to 172.31.255.255 range is specifically reserved for Class B private networks."),
Q("QUIZ", "EASY", "What does it mean if an IPv6 address contains a double colon '::'?", ["It is a broadcast address", "All sections between them contain only zeroes", "It is an invalid address", "It is a private MAC address"], "All sections between them contain only zeroes", "In IPv6, a double colon is used to compress the address by replacing consecutive sections of zeroes."),
Q("QUIZ", "EASY", "Which OSI layer specifies the mechanical, electrical, and procedural network interface specifications?", ["Data Link Layer", "Physical Layer", "Network Layer", "Transport Layer"], "Physical Layer", "The Physical Layer handles the actual physical connection, including electrical voltage and mechanical pins."),
Q("QUIZ", "EASY", "In the OSI model, which layer is responsible for error-free transfer of data frames?", ["Data Link Layer", "Transport Layer", "Physical Layer", "Session Layer"], "Data Link Layer", "The Data Link Layer is responsible for the error-free transfer of frames across a single physical link."),
Q("QUIZ", "EASY", "What does the abbreviation 'LLC' stand for in the context of the Data Link Layer?", ["Logical Link Control", "Local LAN Connection", "Linear Link Cable", "Logical Local Control"], "Logical Link Control", "The Data Link layer contains two sub-layers: the Logical Link Control (LLC) layer and the Media Access Control (MAC) layer."),
Q("QUIZ", "MEDIUM", "What is the primary function of the MAC sub-layer?", ["To encrypt passwords", "To act as a link between the Logical Link Control layer and the network's physical layer", "To route IP packets globally", "To manage user accounts"], "To act as a link between the Logical Link Control layer and the network's physical layer", "The MAC sub-layer controls access to the physical transmission medium and physically addresses the frames."),
Q("QUIZ", "MEDIUM", "Which of the following layers performs 'Packetizing'?", ["Transport Layer", "Network Layer", "Data Link Layer", "Presentation Layer"], "Network Layer", "The Network Layer receives data from the upper layers and converts them into packets, a process called Packetizing."),
Q("QUIZ", "MEDIUM", "Why is the Transport Layer considered responsible for 'end-to-end' error control?", ["It only checks errors on a single cable", "It ensures that the message reaches the final destination machine completely and without any errors", "It uses MAC addresses", "It runs on the physical hardware only"], "It ensures that the message reaches the final destination machine completely and without any errors", "Unlike the Data Link Layer which checks for errors per physical link (hop-by-hop), the Transport Layer provides end-to-end error and flow control across the entire network path."),
Q("QUIZ", "MEDIUM", "In a 'Connectionless Service' at the Transport Layer, how are segments treated?", ["As a continuous stream of data", "As individual packets that travel different routes to reach the destination", "As encrypted files", "As broadcast messages to all nodes"], "As individual packets that travel different routes to reach the destination", "In a connectionless service (like UDP), each segment is an independent packet that may take a different path and arrive out of order."),
Q("QUIZ", "MEDIUM", "Which layer is responsible for adding 'checkpoints' to a data stream?", ["Transport Layer", "Session Layer", "Application Layer", "Physical Layer"], "Session Layer", "The Session Layer provides synchronization by adding checkpoints. If the connection fails, it can resume from the last checkpoint rather than starting over."),
Q("QUIZ", "HARD", "Which of the following protocols is used for Directory services at the Application Layer?", ["X.500", "SMTP", "UDP", "IPSEC"], "X.500", "X.500 is a standard for directory services at the Application Layer, providing global information about various objects."),
Q("QUIZ", "HARD", "Which layer is mainly concerned with the syntax and semantics of the information exchanged?", ["Session Layer", "Application Layer", "Presentation Layer", "Network Layer"], "Presentation Layer", "The Presentation Layer translates data so that the syntax and semantics are understood by both the sender and receiver systems."),
Q("QUIZ", "HARD", "Which protocol operates at the Presentation Layer?", ["NetBIOS", "SSL/TLS", "SMTP", "PPP"], "SSL/TLS", "Secure Sockets Layer (SSL) and Transport Layer Security (TLS) operate at the Presentation Layer, handling encryption and secure data translation."),
Q("QUIZ", "HARD", "What is one major disadvantage of the OSI model regarding how its layers function?", ["It uses too many cables", "Layers cannot work in parallel; each layer must wait to receive data from the previous layer", "It does not support wireless networks", "It lacks a Transport Layer"], "Layers cannot work in parallel; each layer must wait to receive data from the previous layer", "The strict hierarchical nature of the OSI model means processing is strictly sequential, which can introduce latency compared to parallel processing models."),
Q("QUIZ", "HARD", "What is the broadcast address for a host with IP 129.79.149.0 using the default subnet mask?", ["129.79.149.0", "129.79.255.255", "129.79.149.255", "129.255.255.255"], "129.79.255.255", "129.x.x.x is a Class B address, meaning the default subnet mask is 255.255.0.0. The broadcast address replaces the host bits with all 1s, resulting in 129.79.255.255."),

// ╔══════════════════════════════════╗
// ║        EXERCISE (15 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "Which type of IP address is used strictly for internal communication and is not visible on the internet?", ["Public IP", "Private IP", "Dynamic IP", "Loopback IP"], "Private IP", "Private IP addresses are non-routable on the internet and are used exclusively within local area networks (LANs)."),
Q("EXERCISE", "EASY", "What does 'DHCP Reservation' mean?", ["Reserving bandwidth for a user", "Permanently assigning a specific IP address to a specific device like a printer", "Renting a server", "Deleting an IP address"], "Permanently assigning a specific IP address to a specific device like a printer", "DHCP Reservation links a specific IP address to a device's MAC address, ensuring it always receives the same IP."),
Q("EXERCISE", "EASY", "Which class of IP address ranges from 192 to 223?", ["Class A", "Class B", "Class C", "Class D"], "Class C", "Class C IP addresses fall within the 192 to 223 range in the first octet."),
Q("EXERCISE", "EASY", "What is a 'DHCP Lease'?", ["The physical hardware of the server", "The amount of time an IP address is temporarily assigned to a computer", "A protocol for encrypting data", "The cost of the network"], "The amount of time an IP address is temporarily assigned to a computer", "A lease ensures IP addresses are returned to the pool when devices disconnect, preventing the server from running out of IPs."),
Q("EXERCISE", "EASY", "What is the primary function of a router at the Network Layer?", ["To detect hardware collisions", "To determine the best optimal path to move data from source to destination", "To encrypt web traffic", "To assign MAC addresses"], "To determine the best optimal path to move data from source to destination", "Routing involves analyzing the network and selecting the best path for packets to reach their destination."),
Q("EXERCISE", "MEDIUM", "What is the function of 'Bit synchronization' at the Physical Layer?", ["To compress video files", "To provide a clock that controls both sender and receiver at the bit level", "To translate IP to MAC", "To prevent unauthorized access"], "To provide a clock that controls both sender and receiver at the bit level", "Bit synchronization ensures that the sender and receiver are perfectly timed so that bits are read correctly."),
Q("EXERCISE", "MEDIUM", "How is 'Error Control' achieved at the Data Link Layer?", ["By encrypting the payload", "By adding a calculated CRC (Cyclic Redundancy Check) value to the frame's trailer", "By routing through a firewall", "By using a DHCP server"], "By adding a calculated CRC (Cyclic Redundancy Check) value to the frame's trailer", "The receiver calculates its own CRC and compares it to the trailer. If they don't match, an error occurred and the frame is rejected."),
Q("EXERCISE", "MEDIUM", "Which of the following is considered a 'Connection-oriented' service at the Transport Layer?", ["UDP", "IP", "TCP", "ICMP"], "TCP", "Transmission Control Protocol (TCP) establishes a firm connection before data transfer, ensuring reliability and ordered delivery."),
Q("EXERCISE", "MEDIUM", "At which layer does the protocol 'ICMP' operate?", ["Application Layer", "Network Layer", "Data Link Layer", "Physical Layer"], "Network Layer", "Internet Control Message Protocol (ICMP), used by tools like 'ping', operates at the Network Layer (Layer 3)."),
Q("EXERCISE", "MEDIUM", "What is the primary role of the 'Dialog Controller' in the Session Layer?", ["To route packets", "To start and manage communication between two systems in half-duplex or full-duplex", "To translate ASCII to EBCDIC", "To compress files"], "To start and manage communication between two systems in half-duplex or full-duplex", "The Session Layer manages the dialogue, determining whose turn it is to transmit and in what mode."),
Q("EXERCISE", "HARD", "Which of the following protocols operates at the Data Link Layer?", ["HTTP", "SSL", "NetBIOS", "PPP (Point-to-Point Protocol)"], "PPP (Point-to-Point Protocol)", "PPP, ATM, and Frame Relay are examples of Data Link Layer protocols that manage direct point-to-point physical links."),
Q("EXERCISE", "HARD", "Why is the Session layer and Presentation layer often criticized in the OSI model?", ["They are too complex to implement", "They aren't as practically useful or distinct as other layers in real-world networking (like TCP/IP)", "They slow down the physical cables", "They only work on wireless networks"], "They aren't as practically useful or distinct as other layers in real-world networking (like TCP/IP)", "A known disadvantage of the OSI model is that the Session and Presentation layers are often bundled directly into the Application layer in practical models like TCP/IP."),
Q("EXERCISE", "HARD", "What does 'Service-point addressing' mean at the Transport layer?", ["Assigning a physical MAC address to a NIC", "Adding a port address to the header to transmit the message to the correct software process", "Resolving a URL to an IP address", "Assigning a subnet mask"], "Adding a port address to the header to transmit the message to the correct software process", "Because a single computer runs many processes simultaneously, port addresses (service points) ensure data reaches the correct application (e.g., Port 80 for web)."),
Q("EXERCISE", "HARD", "What is the main advantage of the OSI model's layered architecture?", ["It eliminates the need for physical cables", "It has the flexibility to adapt to many protocols and allows for specialized troubleshooting per layer", "It processes all data instantly in parallel", "It guarantees 100% security against hackers"], "It has the flexibility to adapt to many protocols and allows for specialized troubleshooting per layer", "The OSI model's modularity means developers can innovate at one layer without rewriting the protocols for all other layers."),
Q("EXERCISE", "HARD", "In an IPv4 address, if the network class is Class A, how many bits are used for the host address?", ["8 bits", "16 bits", "24 bits", "32 bits"], "24 bits", "Class A addresses use 8 bits for the network ID, leaving the remaining 24 bits for the host ID, allowing millions of hosts per network."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (12 Qns)          ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "Which block of IP addresses ranges from 192.168.0.0 to 192.168.255.255?", ["Class A Private", "Class B Private", "Class C Private", "Class D Public"], "Class C Private", "This is the reserved block for Class C private networks, very commonly used in home routers."),
Q("CAT 1", "EASY", "What does it mean if an IP address is 'Private'?", ["It cannot connect to the internet directly and is only used within a local network", "It belongs to the government", "It is highly encrypted", "It changes every second"], "It cannot connect to the internet directly and is only used within a local network", "Private IPs are non-routable on the public internet; they require a router using NAT to access the web."),
Q("CAT 1", "EASY", "Which type of IP address can be accessed globally?", ["Private IP", "Public IP", "APIPA", "Loopback"], "Public IP", "Public IP addresses are unique across the entire internet and can be accessed globally."),
Q("CAT 1", "EASY", "What is the primary function of NAT?", ["To provide a firewall", "To translate local private addresses to a routable public address", "To resolve DNS queries", "To assign MAC addresses"], "To translate local private addresses to a routable public address", "Network Address Translation (NAT) masks internal private IPs behind a single public IP assigned to the router."),
Q("CAT 1", "MEDIUM", "What is the role of the 'Logical Link Control' (LLC) sub-layer?", ["To transmit raw bits over fiber optics", "To identify the network layer protocol from the header and provide flow control", "To manage user passwords", "To assign dynamic IP addresses"], "To identify the network layer protocol from the header and provide flow control", "The LLC is the upper sub-layer of the Data Link layer, interfacing with the Network layer and handling flow/error control."),
Q("CAT 1", "MEDIUM", "Which protocol is known for 'unreliable' transmission at the Transport Layer?", ["TCP", "UDP", "IP", "FTP"], "UDP", "User Datagram Protocol (UDP) is unreliable because it does not send acknowledgments or guarantee ordered delivery."),
Q("CAT 1", "MEDIUM", "At which OSI layer does data compression occur?", ["Application Layer", "Presentation Layer", "Session Layer", "Data Link Layer"], "Presentation Layer", "The Presentation Layer reduces the number of bits to be transmitted through data compression, essential for multimedia."),
Q("CAT 1", "MEDIUM", "What is the process of 'Framing'?", ["Translating domain names", "Adding a header (destination/source address) and trailer to raw bit streams to create packets", "Encrypting the data", "Connecting cables to a switch"], "Adding a header (destination/source address) and trailer to raw bit streams to create packets", "Framing occurs at the Data Link layer, packaging raw bits into manageable frames with physical addressing."),
Q("CAT 1", "HARD", "Which OSI layer is responsible for defining 'Transmission Modes' such as Simplex, Half-Duplex, and Full-Duplex?", ["Data Link Layer", "Physical Layer", "Session Layer", "Transport Layer"], "Physical Layer", "The Physical Layer defines how data physically flows between two connected devices, including the transmission mode directionality."),
Q("CAT 1", "HARD", "What is 'Internetworking' as defined in the Network Layer functions?", ["Browsing the web", "Providing a logical connection and routing between entirely different devices and networks", "Sharing printers on a LAN", "Connecting two PCs with a crossover cable"], "Providing a logical connection and routing between entirely different devices and networks", "Internetworking is the process of connecting different networks together globally, which is the primary job of the Network layer and routers."),
Q("CAT 1", "HARD", "Why are protocols like MPEG and SSL mapped to the Presentation Layer?", ["Because they handle physical routing", "Because they deal with data format translation, compression, and encryption respectively", "Because they are email protocols", "Because they manage MAC addresses"], "Because they deal with data format translation, compression, and encryption respectively", "MPEG handles video compression/formatting, and SSL handles encryption, which perfectly aligns with the Presentation layer's responsibilities."),
Q("CAT 1", "HARD", "How does a router utilize a 'Broadcast Address'?", ["It blocks it completely", "It uses it to send data to all host devices connected to that specific network segment", "It routes it to the global internet", "It converts it to a private IP"], "It uses it to send data to all host devices connected to that specific network segment", "A broadcast address enables a message to reach every single node on a local network simultaneously."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (12 Qns)          ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "What is the main function of the Application Layer?", ["To compress images", "To provide network services directly to end-user applications", "To route packets", "To establish physical connections"], "To provide network services directly to end-user applications", "Layer 7 acts as a window for users and application processes to access network services like email and file transfer."),
Q("CAT 2", "EASY", "Which layer is responsible for 'Bit rate control'?", ["Physical Layer", "Network Layer", "Session Layer", "Presentation Layer"], "Physical Layer", "The Physical Layer defines the transmission rate, ensuring the correct number of bits are sent per second."),
Q("CAT 2", "EASY", "In an Ethernet network, what does a system do if it receives a broadcast message NOT addressed specifically to its application?", ["It forwards it to the internet", "It discards the message", "It crashes", "It sends an error to the sender"], "It discards the message", "In a broadcast network, all systems receive every message, but they discard messages that are not meant for them."),
Q("CAT 2", "EASY", "What does 'FTAM' stand for in the Application Layer?", ["File Transfer, Access, and Management", "Fast Transport and Memory", "Fiber Transfer and Modulation", "Frame Translation and Mapping"], "File Transfer, Access, and Management", "FTAM is an Application layer service that allows users to access, retrieve, and manage files on a remote computer."),
Q("CAT 2", "MEDIUM", "What does 'Flow Control' achieve at the Transport Layer?", ["It stops physical collisions on the wire", "It ensures the sender does not overwhelm the receiver, performed end-to-end", "It assigns IP addresses", "It encrypts the data stream"], "It ensures the sender does not overwhelm the receiver, performed end-to-end", "End-to-end flow control at the Transport Layer manages the rate of data transmission to match the receiver's processing capabilities."),
Q("CAT 2", "MEDIUM", "Which protocol works at the Session Layer to establish and manage interactions?", ["TCP", "NetBIOS", "IPv6", "SMTP"], "NetBIOS", "NetBIOS (Network Basic Input/Output System) is a classic example of a Session Layer protocol."),
Q("CAT 2", "MEDIUM", "Why is the OSI model considered a 'Standard Model'?", ["Because it is the only model used today", "Because it provides a universal, theoretical framework that describes how any network should operate", "Because it is entirely open-source software", "Because it was created by Microsoft"], "Because it provides a universal, theoretical framework that describes how any network should operate", "The OSI model provides a standardized reference framework, ensuring diverse networking technologies can be understood and developed coherently."),
Q("CAT 2", "MEDIUM", "What is an IPv6 address composed of?", ["32 bits in decimal format", "64 bits in octal format", "128 bits in hexadecimal format", "256 bits in binary format"], "128 bits in hexadecimal format", "IPv6 uses 128 binary bits expressed as 8 groups of hexadecimal numbers separated by colons."),
Q("CAT 2", "HARD", "How does 'Segmentation and Reassembly' function when using TCP?", ["It encrypts data before sending", "It divides large messages into smaller segments, assigns sequence numbers, and reassembles them in order at the destination", "It physically cuts the network cable into segments", "It compresses files to save bandwidth"], "It divides large messages into smaller segments, assigns sequence numbers, and reassembles them in order at the destination", "The Transport layer breaks down upper-layer data into segments. Sequence numbers guarantee the data is rebuilt in the exact original order."),
Q("CAT 2", "HARD", "What does it mean if an IP address has a '0' in its host portion (e.g., 192.168.1.0)?", ["It is a broadcast address", "It is the network address", "It is an invalid address", "It is a private MAC address"], "It is the network address", "In classful IP addressing, an address with all zeroes in the host portion represents the network itself, not an individual host."),
Q("CAT 2", "HARD", "Which of the following is a disadvantage of the OSI model?", ["It doesn't define any particular protocol, making it purely theoretical", "It requires expensive hardware", "It only supports IPv4", "It has too few layers to be useful"], "It doesn't define any particular protocol, making it purely theoretical", "Unlike TCP/IP which is a practical protocol suite, OSI is a reference model that does not mandate specific protocols, making it somewhat abstract."),
Q("CAT 2", "HARD", "What is a 'Connection-oriented' service?", ["A service that requires a physical cable", "A service like TCP that establishes a reliable connection with the destination before delivering packets in a single route", "A service like UDP that broadcasts packets everywhere", "A service that uses radio waves"], "A service like TCP that establishes a reliable connection with the destination before delivering packets in a single route", "Connection-oriented services ensure reliability by establishing a session (handshake) before transmitting any data."),

// ╔══════════════════════════════════╗
// ║            UE (12 Qns)           ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "Which layer is known as the 'Syntax Layer'?", ["Network Layer", "Presentation Layer", "Application Layer", "Session Layer"], "Presentation Layer", "The Presentation Layer is also known as the syntax layer because it deals with the syntax and semantics of data."),
Q("UE", "EASY", "Which of the following describes an IP Address?", ["A physical MAC address burned into a NIC", "A 32-bit logical address used to uniquely identify a device on a network", "A name like www.google.com", "A secret password for Wi-Fi"], "A 32-bit logical address used to uniquely identify a device on a network", "An IP Address is a unique numerical identifier that operates at the logical (Network) layer."),
Q("UE", "EASY", "Which layer is Layer 4 in the OSI model?", ["Data Link Layer", "Network Layer", "Transport Layer", "Session Layer"], "Transport Layer", "Layer 4 is the Transport Layer, responsible for reliable end-to-end data delivery."),
Q("UE", "EASY", "What does 'DHCP' stand for?", ["Dynamic Host Configuration Protocol", "Data Handling Control Protocol", "Digital Host Connection Provider", "Dynamic Hardware Configuration Process"], "Dynamic Host Configuration Protocol", "DHCP automates the assignment of IP addresses, subnet masks, and gateways to network devices."),
Q("UE", "MEDIUM", "What is the primary function of a 'DHCP Server'?", ["To block hackers", "To assign IP addresses dynamically so they don't have to be configured manually", "To host websites", "To translate domain names"], "To assign IP addresses dynamically so they don't have to be configured manually", "DHCP servers manage a pool of IP addresses and automatically lease them to devices joining the network."),
Q("UE", "MEDIUM", "Which device uses a 'Routing Table' to make decisions?", ["Hub", "Switch", "Router", "Repeater"], "Router", "Routers operate at the Network Layer and use dynamically updated routing tables to determine the best path for packets."),
Q("UE", "MEDIUM", "What does 'Synchronization' do at the Session Layer?", ["It matches the clock speeds of the CPU and RAM", "It adds checkpoints to the data stream to prevent total data loss if the connection drops", "It translates IP to MAC", "It compresses files"], "It adds checkpoints to the data stream to prevent total data loss if the connection drops", "If a connection drops during a large file transfer, synchronization checkpoints allow the transfer to resume from the last point instead of starting over."),
Q("UE", "MEDIUM", "Which statement about NAT is true?", ["It makes the internet slower", "It improves security by hiding internal IP addresses from hackers on the outside", "It assigns MAC addresses to printers", "It decrypts SSL certificates"], "It improves security by hiding internal IP addresses from hackers on the outside", "By replacing private IPs with a public IP at the router, NAT effectively masks the internal network structure from the outside world."),
Q("UE", "HARD", "How does 'Flow Control' at the Data Link layer differ from 'Flow Control' at the Transport layer?", ["Data Link manages speed between two adjacent nodes, Transport manages speed from the original sender to final receiver", "There is no difference", "Data link uses TCP, Transport uses MAC", "Data link compresses data, Transport encrypts it"], "Data Link manages speed between two adjacent nodes, Transport manages speed from the original sender to final receiver", "Hop-by-hop flow control (Data Link) prevents overwhelming the next switch/router, while end-to-end flow control (Transport) prevents overwhelming the final destination computer."),
Q("UE", "HARD", "Which class of IP address is represented by the range 224 to 247?", ["Class A", "Class B", "Class C", "Class D (Reserved for Multicast)"], "Class D (Reserved for Multicast)", "Class D addresses (224.x.x.x to 239.x.x.x) are reserved for multicasting purposes."),
Q("UE", "HARD", "In an IPv6 address, what is the meaning of a double colon (::)?", ["It marks the end of the address", "It replaces one or more consecutive sections of only zeroes to compress the address format", "It separates the network ID from the host ID", "It indicates a broadcast address"], "It replaces one or more consecutive sections of only zeroes to compress the address format", "IPv6 uses the double colon '::' as a shorthand to represent multiple blocks of 0000, making the address easier to read and type."),
Q("UE", "HARD", "Which OSI layer is responsible for converting 'sender-dependent format' into a 'common format'?", ["Application Layer", "Presentation Layer", "Transport Layer", "Data Link Layer"], "Presentation Layer", "The Presentation Layer translates data from the specific format used by the application into a generic network format for transmission."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (10 Qns)      ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "Which layer of the OSI model establishes, maintains, and deactivates the physical connection?", ["Session Layer", "Transport Layer", "Physical Layer", "Network Layer"], "Physical Layer", "The Physical Layer is strictly responsible for the actual hardware connection and raw bit transmission."),
Q("POSSIBLE QNS", "EASY", "What is the primary service provided by the Internet Protocol (IP)?", ["Encryption and Decryption", "Addressing and Fragmentation", "Error checking", "File transfer"], "Addressing and Fragmentation", "IP provides logical addressing (IP addresses) and fragmentation of packets if they are too large for the network."),
Q("POSSIBLE QNS", "EASY", "Which is a valid Class A private IP address?", ["192.168.1.1", "172.16.5.5", "10.0.0.5", "8.8.8.8"], "10.0.0.5", "The entire 10.0.0.0/8 block is reserved for Class A private networks."),
Q("POSSIBLE QNS", "MEDIUM", "What is the function of the MAC sub-layer?", ["To encrypt traffic", "To transfer packets over the network physically and link with the LLC layer", "To resolve DNS", "To route between different networks"], "To transfer packets over the network physically and link with the LLC layer", "The Media Access Control layer directly interfaces with the physical medium, placing frames onto the wire or air."),
Q("POSSIBLE QNS", "MEDIUM", "Which OSI layer uses 'Frames' as its protocol data unit?", ["Physical Layer", "Data Link Layer", "Network Layer", "Transport Layer"], "Data Link Layer", "The Data Link layer encapsulates packets into Frames, adding MAC addresses for local delivery."),
Q("POSSIBLE QNS", "MEDIUM", "What makes UDP a preferred protocol for video streaming despite being 'unreliable'?", ["It encrypts the video", "It is connectionless and doesn't wait for acknowledgments, making it much faster than TCP", "It guarantees every pixel is delivered", "It compresses the video automatically"], "It is connectionless and doesn't wait for acknowledgments, making it much faster than TCP", "UDP sacrifices reliability (no error checking or retransmission) for speed, which is ideal for real-time video where minor packet loss is acceptable."),
Q("POSSIBLE QNS", "HARD", "How does a router process an IP address ending in 255 (e.g., 192.168.1.255) on a default Class C network?", ["It sends it to the internet", "It routes it to the local switch", "It treats it as a broadcast address and sends the message to all hosts on that network", "It drops the packet"], "It treats it as a broadcast address and sends the message to all hosts on that network", "An IP with all host bits set to 1 is the broadcast address. The router forwards the packet to every device on that specific subnet."),
Q("POSSIBLE QNS", "HARD", "What does 'Service-point addressing' accomplish in the Transport Layer?", ["It assigns MAC addresses", "It ensures that data is delivered not just to the correct computer, but to the correct specific software process running on that computer", "It translates domain names", "It provides power to the NIC"], "It ensures that data is delivered not just to the correct computer, but to the correct specific software process running on that computer", "Using port numbers, the Transport layer directs incoming data to the correct application, like sending Port 80 traffic to a web browser."),
Q("POSSIBLE QNS", "HARD", "Which statement best describes 'Internetworking' at the Network Layer?", ["Creating a local LAN", "Connecting different logical networks together and finding the best path between them", "Encrypting data across a WAN", "Assigning DHCP leases"], "Connecting different logical networks together and finding the best path between them", "Internetworking is the core function of routers at the Network layer, logically bridging different networks globally."),
Q("POSSIBLE QNS", "HARD", "What is one reason why 'Layers cannot work in parallel' is a disadvantage of the OSI model?", ["It makes cables too hot", "Data must be processed sequentially, adding headers at each layer step-by-step, which can introduce processing delays", "It prevents wireless communication", "It allows hackers to intercept data easily"], "Data must be processed sequentially, adding headers at each layer step-by-step, which can introduce processing delays", "Because each layer depends strictly on the one above or below it, the system cannot process multiple layers simultaneously, slightly slowing down packet preparation.")
];

async function insertUnit3Extra() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = questions_unit3_extra.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} EXTRA questions for Unit 3.`);
        } else {
            console.log("No new EXTRA questions for Unit 3 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit3Extra();
