const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a49ecb638bb37720e3e9194"; // COMPUTER ARCHITECTURE AND ASSEMBLY PROGRAMMING LANGUAGE

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const ca_unit1_part4 = [
// ╔══════════════════════════════════╗
// ║           QUIZ (8 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "Which logic gate outputs 1 only if all its inputs are 1?", ["OR Gate", "XOR Gate", "NOT Gate", "AND Gate"], "AND Gate", "An AND gate is a fundamental logic operation used heavily in the ALU for bitwise masking."),
Q("QUIZ", "MEDIUM", "What is an advantage of 'Register-Register Architecture' found in RISC?", ["It reduces memory access bottlenecks and improves performance", "It eliminates the need for cache memory", "It requires no electricity", "It uses the hard drive directly for math"], "It reduces memory access bottlenecks and improves performance", "Since all math happens inside CPU registers, the CPU doesn't have to wait for the slow RAM during calculation steps."),
Q("QUIZ", "HARD", "In the context of the CPU pipeline, what is a 'Pipeline Hazard'?", ["A fire inside the CPU", "A situation where the next instruction cannot execute in the following clock cycle due to data dependencies or branching", "A virus that infects the motherboard", "A physical defect in the silicon"], "A situation where the next instruction cannot execute in the following clock cycle due to data dependencies or branching", "Hazards (like waiting for a previous math result) cause the pipeline to stall, reducing efficiency."),
Q("QUIZ", "MEDIUM", "What does a 'Binary Adder' output besides the sum?", ["A multiplication product", "A carry bit", "A floating-point fraction", "An error code"], "A carry bit", "When adding two binary 1s (1 + 1), the sum is 0, and a '1' is carried over to the next significant bit."),
Q("QUIZ", "EASY", "What is the function of the 'Stack Pointer'?", ["To manage the printer queue", "To track the current top of the memory stack", "To point to the monitor", "To delete files"], "To track the current top of the memory stack", "The SP register ensures the CPU knows exactly where to push or pop the next piece of data."),
Q("QUIZ", "HARD", "How does a 'Micro-programmed Control Unit' handle complex instructions?", ["By exploding", "By translating them into a longer sequence of simpler microinstructions stored in ROM", "By sending them to the GPU", "By ignoring them"], "By translating them into a longer sequence of simpler microinstructions stored in ROM", "Instead of complex physical wiring, it runs a tiny hidden program that breaks the big instruction into smaller hardware steps."),
Q("QUIZ", "MEDIUM", "What defines the 'Execution Cycle'?", ["Fetching the instruction from RAM", "Decoding the Opcode", "Performing the actual mathematical, logical, or data transfer operation specified by the instruction", "Turning on the computer"], "Performing the actual mathematical, logical, or data transfer operation specified by the instruction", "This is the cycle where the real 'work' of the program is actually done by the ALU and registers."),
Q("QUIZ", "HARD", "Which addressing mode is used in `MOV AX, [BX+SI]`?", ["Immediate Mode", "Relative Mode", "Indexed Mode", "Register Mode"], "Indexed Mode", "Indexed addressing combines a base register (BX) and a source index register (SI) to calculate the final memory address, great for 2D arrays."),

// ╔══════════════════════════════════╗
// ║         EXERCISE (8 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "Which CPU component fetches, decodes, and executes instructions?", ["The Hard Disk", "The Control Unit (CU)", "The Optical Drive", "The Keyboard"], "The Control Unit (CU)", "The CU acts as the orchestrator, directing all other parts of the CPU through the instruction cycle."),
Q("EXERCISE", "MEDIUM", "What happens when an instruction calls a function regarding the Stack?", ["The stack is erased", "The return address and local variables are 'Pushed' onto the stack to create a new stack frame", "The stack pointer is reset to zero", "The stack moves to the hard drive"], "The return address and local variables are 'Pushed' onto the stack to create a new stack frame", "This ensures that when the function finishes, the CPU knows exactly where to return to in the original code."),
Q("EXERCISE", "HARD", "Why does CISC architecture have 'Fewer Registers' generally compared to RISC?", ["Because registers are slow", "Because many CISC operations can directly access memory, reducing the need to hold intermediate data in registers", "Because CISC chips are smaller physically", "Because CISC cannot do math"], "Because many CISC operations can directly access memory, reducing the need to hold intermediate data in registers", "Since CISC can do math directly on RAM addresses, it doesn't need 32 general-purpose registers to temporarily hold data like RISC does."),
Q("EXERCISE", "MEDIUM", "What is the purpose of 'Instruction Pipelining'?", ["To transport data over the internet", "To process multiple instructions simultaneously by dividing execution into stages, increasing overall throughput", "To cool the CPU", "To encrypt passwords"], "To process multiple instructions simultaneously by dividing execution into stages, increasing overall throughput", "It acts like an assembly line, keeping all parts of the CPU busy at all times."),
Q("EXERCISE", "HARD", "What does a 'Logical Shift Left' do to a binary number?", ["It divides the number by 2", "It multiplies the number by 2 by shifting all bits left and inserting a 0 at the least significant bit (LSB)", "It reverses the bits", "It changes all 1s to 0s"], "It multiplies the number by 2 by shifting all bits left and inserting a 0 at the least significant bit (LSB)", "Shifting binary left is the digital equivalent of adding a zero to a decimal number (multiplying by 10), but in base-2 it multiplies by 2."),
Q("EXERCISE", "EASY", "Which memory is the absolute fastest in a computer system?", ["Main Memory (RAM)", "Cache Memory", "CPU Registers", "Solid State Drive (SSD)"], "CPU Registers", "Registers are built directly into the CPU core and operate at the exact same speed as the processor itself."),
Q("EXERCISE", "MEDIUM", "What is the 'Instruction Set Architecture' (ISA)?", ["The physical blueprint of the motherboard", "The defined set of instructions, registers, and addressing modes that the CPU hardware can understand and execute", "A type of computer virus", "The programming language Python"], "The defined set of instructions, registers, and addressing modes that the CPU hardware can understand and execute", "The ISA is the rulebook that compilers use to turn high-level code into executable machine code for a specific CPU family."),
Q("EXERCISE", "HARD", "What is an 'Incrementer' circuit used for?", ["Subtracting numbers", "Adding exactly 1 to an input value, commonly used to advance the Program Counter", "Multiplying by 10", "Clearing the screen"], "Adding exactly 1 to an input value, commonly used to advance the Program Counter", "An incrementer is a specialized, faster adder circuit hardwired to just add one, essential for stepping through sequential instructions."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "What does 'ALU' stand for?", ["Automatic Line User", "Arithmetic Logic Unit", "Array Loader Utility", "Asynchronous Local Unit"], "Arithmetic Logic Unit", "The ALU handles all the math and bitwise logic inside the CPU."),
Q("CAT 1", "MEDIUM", "What is the purpose of the 'Fetch Cycle'?", ["To perform an addition", "To retrieve the next instruction from memory and place it in the Instruction Register", "To save a file to disk", "To handle an interrupt"], "To retrieve the next instruction from memory and place it in the Instruction Register", "Before the CPU can execute a command, it must fetch it from RAM using the address in the Program Counter."),
Q("CAT 1", "HARD", "What is the advantage of 'Superscalar Execution'?", ["It allows the CPU to run without electricity", "It allows multiple instructions to be issued and executed in parallel in a single clock cycle using multiple execution units (e.g., two ALUs)", "It makes the CPU waterproof", "It prevents all software errors"], "It allows multiple instructions to be issued and executed in parallel in a single clock cycle using multiple execution units (e.g., two ALUs)", "Superscalar goes beyond pipelining by literally duplicating hardware inside the core to do more than one thing at the exact same time."),
Q("CAT 1", "EASY", "Which bus carries the memory address the CPU wants to access?", ["Data Bus", "Control Bus", "Address Bus", "USB Bus"], "Address Bus", "The Address Bus is one-directional (from CPU to RAM) and tells the RAM exactly which mailbox to open."),
Q("CAT 1", "MEDIUM", "In a 'Hardwired Control Unit', how are control signals generated?", ["By reading a file from the hard drive", "By using physical combinational and sequential logic circuits (gates and flip-flops) directly tied to the opcode", "By asking the user", "By using an internet connection"], "By using physical combinational and sequential logic circuits (gates and flip-flops) directly tied to the opcode", "Hardwired units use raw electrical logic for maximum speed, though they are very difficult to modify later."),
Q("CAT 1", "HARD", "What is the primary characteristic of a 'Load/Store Architecture'?", ["It stores everything in the cloud", "Data must be explicitly loaded from memory into registers before arithmetic operations can be performed, and then stored back", "It cannot use registers", "It loads files automatically"], "Data must be explicitly loaded from memory into registers before arithmetic operations can be performed, and then stored back", "Typical of RISC architectures, this simplifies the ALU design since it never has to wait for slow memory during math operations."),
Q("CAT 1", "MEDIUM", "What does 'Immediate Addressing Mode' mean?", ["The instruction executes instantly", "The operand data is embedded directly inside the machine code instruction itself", "The data is in a register", "The data is on the internet"], "The operand data is embedded directly inside the machine code instruction itself", "For example, in 'ADD AX, 5', the number 5 is the immediate operand. The CPU doesn't have to look anywhere else for it."),
Q("CAT 1", "HARD", "Why does a CPU need 'Status Flags' (Condition Codes)?", ["To look pretty", "To record the outcome of ALU operations (like zero, negative, or carry) so conditional branching instructions (like Jump if Zero) can make decisions", "To store big files", "To connect to Wi-Fi"], "To record the outcome of ALU operations (like zero, negative, or carry) so conditional branching instructions (like Jump if Zero) can make decisions", "Flags are the CPU's short-term memory of the last math operation, enabling 'IF/ELSE' logic in software."),
Q("CAT 1", "EASY", "What is the 'Accumulator'?", ["A battery", "A primary register used to store the results of arithmetic and logical operations", "A hard drive", "A type of virus"], "A primary register used to store the results of arithmetic and logical operations", "Historically, it 'accumulates' the running total of a series of calculations."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "What is the 'Brain' of the computer?", ["RAM", "Hard Drive", "CPU", "Power Supply"], "CPU", "The Central Processing Unit coordinates all hardware and executes all software."),
Q("CAT 2", "MEDIUM", "What happens during a 'Pop' operation on a stack?", ["An item is added, and the stack pointer is incremented", "The top item is removed, and the stack pointer is decremented", "The stack is deleted entirely", "The stack is sorted"], "The top item is removed, and the stack pointer is decremented", "Popping retrieves the most recently saved data, following the LIFO (Last In, First Out) principle."),
Q("CAT 2", "HARD", "What is the purpose of 'Vector Processing' (SIMD)?", ["To draw vector graphics", "To apply a single instruction simultaneously to multiple data elements, accelerating tasks like 3D rendering and scientific simulations", "To slow down the CPU", "To encrypt text"], "To apply a single instruction simultaneously to multiple data elements, accelerating tasks like 3D rendering and scientific simulations", "Instead of adding numbers one by one, SIMD can add an entire array of numbers in a single clock cycle."),
Q("CAT 2", "EASY", "Which memory type sits directly between the CPU and RAM?", ["SSD", "Cache Memory", "HDD", "DVD"], "Cache Memory", "Cache provides a high-speed buffer so the fast CPU doesn't spend most of its time waiting for the slower RAM."),
Q("CAT 2", "MEDIUM", "What does 'Direct Addressing Mode' specify?", ["A register name", "The exact, literal memory address where the operand is located", "An offset value", "A web URL"], "The exact, literal memory address where the operand is located", "The instruction contains the full address. The CPU just goes directly to that address in RAM to fetch the data."),
Q("CAT 2", "HARD", "What causes a 'Stack Overflow'?", ["The CPU getting too hot", "Pushing too much data onto the stack, exceeding the fixed size limit imposed by the hardware or Operating System", "The hard drive failing", "A fast internet connection"], "Pushing too much data onto the stack, exceeding the fixed size limit imposed by the hardware or Operating System", "Infinite recursive loops are a common cause. The stack grows until it hits memory it's not allowed to touch, crashing the program."),
Q("CAT 2", "MEDIUM", "What is a '4-bit Arithmetic Circuit' capable of?", ["Only addition", "Addition, subtraction, and incrementation using a combination of logic gates on 4-bit numbers", "Storing files", "Playing audio"], "Addition, subtraction, and incrementation using a combination of logic gates on 4-bit numbers", "It is the foundational building block of the ALU, capable of performing multiple math operations based on control signals."),
Q("CAT 2", "HARD", "How does a 'Micro-programmed Control Unit' provide flexibility?", ["It can be physically bent", "Its micro-program is stored in ROM/RAM, so the instruction set can be updated or fixed by changing the microcode software without altering the silicon wiring", "It uses wireless technology", "It doesn't use electricity"], "Its micro-program is stored in ROM/RAM, so the instruction set can be updated or fixed by changing the microcode software without altering the silicon wiring", "This allows CPU manufacturers to issue 'microcode updates' to patch hardware bugs long after the chip is manufactured."),
Q("CAT 2", "EASY", "What does the 'Instruction Register' (IR) hold?", ["The next instruction address", "The instruction currently being decoded and executed", "The results of an addition", "The user's password"], "The instruction currently being decoded and executed", "Once fetched from RAM, the instruction sits in the IR so the Control Unit can interpret its Opcode."),

// ╔══════════════════════════════════╗
// ║            UE (8 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "What measures the speed of the CPU, often in GHz?", ["The Address Bus", "The System Clock", "The Cache Size", "The Hard Drive Size"], "The System Clock", "The clock generates electronic pulses that synchronize all operations. 1 GHz means 1 billion cycles per second."),
Q("UE", "MEDIUM", "In processor organization, what does the 'Opcode' field specify?", ["Where the data is", "The specific operation to perform, such as ADD, SUB, or JUMP", "The length of the instruction", "The author of the program"], "The specific operation to perform, such as ADD, SUB, or JUMP", "The Opcode is the critical part of the instruction that tells the Control Unit which hardware circuits to activate."),
Q("UE", "HARD", "What is an 'Indirect Cycle' in instruction execution?", ["A cycle used to cool the CPU", "An extra cycle where the CPU fetches a memory address from memory, which points to the actual location of the operand (indirect addressing)", "A cycle that deletes data", "A cycle used for printing"], "An extra cycle where the CPU fetches a memory address from memory, which points to the actual location of the operand (indirect addressing)", "Indirect addressing requires two trips to RAM: one to get the pointer, and a second to get the actual data, slowing execution down."),
Q("UE", "MEDIUM", "What characterizes 'Register Mode' addressing?", ["The operand is in RAM", "The operand is directly contained in a CPU register, making execution very fast", "The operand is an immediate number", "The operand is on the hard drive"], "The operand is directly contained in a CPU register, making execution very fast", "Because no RAM access is required, operations on registers execute at the maximum speed of the CPU."),
Q("UE", "HARD", "What is the function of the 'Memory Management Unit' (MMU)?", ["To organize files in folders", "To translate virtual memory addresses to physical RAM addresses and ensure memory protection between running programs", "To clean the cache", "To download RAM from the internet"], "To translate virtual memory addresses to physical RAM addresses and ensure memory protection between running programs", "The MMU allows the OS to isolate programs from each other, preventing a crash in one program from taking down the whole computer."),
Q("UE", "EASY", "Which bus carries commands like READ and WRITE?", ["Data Bus", "Address Bus", "Control Bus", "USB"], "Control Bus", "The Control Bus carries the timing and command signals that orchestrate the system."),
Q("UE", "MEDIUM", "What is an 'Incrementer' circuit?", ["A circuit that multiplies by 10", "A specific digital circuit designed solely to add 1 to an input value, commonly used for the Program Counter", "A circuit that deletes data", "A type of monitor"], "A specific digital circuit designed solely to add 1 to an input value, commonly used for the Program Counter", "Instead of using a full ALU to just add one, a smaller, faster incrementer circuit is often dedicated to the Program Counter."),
Q("UE", "HARD", "What is the primary advantage of a 'Common ALU' shared among registers?", ["It makes the CPU run twice as fast", "It simplifies CPU design and reduces hardware complexity and physical size compared to having separate ALUs for every register pair", "It eliminates the need for RAM", "It uses zero power"], "It simplifies CPU design and reduces hardware complexity and physical size compared to having separate ALUs for every register pair", "While it creates a potential bottleneck (contention), a shared ALU saves a massive amount of silicon space."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (8 Qns)       ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "What does 'ISA' stand for in computer architecture?", ["Internal System Array", "Instruction Set Architecture", "Integrated Serial Adapter", "Input Standard Arithmetic"], "Instruction Set Architecture", "The ISA is the specification that defines the set of instructions the processor can execute."),
Q("POSSIBLE QNS", "MEDIUM", "What is 'Branch Prediction'?", ["Predicting when the hard drive will fail", "The CPU guessing the outcome of an 'if' statement to keep the pipeline full of speculative instructions", "Predicting the weather", "A type of virus scanner"], "The CPU guessing the outcome of an 'if' statement to keep the pipeline full of speculative instructions", "If the prediction is right, performance soars. If wrong, the CPU discards the speculative work and takes the correct path."),
Q("POSSIBLE QNS", "HARD", "Which architecture is known for 'Multi-Cycle Execution' and 'Microcode'?", ["RISC", "CISC", "Harvard", "Von Neumann"], "CISC", "Complex instructions in CISC cannot be executed in one cycle, so the control unit breaks them down into multiple, microcoded steps."),
Q("POSSIBLE QNS", "MEDIUM", "What is 'Base-Register Mode' commonly used for?", ["Generating random numbers", "Addressing data structures like arrays, where the base register holds the start address and an offset is added to it", "Connecting to the internet", "Playing video games"], "Addressing data structures like arrays, where the base register holds the start address and an offset is added to it", "It is the perfect hardware implementation for array indexing (e.g., Array[5])."),
Q("POSSIBLE QNS", "HARD", "What is an 'Interrupt Cycle'?", ["When the power goes out", "The CPU halting normal execution, saving its state (PC and flags), and jumping to an interrupt handler to service a hardware request", "When the CPU overheats", "When the cache is cleared"], "The CPU halting normal execution, saving its state (PC and flags), and jumping to an interrupt handler to service a hardware request", "Interrupts are how a keyboard press gets immediate attention without the CPU constantly checking the keyboard port."),
Q("POSSIBLE QNS", "EASY", "What is the 'Program Counter' (PC)?", ["A counter that tracks time", "A register holding the memory address of the next instruction to fetch", "A device that counts files", "A tool for measuring electricity"], "A register holding the memory address of the next instruction to fetch", "The PC is incremented automatically after every fetch so it always points to the next step in the program."),
Q("POSSIBLE QNS", "MEDIUM", "What is 'Inter-register transfer'?", ["Transferring data from a hard drive to a USB", "The movement of data between different registers within the CPU, coordinated by clock signals", "Sending data over Wi-Fi", "Downloading a file"], "The movement of data between different registers within the CPU, coordinated by clock signals", "This is the fastest type of data movement possible in a computer, happening entirely inside the CPU chip."),
Q("POSSIBLE QNS", "HARD", "How does a 'Full Adder' differ from a 'Half Adder'?", ["It adds three numbers", "A full adder can accept a carry-in from a previous less significant bit, making it possible to chain them for multi-bit addition", "It is physically larger only", "It can subtract"], "A full adder can accept a carry-in from a previous less significant bit, making it possible to chain them for multi-bit addition", "Without full adders, we could only add 1-bit numbers. Chaining them allows for 32-bit or 64-bit addition.")
];

async function insertUnit1Part4() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = ca_unit1_part4.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} part 4 questions for CA Unit 1.`);
        } else {
            console.log("No new part 4 questions for CA Unit 1 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit1Part4();
