const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a49ecb638bb37720e3e9194"; // COMPUTER ARCHITECTURE AND ASSEMBLY PROGRAMMING LANGUAGE

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const ca_unit1_extra = [
// ╔══════════════════════════════════╗
// ║           QUIZ (8 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "What is the smallest unit of storage within a digital CPU?", ["Hard Drive", "Register", "RAM", "Cache"], "Register", "Registers are extremely small, high-speed storage locations directly on the CPU die, built from flip-flops."),
Q("QUIZ", "MEDIUM", "What is the function of the 'Instruction Decoder' inside the Control Unit?", ["It translates English to Binary", "It interprets the fetched instructions, determining the operation to be performed and identifying the operands", "It checks for viruses", "It saves the file to the disk"], "It interprets the fetched instructions, determining the operation to be performed and identifying the operands", "The instruction decoder is responsible for reading the opcode and translating it into the electrical signals needed to run the ALU."),
Q("QUIZ", "HARD", "Which addressing mode is primarily used when accessing local variables and function parameters?", ["Relative Mode", "Direct Mode", "Base Pointer (BP) Mode", "Immediate Mode"], "Base Pointer (BP) Mode", "The Base Pointer register points to the base of the current stack frame, making it easy to reference variables pushed onto the stack by adding or subtracting an offset."),
Q("QUIZ", "MEDIUM", "What is the primary difference between a 'Half Adder' and a 'Full Adder'?", ["A half adder is physically smaller", "A full adder can accept a carry-in from a previous addition stage, while a half adder cannot", "A full adder multiplies numbers", "A half adder only adds zeros"], "A full adder can accept a carry-in from a previous addition stage, while a half adder cannot", "Full adders handle three inputs (A, B, and Carry-In), which is necessary for chaining them together to add multi-bit numbers."),
Q("QUIZ", "EASY", "Which CPU architecture is characterized by a 'Complex Instruction Set'?", ["RISC", "CISC", "ARM", "MIPS"], "CISC", "Complex Instruction Set Computing (CISC) architectures, like x86, have large sets of complex instructions that may take multiple clock cycles."),
Q("QUIZ", "HARD", "What happens during a 'Logical Shift Right' operation?", ["The bits are shifted right, and the sign bit is preserved", "The bits are shifted right, and a zero is shifted into the most significant bit (MSB)", "The bits are shifted left", "The bits are deleted"], "The bits are shifted right, and a zero is shifted into the most significant bit (MSB)", "A logical shift strictly pads with zeros, whereas an arithmetic shift preserves the sign bit (for negative numbers)."),
Q("QUIZ", "MEDIUM", "What is the primary purpose of 'General-Purpose Registers' (D0-Dn)?", ["To hold the operating system", "To hold data temporarily during computations for the programmer or the processor to use as needed", "To keep track of the stack", "To point to the next instruction"], "To hold data temporarily during computations for the programmer or the processor to use as needed", "Unlike specialized registers (like the PC or SP), general-purpose registers can be freely used by assembly programmers to hold any temporary values."),
Q("QUIZ", "HARD", "In the fetch cycle, which register provides the address of the next instruction?", ["Accumulator (AC)", "Instruction Register (IR)", "Program Counter (PC)", "Stack Pointer (SP)"], "Program Counter (PC)", "The Program Counter always holds the memory address of the next instruction to fetch from RAM."),

// ╔══════════════════════════════════╗
// ║         EXERCISE (8 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "Which component is responsible for the 'Execute Cycle'?", ["The Hard Drive", "The Control Unit and ALU", "The Monitor", "The RAM"], "The Control Unit and ALU", "During the execute cycle, the Control Unit directs the ALU to perform the required mathematical or logical operations."),
Q("EXERCISE", "MEDIUM", "What does 'Memory-to-Memory Operations' mean in the context of CISC?", ["Copying a file from USB to Hard Drive", "The architecture supports instructions that can directly manipulate data stored in memory without first loading it into a register", "Backing up RAM to a cloud server", "Using two RAM sticks"], "The architecture supports instructions that can directly manipulate data stored in memory without first loading it into a register", "CISC can perform tasks like adding a number directly to a memory address, saving the programmer from writing LOAD and STORE instructions."),
Q("EXERCISE", "HARD", "What is the role of a 'Microinstruction' in a micro-programmed control unit?", ["It is a small computer", "It is a low-level control word stored in ROM that generates specific hardware control signals when executed", "It is an instruction written in Python", "It is a virus"], "It is a low-level control word stored in ROM that generates specific hardware control signals when executed", "Microinstructions are the hidden 'instructions behind the instructions' that physically operate the CPU gates."),
Q("EXERCISE", "MEDIUM", "Which register is specifically used to store the results of arithmetic and logical operations by default?", ["Program Counter (PC)", "Instruction Register (IR)", "Accumulator (AC)", "Base Pointer (BP)"], "Accumulator (AC)", "In many older and simpler CPU architectures, the Accumulator is the default destination for the results of ALU operations."),
Q("EXERCISE", "HARD", "What is 'Branch Prediction and Speculative Execution' used for?", ["To predict stock prices", "To guess the outcome of an 'if' statement and execute code early, improving pipeline efficiency", "To physically split the CPU", "To encrypt user data"], "To guess the outcome of an 'if' statement and execute code early, improving pipeline efficiency", "If the CPU guesses correctly, it saves time. If it guesses wrong, it just discards the speculative results and takes the correct path."),
Q("EXERCISE", "EASY", "What is the 'Data Bus'?", ["A vehicle for transporting computers", "A set of parallel wires used to transfer binary data simultaneously between different components like CPU and Memory", "A software protocol", "A power cable"], "A set of parallel wires used to transfer binary data simultaneously between different components like CPU and Memory", "The data bus is the physical highway over which actual information travels inside the motherboard."),
Q("EXERCISE", "MEDIUM", "What is an advantage of 'Pipelining'?", ["It makes the CPU run colder", "It allows multiple instructions to be in different stages of execution at the same time, increasing throughput", "It uses less electricity", "It prevents all software bugs"], "It allows multiple instructions to be in different stages of execution at the same time, increasing throughput", "Instead of waiting for one instruction to finish entirely, the CPU starts the next one immediately in the next pipeline stage."),
Q("EXERCISE", "HARD", "Which addressing mode uses a register to hold an address, and an offset is added to that register to find the final operand?", ["Direct Mode", "Indexed Mode / Base-Register Mode", "Immediate Mode", "Register Mode"], "Indexed Mode / Base-Register Mode", "This is heavily used for traversing arrays, where the base register points to the start of the array, and the offset is the index."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "What determines the maximum addressable memory size of a CPU?", ["The size of the hard drive", "The width (number of wires) of the Address Bus", "The speed of the clock", "The size of the monitor"], "The width (number of wires) of the Address Bus", "A 32-bit address bus can access 2^32 addresses (4 GB of RAM), while a 64-bit bus can access vastly more."),
Q("CAT 1", "MEDIUM", "What is the primary characteristic of a RISC architecture regarding execution speed?", ["It takes many cycles per instruction", "It aims for Single-Cycle Execution for most instructions", "It requires an internet connection", "It executes randomly"], "It aims for Single-Cycle Execution for most instructions", "By keeping instructions simple, RISC processors try to execute one instruction per clock tick, ensuring a highly efficient pipeline."),
Q("CAT 1", "HARD", "What does 'Load/Store Architecture' mean in RISC?", ["It loads websites and stores cookies", "Operations can only be performed on registers; data must first be loaded from memory to a register, and later stored back", "It stores files on a USB", "It automatically saves documents"], "Operations can only be performed on registers; data must first be loaded from memory to a register, and later stored back", "Unlike CISC, RISC ALUs cannot interact directly with RAM. All math happens in registers."),
Q("CAT 1", "EASY", "Which component generates a series of electronic pulses to synchronize CPU operations?", ["The Clock", "The Hard Drive", "The Power Supply", "The ALU"], "The Clock", "The system clock is the metronome of the computer, keeping all components working together in perfect timing."),
Q("CAT 1", "MEDIUM", "In a 'Stack', what does the 'Pop' operation do?", ["Adds an item to the top of the stack", "Removes the item currently at the top of the stack and decrements the stack pointer", "Deletes the entire stack", "Sorts the stack alphabetically"], "Removes the item currently at the top of the stack and decrements the stack pointer", "Popping retrieves the most recently pushed piece of data, allowing the CPU to return to a previous state."),
Q("CAT 1", "HARD", "What is a 'Binary Subtractor'?", ["A circuit that adds numbers", "A digital circuit that performs subtraction, often by using two's complement logic and borrowing from higher bits", "A software program to hide files", "A physical switch"], "A digital circuit that performs subtraction, often by using two's complement logic and borrowing from higher bits", "Subtractors are critical ALU components, though modern ALUs often perform subtraction by adding the two's complement of the negative number."),
Q("CAT 1", "MEDIUM", "What does 'RTL' describe?", ["Web page layout", "The step-by-step flow of data between registers and logic components within a digital system", "How to fix a router", "Audio routing"], "The step-by-step flow of data between registers and logic components within a digital system", "Register Transfer Language is a notation used by hardware engineers to document exactly how data moves inside the CPU during each clock cycle."),
Q("CAT 1", "HARD", "Which addressing mode is used in branch instructions where the operand is an offset applied to the Program Counter?", ["Relative Mode", "Absolute Mode", "Immediate Mode", "Register Mode"], "Relative Mode", "Relative addressing allows a program to jump forward or backward a specific number of bytes from its current position, making the code relocatable."),
Q("CAT 1", "EASY", "Which CPU feature is small, extremely fast volatile memory used to store frequently accessed data?", ["CD-ROM", "Cache Memory", "Floppy Disk", "BIOS"], "Cache Memory", "Cache is much faster than RAM, acting as a high-speed buffer to keep the CPU fed with data without waiting."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "What does 'ALU' stand for?", ["Arithmetic Logic Unit", "Automatic Learning Utility", "Array Logic User", "Asynchronous Local Unit"], "Arithmetic Logic Unit", "The ALU is the mathematical engine of the CPU."),
Q("CAT 2", "MEDIUM", "What happens during an 'Interrupt Cycle'?", ["The computer reboots", "The CPU pauses its current program, saves its state, handles an urgent request from a device, and then resumes", "The power goes out", "The cache is cleared"], "The CPU pauses its current program, saves its state, handles an urgent request from a device, and then resumes", "Interrupts allow hardware (like a keyboard press) to instantly get the CPU's attention without the CPU having to constantly check for it."),
Q("CAT 2", "HARD", "What is 'Contention' in the context of a Common ALU architecture?", ["A physical fight between wires", "Since multiple instructions may need the single ALU simultaneously, they must wait their turn, causing delays", "A virus attacking the ALU", "The ALU running too fast"], "Since multiple instructions may need the single ALU simultaneously, they must wait their turn, causing delays", "While a common ALU saves space, it creates a bottleneck if several parallel operations all need to do math at the exact same moment."),
Q("CAT 2", "EASY", "Which principle does a memory stack follow?", ["FIFO", "FILO", "LIFO (Last In, First Out)", "LILO"], "LIFO (Last In, First Out)", "A stack is like a stack of plates; you can only take the top plate off, which is the last one you put on."),
Q("CAT 2", "MEDIUM", "What is the main function of the 'Memory Management Unit' (MMU)?", ["To format the hard drive", "To translate virtual addresses to physical addresses and handle memory protection", "To clean the keyboard", "To compile code"], "To translate virtual addresses to physical addresses and handle memory protection", "The MMU provides the abstraction of virtual memory, ensuring programs don't overwrite each other's RAM."),
Q("CAT 2", "HARD", "In variable-length instruction formats, what does the 'Length' field indicate?", ["How many lines of code there are", "The size (number of bytes) of the current instruction, so the CPU knows exactly where the next instruction begins", "The length of the ethernet cable", "The runtime of the program"], "The size (number of bytes) of the current instruction, so the CPU knows exactly where the next instruction begins", "Because CISC instructions can be 1 byte or 15 bytes long, the CPU needs to know how many bytes to fetch for the current operation."),
Q("CAT 2", "MEDIUM", "What does 'ISA' (Instruction Set Architecture) define?", ["The shape of the motherboard", "The complete set of machine language instructions, opcodes, and addressing modes that a specific CPU can understand", "The color of the CPU", "The operating system"], "The complete set of machine language instructions, opcodes, and addressing modes that a specific CPU can understand", "The ISA is the rulebook. If software is compiled for the x86 ISA, it cannot run on an ARM ISA processor without translation."),
Q("CAT 2", "HARD", "What is the primary difference between an 'Arithmetic Shift' and a 'Logical Shift'?", ["Arithmetic shifts are slower", "An arithmetic shift preserves the sign bit (useful for signed numbers), while a logical shift does not", "Logical shifts are only used for text", "There is no difference"], "An arithmetic shift preserves the sign bit (useful for signed numbers), while a logical shift does not", "When shifting right to divide by 2, an arithmetic shift ensures a negative number stays negative by filling the MSB with 1s instead of 0s."),
Q("CAT 2", "EASY", "What is the purpose of 'Registers' in the CPU?", ["To permanently store the OS", "To temporarily hold data, instructions, and addresses that are actively being processed", "To connect to Wi-Fi", "To display graphics"], "To temporarily hold data, instructions, and addresses that are actively being processed", "Registers are the absolute top of the memory hierarchy, providing zero-latency access to the data the CPU needs right this nanosecond."),

// ╔══════════════════════════════════╗
// ║            UE (8 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "What does 'SIMD' stand for in Vector Processing?", ["Single Instruction, Multiple Data", "Simple Internet Media Download", "Synchronized Internal Memory Device", "Standard Input Mode Data"], "Single Instruction, Multiple Data", "SIMD allows one instruction (like 'ADD') to be applied to an entire array of data simultaneously, speeding up graphics and scientific math."),
Q("UE", "MEDIUM", "How does a 'Micro-programmed Control Unit' determine what control signals to generate?", ["By guessing", "The instruction's Opcode is used as an index to look up a sequence of microinstructions in a ROM/RAM control memory", "By asking the user", "By using physical switches"], "The instruction's Opcode is used as an index to look up a sequence of microinstructions in a ROM/RAM control memory", "The Opcode points to the start of a tiny program inside the CPU that tells the hardware exactly how to execute that instruction."),
Q("UE", "HARD", "What is an 'Indirect Cycle'?", ["A cycle that wastes time", "An extra cycle required when an instruction uses indirect addressing, meaning the CPU must fetch a memory address to find the actual address of the data", "A cycle used to cool the CPU", "A cycle that deletes files"], "An extra cycle required when an instruction uses indirect addressing, meaning the CPU must fetch a memory address to find the actual address of the data", "If the instruction says 'the data is at the address stored in register X', the CPU must first look in register X, then go to RAM to get the data."),
Q("UE", "MEDIUM", "Which addressing mode is demonstrated by the instruction: `MOV AX, BX`?", ["Immediate Mode", "Direct Mode", "Register Mode", "Relative Mode"], "Register Mode", "In Register mode, both the source and the destination are CPU registers, meaning no RAM access is required."),
Q("UE", "HARD", "What determines the limit of the stack size in a computer system?", ["The size of the monitor", "Hardware limitations (size of stack pointer) and Operating System constraints designed to prevent a process from consuming all memory", "The speed of the internet", "The number of USB ports"], "Hardware limitations (size of stack pointer) and Operating System constraints designed to prevent a process from consuming all memory", "The OS strictly bounds the stack segment. If a program uses too much stack space, the OS kills it with a 'Stack Overflow' error."),
Q("UE", "EASY", "Which CPU component acts as a high-speed pathway transferring information between the CPU, memory, and I/O devices?", ["The Hard Drive", "The Bus System", "The Cache", "The ALU"], "The Bus System", "Buses are the internal communication highways of the motherboard and CPU."),
Q("UE", "MEDIUM", "What is a '4-bit Arithmetic Circuit'?", ["A 4-bit hard drive", "A combination of logic gates that can perform addition, subtraction, and incrementation on 4-bit binary numbers", "A program written in 4 bits", "A small battery"], "A combination of logic gates that can perform addition, subtraction, and incrementation on 4-bit binary numbers", "This circuit is the foundation of the ALU, stringing together full adders and multiplexers to perform math."),
Q("UE", "HARD", "Why are 'Status Flags' (Condition Codes) critical for programming?", ["They control the screen brightness", "They allow the CPU to make logical decisions (like 'Jump if Equal') based on the result of the previous ALU operation", "They encrypt passwords", "They store large files"], "They allow the CPU to make logical decisions (like 'Jump if Equal') based on the result of the previous ALU operation", "Without flags, 'IF' statements in programming would not work. The CPU checks the Zero or Carry flag to decide which code block to execute next."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (8 Qns)       ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "Which CPU design philosophy uses a large, varied set of complex instructions?", ["RISC", "CISC", "ARM", "Harvard"], "CISC", "Complex Instruction Set Computing tries to make the compiler's job easier by building high-level operations directly into the hardware."),
Q("POSSIBLE QNS", "MEDIUM", "What is the main role of the 'Instruction Register' (IR) during the Decode cycle?", ["It performs addition", "It holds the instruction so the Control Unit can read its Opcode and understand what needs to be done", "It stores the result", "It points to the stack"], "It holds the instruction so the Control Unit can read its Opcode and understand what needs to be done", "The IR is the 'reading desk' for the Control Unit. The instruction must sit there to be interpreted."),
Q("POSSIBLE QNS", "HARD", "What is 'Superscalar Execution'?", ["Running the CPU without power", "An architecture that allows multiple instructions to be issued and executed in parallel within a single clock cycle using multiple execution units", "Using an extremely large monitor", "Executing instructions randomly"], "An architecture that allows multiple instructions to be issued and executed in parallel within a single clock cycle using multiple execution units", "While pipelining overlaps stages, superscalar actually has duplicate hardware (like two ALUs) to literally do two things at the exact same time."),
Q("POSSIBLE QNS", "MEDIUM", "What does 'Pushing' to the stack mean?", ["Deleting data", "Adding a new element to the top of the stack and incrementing the stack pointer", "Reading the bottom element", "Restarting the computer"], "Adding a new element to the top of the stack and incrementing the stack pointer", "Pushing saves data (like a local variable or a return address) onto the LIFO stack structure."),
Q("POSSIBLE QNS", "HARD", "How does a 'Micro-programmed Control Unit' offer 'Flexibility' as an advantage?", ["It can bend physically", "If the instruction set architecture needs to be updated or patched, engineers can simply rewrite the micro-program in ROM rather than redesigning physical silicon wiring", "It uses wireless signals", "It requires no memory"], "If the instruction set architecture needs to be updated or patched, engineers can simply rewrite the micro-program in ROM rather than redesigning physical silicon wiring", "Microcode can often be updated via BIOS/UEFI updates, allowing manufacturers to fix CPU bugs after the chip is sold."),
Q("POSSIBLE QNS", "EASY", "What does the 'Address Bus' carry?", ["Actual user files", "Control signals like READ/WRITE", "Memory addresses indicating exactly where data should be read from or written to", "Power to the motherboard"], "Memory addresses indicating exactly where data should be read from or written to", "The address bus is strictly for navigation, telling the RAM which specific byte the CPU is interested in."),
Q("POSSIBLE QNS", "MEDIUM", "Which register typically points to the base of a stack frame for accessing local variables?", ["Accumulator", "Base Pointer (BP)", "Program Counter (PC)", "Instruction Register (IR)"], "Base Pointer (BP)", "The Base Pointer acts as a stable reference point inside a function, allowing easy access to parameters (BP+offset) and local variables (BP-offset)."),
Q("POSSIBLE QNS", "HARD", "What is the primary difference between a 'Register Transfer' and a 'Memory Transfer'?", ["Register transfers are slower", "Register transfer moves data between ultra-fast internal CPU registers, while Memory transfer moves data between the CPU and external RAM", "There is no difference", "Memory transfer uses Wi-Fi"], "Register transfer moves data between ultra-fast internal CPU registers, while Memory transfer moves data between the CPU and external RAM", "Moving data inside the CPU (Register Transfer) happens in a fraction of a nanosecond, whereas Memory Transfer is significantly slower due to the external bus bottleneck.")
];

async function insertUnit1Extra() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = ca_unit1_extra.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} extra questions for CA Unit 1.`);
        } else {
            console.log("No new extra questions for CA Unit 1 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit1Extra();
