const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a49ecb638bb37720e3e9194"; // COMPUTER ARCHITECTURE AND ASSEMBLY PROGRAMMING LANGUAGE

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const ca_unit4_part1 = [
// ╔══════════════════════════════════╗
// ║           QUIZ (8 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "What is a microprocessor?", ["A tiny screen", "A computer's Central Processing Unit (CPU) built on a single Integrated Circuit (IC)", "A small hard drive", "A type of computer virus"], "A computer's Central Processing Unit (CPU) built on a single Integrated Circuit (IC)", "Before microprocessors, CPUs were built using multiple separate components and boards. Integrating them onto one chip revolutionized computing."),
Q("QUIZ", "MEDIUM", "In the 8086 microprocessor, what is the 'Code Segment Register' (CS) used for?", ["To store the results of addition", "To hold the starting address of the memory segment that contains the instruction codes of a program", "To store variables", "To connect to the internet"], "To hold the starting address of the memory segment that contains the instruction codes of a program", "The CPU uses the CS register combined with the Instruction Pointer (IP) to find the next line of code to execute."),
Q("QUIZ", "HARD", "In Flynn's taxonomy of parallel processing, what does 'SIMD' stand for?", ["Single Instruction, Multiple Data", "System Integrated Memory Device", "Sequential Instruction, Micro Data", "Static Integer Math Division"], "Single Instruction, Multiple Data", "SIMD allows a single instruction (like ADD) to be applied to a large array of data simultaneously, rather than looping through the data one by one."),
Q("QUIZ", "MEDIUM", "What happens during the 'Instruction Decode' (ID) stage of pipelining?", ["The CPU shuts down", "The fetched instruction is analyzed to determine what operation it represents and what operands are involved", "The data is saved to the hard drive", "The result is printed to the screen"], "The fetched instruction is analyzed to determine what operation it represents and what operands are involved", "The CPU needs to 'understand' the opcode before it can actually execute it in the ALU."),
Q("QUIZ", "EASY", "What is 'Pipelining' compared to in the real world?", ["An assembly line in a factory", "A traffic jam", "A library", "A microwave oven"], "An assembly line in a factory", "Instead of waiting for a car to be completely built before starting the next one, pipelining works on multiple instructions at different stages simultaneously."),
Q("QUIZ", "HARD", "How does 'Superscalar' architecture differ from standard pipelining?", ["It doesn't use a clock", "It can issue and execute multiple instructions in a single clock cycle by having multiple redundant execution units (like two ALUs)", "It executes instructions backwards", "It uses magnetic tape for memory"], "It can issue and execute multiple instructions in a single clock cycle by having multiple redundant execution units (like two ALUs)", "While a standard pipeline handles one instruction per stage, a superscalar pipeline can handle two or three per stage if the instructions are independent."),
Q("QUIZ", "MEDIUM", "What is an 'Effective Address'?", ["An IP address", "The final calculated location in memory of an operand that an instruction needs to access", "A URL", "An email address"], "The final calculated location in memory of an operand that an instruction needs to access", "Instructions often use math (like Base + Offset) to find data. The result of that math is the effective address."),
Q("QUIZ", "HARD", "What is a 'Vector Processor' primarily designed to do?", ["Process text files", "Perform operations on entire arrays or vectors of data in parallel, avoiding the overhead of processing loops", "Play audio", "Format hard drives"], "Perform operations on entire arrays or vectors of data in parallel, avoiding the overhead of processing loops", "Instead of 'FOR i=1 to 100: C[i] = A[i] + B[i]', a vector processor does 'C = A + B' in a single hardware step."),

// ╔══════════════════════════════════╗
// ║         EXERCISE (8 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "What is the primary purpose of 'Parallel Processing'?", ["To make the computer heavier", "To enhance processing capability and increase throughput by executing multiple tasks simultaneously", "To reduce the amount of RAM needed", "To dim the monitor"], "To enhance processing capability and increase throughput by executing multiple tasks simultaneously", "By dividing a large problem into smaller sub-problems ('Divide and Conquer'), the computer finishes the job much faster."),
Q("EXERCISE", "MEDIUM", "In the context of 8086 registers, what does the 'Stack Segment Register' (SS) hold?", ["Only the operating system", "Addresses and data of subroutines, as well as contents placed by PUSH instructions", "The video memory", "The internet history"], "Addresses and data of subroutines, as well as contents placed by PUSH instructions", "The Stack is a crucial memory area for temporary data and function return addresses. SS points to where this area begins."),
Q("EXERCISE", "HARD", "What defines an 'MIMD' system?", ["Multiple Instruction, Multiple Data; multiple processors each independently executing their own instruction streams on their own data streams", "A system with no memory", "A system that only executes one program at a time", "A single processor with multiple monitors"], "Multiple Instruction, Multiple Data; multiple processors each independently executing their own instruction streams on their own data streams", "Modern multi-core desktop processors running different applications simultaneously are examples of MIMD architecture."),
Q("EXERCISE", "MEDIUM", "What is the 'Instruction Fetch' (IF) stage in a pipeline?", ["The stage where the CPU is turned on", "The stage where the processor retrieves the next instruction from memory (RAM or Cache)", "The stage where the result is written back", "The stage where math is done"], "The stage where the processor retrieves the next instruction from memory (RAM or Cache)", "You can't execute code if you haven't brought it into the CPU first. This is always the first stage of the pipeline."),
Q("EXERCISE", "EASY", "Which type of microprocessor is commonly found in smartphones and tablets?", ["Mainframe processors", "Processors utilizing ARM architecture, often with multiple cores (Quad/Octa) and integrated GPUs", "Vacuum tubes", "Punch card readers"], "Processors utilizing ARM architecture, often with multiple cores (Quad/Octa) and integrated GPUs", "Mobile devices require extremely power-efficient microprocessors that still deliver high multimedia performance."),
Q("EXERCISE", "HARD", "What is 'Super Pipelining'?", ["A pipeline that never stalls", "A technique that breaks down standard pipeline stages into even smaller, finer-grained stages, allowing for higher clock frequencies", "A pipeline that uses two monitors", "A software virus"], "A technique that breaks down standard pipeline stages into even smaller, finer-grained stages, allowing for higher clock frequencies", "If a stage takes 2ns, the max clock is 500MHz. If you cut that stage in half (1ns), you can run the clock at 1GHz (Superpipelining)."),
Q("EXERCISE", "MEDIUM", "What does the 'Flag Register' store?", ["The country code of the computer", "The results of arithmetic and logic operations, such as zero, carry, or negative status, used for conditional branching", "The Wi-Fi password", "The current time"], "The results of arithmetic and logic operations, such as zero, carry, or negative status, used for conditional branching", "When you write an 'IF (x == 0)' statement, the CPU subtracts the numbers and checks the Zero Flag to see if the result was 0."),
Q("EXERCISE", "HARD", "How does a 'GPU' (Graphics Processing Unit) relate to parallel processing?", ["It doesn't; it's strictly sequential", "GPUs are massively parallel processors with thousands of small cores originally designed for graphics, now widely used for general-purpose array processing", "It only handles text", "It is an older version of a CPU"], "GPUs are massively parallel processors with thousands of small cores originally designed for graphics, now widely used for general-purpose array processing", "GPUs are the ultimate SIMD machines. They are perfect for tasks like machine learning where the same math is applied to millions of pixels/data points."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "What is a 'Microcomputer'?", ["A computer the size of a building", "A digital computer with one microprocessor acting as its CPU", "A computer with no screen", "A mechanical calculator"], "A digital computer with one microprocessor acting as its CPU", "Desktops, laptops, and smartphones are all technically microcomputers."),
Q("CAT 1", "MEDIUM", "What is 'SISD' architecture?", ["Single Instruction, Single Data; representing a standard sequential computer where one processor executes one algorithm on one data source", "A type of hard drive", "A highly parallel supercomputer", "A network protocol"], "Single Instruction, Single Data; representing a standard sequential computer where one processor executes one algorithm on one data source", "This is the classic Von Neumann architecture before parallel processing and multi-core chips became standard."),
Q("CAT 1", "HARD", "Why is developing software for 'MIMD' systems considered challenging?", ["Because they don't have keyboards", "Because it requires sophisticated algorithms to manage shared data areas, synchronize multiprocessor interactions, and prevent data corruption", "Because they only run in DOS", "Because they use magnetic tapes"], "Because it requires sophisticated algorithms to manage shared data areas, synchronize multiprocessor interactions, and prevent data corruption", "If Core A and Core B try to modify the same variable in RAM at the exact same time, it causes a race condition. Programmers must use 'locks' to prevent this."),
Q("CAT 1", "EASY", "What happens in the 'Write Back' (WB) stage of a pipeline?", ["The computer is turned off", "The final results of the executed instruction are written back to the appropriate CPU register", "The data is sent to the printer", "The code is deleted"], "The final results of the executed instruction are written back to the appropriate CPU register", "This is the final step, committing the result of the ALU's hard work so the next instruction can use it."),
Q("CAT 1", "MEDIUM", "What is the function of the 'Data Segment Register' (DS)?", ["To store the operating system kernel", "To point to the segment of memory where data, variables, and constants used by the program are held", "To connect to a database", "To store video files"], "To point to the segment of memory where data, variables, and constants used by the program are held", "While the CS points to the actual instructions, the DS points to the variables those instructions are manipulating."),
Q("CAT 1", "HARD", "What is the main advantage of 'RISC' (Reduced Instruction Set Computing) when it comes to pipelining?", ["It doesn't use a pipeline", "Its simple, uniform-length instructions make the decode stage predictable and fast, allowing for highly efficient, seamless pipelining", "It requires no RAM", "It uses extremely complex instructions"], "Its simple, uniform-length instructions make the decode stage predictable and fast, allowing for highly efficient, seamless pipelining", "CISC instructions have variable lengths and take varying amounts of time, causing pipeline 'hiccups'. RISC is designed specifically to keep the pipeline flowing perfectly."),
Q("CAT 1", "MEDIUM", "What is an 'Arithmetic Pipeline'?", ["A pipeline for water", "A specialized pipeline that breaks complex arithmetic operations (like floating-point multiplication) into smaller, concurrent sub-stages", "A pipeline that only adds 1", "A pipeline for graphics"], "A specialized pipeline that breaks complex arithmetic operations (like floating-point multiplication) into smaller, concurrent sub-stages", "Floating-point math is hard. By pipelining the ALU itself, the CPU can start a new multiplication every clock cycle, even if one takes 4 cycles to finish."),
Q("CAT 1", "HARD", "In array processing, what is 'Memory Hierarchy Optimization'?", ["Buying more hard drives", "Techniques like data prefetching and cache optimization to ensure the parallel processors aren't starving while waiting for data from slow RAM", "Deleting old files", "Using magnetic tape"], "Techniques like data prefetching and cache optimization to ensure the parallel processors aren't starving while waiting for data from slow RAM", "A GPU can do a trillion calculations a second, but if it has to wait for data to arrive from main memory, all that speed is wasted. Data locality is key."),
Q("CAT 1", "EASY", "What is the premise of the 'Divide and Conquer' strategy in parallel organization?", ["Selling old computers", "Dividing a large computational problem into smaller sub-problems that can be solved simultaneously by multiple processors", "Dividing the keyboard in half", "Deleting half the code"], "Dividing a large computational problem into smaller sub-problems that can be solved simultaneously by multiple processors", "If one person can paint a house in 10 days, 10 people can paint it in 1 day. That is parallel processing."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "Which component performs the actual arithmetic or logic operation in the pipeline?", ["Instruction Fetch (IF)", "Instruction Execute (EX)", "Write Back (WB)", "Instruction Decode (ID)"], "Instruction Execute (EX)", "The EX stage uses the ALU (Arithmetic Logic Unit) to do the actual math (addition, subtraction, AND, OR)."),
Q("CAT 2", "MEDIUM", "What is 'SPMD' (Single Program, Multiple Data)?", ["A type of CD-ROM", "A subset of MIMD where multiple separate processors/nodes carry out the exact same program but on different sets of data, often using message passing", "A single processor computer", "A type of virus"], "A subset of MIMD where multiple separate processors/nodes carry out the exact same program but on different sets of data, often using message passing", "This is very common in cluster computing (like a university supercomputer). Everyone runs the same weather simulation code, but each node calculates a different geographic region."),
Q("CAT 2", "HARD", "What is a 'Pipeline Stall' (or Bubble)?", ["When the CPU overheats", "A delay in the pipeline caused by data dependencies, branch instructions, or resource conflicts, forcing stages to wait", "When the power goes out", "When the hard drive is full"], "A delay in the pipeline caused by data dependencies, branch instructions, or resource conflicts, forcing stages to wait", "If Instruction 2 needs the result of Instruction 1, it cannot execute until Instruction 1 reaches the Write Back stage. This delay creates a 'bubble' of wasted time in the pipeline."),
Q("CAT 2", "EASY", "Where are microprocessors used?", ["Only in desktop computers", "In handheld devices, desktops, supercomputers, and smart home appliances", "Only in calculators", "Only in cars"], "In handheld devices, desktops, supercomputers, and smart home appliances", "Microprocessors are the brain of almost every modern electronic device."),
Q("CAT 2", "MEDIUM", "What does the 'Extra Segment Register' (ES) in the 8086 typically hold?", ["Extra power", "The destination addresses for certain string and memory-copy instructions", "The operating system", "Backup data"], "The destination addresses for certain string and memory-copy instructions", "When copying a block of memory, the DS register might point to the source, and the ES register points to the destination."),
Q("CAT 2", "HARD", "How do Intel's AVX or ARM's NEON instructions relate to parallel processing?", ["They disable parallel processing", "They are specialized Instruction Set Architecture (ISA) extensions that provide SIMD capabilities, allowing the CPU to process arrays of data in a single instruction", "They are used for internet routing", "They are used for printing text"], "They are specialized Instruction Set Architecture (ISA) extensions that provide SIMD capabilities, allowing the CPU to process arrays of data in a single instruction", "These extensions allow a standard desktop CPU to do basic vector processing, massively speeding up video encoding and cryptography."),
Q("CAT 2", "MEDIUM", "What is a primary benefit of 'Parallel Organization' regarding reliability?", ["It makes the computer waterproof", "Parallel systems can be made more robust; if one processor fails, redundant processors can take over the workload", "It prevents all viruses", "It saves electricity"], "Parallel systems can be made more robust; if one processor fails, redundant processors can take over the workload", "In critical systems like aerospace or banking, parallel processors are often used for fault tolerance, not just speed."),
Q("CAT 2", "HARD", "What is 'MISD' architecture?", ["Multiple Instruction, Single Data; multiple processors apply different algorithms to the exact same stream of data simultaneously", "A standard desktop PC", "A type of hard drive", "A graphics card"], "Multiple Instruction, Single Data; multiple processors apply different algorithms to the exact same stream of data simultaneously", "It is very rare in general computing, but used in specialized fault-tolerant systems (like flight controllers) where 3 different processors calculate the same data and 'vote' on the result to ensure no errors."),
Q("CAT 2", "EASY", "What happens in the 'Memory Access' (MEM) stage of a pipeline?", ["The computer forgets data", "The instruction retrieves data from or stores data to the main memory, if required", "The CPU enters sleep mode", "The screen turns on"], "The instruction retrieves data from or stores data to the main memory, if required", "Not all instructions need this stage. A simple register addition (ADD AX, BX) skips memory access entirely."),

// ╔══════════════════════════════════╗
// ║            UE (8 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "What is the overarching goal of an 'Instruction Pipeline'?", ["To slow down the computer", "To improve processor throughput by overlapping the execution of multiple instructions, reducing wasted time", "To heat up the processor", "To compress files"], "To improve processor throughput by overlapping the execution of multiple instructions, reducing wasted time", "By keeping every part of the CPU busy at all times, throughput skyrockets."),
Q("UE", "MEDIUM", "What role do 'Supercomputers' play?", ["They are used for word processing", "They handle computationally intensive tasks like quantum mechanics, weather forecasting, and molecular modeling", "They are used as basic web servers", "They are used for retro gaming"], "They handle computationally intensive tasks like quantum mechanics, weather forecasting, and molecular modeling", "These are massive MIMD architectures with thousands of nodes working in parallel to solve problems that would take a desktop PC centuries to finish."),
Q("UE", "HARD", "Why does 'Superpipelining' introduce challenges with instruction dependencies?", ["Because it uses too much RAM", "Because with more, shorter stages, it takes longer for an instruction to fully complete, meaning subsequent instructions waiting for that result must stall for more clock cycles", "Because the clock stops", "Because it encrypts the data"], "Because with more, shorter stages, it takes longer for an instruction to fully complete, meaning subsequent instructions waiting for that result must stall for more clock cycles", "If a pipeline has 20 stages, an instruction takes 20 cycles to finish. If the very next instruction needs that answer, it has to wait a long time."),
Q("UE", "MEDIUM", "What does 'Instruction-Level Parallelism' (ILP) refer to?", ["Connecting two computers with a cable", "The ability of a superscalar processor to automatically find and execute independent instructions simultaneously within the same clock cycle", "Running two programs at once", "Using a dual-monitor setup"], "The ability of a superscalar processor to automatically find and execute independent instructions simultaneously within the same clock cycle", "The CPU hardware looks ahead in the code, sees that Instruction 1 and Instruction 2 don't rely on each other, and runs them both at the same time without the programmer doing anything special."),
Q("UE", "HARD", "How does a 'Load-Store Architecture' benefit a RISC pipeline?", ["It stores the pipeline in RAM", "It restricts memory access (which is slow) to only specific LOAD and STORE instructions, ensuring that arithmetic instructions only operate on fast registers, keeping the EX stage predictably fast", "It loads files automatically", "It prevents data loss"], "It restricts memory access (which is slow) to only specific LOAD and STORE instructions, ensuring that arithmetic instructions only operate on fast registers, keeping the EX stage predictably fast", "If an ADD instruction had to fetch from RAM, the EX stage would stall randomly based on cache misses. Load-Store separates memory delays from math execution."),
Q("UE", "EASY", "What is the difference between a Microprocessor and a Microcomputer?", ["They are the exact same thing", "A microprocessor is just the single CPU chip; a microcomputer is the complete system (CPU, Memory, I/O) that uses it", "A microcomputer is smaller", "A microprocessor is a software program"], "A microprocessor is just the single CPU chip; a microcomputer is the complete system (CPU, Memory, I/O) that uses it", "An Intel Core i7 is a microprocessor. A Dell laptop is a microcomputer."),
Q("UE", "MEDIUM", "What is the advantage of 'Vector Processing' over 'Scalar Processing' for large arrays?", ["It uses less electricity", "Vector processing uses a single instruction to operate on an entire array simultaneously, eliminating the overhead of fetching and decoding instructions in a loop", "It is slower and safer", "It works better with keyboards"], "Vector processing uses a single instruction to operate on an entire array simultaneously, eliminating the overhead of fetching and decoding instructions in a loop", "In scalar, adding a 100-item array takes 100 fetches, 100 decodes, 100 executes. In vector, it takes 1 fetch, 1 decode, and 1 massive parallel execute."),
Q("UE", "HARD", "In C++ SIMD programming, what does the `_mm256_add_epi32` intrinsic do?", ["It adds 256 to a number", "It performs a parallel SIMD addition on two 256-bit registers, simultaneously adding eight 32-bit integers in a single hardware cycle", "It encrypts a file", "It prints to the screen"], "It performs a parallel SIMD addition on two 256-bit registers, simultaneously adding eight 32-bit integers in a single hardware cycle", "This is how programmers manually tap into the SIMD capabilities (like AVX2) of modern CPUs for high-performance computing.")
];

async function insertUnit4Part1() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = ca_unit4_part1.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} questions for CA Unit 4 Part 1.`);
        } else {
            console.log("No new questions for CA Unit 4 Part 1 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit4Part1();
