const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a49ecb638bb37720e3e9194"; // COMPUTER ARCHITECTURE AND ASSEMBLY PROGRAMMING LANGUAGE

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const ca_unit5_part2 = [
// ╔══════════════════════════════════╗
// ║           QUIZ (8 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "What is the primary advantage of NUMA over UMA?", ["NUMA is cheaper", "NUMA is highly scalable, easily supporting dozens of sockets and thousands of cores without bus contention", "NUMA uses less power", "NUMA does not require a motherboard"], "NUMA is highly scalable, easily supporting dozens of sockets and thousands of cores without bus contention", "By decentralizing the memory controllers, NUMA allows massive parallel expansion that UMA simply cannot physically support."),
Q("QUIZ", "MEDIUM", "What is 'Strided Memory Access' used for?", ["To slow down data fetching", "To seamlessly load non-contiguous linear lines of data (like a specific column in a matrix) into continuous vector registers", "To access the internet", "To copy hard drives"], "To seamlessly load non-contiguous linear lines of data (like a specific column in a matrix) into continuous vector registers", "If a matrix is stored row-by-row in RAM, fetching a column means skipping over elements. Strided access handles this skipping natively in hardware."),
Q("QUIZ", "HARD", "How does a 'Register-to-Register' vector processor execute an operation?", ["Directly from the hard drive", "Explicit instructions load data from RAM into dedicated vector registers, ALU operations execute exclusively on these registers, and results are stored back to RAM", "It uses no RAM", "It uses the cloud"], "Explicit instructions load data from RAM into dedicated vector registers, ALU operations execute exclusively on these registers, and results are stored back to RAM", "This 'load-store' paradigm decouples slow memory access from fast arithmetic execution, a hallmark of modern architectures like Cray-1 and modern GPUs."),
Q("QUIZ", "MEDIUM", "What is the role of a 'Point-to-Point Interconnect' in modern NUMA?", ["To connect to a printer", "It acts as a high-speed, direct network between individual processor nodes (e.g., AMD Infinity Fabric) replacing the congested shared system bus", "To provide electricity", "To store data"], "It acts as a high-speed, direct network between individual processor nodes (e.g., AMD Infinity Fabric) replacing the congested shared system bus", "This topology allows for massive horizontal scaling of server architecture."),
Q("QUIZ", "EASY", "What does 'SIMD' stand for?", ["Single Instruction, Multiple Data", "System Integrated Memory Drive", "Static Interface Module Data", "Sequential Input, Main Data"], "Single Instruction, Multiple Data", "SIMD is the defining characteristic of Vector Processing, applying one command to a vast array of numbers simultaneously."),
Q("QUIZ", "HARD", "What does 'Vector Mask Control' allow a vector processor to do?", ["Draw vector graphics", "Handle conditional branches (like IF statements) inside a parallel loop by only writing back results where the boolean mask bit is 1", "Encrypt files", "Connect to the internet"], "Handle conditional branches (like IF statements) inside a parallel loop by only writing back results where the boolean mask bit is 1", "This elegant hardware solution completely eliminates the need for expensive branch prediction logic in massive parallel arrays."),
Q("QUIZ", "MEDIUM", "What distinguishes 'NC-NUMA' from 'CC-NUMA'?", ["NC-NUMA uses Wi-Fi", "In NC-NUMA (Non-Cache-Coherent), the hardware does not maintain cache consistency across nodes; the burden is shifted entirely to the software or OS", "NC-NUMA is for smartphones only", "NC-NUMA has no memory"], "In NC-NUMA (Non-Cache-Coherent), the hardware does not maintain cache consistency across nodes; the burden is shifted entirely to the software or OS", "While simpler to build, NC-NUMA is extremely difficult to program for safely."),
Q("QUIZ", "HARD", "What optimization does 'Vector Chaining' achieve?", ["It slows down execution for safety", "It allows the structural elements of a product vector to be fed directly into an adder pipeline instantly as they exit the multiplier pipeline, eliminating sequential waiting", "It encrypts data", "It deletes old variables"], "It allows the structural elements of a product vector to be fed directly into an adder pipeline instantly as they exit the multiplier pipeline, eliminating sequential waiting", "This is the ultimate expression of data forwarding, massively increasing throughput for complex chained equations."),

// ╔══════════════════════════════════╗
// ║         EXERCISE (8 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "What is 'Local Memory' in a NUMA architecture?", ["Memory on a USB drive", "Memory that is physically attached to the processor's own internal memory controller", "Memory in the cloud", "Memory that cannot be accessed"], "Memory that is physically attached to the processor's own internal memory controller", "Accessing local memory is deterministic and incredibly fast compared to reaching across the interconnect for remote memory."),
Q("EXERCISE", "MEDIUM", "Why do early 'Memory-to-Memory' vector processors have high startup latencies?", ["Because they use vacuum tubes", "Because they stream data directly from main memory to the ALU and back, requiring the pipeline to wait for the slow RAM before it can begin processing", "Because they need to connect to the internet", "Because they encrypt all data"], "Because they stream data directly from main memory to the ALU and back, requiring the pipeline to wait for the slow RAM before it can begin processing", "While this design allowed for infinite vector lengths, the RAM bottleneck was too severe for modern clock speeds."),
Q("EXERCISE", "HARD", "What does 'Strip Mining' involve computationally?", ["Calculating Bitcoin hashes", "Partitioning a software loop of arbitrary length 'N' into chunks of 'MVL' (Max Vector Length), usually processing the remainder 'N % MVL' first", "Deleting files", "Formatting the hard drive"], "Partitioning a software loop of arbitrary length 'N' into chunks of 'MVL' (Max Vector Length), usually processing the remainder 'N % MVL' first", "This technique bridges the gap between software arrays of infinite size and hardware registers of fixed size."),
Q("EXERCISE", "MEDIUM", "What is a 'Gather' operation in vector memory access?", ["Collecting files in a folder", "Using a vector of index pointers to collect elements scattered across disparate physical memory addresses and consolidating them into a single vector register", "Gathering error logs", "Downloading from the internet"], "Using a vector of index pointers to collect elements scattered across disparate physical memory addresses and consolidating them into a single vector register", "This allows parallel processing to be applied to sparse matrices and complex, non-linear data structures."),
Q("EXERCISE", "EASY", "What problem does UMA (Uniform Memory Access) suffer from at scale?", ["It runs out of power", "Severe bus and memory controller contention as more processors are added to the single shared bus", "It physically overheats", "It cannot run Windows"], "Severe bus and memory controller contention as more processors are added to the single shared bus", "UMA simply cannot scale to dozens of processors because the physical bus connecting them to the RAM becomes too congested."),
Q("EXERCISE", "HARD", "What is the function of hardware cache coherence protocols (like MESI) in CC-NUMA?", ["To connect to Wi-Fi", "To automatically track and maintain consistency across all local and remote caches, invalidating remote copies instantly if a node modifies a piece of data", "To format documents", "To print data"], "To automatically track and maintain consistency across all local and remote caches, invalidating remote copies instantly if a node modifies a piece of data", "Without MESI, one CPU might read a stale variable from its cache, completely unaware that another CPU just changed the actual value in RAM."),
Q("EXERCISE", "MEDIUM", "What defines the 'Vector Length' (VL)?", ["The size of the hard drive", "The precise number of scalar elements currently loaded into a fixed-size vector register for processing", "The length of the motherboard", "The time to boot the OS"], "The precise number of scalar elements currently loaded into a fixed-size vector register for processing", "The programmer (or compiler) sets the VL register so the hardware knows exactly how many elements to process in the current pass."),
Q("EXERCISE", "HARD", "How does a vector processor handle scalar operations?", ["It cannot handle them", "It includes dedicated Scalar Registers & Units operating in tandem to manage program counters, calculate branches, and compute base memory addresses", "It uses the hard drive for scalar math", "It outsources them to a network server"], "It includes dedicated Scalar Registers & Units operating in tandem to manage program counters, calculate branches, and compute base memory addresses", "Vector units are specialized for arrays, but standard sequential program logic still requires traditional scalar processing."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "What is the primary characteristic of NUMA memory access latency?", ["It is always exactly the same", "It is variable; it depends heavily on whether the accessed memory is physically local or remote to the processor", "It is infinite", "It relies on network speed"], "It is variable; it depends heavily on whether the accessed memory is physically local or remote to the processor", "The OS scheduler tries to keep processes on the same node as their memory allocation to minimize this variable latency."),
Q("CAT 1", "MEDIUM", "What is the 'MVL' in a vector architecture?", ["Maximum Voltage Limit", "Maximum Vector Length; the fixed-size physical capacity of the hardware vector register", "Minimum Variable Logic", "Main Video Line"], "Maximum Vector Length; the fixed-size physical capacity of the hardware vector register", "If the hardware MVL is 64, you can only process 64 elements simultaneously in one hardware pass."),
Q("CAT 1", "HARD", "What is a 'Scatter' operation the inverse of?", ["A JUMP operation", "A 'Gather' operation; Scatter takes elements from a vector register and disperses them out to erratic locations via an index address vector", "A PRINT operation", "A DELETE operation"], "A 'Gather' operation; Scatter takes elements from a vector register and disperses them out to erratic locations via an index address vector", "If you did math on a sparsely gathered array, 'Scatter' writes the modified answers back to their original scattered locations in RAM."),
Q("CAT 1", "EASY", "What computing paradigm replaces SISD in vector processing?", ["MIMD", "SIMD (Single Instruction, Multiple Data)", "MISD", "RISC"], "SIMD (Single Instruction, Multiple Data)", "Instead of looping 100 times to add 100 numbers, SIMD adds all 100 numbers at once using one instruction."),
Q("CAT 1", "MEDIUM", "What is the advantage of 'Vector Chaining'?", ["It secures the computer to a desk", "It heavily amplifies performance by allowing sequential vector operations to overlap, feeding output directly into the next input without waiting for memory", "It stops the computer from overheating", "It encrypts network traffic"], "It heavily amplifies performance by allowing sequential vector operations to overlap, feeding output directly into the next input without waiting for memory", "It is the vector equivalent of data forwarding in a scalar pipeline."),
Q("CAT 1", "HARD", "Why is NC-NUMA relegated to specialized environments?", ["Because it is too expensive", "Because the lack of hardware cache coherence shifts significant optimization burdens onto developers, making general-purpose software prone to data corruption", "Because it uses too much electricity", "Because it only supports one monitor"], "Because the lack of hardware cache coherence shifts significant optimization burdens onto developers, making general-purpose software prone to data corruption", "Writing an OS for NC-NUMA requires intense, manual management of what data is valid in which cache, a nightmare for general software."),
Q("CAT 1", "MEDIUM", "What is a 'Vector Functional Unit'?", ["A power supply", "A highly specialized arithmetic pipeline (Adder, Multiplier) heavily segmented to accept a new pair of vector elements every single clock cycle", "A hard drive controller", "A Wi-Fi card"], "A highly specialized arithmetic pipeline (Adder, Multiplier) heavily segmented to accept a new pair of vector elements every single clock cycle", "These units are the 'muscle' of a vector processor, achieving peak processing efficiency through deep pipelining."),
Q("CAT 1", "HARD", "How does NUMA manage a 'Logical Address Space'?", ["By hiding addresses", "It maintains a single, unified logical address space, allowing software to see one giant pool of RAM even though the physical memory is partitioned across nodes", "By using the hard drive", "By compressing the RAM"], "It maintains a single, unified logical address space, allowing software to see one giant pool of RAM even though the physical memory is partitioned across nodes", "To the software, it's just one big block of memory. The hardware handles the complex routing of read/write requests to the correct node."),
Q("CAT 1", "EASY", "What limits the scalability of UMA?", ["The lack of hard drives", "The centralized shared system bus, which becomes congested with traffic as more processors are added", "The monitor size", "The power cable"], "The centralized shared system bus, which becomes congested with traffic as more processors are added", "UMA topologies simply run out of physical bandwidth to support dozens of CPUs."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "What does CC-NUMA hardware automatically track?", ["Internet usage", "Cache consistency across all remote and local caches", "Keyboard inputs", "Monitor refresh rates"], "Cache consistency across all remote and local caches", "It guarantees that no processor ever reads stale, outdated data from its local cache if another processor has modified it."),
Q("CAT 2", "MEDIUM", "What is the purpose of 'Vector Mask Control'?", ["To hide the IP address", "To allow conditional execution (IF-ELSE logic) within a vector loop without branching, by masking the write-back of specific elements", "To compress video", "To protect against viruses"], "To allow conditional execution (IF-ELSE logic) within a vector loop without branching, by masking the write-back of specific elements", "It's an elegant solution to the problem that SIMD processors cannot 'branch' different elements in different directions."),
Q("CAT 2", "HARD", "What is the core bottleneck that Register-to-Register vector architecture solves?", ["Hard drive speed", "Main memory access bottlenecking; by fetching data into high-speed vector registers first, the deeply pipelined ALUs can operate at ultra-low latency", "Monitor latency", "Keyboard input delay"], "Main memory access bottlenecking; by fetching data into high-speed vector registers first, the deeply pipelined ALUs can operate at ultra-low latency", "This architecture, pioneered by the Cray-1, ensures the multi-million dollar CPU doesn't spend 90% of its time waiting for RAM."),
Q("CAT 2", "EASY", "What is 'Strip Mining'?", ["Mining for precious metals", "A technique that partitions a software loop of length N into hardware-friendly segments matching the Maximum Vector Length", "Deleting old software", "Connecting to a server"], "A technique that partitions a software loop of length N into hardware-friendly segments matching the Maximum Vector Length", "It allows a fixed-size hardware unit to process infinitely long software arrays."),
Q("CAT 2", "MEDIUM", "What does 'Remote Memory' refer to in NUMA?", ["Memory stored on Google Drive", "Memory that is physically attached to another processor node across the interconnect fabric, resulting in higher access latency", "Memory on a USB stick", "Memory that was deleted"], "Memory that is physically attached to another processor node across the interconnect fabric, resulting in higher access latency", "The golden rule of NUMA programming is 'keep your data local'."),
Q("CAT 2", "HARD", "What is 'Strided Memory Access' essential for?", ["Connecting to Wi-Fi", "Accessing multi-dimensional matrices (like reading columns in row-major data) seamlessly, loading non-contiguous linear data into a continuous register", "Printing documents", "Format conversions"], "Accessing multi-dimensional matrices (like reading columns in row-major data) seamlessly, loading non-contiguous linear data into a continuous register", "Without strided access, fetching a column of a matrix would cause massive cache misses and destroy performance."),
Q("CAT 2", "MEDIUM", "What is a 'Point-to-point interconnect'?", ["A laser pointer", "A highly scalable network topology (like Intel UPI) used in NUMA to connect nodes directly, replacing the shared system bus", "A type of mouse", "A graphical interface"], "A highly scalable network topology (like Intel UPI) used in NUMA to connect nodes directly, replacing the shared system bus", "It allows massive horizontal scaling. If Node A needs to talk to Node B, it doesn't block Node C from talking to Node D."),
Q("CAT 2", "HARD", "Why does a vector processor eliminate 'instruction decode overhead'?", ["It doesn't use instructions", "A single comprehensive instruction is decoded once, and the operation is applied to an entire array of data automatically in hardware", "It uses the hard drive to decode", "It guesses the instruction"], "A single comprehensive instruction is decoded once, and the operation is applied to an entire array of data automatically in hardware", "In a scalar loop of 1000 iterations, the CPU decodes the 'ADD' instruction 1000 times. A vector processor decodes it once."),
Q("CAT 2", "EASY", "What does 'UMA' stand for?", ["Universal Module Adapter", "Uniform Memory Access", "United Mobile Array", "Unique Matrix Algorithm"], "Uniform Memory Access", "In UMA, memory access is perfectly uniform, no matter which CPU is asking for data."),

// ╔══════════════════════════════════╗
// ║            UE (8 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "What is the primary difference between Local Memory and Remote Memory in NUMA?", ["Local is RAM, Remote is HDD", "Local memory is accessed significantly faster because it is attached to the processor's own controller; remote memory requires traversing the interconnect", "Remote memory is encrypted", "Local memory is read-only"], "Local memory is accessed significantly faster because it is attached to the processor's own controller; remote memory requires traversing the interconnect", "This variable latency is the defining characteristic of 'Non-Uniform' memory access."),
Q("UE", "MEDIUM", "What is the function of the 'Vector Control Unit'?", ["To draw lines", "To decode vector instructions, track structural conflicts (like resource contention), and manage coordination elements like vector lengths", "To cool the CPU", "To provide internet access"], "To decode vector instructions, track structural conflicts (like resource contention), and manage coordination elements like vector lengths", "It acts as the maestro, ensuring the massive parallel pipelines are fed data correctly and don't collide."),
Q("UE", "HARD", "How does a 'Gather' operation optimize sparse matrix computation?", ["It deletes sparse data", "It uses a vector of index pointers to collect disjointed elements scattered across physical memory and packs them into a single coherent vector register for fast processing", "It compresses the matrix into a zip file", "It ignores sparse data"], "It uses a vector of index pointers to collect disjointed elements scattered across physical memory and packs them into a single coherent vector register for fast processing", "Once gathered into a register, the SIMD ALUs can process the data at maximum speed as if it had been stored sequentially."),
Q("UE", "MEDIUM", "What is the MESI protocol?", ["A networking standard", "A hardware cache coherence protocol (Modified, Exclusive, Shared, Invalid) used in CC-NUMA to ensure data consistency across remote nodes", "A video encoding format", "An encryption algorithm"], "A hardware cache coherence protocol (Modified, Exclusive, Shared, Invalid) used in CC-NUMA to ensure data consistency across remote nodes", "It ensures that multiprocessor systems don't corrupt data by operating on stale cache copies."),
Q("UE", "HARD", "In 'Strip Mining', what is the purpose of computing 'N % MVL' for the first iteration?", ["To crash the program", "To process the 'remainder' elements first, ensuring that all subsequent loop iterations are perfectly aligned to execute chunks exactly matching the Max Vector Length", "To encrypt the remainder", "To skip the remainder"], "To process the 'remainder' elements first, ensuring that all subsequent loop iterations are perfectly aligned to execute chunks exactly matching the Max Vector Length", "If N=100 and MVL=64, N%MVL=36. The CPU processes a batch of 36 first. The remaining 64 exactly fill the hardware in the final pass."),
Q("UE", "EASY", "Which architecture uses 'SIMD' heavily?", ["Sequential Processors", "Vector Processors and Array Processors (like GPUs)", "Hard Drives", "Monitors"], "Vector Processors and Array Processors (like GPUs)", "SIMD (Single Instruction, Multiple Data) is the core philosophy behind processing graphics and scientific arrays."),
Q("UE", "MEDIUM", "What problem does UMA face as the number of sockets scales?", ["It uses too little power", "Low scalability bounded to 4-8 sockets due to severe bus contention and memory controller bottlenecks", "It cannot connect to Wi-Fi", "It requires too many monitors"], "Low scalability bounded to 4-8 sockets due to severe bus contention and memory controller bottlenecks", "You cannot build a 64-processor supercomputer using UMA; the shared bus would instantly become completely deadlocked."),
Q("UE", "HARD", "What is the 'Vector Register File'?", ["A text document", "A dedicated bank of fixed-size storage blocks (registers) capable of holding precise arrays of scalar elements for Register-to-Register vector architectures", "A cache for the hard drive", "A type of volatile RAM"], "A dedicated bank of fixed-size storage blocks (registers) capable of holding precise arrays of scalar elements for Register-to-Register vector architectures", "This is the ultra-fast staging ground where the actual SIMD magic happens, completely decoupled from slow RAM."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (8 Qns)       ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "What does 'NC-NUMA' stand for?", ["Network-Connected NUMA", "Non-Cache-Coherent NUMA", "New-Core NUMA", "No-Cache NUMA"], "Non-Cache-Coherent NUMA", "It lacks the hardware protocols (like MESI) to keep caches synchronized automatically."),
Q("POSSIBLE QNS", "MEDIUM", "What does 'Vector Chaining' optimize?", ["Network connections", "It optimizes Read-After-Write dependencies by feeding the results of one pipeline directly into the start of the next dependent pipeline instantly", "Hard drive storage", "Monitor refresh rates"], "It optimizes Read-After-Write dependencies by feeding the results of one pipeline directly into the start of the next dependent pipeline instantly", "This allows complex formulas like Y = (A * B) + C to execute seamlessly without stalling the hardware."),
Q("POSSIBLE QNS", "HARD", "Why is 'Vector Mask Control' superior to standard branching for vector arrays?", ["It uses more electricity", "Standard branching breaks the pipeline and is impossible to execute in parallel on different elements. Masking executes all math blindly but only writes back the valid 'True' results", "It crashes the program", "It encrypts the data"], "Standard branching breaks the pipeline and is impossible to execute in parallel on different elements. Masking executes all math blindly but only writes back the valid 'True' results", "While it does 'wasted' math on the False elements, it is significantly faster than destroying the pipeline execution flow."),
Q("POSSIBLE QNS", "MEDIUM", "What is 'Strided' memory access used for?", ["To slow down the computer", "To read non-contiguous data at a constant interval, such as extracting a single column from a massive row-major matrix", "To compress files", "To connect to Wi-Fi"], "To read non-contiguous data at a constant interval, such as extracting a single column from a massive row-major matrix", "This prevents the CPU from having to fetch entire cache lines of useless data just to get one number."),
Q("POSSIBLE QNS", "HARD", "What is the role of 'Scalar Processors' within a Vector Architecture?", ["They are not used at all", "They manage program counter loops, calculate branch conditions, compute base memory addresses, and allow scalar-vector mixed calculations", "They only draw graphics", "They format the hard drive"], "They manage program counter loops, calculate branch conditions, compute base memory addresses, and allow scalar-vector mixed calculations", "Vector processors handle the massive arrays, but the scalar processor acts as the conductor managing the actual software logic."),
Q("POSSIBLE QNS", "EASY", "What does 'MVL' mean?", ["Maximum Voltage Limit", "Maximum Vector Length", "Minimum Value Logic", "Main Video Line"], "Maximum Vector Length", "It is a physical hardware limit representing how many items a vector register can hold at once."),
Q("POSSIBLE QNS", "MEDIUM", "What is a 'Scatter' operation?", ["Throwing the CPU away", "Dispersing elements from a coherent vector register out to erratic, non-linear physical memory locations via an index address vector", "Deleting files", "Printing to multiple printers"], "Dispersing elements from a coherent vector register out to erratic, non-linear physical memory locations via an index address vector", "It is the direct opposite of a Gather operation, used for writing sparse data back to RAM."),
Q("POSSIBLE QNS", "HARD", "What is the architectural difference between UMA and NUMA?", ["UMA uses Windows, NUMA uses Linux", "UMA has equal memory access latency for all processors via a shared bus; NUMA partitions memory to nodes, resulting in variable access latency but infinite scalability", "UMA has no RAM", "NUMA uses only hard drives"], "UMA has equal memory access latency for all processors via a shared bus; NUMA partitions memory to nodes, resulting in variable access latency but infinite scalability", "NUMA solves the physical limitations of wires and electricity by breaking the centralized memory model into a distributed network of nodes.")
];

async function insertUnit5Part2() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = ca_unit5_part2.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} questions for CA Unit 5 Part 2.`);
        } else {
            console.log("No new questions for CA Unit 5 Part 2 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit5Part2();
