const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a49ecb638bb37720e3e9194"; // COMPUTER ARCHITECTURE AND ASSEMBLY PROGRAMMING LANGUAGE

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const ca_unit1 = [
// ╔══════════════════════════════════╗
// ║           QUIZ (8 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "What is a 'Register' in digital systems?", ["A large hard drive", "A small unit of storage typically made up of flip-flops capable of holding binary data", "A type of fiber optic cable", "A cooling fan"], "A small unit of storage typically made up of flip-flops capable of holding binary data", "Registers are the fastest, smallest memory locations inside the CPU, used for temporary data storage during processing."),
Q("QUIZ", "EASY", "What does 'RTL' stand for in computer architecture?", ["Real Time Logic", "Register Transfer Language", "Routing Transfer Logic", "Random Tape Loader"], "Register Transfer Language", "RTL is a hardware description language used to describe the flow of data between registers and logic gates."),
Q("QUIZ", "MEDIUM", "What is the primary function of the 'Accumulator' (AC) register?", ["To hold memory addresses", "To store the results of arithmetic and logical operations", "To point to the top of the stack", "To hold the next instruction"], "To store the results of arithmetic and logical operations", "The Accumulator is historically the primary register where calculations from the ALU are temporarily held."),
Q("QUIZ", "MEDIUM", "Which bus is responsible for specifying where data should be read from or written to in memory?", ["Data Bus", "Address Bus", "Control Bus", "USB Bus"], "Address Bus", "The Address Bus carries memory addresses from the CPU to the RAM, indicating the exact location for read/write operations."),
Q("QUIZ", "HARD", "Which addressing mode specifies the operand directly in the instruction itself? (e.g., MOV AX, 5)", ["Register Mode", "Direct Mode", "Immediate Mode", "Indirect Mode"], "Immediate Mode", "In Immediate mode, the actual data value (operand) is hardcoded directly inside the instruction, so no memory fetch is needed."),
Q("QUIZ", "HARD", "What is the main advantage of a 'Hardwired Control Unit' compared to a Micro-programmed one?", ["It is highly flexible", "It executes instructions faster because control signals are generated directly by logic circuits", "It is easier to redesign", "It requires no electricity"], "It executes instructions faster because control signals are generated directly by logic circuits", "Because it uses raw physical logic gates (combinational circuits) rather than software microinstructions, it operates at maximum hardware speed."),
Q("QUIZ", "MEDIUM", "Which CPU component is known as the 'brain' of the CPU, orchestrating data flow and instruction execution?", ["ALU", "Control Unit (CU)", "Memory Stack", "Cache"], "Control Unit (CU)", "The Control Unit fetches, decodes, and directs the execution of instructions, acting as the central coordinator."),
Q("QUIZ", "EASY", "What does the 'Program Counter' (PC) hold?", ["The current time", "The results of an addition", "The memory address of the next instruction to be fetched and executed", "The size of the hard drive"], "The memory address of the next instruction to be fetched and executed", "The PC ensures the CPU knows exactly where to go in memory to grab the very next command in the program."),

// ╔══════════════════════════════════╗
// ║         EXERCISE (8 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "What type of data structure does a 'Memory Stack' use?", ["FIFO (First In, First Out)", "LIFO (Last In, First Out)", "Random Access", "Sequential Access"], "LIFO (Last In, First Out)", "A stack operates on the Last-In-First-Out principle, meaning the most recently added item is the first one to be removed."),
Q("EXERCISE", "EASY", "Which component performs mathematical calculations like addition, subtraction, AND, OR, and NOT?", ["Control Unit", "Arithmetic Logic Unit (ALU)", "Program Counter", "Stack Pointer"], "Arithmetic Logic Unit (ALU)", "The ALU is the digital circuit within the CPU exclusively dedicated to arithmetic and bitwise logical operations."),
Q("EXERCISE", "MEDIUM", "Which of the following is a characteristic of RISC architecture?", ["Complex instruction set", "Memory-to-memory operations", "Single-cycle execution and a large number of general-purpose registers", "Fewer registers and heavy use of microcode"], "Single-cycle execution and a large number of general-purpose registers", "RISC (Reduced Instruction Set Computing) focuses on executing simple instructions very fast, usually in a single clock cycle, relying heavily on registers."),
Q("EXERCISE", "MEDIUM", "What is the purpose of 'Status Flags' (Flag Register)?", ["To show the CPU manufacturer", "To contain individual bits representing the outcome of ALU operations (like carry, zero, overflow) for conditional branching", "To store string variables", "To point to the stack"], "To contain individual bits representing the outcome of ALU operations (like carry, zero, overflow) for conditional branching", "Flags tell the CPU what happened during the last math operation, allowing it to make decisions (e.g., 'Jump if Zero')."),
Q("EXERCISE", "HARD", "In the instruction cycle, what happens during the 'Decode Cycle'?", ["The CPU shuts down", "The ALU adds numbers", "The control unit interprets the fetched instruction to determine what operation to perform and what operands are involved", "Data is saved to the hard drive"], "The control unit interprets the fetched instruction to determine what operation to perform and what operands are involved", "Decoding translates the binary opcode into physical control signals that tell the CPU hardware what to do next."),
Q("EXERCISE", "HARD", "What does 'Indirect Addressing Mode' imply?", ["The operand is a register", "The instruction contains the memory address of a pointer, which in turn contains the address of the actual operand", "The operand is directly in the instruction", "The data is fetched from the cache"], "The instruction contains the memory address of a pointer, which in turn contains the address of the actual operand", "Indirect addressing means looking up a memory location just to find another memory location where the real data lives."),
Q("EXERCISE", "MEDIUM", "Which control signal cycle handles saving the CPU's current state when an external device requests immediate attention?", ["Fetch Cycle", "Execute Cycle", "Interrupt Cycle", "Indirect Cycle"], "Interrupt Cycle", "When a hardware interrupt occurs, the CPU must pause, save its state (like the PC), handle the device, and then resume."),
Q("EXERCISE", "HARD", "Why do CISC architectures typically have fewer general-purpose registers compared to RISC?", ["Because registers are expensive", "Because many CISC operations can directly access and manipulate data in memory (Memory-to-Memory operations)", "Because CISC is older", "Because CISC uses fiber optics"], "Because many CISC operations can directly access and manipulate data in memory (Memory-to-Memory operations)", "Since CISC instructions can perform math directly on RAM addresses, it doesn't need to load everything into local registers first like RISC does."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "What measures the speed of the CPU's electronic pulses, typically in GHz?", ["Data Bus", "Clock", "Cache", "Accumulator"], "Clock", "The system clock dictates the pace at which the CPU executes instructions, measuring cycles per second."),
Q("CAT 1", "EASY", "What is the function of the 'Instruction Register' (IR)?", ["It holds the address of the next instruction", "It holds the currently executing instruction fetched from memory", "It performs addition", "It stores local variables"], "It holds the currently executing instruction fetched from memory", "Once an instruction is fetched from RAM, it sits in the IR so the Control Unit can decode and execute it."),
Q("CAT 1", "MEDIUM", "What is the role of a 'Micro-programmed Control Unit'?", ["It uses pure hardware logic gates to run fast", "It generates control signals using a sequence of microinstructions stored in a special control memory (ROM)", "It manages the cooling fan", "It acts as a hard drive"], "It generates control signals using a sequence of microinstructions stored in a special control memory (ROM)", "Instead of complex wiring, a micro-programmed unit uses a tiny, hidden program to tell the CPU hardware how to execute a machine code instruction."),
Q("CAT 1", "MEDIUM", "Which basic micro operation involves adding 1 to an input value?", ["Shift", "Incrementer", "Subtractor", "Logic AND"], "Incrementer", "An incrementer circuit specifically adds exactly 1 to a binary value, commonly used to update the Program Counter."),
Q("CAT 1", "MEDIUM", "What does 'Pipelining' achieve in modern CPUs?", ["It pumps water through the CPU", "It allows multiple instructions to be processed simultaneously by dividing instruction execution into overlapping stages", "It slows down the CPU to save power", "It stores data permanently"], "It allows multiple instructions to be processed simultaneously by dividing instruction execution into overlapping stages", "Pipelining is like an assembly line; while one instruction is executing, the next is being decoded, and a third is being fetched."),
Q("CAT 1", "HARD", "Which characteristic belongs to a CISC architecture?", ["Single-cycle execution", "Microcode is often used to translate complex instructions into simpler micro-operations", "Load/Store architecture only", "Compiler-friendly simple instructions"], "Microcode is often used to translate complex instructions into simpler micro-operations", "CISC (like Intel x86) uses complex, multi-cycle instructions that the CPU's internal microcode breaks down into simpler steps."),
Q("CAT 1", "HARD", "What defines the 'Direct Addressing Mode'?", ["The operand is a register name", "The instruction provides the exact memory address where the operand is located", "The operand is added to an index", "The operand is hidden"], "The instruction provides the exact memory address where the operand is located", "In direct mode (e.g., MOV AX, [1234]), the CPU goes straight to memory address 1234 to fetch the data."),
Q("CAT 1", "HARD", "What is the 'Stack Pointer' (SP) used for?", ["To point to the hard drive", "To keep track of the top of the stack in memory, incrementing/decrementing during push and pop operations", "To count the number of instructions", "To measure CPU temperature"], "To keep track of the top of the stack in memory, incrementing/decrementing during push and pop operations", "The SP register ensures the CPU always knows where the last pushed item is located in the stack segment."),
Q("CAT 1", "MEDIUM", "In an Instruction Format, what does the 'Opcode' specify?", ["Where the data is stored", "The specific operation to be performed (like ADD, SUB, LOAD)", "The length of the cable", "The clock speed"], "The specific operation to be performed (like ADD, SUB, LOAD)", "The operation code (Opcode) is the binary command that tells the CPU exactly what action to take."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "Which bus carries signals like read, write, and interrupt requests?", ["Data Bus", "Address Bus", "Control Bus", "Universal Bus"], "Control Bus", "The Control Bus carries the commands and timing signals from the Control Unit to all other hardware components."),
Q("CAT 2", "EASY", "What does a 'Binary Adder' do?", ["Subtracts two numbers", "Performs the addition of two binary numbers", "Multiplies numbers", "Stores files"], "Performs the addition of two binary numbers", "A binary adder is a digital logic circuit (built with half and full adders) that computes the sum of binary digits."),
Q("CAT 2", "MEDIUM", "Why is a register set designed with a 'Common ALU'?", ["To make the CPU bigger", "Rather than having separate ALUs for every operation, one shared ALU performs various operations as instructed by the CU, simplifying design", "To eliminate the need for cache", "To slow down calculations"], "Rather than having separate ALUs for every operation, one shared ALU performs various operations as instructed by the CU, simplifying design", "A common ALU reduces hardware complexity and size, acting as a centralized calculation hub for all registers."),
Q("CAT 2", "MEDIUM", "What is one major use of the Memory Stack in programming?", ["To store the operating system kernel", "To manage function calls, return addresses, and local variables automatically", "To permanently save documents", "To control the monitor"], "To manage function calls, return addresses, and local variables automatically", "When a program calls a function, the return address and local variables are pushed to the stack, making recursion and scope management possible."),
Q("CAT 2", "HARD", "What happens during a 'Shift Micro Operation'?", ["The CPU switches to a different program", "The bits of a binary number are moved left or right, which is useful for rapid multiplication or division by 2", "The data is deleted", "The memory address changes"], "The bits of a binary number are moved left or right, which is useful for rapid multiplication or division by 2", "Shifting a binary number left multiplies it by 2; shifting it right divides it by 2. This is faster than using the ALU multiplier."),
Q("CAT 2", "HARD", "What is a major disadvantage of a Micro-programmed Control Unit?", ["It is impossible to modify", "It has slower execution compared to hardwired units because it has the extra overhead of fetching microinstructions from control memory", "It cannot perform arithmetic", "It uses too many physical logic gates"], "It has slower execution compared to hardwired units because it has the extra overhead of fetching microinstructions from control memory", "Reading microcode from a ROM adds an extra layer of processing, making it slightly slower than pure hardwired electrical logic."),
Q("CAT 2", "MEDIUM", "Which register holds memory addresses and is often used in indexed addressing modes for accessing arrays?", ["Accumulator", "Index Register (IX, IY)", "Instruction Register", "Flag Register"], "Index Register (IX, IY)", "Index registers are specifically used to hold offset values to iterate through consecutive memory locations, like an array."),
Q("CAT 2", "HARD", "What does ISA stand for in processor organization?", ["International Standards Agency", "Internal Storage Array", "Instruction Set Architecture", "Integrated System Arithmetic"], "Instruction Set Architecture", "The ISA is the boundary between hardware and software, defining the exact machine language commands the CPU understands."),
Q("CAT 2", "EASY", "Which memory type sits between the CPU and Main Memory to provide extremely fast data access?", ["Hard Drive", "Cache Memory", "Optical Disk", "USB Drive"], "Cache Memory", "Cache is a tiny amount of extremely fast SRAM built directly into or very close to the CPU to hold frequently used data."),

// ╔══════════════════════════════════╗
// ║            UE (8 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "What is the fundamental building block of a CPU's processing power?", ["Hard Drive", "Micro Operations", "Monitor", "Keyboard"], "Micro Operations", "Micro operations (like shift, add, load) are the lowest-level elementary tasks that the CPU strings together to execute full instructions."),
Q("UE", "MEDIUM", "What is a 'Full Adder'?", ["A circuit that only adds zeros", "A digital circuit that adds three binary digits: two inputs and a carry from a previous addition", "A hard drive controller", "A software program"], "A digital circuit that adds three binary digits: two inputs and a carry from a previous addition", "Unlike a half adder, a full adder can handle the 'carry over' from a previous column, allowing computers to add massive binary numbers."),
Q("UE", "MEDIUM", "What is the purpose of the 'Fetch Cycle'?", ["To execute the math", "To retrieve the next instruction from memory using the Program Counter and place it into the Instruction Register", "To save a file", "To handle a hardware interrupt"], "To retrieve the next instruction from memory using the Program Counter and place it into the Instruction Register", "Fetching is the first step of instruction processing, bringing the command from RAM into the CPU."),
Q("UE", "HARD", "How does a CPU implement 'Vector Processing' or 'SIMD'?", ["By executing one instruction on one piece of data", "By using a single instruction to operate on multiple data elements simultaneously, useful for multimedia and scientific computing", "By writing data to a hard drive", "By shutting down extra cores"], "By using a single instruction to operate on multiple data elements simultaneously, useful for multimedia and scientific computing", "Single Instruction, Multiple Data (SIMD) allows the CPU to process an entire array or 'vector' of numbers in one clock cycle."),
Q("UE", "HARD", "In instruction formats, what are 'Operands'?", ["The operation code", "The actual data or memory addresses on which the operation (opcode) is performed", "The length of the instruction", "The CPU cooling mechanism"], "The actual data or memory addresses on which the operation (opcode) is performed", "If the Opcode is 'ADD', the operands are the specific numbers or registers that need to be added together."),
Q("UE", "HARD", "What does 'Base-Register Addressing Mode' involve?", ["Reading directly from the cache", "Storing a base address in a register, and adding an offset to it to access the operand (common for addressing data structures)", "Jumping to a random address", "Using a hardcoded value"], "Storing a base address in a register, and adding an offset to it to access the operand (common for addressing data structures)", "This mode allows programs to be loaded anywhere in memory. The base register holds the start of the program, and offsets point to specific variables."),
Q("UE", "MEDIUM", "Why might a stack suffer a 'Stack Overflow'?", ["Because the CPU is too cold", "Because hardware or OS limits on the fixed stack size are exceeded, often due to deep recursive function calls", "Because the hard drive is full", "Because of a fast internet connection"], "Because hardware or OS limits on the fixed stack size are exceeded, often due to deep recursive function calls", "If a function calls itself infinitely, it keeps pushing frames to the stack until it runs out of allocated memory, crashing the program."),
Q("UE", "EASY", "What is the purpose of 'Temporary Registers' in a CPU?", ["To save files permanently", "To hold intermediate results during complex arithmetic and logical operations before the final answer is stored", "To control the mouse", "To store the operating system"], "To hold intermediate results during complex arithmetic and logical operations before the final answer is stored", "Calculations often require multiple steps. Temp registers hold the halfway answers safely without overwriting user data."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (8 Qns)       ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "What does 'CPU' stand for?", ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Control Processing User"], "Central Processing Unit", "The CPU is the central brain of the computer that fetches, decodes, and executes instructions."),
Q("POSSIBLE QNS", "MEDIUM", "Which architecture heavily relies on compilers to optimize code and schedule simple instructions?", ["CISC", "RISC", "Hardwired", "Von Neumann"], "RISC", "Because RISC instructions are so simple, the software compiler must do the heavy lifting of arranging them optimally to run fast."),
Q("POSSIBLE QNS", "MEDIUM", "What is the function of the 'Memory Management Unit' (MMU)?", ["To manage hard drive spinning", "To translate virtual addresses generated by the CPU into physical addresses in RAM and handle memory protection", "To clear the cache", "To assign IP addresses"], "To translate virtual addresses generated by the CPU into physical addresses in RAM and handle memory protection", "The MMU allows the operating system to safely give each program its own isolated virtual memory space."),
Q("POSSIBLE QNS", "HARD", "What does 'Branch Prediction' do in modern processors?", ["It predicts the weather", "It guesses the outcome of conditional branches (if/else) to fetch and execute instructions speculatively, keeping the pipeline full", "It predicts hard drive failures", "It randomly deletes files"], "It guesses the outcome of conditional branches (if/else) to fetch and execute instructions speculatively, keeping the pipeline full", "To prevent the pipeline from stalling during an 'if' statement, the CPU guesses which way the code will branch and starts executing it early."),
Q("POSSIBLE QNS", "HARD", "Which statement best describes 'Inter-register transfer'?", ["Transferring data from a hard drive to a USB", "The movement of data between different registers within the CPU, typically synchronized by a clock signal", "Sending data over Wi-Fi", "Downloading a file"], "The movement of data between different registers within the CPU, typically synchronized by a clock signal", "This is a core micro-operation. Data is passed from one internal CPU register to another via the internal data bus."),
Q("POSSIBLE QNS", "HARD", "How does a 'Binary Subtractor' handle its calculations?", ["By adding zeros", "By borrowing from higher bits, similar to manual decimal subtraction, usually implemented using two's complement logic", "By ignoring negative numbers", "By multiplying by -1"], "By borrowing from higher bits, similar to manual decimal subtraction, usually implemented using two's complement logic", "Subtractors are built using logic gates to handle borrow-in and borrow-out, though modern ALUs often just use Adders with two's complement."),
Q("POSSIBLE QNS", "MEDIUM", "What is the purpose of the 'Data Bus'?", ["To carry memory addresses", "To transfer actual binary data in parallel between CPU, Memory, and I/O devices", "To send control signals", "To connect to the internet"], "To transfer actual binary data in parallel between CPU, Memory, and I/O devices", "The width of the data bus (e.g., 64-bit) determines how much actual information the CPU can swallow in a single clock cycle."),
Q("POSSIBLE QNS", "EASY", "Which type of register keeps track of the 'Base Pointer' (BP)?", ["Accumulator", "Base Pointer (BP) Register", "Instruction Register", "Program Counter"], "Base Pointer (BP) Register", "The BP holds the base address of the current stack frame, allowing easy access to local variables and parameters passed to a function.")
];

async function insertUnit1() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = ca_unit1.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} questions for CA Unit 1.`);
        } else {
            console.log("No new questions for CA Unit 1 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit1();
