const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a49ecb638bb37720e3e9194"; // COMPUTER ARCHITECTURE AND ASSEMBLY PROGRAMMING LANGUAGE

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const ca_unit2_part2 = [
// ╔══════════════════════════════════╗
// ║           QUIZ (8 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "What is an 'I/O Bus'?", ["A vehicle for computer parts", "A dedicated set of wires (data, address, control) connecting the CPU to I/O interfaces", "A wireless connection protocol", "A power cable for the monitor"], "A dedicated set of wires (data, address, control) connecting the CPU to I/O interfaces", "The I/O bus is specifically tailored to handle the unique timing and addressing needs of peripheral devices."),
Q("QUIZ", "MEDIUM", "Why is 'Programmed I/O' considered inefficient?", ["It is too hard to code", "It ties up the CPU in a continuous polling loop, preventing it from executing other tasks", "It requires too much RAM", "It only works with serial ports"], "It ties up the CPU in a continuous polling loop, preventing it from executing other tasks", "Because the CPU is constantly asking 'Are you ready yet?', it wastes millions of clock cycles that could have been used for math."),
Q("QUIZ", "HARD", "In 'Handshaking', what prevents data loss if the receiving device is extremely slow?", ["A large hard drive buffer", "The sending device refuses to place new data on the bus until the receiving device explicitly asserts a 'Data Accepted' signal", "An automatic reboot mechanism", "A cooling fan"], "The sending device refuses to place new data on the bus until the receiving device explicitly asserts a 'Data Accepted' signal", "This strict back-and-forth communication guarantees that no byte is ever overwritten before the receiver has safely captured it."),
Q("QUIZ", "MEDIUM", "What is the primary function of a 'Data Communication Processor'?", ["To print documents", "To manage and route complex serial network communication protocols independently of the main CPU", "To increase the system clock speed", "To manage the power supply"], "To manage and route complex serial network communication protocols independently of the main CPU", "Also known as a Front-End Processor or NIC, it takes the heavy burden of network routing, error checking, and packet formatting off the main CPU."),
Q("QUIZ", "EASY", "What does 'Asynchronous' data transfer mean?", ["Data is transferred simultaneously", "Data transfer is not tied to a shared, common master clock signal between the sender and receiver", "Data is transferred backwards", "Data transfer happens instantly"], "Data transfer is not tied to a shared, common master clock signal between the sender and receiver", "Without a shared clock, asynchronous systems must use start/stop bits or handshaking to figure out when a byte begins and ends."),
Q("QUIZ", "HARD", "How does 'Cycle Stealing' work in DMA?", ["The DMA steals power from the RAM", "The DMA controller asserts the bus request, transfers exactly one data word, and immediately returns control to the CPU, repeating this process", "The CPU steals data from the DMA", "The DMA stops the system clock"], "The DMA controller asserts the bus request, transfers exactly one data word, and immediately returns control to the CPU, repeating this process", "This interleaves DMA transfers with CPU execution, so the CPU is never completely locked out of the bus for long periods."),
Q("QUIZ", "MEDIUM", "What defines 'Memory-Mapped I/O'?", ["I/O devices are stored on the hard drive", "I/O interface registers are assigned standard memory addresses, allowing the CPU to use normal memory instructions to communicate with them", "I/O devices have their own special memory chips", "I/O devices are mapped physically on a map"], "I/O interface registers are assigned standard memory addresses, allowing the CPU to use normal memory instructions to communicate with them", "For example, writing a byte to memory address 0xFFFF0000 might actually turn on a pixel on the screen rather than storing data in RAM."),
Q("QUIZ", "HARD", "What is the function of an 'Interrupt Vector'?", ["A virus that attacks the system", "A specific memory address provided by the interrupting device that points the CPU directly to the correct Interrupt Service Routine (ISR)", "A physical cable", "A mathematical calculation"], "A specific memory address provided by the interrupting device that points the CPU directly to the correct Interrupt Service Routine (ISR)", "Vectored interrupts eliminate the need for software polling, making interrupt handling incredibly fast."),

// ╔══════════════════════════════════╗
// ║         EXERCISE (8 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "What is 'Serial Communication'?", ["Sending multiple bits at once", "Transmitting data sequentially, one bit at a time, over a single communication channel", "Sending data over Wi-Fi only", "Printing data serially"], "Transmitting data sequentially, one bit at a time, over a single communication channel", "Serial communication uses fewer wires and is much less susceptible to signal interference over long distances compared to parallel."),
Q("EXERCISE", "MEDIUM", "What is the key feature of 'Isolated I/O'?", ["It isolates the computer from the internet", "It uses a completely separate address space and dedicated instructions (like IN and OUT) specifically for I/O devices", "It isolates the CPU from the RAM", "It uses wireless technology"], "It uses a completely separate address space and dedicated instructions (like IN and OUT) specifically for I/O devices", "This preserves the entire memory address space for RAM, but requires programmers to use specialized, limited I/O instructions."),
Q("EXERCISE", "HARD", "What is the purpose of the 'Strobe Signal' in asynchronous transfer?", ["To flash a physical light", "A single control line used to inform the destination unit that valid data is currently available on the data bus", "To reboot the system", "To increase voltage"], "A single control line used to inform the destination unit that valid data is currently available on the data bus", "While simple, the strobe method is risky because the sender doesn't know if the receiver was fast enough to actually read the data."),
Q("EXERCISE", "MEDIUM", "What does a 'Status Command' do in an I/O interface?", ["It formats the device", "It allows the CPU to read the interface's status register to check if the peripheral is ready, busy, or in an error state", "It sends data to the device", "It powers off the device"], "It allows the CPU to read the interface's status register to check if the peripheral is ready, busy, or in an error state", "Before writing data to a printer, the CPU must send a status command to ensure the printer isn't out of paper."),
Q("EXERCISE", "HARD", "How does a 'Daisy-Chain' priority interrupt work?", ["By linking computers together", "The interrupt acknowledge signal from the CPU passes serially through devices; the first device in the chain that requested an interrupt intercepts it", "By randomly selecting a device", "By using a software array"], "The interrupt acknowledge signal from the CPU passes serially through devices; the first device in the chain that requested an interrupt intercepts it", "Hardware daisy-chaining is a fast, physical way to establish priority. Device 1 gets the signal first. If it didn't interrupt, it passes the signal to Device 2, and so on."),
Q("EXERCISE", "EASY", "What is 'DMA' primarily used for?", ["Calculating complex math", "Transferring large blocks of data between high-speed peripherals (like disk drives) and memory without involving the CPU", "Playing audio files", "Cooling the processor"], "Transferring large blocks of data between high-speed peripherals (like disk drives) and memory without involving the CPU", "DMA is a lifesaver for performance. It acts as a secondary mini-processor dedicated solely to moving data."),
Q("EXERCISE", "MEDIUM", "What distinguishes an 'I/O Processor' (IOP) from a standard DMA controller?", ["An IOP is slower", "An IOP is essentially a specialized CPU that can execute complex I/O programs (channel programs) independently, whereas DMA just moves raw blocks of data", "An IOP has no memory", "An IOP only works with printers"], "An IOP is essentially a specialized CPU that can execute complex I/O programs (channel programs) independently, whereas DMA just moves raw blocks of data", "IOPs are found in high-end mainframes, capable of executing complex branching logic and error correction without waking up the main CPU."),
Q("EXERCISE", "HARD", "In asynchronous serial transfer, what is the 'Baud Rate'?", ["The size of the data packet", "The rate of signal changes (modulation rate) on the transmission medium, which must be agreed upon by both sender and receiver", "The heat of the cable", "The voltage level"], "The rate of signal changes (modulation rate) on the transmission medium, which must be agreed upon by both sender and receiver", "If the sender is sending at 9600 baud and the receiver is listening at 115200 baud, the data will just look like garbage noise."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "Which component manages data transfers without CPU intervention?", ["ALU", "DMA Controller", "Program Counter", "Cache Memory"], "DMA Controller", "The Direct Memory Access controller takes over the system buses to blast data directly into RAM."),
Q("CAT 1", "MEDIUM", "Why is an 'I/O Interface' required?", ["To make the computer heavier", "To resolve differences in operating speed, data format, and electrical characteristics between the CPU and mechanical/electrical peripherals", "To generate Wi-Fi signals", "To store the operating system"], "To resolve differences in operating speed, data format, and electrical characteristics between the CPU and mechanical/electrical peripherals", "A CPU operates in nanoseconds at 1V. A printer operates in seconds at 12V. The interface bridges this massive gap."),
Q("CAT 1", "HARD", "What is the difference between a 'Selector Channel' and a 'Multiplexer Channel' in an IOP?", ["They are identical", "A selector channel dedicates itself to one high-speed device until the transfer is done; a multiplexer interleaves bytes from multiple slow devices", "Selector is for input, Multiplexer is for output", "Multiplexer is for video, Selector is for audio"], "A selector channel dedicates itself to one high-speed device until the transfer is done; a multiplexer interleaves bytes from multiple slow devices", "A selector is like a dedicated express lane for a hard drive, while a multiplexer is like a traffic cop letting multiple keyboards take turns sending a byte."),
Q("CAT 1", "EASY", "What does 'Interrupt-Initiated I/O' do?", ["Crashes the computer", "Allows the peripheral to interrupt the CPU only when it is ready, freeing the CPU to do other work instead of polling", "Deletes data", "Slows down the internet"], "Allows the peripheral to interrupt the CPU only when it is ready, freeing the CPU to do other work instead of polling", "This is the basis of modern event-driven architecture."),
Q("CAT 1", "MEDIUM", "What is a 'Data Output Command'?", ["A command to print to screen", "An I/O command issued by the CPU that causes the interface to take data from the data bus and send it to the peripheral device", "A command to read the hard drive", "A status check"], "An I/O command issued by the CPU that causes the interface to take data from the data bus and send it to the peripheral device", "This is the command used when the CPU actually wants to push data out to the real world."),
Q("CAT 1", "HARD", "How does the CPU grant bus control to the DMA controller?", ["By turning off", "By finishing its current instruction, placing its bus pins in a high-impedance (tri-state) mode, and asserting the Bus Grant (BG) signal", "By sending an email", "By deleting a file"], "By finishing its current instruction, placing its bus pins in a high-impedance (tri-state) mode, and asserting the Bus Grant (BG) signal", "Tri-stating electrically disconnects the CPU from the motherboard wires so the DMA controller can drive the signals instead."),
Q("CAT 1", "MEDIUM", "What is 'Software Polling' in the context of interrupts?", ["A survey of users", "When an interrupt occurs, the CPU executes a routine that checks the status flag of each device in sequence to find out who interrupted", "Downloading software", "Checking for viruses"], "When an interrupt occurs, the CPU executes a routine that checks the status flag of each device in sequence to find out who interrupted", "This is used in non-vectored systems. The CPU has to manually ask 'Was it you?' down the list of devices until one says 'Yes'."),
Q("CAT 1", "HARD", "What is 'Burst Mode' DMA?", ["A fast internet connection", "The DMA controller seizes control of the bus and transfers an entire block of data continuously before giving the bus back to the CPU", "A CPU overclocking feature", "A type of virus"], "The DMA controller seizes control of the bus and transfers an entire block of data continuously before giving the bus back to the CPU", "This is incredibly fast for the data transfer, but it completely stalls the CPU for the duration of the burst because the CPU has no access to RAM."),
Q("CAT 1", "EASY", "What is 'Parallel Communication'?", ["Sending data over Wi-Fi", "Sending multiple bits of data simultaneously over multiple parallel wires", "Sending data one bit at a time", "Printing a document"], "Sending multiple bits of data simultaneously over multiple parallel wires", "Parallel communication is very fast but usually restricted to short distances (like inside the motherboard) due to signal crosstalk."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "What is 'Programmed I/O'?", ["Programming the OS", "A data transfer method where the CPU executes a continuous loop, polling the device's status until it is ready", "Using a mouse", "Connecting to a network"], "A data transfer method where the CPU executes a continuous loop, polling the device's status until it is ready", "It is the simplest but most inefficient form of I/O, as it wastes CPU cycles on waiting."),
Q("CAT 2", "MEDIUM", "What is 'Memory-Mapped I/O'?", ["Storing memory on a disk", "An architecture where I/O devices are treated exactly like memory locations, using the same address space and memory instructions", "A way to map the internet", "A graphical map of the RAM"], "An architecture where I/O devices are treated exactly like memory locations, using the same address space and memory instructions", "This makes programming simpler because you don't need special IN/OUT assembly commands, but it does consume part of the RAM's address space."),
Q("CAT 2", "HARD", "What is the role of a UART?", ["To generate 3D graphics", "Universal Asynchronous Receiver-Transmitter; it converts parallel data from the CPU into a serial bit stream, and vice versa", "To amplify sound", "To manage the power supply"], "Universal Asynchronous Receiver-Transmitter; it converts parallel data from the CPU into a serial bit stream, and vice versa", "The UART is the crucial chip that allows computers to communicate over serial ports, USB, and modems."),
Q("CAT 2", "EASY", "What does 'Asynchronous' mean?", ["Happening at the same time", "Lacking a shared master clock signal; events happen independently and are coordinated by control signals like handshaking", "Running very fast", "Using Wi-Fi"], "Lacking a shared master clock signal; events happen independently and are coordinated by control signals like handshaking", "Asynchronous transfer is necessary when the CPU and the peripheral operate at vastly different, un-synchronized speeds."),
Q("CAT 2", "MEDIUM", "What is an 'Interrupt Controller'?", ["A switch to turn off the PC", "A hardware chip that manages multiple peripheral interrupt requests, resolves priority, and sends a single interrupt signal to the CPU", "A software program", "A type of firewall"], "A hardware chip that manages multiple peripheral interrupt requests, resolves priority, and sends a single interrupt signal to the CPU", "Since the CPU only has one or two physical interrupt pins, the controller acts as a multiplexer for all the devices on the motherboard."),
Q("CAT 2", "HARD", "How does 'Handshaking' improve upon 'Strobe Control'?", ["It uses less electricity", "It introduces an acknowledgment signal from the receiver, confirming data receipt and preventing data loss if the receiver is slow", "It is an older technology", "It encrypts the data"], "It introduces an acknowledgment signal from the receiver, confirming data receipt and preventing data loss if the receiver is slow", "Strobe is a one-way shout. Handshaking is a two-way conversation ensuring reliability."),
Q("CAT 2", "MEDIUM", "What is the difference between 'Isolated I/O' and 'Memory-Mapped I/O'?", ["Isolated I/O is faster", "Isolated uses separate address spaces and specific instructions (IN/OUT), while Memory-Mapped shares the RAM address space and uses standard memory instructions", "Memory-Mapped has no memory", "They are the exact same thing"], "Isolated uses separate address spaces and specific instructions (IN/OUT), while Memory-Mapped shares the RAM address space and uses standard memory instructions", "Intel x86 architectures historically favored Isolated I/O, while ARM and Motorola favored Memory-Mapped I/O."),
Q("CAT 2", "HARD", "In asynchronous serial transfer, what is the purpose of the 'Start Bit'?", ["To turn the computer on", "To signal the receiver that a new character frame is beginning, allowing it to synchronize its internal clock for that character", "To encrypt the character", "To indicate the end of the file"], "To signal the receiver that a new character frame is beginning, allowing it to synchronize its internal clock for that character", "Because there is no shared clock line, the start bit (usually a transition from high to low voltage) wakes up the receiver's timing circuit."),
Q("CAT 2", "EASY", "Which device usually has the highest interrupt priority?", ["The Keyboard", "The System Clock or a high-speed disk drive", "The Mouse", "The Printer"], "The System Clock or a high-speed disk drive", "Data from a fast spinning hard drive will be lost if not read immediately, whereas a human pressing a keyboard key can wait a few extra milliseconds."),

// ╔══════════════════════════════════╗
// ║            UE (8 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "What is an 'I/O Processor' (IOP)?", ["A generic CPU", "A dedicated, advanced processor that executes specialized I/O programs to manage peripherals independently of the main CPU", "A cooling fan", "A graphics card"], "A dedicated, advanced processor that executes specialized I/O programs to manage peripherals independently of the main CPU", "IOPs are mostly found in large mainframes where I/O traffic is so heavy it would overwhelm a standard CPU or DMA controller."),
Q("UE", "MEDIUM", "What is the purpose of 'Cycle Stealing' in DMA?", ["To steal data from the user", "To transfer data one word at a time by occasionally taking control of the bus for one clock cycle, minimizing CPU stall time", "To speed up the clock", "To format the hard drive"], "To transfer data one word at a time by occasionally taking control of the bus for one clock cycle, minimizing CPU stall time", "Unlike Burst Mode, Cycle Stealing ensures the CPU never stops executing instructions for too long, maintaining system responsiveness."),
Q("UE", "HARD", "What does the CPU use a 'Control Command' for?", ["To turn off the monitor", "To transmit an action-specific instruction to the peripheral, such as 'rewind tape' or 'move read head'", "To delete a file", "To transfer binary data"], "To transmit an action-specific instruction to the peripheral, such as 'rewind tape' or 'move read head'", "This command doesn't move data payload; it manipulates the physical or logical state of the peripheral mechanism."),
Q("UE", "MEDIUM", "What is a 'Vectored Interrupt'?", ["An interrupt that uses vectors for graphics", "An interrupt where the hardware device supplies a specific branch address (vector) telling the CPU exactly where the handler routine is", "An interrupt from a virus", "An interrupt that cannot be stopped"], "An interrupt where the hardware device supplies a specific branch address (vector) telling the CPU exactly where the handler routine is", "This hardware-based approach is incredibly fast because the CPU doesn't have to waste time polling devices to find the source."),
Q("UE", "HARD", "In a 'Daisy-Chaining' priority setup, what happens if a lower-priority device requests an interrupt while a higher-priority device is also requesting one?", ["The lower-priority device is serviced first", "The higher-priority device intercepts the CPU's acknowledge signal, services its interrupt, and blocks the signal from reaching the lower-priority device", "The system crashes", "They are serviced simultaneously"], "The higher-priority device intercepts the CPU's acknowledge signal, services its interrupt, and blocks the signal from reaching the lower-priority device", "The physical wiring guarantees that the device closer to the CPU on the chain always wins conflicts."),
Q("UE", "EASY", "What does 'Baud Rate' refer to?", ["The size of the monitor", "The rate at which the signal changes per second on a communication channel", "The temperature of the CPU", "The speed of the hard drive spinning"], "The rate at which the signal changes per second on a communication channel", "In simple binary serial communication, the baud rate is equivalent to the bits per second (bps)."),
Q("UE", "MEDIUM", "What does 'Programmed I/O' severely lack?", ["Code simplicity", "Efficiency, as it forces the CPU into a busy-wait polling loop rather than using interrupts", "Compatibility with keyboards", "The ability to transfer data"], "Efficiency, as it forces the CPU into a busy-wait polling loop rather than using interrupts", "It is the electronic equivalent of constantly asking 'Are we there yet?' instead of waiting to be told when you arrive."),
Q("UE", "HARD", "What is the primary function of a 'Data Output Command' in an interface?", ["To print a document", "To trigger the interface to take data from the system data bus and load it into its internal buffer register for the peripheral", "To format a disk", "To check the device status"], "To trigger the interface to take data from the system data bus and load it into its internal buffer register for the peripheral", "It is the final step in the CPU's process of pushing data out. Once in the interface buffer, the slower peripheral can take its time reading it."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (8 Qns)       ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "What does the 'I/O Bus' carry?", ["Only power", "Data, Address, and Control signals specifically for peripheral interfaces", "Only Wi-Fi signals", "Only audio signals"], "Data, Address, and Control signals specifically for peripheral interfaces", "It is the dedicated highway system connecting the motherboard to the outside world."),
Q("POSSIBLE QNS", "MEDIUM", "What is the key advantage of 'DMA'?", ["It increases CPU clock speed", "It allows high-speed data transfer directly between memory and peripherals without consuming CPU processing cycles", "It acts as a firewall", "It encrypts data automatically"], "It allows high-speed data transfer directly between memory and peripherals without consuming CPU processing cycles", "By offloading the manual labor of moving bytes, the CPU can focus on executing complex software logic."),
Q("POSSIBLE QNS", "HARD", "What is 'Strobe Control'?", ["A flashing light in a club", "An asynchronous transfer method using a single control line (strobe) to indicate when data on the bus is valid", "A method for encrypting data", "A type of DMA transfer"], "An asynchronous transfer method using a single control line (strobe) to indicate when data on the bus is valid", "It is simple and requires few wires, but it is dangerous if the receiving device is too slow to catch the strobe."),
Q("POSSIBLE QNS", "MEDIUM", "What is a 'Data Input Command'?", ["A command to type on a keyboard", "An instruction from the CPU telling the interface to receive data from the peripheral and place it on the data bus", "A command to turn off the computer", "A command to check printer ink"], "An instruction from the CPU telling the interface to receive data from the peripheral and place it on the data bus", "This is how the CPU pulls data in from the real world, like reading a file from a disk."),
Q("POSSIBLE QNS", "HARD", "How does a CPU handle an 'Interrupt'?", ["It ignores it", "It finishes the current instruction, pushes the Program Counter and flags to the stack, and branches to the Interrupt Service Routine", "It turns off immediately", "It deletes the current program"], "It finishes the current instruction, pushes the Program Counter and flags to the stack, and branches to the Interrupt Service Routine", "This context-switching is vital. By saving the PC to the stack, the CPU knows exactly where to resume once the interrupt is handled."),
Q("POSSIBLE QNS", "EASY", "Which mode is best for a keyboard input?", ["Direct Memory Access (DMA)", "Interrupt-Initiated I/O", "Burst Mode DMA", "Cycle Stealing"], "Interrupt-Initiated I/O", "Keyboards are extremely slow and generate very little data. DMA would be overkill, and polling would waste CPU time. Interrupts are perfect."),
Q("POSSIBLE QNS", "MEDIUM", "What does a 'Status Command' read?", ["The size of the hard drive", "The status register of the interface, which contains flags indicating conditions like 'device busy', 'data ready', or 'error'", "The temperature of the CPU", "The Wi-Fi password"], "The status register of the interface, which contains flags indicating conditions like 'device busy', 'data ready', or 'error'", "Before any data transfer, the CPU or DMA must read the status register to ensure the device is in a valid state."),
Q("POSSIBLE QNS", "HARD", "What is the difference between a 'Multiplexer Channel' and a 'Selector Channel' in an I/O Processor?", ["They are the same", "Multiplexers interleave data transfers from multiple slow devices concurrently; Selectors dedicate themselves to one fast device until finished", "Multiplexers are for software, Selectors are for hardware", "Multiplexers only work with RAM"], "Multiplexers interleave data transfers from multiple slow devices concurrently; Selectors dedicate themselves to one fast device until finished", "Multiplexing is like a bartender serving multiple slow-drinking patrons at once. Selecting is like pouring a massive keg for one patron until it's empty.")
];

async function insertUnit2Part2() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = ca_unit2_part2.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} questions for CA Unit 2 Part 2.`);
        } else {
            console.log("No new questions for CA Unit 2 Part 2 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit2Part2();
