const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a49ecb638bb37720e3e9194"; // COMPUTER ARCHITECTURE AND ASSEMBLY PROGRAMMING LANGUAGE

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const ca_unit5_part1 = [
// ╔══════════════════════════════════╗
// ║           QUIZ (8 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "What does NUMA stand for in computer architecture?", ["Non-Uniform Memory Access", "Network User Multi-Array", "New Universal Memory Architecture", "Node-Unified Memory Access"], "Non-Uniform Memory Access", "NUMA is a memory design used in multiprocessing where memory access time depends on the memory location relative to the processor."),
Q("QUIZ", "MEDIUM", "What is the primary difference between UMA and NUMA architectures?", ["UMA is used for graphics, NUMA for audio", "In UMA, all processors share memory equally with the same access latency; in NUMA, processors access local memory faster than remote memory", "UMA is faster than NUMA", "NUMA does not use RAM"], "In UMA, all processors share memory equally with the same access latency; in NUMA, processors access local memory faster than remote memory", "UMA suffers from bus contention when scaled to many processors, while NUMA solves this by partitioning memory to local nodes."),
Q("QUIZ", "HARD", "In vector computation, what is the purpose of 'Strip Mining'?", ["To extract precious metals from the CPU", "A compiler/hardware technique to handle arbitrary loop lengths by partitioning them into segments matching the Maximum Vector Length (MVL) of the physical registers", "To delete data sequentially", "To encrypt vector arrays"], "A compiler/hardware technique to handle arbitrary loop lengths by partitioning them into segments matching the Maximum Vector Length (MVL) of the physical registers", "If a vector register holds 64 elements, and a loop needs 100 iterations, strip mining runs one batch of 64 and a second remainder batch of 36."),
Q("QUIZ", "MEDIUM", "What defines 'CC-NUMA'?", ["Cloud-Controlled NUMA", "Cache-Coherent NUMA; the hardware automatically maintains consistency across all remote and local caches if data is modified", "Custom Core NUMA", "Centralized Cache NUMA"], "Cache-Coherent NUMA; the hardware automatically maintains consistency across all remote and local caches if data is modified", "Without hardware cache coherence (NC-NUMA), the software compiler or OS has to manually track if another processor modified a variable, which is extremely difficult."),
Q("QUIZ", "EASY", "What does a 'Vector Processor' do?", ["Processes only text", "Manipulates one-dimensional arrays of data (vectors) using a single instruction rather than looping through individual scalar operands", "Draws vector graphics on a screen", "Connects to Wi-Fi"], "Manipulates one-dimensional arrays of data (vectors) using a single instruction rather than looping through individual scalar operands", "This SIMD approach provides massive data throughput for mathematical workflows."),
Q("QUIZ", "HARD", "What is 'Vector Chaining'?", ["Tying computers together", "An optimization similar to scalar data forwarding; it feeds the results exiting one vector pipeline directly into the start of a second vector pipeline without waiting for the full vector to finish", "Encrypting a sequence of vectors", "Connecting to a network"], "An optimization similar to scalar data forwarding; it feeds the results exiting one vector pipeline directly into the start of a second vector pipeline without waiting for the full vector to finish", "If computing Y = A * X + B, chaining allows the addition pipeline to start working on the very first element of the product instantly after it leaves the multiplier."),
Q("QUIZ", "MEDIUM", "In memory architecture, what does a 'Point-to-point interconnect' (like Intel UPI) replace?", ["The hard drive", "The shared system bus, allowing highly scalable communication between NUMA nodes without the bottleneck of a single shared wire", "The CPU fan", "The monitor cable"], "The shared system bus, allowing highly scalable communication between NUMA nodes without the bottleneck of a single shared wire", "Shared buses cap out at about 4-8 processors because they get congested. Point-to-point links scale to thousands of cores."),
Q("QUIZ", "HARD", "How does 'Vector Mask Control' handle conditional branches (IF-ELSE) within a vector loop?", ["By stopping the processor", "It uses a boolean mask register; operations are performed on all elements, but write-back is predicated on the mask bit, eliminating speculative branching penalties", "By skipping the IF statement", "By asking the user"], "It uses a boolean mask register; operations are performed on all elements, but write-back is predicated on the mask bit, eliminating speculative branching penalties", "Instead of breaking the parallel execution flow to branch, the processor calculates everything and simply throws away the results for the elements where the 'IF' condition was false."),

// ╔══════════════════════════════════╗
// ║         EXERCISE (8 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "Why is a 'Shared System Bus' a bottleneck in UMA?", ["It uses too much power", "As you add more processors, they all fight to use the exact same wire to access memory, causing severe traffic jams", "It physically breaks easily", "It cannot connect to the internet"], "As you add more processors, they all fight to use the exact same wire to access memory, causing severe traffic jams", "This contention limits symmetric multiprocessing (SMP) to a small number of sockets before performance actually degrades."),
Q("EXERCISE", "MEDIUM", "What is 'Strided Memory Access' in vector architectures?", ["Accessing memory over Wi-Fi", "Accessing elements separated by a constant interval greater than 1 (like reading a specific column in a matrix) to load non-contiguous data into a continuous register", "Accessing memory randomly", "Deleting memory sequentially"], "Accessing elements separated by a constant interval greater than 1 (like reading a specific column in a matrix) to load non-contiguous data into a continuous register", "Normally, fetching 'every 4th item' in RAM kills cache performance. Vector processors have specialized address logic to handle strides seamlessly."),
Q("EXERCISE", "HARD", "How does a 'Memory-to-Memory' vector processor differ from a 'Register-to-Register' one?", ["Memory-to-Memory uses Wi-Fi", "Memory-to-Memory streams data directly from RAM to the ALU and back without using vector registers, causing high startup latency but allowing infinitely long vectors", "Register-to-Register uses no RAM", "Memory-to-Memory is purely software"], "Memory-to-Memory streams data directly from RAM to the ALU and back without using vector registers, causing high startup latency but allowing infinitely long vectors", "Older architectures used Memory-to-Memory. Modern ones use Register-to-Register (like Cray-1) because it prevents the RAM from becoming a severe bottleneck during complex math."),
Q("EXERCISE", "MEDIUM", "What characterizes 'NC-NUMA'?", ["Non-Cache-Coherent NUMA; hardware does not track cache consistency across nodes, leaving the burden entirely to the software/OS", "New Cache NUMA; it uses the newest cache technology", "Network Connected NUMA", "Non-Centralized NUMA"], "Non-Cache-Coherent NUMA; hardware does not track cache consistency across nodes, leaving the burden entirely to the software/OS", "NC-NUMA is simpler to build but notoriously difficult to program for, as developers must manually flush caches to prevent reading stale data."),
Q("EXERCISE", "EASY", "What does 'MVL' stand for in vector processing?", ["Memory Voltage Level", "Maximum Vector Length; the physical capacity of a vector register (e.g., 64 elements)", "Minimum Video Latency", "Multiple Variable Logic"], "Maximum Vector Length; the physical capacity of a vector register (e.g., 64 elements)", "If a loop has 100 elements, it exceeds the MVL of 64, requiring Strip Mining to process."),
Q("EXERCISE", "HARD", "What is a 'Scatter-Gather' operation?", ["Throwing the computer across the room", "Gather collects sparsely scattered elements into a coherent vector register using an index array; Scatter disperses them back to erratic memory locations", "A virus that deletes files", "A method for printing documents"], "Gather collects sparsely scattered elements into a coherent vector register using an index array; Scatter disperses them back to erratic memory locations", "This is crucial for complex simulations where data isn't neatly organized in a straight line in RAM."),
Q("EXERCISE", "MEDIUM", "What is the role of 'Scalar Registers & Units' in a vector architecture?", ["They are completely unused", "They operate alongside vector units to manage loop counters, calculate branch conditions, and compute base memory addresses", "To generate graphics", "To cool the system"], "They operate alongside vector units to manage loop counters, calculate branch conditions, and compute base memory addresses", "Vector units do the heavy lifting, but scalar units still handle the basic housekeeping logic of the program."),
Q("EXERCISE", "HARD", "Why does NUMA present a unified logical address space despite physically partitioned memory?", ["Because it only uses one hard drive", "To allow the operating system and applications to see one giant pool of RAM (e.g., 1TB), even though that RAM is physically split across 4 different CPU sockets", "To hide the RAM from the user", "Because it uses the cloud"], "To allow the operating system and applications to see one giant pool of RAM (e.g., 1TB), even though that RAM is physically split across 4 different CPU sockets", "This makes programming much easier. The software requests an address, and the hardware handles routing it to the correct local or remote memory bank automatically."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "What is 'UMA'?", ["Universal Memory Adapter", "Uniform Memory Access; an architecture where all processors have equal, deterministic access times to a centralized shared memory", "United Memory Array", "Ultra Memory Access"], "Uniform Memory Access; an architecture where all processors have equal, deterministic access times to a centralized shared memory", "Standard desktop motherboards use UMA, but it doesn't scale well for massive supercomputers."),
Q("CAT 1", "MEDIUM", "What makes 'Vector Chaining' so powerful?", ["It chains the power supply to the wall", "It prevents the processor from waiting for an entire vector operation to finish before starting the next dependent operation, heavily amplifying performance", "It deletes old files automatically", "It prevents all viruses"], "It prevents the processor from waiting for an entire vector operation to finish before starting the next dependent operation, heavily amplifying performance", "Instead of a sequential traffic jam, the data flows seamlessly through multiple ALUs like water through pipes."),
Q("CAT 1", "HARD", "In CC-NUMA, what protocols are typically used to maintain cache coherence?", ["TCP/IP", "Hardware protocols like MESI, MOESI, or directory-based schemes", "HTTP and FTP", "Wi-Fi protocols"], "Hardware protocols like MESI, MOESI, or directory-based schemes", "These protocols ensure that if CPU 1 modifies a variable in its cache, CPU 2's cached copy of that variable is instantly marked as 'Invalid' so CPU 2 doesn't use stale data."),
Q("CAT 1", "EASY", "What computing paradigm does Vector Processing use?", ["SISD (Single Instruction, Single Data)", "SIMD (Single Instruction, Multiple Data)", "MIMD", "MISD"], "SIMD (Single Instruction, Multiple Data)", "A single instruction tells the hardware to process an entire array of data at once."),
Q("CAT 1", "MEDIUM", "What is a 'Vector Register'?", ["A book that logs data", "A fixed-size storage block inside the CPU capable of holding an array of scalar elements (e.g., 64 floats) for parallel processing", "A hard drive sector", "A type of internet connection"], "A fixed-size storage block inside the CPU capable of holding an array of scalar elements (e.g., 64 floats) for parallel processing", "Unlike a standard 64-bit register that holds one number, a vector register might be 2048-bits wide, holding many numbers."),
Q("CAT 1", "HARD", "How does 'Strip Mining' calculate the remainder for its first iteration?", ["It guesses the remainder", "It computes VL = N % MVL, where N is total elements and MVL is max vector length, executing this chunk first to align subsequent chunks to exact MVL boundaries", "It divides by 2", "It uses the internet to find the answer"], "It computes VL = N % MVL, where N is total elements and MVL is max vector length, executing this chunk first to align subsequent chunks to exact MVL boundaries", "This ensures that the massive hardware pipelines are filled completely with exactly 64 elements for the rest of the loop, maximizing efficiency."),
Q("CAT 1", "MEDIUM", "Why is 'Local Memory' important in NUMA?", ["It is cheaper", "Accessing memory directly attached to a processor's own memory controller is significantly faster than accessing remote memory attached to another processor", "It is non-volatile", "It is used for graphics"], "Accessing memory directly attached to a processor's own memory controller is significantly faster than accessing remote memory attached to another processor", "The OS tries very hard to keep a program and its data on the same physical NUMA node to avoid the latency penalty of cross-node communication."),
Q("CAT 1", "HARD", "What is the primary drawback of 'Memory-to-Memory' vector processors?", ["They do not use electricity", "They require extremely high startup latencies to fill the pipelines directly from slow main memory, as they lack high-speed intermediary vector registers", "They only process text", "They cannot do math"], "They require extremely high startup latencies to fill the pipelines directly from slow main memory, as they lack high-speed intermediary vector registers", "This is why modern architectures (like GPUs and AVX units) use Register-to-Register designs instead."),
Q("CAT 1", "EASY", "What is the 'Vector Length' (VL)?", ["The physical length of the motherboard", "The exact number of scalar elements currently being processed in a vector register", "The length of a hard drive cable", "The time it takes to boot"], "The exact number of scalar elements currently being processed in a vector register", "If a loop has 32 elements, the software sets the hardware VL register to 32 so the processor doesn't waste energy processing garbage data in the remaining slots."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "What is the main limitation of UMA scalability?", ["It costs too much", "Bus contention; too many processors trying to use the shared bus and memory controller simultaneously", "It uses too much internet bandwidth", "It requires too much cooling"], "Bus contention; too many processors trying to use the shared bus and memory controller simultaneously", "Imagine 64 people trying to walk through a single door at the same time. That is UMA with 64 cores."),
Q("CAT 2", "MEDIUM", "What is the function of the 'Vector Control Unit'?", ["To draw vector graphics", "To decode vector instructions, track structural conflicts, and manage elements like vector lengths", "To cool the CPU", "To supply power"], "To decode vector instructions, track structural conflicts, and manage elements like vector lengths", "It acts as the traffic cop, ensuring that if two instructions need the multiplication pipeline, they don't crash into each other."),
Q("CAT 2", "HARD", "How does 'Vector Mask Control' eliminate speculative branching penalties?", ["It deletes the branch completely", "By avoiding branch predictions altogether; it executes the math for every element, but uses the mask to silently discard the results for elements where the condition was false", "By stopping the clock", "By crashing the program"], "By avoiding branch predictions altogether; it executes the math for every element, but uses the mask to silently discard the results for elements where the condition was false", "While it seems wasteful to do math you don't need, it is actually much faster than flushing a massive vector pipeline due to a wrong branch prediction."),
Q("CAT 2", "EASY", "What does 'CC-NUMA' stand for?", ["Central-Core NUMA", "Cache-Coherent NUMA", "Cloud-Connected NUMA", "Custom-Circuit NUMA"], "Cache-Coherent NUMA", "It is the gold standard for enterprise servers, handling the messy job of keeping data synchronized in hardware."),
Q("CAT 2", "MEDIUM", "What does a 'Gather' operation do in vector processing?", ["Collects files into a zip", "Uses a vector of index pointers to collect sparsely scattered elements from diverse RAM addresses into a single coherent vector register", "Gathers error logs", "Collects internet packets"], "Uses a vector of index pointers to collect sparsely scattered elements from diverse RAM addresses into a single coherent vector register", "If you need array items [1, 50, 99, 1002], 'Gather' hardware reaches out and pulls them all into one register simultaneously."),
Q("CAT 2", "HARD", "In Strip Mining, what happens if the total loop iterations (N) are exactly divisible by the Max Vector Length (MVL)?", ["The computer crashes", "The remainder (VL = N % MVL) is zero, so the loop executes exclusively in perfectly aligned chunks of MVL without a specialized initial remainder iteration", "The data is deleted", "The loop skips entirely"], "The remainder (VL = N % MVL) is zero, so the loop executes exclusively in perfectly aligned chunks of MVL without a specialized initial remainder iteration", "This is the most efficient scenario possible, allowing maximum throughput with zero overhead."),
Q("CAT 2", "MEDIUM", "What is the primary advantage of a 'Register-to-Register' vector processor over 'Memory-to-Memory'?", ["It doesn't need power", "It minimizes main memory access bottlenecking and provides ultra-low latency execution by using a dedicated bank of high-speed vector registers", "It works with Wi-Fi", "It is physically smaller"], "It minimizes main memory access bottlenecking and provides ultra-low latency execution by using a dedicated bank of high-speed vector registers", "Once the data is loaded into the registers, the ALUs can manipulate it at maximum clock speed without waiting for RAM."),
Q("CAT 2", "HARD", "What defines the interconnect topology in a highly scalable NUMA system?", ["A single shared bus", "Point-to-point interconnect networks (like AMD Infinity Fabric or Intel UPI) rather than a centralized bus", "Wi-Fi connections", "Bluetooth"], "Point-to-point interconnect networks (like AMD Infinity Fabric or Intel UPI) rather than a centralized bus", "Instead of a single highway, point-to-point acts like a mesh of direct roads between every node, preventing traffic jams."),
Q("CAT 2", "EASY", "What does 'SIMD' eliminate compared to 'SISD' when processing an array?", ["The need for RAM", "Instruction decode overhead, as one instruction covers the entire array instead of decoding a new instruction for every single loop iteration", "The need for power", "The need for a monitor"], "Instruction decode overhead, as one instruction covers the entire array instead of decoding a new instruction for every single loop iteration", "If you loop 1000 times in SISD, you decode 1000 instructions. In SIMD, you decode 1 instruction and apply it 1000 times."),

// ╔══════════════════════════════════╗
// ║            UE (8 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "In NUMA architecture, what is a 'Node'?", ["A single text file", "A discrete cluster containing a processor, its dedicated memory controller, and its local attached physical memory", "A type of virus", "A graphics card"], "A discrete cluster containing a processor, its dedicated memory controller, and its local attached physical memory", "A dual-socket server motherboard generally has two NUMA nodes."),
Q("UE", "MEDIUM", "What is a 'Stride' in vector memory access?", ["Walking across the room", "A constant interval greater than 1 used to fetch non-contiguous linear data (e.g., every 8th byte) seamlessly into a vector register", "A type of hard drive", "An error code"], "A constant interval greater than 1 used to fetch non-contiguous linear data (e.g., every 8th byte) seamlessly into a vector register", "This is how hardware accelerates matrix mathematics, pulling entire columns out of row-major data layouts instantly."),
Q("UE", "HARD", "How does NC-NUMA shift the optimization burden?", ["By making the computer heavier", "Because hardware doesn't track cache consistency, software compilers or operating system kernels must manually manage cache validity to prevent processors from reading stale data", "By using more electricity", "By requiring a bigger monitor"], "Because hardware doesn't track cache consistency, software compilers or operating system kernels must manually manage cache validity to prevent processors from reading stale data", "This makes writing software for NC-NUMA clusters incredibly difficult, usually relegated to specialized scientific applications."),
Q("UE", "MEDIUM", "What problem does 'Strip Mining' solve?", ["Mining for Bitcoin", "The hardware limitation that physical vector registers have a fixed capacity, while software loops can be of any arbitrary length", "Deleting old files", "Overheating processors"], "The hardware limitation that physical vector registers have a fixed capacity, while software loops can be of any arbitrary length", "It acts as the bridge between infinite software variables and finite hardware transistors."),
Q("UE", "HARD", "What does the 'MESI' protocol do in a CC-NUMA system?", ["It connects to the internet", "It is a cache coherence protocol that categorizes cached data states (Modified, Exclusive, Shared, Invalid) to ensure hardware-level synchronization across remote nodes", "It encrypts hard drives", "It formats documents"], "It is a cache coherence protocol that categorizes cached data states (Modified, Exclusive, Shared, Invalid) to ensure hardware-level synchronization across remote nodes", "If Node A modifies a Shared variable, MESI instantly sends signals over the interconnect to mark Node B's copy as Invalid."),
Q("UE", "EASY", "Which component is heavily segmented in a vector architecture to maintain peak efficiency?", ["The power cable", "Vector Functional Units (Arithmetic pipelines like Adders and Multipliers)", "The hard drive", "The keyboard"], "Vector Functional Units (Arithmetic pipelines like Adders and Multipliers)", "They are deeply pipelined so they can accept a new pair of vector elements every single clock cycle."),
Q("UE", "MEDIUM", "What is a 'Scatter' operation?", ["Throwing data away", "Taking elements sequentially from a vector register and dispersing them out to erratic physical memory locations via an index address vector", "Deleting files randomly", "Connecting to multiple networks"], "Taking elements sequentially from a vector register and dispersing them out to erratic physical memory locations via an index address vector", "This is the exact inverse of a 'Gather' operation, writing sparse data back to RAM efficiently."),
Q("UE", "HARD", "Why is a 'Point-to-point interconnect' vital for highly scalable NUMA?", ["Because it uses Bluetooth", "It eliminates the severe bus contention of centralized networks, providing dedicated high-bandwidth pathways between specific processor nodes", "It makes the computer look better", "It is cheaper to manufacture"], "It eliminates the severe bus contention of centralized networks, providing dedicated high-bandwidth pathways between specific processor nodes", "This topology allows a 64-socket server to exist without the processors constantly waiting for each other to stop talking."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (8 Qns)       ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "What does 'Remote Memory' mean in a NUMA system?", ["Memory stored in the cloud", "Physical memory that is attached to a different processor node, accessed across the system interconnect fabric", "Memory on a USB drive", "Memory that was deleted"], "Physical memory that is attached to a different processor node, accessed across the system interconnect fabric", "Accessing remote memory takes much longer than accessing local memory on the same node."),
Q("POSSIBLE QNS", "MEDIUM", "What is 'Vector Mask Control' used for?", ["To hide the computer's IP address", "To execute conditional (IF-ELSE) statements within a parallel vector loop without incurring branching penalties", "To encrypt files", "To protect against viruses"], "To execute conditional (IF-ELSE) statements within a parallel vector loop without incurring branching penalties", "It selectively applies the results of parallel math based on a boolean array (the mask)."),
Q("POSSIBLE QNS", "HARD", "In 'Vector Chaining', what is the dependency being mitigated?", ["Power dependency", "Read-After-Write (RAW) data dependency; instead of stalling, the result of the first instruction flows directly into the second instruction's pipeline", "Internet dependency", "Software dependency"], "Read-After-Write (RAW) data dependency; instead of stalling, the result of the first instruction flows directly into the second instruction's pipeline", "This is the ultimate form of operand forwarding applied to massive arrays of data."),
Q("POSSIBLE QNS", "MEDIUM", "What is the key limitation of 'UMA' (Uniform Memory Access)?", ["It is too fast", "Low scalability; it is typically bounded to 4-8 sockets because the shared system bus becomes hopelessly congested", "It requires no RAM", "It only works with Windows"], "Low scalability; it is typically bounded to 4-8 sockets because the shared system bus becomes hopelessly congested", "As the number of cores grows, they spend all their time waiting in line to access the RAM."),
Q("POSSIBLE QNS", "HARD", "How does a compiler implement 'Strip Mining'?", ["By mining cryptocurrency", "By creating two nested loops: an outer loop that iterates in chunks of Max Vector Length (MVL), and an inner loop (executed in hardware) for the vector instructions", "By deleting old code", "By using a GPU"], "By creating two nested loops: an outer loop that iterates in chunks of Max Vector Length (MVL), and an inner loop (executed in hardware) for the vector instructions", "The compiler abstracts the physical hardware limitations away so the programmer can just write a normal loop of any length."),
Q("POSSIBLE QNS", "EASY", "What is a 'Vector Register File'?", ["A folder on the desktop", "A dedicated bank of high-speed registers designed to hold one-dimensional arrays of data for parallel processing", "A list of passwords", "A type of hard drive"], "A dedicated bank of high-speed registers designed to hold one-dimensional arrays of data for parallel processing", "This is the core storage area for Register-to-Register vector architectures like modern GPUs and AVX chips."),
Q("POSSIBLE QNS", "MEDIUM", "Why do Vector Processors still include 'Scalar Registers & Units'?", ["For decoration", "To handle necessary sequential program logic, like calculating branch conditions, managing loop counters, and computing base memory addresses", "To slow the processor down", "To connect to the internet"], "To handle necessary sequential program logic, like calculating branch conditions, managing loop counters, and computing base memory addresses", "Not every line of code can be parallelized. You still need standard scalar processing for the basic logic of an application."),
Q("POSSIBLE QNS", "HARD", "What does 'Deterministic access times' mean in relation to UMA?", ["The access time changes randomly", "No matter which processor requests data, or where that data is physically stored in RAM, the latency is always exactly the same", "The computer decides the time", "It relies on network speed"], "No matter which processor requests data, or where that data is physically stored in RAM, the latency is always exactly the same", "While this is mathematically predictable and easy for software to handle, it becomes a severe bottleneck at scale.")
];

async function insertUnit5Part1() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = ca_unit5_part1.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} questions for CA Unit 5 Part 1.`);
        } else {
            console.log("No new questions for CA Unit 5 Part 1 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit5Part1();
