const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a49ecb638bb37720e3e9194"; // COMPUTER ARCHITECTURE AND ASSEMBLY PROGRAMMING LANGUAGE

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const ca_unit3_part1 = [
// ╔══════════════════════════════════╗
// ║           QUIZ (8 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "Which type of memory access requires reading data incrementally from the beginning?", ["Random Access Memory", "Sequential Access Memory (SAM)", "Direct Memory Access", "Cache Memory"], "Sequential Access Memory (SAM)", "SAM, like a magnetic tape, requires the system to physically pass over all preceding data to reach the desired point."),
Q("QUIZ", "MEDIUM", "What is the primary difference between SRAM and DRAM?", ["SRAM is slower than DRAM", "SRAM uses bistable latching circuitry and doesn't need refreshing, whereas DRAM uses capacitors that leak charge and require periodic refreshing", "SRAM is non-volatile, DRAM is volatile", "SRAM is used for hard drives"], "SRAM uses bistable latching circuitry and doesn't need refreshing, whereas DRAM uses capacitors that leak charge and require periodic refreshing", "Because it doesn't need to pause for refresh cycles, SRAM is much faster, which is why it's used for CPU cache."),
Q("QUIZ", "HARD", "What does 'Associative Memory Page Table' (TLB) do in Virtual Memory?", ["It stores user passwords", "It acts as a hardware cache storing recently accessed virtual-to-physical address mappings to speed up address translation", "It connects the RAM to the Hard Drive", "It formats the cache memory"], "It acts as a hardware cache storing recently accessed virtual-to-physical address mappings to speed up address translation", "The Translation Lookaside Buffer (TLB) prevents the CPU from having to search the slow page table in RAM every time it accesses memory."),
Q("QUIZ", "MEDIUM", "What is 'Write-Through' cache?", ["Data is written only to the hard drive", "Data is simultaneously written to both the cache and the main memory to ensure data is always up-to-date", "Data is deleted after being read", "Data is written to the cache but never to RAM"], "Data is simultaneously written to both the cache and the main memory to ensure data is always up-to-date", "While safe and consistent, write-through is slower because every write operation must wait for the slow RAM to finish."),
Q("QUIZ", "EASY", "What does ROM stand for?", ["Read-Only Memory", "Random Output Memory", "Re-write Operational Memory", "Rapid Online Memory"], "Read-Only Memory", "ROM is non-volatile memory that retains its data even when the power is turned off, commonly used for the BIOS."),
Q("QUIZ", "HARD", "Which cache mapping technique allows any memory block to be placed in any cache line without restriction?", ["Direct Mapping", "Set-Associative Mapping", "Fully Associative Mapping", "Random Mapping"], "Fully Associative Mapping", "Fully associative mapping minimizes cache conflicts completely, but it requires highly complex and expensive hardware to search the entire cache simultaneously."),
Q("QUIZ", "MEDIUM", "What is the principle of 'Locality'?", ["The idea that a CPU must be physically close to the RAM", "The observation that programs tend to access a small portion of their address space frequently, and nearby memory locations are likely to be accessed together", "The idea that memory cannot be moved", "A rule for network routing"], "The observation that programs tend to access a small portion of their address space frequently, and nearby memory locations are likely to be accessed together", "Cache memory exists purely to exploit the principle of locality by holding onto recently used data and its neighbors."),
Q("QUIZ", "HARD", "In segmented-page mapping, how is memory organized?", ["Into a single flat file", "Memory is divided into logical segments (code, data, stack), and each segment is further divided into fixed-size pages", "It is divided randomly", "It uses only magnetic tape"], "Memory is divided into logical segments (code, data, stack), and each segment is further divided into fixed-size pages", "This hybrid approach provides the logical protection benefits of segmentation with the physical efficiency of paging."),

// ╔══════════════════════════════════╗
// ║         EXERCISE (8 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "Which is the fastest and most expensive storage location in a computer system?", ["Main Memory (RAM)", "Secondary Storage (HDD)", "Cache Memory", "CPU Registers"], "CPU Registers", "Registers are physically inside the CPU core, offering zero-latency access, but there are very few of them."),
Q("EXERCISE", "MEDIUM", "How is 'Virtual Memory' implemented?", ["By buying more RAM", "By treating a portion of secondary memory (like a hard drive) as an extension of main memory, giving the illusion of a massive RAM space", "By using flash drives", "By connecting to the cloud"], "By treating a portion of secondary memory (like a hard drive) as an extension of main memory, giving the illusion of a massive RAM space", "The OS uses a 'pagefile' or 'swap partition' on the disk to temporarily hold data that doesn't fit in the physical RAM."),
Q("EXERCISE", "HARD", "What does 'EEPROM' stand for, and what is its main advantage?", ["Electrically Erasable Programmable Read-Only Memory; it can be erased and reprogrammed electronically without needing UV light or removal from the circuit", "Energy Efficient Programmable Read-Only Memory; it uses no power", "External Erasable Programmable ROM; it is a type of hard drive", "Extra Erasable Programmable ROM; it has infinite storage"], "Electrically Erasable Programmable Read-Only Memory; it can be erased and reprogrammed electronically without needing UV light or removal from the circuit", "Flash memory (like USB drives and SSDs) is a modern, high-density type of EEPROM."),
Q("EXERCISE", "MEDIUM", "What is the function of the 'Address Bus' in memory connection?", ["To transfer the actual data", "To specify which exact memory address the CPU wants to read from or write to", "To power the RAM", "To handle interrupts"], "To specify which exact memory address the CPU wants to read from or write to", "The width of this bus (e.g., 32 wires) determines the maximum amount of RAM the CPU can address (e.g., 4GB)."),
Q("EXERCISE", "EASY", "What characterizes 'Volatile' memory?", ["It explodes if overheated", "It requires continuous power to maintain stored data; it loses its contents when power is turned off", "It cannot be erased", "It is very slow"], "It requires continuous power to maintain stored data; it loses its contents when power is turned off", "RAM and Cache are volatile. HDDs, SSDs, and ROM are non-volatile."),
Q("EXERCISE", "HARD", "What is a 'Page Fault'?", ["When the RAM physically breaks", "An instance where the CPU tries to access a virtual page that is not currently loaded in physical memory, requiring the OS to fetch it from the disk", "A spelling error in code", "When the cache is full"], "An instance where the CPU tries to access a virtual page that is not currently loaded in physical memory, requiring the OS to fetch it from the disk", "A page fault triggers a significant delay as the OS must read the hard drive, load the page into RAM, and update the page table."),
Q("EXERCISE", "MEDIUM", "In 'Direct Mapping' for cache, what is the primary disadvantage?", ["It is too slow to build", "It can lead to cache conflicts if multiple frequently accessed memory blocks map to the exact same single cache location", "It uses too much electricity", "It requires too many wires"], "It can lead to cache conflicts if multiple frequently accessed memory blocks map to the exact same single cache location", "Because each RAM block has only one rigid spot it can go in the cache, two blocks fighting for the same spot will constantly overwrite each other (thrashing)."),
Q("EXERCISE", "HARD", "What does 'Write-Back' caching mean?", ["Data is written to the hard drive immediately", "Data is written only to the cache initially, and the main memory is updated only when that cache line is later evicted or replaced", "Data cannot be written", "Data is written backwards"], "Data is written only to the cache initially, and the main memory is updated only when that cache line is later evicted or replaced", "This is much faster than write-through, but risks data loss if the system loses power before the 'dirty' cache line is written back to RAM."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "Which storage medium is an example of 'Sequential Access Memory'?", ["Solid State Drive (SSD)", "Magnetic Tape", "Random Access Memory (RAM)", "Cache"], "Magnetic Tape", "Magnetic tapes must be wound and rewound sequentially to find a specific piece of data, making them terrible for random access but great for bulk backup."),
Q("CAT 1", "MEDIUM", "What is the difference between a 'Logical Address' and a 'Physical Address'?", ["They are the same thing", "Logical addresses are generated by the CPU and seen by the program, while Physical addresses refer to the actual hardware location in RAM", "Logical addresses are for text, physical for numbers", "Logical addresses are on the hard drive"], "Logical addresses are generated by the CPU and seen by the program, while Physical addresses refer to the actual hardware location in RAM", "The MMU acts as the translator between the software's logical illusion and the hardware's physical reality."),
Q("CAT 1", "HARD", "How does 'Set-Associative Mapping' balance cache design?", ["It uses random guessing", "It divides the cache into sets containing multiple lines, reducing the conflict misses of direct mapping without the extreme hardware cost of fully associative mapping", "It only caches video files", "It maps memory to the hard drive"], "It divides the cache into sets containing multiple lines, reducing the conflict misses of direct mapping without the extreme hardware cost of fully associative mapping", "A 4-way set associative cache means any memory block can go into one of 4 spots within its assigned set, drastically reducing thrashing."),
Q("CAT 1", "EASY", "Which type of ROM can only be programmed once by the user using a special device?", ["Mask ROM", "EEPROM", "PROM (Programmable Read-Only Memory)", "Flash Memory"], "PROM (Programmable Read-Only Memory)", "Once the fuses inside a PROM are 'blown' by the programmer, the data is permanent and cannot be erased."),
Q("CAT 1", "MEDIUM", "What is the purpose of the 'Control Bus' in memory connection?", ["To transfer data", "To carry signals like read/write, memory enable, and bus control to coordinate activities between CPU and memory", "To supply 12V power", "To connect to the internet"], "To carry signals like read/write, memory enable, and bus control to coordinate activities between CPU and memory", "Without the control bus, the RAM wouldn't know if the CPU wanted to read the address on the address bus, or overwrite it."),
Q("CAT 1", "HARD", "What does 'Memory Protection' hardware achieve?", ["It physically locks the RAM chips in place", "It ensures processes cannot access memory regions they are not authorized to use, preventing crashes and enhancing security", "It prevents RAM from overheating", "It encrypts all data automatically"], "It ensures processes cannot access memory regions they are not authorized to use, preventing crashes and enhancing security", "If a program tries to read another program's RAM (or the OS kernel's RAM), the MMU throws a hardware exception (like a Segmentation Fault) and kills the offending program."),
Q("CAT 1", "MEDIUM", "What distinguishes 'Tertiary Storage' from Secondary Storage?", ["It is faster", "It refers to offline, extremely large-capacity, but very slow storage solutions like robotic magnetic tape libraries", "It is built into the CPU", "It is volatile"], "It refers to offline, extremely large-capacity, but very slow storage solutions like robotic magnetic tape libraries", "Tertiary storage is used for deep archiving where data isn't needed immediately but must be kept cheaply for years."),
Q("CAT 1", "HARD", "In the memory hierarchy, what is the trade-off as you move further away from the CPU?", ["Speed increases, capacity decreases, cost increases", "Speed decreases, capacity increases, cost per byte decreases", "Everything stays the same", "It becomes more volatile"], "Speed decreases, capacity increases, cost per byte decreases", "Registers (fast, tiny, expensive) -> Cache -> RAM -> SSD -> HDD -> Tape (slow, massive, cheap)."),
Q("CAT 1", "EASY", "What is the primary role of a 'Hard Disk Drive' (HDD)?", ["To process graphics", "To act as secondary, non-volatile storage using rotating magnetic platters for long-term data retention", "To cool the system", "To act as the main memory"], "To act as secondary, non-volatile storage using rotating magnetic platters for long-term data retention", "Unlike RAM, HDDs keep your files safe when the power cord is unplugged."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (9 Qns)           ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "What does 'SRAM' stand for?", ["Static Random Access Memory", "Synchronous Read Audio Memory", "System RAM", "Sequential RAM"], "Static Random Access Memory", "Static RAM is fast, expensive, and used mostly for L1/L2/L3 CPU caches."),
Q("CAT 2", "MEDIUM", "What does a 'Page Replacement Technique' like LRU do?", ["Replaces the CPU", "When physical RAM is full, it decides which page to evict to the disk. LRU evicts the 'Least Recently Used' page", "Replaces a broken RAM stick", "Replaces text on a screen"], "When physical RAM is full, it decides which page to evict to the disk. LRU evicts the 'Least Recently Used' page", "LRU assumes that if a page hasn't been used in a long time, it probably won't be needed soon, making it a good candidate to swap out."),
Q("CAT 2", "HARD", "How does an 'EPROM' chip get erased?", ["By pressing a delete button", "By removing it from the circuit and exposing it to strong ultraviolet (UV) light through a quartz window on the chip", "By running a software command", "By heating it up"], "By removing it from the circuit and exposing it to strong ultraviolet (UV) light through a quartz window on the chip", "The UV light provides enough energy for the trapped electrons in the memory cells to escape, wiping the chip blank."),
Q("CAT 2", "EASY", "What is 'Flash Memory'?", ["A type of fast RAM", "A type of EEPROM that allows multiple memory locations to be erased or written simultaneously, commonly used in USB drives and SSDs", "A memory that only lasts a second", "A type of magnetic tape"], "A type of EEPROM that allows multiple memory locations to be erased or written simultaneously, commonly used in USB drives and SSDs", "Flash memory revolutionized storage by providing non-volatile, shock-resistant, fast storage with no moving parts."),
Q("CAT 2", "MEDIUM", "Why is 'Cache Memory' divided into levels (L1, L2, L3)?", ["To look complicated", "To balance speed and size; L1 is the smallest and fastest, while L3 is larger and slightly slower to catch misses from L1 and L2", "Because of different brands", "To separate audio and video"], "To balance speed and size; L1 is the smallest and fastest, while L3 is larger and slightly slower to catch misses from L1 and L2", "This multi-level hierarchy ensures the CPU is fed data as fast as physically possible without making the chip too expensive."),
Q("CAT 2", "HARD", "In Virtual Memory, what does the 'Memory Table' (Page Table) contain?", ["Usernames and passwords", "Mappings between the virtual pages generated by the software and the actual physical page frames in RAM", "A list of installed hardware", "The operating system code"], "Mappings between the virtual pages generated by the software and the actual physical page frames in RAM", "The OS maintains this table. Every memory access by a program must be translated through this table by the MMU."),
Q("CAT 2", "MEDIUM", "What is an advantage of 'Solid State Drives' (SSDs) over 'Hard Disk Drives' (HDDs)?", ["They have more moving parts", "They use flash memory with no moving parts, resulting in much faster read/write speeds and better durability against physical shock", "They are much cheaper per gigabyte", "They use magnetic tape"], "They use flash memory with no moving parts, resulting in much faster read/write speeds and better durability against physical shock", "Dropping a running HDD will likely destroy it due to the mechanical read/write head crashing into the platter. An SSD has no such issue."),
Q("CAT 2", "HARD", "What is 'Mask ROM'?", ["A ROM chip used during Halloween", "The original type of ROM where data is permanently encoded during the actual physical manufacturing process using metal masks", "A ROM that can be rewritten", "A ROM used for graphics"], "The original type of ROM where data is permanently encoded during the actual physical manufacturing process using metal masks", "It is the cheapest ROM to mass-produce, but if there is a bug in the code, millions of chips must be thrown away because they cannot be updated."),
Q("CAT 2", "EASY", "Which memory type uses a laser to read microscopic pits on a reflective surface?", ["Flash Drive", "Magnetic Tape", "Optical Discs (CD, DVD, Blu-ray)", "SSD"], "Optical Discs (CD, DVD, Blu-ray)", "The transition between pits and lands on the disc's surface reflects the laser differently, translating to binary 1s and 0s."),

// ╔══════════════════════════════════╗
// ║            UE (8 Qns)            ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "What does 'DRAM' stand for?", ["Dynamic Random Access Memory", "Digital Read Access Memory", "Direct RAM", "Dual Random Active Memory"], "Dynamic Random Access Memory", "It is 'Dynamic' because it constantly loses its charge and must be dynamically refreshed thousands of times a second."),
Q("UE", "MEDIUM", "What is the consequence of a 'Cache Miss'?", ["The computer turns off", "The CPU must fetch the required data from the much slower main memory (RAM), stalling the execution pipeline", "The hard drive is formatted", "The file is deleted"], "The CPU must fetch the required data from the much slower main memory (RAM), stalling the execution pipeline", "Cache misses are the enemy of performance. Compilers and programmers work hard to organize data so it stays in the cache."),
Q("UE", "HARD", "What is the primary difference between 'Paging' and 'Segmentation' in memory mapping?", ["Paging uses Wi-Fi", "Paging divides memory into fixed-size blocks, while segmentation divides memory into variable-sized logical blocks (like 'code' or 'stack')", "Segmentation only works on ROM", "They are exactly the same"], "Paging divides memory into fixed-size blocks, while segmentation divides memory into variable-sized logical blocks (like 'code' or 'stack')", "Modern systems often use Segmented-Page mapping, getting the logical benefits of segmentation with the physical simplicity of fixed-size pages."),
Q("UE", "MEDIUM", "What does 'Non-Volatile' mean?", ["The memory is explosive", "The memory retains its stored data even when the electrical power is completely turned off", "The memory changes its data randomly", "The memory cannot be read"], "The memory retains its stored data even when the electrical power is completely turned off", "ROM, Flash memory, and magnetic disks are non-volatile, making them essential for long-term storage and booting the computer."),
Q("UE", "HARD", "How does 'FIFO' work as a Page Replacement Technique?", ["It evicts the most recently used page", "It evicts the 'First-In-First-Out' page, meaning the oldest page that was brought into RAM is the one kicked out to the disk", "It evicts random pages", "It never evicts pages"], "It evicts the 'First-In-First-Out' page, meaning the oldest page that was brought into RAM is the one kicked out to the disk", "FIFO is simple to implement but often inefficient, because the oldest page might still be heavily used by the program."),
Q("UE", "EASY", "Which memory component is physically located within the CPU core?", ["RAM", "Registers", "Hard Drive", "Optical Drive"], "Registers", "Registers are the tiny scratchpads built directly into the silicon of the CPU execution units."),
Q("UE", "MEDIUM", "What is the main function of the 'Data Bus' in relation to memory?", ["To specify the address", "To carry the actual binary payload (the data itself) being read from or written to the memory", "To supply power", "To send an interrupt"], "To carry the actual binary payload (the data itself) being read from or written to the memory", "If you want to save the number '5' to RAM, the address goes on the Address Bus, and the binary for '5' travels over the Data Bus."),
Q("UE", "HARD", "What does 'Cache Initialization' typically involve?", ["Formatting the hard drive", "Clearing the cache memory and potentially preloading it with default values or commonly used instructions during system boot-up", "Deleting the OS", "Connecting to the internet"], "Clearing the cache memory and potentially preloading it with default values or commonly used instructions during system boot-up", "When a computer boots, the cache contains random garbage. Initialization flushes it so it's ready to accurately store real data."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (8 Qns)       ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "What is the purpose of 'Secondary Storage'?", ["To replace the CPU", "To provide large-capacity, non-volatile, long-term storage for programs and data not currently in active use", "To speed up the clock", "To act as a cooling mechanism"], "To provide large-capacity, non-volatile, long-term storage for programs and data not currently in active use", "Because RAM is wiped when power is lost, you need a Hard Drive or SSD to actually keep your files."),
Q("POSSIBLE QNS", "MEDIUM", "What is 'DDR SDRAM'?", ["A type of hard drive", "Double Data Rate Synchronous Dynamic RAM, a fast type of main memory that transfers data on both the rising and falling edges of the clock signal", "A DVD format", "A type of cache"], "Double Data Rate Synchronous Dynamic RAM, a fast type of main memory that transfers data on both the rising and falling edges of the clock signal", "By transferring twice per clock tick, DDR effectively doubles the bandwidth of standard SDRAM."),
Q("POSSIBLE QNS", "HARD", "What does a 'Page Table' map exactly?", ["Usernames to Passwords", "Virtual page numbers to Physical page frames", "IP addresses to MAC addresses", "Files to Folders"], "Virtual page numbers to Physical page frames", "The CPU asks for Virtual Page 5. The MMU looks in the Page Table, sees that Virtual Page 5 is actually sitting in Physical Frame 12 in RAM, and translates the address."),
Q("POSSIBLE QNS", "MEDIUM", "Why is SRAM primarily used for Cache memory instead of Main memory?", ["Because it is very slow", "Because it is incredibly fast but physically larger and much more expensive per megabyte than DRAM", "Because it is non-volatile", "Because it uses magnetic tape"], "Because it is incredibly fast but physically larger and much more expensive per megabyte than DRAM", "If a computer used SRAM for its 16GB of main memory, it would cost tens of thousands of dollars and be physically massive."),
Q("POSSIBLE QNS", "HARD", "What is the 'TLB' (Translation Lookaside Buffer)?", ["A buffer for video streaming", "A specialized hardware cache inside the MMU that stores recent virtual-to-physical address translations to drastically speed up virtual memory", "A type of USB drive", "A firewall component"], "A specialized hardware cache inside the MMU that stores recent virtual-to-physical address translations to drastically speed up virtual memory", "Without a TLB, every memory access would require two RAM accesses (one to read the page table, one to get the data). The TLB caches the page table."),
Q("POSSIBLE QNS", "EASY", "What is the structure of a 'Magnetic Disk' (HDD)?", ["Silicon chips only", "One or more rigid rotating platters coated with magnetic material, accessed by moving read/write heads", "Laser and plastic layers", "A long spool of tape"], "One or more rigid rotating platters coated with magnetic material, accessed by moving read/write heads", "The mechanical nature of spinning platters and moving actuator arms is why HDDs are slower than SSDs and prone to physical damage."),
Q("POSSIBLE QNS", "MEDIUM", "What does 'Random Access' mean in the context of RAM?", ["Data is retrieved by chance", "Any byte of memory can be accessed directly and almost instantly, regardless of its physical location, without reading preceding bytes", "Data changes randomly", "Only unauthorized users can access it"], "Any byte of memory can be accessed directly and almost instantly, regardless of its physical location, without reading preceding bytes", "This is the opposite of Sequential Access (like tape), where you have to fast-forward to get to your data."),
Q("POSSIBLE QNS", "HARD", "How does the OS handle 'Access Permissions' in Memory Protection?", ["By asking the user every time", "By using techniques like Access Control Lists (ACLs) within the page table to mark segments as read-only, read/write, or execute-only", "By encrypting the RAM", "By hiding the RAM chips"], "By using techniques like Access Control Lists (ACLs) within the page table to mark segments as read-only, read/write, or execute-only", "If a hacker tries to execute code they injected into a data segment, the MMU stops them because the page table marks that segment as 'No-Execute' (NX).")
];

async function insertUnit3Part1() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = ca_unit3_part1.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} questions for CA Unit 3 Part 1.`);
        } else {
            console.log("No new questions for CA Unit 3 Part 1 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit3Part1();
