const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a5d16dbf29e866583f45d27";

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const exp_part2 = [
Q("QUIZ", "EASY", "Which layer of the OSI model does an IP address operate on?", ["Layer 1", "Layer 2", "Layer 3", "Layer 4"], "Layer 3", "IP addresses are logical addresses managed at the Network Layer (Layer 3)."),
Q("EXERCISE", "MEDIUM", "What is the primary function of the 'ARP' protocol?", ["To route internet traffic", "To translate a logical IP address into a physical MAC address", "To encrypt user data", "To assign dynamic IPs"], "To translate a logical IP address into a physical MAC address", "The Address Resolution Protocol maps a known IP address to the corresponding MAC address on a local network."),
Q("CAT 1", "HARD", "How does a 'Distance-Vector' routing protocol work?", ["It sends full network maps to all routers", "It determines the best path by calculating the direction (vector) and the distance (hop count) to a destination", "It physically traces the cables", "It uses GPS coordinates"], "It determines the best path by calculating the direction (vector) and the distance (hop count) to a destination", "Protocols like RIP use distance-vector algorithms, counting how many router hops it takes to reach a subnet."),
Q("CAT 2", "EASY", "Which protocol is responsible for dynamically assigning IP addresses to devices?", ["DNS", "FTP", "DHCP", "SMTP"], "DHCP", "Dynamic Host Configuration Protocol automatically assigns IPs, reducing manual configuration errors."),
Q("UE", "MEDIUM", "In classful addressing, which class of IP addresses uses the first 8 bits for the Network ID and 24 bits for the Host ID?", ["Class A", "Class B", "Class C", "Class D"], "Class A", "Class A addresses allow for millions of hosts per network, using only the first octet for the network ID."),
Q("POSSIBLE QNS", "HARD", "What does 'APIPA' do when a computer boots up but cannot reach a DHCP server?", ["It shuts down the network card", "It automatically self-assigns an IP address in the 169.254.x.x range to allow local communication", "It uses the MAC address as an IP", "It forces the computer to restart"], "It automatically self-assigns an IP address in the 169.254.x.x range to allow local communication", "APIPA ensures that even if DHCP fails, local devices can still ping and talk to each other on the same subnet."),
Q("QUIZ", "MEDIUM", "What is the primary difference between IPv4 and IPv6 address formats?", ["IPv4 uses letters, IPv6 uses numbers", "IPv4 is 32-bit dotted-decimal; IPv6 is 128-bit colon-hexadecimal", "IPv4 uses MACs, IPv6 uses IPs", "IPv6 is strictly for wireless networks"], "IPv4 is 32-bit dotted-decimal; IPv6 is 128-bit colon-hexadecimal", "IPv6 was introduced to solve the address exhaustion problem of IPv4, vastly expanding the address space."),
Q("EXERCISE", "HARD", "Why does a router use 'NAT' (Network Address Translation)?", ["To translate English to French", "To map multiple private IP addresses inside a LAN to a single public IP address on the internet", "To block all incoming emails", "To assign MAC addresses"], "To map multiple private IP addresses inside a LAN to a single public IP address on the internet", "NAT hides internal network structures and conserves the limited supply of public IPv4 addresses."),
Q("CAT 1", "EASY", "Which OSI layer is responsible for error control on a 'Hop-by-Hop' (single link) basis?", ["Data Link Layer", "Transport Layer", "Session Layer", "Application Layer"], "Data Link Layer", "The Data Link layer uses CRC to check for errors across a single physical wire connection."),
Q("CAT 2", "MEDIUM", "What is the purpose of 'Flow Control' at the Transport Layer?", ["To speed up the internet", "To ensure the sender does not transmit data faster than the receiving application can process it (End-to-End)", "To allocate MAC addresses", "To stop physical collisions"], "To ensure the sender does not transmit data faster than the receiving application can process it (End-to-End)", "TCP uses windowing for end-to-end flow control, preventing buffer overflows at the destination."),
Q("UE", "HARD", "What does it mean if an application uses a 'Connectionless Service' like UDP?", ["It must connect via Wi-Fi only", "It treats each segment independently and does not guarantee reliable or ordered delivery", "It requires a physical wire", "It establishes a strict handshake first"], "It treats each segment independently and does not guarantee reliable or ordered delivery", "UDP is connectionless, meaning it just fires data packets at the destination without checking if they arrived safely."),
Q("POSSIBLE QNS", "MEDIUM", "What defines an Ethernet 'Broadcast Domain'?", ["The range of Wi-Fi", "The entire network segment that receives a broadcast frame (usually separated by a Router)", "A single port on a switch", "The distance a cable can run"], "The entire network segment that receives a broadcast frame (usually separated by a Router)", "While a switch breaks up collision domains, it takes a Layer 3 Router to block broadcasts and separate broadcast domains."),
Q("QUIZ", "HARD", "What is the role of the 'Logical Link Control' (LLC) sub-layer?", ["It acts as the physical wire", "It sits above the MAC layer, interfacing with the Network layer and handling flow control and protocol multiplexing", "It generates IP addresses", "It translates web pages"], "It sits above the MAC layer, interfacing with the Network layer and handling flow control and protocol multiplexing", "The LLC is the upper half of the Data Link layer, hiding the physical hardware differences from the Network layer."),
Q("EXERCISE", "EASY", "What is the default subnet mask for a Class C network?", ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"], "255.255.255.0", "Class C networks use 24 bits for the network and 8 bits for hosts."),
Q("CAT 1", "MEDIUM", "Which statement accurately describes 'TCP'?", ["It is a Layer 3 routing protocol", "It is a Layer 4 protocol that establishes a reliable, connection-oriented session between hosts", "It is an unreliable broadcast protocol", "It is used to physically wire switches"], "It is a Layer 4 protocol that establishes a reliable, connection-oriented session between hosts", "TCP ensures all data arrives intact and in order via acknowledgments and sequence numbers."),
Q("CAT 2", "HARD", "Why might a network administrator configure a 'DHCP Reservation'?", ["To block a user", "To ensure a specific device, like a network printer, always receives the exact same IP address from the DHCP server", "To increase the internet speed of that device", "To hide the device's MAC address"], "To ensure a specific device, like a network printer, always receives the exact same IP address from the DHCP server", "Reservations bind an IP to a MAC address so devices that need static IPs can still be managed centrally by DHCP."),
Q("UE", "EASY", "Which layer is known as the 'Syntax Layer'?", ["Network", "Session", "Presentation", "Application"], "Presentation", "The Presentation Layer handles data formatting, syntax, encryption, and compression."),
Q("POSSIBLE QNS", "MEDIUM", "What does a 'Subnet Mask' essentially do?", ["It hides the IP address from hackers", "It determines which portion of the IP address is the network ID and which portion is the host ID", "It blocks viruses", "It generates MAC addresses"], "It determines which portion of the IP address is the network ID and which portion is the host ID", "The 1s in the subnet mask represent the network portion, while the 0s represent the host portion."),
Q("QUIZ", "HARD", "What happens during 'Decapsulation' at a router?", ["The router encrypts the data", "The router strips off the Layer 2 Frame header/trailer to expose and read the Layer 3 IP Packet inside", "The router converts the IP to a MAC", "The router compresses the file"], "The router strips off the Layer 2 Frame header/trailer to expose and read the Layer 3 IP Packet inside", "To make a routing decision, the router must look inside the Data Link frame to see the IP packet destination."),
Q("EXERCISE", "EASY", "Which type of MAC address is assigned by the manufacturer and cannot normally be changed?", ["Dynamic MAC", "Burned-in Address (BIA)", "Public MAC", "IPv6 MAC"], "Burned-in Address (BIA)", "The MAC address is permanently burned into the Network Interface Card's ROM during manufacturing."),
Q("CAT 1", "MEDIUM", "What is the purpose of 'OUI' in a MAC address?", ["It identifies the specific computer model", "It uniquely identifies the hardware manufacturer (vendor) assigned by the IEEE", "It tracks the IP address", "It determines the network speed"], "It uniquely identifies the hardware manufacturer (vendor) assigned by the IEEE", "The first 24 bits (3 bytes) of a MAC address are the Organizationally Unique Identifier."),
Q("CAT 2", "HARD", "Which router component is essentially the 'CPU' of the router, running routing protocols?", ["Switching Fabric", "Input Buffer", "Routing Processor", "Output Port"], "Routing Processor", "The Routing Processor executes algorithms like OSPF or BGP to build and maintain the routing tables."),
Q("UE", "EASY", "What is 'Packetizing'?", ["Packing a router into a box", "The Network layer process of encapsulating upper-layer data into IP packets", "Zipping a file", "Sending data over Wi-Fi"], "The Network layer process of encapsulating upper-layer data into IP packets", "Packetizing involves taking transport layer segments and adding the IP header (source/destination IPs)."),
Q("POSSIBLE QNS", "MEDIUM", "If an IP address begins with 10.x.x.x, what do we know about it?", ["It is a public IP address", "It is a Class A private IP address, non-routable on the internet", "It is an IPv6 address", "It is a loopback address"], "It is a Class A private IP address, non-routable on the internet", "The 10.0.0.0/8 block is strictly reserved for private local area networks."),
Q("QUIZ", "HARD", "What is 'Segmentation' at the Transport Layer?", ["Cutting cables into segments", "Dividing a large message from the Application layer into smaller manageable units (segments) for transmission", "Dividing a LAN using switches", "Dividing an IP address"], "Dividing a large message from the Application layer into smaller manageable units (segments) for transmission", "Because networks have Maximum Transmission Units (MTU), the Transport layer must chop large data streams into smaller segments."),
Q("EXERCISE", "EASY", "Which OSI layer provides services like Email (SMTP) and Web Browsing (HTTP)?", ["Physical", "Network", "Session", "Application"], "Application", "Layer 7 provides network services directly to the user's software applications."),
Q("CAT 1", "MEDIUM", "What is a 'Gateway'?", ["A simple physical cable", "A network node that connects two networks using entirely different protocols or architectures", "A switch that only handles MAC addresses", "A type of fiber optic wire"], "A network node that connects two networks using entirely different protocols or architectures", "Gateways act as protocol converters, translating data formats so disparate networks can communicate."),
Q("CAT 2", "HARD", "How does a router process a packet whose destination IP is on a completely unknown network?", ["It sends it back to the sender", "It forwards the packet to its configured 'Default Gateway' (Default Route)", "It broadcasts it to all ports", "It changes the IP to a MAC address"], "It forwards the packet to its configured 'Default Gateway' (Default Route)", "If a router's routing table has no specific match for a destination, it uses the default route to pass it to a higher-level router (like the ISP)."),
Q("UE", "MEDIUM", "What does 'Service-Point Addressing' (Port Addressing) ensure?", ["That data goes to the correct computer", "That data is delivered to the specific correct software application (process) running on the destination computer", "That the router doesn't crash", "That MAC addresses don't collide"], "That data is delivered to the specific correct software application (process) running on the destination computer", "Because a PC runs many apps, port numbers (Layer 4) ensure web traffic goes to the browser and email traffic goes to the email client."),
Q("POSSIBLE QNS", "HARD", "Why are 'Session' and 'Presentation' layers often deemed less distinct in real-world networking?", ["They are illegal to use", "In the widely used TCP/IP model, their functions are simply bundled into the Application layer", "They require expensive licenses", "They only work on IBM computers"], "In the widely used TCP/IP model, their functions are simply bundled into the Application layer", "The strict 7-layer OSI model is theoretical. In the practical TCP/IP suite, Layers 5, 6, and 7 are combined into a single Application layer."),
Q("QUIZ", "EASY", "What is the term for a 48-bit hardware address burned into a network card?", ["IP Address", "Subnet Mask", "MAC Address", "Default Gateway"], "MAC Address", "The Media Access Control address is the unique physical identifier of a NIC."),
Q("EXERCISE", "MEDIUM", "What does a 'Switching Fabric' do inside a router?", ["It weaves fiber optic cables", "It connects the router's input ports to its output ports internally", "It translates IP addresses", "It acts as a physical firewall"], "It connects the router's input ports to its output ports internally", "The switching fabric is the high-speed internal network of the router that moves packets from the receiving port to the transmitting port."),
Q("CAT 1", "HARD", "Which type of internal router switching involves placing a token on a shared pathway?", ["Switching via memory", "Switching via bus", "Switching via interconnection network", "Switching via Wi-Fi"], "Switching via bus", "In bus switching, all ports share a single internal backplane, and packets use tokens so only the correct output port accepts them."),
Q("CAT 2", "EASY", "Which layer is responsible for creating 'Frames'?", ["Network Layer", "Physical Layer", "Data Link Layer", "Transport Layer"], "Data Link Layer", "The Data Link layer takes bits from the physical layer and organizes them into logical frames."),
Q("UE", "MEDIUM", "Which feature allows an administrator to combine multiple physical switches to act as one logical switch?", ["Virtualization", "Stacking (Stackable Switches)", "MAC Cloning", "Routing"], "Stacking (Stackable Switches)", "Stackable switches use a special backplane cable to unify management and increase port density seamlessly."),
Q("POSSIBLE QNS", "HARD", "If an IPv6 address has '::' in it, what does that represent?", ["A broadcast indicator", "A compressed block of consecutive zeroes", "A private network indicator", "An error in the address"], "A compressed block of consecutive zeroes", "To make IPv6 addresses shorter to write, consecutive blocks of '0000' can be replaced once with a double colon '::'."),
Q("QUIZ", "MEDIUM", "What is 'MAC Filtering'?", ["Washing the network cables", "A security measure where a router allows or denies network access based on the device's hardware MAC address", "Compressing MAC addresses", "Translating IPs to MACs"], "A security measure where a router allows or denies network access based on the device's hardware MAC address", "MAC filtering uses a whitelist or blacklist of physical addresses to control who can join a Wi-Fi or wired network."),
Q("EXERCISE", "HARD", "What differentiates a 'Core Router' from an 'Edge Router'?", ["Core routers connect to the internet, Edge routers do not", "Core routers operate at the internet backbone carrying heavy data between internal networks, while Edge routers connect a local network to an external ISP", "Core routers are wireless, Edge routers are wired", "There is no difference"], "Core routers operate at the internet backbone carrying heavy data between internal networks, while Edge routers connect a local network to an external ISP", "Core routers are designed for ultra-high-speed internal routing, while Edge routers manage security and NAT at the network perimeter."),
Q("CAT 1", "EASY", "What is the Loopback Address for IPv4?", ["192.168.1.1", "10.0.0.1", "127.0.0.1", "255.255.255.255"], "127.0.0.1", "127.0.0.1 always points back to the local machine, used for testing the internal TCP/IP stack."),
Q("CAT 2", "MEDIUM", "What is 'DDoS'?", ["A type of routing protocol", "An attack that floods network infrastructure with overwhelming traffic to cause an outage", "A MAC address cloning software", "A fiber optic connector type"], "An attack that floods network infrastructure with overwhelming traffic to cause an outage", "Distributed Denial of Service uses botnets to crash servers and routers by overwhelming their processing capacity."),
Q("UE", "HARD", "In the Data Link layer, what is the purpose of the 'Trailer'?", ["To store the source IP address", "To hold the CRC (Cyclic Redundancy Check) value for error detection", "To declare the packet's priority", "To physically terminate the cable"], "To hold the CRC (Cyclic Redundancy Check) value for error detection", "The frame trailer contains a mathematical checksum. The receiver calculates the checksum and compares it to detect corrupted data."),
Q("POSSIBLE QNS", "EASY", "What does 'Full-Duplex' mean?", ["Data can only be sent, not received", "Data can only travel in one direction at a time", "Data can be sent and received simultaneously without collisions", "Data is broadcasted to all devices"], "Data can be sent and received simultaneously without collisions", "Full-duplex allows two-way simultaneous communication, effectively doubling the bandwidth of the link."),
Q("QUIZ", "MEDIUM", "Which of the following is true about a 'Managed Switch'?", ["It cannot be configured at all", "It supports protocols like SNMP, allowing granular control over VLANs, security, and performance", "It is extremely cheap and meant for homes", "It only supports wireless connections"], "It supports protocols like SNMP, allowing granular control over VLANs, security, and performance", "Managed switches are enterprise-grade devices that require an administrator to configure their advanced features."),
Q("EXERCISE", "HARD", "What is the primary function of the 'Session Layer'?", ["To route packets", "To establish, maintain, and terminate interactions between communicating devices, including adding synchronization checkpoints", "To encrypt data", "To assign MAC addresses"], "To establish, maintain, and terminate interactions between communicating devices, including adding synchronization checkpoints", "Layer 5 manages the 'dialog' and ensures that if a connection drops, it can resume from a checkpoint rather than restarting completely."),
Q("CAT 1", "EASY", "Which type of switch combines data and power transmission over a single Ethernet cable?", ["Routing Switch", "Virtual Switch", "PoE (Power over Ethernet) Switch", "Unmanaged Switch"], "PoE (Power over Ethernet) Switch", "PoE switches eliminate the need for separate electrical plugs for network devices like IP cameras and VoIP phones."),
Q("CAT 2", "MEDIUM", "Why might a network administrator implement QoS (Quality of Service) on a router?", ["To block all internet access", "To prioritize critical network traffic (like Voice over IP) over less important traffic (like file downloads)", "To change MAC addresses randomly", "To encrypt emails"], "To prioritize critical network traffic (like Voice over IP) over less important traffic (like file downloads)", "QoS ensures that time-sensitive data gets the bandwidth it needs to function smoothly during network congestion."),
Q("UE", "HARD", "What is the difference between 'Flow Control' and 'Error Control' at the Data Link layer?", ["They are exactly the same", "Flow control ensures the sender doesn't overwhelm the receiver with too much data; Error control detects corrupted frames and requests retransmission", "Flow control checks for viruses, Error control blocks them", "Flow control uses IPs, Error control uses MACs"], "Flow control ensures the sender doesn't overwhelm the receiver with too much data; Error control detects corrupted frames and requests retransmission", "Flow control manages speed/pacing, while error control manages data integrity."),
Q("POSSIBLE QNS", "EASY", "Which component of an IP address represents the specific device on a network?", ["Network ID", "Subnet Mask", "Host ID", "OUI"], "Host ID", "The Host ID uniquely identifies a specific computer or device within the given Network ID."),
Q("QUIZ", "HARD", "What is 'MAC Address Collision' and why is it problematic?", ["When two packets hit each other on the wire", "A rare scenario where two devices have identical MAC addresses, causing severe switching confusion and network drops", "When a router blocks a MAC address", "When MAC addresses change too fast"], "A rare scenario where two devices have identical MAC addresses, causing severe switching confusion and network drops", "If a switch sees the same MAC address on two different ports, it constantly updates its table, leading to dropped frames and severe network instability."),
Q("EXERCISE", "MEDIUM", "Which routing protocol requests neighboring routers for a route if it cannot find a path in its own table?", ["RIP", "EIGRP (Enhanced Interior Gateway Routing Protocol)", "BGP", "SMTP"], "EIGRP (Enhanced Interior Gateway Routing Protocol)", "EIGRP dynamically queries neighbor routers to calculate the best backup paths when a primary link fails.")
];

async function run() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = exp_part2.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} EXPANSION Part 2 questions.`);
        } else {
            console.log("No new EXPANSION Part 2 questions to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
run();
