const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a5d16dbf29e866583f45d27";

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const exp_part3 = [
Q("QUIZ", "EASY", "Which transmission medium uses light pulses to transmit data?", ["Coaxial Cable", "Twisted Pair", "Fiber Optic Cable", "Radio Waves"], "Fiber Optic Cable", "Fiber optics use a glass or plastic core to transmit data as pulses of light, making it extremely fast and immune to EMI."),
Q("EXERCISE", "MEDIUM", "What is the primary characteristic of a 'Full Mesh' topology?", ["It uses one central switch", "Every single device is connected directly to every other device on the network", "It uses a single circular cable", "It relies entirely on Wi-Fi"], "Every single device is connected directly to every other device on the network", "Full mesh provides the highest redundancy and reliability, but it is extremely expensive and complex to wire."),
Q("CAT 1", "HARD", "How does a router 'decapsulate' data at the Input Port?", ["By wrapping it in a new frame", "By stripping away the Data Link layer frame header and trailer to expose the Network layer IP packet inside", "By encrypting the payload", "By deleting the packet"], "By stripping away the Data Link layer frame header and trailer to expose the Network layer IP packet inside", "When a frame arrives, the router must remove the Layer 2 encapsulation to read the Layer 3 IP address needed for routing decisions."),
Q("CAT 2", "EASY", "Which term describes a router attack where traffic from many compromised devices is used to overwhelm the network infrastructure?", ["ARP Spoofing", "MAC Cloning", "DDoS (Distributed Denial-Of-Service) Attack", "Packet Sniffing"], "DDoS (Distributed Denial-Of-Service) Attack", "In a DDoS attack, a botnet floods the router with thousands of requests per second, exhausting its processing power and causing an outage."),
Q("UE", "MEDIUM", "What does an 'Edge Router' primarily connect to?", ["A virtual machine", "An Internet Service Provider (ISP)", "A printer", "A switch in the same room"], "An Internet Service Provider (ISP)", "Edge routers are located at the boundary of a local network, serving as the gateway to the internet via an ISP."),
Q("POSSIBLE QNS", "HARD", "How does 'Network overhead' cause bandwidth shortages in routers using dynamic routing?", ["The router's cooling fans consume bandwidth", "The constant exchanging of routing table updates between routers consumes a large portion of available bandwidth", "The router encrypts all data twice", "The router blocks UDP traffic"], "The constant exchanging of routing table updates between routers consumes a large portion of available bandwidth", "Dynamic routing algorithms require routers to talk to each other frequently to map the network, eating up bandwidth that could be used for user data."),
Q("QUIZ", "EASY", "Why is it recommended not to use a modem to connect directly to the internet without a router?", ["Because modems don't have cables", "Because using a modem directly exposes your computer to several security risks; a router acts as a secure intermediary", "Because modems are too fast", "Because modems only support IPv6"], "Because using a modem directly exposes your computer to several security risks; a router acts as a secure intermediary", "Routers provide NAT and hardware firewalls, making them an essential first step in securing a network connection."),
Q("EXERCISE", "MEDIUM", "What does 'EIGRP' do if it cannot find a path to a destination in its own routing tables?", ["It drops the packet immediately", "It broadcasts a request to its neighboring routers asking for a path", "It restarts the router", "It changes the MAC address"], "It broadcasts a request to its neighboring routers asking for a path", "Enhanced IGRP dynamically requests routes from neighbor routers, which propagate the request until a valid path is found."),
Q("CAT 1", "HARD", "What is 'MAC Address Collision'?", ["When two cables are plugged into the same port", "A rare event where two devices on a network have the same MAC address, causing network disruptions and identification issues", "When an IP address matches a MAC address", "When a router blocks a MAC address"], "A rare event where two devices on a network have the same MAC address, causing network disruptions and identification issues", "While MAC addresses should be globally unique, manufacturing errors or intentional spoofing can lead to two identical MACs on a LAN, causing severe switching errors."),
Q("CAT 2", "EASY", "What is a 'Multicast MAC address' used for?", ["To send a packet to every single device on the network", "To send a single packet to a specific group of devices at once", "To send a packet back to the sender", "To assign an IP address"], "To send a single packet to a specific group of devices at once", "Multicast MACs (where the LSB of the first octet is 1) allow efficient distribution of data to a group of interested devices without broadcasting to everyone."),
Q("UE", "MEDIUM", "Why is a router considered slower than a Layer 2 switch?", ["Routers have less RAM", "Routers must analyze multiple layers of information (up to Layer 3), which requires more processing time than simple MAC address lookups", "Routers only use wireless connections", "Routers must wait for the ISP to approve each packet"], "Routers must analyze multiple layers of information (up to Layer 3), which requires more processing time than simple MAC address lookups", "Decapsulating the frame, inspecting the IP header, routing, and re-encapsulating takes significant CPU cycles compared to a switch just reading a MAC address."),
Q("POSSIBLE QNS", "HARD", "In router architecture, what happens during 'Switching via Bus'?", ["The CPU manually copies every packet", "A packet is tagged with a token and placed on a shared internal bus; all output ports see it but only the targeted port accepts it", "Packets are sent over a 2N crossbar", "Packets are sent via fiber optic cables"], "A packet is tagged with a token and placed on a shared internal bus; all output ports see it but only the targeted port accepts it", "Bus switching shares a single internal pathway. The token ensures only the correct output port scrapes the packet off the bus."),
Q("QUIZ", "EASY", "What is one application of a router in the telecommunications industry?", ["To print invoices", "To connect hardware equipment like BSC, MGW, IN, and SGSN servers from remote location networks", "To scan for hardware viruses", "To create a MAC address"], "To connect hardware equipment like BSC, MGW, IN, and SGSN servers from remote location networks", "Routers are extensively used in telecom backbones to link remote switching centers securely over STM connections."),
Q("EXERCISE", "MEDIUM", "What is the primary characteristic of an 'Interior Gateway Routing Protocol' (IGRP)?", ["It connects two different ISPs", "It outlines the protocol for exchanging routing data between gateways inside the same separate network (Autonomous System)", "It handles MAC addresses only", "It converts IPv4 to IPv6"], "It outlines the protocol for exchanging routing data between gateways inside the same separate network (Autonomous System)", "IGRP is used to share routing information strictly within the boundaries of a single organization's network."),
Q("CAT 1", "HARD", "How does NAT (Network Address Translation) map multiple devices?", ["It maps multiple private IP addresses into one public IP address, allowing them all to share a single internet connection", "It assigns a unique public IP to every device", "It changes their MAC addresses to match the router's", "It compresses the payload to 50%"], "It maps multiple private IP addresses into one public IP address, allowing them all to share a single internet connection", "NAT changes the source IP of outgoing packets from a private IP to the router's public IP, keeping track of the translation in a table."),
Q("CAT 2", "EASY", "What is the function of 'Monitoring and diagnostics' on a router?", ["To monitor the physical temperature of the room", "To track network traffic, identify failures, and provide information to resolve network problems", "To monitor employee screen time", "To diagnose hard drive failures"], "To track network traffic, identify failures, and provide information to resolve network problems", "Advanced routers offer diagnostics and logging (like SNMP or Syslog) to help administrators troubleshoot network issues quickly."),
Q("UE", "MEDIUM", "What does it mean that MAC addresses are 'static' by nature?", ["They are randomly generated every time the computer boots", "They are assigned at the time of manufacture and cannot be easily changed without spoofing software", "They are assigned by the DHCP server", "They cannot be used on wireless networks"], "They are assigned at the time of manufacture and cannot be easily changed without spoofing software", "Unlike IP addresses which change as you move between networks, your device's MAC address remains physically the same everywhere you go."),
Q("POSSIBLE QNS", "HARD", "Which routing protocol is described as facilitating information sharing specifically between 'edge routers' to offer 'network stability'?", ["OSPF", "BGP (Border Gateway Protocol)", "IGRP", "RIP"], "BGP (Border Gateway Protocol)", "BGP is the protocol used between massive autonomous systems (like ISPs) to stabilize internet routing and switch paths if a link fails."),
Q("QUIZ", "EASY", "What determines the first 3 bytes (6 hex digits) of a MAC address?", ["The internet provider", "The OUI (Organizational Unique Identifier) assigned to the manufacturer", "The DHCP server", "The operating system"], "The OUI (Organizational Unique Identifier) assigned to the manufacturer", "The IEEE assigns OUIs to hardware manufacturers so that the first half of a MAC address identifies the brand of the NIC."),
Q("EXERCISE", "MEDIUM", "What is the difference between a 'Static' and 'Dynamic' routing table in a router?", ["Static tables are wireless, Dynamic are wired", "Dynamic tables update automatically based on network activity, while static tables must be configured manually by an admin", "Static tables hold MAC addresses, Dynamic hold IPs", "Static tables are used only by switches"], "Dynamic tables update automatically based on network activity, while static tables must be configured manually by an admin", "Dynamic routing (like OSPF) automatically learns new routes when topology changes. Static routing requires human intervention."),
Q("CAT 1", "HARD", "How does MAC filtering restrict network access?", ["By requiring a complex password", "By only allowing devices whose specific hardware MAC address is on an authorized list to connect", "By blocking all Class C IP addresses", "By turning off the router's broadcast signal"], "By only allowing devices whose specific hardware MAC address is on an authorized list to connect", "Administrators can configure the router to inspect incoming connection requests and reject any device whose MAC address is not pre-approved."),
Q("CAT 2", "EASY", "Which of the following is an advantage of the OSI model?", ["It guarantees zero latency", "It allows connectionless and connection-oriented services and is adaptable to many protocols", "It only works with physical hubs", "It merges all 7 layers into one"], "It allows connectionless and connection-oriented services and is adaptable to many protocols", "The OSI model's modularity makes it flexible, allowing different network technologies to interoperate."),
Q("UE", "MEDIUM", "Which sub-layer adds a header identifying the network layer protocol and provides flow control?", ["Media Access Control (MAC)", "Logical Link Control (LLC)", "Physical Control Layer", "Transport Control Layer"], "Logical Link Control (LLC)", "The LLC layer interfaces with Layer 3 (Network) and adds necessary control information, distinguishing it from the MAC sub-layer."),
Q("POSSIBLE QNS", "HARD", "If you need a network switch for a high-end enterprise environment that requires VLANs, SNMP, and advanced security, what type should you use?", ["Unmanaged Switch", "Smart Switch", "Managed Switch", "Virtual Switch"], "Managed Switch", "Fully Managed Switches offer comprehensive command-line and web interfaces to tweak every parameter of the network traffic."),
Q("QUIZ", "EASY", "What does it mean to operate in 'Half-Duplex' mode?", ["Data can flow in both directions simultaneously", "Data can flow in both directions, but only one direction at a time", "Data can only flow in one direction permanently", "Data flows randomly"], "Data can flow in both directions, but only one direction at a time", "Like a walkie-talkie, devices must take turns transmitting on a half-duplex connection."),
Q("EXERCISE", "MEDIUM", "What is the 'Default Gateway'?", ["The password to the Wi-Fi", "The IP address of the router interface that connects the local network to external networks (like the internet)", "The MAC address of the switch", "The physical door to the server room"], "The IP address of the router interface that connects the local network to external networks (like the internet)", "When a computer wants to send data to an IP outside its own subnet, it sends it to the default gateway."),
Q("CAT 1", "HARD", "How does a 'Stackable Switch' provide flexibility?", ["It acts as a wireless access point", "It allows multiple physical switches to be connected via a backplane and managed as a single logical switch", "It fits inside a virtual machine", "It routes analog phone calls"], "It allows multiple physical switches to be connected via a backplane and managed as a single logical switch", "Stacking increases port density without adding the management overhead of dealing with multiple standalone switches."),
Q("CAT 2", "EASY", "Which layer is known as the 'Syntax Layer'?", ["Network Layer", "Session Layer", "Presentation Layer", "Application Layer"], "Presentation Layer", "The Presentation Layer acts as a data translator, modifying the syntax and semantics for the receiving application."),
Q("UE", "MEDIUM", "Why is the Transport Layer considered 'End-to-End' while the Data Link Layer is 'Hop-to-Hop'?", ["Because Transport uses MACs", "Because Transport manages the connection from the original sender to the final destination, ignoring the intermediate physical links", "Because Data Link encrypts the data", "There is no difference"], "Because Transport manages the connection from the original sender to the final destination, ignoring the intermediate physical links", "TCP (Transport) ensures the entire message reaches the final IP, whereas Data Link just ensures the frame reaches the next physical router or switch."),
Q("POSSIBLE QNS", "HARD", "What does a 'Subnet Mask' of 255.255.255.0 indicate about an IP address?", ["It is a Class A network", "The first 24 bits represent the Network ID and the last 8 bits represent the Host ID", "It has zero host addresses", "It is a broadcast address"], "The first 24 bits represent the Network ID and the last 8 bits represent the Host ID", "A Class C subnet mask (255.255.255.0) leaves 8 bits for hosts, allowing up to 254 usable devices on that subnet."),
Q("QUIZ", "EASY", "What is the primary function of the Application Layer?", ["To compress files", "To serve as a window for users and application processes to access network services", "To route packets over the internet", "To transmit raw bits"], "To serve as a window for users and application processes to access network services", "The Application layer (Layer 7) provides direct services like Email, File Transfer, and Web browsing to the user's software."),
Q("EXERCISE", "MEDIUM", "What defines an Ethernet network as a 'Broadcast Network'?", ["It uses satellites", "Any system can send information and all systems receive the message, but they discard messages not addressed to them", "It only allows one computer to send data", "It uses token passing"], "Any system can send information and all systems receive the message, but they discard messages not addressed to them", "In an Ethernet broadcast network, frames are flooded. Only the NIC with the matching MAC address processes the frame; others discard it."),
Q("CAT 1", "HARD", "Which protocol is matched to the Session Layer?", ["TCP", "NetBIOS", "IPv4", "HTTP"], "NetBIOS", "NetBIOS and SAP are examples of protocols operating at the Session Layer."),
Q("CAT 2", "EASY", "Which IP block is considered a Class B Private Network?", ["10.0.0.0 to 10.255.255.255", "192.168.0.0 to 192.168.255.255", "172.16.0.0 to 172.31.255.255", "127.0.0.0 to 127.255.255.255"], "172.16.0.0 to 172.31.255.255", "The 172.16 to 172.31 block is reserved by IANA for Class B private networks."),
Q("UE", "MEDIUM", "How does a 'Connectionless Service' at the Transport layer operate?", ["It establishes a firm connection before sending data", "It treats each segment as an individual packet that can travel different routes to the destination", "It requires a physical cable", "It guarantees delivery"], "It treats each segment as an individual packet that can travel different routes to the destination", "Connectionless services (like UDP) send packets independently without setting up a path first. Packets may arrive out of order."),
Q("POSSIBLE QNS", "HARD", "What is 'Bit rate control' and which layer handles it?", ["Determining the sequence of packets; Network layer", "Encrypting bits; Presentation layer", "Defining the transmission rate (bits per second); Physical layer", "Controlling application access; Application layer"], "Defining the transmission rate (bits per second); Physical layer", "The Physical Layer defines how many bits are sent per second, ensuring synchronization between sender and receiver."),
Q("QUIZ", "EASY", "What does OSI stand for?", ["Open Source Internet", "Open System Interconnection", "Operating System Interface", "Optical Signal Interconnect"], "Open System Interconnection", "OSI is a standard reference model created by ISO to describe network communication."),
Q("EXERCISE", "MEDIUM", "Which type of IP address is required for a web server accessible to everyone on the internet?", ["Private IP", "APIPA IP", "Loopback IP", "Public IP"], "Public IP", "A Public IP is globally routable and unique, which is required for publicly accessible entities like web servers."),
Q("CAT 1", "HARD", "Which layer is responsible for defining physical topologies (like Star, Bus, Ring)?", ["Data Link Layer", "Physical Layer", "Network Layer", "Application Layer"], "Physical Layer", "The Physical Layer specifies how nodes are physically arranged in a network topology."),
Q("CAT 2", "EASY", "What happens to data at the Presentation layer?", ["It gets an IP address", "It is routed to another country", "It is translated, compressed, or encrypted", "It is broken into raw bits"], "It is translated, compressed, or encrypted", "The Presentation Layer (Layer 6) prepares the data structure (syntax), compresses it, and encrypts it for security."),
Q("UE", "MEDIUM", "What is the primary role of the MAC sub-layer in the Data Link Layer?", ["It handles IP routing", "It is a link between the Logical Link Control (LLC) layer and the physical layer for transferring packets", "It establishes the session", "It provides user interface"], "It is a link between the Logical Link Control (LLC) layer and the physical layer for transferring packets", "The Media Access Control (MAC) layer physically addresses frames and interfaces directly with the hardware media."),
Q("POSSIBLE QNS", "HARD", "Why is the Transport layer considered 'End-to-End'?", ["It connects physical cables together", "It ensures the complete message reaches the final destination without error, crossing multiple links", "It translates IP addresses", "It runs in the application"], "It ensures the complete message reaches the final destination without error, crossing multiple links", "Unlike Data Link which is hop-to-hop, Transport ensures the entire conversation between the source and destination is reliable."),
Q("QUIZ", "EASY", "Which of these protocols works at the Data Link Layer?", ["IP", "TCP", "PPP (Point-to-Point Protocol)", "HTTP"], "PPP (Point-to-Point Protocol)", "PPP, Frame Relay, and ATM are protocols that operate at the Data Link layer."),
Q("EXERCISE", "MEDIUM", "How does IPv6 solve the problem of address exhaustion experienced by IPv4?", ["By using a 64-bit address", "By reusing private IP addresses on the internet", "By using a 128-bit hexadecimal address, offering vastly more unique addresses", "By switching to MAC addresses"], "By using a 128-bit hexadecimal address, offering vastly more unique addresses", "IPv6 expands the address space from 32 bits (IPv4) to 128 bits, providing virtually unlimited IP addresses."),
Q("CAT 1", "HARD", "Why is UDP described as an 'unreliable' protocol?", ["Because it frequently crashes computers", "Because it is slow", "Because the receiver does not send acknowledgments and the sender does not wait for them", "Because it cannot send video files"], "Because the receiver does not send acknowledgments and the sender does not wait for them", "UDP is connectionless. It simply sends data without verifying if it was received, making it 'unreliable' but very fast (good for streaming)."),
Q("CAT 2", "EASY", "Which layer is Layer 3 in the OSI model?", ["Physical", "Data Link", "Network", "Transport"], "Network", "The Network Layer is Layer 3, handling IP addresses and routing."),
Q("UE", "MEDIUM", "Which IP version uses numbers separated by dots (e.g., 192.168.1.1)?", ["IPv6", "IPv4", "IPv5", "MAC v4"], "IPv4", "IPv4 uses the dotted-decimal notation consisting of four octets."),
Q("POSSIBLE QNS", "HARD", "A DHCP server can automatically assign which of the following?", ["A new graphics card", "An IP Address, Subnet Mask, Default Gateway, and DNS Server", "A physical MAC address", "An antivirus license"], "An IP Address, Subnet Mask, Default Gateway, and DNS Server", "DHCP automates network configuration by providing all necessary logical addressing details."),
Q("QUIZ", "EASY", "What is 'Packetizing'?", ["Compressing a file into a ZIP folder", "The process at the Network Layer where data from the upper layer is converted into packets", "Encrypting an email", "Transmitting a broadcast"], "The process at the Network Layer where data from the upper layer is converted into packets", "Packetizing is the process of encapsulating upper-layer segments into Network layer IP packets."),
Q("EXERCISE", "MEDIUM", "If an IP address is 10.5.5.5, what Class does it belong to?", ["Class A", "Class B", "Class C", "Class D"], "Class A", "The first octet '10' falls within the 0 to 126 range, which denotes a Class A address.")
];

async function run() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = exp_part3.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} EXPANSION Part 3 questions.`);
        } else {
            console.log("No new EXPANSION Part 3 questions to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
run();
