const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a5d16dbf29e866583f45d27";

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const questions_unit2_part1 = [
// ╔══════════════════════════════════╗
// ║          QUIZ (20 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "Which of the following is NOT a fundamental requirement to set up a LAN?", ["Workstations", "Network Devices like Switches", "Satellite Dish", "Ethernet Cables or Wi-Fi"], "Satellite Dish", "A typical LAN setup requires workstations, network devices (routers, switches), and a medium (wired or wireless), but not typically a satellite dish."),
Q("QUIZ", "EASY", "What does SSID stand for in a wireless LAN?", ["Secure System Identification", "Service Set Identifier", "Signal Strength Indicator Device", "Synchronized Server ID"], "Service Set Identifier", "SSID stands for Service Set Identifier, which is the broadcast name of a wireless network."),
Q("QUIZ", "EASY", "When designing a LAN, what does 'Network Topology' refer to?", ["The cost of the network", "The physical or logical arrangement of nodes", "The antivirus software used", "The brand of the router"], "The physical or logical arrangement of nodes", "Network topology refers to how the network's links and nodes are arranged (e.g., star, bus, ring)."),
Q("QUIZ", "EASY", "Which command is used on Windows to verify IP configuration?", ["ifconfig", "ipconfig", "netstat", "ping"], "ipconfig", "In Windows, 'ipconfig' is used to view the IP address, subnet mask, and default gateway."),
Q("QUIZ", "EASY", "If an IP address starts with 169.254.x.x, what does it usually indicate?", ["The device is successfully connected to the internet", "A DHCP server could not be reached", "The device is a server", "The device is using IPv6"], "A DHCP server could not be reached", "An IP address starting with 169.254.x.x is an APIPA address, meaning the device failed to obtain an IP from a DHCP server."),
Q("QUIZ", "EASY", "What is the primary function of the 'ping' command?", ["To encrypt network traffic", "To assign an IP address", "To test the reachability of a host on a network", "To download files"], "To test the reachability of a host on a network", "Ping sends ICMP echo requests to a target host and waits for an echo reply to test connectivity."),
Q("QUIZ", "EASY", "Which hardware tool is used to trace cables in walls or panels?", ["Multimeter", "Loopback Plug", "Tone Generator and Probe", "Cable Tester"], "Tone Generator and Probe", "A Tone Generator and Probe is used by technicians to trace network or telephone cables hidden in walls or bundles."),
Q("QUIZ", "EASY", "What is a Network Operating System (NOS)?", ["Software used for graphic design", "An OS built specifically to support networking functions and centralized management", "A protocol for sending emails", "A hardware switch"], "An OS built specifically to support networking functions and centralized management", "A NOS (like Windows Server or Linux) facilitates communication, resource sharing, and security management across multiple devices."),
Q("QUIZ", "EASY", "Which type of NOS allows sharing of resources with small-sized networks without a central server?", ["Client/Server", "Peer to Peer", "Mainframe", "Cloud OS"], "Peer to Peer", "In a Peer-to-Peer network operating system, nodes share resources equally without relying on a central server."),
Q("QUIZ", "EASY", "Which transmission medium uses pulses of light to send data?", ["Twisted Pair", "Coaxial Cable", "Fiber Optic", "Microwaves"], "Fiber Optic", "Fiber optic cables transmit data using pulses of light through a core made of glass or plastic."),
Q("QUIZ", "MEDIUM", "What is the primary difference between a Wired NIC and a Wireless NIC?", ["Wired NICs use antennas, Wireless NICs use cables", "Wired NICs connect via Ethernet cables, Wireless NICs use radio frequencies via antennas", "Wired NICs operate at Layer 3, Wireless NICs at Layer 2", "Wireless NICs are faster than Fiber Optics"], "Wired NICs connect via Ethernet cables, Wireless NICs use radio frequencies via antennas", "Wired NICs use physical cables (like Ethernet), while Wireless NICs use antennas to communicate via radio waves (Wi-Fi)."),
Q("QUIZ", "MEDIUM", "Which tool is a powerful free packet sniffer used to analyze network traffic?", ["Netstat", "Nslookup", "Wireshark", "Ipconfig"], "Wireshark", "Wireshark captures and analyzes network traffic, allowing administrators to inspect packets in detail for troubleshooting."),
Q("QUIZ", "MEDIUM", "What does 'Attenuation' mean in transmission media?", ["A change in the shape of the signal", "Unwanted signals added to the medium", "The loss of energy or signal strength over distance", "The conversion of analog to digital"], "The loss of energy or signal strength over distance", "Attenuation is the gradual loss of signal strength as it travels through a transmission medium."),
Q("QUIZ", "MEDIUM", "In a Fiber Optic cable, what is the function of the 'Cladding'?", ["It transmits the light", "It protects the cable from physical shock", "It provides a lower refractive index to cause reflection within the core", "It provides electrical power"], "It provides a lower refractive index to cause reflection within the core", "The cladding surrounds the core and reflects light back into it, preventing light from escaping the fiber."),
Q("QUIZ", "MEDIUM", "Which unguided transmission media requires sending and receiving antennas to be strictly aligned (line-of-sight)?", ["Radio Waves", "Microwaves", "Infrared", "Bluetooth"], "Microwaves", "Microwaves are unidirectional, meaning their signals are narrowly focused, so the sending and receiving antennas must be aligned."),
Q("QUIZ", "HARD", "Which of the following describes 'Baseband transmission' in coaxial cables?", ["Transmitting multiple signals simultaneously", "Transmitting a single signal at high speed", "Transmitting data via light pulses", "Transmitting data wirelessly"], "Transmitting a single signal at high speed", "Baseband transmission sends a single digital signal over the cable at high speeds, utilizing the entire bandwidth."),
Q("QUIZ", "HARD", "What is the purpose of a 'Loopback Plug'?", ["To test network ports (NIC or switch ports)", "To measure electrical voltage", "To trace cables in walls", "To detect miswired cables"], "To test network ports (NIC or switch ports)", "A loopback plug connects the transmit pins directly to the receive pins on a port to verify that the hardware is functioning correctly."),
Q("QUIZ", "HARD", "What causes 'Distortion' in transmission impairment?", ["Signals colliding with each other", "Different frequency components of a signal reaching the receiver at different times", "Loss of signal energy over distance", "Interference from external magnetic fields"], "Different frequency components of a signal reaching the receiver at different times", "Distortion occurs when different frequencies of a composite signal travel at different speeds, altering the signal's shape upon arrival."),
Q("QUIZ", "HARD", "In which Transmission Mode can data flow in both directions, but NOT at the same time?", ["Simplex Mode", "Half-Duplex Mode", "Full-Duplex Mode", "Multiplex Mode"], "Half-Duplex Mode", "In Half-Duplex mode, both devices can transmit and receive, but they must take turns (e.g., a Walkie-Talkie)."),
Q("QUIZ", "HARD", "Why do some computers use a 'Boot ROM socket' on their NIC?", ["To increase network speed", "To allow diskless workstations to connect to the network securely and boot an OS from the network", "To store IP addresses", "To provide wireless capabilities"], "To allow diskless workstations to connect to the network securely and boot an OS from the network", "The Boot ROM allows a computer without a local hard drive to boot up using an operating system located on a central network server."),

// ╔══════════════════════════════════╗
// ║        EXERCISE (20 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "What is the main advantage of a Local Area Network (LAN)?", ["It spans across countries", "It provides an easy and cheap way of communication within a small area", "It eliminates the need for cables", "It provides satellite internet"], "It provides an easy and cheap way of communication within a small area", "LANs are cost-effective, offer high transmission rates, and easily facilitate resource sharing in localized areas."),
Q("EXERCISE", "EASY", "Which of the following is a network design software mentioned for planning architecture?", ["Photoshop", "Cisco Packet Tracer", "Microsoft Word", "Notepad"], "Cisco Packet Tracer", "Cisco Packet Tracer is a popular network simulation tool used to sketch out and test network diagrams before physical deployment."),
Q("EXERCISE", "EASY", "If you ping 127.0.0.1, what are you testing?", ["The default gateway", "The internet connection", "Your own system's local TCP/IP stack", "A remote server"], "Your own system's local TCP/IP stack", "127.0.0.1 is the loopback address. Pinging it verifies that your computer's network interface and TCP/IP software are working."),
Q("EXERCISE", "EASY", "What does 'nslookup' do?", ["Checks network latency", "Resolves domain names to IP addresses and vice versa", "Captures data packets", "Tests cables physically"], "Resolves domain names to IP addresses and vice versa", "Nslookup is a command-line tool used to query the Domain Name System (DNS) to obtain domain name or IP address mapping."),
Q("EXERCISE", "EASY", "A keyboard and monitor are examples of which transmission mode?", ["Half-Duplex", "Full-Duplex", "Simplex", "Multiplex"], "Simplex", "A keyboard only sends data and a monitor only receives data. This unidirectional communication is called Simplex mode."),
Q("EXERCISE", "EASY", "Which transmission media is known as 'Bounded media'?", ["Guided Media", "Unguided Media", "Wireless Media", "Microwaves"], "Guided Media", "Guided media (like twisted pair, coaxial, and fiber) physically guide the signal through a physical channel, so they are called bounded media."),
Q("EXERCISE", "EASY", "Which cable type is most commonly used for TV wiring?", ["Twisted Pair", "Coaxial Cable", "Fiber Optic", "Infrared"], "Coaxial Cable", "Coaxial cables are commonly used for television wiring because of their good shielding and high bandwidth."),
Q("EXERCISE", "EASY", "What type of transmission is a standard telephone network?", ["Simplex", "Half-Duplex", "Full-Duplex", "None of the above"], "Full-Duplex", "A telephone network allows both parties to speak and listen simultaneously, which is the definition of Full-Duplex."),
Q("EXERCISE", "EASY", "Which NOS type is generally too expensive to implement for very small networks?", ["Peer to Peer", "Client/Server", "Standalone", "Offline"], "Client/Server", "Client/Server NOS requires dedicated central servers and administrative software, making it expensive to implement and maintain for small setups."),
Q("EXERCISE", "EASY", "Which is a characteristic of Infrared transmission?", ["It can penetrate thick walls", "It covers long distances", "It is used for short-range communication like TV remotes", "It is a guided media"], "It is used for short-range communication like TV remotes", "Infrared is a short-range, line-of-sight wireless technology that cannot penetrate walls, commonly used in remote controls."),
Q("EXERCISE", "MEDIUM", "What is the primary role of the 'Controller' in a Network Interface Card (NIC)?", ["It emits light pulses", "It acts like a mini CPU to process received data", "It plugs into the wall socket", "It replaces the router"], "It acts like a mini CPU to process received data", "The controller on a NIC processes network data packets, acting like a specialized mini CPU for network traffic."),
Q("EXERCISE", "MEDIUM", "How do Shielded Twisted Pair (STP) cables differ from Unshielded Twisted Pair (UTP)?", ["STP has no copper wire", "STP contains a mesh surrounding the wire for better protection against interference", "STP is wireless", "STP is much cheaper than UTP"], "STP contains a mesh surrounding the wire for better protection against interference", "The shielding in STP protects the data transmission from Electromagnetic Interference (EMI), allowing higher transmission rates than UTP."),
Q("EXERCISE", "MEDIUM", "What is a 'Multimeter' used for in network troubleshooting?", ["To ping a server", "To measure electrical signals in cables and devices", "To capture packets", "To trace the routing path"], "To measure electrical signals in cables and devices", "A multimeter is a hardware diagnostic tool that measures voltage, current, and resistance to ensure electrical signals in cables are correct."),
Q("EXERCISE", "MEDIUM", "Which tool lists the intermediate routers (hops) between your computer and a target address?", ["ping", "netstat", "ipconfig", "traceroute / tracert"], "traceroute / tracert", "Traceroute (or tracert on Windows) shows the exact path data takes, listing all the hops it passes through to reach the destination."),
Q("EXERCISE", "MEDIUM", "What is a primary disadvantage of a Local Area Network?", ["Low data transmission rate", "Administrators can access all user data, potentially violating privacy", "It cannot share resources", "It requires a satellite connection"], "Administrators can access all user data, potentially violating privacy", "Because data is centralized, network administrators have access to users' files, which can be a privacy concern."),
Q("EXERCISE", "HARD", "In setting up a LAN, when might an administrator choose a 'Crossover' Ethernet cable over a 'Straight-through' cable?", ["To connect a PC to a standard switch port", "To connect a switch directly to a router without auto-MDIX", "To connect a wireless access point", "To provide power over Ethernet"], "To connect a switch directly to a router without auto-MDIX", "Historically, crossover cables were required to connect similar devices directly (like Switch-to-Switch or Switch-to-Router) if they didn't support automatic crossover detection."),
Q("EXERCISE", "HARD", "In Coaxial cables, what is the specific purpose of the copper mesh (outer conductor)?", ["To transmit the primary data signal", "To act as a structural support", "To prevent Electromagnetic Interference (EMI)", "To provide physical flexibility"], "To prevent Electromagnetic Interference (EMI)", "The outer copper mesh acts as a shield to block external electromagnetic interference from corrupting the data traveling on the inner core."),
Q("EXERCISE", "HARD", "Which frequency range characterizes terrestrial microwaves?", ["3KHz to 1 MHz", "1 to 300 GHz (specifically 4-6 GHz to 21-23 GHz for terrestrial)", "300 GHz to 400 THz", "Visible light spectrum"], "1 to 300 GHz (specifically 4-6 GHz to 21-23 GHz for terrestrial)", "Microwaves fall in the 1 to 300 GHz range, making them suitable for high-bandwidth point-to-point communication."),
Q("EXERCISE", "HARD", "How does Full-Duplex mode achieve simultaneous two-way communication?", ["It uses a single simplex channel rapidly switching direction", "It operates at the speed of light", "It logically uses two simplex channels, one for each direction", "It compresses the data"], "It logically uses two simplex channels, one for each direction", "Full-Duplex mode has two separate channels (or frequency bands), allowing traffic to flow in both directions simultaneously without collision."),
Q("EXERCISE", "HARD", "Why are radio waves considered 'omnidirectional'?", ["They can only travel in a straight line", "They propagate in all directions from the source", "They bounce off the ionosphere", "They cannot penetrate walls"], "They propagate in all directions from the source", "Unlike microwaves which are highly directional, radio waves spread out in all directions, meaning the sender and receiver antennas do not need to be precisely aligned.")
];
module.exports = questions_unit2_part1;
