const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a5d16dbf29e866583f45d27";

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const unit5_questions = [
// ╔══════════════════════════════════╗
// ║          QUIZ (12 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "What is the primary function of a Network Switch?", ["To provide Wi-Fi to a house", "To segment networks into different subnets and filter/forward packets based on MAC address", "To translate IP addresses to domain names", "To block computer viruses"], "To segment networks into different subnets and filter/forward packets based on MAC address", "A switch connects devices within a LAN and uses MAC addresses to forward data exactly where it needs to go."),
Q("QUIZ", "EASY", "In which OSI layer does a standard Network Switch operate?", ["Physical Layer (Layer 1)", "Data Link Layer (Layer 2)", "Network Layer (Layer 3)", "Transport Layer (Layer 4)"], "Data Link Layer (Layer 2)", "Switches operate primarily at the Data Link Layer, processing Ethernet frames using MAC addresses."),
Q("QUIZ", "EASY", "What type of transmission mode do switches generally operate in?", ["Simplex", "Half-Duplex", "Full-Duplex", "Auto-Duplex"], "Full-Duplex", "Switches operate in full-duplex mode, allowing continuous two-way data transmission without collisions."),
Q("QUIZ", "MEDIUM", "What is an 'Unmanaged Switch'?", ["A switch that requires complex SNMP configuration", "A plug-and-play device used for simple home networks that automatically passes data without configuration", "A switch that connects different ISPs", "A switch installed in a virtual machine"], "A plug-and-play device used for simple home networks that automatically passes data without configuration", "Unmanaged switches are simple devices that work straight out of the box with no admin interface."),
Q("QUIZ", "MEDIUM", "Which type of switch uses SNMP for configuration and provides better security and precision control?", ["Virtual Switch", "Unmanaged Switch", "Managed Switch", "Hub"], "Managed Switch", "Managed switches offer advanced features like VLANs, QoS, and SNMP monitoring for complex enterprise networks."),
Q("QUIZ", "MEDIUM", "What does a 'PoE Switch' do?", ["It connects purely over Wi-Fi", "It combines data and power transmission over the same Ethernet cable", "It acts as a firewall", "It converts IPv4 to IPv6"], "It combines data and power transmission over the same Ethernet cable", "Power over Ethernet (PoE) switches supply electricity along with data, ideal for powering IP cameras and phones."),
Q("QUIZ", "HARD", "How does a switch reduce data collisions compared to a hub?", ["By deleting large files", "By establishing a temporary dedicated connection between source and destination and offering full bandwidth", "By converting frames into IP packets", "By shutting down inactive ports"], "By establishing a temporary dedicated connection between source and destination and offering full bandwidth", "Unlike a hub that broadcasts everything, a switch creates an isolated collision domain for each port."),
Q("QUIZ", "HARD", "What are 'Stackable Switches'?", ["Switches that only support wireless devices", "Switches connected through a backplane to combine multiple logical switches into a single logical switch", "Switches that manage virtual machines", "Switches powered by USB"], "Switches connected through a backplane to combine multiple logical switches into a single logical switch", "Stacking allows administrators to manage multiple physical switches as if they were one single switch, increasing port density and simplifying management."),
Q("QUIZ", "HARD", "What is the key difference between a Switch and a Router regarding the type of address they use?", ["Switches use IP addresses, Routers use MAC addresses", "Switches use MAC addresses, Routers use IP addresses", "They both use MAC addresses", "They both use IP addresses"], "Switches use MAC addresses, Routers use IP addresses", "Switches (Layer 2) route frames using hardware MAC addresses, while Routers (Layer 3) route packets using logical IP addresses."),
Q("QUIZ", "EASY", "Which device operates at Layer 1 of the OSI model and experiences frequent communication collisions?", ["Managed Switch", "Router", "Hub", "Gateway"], "Hub", "A hub is a dumb Layer 1 device that blindly repeats signals to all ports, causing high collision rates."),
Q("QUIZ", "MEDIUM", "What is a 'Smart Switch'?", ["A completely unmanaged plug-and-play switch", "A partially managed switch that offers some extra controls but lacks the full features of a fully managed switch", "A switch that only routes internet traffic", "A virtual machine switch"], "A partially managed switch that offers some extra controls but lacks the full features of a fully managed switch", "Smart switches sit between unmanaged and fully managed switches, offering basic VLAN and QoS features at a lower cost."),
Q("QUIZ", "HARD", "What does a switch do before forwarding data to ensure integrity?", ["It compresses the data to 50%", "It performs error checking", "It translates the MAC address to an IP address", "It broadcasts the data to all ports first"], "It performs error checking", "A switch performs error checking (like reading the CRC) before forwarding the frame to ensure corrupted data isn't propagated."),

// ╔══════════════════════════════════╗
// ║        EXERCISE (12 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "A Network Switch uses which of the following to transfer data to the proper destination?", ["IP Address", "Domain Name", "MAC Address", "Email Address"], "MAC Address", "Switches maintain a MAC address table to learn which device is connected to which port."),
Q("EXERCISE", "EASY", "Which transmission modes does a network switch support?", ["Only Unicast", "Only Broadcast", "Unicast, Multicast, and Broadcast", "Only Multicast"], "Unicast, Multicast, and Broadcast", "Switches can handle one-to-one (unicast), one-to-many (multicast), and one-to-all (broadcast) traffic."),
Q("EXERCISE", "EASY", "What is a 'Virtual Switch'?", ["A switch made of fiber optics", "A switch that exists inside a Virtual Machine hosting environment", "A router disguised as a switch", "A broken network switch"], "A switch that exists inside a Virtual Machine hosting environment", "Virtual switches connect virtual machines together within a host server, functioning exactly like physical switches."),
Q("EXERCISE", "MEDIUM", "Why is a switch considered more complex than a hub?", ["Because it uses more electricity", "Because it reads MAC addresses, performs error checking, and manages data in and out to prevent collisions", "Because it is heavier", "Because it only supports wireless connections"], "Because it reads MAC addresses, performs error checking, and manages data in and out to prevent collisions", "A hub blindly repeats signals, while a switch actively inspects frames and intelligently forwards them."),
Q("EXERCISE", "MEDIUM", "What is a 'Routing Switch' (or Layer 3 Switch)?", ["A switch that connects LANs and performs Network Layer routing functions", "A switch that only routes Wi-Fi", "An unmanaged home switch", "A switch that acts as a modem"], "A switch that connects LANs and performs Network Layer routing functions", "Routing switches combine the fast MAC-based switching of Layer 2 with the IP routing capabilities of Layer 3."),
Q("EXERCISE", "MEDIUM", "Which device helps prevent traffic overloading by segmenting the network into smaller subnets?", ["Hub", "Modem", "Repeater", "Switch"], "Switch", "Switches divide a large network into smaller collision domains (LAN segments), vastly improving overall performance."),
Q("EXERCISE", "HARD", "How does a switch handle the 'Collision Domain'?", ["It merges all ports into one collision domain", "It creates a separate collision domain for each connection (port)", "It ignores collisions entirely", "It pushes collisions to the router"], "It creates a separate collision domain for each connection (port)", "By providing dedicated bandwidth to each port, switches effectively eliminate collisions that occur in hub-based networks."),
Q("EXERCISE", "HARD", "What happens when a data packet first enters a switch?", ["The switch deletes the packet", "The switch broadcasts it to all ports without reading it", "The switch reads the header, finds the destination MAC address, and sends it out the appropriate port", "The switch translates the IP address"], "The switch reads the header, finds the destination MAC address, and sends it out the appropriate port", "The switch acts as a traffic cop, inspecting the incoming frame to determine its exact destination based on the MAC table."),
Q("EXERCISE", "HARD", "Which device moves data between two or MORE computers using 'Data Packets' (not frames)?", ["Network Switch", "Hub", "Router", "Bridge"], "Router", "Routers process Layer 3 Data Packets and move them between different networks, whereas switches process Layer 2 Data Frames within the same network."),
Q("EXERCISE", "EASY", "What does 'LAN' stand for in the context of LAN Switches?", ["Large Area Network", "Local Area Network", "Logical Access Node", "Lightwave Area Network"], "Local Area Network", "LAN switches (Ethernet switches) connect devices within a single local area, like an office building."),
Q("EXERCISE", "MEDIUM", "What protocol is commonly used to configure Managed Switches?", ["HTTP", "SNMP (Simple Network Management Protocol)", "FTP", "POP3"], "SNMP (Simple Network Management Protocol)", "Administrators use SNMP to monitor, configure, and manage high-end network switches."),
Q("EXERCISE", "HARD", "What is listed as a disadvantage of using switches?", ["They slow down the internet", "They cannot stop broadcast traffic from traveling to all other LAN segments", "They are cheaper than hubs", "They cause massive data collisions"], "They cannot stop broadcast traffic from traveling to all other LAN segments", "While a switch breaks up collision domains, it does NOT break up broadcast domains. A broadcast frame will still be sent to all ports."),

// ╔══════════════════════════════════╗
// ║          CAT 1 (10 Qns)          ║
// ╚══════════════════════════════════╝
Q("CAT 1", "EASY", "Which layer of the OSI model does a Hub operate in?", ["Layer 1 (Physical)", "Layer 2 (Data Link)", "Layer 3 (Network)", "Layer 4 (Transport)"], "Layer 1 (Physical)", "A hub is a simple physical device that connects nodes together without any intelligent data management."),
Q("CAT 1", "EASY", "Which device uses 'Plug and Play' method and is generally used for home networks?", ["Managed Switch", "Core Router", "Unmanaged Switch", "Virtual Switch"], "Unmanaged Switch", "Unmanaged switches require zero configuration, making them perfect for simple home setups."),
Q("CAT 1", "EASY", "What is the primary identifier a switch looks for to deliver a message?", ["Email Address", "IP Address", "MAC Address", "Computer Name"], "MAC Address", "Switches operate at the Data Link layer and rely exclusively on hardware MAC addresses for forwarding frames."),
Q("CAT 1", "MEDIUM", "What allows PoE switches to provide electricity?", ["They have internal batteries", "They combine data and power transmission over the same Ethernet cable", "They use solar panels", "They plug into USB ports"], "They combine data and power transmission over the same Ethernet cable", "Power over Ethernet utilizes unused wires in the Ethernet cable to deliver low-voltage power to devices like IP phones."),
Q("CAT 1", "MEDIUM", "Which device transfers data together by connecting devices and preventing collisions with Ethernet frames?", ["Hub", "Repeater", "Modem", "Network Switch"], "Network Switch", "Switches actively manage the flow of Ethernet frames, unlike hubs which simply blindly repeat electrical signals."),
Q("CAT 1", "MEDIUM", "What is a 'Modular Switch'?", ["A switch that only handles one computer", "A switch that helps accommodate two or more expansion cards, providing better flexibility", "A virtual switch", "A switch used only for routing"], "A switch that helps accommodate two or more expansion cards, providing better flexibility", "Modular switches allow administrators to add specific line cards (like fiber optic ports) as the network grows, making them highly flexible."),
Q("CAT 1", "HARD", "How does a switch improve network connectivity compared to a hub regarding 'Duplex' modes?", ["Hubs are Full-Duplex, Switches are Simplex", "Switches work in Full-Duplex mode, allowing continuous two-way transmission, whereas Hubs are Half-Duplex", "They both operate in Half-Duplex", "Switches cannot send and receive data simultaneously"], "Switches work in Full-Duplex mode, allowing continuous two-way transmission, whereas Hubs are Half-Duplex", "Because a switch creates isolated connections, devices can send and receive simultaneously (Full-Duplex) without colliding."),
Q("CAT 1", "HARD", "Which device works with both wired and Wi-Fi networks according to the comparison chart?", ["Network Switch", "Hub", "Router", "Bridge"], "Router", "Standard switches strictly manage wired connections. Routers often include wireless access points to manage both wired and Wi-Fi networks."),
Q("CAT 1", "HARD", "What does a switch do to the connection once the 'conversation' between the source and destination is done?", ["It leaves it open forever", "It terminates the temporary connection", "It converts it to a broadcast", "It assigns a new IP address"], "It terminates the temporary connection", "The switch dynamically establishes and tears down temporary circuits between ports as frames are transmitted."),
Q("CAT 1", "HARD", "Which data unit is correctly paired with its device?", ["Switch uses Packets, Router uses Frames", "Switch uses Frames, Router uses Packets", "Hub uses Frames, Switch uses Packets", "Router uses Segments, Switch uses Bits"], "Switch uses Frames, Router uses Packets", "Layer 2 Switches handle Frames. Layer 3 Routers handle Packets."),

// ╔══════════════════════════════════╗
// ║          CAT 2 (10 Qns)          ║
// ╚══════════════════════════════════╝
Q("CAT 2", "EASY", "Which network device is described as being 'a little more complex' and capable of preventing collisions?", ["Hub", "Repeater", "Switch", "Ethernet Cable"], "Switch", "A switch contains memory and logic to inspect frames, making it more complex and efficient than a hub."),
Q("CAT 2", "EASY", "Which transmission mode sends data from one source to ALL devices on the network?", ["Unicast", "Multicast", "Broadcast", "Anycast"], "Broadcast", "Broadcast transmission sends a frame to the MAC address FF-FF-FF-FF-FF-FF, reaching every node."),
Q("CAT 2", "EASY", "Is a Network Switch generally used for WAN or LAN?", ["WAN", "LAN", "PAN", "MAN"], "LAN", "Switches are primarily designed to segment and manage traffic within a Local Area Network (LAN)."),
Q("CAT 2", "MEDIUM", "What type of switch provides better security levels, precision control, and is mostly used in large networks?", ["Unmanaged Switch", "Managed Switch", "Hub", "PoE Switch"], "Managed Switch", "Managed switches allow granular configuration of ports, VLANs, and security policies, essential for large enterprise environments."),
Q("CAT 2", "MEDIUM", "Which device primarily shares resources among multiple devices with the help of a single LAN?", ["Router", "Network Switch", "Modem", "Gateway"], "Network Switch", "A switch connects local devices (like PCs and printers) together so they can share resources on the same LAN segment."),
Q("CAT 2", "MEDIUM", "What is one distinct advantage of switches over hubs regarding bandwidth?", ["Switches decrease total bandwidth", "Switches allocate a limited but dedicated bandwidth to each LAN segment, increasing overall network bandwidth", "Switches use bandwidth only for Wi-Fi", "Hubs have infinite bandwidth"], "Switches allocate a limited but dedicated bandwidth to each LAN segment, increasing overall network bandwidth", "Because a switch doesn't force all devices to share a single collision domain, the aggregate bandwidth of the network increases significantly."),
Q("CAT 2", "HARD", "How does a 'Routing Switch' differ from a standard 'Network Switch'?", ["It operates at Layer 1", "It is completely unmanaged", "It combines Layer 2 switching with Layer 3 Network routing functions", "It only handles analog signals"], "It combines Layer 2 switching with Layer 3 Network routing functions", "A routing switch (or Layer 3 switch) can route IP packets between different subnets as well as switch MAC frames."),
Q("CAT 2", "HARD", "If an administrator needs a switch that offers some extra control over data transmissions but doesn't need the full complexity of a Managed Switch, what should they buy?", ["Unmanaged Switch", "Smart Switch", "Hub", "Virtual Switch"], "Smart Switch", "Smart switches (partially managed switches) offer a middle ground, providing basic web-based management for VLANs and QoS at a lower price point."),
Q("CAT 2", "HARD", "In the comparison between a Switch and a Router, which statement is true regarding the resource scope?", ["Routers share resources on a single LAN, Switches move data between computers globally", "Switches share resources among multiple devices in a single LAN, while Routers move data between two or more different networks", "Both operate exactly the same way", "Switches use IPs, Routers use MACs"], "Switches share resources among multiple devices in a single LAN, while Routers move data between two or more different networks", "Switches build the local network, Routers connect local networks to other networks (like the internet)."),
Q("CAT 2", "HARD", "Which device acts simply to connect all nodes of a network physically, without managing data in and out?", ["Router", "Managed Switch", "Hub", "Firewall"], "Hub", "A hub merely connects physical wires together. When an electrical signal enters one port, it is blindly repeated out of all other ports."),

// ╔══════════════════════════════════╗
// ║            UE (10 Qns)           ║
// ╚══════════════════════════════════╝
Q("UE", "EASY", "Which layer of the OSI model does a Network Switch operate in?", ["Layer 1", "Layer 2", "Layer 3", "Layer 4"], "Layer 2", "Switches operate at Layer 2 (Data Link Layer), dealing with frames and MAC addresses."),
Q("UE", "EASY", "What is a 'Collision Domain'?", ["A virtual reality game", "A network segment where data packets can collide with one another when being sent on a shared medium", "A routing protocol", "A type of fiber optic cable"], "A network segment where data packets can collide with one another when being sent on a shared medium", "In a hub network, all devices share one collision domain. A switch breaks this up, providing each port with its own collision domain."),
Q("UE", "EASY", "Which switch type is used when you need to power an IP camera directly through the network cable?", ["Virtual Switch", "PoE Switch", "Unmanaged Switch", "Routing Switch"], "PoE Switch", "Power over Ethernet (PoE) switches eliminate the need for separate electrical power supplies for networked devices."),
Q("UE", "MEDIUM", "What is one reason why network switches are considered essential for home or local networks?", ["They host web pages", "They provide automatic link connections, remove time-consuming settings, and allow fast streaming and easy device access", "They generate MAC addresses", "They encrypt passwords"], "They provide automatic link connections, remove time-consuming settings, and allow fast streaming and easy device access", "Switches make local networking seamless. Devices plug in and instantly communicate without manual IP routing configuration."),
Q("UE", "MEDIUM", "What does a switch examine first when data arrives at any of its ports?", ["The IP Address", "The destination MAC address in the frame header", "The size of the file", "The HTTP request"], "The destination MAC address in the frame header", "The switch reads the destination MAC address to decide which specific port the frame should be forwarded to."),
Q("UE", "MEDIUM", "What is a 'Stackable Switch' used for?", ["Connecting to wireless devices", "Combining two or more logical switches into a single logical switch via a backplane connection", "Acting as a router", "Powering down inactive ports"], "Combining two or more logical switches into a single logical switch via a backplane connection", "Stacking provides the capacity of multiple switches while allowing the network administrator to manage them as a single entity."),
Q("UE", "HARD", "How does a switch handle 'Unicast' transmission?", ["It sends the data to all connected devices", "It establishes a one-to-one connection and transfers the data only to the device that has been specifically addressed", "It sends data to a specific group", "It drops the packet"], "It establishes a one-to-one connection and transfers the data only to the device that has been specifically addressed", "Unicast is direct communication. The switch uses its MAC table to forward the frame exclusively to the intended recipient's port."),
Q("UE", "HARD", "What technique is used by switches to transfer data packets from source to destination?", ["Circuit Switching", "Packet Switching techniques", "Message Switching", "Analog Switching"], "Packet Switching techniques", "Modern switches use packet switching techniques (specifically frame switching) to receive, store, and forward digital data blocks."),
Q("UE", "HARD", "Which device works exclusively in a wired network connection according to standard definitions?", ["Router", "Network Switch", "Smartphone", "Tablet"], "Network Switch", "While routers often include Wi-Fi access points, pure network switches deal entirely with wired Ethernet connections."),
Q("UE", "HARD", "What is a known disadvantage of using switches instead of hubs?", ["They cause more collisions", "They cannot perform full-duplex communication", "They are generally more expensive than simple hubs", "They cannot read MAC addresses"], "They are generally more expensive than simple hubs", "Because switches require complex ASICs, processors, and memory to manage MAC tables and forward frames, they cost more than simple hubs."),

// ╔══════════════════════════════════╗
// ║       POSSIBLE QNS (10 Qns)      ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS", "EASY", "What does 'LAN' segment mean?", ["A piece of a cable", "A subdivided portion of a network created by a switch to reduce congestion", "A type of router", "A wireless protocol"], "A subdivided portion of a network created by a switch to reduce congestion", "Switches break large networks into smaller, more efficient LAN segments."),
Q("POSSIBLE QNS", "EASY", "If you need a switch for a small home business and do not want to configure anything, what should you buy?", ["Managed Switch", "Core Router", "Unmanaged Switch", "Modular Switch"], "Unmanaged Switch", "Unmanaged switches are purely plug-and-play, perfect for small setups requiring no management."),
Q("POSSIBLE QNS", "EASY", "Which transmission mode means 'one-to-many'?", ["Unicast", "Multicast", "Broadcast", "Simplex"], "Multicast", "Multicast allows a source to send data to a specific group of interested devices, rather than just one or all of them."),
Q("POSSIBLE QNS", "MEDIUM", "What is the primary difference between a Modular Switch and a Stackable Switch?", ["Modular is for software, Stackable is for hardware", "Modular accommodates adding expansion cards into a chassis, while Stackable connects entire standalone switches together via a backplane", "Modular is unmanaged, Stackable is managed", "There is no difference"], "Modular accommodates adding expansion cards into a chassis, while Stackable connects entire standalone switches together via a backplane", "Modular switches offer a massive chassis where you slide in port blades. Stackable switches are regular 1U switches cabled together to act as one."),
Q("POSSIBLE QNS", "MEDIUM", "Why do communication collisions usually happen in a Hub?", ["Because hubs are too fast", "Because a hub operates at Layer 1 and blindly broadcasts every received signal to all other ports simultaneously", "Because hubs use IP addresses", "Because hubs run in full-duplex"], "Because a hub operates at Layer 1 and blindly broadcasts every received signal to all other ports simultaneously", "A hub creates one massive collision domain. If two devices talk at the exact same time, the signals collide and corrupt."),
Q("POSSIBLE QNS", "MEDIUM", "Which device operates at Layer 3 of the OSI model?", ["Hub", "Unmanaged Switch", "Router", "Network Interface Card"], "Router", "Routers process IP packets and make routing decisions at the Network Layer (Layer 3)."),
Q("POSSIBLE QNS", "HARD", "How does a switch utilize its 'Full-Duplex' capability to improve connectivity?", ["It translates data twice", "It allows devices to send and receive data simultaneously without the risk of collision, providing continuous transmission", "It connects to two ISPs", "It encrypts data in both directions"], "It allows devices to send and receive data simultaneously without the risk of collision, providing continuous transmission", "Full-duplex effectively doubles the potential bandwidth because the transmit and receive paths are separate and isolated by the switch."),
Q("POSSIBLE QNS", "HARD", "What does it mean that a switch 'cannot stop traffic destined for a different LAN segment from traveling to all other LAN segments' in certain contexts?", ["It means switches are useless", "It refers to Broadcast traffic; a Layer 2 switch cannot break up a broadcast domain, so broadcast frames flood all ports", "It means switches ignore MAC addresses", "It means switches route IP packets"], "It refers to Broadcast traffic; a Layer 2 switch cannot break up a broadcast domain, so broadcast frames flood all ports", "While switches break up collision domains, any broadcast frame (like an ARP request) must be forwarded out all ports to ensure the target receives it. Routers are needed to stop broadcasts."),
Q("POSSIBLE QNS", "HARD", "What feature allows Managed Switches to be used in complex architectures?", ["They are painted black", "They support protocols like SNMP for precision control, monitoring, and configuring high security levels", "They use Category 3 cables", "They lack a power supply"], "They support protocols like SNMP for precision control, monitoring, and configuring high security levels", "Managed switches offer a command-line or web interface to configure VLANs, port security, QoS, and monitoring via SNMP."),
Q("POSSIBLE QNS", "HARD", "Which device uses 'Data Packets' and 'IP Addresses' to move data between completely different networks?", ["Network Switch", "Hub", "Router", "Repeater"], "Router", "Unlike a switch which uses MAC addresses and frames on a single LAN, a router inspects IP addresses inside packets to navigate across the internet.")
];

async function insertUnit5() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = unit5_questions.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} questions for Unit 5.`);
        } else {
            console.log("No new questions for Unit 5 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit5();
