const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a5d16dbf29e866583f45d27";

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const unit4_questions = [
// ╔══════════════════════════════════╗
// ║          QUIZ (15 Qns)           ║
// ╚══════════════════════════════════╝
Q("QUIZ", "EASY", "What does MAC stand for in MAC Address?", ["Machine Access Control", "Media Access Control", "Main Address Configuration", "Memory Access Channel"], "Media Access Control", "MAC stands for Media Access Control. A MAC address is a unique hardware identifier."),
Q("QUIZ", "EASY", "How long is a MAC Address?", ["32 bits", "48 bits", "64 bits", "128 bits"], "48 bits", "A MAC Address is a unique 48-bit hardware number, typically represented in 12 hexadecimal digits."),
Q("QUIZ", "EASY", "Which layer of the OSI model uses MAC addresses?", ["Physical Layer", "Network Layer", "Data Link Layer", "Transport Layer"], "Data Link Layer", "MAC addresses operate at the Data Link Layer, specifically within the MAC sub-layer."),
Q("QUIZ", "EASY", "Who provides the MAC address to a network device?", ["The Internet Service Provider (ISP)", "The user", "The NIC Manufacturer", "The DHCP Server"], "The NIC Manufacturer", "MAC addresses are burned into the Network Interface Card (NIC) by the hardware manufacturer."),
Q("QUIZ", "EASY", "What is the primary function of a Router?", ["To provide electrical power to cables", "To analyze and forward data packets between different computer networks based on IP addresses", "To act as a physical monitor", "To block all incoming traffic by default"], "To analyze and forward data packets between different computer networks based on IP addresses", "Routers are Layer 3 devices that route packets across networks using dynamically updated routing tables."),
Q("QUIZ", "MEDIUM", "What do the first 6 digits of a MAC address represent?", ["The device's serial number", "The Organizational Unique Identifier (OUI) identifying the manufacturer", "The IP address mapping", "The country code"], "The Organizational Unique Identifier (OUI) identifying the manufacturer", "The first 3 bytes (6 hex digits) of a MAC address form the OUI, which uniquely identifies the vendor/manufacturer."),
Q("QUIZ", "MEDIUM", "Which type of MAC address is meant to reach only a single receiving NIC?", ["Broadcast", "Multicast", "Unicast", "Anycast"], "Unicast", "A Unicast address (where the LSB of the first octet is zero) directs a frame to one specific, individual NIC."),
Q("QUIZ", "MEDIUM", "If the destination MAC address is FF-FF-FF-FF-FF-FF, what type of address is it?", ["Multicast", "Unicast", "Broadcast", "Loopback"], "Broadcast", "A MAC address of all 1s (FF-FF-FF-FF-FF-FF in hex) is the broadcast address, which reaches every computer on the LAN segment."),
Q("QUIZ", "MEDIUM", "What does 'MAC Cloning' allow a user to do?", ["Create duplicate devices", "Bypass all firewalls", "Fix ISP connectivity issues by copying an old registered MAC address to a new router", "Increase internet speed instantly"], "Fix ISP connectivity issues by copying an old registered MAC address to a new router", "When an ISP binds an internet lease to a specific MAC address, MAC Cloning lets a new router spoof the old MAC to maintain connectivity."),
Q("QUIZ", "MEDIUM", "Which protocol resolves IP addresses to MAC addresses?", ["DNS", "DHCP", "ARP", "RARP"], "ARP", "Address Resolution Protocol (ARP) is used to map a known IP address to an unknown MAC address on a local network."),
Q("QUIZ", "HARD", "Which component is considered the 'heart' of the Router?", ["Input Port", "Output Port", "Routing Processor", "Switching Fabric"], "Switching Fabric", "The Switching Fabric connects the router's input ports to its output ports, routing packets internally via memory, bus, or an interconnection network."),
Q("QUIZ", "HARD", "What is the primary role of the 'Routing Processor' in a router?", ["It executes routing protocols like OSPF and builds the forwarding table", "It physically connects the Ethernet cables", "It provides Wi-Fi signals", "It translates domain names"], "It executes routing protocols like OSPF and builds the forwarding table", "The Routing Processor acts like a CPU, running algorithms (like link-state or distance-vector) to determine the best paths and update routing tables."),
Q("QUIZ", "HARD", "Which routing protocol facilitates information sharing specifically between EDGE routers to control internet packet routing?", ["IGRP", "BGP (Border Gateway Protocol)", "OSPF", "EIGRP"], "BGP (Border Gateway Protocol)", "BGP is the core routing protocol of the internet, exchanging routing and reachability information between autonomous systems (edge routers)."),
Q("QUIZ", "HARD", "Why are MAC addresses considered to have a 'Limited Scope'?", ["They are too short", "They are only used to identify devices within a local network segment and are not routable across the internet", "They expire after 24 hours", "They cannot handle IPv6"], "They are only used to identify devices within a local network segment and are not routable across the internet", "MAC addresses do not cross router boundaries. Once a packet leaves a local network, routing relies on IP addresses."),
Q("QUIZ", "HARD", "What is a 'Virtual Router'?", ["A router hidden behind a wall", "A software-based routing framework implemented on a virtual machine, offering flexibility and scalability", "A router that uses virtual reality", "An unconfigured physical router"], "A software-based routing framework implemented on a virtual machine, offering flexibility and scalability", "Virtual routers are software applications that replicate the functionality of a hardware router, often used in cloud environments."),

// ╔══════════════════════════════════╗
// ║        EXERCISE (15 Qns)         ║
// ╚══════════════════════════════════╝
Q("EXERCISE", "EASY", "Which sub-layer of the Data Link layer is responsible for using the MAC address?", ["Logical Link Control (LLC)", "Media Access Control (MAC)", "Physical Control", "Network Control"], "Media Access Control (MAC)", "The MAC address is specifically used by the MAC sub-layer to physically address data frames."),
Q("EXERCISE", "EASY", "A MAC address is written in which format?", ["Dotted decimal", "Binary only", "Hexadecimal (e.g., CC:46:D6:11:22:33)", "Octal"], "Hexadecimal (e.g., CC:46:D6:11:22:33)", "MAC addresses are typically represented using 12 hexadecimal digits separated by colons or hyphens."),
Q("EXERCISE", "EASY", "Which type of router is designed specifically to connect multiple wired devices using Ethernet cables in schools or small offices?", ["Wireless Router", "Wired Router", "Virtual Router", "Core Router"], "Wired Router", "Wired Routers take data from a modem and distribute it to a network exclusively via physical Ethernet cables."),
Q("EXERCISE", "EASY", "Which of the following is a disadvantage of a MAC Address?", ["It is globally unique", "It is hardware-dependent; if the NIC breaks, the MAC address changes when the card is replaced", "It provides high security natively", "It replaces IP addresses entirely"], "It is hardware-dependent; if the NIC breaks, the MAC address changes when the card is replaced", "Because the MAC is burned into the physical NIC, replacing the hardware inevitably changes the device's MAC address."),
Q("EXERCISE", "EASY", "What does a Router use to decide the best way to transfer packets?", ["MAC addresses only", "Destination IP addresses and forwarding/routing tables", "Domain names", "File sizes"], "Destination IP addresses and forwarding/routing tables", "Routers examine the destination IP in a packet's header and cross-reference their routing tables to determine the best path."),
Q("EXERCISE", "MEDIUM", "What does QoS (Quality of Service) do on a router?", ["It tests the cables for physical damage", "It prioritizes network traffic based on data type, ensuring critical applications get enough bandwidth", "It changes the MAC address daily", "It encrypts all network traffic"], "It prioritizes network traffic based on data type, ensuring critical applications get enough bandwidth", "QoS is a router function that guarantees certain traffic (like voice or video calls) is prioritized over less critical traffic (like file downloads)."),
Q("EXERCISE", "MEDIUM", "How can MAC addresses be 'spoofed'?", ["By physically melting the NIC", "By using software to mask or change the broadcasted MAC address, allowing unauthorized network access", "By using a crossover cable", "By unplugging the router"], "By using software to mask or change the broadcasted MAC address, allowing unauthorized network access", "Although burned into hardware, operating systems allow users to temporarily spoof their MAC address via software, creating a security risk."),
Q("EXERCISE", "MEDIUM", "In Multicast MAC addressing, what distinguishes the address?", ["It consists of all 1s", "The least significant bit (LSB) of the first octet is set to one", "It consists of all zeroes", "It is completely random"], "The least significant bit (LSB) of the first octet is set to one", "An LSB of 1 in the first octet indicates that the frame is destined for a specific group of devices (multicast) rather than a single device."),
Q("EXERCISE", "MEDIUM", "What is a 'Core Router'?", ["A router at the edge of a network connecting to the ISP", "A router that provides Wi-Fi", "A router that distributes packets within the same network, carrying very heavy data transfers", "A router installed on a smartphone"], "A router that distributes packets within the same network, carrying very heavy data transfers", "Core routers operate at the internet's backbone or within large enterprise networks, designed strictly to move massive amounts of data as fast as possible."),
Q("EXERCISE", "MEDIUM", "Which protocol is utilized to determine the optimal path for packets as they travel across several networks?", ["ARP", "OSPF (Open Shortest Path First)", "FTP", "DHCP"], "OSPF (Open Shortest Path First)", "OSPF is a widely used interior gateway routing protocol that calculates the shortest and best path for routing packets."),
Q("EXERCISE", "HARD", "In the architecture of a router, what happens at the 'Input Port'?", ["It broadcasts Wi-Fi signals", "It terminates the physical link, performs decapsulation, and looks up the forwarding table to determine the output port", "It creates a VPN tunnel", "It updates the DNS server"], "It terminates the physical link, performs decapsulation, and looks up the forwarding table to determine the output port", "The input port receives the raw bits, processes the data link frame, reads the IP packet header, and determines where the packet should go next."),
Q("EXERCISE", "HARD", "How is 'Switching via Bus' implemented inside a router's switching fabric?", ["A single CPU copies packets into RAM", "Packets are assigned a token and put on a shared internal bus; all output ports see it, but only the matching port accepts it", "It uses wireless signals internally", "It uses 2N dedicated buses"], "Packets are assigned a token and put on a shared internal bus; all output ports see it, but only the matching port accepts it", "In a bus-based switching fabric, packets are transferred over a shared backplane, limiting the router's speed to the bandwidth of that single bus."),
Q("EXERCISE", "HARD", "What is one major disadvantage of using routers according to the notes?", ["They cannot connect to the internet", "They are slower than switches because they must analyze multiple layers of information (Physical to Network layer)", "They do not have MAC addresses", "They cannot use Ethernet cables"], "They are slower than switches because they must analyze multiple layers of information (Physical to Network layer)", "Because routers must strip off the Layer 2 frame, inspect the Layer 3 IP packet, and calculate routes, they inherently add processing delay compared to simple Layer 2 switches."),
Q("EXERCISE", "HARD", "What is the primary function of the 'EIGRP' protocol?", ["To resolve MAC to IP", "To request neighboring routers for a route if it cannot find a path in its own routing tables", "To host web pages", "To encrypt router passwords"], "To request neighboring routers for a route if it cannot find a path in its own routing tables", "Enhanced Interior Gateway Routing Protocol (EIGRP) communicates with neighbors to dynamically find and establish optimal paths when primary routes fail."),
Q("EXERCISE", "HARD", "What does 'Dynamic routing' cause that can be considered a bandwidth shortage?", ["It physically damages cables", "It causes network overhead because routers must constantly exchange routing table updates, consuming bandwidth", "It limits the router to 10 Mbps", "It blocks UDP traffic"], "It causes network overhead because routers must constantly exchange routing table updates, consuming bandwidth", "Dynamic routing algorithms continuously send update messages between routers to keep tables current, which eats into the available bandwidth for actual user data.")
];

const cat1 = [
Q("CAT 1", "EASY", "Which identifier is provided by the Internet Service Provider (ISP)?", ["MAC Address", "Serial Number", "IP Address", "OUI"], "IP Address", "While the NIC manufacturer provides the MAC address, the ISP provides the publicly routable IP address."),
Q("CAT 1", "EASY", "Which layer is MAC addressing fundamentally associated with?", ["Layer 1 (Physical)", "Layer 2 (Data Link)", "Layer 3 (Network)", "Layer 4 (Transport)"], "Layer 2 (Data Link)", "The Media Access Control address operates at the Data Link layer."),
Q("CAT 1", "EASY", "What does 'DDoS' stand for in the context of router security challenges?", ["Direct Data Output System", "Distributed Denial-Of-Service", "Dynamic Domain Open Server", "Data Duplication over Switches"], "Distributed Denial-Of-Service", "A DDoS attack attempts to overwhelm network infrastructure, like routers, with a massive flood of traffic, causing outages."),
Q("CAT 1", "EASY", "A router that provides an internet connection without wires is called a:", ["Wired Router", "Virtual Router", "Wireless Router", "Switch"], "Wireless Router", "A wireless router creates a Wi-Fi signal to connect devices to the network without physical cables."),
Q("CAT 1", "MEDIUM", "What is the purpose of 'Firmware' in a router?", ["It acts as the physical antenna", "It is the software installed directly on the hardware to assist its operation and must be updated to fix security flaws", "It is the battery supply", "It is a type of MAC address"], "It is the software installed directly on the hardware to assist its operation and must be updated to fix security flaws", "Router firmware runs the device's operating system. Exploiting outdated firmware is a common security challenge."),
Q("CAT 1", "MEDIUM", "Why is changing default administration credentials (like admin/admin) critical for a router?", ["To increase download speed", "Because attackers know these default values and can use them to remotely take over the router", "To allow MAC cloning", "To enable IPv6"], "Because attackers know these default values and can use them to remotely take over the router", "Leaving default credentials exposes the router to trivial unauthorized access and botnet infections."),
Q("CAT 1", "MEDIUM", "Which protocol is frequently used for communicating routing table data between entirely different internet hosts (outside a single organization)?", ["IGRP", "EGP (Exterior Gateway Protocol)", "ARP", "DHCP"], "EGP (Exterior Gateway Protocol)", "EGP, and its successor BGP, are designed specifically to share routing data between different autonomous systems on the global internet."),
Q("CAT 1", "HARD", "How does 'Switching via memory' work inside a router?", ["It uses hard drives to store packets permanently", "A processor copies the packet from the input port to memory, and then sends it to the appropriate output port", "It bypasses the CPU entirely", "It uses fiber optics internally"], "A processor copies the packet from the input port to memory, and then sends it to the appropriate output port", "In memory-based switching, the router acts like a traditional computer where the CPU handles the transfer of packets between input and output buffers in RAM."),
Q("CAT 1", "HARD", "What does 'Queuing Buffers' do at a router's Output Port?", ["They delete oversized packets", "They store packets temporarily when more packets arrive than can be transmitted simultaneously out of the link", "They translate IP to MAC", "They encrypt the data"], "They store packets temporarily when more packets arrive than can be transmitted simultaneously out of the link", "If traffic arrives faster than the output link can handle, packets queue in the buffer. If the buffer fills up, packets are dropped.")
];

const cat2 = [
Q("CAT 2", "EASY", "What is a major advantage of using MAC Addresses for network administration?", ["They are totally invisible", "They are easy to configure, require no extra infrastructure, and guarantee device uniqueness on a LAN", "They route data to other countries", "They encrypt all data"], "They are easy to configure, require no extra infrastructure, and guarantee device uniqueness on a LAN", "Because every NIC has a burned-in MAC, administrators can easily identify and filter devices on a local network without setting up complex software."),
Q("CAT 2", "EASY", "Which type of router is usually located at the boundary of a network, connecting it directly to an ISP?", ["Core Router", "Edge Router", "Portable Router", "Virtual Router"], "Edge Router", "Edge routers sit at the edge or boundary of a network, distributing packets between the local network and the external ISP."),
Q("CAT 2", "EASY", "What is one application of a router mentioned in the notes?", ["Playing video games", "Connecting hardware equipment like BSC, MGW, IN, SGSN from remote location networks", "Printing documents directly", "Scanning for viruses on a hard drive"], "Connecting hardware equipment like BSC, MGW, IN, SGSN from remote location networks", "Routers are widely used in telecommunications to connect complex remote servers and switching centers securely."),
Q("CAT 2", "EASY", "Which security risk involves intercepting plain text MAC addresses from the air?", ["Eavesdropping / Lack of encryption", "DDoS", "Hardware Failure", "Buffer Overflow"], "Eavesdropping / Lack of encryption", "Because MAC addresses are transmitted in plain text in frame headers, they are highly vulnerable to interception and eavesdropping."),
Q("CAT 2", "MEDIUM", "What is a 'Portable Router'?", ["A router that weighs 100 lbs", "A router designed for easy portability to create a private Wi-Fi hotspot on the go", "A router that only uses Ethernet", "A router embedded in a TV"], "A router designed for easy portability to create a private Wi-Fi hotspot on the go", "Portable (or travel) routers use cellular data or existing connections to broadcast a private Wi-Fi network anywhere."),
Q("CAT 2", "MEDIUM", "What does 'IGRP' stand for?", ["Internal Gateway Routing Protocol", "Interior Gateway Routing Protocol", "Integrated Global Routing Path", "Internet Gateway Resource Protocol"], "Interior Gateway Routing Protocol", "IGRP is a distance-vector interior routing protocol used to exchange routing data within a single autonomous network."),
Q("CAT 2", "MEDIUM", "Which router function involves checking the 'checksum' of a received packet?", ["Routing", "Security", "Forwarding", "QoS"], "Forwarding", "During the forwarding process, the router receives the packet, checks its header for errors (checksum), and sends it to the output port."),
Q("CAT 2", "HARD", "How does an 'Interconnection Network' switching fabric improve upon a 'Bus' switching fabric in a router?", ["It uses a single shared wire", "It uses a crossbar switch (2N bus) allowing multiple packets to be transferred simultaneously to different output ports", "It relies entirely on the main CPU", "It only supports IPv6"], "It uses a crossbar switch (2N bus) allowing multiple packets to be transferred simultaneously to different output ports", "An interconnection network (like a crossbar) removes the bottleneck of a single shared bus, enabling parallel forwarding of packets."),
Q("CAT 2", "HARD", "In MAC addressing, what is meant by 'Inefficiency' as a disadvantage?", ["MAC addresses are slow", "MAC addresses are not hierarchical (unlike IP subnets), making it difficult to efficiently route and manage large networks globally", "They consume too much electricity", "They cause frequent network collisions"], "MAC addresses are not hierarchical (unlike IP subnets), making it difficult to efficiently route and manage large networks globally", "Because MAC addresses are flat and randomly distributed geographically, routers cannot group them into efficient routing tables like they do with IP subnets.")
];

const ue = [
Q("UE", "EASY", "What is the primary physical characteristic of a MAC Address?", ["It is dynamic and changes daily", "It is 48 bits long and burned into the network card hardware", "It is 32 bits long", "It is assigned by a DHCP server"], "It is 48 bits long and burned into the network card hardware", "A MAC Address is permanently embedded into a device's Network Interface Card during manufacturing."),
Q("UE", "EASY", "Which type of router distributes packets within the same network and handles heavy data transfers?", ["Virtual Router", "Edge Router", "Core Router", "Wireless Router"], "Core Router", "Core routers form the backbone of a network, routing massive amounts of data internally rather than connecting to the outside world."),
Q("UE", "EASY", "Why is a router considered a security device?", ["It comes with a free antivirus subscription", "It can be configured with firewalls, NAT, and access control to protect against unauthorized access", "It physically shocks hackers", "It hides the MAC address"], "It can be configured with firewalls, NAT, and access control to protect against unauthorized access", "Routers act as the first line of defense between the internet and a private LAN by utilizing NAT, firewalls, and packet filtering."),
Q("UE", "EASY", "What is 'RARP' used for?", ["Retrieving an IP address when only a MAC address is known", "Encrypting emails", "Assigning MAC addresses", "Blocking DDoS attacks"], "Retrieving an IP address when only a MAC address is known", "Reverse Address Resolution Protocol (RARP) does the exact opposite of ARP: it resolves a hardware MAC address to an IP address."),
Q("UE", "EASY", "If a router's firmware is outdated, what is the most likely consequence?", ["The router will catch fire", "Hackers can exploit known vulnerabilities to take over the router or use it in a botnet", "The MAC address will change", "The router will switch to IPv6"], "Hackers can exploit known vulnerabilities to take over the router or use it in a botnet", "Firmware updates patch security flaws. Unpatched routers are prime targets for cyberattacks."),
Q("UE", "MEDIUM", "What is the function of a 'VPN' configured on a router?", ["To speed up local downloads", "To allow remote users to connect securely to the private network over the public internet", "To block all YouTube traffic", "To assign MAC addresses dynamically"], "To allow remote users to connect securely to the private network over the public internet", "Virtual Private Network (VPN) connectivity on a router creates an encrypted tunnel, allowing safe remote access to LAN resources."),
Q("UE", "MEDIUM", "How does MAC filtering restrict network access?", ["By asking for a password", "By only allowing devices with specific, pre-authorized MAC addresses to connect to the network", "By blocking all IP addresses", "By turning off the router at night"], "By only allowing devices with specific, pre-authorized MAC addresses to connect to the network", "MAC filtering creates an allowlist; if a device's burned-in hardware address isn't on the list, the router refuses its connection."),
Q("UE", "MEDIUM", "Which routing protocol uses the term 'Shortest Path First'?", ["BGP", "OSPF", "EIGRP", "RIP"], "OSPF", "Open Shortest Path First (OSPF) is a link-state routing protocol used to find the most optimal path within a single routing domain."),
Q("UE", "HARD", "In the context of router disadvantages, what is meant by 'Connection waiting'?", ["The router needs to reboot", "Because routers analyze multiple layers (from Physical to Network), processing delays can cause connections to slow down or wait when multiple devices are active", "The ISP is down", "The cables are too long"], "Because routers analyze multiple layers (from Physical to Network), processing delays can cause connections to slow down or wait when multiple devices are active", "Routers must perform complex logical calculations on every packet, making them inherently slower than simple Layer 2 switches."),
Q("UE", "HARD", "What does a router's 'Static Routing Table' imply?", ["It is automatically updated by the network", "It is configured manually by an administrator and does not adapt automatically to network changes", "It changes based on electricity flow", "It only handles MAC addresses"], "It is configured manually by an administrator and does not adapt automatically to network changes", "Static routing requires manual entry of paths. It is highly secure and uses no bandwidth overhead, but cannot automatically bypass network failures.")
];

const poss = [
Q("POSSIBLE QNS", "EASY", "What is an OUI in a MAC address?", ["Over User Interface", "Organizational Unique Identifier, representing the manufacturer", "Optional Unicast IP", "Open Universal Internet"], "Organizational Unique Identifier, representing the manufacturer", "The first 3 bytes (6 digits) of a MAC address are assigned to vendors by the IEEE to identify the manufacturer."),
Q("POSSIBLE QNS", "EASY", "What is the main function of 'Bandwidth Management' on a router?", ["To increase the physical size of the cable", "To control the amount of data flowing through the network to prevent congestion", "To stop viruses", "To translate IP addresses"], "To control the amount of data flowing through the network to prevent congestion", "By managing bandwidth, a router ensures the network doesn't become choked by excessive traffic, maintaining stability."),
Q("POSSIBLE QNS", "EASY", "Can two different devices on the internet share the exact same MAC address?", ["Yes, it is common", "No, MAC addresses are designed to be worldwide unique", "Only if they are on the same Wi-Fi", "Yes, if they use the same IP"], "No, MAC addresses are designed to be worldwide unique", "Millions of devices exist, and manufacturers follow strict guidelines to ensure every single MAC address produced is unique."),
Q("POSSIBLE QNS", "MEDIUM", "What is 'Packet Filtering'?", ["Washing the cables", "A router service that uses a collection of rules to allow or block packets from passing through the network", "Compressing data", "Assigning dynamic IPs"], "A router service that uses a collection of rules to allow or block packets from passing through the network", "Packet filtering is a basic firewall technique where a router inspects packet headers and drops those that violate security rules."),
Q("POSSIBLE QNS", "MEDIUM", "What is one reason why MAC addresses lack inherent security?", ["They are encrypted too heavily", "They are sent in plain text, making them vulnerable to interception, eavesdropping, and spoofing", "They change every 5 minutes", "They are too long"], "They are sent in plain text, making them vulnerable to interception, eavesdropping, and spoofing", "Because MAC addresses are transmitted unencrypted in the Data Link header, anyone sniffing the network can read and spoof them."),
Q("POSSIBLE QNS", "HARD", "How does a router 'decapsulate' data at the Input Port?", ["By wrapping it in a new frame", "By stripping away the Data Link layer frame header and trailer to expose the Network layer IP packet inside", "By encrypting the payload", "By deleting the packet"], "By stripping away the Data Link layer frame header and trailer to expose the Network layer IP packet inside", "When a frame arrives, the router must remove the Layer 2 encapsulation to read the Layer 3 IP address needed for routing decisions."),
Q("POSSIBLE QNS", "HARD", "Which term describes a router attack where traffic from many compromised devices is used to overwhelm the network infrastructure?", ["ARP Spoofing", "MAC Cloning", "DDoS (Distributed Denial-Of-Service) Attack", "Packet Sniffing"], "DDoS (Distributed Denial-Of-Service) Attack", "In a DDoS attack, a botnet floods the router with thousands of requests per second, exhausting its processing power and causing an outage.")
];

const all_unit4_questions = [...unit4_questions, ...cat1, ...cat2, ...ue, ...poss];

async function insertUnit4() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');
        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID }, { projection: { questionText: 1, category: 1 } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = all_unit4_questions.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) return false;
            return true;
        });

        if (toInsert.length > 0) {
            const res = await db.collection('questions').insertMany(toInsert);
            console.log(`Inserted ${res.insertedCount} questions for Unit 4.`);
        } else {
            console.log("No new questions for Unit 4 to insert.");
        }
    } catch (e) {
        console.error(e);
    } finally {
        await client.close();
    }
}
insertUnit4();
