/**
 * JAVA UNIT 6 - JDBC (DATABASE CONNECTIVITY) - HANDCRAFTED QUESTIONS (PART 1)
 * Based on: Unit 6 (JDBC Drivers, Connection, Statement, PreparedStatement, ResultSet)
 * Categories: QUIZ, EXERCISE, CAT 1, POSSIBLE QNS, UE
 * Difficulty: EASY, MEDIUM, HARD
 */

const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a5fc0d11b56432cd9e6f585";

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const questions = [

// ╔══════════════════════════════════╗
// ║          QUIZ - EASY             ║
// ╚══════════════════════════════════╝
Q("QUIZ","EASY",
  "What does JDBC stand for?",
  ["Java Database Connection", "Java Database Connectivity", "Java Data Base Component", "Java Data Binding Code"],
  "Java Database Connectivity",
  "JDBC is a Java API used to connect and execute queries with a database."
),
Q("QUIZ","EASY",
  "Which package contains the core JDBC classes and interfaces?",
  ["java.db", "javax.sql", "java.sql", "java.jdbc"],
  "java.sql",
  "The `java.sql` package provides the API for accessing and processing data stored in a data source (usually a relational database) using the Java programming language."
),
Q("QUIZ","EASY",
  "What is a JDBC Driver?",
  ["A hardware component", "A software component (usually a .jar file provided by the database vendor) that enables a Java application to interact with a specific database", "A method to drive database queries faster", "A built-in Java class for MySQL"],
  "A software component (usually a .jar file provided by the database vendor) that enables a Java application to interact with a specific database",
  "Each database (MySQL, Oracle, PostgreSQL) requires its own specific JDBC Driver to translate Java JDBC calls into the database's specific native protocol."
),

// ╔══════════════════════════════════╗
// ║         QUIZ - MEDIUM            ║
// ╚══════════════════════════════════╝
Q("QUIZ","MEDIUM",
  "Which interface is responsible for establishing a connection to the database?",
  ["DriverManager", "Connection", "Statement", "DataSource"],
  "Connection",
  "The `Connection` interface represents a session with a specific database. You typically obtain it by calling `DriverManager.getConnection(url, user, password)`."
),
Q("QUIZ","MEDIUM",
  "What is the difference between `Statement` and `PreparedStatement`?",
  ["They are exactly the same", "`Statement` is used for executing static SQL queries, while `PreparedStatement` is used for executing parameterized (dynamic) SQL queries and prevents SQL Injection", "`PreparedStatement` is slower", "`Statement` is only used for SELECT queries"],
  "`Statement` is used for executing static SQL queries, while `PreparedStatement` is used for executing parameterized (dynamic) SQL queries and prevents SQL Injection",
  "Because `PreparedStatement` pre-compiles the query and uses placeholders (`?`), it is faster for repeated executions and highly secure against SQL injection attacks."
),
Q("QUIZ","MEDIUM",
  "What does the `ResultSet` interface do?",
  ["It sets the results in the database", "It represents a database result set, which is generated by executing a statement that queries the database", "It closes the connection", "It handles database errors"],
  "It represents a database result set, which is generated by executing a statement that queries the database",
  "When you execute `stmt.executeQuery(\"SELECT * FROM users\")`, it returns a `ResultSet` object which you can loop through to read the rows."
),

// ╔══════════════════════════════════╗
// ║          QUIZ - HARD             ║
// ╚══════════════════════════════════╝
Q("QUIZ","HARD",
  "What does `Class.forName(\"com.mysql.cj.jdbc.Driver\")` do?",
  ["It connects to the database immediately", "It creates a new database table", "It dynamically loads and registers the specified JDBC driver class into the JVM memory at runtime", "It throws an exception"],
  "It dynamically loads and registers the specified JDBC driver class into the JVM memory at runtime",
  "Although modern JDBC (Java 6+) automatically loads drivers found in the classpath via the SPI mechanism, `Class.forName()` was traditionally required to ensure the driver class static block executed and registered itself with the DriverManager."
),
Q("QUIZ","HARD",
  "What is the difference between `execute()`, `executeQuery()`, and `executeUpdate()`?",
  ["There is no difference", "`executeQuery` is for SELECT (returns ResultSet), `executeUpdate` is for INSERT/UPDATE/DELETE (returns int), and `execute` can run any SQL and returns a boolean", "`execute` is faster", "`executeUpdate` is only for updating existing records"],
  "`executeQuery` is for SELECT (returns ResultSet), `executeUpdate` is for INSERT/UPDATE/DELETE (returns int), and `execute` can run any SQL and returns a boolean",
  "Knowing which execution method to call is crucial. Calling `executeQuery` on an `INSERT` statement will throw an `SQLException`."
),

// ╔══════════════════════════════════╗
// ║       EXERCISE - EASY            ║
// ╚══════════════════════════════════╝
Q("EXERCISE","EASY",
  "How do you move the cursor to the next row in a `ResultSet`?",
  ["rs.moveNext()", "rs.next()", "rs.forward()", "rs.step()"],
  "rs.next()",
  "The `next()` method moves the cursor to the next row. It returns `true` if a row exists, and `false` if there are no more rows, making it perfect for a `while(rs.next())` loop."
),
Q("EXERCISE","EASY",
  "Which exception is thrown if a database access error occurs or the JDBC URL is incorrect?",
  ["DatabaseException", "SQLException", "JDBCException", "ConnectionException"],
  "SQLException",
  "Almost all methods in the JDBC API throw `SQLException`, which is a checked exception and must be enclosed in a try-catch block."
),

// ╔══════════════════════════════════╗
// ║      EXERCISE - MEDIUM           ║
// ╚══════════════════════════════════╝
Q("EXERCISE","MEDIUM",
  "How do you retrieve an integer value from a column named \"age\" in a ResultSet?",
  ["rs.getInt(\"age\")", "rs.getInteger(\"age\")", "rs.getValue(\"age\")", "rs.getColumn(\"age\")"],
  "rs.getInt(\"age\")",
  "The `ResultSet` provides specific getter methods for different data types, like `getString()`, `getInt()`, and `getDouble()`. You can pass either the column index (1-based) or the column label name."
),
Q("EXERCISE","MEDIUM",
  "Why is it recommended to close the `ResultSet`, `Statement`, and `Connection` in the `finally` block?",
  ["To make the code look clean", "To ensure that database resources are released even if an exception occurs, preventing connection leaks that could crash the database server", "To save the data to the hard drive", "To compile the code"],
  "To ensure that database resources are released even if an exception occurs, preventing connection leaks that could crash the database server",
  "Database connections are heavy, limited resources. If you don't close them properly, the database will eventually run out of available connections."
),

// ╔══════════════════════════════════╗
// ║       EXERCISE - HARD            ║
// ╚══════════════════════════════════╝
Q("EXERCISE","HARD",
  "What is the purpose of `connection.setAutoCommit(false)`?",
  ["It prevents the database from closing", "It disables the default behavior where every single SQL statement is committed (saved permanently) immediately, allowing you to group multiple statements into a single Transaction", "It makes queries faster", "It encrypts the connection"],
  "It disables the default behavior where every single SQL statement is committed (saved permanently) immediately, allowing you to group multiple statements into a single Transaction",
  "If `autoCommit` is false, you must explicitly call `connection.commit()` when all queries succeed, or `connection.rollback()` if an error occurs. This is vital for banking operations (e.g., deducting from one account and adding to another)."
),
Q("EXERCISE","HARD",
  "What does `CallableStatement` do?",
  ["It calls Java methods", "It is used exclusively to execute Stored Procedures and Functions defined inside the database itself", "It prepares a statement for faster execution", "It establishes a connection over HTTP"],
  "It is used exclusively to execute Stored Procedures and Functions defined inside the database itself",
  "`CallableStatement` extends `PreparedStatement`. It allows you to pass IN parameters, register OUT parameters, and execute complex database-side logic."
),

// ╔══════════════════════════════════╗
// ║        CAT 1 - EASY              ║
// ╚══════════════════════════════════╝
Q("CAT 1","EASY",
  "When providing a JDBC URL (e.g. `jdbc:mysql://localhost:3306/school`), what does '3306' represent?",
  ["The table name", "The default Port Number where the MySQL database server is listening", "The version of MySQL", "The maximum number of rows"],
  "The default Port Number where the MySQL database server is listening",
  "The standard format is `jdbc:<subprotocol>://<host>:<port>/<databaseName>`."
),

// ╔══════════════════════════════════╗
// ║       CAT 1 - MEDIUM             ║
// ╚══════════════════════════════════╝
Q("CAT 1","MEDIUM",
  "How do you set a parameter value for a `PreparedStatement` like `SELECT * FROM users WHERE id = ?`?",
  ["pstmt.set(1, id);", "pstmt.setInt(1, id);", "pstmt.setParameter(0, id);", "pstmt.replace(\"?\", id);"],
  "pstmt.setInt(1, id);",
  "Placeholder indexes in JDBC are **1-based** (not 0-based like arrays). So you use `setInt(1, value)` for the first question mark."
),

// ╔══════════════════════════════════╗
// ║        CAT 1 - HARD              ║
// ╚══════════════════════════════════╝
Q("CAT 1","HARD",
  "What is the significance of the `ResultSetMetaData` interface?",
  ["It provides information about the database itself", "It provides information about the types and properties of the columns in a ResultSet (e.g., getting column names, column counts, and column data types dynamically)", "It speeds up the ResultSet", "It handles multimedia data"],
  "It provides information about the types and properties of the columns in a ResultSet (e.g., getting column names, column counts, and column data types dynamically)",
  "You obtain it via `rs.getMetaData()`. It is incredibly useful when you need to write generic code that can display any table dynamically (e.g., drawing an HTML table from any query)."
),

// ╔══════════════════════════════════╗
// ║     POSSIBLE QNS - EASY          ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS","EASY",
  "Which method is used to get a connection to the database?",
  ["Database.connect()", "Connection.start()", "DriverManager.getConnection(url, user, password)", "Class.connect()"],
  "DriverManager.getConnection(url, user, password)",
  "The `DriverManager` class acts as the central registry for JDBC drivers and is responsible for establishing the actual physical connection."
),

// ╔══════════════════════════════════╗
// ║    POSSIBLE QNS - MEDIUM         ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS","MEDIUM",
  "What type of architecture does JDBC use?",
  ["A single-tier architecture", "A two-tier and three-tier architecture model", "A peer-to-peer architecture", "A mesh architecture"],
  "A two-tier and three-tier architecture model",
  "Two-tier: Java App directly talks to the Database. Three-tier: Java App talks to a Middle-Tier Server (like Tomcat), which then talks to the Database."
),

// ╔══════════════════════════════════╗
// ║     POSSIBLE QNS - HARD          ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS","HARD",
  "What is SQL Injection, and how does Java prevent it?",
  ["It is a database optimization technique", "It is a hacking technique where malicious SQL commands are injected into input fields. Java prevents it by using `PreparedStatement`, which treats input as literal values, not executable code.", "It is an error in SQL syntax", "It is a network failure"],
  "It is a hacking technique where malicious SQL commands are injected into input fields. Java prevents it by using `PreparedStatement`, which treats input as literal values, not executable code.",
  "If you use `Statement` and concatenate strings (`\"SELECT * FROM users WHERE name = '\" + input + \"'\"`), a user could input `' OR 1=1 --`, granting them unauthorized access."
),

// ╔══════════════════════════════════╗
// ║          UE - EASY               ║
// ╚══════════════════════════════════╝
Q("UE","EASY",
  "What does `executeUpdate()` return?",
  ["A ResultSet containing the updated rows", "A boolean indicating success or failure", "An integer representing the number of rows affected by the SQL statement (e.g., number of rows inserted/deleted)", "Void"],
  "An integer representing the number of rows affected by the SQL statement (e.g., number of rows inserted/deleted)",
  "If you run `DELETE FROM users WHERE age < 18`, and 5 rows are deleted, `executeUpdate()` returns 5."
),

// ╔══════════════════════════════════╗
// ║         UE - MEDIUM              ║
// ╚══════════════════════════════════╝
Q("UE","MEDIUM",
  "What is the purpose of connection pooling (e.g., using HikariCP or C3P0)?",
  ["To merge multiple databases into one", "To maintain a 'pool' of ready-to-use database connections in memory, significantly improving application performance by avoiding the massive overhead of opening/closing connections repeatedly", "To encrypt the connection", "To run queries in parallel"],
  "To maintain a 'pool' of ready-to-use database connections in memory, significantly improving application performance by avoiding the massive overhead of opening/closing connections repeatedly",
  "Instead of creating a new connection for every user request, the application 'borrows' a connection from the pool, uses it, and returns it to the pool."
),

// ╔══════════════════════════════════╗
// ║          UE - HARD               ║
// ╚══════════════════════════════════╝
Q("UE","HARD",
  "What is a `Scrollable` ResultSet?",
  ["A ResultSet that can be viewed in a web browser", "A ResultSet that allows the cursor to move not just forward (`next()`), but also backward (`previous()`), to absolute positions (`absolute(row)`), or to the end (`last()`)", "A ResultSet that paginates data automatically", "A ResultSet that stores multimedia"],
  "A ResultSet that allows the cursor to move not just forward (`next()`), but also backward (`previous()`), to absolute positions (`absolute(row)`), or to the end (`last()`)",
  "By default, ResultSets are `TYPE_FORWARD_ONLY`. To make it scrollable, you must pass specific constants when creating the statement: `conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY)`."
)

];

async function insertQuestions() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');

        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID, category: { $in: ["QUIZ","EXERCISE","CAT 1","POSSIBLE QNS","UE"] } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = questions.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) {
                console.log(`⚠️  Skipping duplicate: [${q.category}] ${q.questionText.substring(0, 40)}...`);
                return false;
            }
            return true;
        });

        if (toInsert.length === 0) {
            console.log('✅ No new questions to insert (all already exist)');
            return;
        }

        const result = await db.collection('questions').insertMany(toInsert);
        console.log(`\n✅ Successfully inserted ${result.insertedCount} new Unit 6 (Part 1) questions!`);

        const summary = {};
        toInsert.forEach(q => {
            const key = `${q.category} (${q.difficultyLevel})`;
            summary[key] = (summary[key] || 0) + 1;
        });
        console.log('\n📊 Breakdown:');
        Object.entries(summary).sort().forEach(([k, v]) => console.log(`   ${k}: ${v}`));

    } finally {
        await client.close();
    }
}

insertQuestions().catch(console.error);
