/**
 * JAVA GENERAL EXPERT QUESTIONS - PART 3 (50 Questions)
 * Topics: OOP Deep Dive, Exception Edge Cases, File I/O, JVM Tuning
 * Categories: QUIZ, EXERCISE, CAT 1, POSSIBLE QNS, UE
 * Difficulty: EASY, MEDIUM, HARD
 */

const { MongoClient } = require('/run/media/careen/EE68-0880/4LAZIE/node_modules/mongodb');
const URI = "mongodb+srv://kilingepazasauti_db_user:hugongaa@cluster0.oyiolad.mongodb.net/school_db?retryWrites=true&w=majority&appName=Cluster0";
const SID = "6a5fc0d11b56432cd9e6f585";

const Q = (cat, lvl, q, opts, ans, exp) => ({
    subjectId: SID, category: cat, difficultyLevel: lvl,
    questionText: q, options: opts, correctAnswer: ans, explanation: exp,
    _class: "com.school.model.Question"
});

const questions = [

// ╔══════════════════════════════════╗
// ║          QUIZ - EASY             ║
// ╚══════════════════════════════════╝
Q("QUIZ","EASY",
  "What is Encapsulation in OOP?",
  ["Writing all code in one file", "The practice of wrapping data (variables) and code acting on the data (methods) together as a single unit, usually by making variables private and providing public getter/setter methods", "A way to compress files", "Executing code concurrently"],
  "The practice of wrapping data (variables) and code acting on the data (methods) together as a single unit, usually by making variables private and providing public getter/setter methods",
  "Encapsulation protects an object's internal state from being modified maliciously or incorrectly from the outside."
),
Q("QUIZ","EASY",
  "Which keyword allows a child class to call a method that was overridden from its parent class?",
  ["this", "parent", "super", "base"],
  "super",
  "Using `super.methodName()` bypasses the child's overridden implementation and executes the parent's original logic."
),
Q("QUIZ","EASY",
  "In Java Exception Handling, what is the 'catch' block used for?",
  ["To catch a thrown ball in GUI", "To define a block of code that handles the exception generated by the try block", "To define a block of code that always executes", "To catch compiler errors"],
  "To define a block of code that handles the exception generated by the try block",
  "If an exception occurs in the `try` block, the JVM immediately jumps to the first matching `catch` block."
),
Q("QUIZ","EASY",
  "Which Exception is thrown when an application attempts to convert a string to a numeric type, but the string does not have an appropriate format (e.g., parsing \"ABC\" to int)?",
  ["IllegalArgumentException", "NumberFormatException", "ParseException", "ArithmeticException"],
  "NumberFormatException",
  "This is a very common unchecked exception when dealing with user input via `Integer.parseInt()`."
),
Q("QUIZ","EASY",
  "What is a 'Checked Exception' in Java?",
  ["An exception that occurs at runtime", "An exception that the compiler forces you to handle (using try-catch or throws keyword) before it allows the code to compile", "An exception related to checking bank accounts", "An exception that never crashes the program"],
  "An exception that the compiler forces you to handle (using try-catch or throws keyword) before it allows the code to compile",
  "Examples include `IOException` and `SQLException`. Unchecked exceptions (like `NullPointerException`) do not require forced handling."
),

// ╔══════════════════════════════════╗
// ║         QUIZ - MEDIUM            ║
// ╚══════════════════════════════════╝
Q("QUIZ","MEDIUM",
  "What is 'Polymorphism' in Java?",
  ["The ability to run multiple programs at once", "The ability of an object to take on many forms. The most common use in OOP occurs when a parent class reference is used to refer to a child class object, allowing dynamic method resolution.", "A way to parse XML", "A garbage collection algorithm"],
  "The ability of an object to take on many forms. The most common use in OOP occurs when a parent class reference is used to refer to a child class object, allowing dynamic method resolution.",
  "E.g., `Animal a = new Dog(); a.makeSound();` will run the Dog's overridden sound, not the Animal's."
),
Q("QUIZ","MEDIUM",
  "Can you have multiple `catch` blocks for a single `try` block?",
  ["No, only one catch block is allowed", "Yes, but they must all catch the exact same Exception", "Yes, you can have multiple catch blocks, but you must catch the most specific exceptions (child classes) FIRST, and the most general exceptions (parent classes like Exception) LAST", "Yes, in any order"],
  "Yes, you can have multiple catch blocks, but you must catch the most specific exceptions (child classes) FIRST, and the most general exceptions (parent classes like Exception) LAST",
  "If you put `catch (Exception e)` first, it will catch everything, making the specific catch blocks unreachable (causing a compile error)."
),
Q("QUIZ","MEDIUM",
  "What does the `throws` keyword do in a method signature?",
  ["It actually throws the exception to crash the program", "It declares that the method might throw one or more exceptions, delegating the responsibility of handling those exceptions to whatever code calls this method", "It ignores the exception", "It catches the exception"],
  "It declares that the method might throw one or more exceptions, delegating the responsibility of handling those exceptions to whatever code calls this method",
  "E.g., `public void readFile() throws IOException { ... }` means the caller MUST handle the IOException."
),
Q("QUIZ","MEDIUM",
  "In Java File I/O, what is the primary difference between a `Reader` (like FileReader) and an `InputStream` (like FileInputStream)?",
  ["There is no difference", "`InputStream` reads raw 8-bit bytes (good for images/audio). `Reader` reads 16-bit characters (good for text files), handling character encoding automatically.", "`Reader` is faster", "`InputStream` is deprecated"],
  "`InputStream` reads raw 8-bit bytes (good for images/audio). `Reader` reads 16-bit characters (good for text files), handling character encoding automatically.",
  "Never use a raw `FileInputStream` to read a text file, because multi-byte characters (like emojis or foreign languages) might get corrupted."
),
Q("QUIZ","MEDIUM",
  "What is a 'Memory Dump' (Heap Dump) in Java?",
  ["Deleting all memory", "A snapshot of all the objects that are currently alive in the JVM's Heap memory at a specific moment in time. It is used heavily by developers to analyze and fix Memory Leaks.", "A garbage collection phase", "A database backup"],
  "A snapshot of all the objects that are currently alive in the JVM's Heap memory at a specific moment in time. It is used heavily by developers to analyze and fix Memory Leaks.",
  "You can generate one using the `jmap` tool or by passing the `-XX:+HeapDumpOnOutOfMemoryError` JVM flag."
),

// ╔══════════════════════════════════╗
// ║          QUIZ - HARD             ║
// ╚══════════════════════════════════╝
Q("QUIZ","HARD",
  "In OOP, what is 'Composition over Inheritance'?",
  ["Inheritance is always better", "A design principle stating it is better to compose a class by including objects of other classes (HAS-A relationship) rather than extending a parent class (IS-A relationship), leading to more flexible and loosely coupled code", "A design pattern for GUI", "A way to compile code faster"],
  "A design principle stating it is better to compose a class by including objects of other classes (HAS-A relationship) rather than extending a parent class (IS-A relationship), leading to more flexible and loosely coupled code",
  "Deep inheritance hierarchies (e.g., A extends B extends C) become rigid and fragile. Composition is much easier to maintain."
),
Q("QUIZ","HARD",
  "What happens if a static block throws a RuntimeException?",
  ["The program ignores it", "The JVM throws a `java.lang.ExceptionInInitializerError` and the class completely fails to load, crashing the thread attempting to use it", "The GC deletes the class", "The block runs again"],
  "The JVM throws a `java.lang.ExceptionInInitializerError` and the class completely fails to load, crashing the thread attempting to use it",
  "Because static blocks run during class loading, an unhandled exception here is a fatal issue for the class."
),
Q("QUIZ","HARD",
  "What is JVM 'Escape Analysis'?",
  ["A security firewall", "An advanced JIT compiler optimization where the JVM analyzes if an object created in a method ever 'escapes' the method (e.g., returned or assigned to a global variable). If it doesn't escape, the JVM may allocate it on the Stack instead of the Heap.", "A garbage collection algorithm", "A way to exit a loop"],
  "An advanced JIT compiler optimization where the JVM analyzes if an object created in a method ever 'escapes' the method (e.g., returned or assigned to a global variable). If it doesn't escape, the JVM may allocate it on the Stack instead of the Heap.",
  "This is a massive performance boost because objects allocated on the Stack are destroyed instantly when the method ends, completely bypassing the Garbage Collector."
),
Q("QUIZ","HARD",
  "Trace the execution flow of this multi-catch (Java 7+):\n`catch (IOException | SQLException e) { e = new IOException(); }`",
  ["It compiles perfectly", "It causes a compile error because the exception parameter `e` in a multi-catch block is implicitly `final` and cannot be reassigned", "It throws a RuntimeException", "It runs forever"],
  "It causes a compile error because the exception parameter `e` in a multi-catch block is implicitly `final` and cannot be reassigned",
  "To prevent massive logical bugs, Java enforces immutability on the exception variable when combining multiple exceptions in a single block."
),
Q("QUIZ","HARD",
  "What is the difference between `System.exit(0)` and `Runtime.getRuntime().halt(0)`?",
  ["No difference", "`System.exit()` initiates a graceful shutdown, running Shutdown Hooks and finalizing objects. `halt()` forcefully and immediately kills the JVM without running any cleanup code.", "`halt()` pauses the JVM", "`System.exit()` restarts the JVM"],
  "`System.exit()` initiates a graceful shutdown, running Shutdown Hooks and finalizing objects. `halt()` forcefully and immediately kills the JVM without running any cleanup code.",
  "`halt()` should almost never be used unless the JVM is in a catastrophic, deadlocked state."
),

// ╔══════════════════════════════════╗
// ║       EXERCISE - EASY            ║
// ╚══════════════════════════════════╝
Q("EXERCISE","EASY",
  "What is the difference between a class and an interface?",
  ["No difference", "A class describes the attributes and behaviors of an object. An interface is a contract that specifies WHAT methods a class must implement, but not HOW to implement them.", "An interface cannot have variables", "A class is faster"],
  "A class describes the attributes and behaviors of an object. An interface is a contract that specifies WHAT methods a class must implement, but not HOW to implement them.",
  "Interfaces are the backbone of Java API design, allowing different classes to be treated identically based on the contract they fulfill."
),
Q("EXERCISE","EASY",
  "Which block is ALWAYS executed whether an exception is thrown or not?",
  ["try", "catch", "finally", "throws"],
  "finally",
  "The `finally` block is strictly used for cleaning up resources, like closing Database connections or File streams, ensuring they are closed even if an error crashes the logic."
),
Q("EXERCISE","EASY",
  "What is the default layout manager for a `JPanel` in Swing?",
  ["BorderLayout", "FlowLayout", "GridLayout", "GridBagLayout"],
  "FlowLayout",
  "It simply places components next to each other in a row, wrapping to the next line if it runs out of space."
),

// ╔══════════════════════════════════╗
// ║      EXERCISE - MEDIUM           ║
// ╚══════════════════════════════════╝
Q("EXERCISE","MEDIUM",
  "In OOP, what is 'Method Overriding'?",
  ["Writing multiple methods with the same name", "When a child class provides a specific, custom implementation for a method that is already defined in its parent class (Must have the exact same name, return type, and parameters)", "When a method crashes", "When a method is deleted"],
  "When a child class provides a specific, custom implementation for a method that is already defined in its parent class (Must have the exact same name, return type, and parameters)",
  "This is the foundation of Runtime Polymorphism."
),
Q("EXERCISE","MEDIUM",
  "What is a 'Custom Exception' in Java?",
  ["A built-in exception", "A user-defined exception class created by extending `Exception` (for checked) or `RuntimeException` (for unchecked) to represent specific business logic errors (e.g., `InsufficientFundsException`)", "An exception that cannot be caught", "An exception that fixes itself"],
  "A user-defined exception class created by extending `Exception` (for checked) or `RuntimeException` (for unchecked) to represent specific business logic errors (e.g., `InsufficientFundsException`)",
  "Using custom exceptions makes your logs and error handling vastly more readable."
),
Q("EXERCISE","MEDIUM",
  "Why is a `StringBuilder` preferred over concatenating Strings with the `+` operator in a loop?",
  ["It is more secure", "Because Strings are immutable. Using `+` in a loop creates a brand new String object in memory for EVERY iteration, causing massive memory waste. `StringBuilder` modifies a single array in place.", "It prevents exceptions", "It can hold more characters"],
  "Because Strings are immutable. Using `+` in a loop creates a brand new String object in memory for EVERY iteration, causing massive memory waste. `StringBuilder` modifies a single array in place.",
  "Always use `StringBuilder` (or `StringBuffer` if thread-safety is required) when manipulating strings heavily."
),

// ╔══════════════════════════════════╗
// ║       EXERCISE - HARD            ║
// ╚══════════════════════════════════╝
Q("EXERCISE","HARD",
  "Trace the output:\n<pre><code>public int test() {\n  try { return 10; }\n  finally { System.out.print(\"F\"); }\n}\nSystem.out.print(test());</code></pre>",
  ["10F", "F10", "10", "F"],
  "F10",
  "The `try` block resolves the return value to 10, BUT before the method actually hands the value back to the caller, the `finally` block must execute, printing 'F'. Then the caller prints '10'."
),
Q("EXERCISE","HARD",
  "What is the JVM flag `-Xmx` used for?",
  ["To set the minimum heap size", "To set the maximum memory size that the JVM Heap is allowed to use. If the program requires more, it throws an OutOfMemoryError.", "To set the thread stack size", "To enable garbage collection"],
  "To set the maximum memory size that the JVM Heap is allowed to use. If the program requires more, it throws an OutOfMemoryError.",
  "E.g., `java -Xmx2G MyApp` allows the JVM to consume up to 2 Gigabytes of RAM."
),

// ╔══════════════════════════════════╗
// ║        CAT 1 - EASY              ║
// ╚══════════════════════════════════╝
Q("CAT 1","EASY",
  "What is the 'this' keyword used for?",
  ["To refer to the parent class", "To refer to the current instance (object) of the class in which it appears, commonly used to distinguish between instance variables and local parameters with the same name", "To refer to a static method", "To refer to the main thread"],
  "To refer to the current instance (object) of the class in which it appears, commonly used to distinguish between instance variables and local parameters with the same name",
  "E.g., `this.name = name;` assigns the local parameter `name` to the object's instance variable `name`."
),
Q("CAT 1","EASY",
  "Which interface MUST a class implement to be written to a file using an `ObjectOutputStream`?",
  ["FileWriteable", "Serializable", "Cloneable", "Transferable"],
  "Serializable",
  "If the class does not implement `Serializable`, a `NotSerializableException` is thrown."
),

// ╔══════════════════════════════════╗
// ║       CAT 1 - MEDIUM             ║
// ╚══════════════════════════════════╝
Q("CAT 1","MEDIUM",
  "Can a subclass override a method and change its access modifier?",
  ["No, the access modifier must remain exactly the same", "Yes, but it can only make the access modifier MORE restrictive (e.g., public to protected)", "Yes, but it can only make the access modifier LESS restrictive (e.g., protected to public)", "Yes, to anything"],
  "Yes, but it can only make the access modifier LESS restrictive (e.g., protected to public)",
  "You cannot hide a method that was public in the parent. But you can take a protected parent method and expose it publicly in the child."
),
Q("CAT 1","MEDIUM",
  "What is a 'Thread Dump'?",
  ["Deleting all threads", "A diagnostic snapshot of the exact state of all threads running in the JVM. It shows their stack traces and what locks they are waiting for, crucial for debugging Deadlocks.", "A memory leak", "A database backup"],
  "A diagnostic snapshot of the exact state of all threads running in the JVM. It shows their stack traces and what locks they are waiting for, crucial for debugging Deadlocks.",
  "You can generate one using `jstack` or by sending a `SIGQUIT` signal to the JVM process."
),

// ╔══════════════════════════════════╗
// ║        CAT 1 - HARD              ║
// ╚══════════════════════════════════╝
Q("CAT 1","HARD",
  "What is the difference between `ClassNotFoundException` and `NoClassDefFoundError`?",
  ["They are the same", "ClassNotFoundException is checked (thrown by Class.forName). NoClassDefFoundError is a fatal Error thrown by the JVM when a class that was available during compilation is missing during runtime.", "One is for Web, one is for Desktop", "One is for Mac, one is for Windows"],
  "ClassNotFoundException is checked (thrown by Class.forName). NoClassDefFoundError is a fatal Error thrown by the JVM when a class that was available during compilation is missing during runtime.",
  "NoClassDefFoundError almost always points to a broken classpath or missing JAR file on the production server."
),
Q("CAT 1","HARD",
  "What is 'Lock Coarsening' in the JIT Compiler?",
  ["Making locks stronger", "An optimization where the JIT compiler merges multiple adjacent synchronized blocks that lock on the exact same object into a single, larger synchronized block to reduce the heavy overhead of repeatedly acquiring and releasing the lock", "A way to cause a deadlock", "A way to unlock databases"],
  "An optimization where the JIT compiler merges multiple adjacent synchronized blocks that lock on the exact same object into a single, larger synchronized block to reduce the heavy overhead of repeatedly acquiring and releasing the lock",
  "The JVM is incredibly smart at optimizing poorly written concurrency code."
),

// ╔══════════════════════════════════╗
// ║     POSSIBLE QNS - EASY          ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS","EASY",
  "Can you instantiate an Abstract Class?",
  ["Yes, normally", "No, abstract classes cannot be instantiated with `new`. They must be extended by a concrete subclass.", "Only inside a static block", "Only using Reflection"],
  "No, abstract classes cannot be instantiated with `new`. They must be extended by a concrete subclass.",
  "Abstract classes act as templates. E.g., You can't just create an `Animal`, you must create a `Dog` or `Cat`."
),
Q("POSSIBLE QNS","EASY",
  "Which stream class is best for reading a raw image file (.png or .jpg)?",
  ["FileReader", "BufferedReader", "FileInputStream", "ObjectInputStream"],
  "FileInputStream",
  "Image files are binary data (bytes), not characters. Using a `Reader` class will corrupt the file."
),

// ╔══════════════════════════════════╗
// ║    POSSIBLE QNS - MEDIUM         ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS","MEDIUM",
  "What is the purpose of the `throw` keyword (without an 's')?",
  ["To declare an exception", "To physically trigger and 'throw' a specific exception object explicitly within a method (e.g., `throw new IllegalArgumentException();`)", "To ignore an exception", "To catch an exception"],
  "To physically trigger and 'throw' a specific exception object explicitly within a method (e.g., `throw new IllegalArgumentException();`)",
  "`throws` is used in the method signature. `throw` is used inside the method body."
),
Q("POSSIBLE QNS","MEDIUM",
  "How does a `BufferedReader` improve performance when reading a file?",
  ["It reads the file faster from the hard drive", "It reads large chunks of data from the disk into a memory buffer at once, reducing the number of expensive physical disk reads compared to reading byte-by-byte", "It compresses the file", "It decrypts the file"],
  "It reads large chunks of data from the disk into a memory buffer at once, reducing the number of expensive physical disk reads compared to reading byte-by-byte",
  "Always wrap your `FileReader` in a `BufferedReader`."
),

// ╔══════════════════════════════════╗
// ║     POSSIBLE QNS - HARD          ║
// ╚══════════════════════════════════╝
Q("POSSIBLE QNS","HARD",
  "Trace the code:\n<pre><code>class A { void msg(){System.out.print(\"A\");} }\nclass B extends A { void msg(){System.out.print(\"B\");} }\nA obj = new B();\nobj.msg();</code></pre>",
  ["A", "B", "Compile Error", "Exception"],
  "B",
  "This is Runtime Polymorphism. Even though the reference is type `A`, the actual object in memory is `B`. The JVM dynamically binds the method call to `B`'s overridden `msg()` method at runtime."
),
Q("POSSIBLE QNS","HARD",
  "What is the JVM flag `-XX:+UseG1GC` used for?",
  ["To allocate 1 GB of RAM", "To explicitly instruct the JVM to use the Garbage-First (G1) Garbage Collector", "To enable a graphical user interface", "To clear the cache"],
  "To explicitly instruct the JVM to use the Garbage-First (G1) Garbage Collector",
  "G1GC is designed for multi-processor machines with large memory space, prioritizing low pause times."
),

// ╔══════════════════════════════════╗
// ║          UE - EASY               ║
// ╚══════════════════════════════════╝
Q("UE","EASY",
  "What is an 'IDE'?",
  ["Integrated Data Environment", "Integrated Development Environment (like IntelliJ IDEA, Eclipse, or NetBeans), which provides a code editor, compiler, and debugger in a single GUI", "Internal Development Engine", "Interface Design Element"],
  "Integrated Development Environment (like IntelliJ IDEA, Eclipse, or NetBeans), which provides a code editor, compiler, and debugger in a single GUI",
  "IDEs drastically improve developer productivity."
),
Q("UE","EASY",
  "What is a 'Jar' file in Java?",
  ["Java Application Resource", "Java ARchive - a file format based on ZIP that aggregates many Java class files and associated metadata/resources into a single file for distribution", "Java Runtime Engine", "Java Array Reference"],
  "Java ARchive - a file format based on ZIP that aggregates many Java class files and associated metadata/resources into a single file for distribution",
  "It is the standard executable distribution format for Java."
),

// ╔══════════════════════════════════╗
// ║         UE - MEDIUM              ║
// ╚══════════════════════════════════╝
Q("UE","MEDIUM",
  "What is the 'Try-With-Resources' statement (Java 7+)?",
  ["A way to try executing a resource", "A try statement that declares one or more resources (like a File Stream or DB Connection). It ensures that each resource is automatically closed at the end of the statement, eliminating the need for a `finally` block.", "A try block that throws exceptions", "A try block for networking"],
  "A try statement that declares one or more resources (like a File Stream or DB Connection). It ensures that each resource is automatically closed at the end of the statement, eliminating the need for a `finally` block.",
  "The resource must implement the `AutoCloseable` interface. E.g., `try (Scanner s = new Scanner(file)) { ... }`."
),
Q("UE","MEDIUM",
  "In JDBC, what is `PreparedStatement` primarily used for besides performance?",
  ["To read text files", "To prevent SQL Injection attacks. It automatically escapes special characters provided in user inputs, ensuring they are treated as data, not as executable SQL commands.", "To format SQL nicely", "To connect to MongoDB"],
  "To prevent SQL Injection attacks. It automatically escapes special characters provided in user inputs, ensuring they are treated as data, not as executable SQL commands.",
  "Never use `Statement` to concatenate user input directly into a SQL string. Always use `PreparedStatement`."
),

// ╔══════════════════════════════════╗
// ║          UE - HARD               ║
// ╚══════════════════════════════════╝
Q("UE","HARD",
  "What happens if you don't override `hashCode()` when you override `equals()`?",
  ["Compile Error", "Objects that are conceptually 'equal' will have different hash codes. If these objects are placed in a `HashMap` or `HashSet`, they will be placed in different buckets, and the collection will fail to find them later, causing massive bugs.", "The JVM will fix it automatically", "The program will run faster"],
  "Objects that are conceptually 'equal' will have different hash codes. If these objects are placed in a `HashMap` or `HashSet`, they will be placed in different buckets, and the collection will fail to find them later, causing massive bugs.",
  "This is a fundamental rule in Java: If two objects are equal according to `equals()`, they MUST have the exact same integer returned by `hashCode()`."
),
Q("UE","HARD",
  "What is the difference between Heap Memory and Stack Memory?",
  ["They are the same", "Heap memory is used for dynamic allocation of Objects and JRE classes, shared among all threads. Stack memory is thread-specific and stores local primitive variables and method call frames.", "Stack is for Objects, Heap is for primitives", "Heap is on the hard drive, Stack is in RAM"],
  "Heap memory is used for dynamic allocation of Objects and JRE classes, shared among all threads. Stack memory is thread-specific and stores local primitive variables and method call frames.",
  "Stack memory is fast and automatically cleared when a method ends. Heap memory requires the Garbage Collector."
)

];

async function insertQuestions() {
    const client = new MongoClient(URI);
    try {
        await client.connect();
        const db = client.db('school_db');

        const existingTexts = new Set();
        const existing = await db.collection('questions')
            .find({ subjectId: SID, category: { $in: ["QUIZ","EXERCISE","CAT 1","POSSIBLE QNS","UE"] } })
            .toArray();
        existing.forEach(q => existingTexts.add(`${q.category}|${q.questionText.substring(0, 50)}`));

        const toInsert = questions.filter(q => {
            const key = `${q.category}|${q.questionText.substring(0, 50)}`;
            if (existingTexts.has(key)) {
                console.log(`⚠️  Skipping duplicate: [${q.category}] ${q.questionText.substring(0, 40)}...`);
                return false;
            }
            return true;
        });

        if (toInsert.length === 0) {
            console.log('✅ No new questions to insert (all already exist)');
            return;
        }

        const result = await db.collection('questions').insertMany(toInsert);
        console.log(`\n✅ Successfully inserted ${result.insertedCount} new GENERAL EXPERT (Part 3) questions!`);

        const summary = {};
        toInsert.forEach(q => {
            const key = `${q.category} (${q.difficultyLevel})`;
            summary[key] = (summary[key] || 0) + 1;
        });
        console.log('\n📊 Breakdown:');
        Object.entries(summary).sort().forEach(([k, v]) => console.log(`   ${k}: ${v}`));

    } finally {
        await client.close();
    }
}

insertQuestions().catch(console.error);
